/**
 * Liens « couvre ce risque » des contrôles-types et des missions d'audit types du catalogue.
 * Servent à l'entrée « par risque » du catalogue de contrôles et des modèles de mission : un
 * contrôle importé est rattaché au risque correspondant SEULEMENT si l'organisation l'a déjà dans
 * son registre (même clé de catalogue) — jamais de risque créé implicitement.
 */
import { EXT_CONTROL_RISKS, EXT_AUDIT_RISKS } from './sector-packs-ext'

export const CONTROL_RISKS: Record<string, string[]> = {
  ...EXT_CONTROL_RISKS,
  // Pack banque / assurance / mutuelle (1.9)
  'finance.control.control-plan': ['core.risk.process-error', 'core.risk.obligation-missed'],
  'finance.control.delegations': ['core.risk.segregation', 'core.risk.internal-fraud'],
  'finance.control.incident-escalation': ['core.risk.obligation-missed'],
  'finance.control.credit-sample': ['finance.risk.credit-data', 'core.risk.process-error'],
  'finance.control.credit-limits': ['finance.risk.credit-data'],
  'finance.control.default-classification': ['finance.risk.credit-data', 'core.risk.financial-reporting'],
  'finance.control.collateral-valuation': ['finance.risk.credit-data'],
  'finance.control.market-limits': ['core.risk.internal-fraud', 'core.risk.process-error'],
  'finance.control.valuation-check': ['core.risk.financial-reporting'],
  'finance.control.liquidity-ratios': ['core.risk.financial-reporting', 'core.risk.obligation-missed'],
  'finance.control.payment-four-eyes': ['finance.risk.payment-routing', 'core.risk.payment-fraud', 'core.risk.internal-fraud'],
  'finance.control.fraud-monitoring': ['core.risk.payment-fraud', 'finance.risk.account-takeover', 'finance.risk.card-data'],
  'finance.control.strong-authentication': ['finance.risk.account-takeover'],
  'finance.control.kyc-sample': ['finance.risk.aml'],
  'finance.control.aml-alerts': ['finance.risk.aml'],
  'finance.control.str-quality': ['finance.risk.aml'],
  'finance.control.asset-freeze': ['finance.risk.sanction-screening'],
  'finance.control.suitability': ['core.risk.mis-selling'],
  'finance.control.complaints': ['core.risk.mis-selling', 'core.risk.obligation-missed'],
  'finance.control.marketing-review': ['core.risk.mis-selling'],
  'finance.control.regulatory-reporting': ['core.risk.financial-reporting', 'core.risk.obligation-missed'],
  'finance.control.suspense-accounts': ['finance.risk.reconciliation', 'core.risk.financial-reporting'],
  'finance.control.ict-register': ['core.risk.supplier-contract', 'core.risk.supplier-outage'],
  'finance.control.critical-providers': ['core.risk.supplier-outage', 'finance.risk.channel-outage'],
  'finance.control.resilience-testing': ['core.risk.continuity-plan', 'core.risk.it-outage'],
  'finance.control.incident-reporting-drill': ['core.risk.obligation-missed', 'core.risk.it-outage'],
  'assurance.control.key-functions': ['core.risk.obligation-missed', 'core.risk.segregation'],
  'assurance.control.policies-review': ['core.risk.obligation-missed'],
  'assurance.control.fit-proper': ['core.risk.obligation-missed', 'core.risk.key-person'],
  'assurance.control.governance-escalation': ['core.risk.obligation-missed'],
  'assurance.control.orsa-process': ['assurance.risk.reserve', 'core.risk.obligation-missed'],
  'assurance.control.solvency-coverage': ['assurance.risk.reserve'],
  'assurance.control.risk-appetite': ['assurance.risk.pricing', 'assurance.risk.reserve'],
  'assurance.control.underwriting-delegations': ['assurance.risk.pricing', 'core.risk.segregation'],
  'assurance.control.new-business-sample': ['assurance.risk.pricing', 'core.risk.process-error'],
  'assurance.control.reserve-backtesting': ['assurance.risk.reserve'],
  'assurance.control.actuarial-data-quality': ['assurance.risk.reserve', 'assurance.risk.broker-data'],
  'assurance.control.claims-delays': ['assurance.risk.claim-delay'],
  'assurance.control.claims-segregation': ['assurance.risk.claim-fraud', 'core.risk.segregation'],
  'assurance.control.delegated-managers': ['core.risk.supplier-outage', 'assurance.risk.claim-delay'],
  'assurance.control.advice-sample': ['core.risk.mis-selling'],
  'assurance.control.intermediaries': ['core.risk.mis-selling', 'assurance.risk.broker-data'],
  'assurance.control.product-governance': ['core.risk.mis-selling'],
  'assurance.control.complaints': ['core.risk.mis-selling', 'core.risk.obligation-missed'],
  'assurance.control.investment-limits': ['core.risk.obligation-missed', 'core.risk.financial-reporting'],
  'assurance.control.reinsurance': ['assurance.risk.reserve'],
  'assurance.control.aml-life': ['core.risk.obligation-missed'],
  'assurance.control.asset-freeze': ['core.risk.obligation-missed'],
  'assurance.control.member-contributions': ['core.risk.process-error', 'core.risk.financial-reporting'],
  'assurance.control.statutes-assembly': ['core.risk.obligation-missed'],
  'assurance.control.benefits-sample': ['assurance.risk.claim-fraud', 'core.risk.process-error'],
  'assurance.control.ict-register': ['core.risk.supplier-contract', 'core.risk.supplier-outage'],
  'assurance.control.critical-providers': ['core.risk.supplier-outage'],
  'assurance.control.resilience-testing': ['core.risk.continuity-plan', 'core.risk.it-outage'],
  'assurance.control.incident-reporting-drill': ['core.risk.obligation-missed', 'core.risk.it-outage'],
  'core.control.access-review': ['core.risk.privileged-access', 'core.risk.leavers', 'core.risk.segregation'],
  'core.control.privileged-review': ['core.risk.privileged-access'],
  'core.control.leavers': ['core.risk.leavers'],
  'core.control.backup-restore': ['core.risk.backup-failure', 'core.risk.ransomware'],
  'core.control.patch-follow-up': ['core.risk.unpatched'],
  'core.control.security-alerts': ['core.risk.detection-gap'],
  'core.control.payment-validation': ['core.risk.payment-fraud', 'core.risk.internal-fraud'],
  'core.control.supplier-clauses': ['core.risk.supplier-contract'],
  'core.control.supplier-review': ['core.risk.supplier-outage'],
  'finance.control.reconciliation': ['finance.risk.reconciliation'],
  'finance.control.sanctions-alerts': ['finance.risk.sanction-screening'],
  'assurance.control.claims-sample': ['assurance.risk.claim-fraud'],
  'assurance.control.pricing-change': ['assurance.risk.pricing'],
  'energie.control.ot-access': ['energie.risk.scada', 'energie.risk.contractor-access'],
  'energie.control.field-permits': ['energie.risk.field-safety'],
  'transport.control.maintenance-due': ['transport.risk.maintenance'],
  'transport.control.cycle-count': ['transport.risk.stock-error'],
  'telecom.control.sim-swap': ['telecom.risk.sim-swap'],
  'telecom.control.revenue-assurance': ['telecom.risk.revenue-leak'],
  'sante.control.record-access': ['sante.risk.patient-data'],
  'sante.control.specimen-identity': ['sante.risk.result-error'],
  'industrie.control.remote-access': ['industrie.risk.remote-maintenance'],
  'industrie.control.batch-release': ['industrie.risk.quality'],
  'public.control.grant-sample': ['public.risk.grant-error'],
  'public.control.open-data-review': ['public.risk.open-data'],
  'commerce.control.price-changes': ['commerce.risk.pricing'],
  'commerce.control.inventory-count': ['commerce.risk.stock'],
  'saas.control.release-review': ['saas.risk.release'],
  'saas.control.support-access': ['saas.risk.support-access'],
  'services.control.engagement-acceptance': ['services.risk.scope'],
  'services.control.unbilled-work': ['services.risk.billing'],
}

export const AUDIT_RISKS: Record<string, string[]> = {
  ...EXT_AUDIT_RISKS,
  'core.audit.access': ['core.risk.privileged-access', 'core.risk.leavers'],
  'core.audit.backup': ['core.risk.backup-failure', 'core.risk.ransomware'],
  'core.audit.suppliers': ['core.risk.supplier-outage', 'core.risk.supplier-contract'],
  'core.audit.payments': ['core.risk.payment-fraud'],
  'finance.audit.payment-chain': ['finance.risk.payment-routing', 'finance.risk.reconciliation'],
  'assurance.audit.claims': ['assurance.risk.claim-fraud', 'assurance.risk.claim-delay'],
  'energie.audit.operations': ['energie.risk.scada', 'energie.risk.outage'],
  'transport.audit.continuity': ['transport.risk.planning-outage', 'transport.risk.delay'],
  'telecom.audit.network-change': ['telecom.risk.config-change', 'telecom.risk.outage'],
  'sante.audit.records': ['sante.risk.patient-data', 'sante.risk.consent'],
  'public.audit.grants': ['public.risk.grant-error'],
  'saas.audit.change': ['saas.risk.release', 'saas.risk.secrets'],
  'industrie.audit.ot': ['industrie.risk.ot-stop', 'industrie.risk.remote-maintenance'],
  'commerce.audit.online-sales': ['commerce.risk.customer-data', 'commerce.risk.pricing'],
  'services.audit.confidentiality': ['services.risk.confidentiality', 'services.risk.client-access'],
}
