/**
 * Convergence de l'ancien socle du registre (`registre-catalogue.ts`, 16 risques Bâle en français,
 * retiré) avec le catalogue de suggestions (catalogue 1.8) :
 * - les situations que le catalogue ne couvrait pas sont reprises ici, formulées en événements,
 *   traduites ×5 et accompagnées de la description de l'ancien socle ;
 * - chaque risque du catalogue porte sa catégorie bâloise (7 catégories d'événements de risque
 *   opérationnel, cf. taxonomie.ts) : à l'import, elle ne s'applique que si la taxonomie de
 *   l'organisation contient ce code.
 * L'ancien « propriétaire » suggéré (fonction) n'est pas repris : un propriétaire n'est jamais présumé.
 */
import type { CatalogueItem, Localized } from './sector-suggestions'

const l = (fr: string, en: string, de: string, es: string, it: string): Localized => ({ fr, en, de, es, it })
const r = (key: string, sector: CatalogueItem['sector'], title: Localized, processKey: string, description: Localized): CatalogueItem =>
  ({ key, sector, kind: 'RISK', title, processKey, description })

export const MERGED_REGISTRY_RISKS: CatalogueItem[] = [
  r('core.risk.internal-fraud', 'TRANSVERSAL', l('Un collaborateur détourne des fonds ou des actifs', 'An employee misappropriates funds or assets', 'Ein Mitarbeiter veruntreut Gelder oder Vermögenswerte', 'Un empleado se apropia indebidamente de fondos o activos', 'Un dipendente sottrae fondi o beni'), 'core.process.finance',
    l('Un collaborateur détourne des fonds, des biens ou des données à son profit (abus de position, falsification, collusion) en contournant les contrôles internes.', 'An employee diverts funds, goods or data for personal gain (abuse of position, falsification, collusion) by circumventing internal controls.', 'Ein Mitarbeiter zweigt unter Umgehung interner Kontrollen Gelder, Güter oder Daten zu seinem Vorteil ab (Amtsmissbrauch, Fälschung, Absprache).', 'Un empleado desvía fondos, bienes o datos en su propio beneficio (abuso de posición, falsificación, colusión) eludiendo los controles internos.', 'Un dipendente sottrae fondi, beni o dati a proprio vantaggio (abuso di posizione, falsificazione, collusione) aggirando i controlli interni.')),
  r('core.risk.segregation', 'TRANSVERSAL', l('Une même personne cumule des tâches incompatibles', 'One person holds incompatible duties', 'Eine Person vereint unvereinbare Aufgaben', 'Una misma persona acumula tareas incompatibles', 'Una stessa persona cumula compiti incompatibili'), 'core.process.govern.compliance',
    l('Des droits étendus ou une séparation des tâches insuffisante permettent de réaliser ou de masquer des opérations irrégulières.', 'Broad rights or insufficient segregation of duties make it possible to carry out or conceal irregular transactions.', 'Weitreichende Rechte oder eine unzureichende Funktionstrennung ermöglichen es, unregelmäßige Vorgänge durchzuführen oder zu verschleiern.', 'Derechos amplios o una separación de funciones insuficiente permiten realizar u ocultar operaciones irregulares.', 'Diritti estesi o una separazione dei compiti insufficiente consentono di effettuare o nascondere operazioni irregolari.')),
  r('core.risk.workplace', 'TRANSVERSAL', l('Un manquement au droit du travail ou à la santé-sécurité expose l’entreprise', 'A breach of employment or health-and-safety rules exposes the company', 'Ein Verstoß gegen Arbeitsrecht oder Arbeitsschutz belastet das Unternehmen', 'Un incumplimiento del derecho laboral o de la seguridad y salud expone a la empresa', 'Una violazione del diritto del lavoro o della salute e sicurezza espone l’azienda'), 'core.process.people',
    l('Manquement aux obligations sociales (durée du travail, sécurité, harcèlement) exposant à un contentieux ou à une sanction administrative.', 'Failure to meet employment obligations (working time, safety, harassment) leading to litigation or an administrative penalty.', 'Verletzung arbeitsrechtlicher Pflichten (Arbeitszeit, Sicherheit, Belästigung), die zu Rechtsstreitigkeiten oder Verwaltungssanktionen führt.', 'Incumplimiento de las obligaciones laborales (jornada, seguridad, acoso) que expone a litigios o a una sanción administrativa.', 'Mancato rispetto degli obblighi in materia di lavoro (orario, sicurezza, molestie) che espone a contenziosi o a una sanzione amministrativa.')),
  r('core.risk.personal-data', 'TRANSVERSAL', l('Des données personnelles sont traitées sans base légale ou conservées trop longtemps', 'Personal data is processed without a legal basis or kept too long', 'Personenbezogene Daten werden ohne Rechtsgrundlage verarbeitet oder zu lange gespeichert', 'Se tratan datos personales sin base jurídica o se conservan demasiado tiempo', 'Dati personali sono trattati senza base giuridica o conservati troppo a lungo'), 'core.process.govern.compliance',
    l('Traitement de données personnelles non conforme (base légale, information, sécurité, durée de conservation) exposant à une violation et à une sanction.', 'Non-compliant processing of personal data (legal basis, information, security, retention period) leading to a breach and a penalty.', 'Nicht konforme Verarbeitung personenbezogener Daten (Rechtsgrundlage, Information, Sicherheit, Speicherdauer), die zu einer Verletzung und einer Sanktion führt.', 'Tratamiento de datos personales no conforme (base jurídica, información, seguridad, plazo de conservación) que expone a una violación y a una sanción.', 'Trattamento non conforme di dati personali (base giuridica, informativa, sicurezza, periodo di conservazione) che espone a una violazione e a una sanzione.')),
  r('core.risk.mis-selling', 'TRANSVERSAL', l('Un produit ou service inadapté est vendu à un client', 'An unsuitable product or service is sold to a customer', 'Einem Kunden wird ein ungeeignetes Produkt oder eine ungeeignete Leistung verkauft', 'Se vende a un cliente un producto o servicio inadecuado', 'Un prodotto o servizio inadeguato viene venduto a un cliente'), 'core.process.deliver.orders',
    l('Commercialisation d’un produit ou service inadapté ou insuffisamment expliqué au client (défaut de conseil, clauses abusives), source de litige et d’atteinte à la réputation.', 'Sale of a product or service that is unsuitable or poorly explained to the customer (inadequate advice, unfair terms), leading to disputes and reputational damage.', 'Vertrieb eines ungeeigneten oder unzureichend erklärten Produkts (mangelhafte Beratung, missbräuchliche Klauseln) mit Streitigkeiten und Reputationsschäden als Folge.', 'Comercialización de un producto o servicio inadecuado o insuficientemente explicado al cliente (falta de asesoramiento, cláusulas abusivas), fuente de litigios y de daño reputacional.', 'Commercializzazione di un prodotto o servizio inadeguato o spiegato in modo insufficiente al cliente (consulenza carente, clausole vessatorie), fonte di contenziosi e di danno reputazionale.')),
  r('core.risk.premises', 'TRANSVERSAL', l('Un sinistre rend des locaux ou des équipements indisponibles', 'A disaster makes premises or equipment unavailable', 'Ein Schadensereignis macht Räumlichkeiten oder Ausrüstung unbenutzbar', 'Un siniestro deja locales o equipos fuera de servicio', 'Un sinistro rende indisponibili locali o attrezzature'), 'core.process.govern.crisis',
    l('Événement physique (incendie, inondation, événement naturel) rendant indisponibles des locaux ou des équipements essentiels à l’activité.', 'Physical event (fire, flood, natural event) making premises or equipment essential to the business unavailable.', 'Physisches Ereignis (Brand, Überschwemmung, Naturereignis), das für den Betrieb wesentliche Räumlichkeiten oder Ausrüstungen unbenutzbar macht.', 'Hecho físico (incendio, inundación, fenómeno natural) que deja fuera de servicio locales o equipos esenciales para la actividad.', 'Evento fisico (incendio, alluvione, evento naturale) che rende indisponibili locali o attrezzature essenziali per l’attività.')),
  r('core.risk.it-outage', 'TRANSVERSAL', l('Une panne rend des applications essentielles indisponibles au-delà du délai acceptable', 'An outage makes essential applications unavailable beyond the acceptable time', 'Ein Ausfall macht wesentliche Anwendungen länger als vertretbar unverfügbar', 'Una avería deja aplicaciones esenciales indisponibles más allá del plazo aceptable', 'Un guasto rende indisponibili applicazioni essenziali oltre il tempo accettabile'), 'core.process.digital',
    l('Panne, saturation ou erreur d’exploitation rendant indisponibles des applications essentielles au-delà du délai de reprise acceptable, interrompant l’activité.', 'Failure, overload or operating error making essential applications unavailable beyond the acceptable recovery time, interrupting the business.', 'Ausfall, Überlastung oder Bedienfehler, durch die wesentliche Anwendungen länger als die vertretbare Wiederanlaufzeit nicht verfügbar sind und der Betrieb unterbrochen wird.', 'Avería, saturación o error de explotación que deja aplicaciones esenciales indisponibles más allá del plazo de recuperación aceptable e interrumpe la actividad.', 'Guasto, saturazione o errore di esercizio che rende indisponibili applicazioni essenziali oltre il tempo di ripristino accettabile, interrompendo l’attività.')),
  r('core.risk.continuity-plan', 'TRANSVERSAL', l('Le plan de continuité ne permet pas de reprendre l’activité dans les délais', 'The continuity plan fails to restore operations in time', 'Der Kontinuitätsplan ermöglicht keine fristgerechte Wiederaufnahme des Betriebs', 'El plan de continuidad no permite reanudar la actividad a tiempo', 'Il piano di continuità non consente di riprendere l’attività nei tempi previsti'), 'core.process.govern.crisis',
    l('Plan de continuité ou de reprise inexistant, obsolète ou jamais testé, empêchant la reprise des activités essentielles dans les délais visés.', 'Continuity or recovery plan that is missing, outdated or never tested, preventing essential activities from resuming within target times.', 'Fehlender, veralteter oder nie getesteter Kontinuitäts- oder Wiederanlaufplan, der die Wiederaufnahme wesentlicher Tätigkeiten in den Zielzeiten verhindert.', 'Plan de continuidad o de recuperación inexistente, obsoleto o nunca probado, que impide reanudar las actividades esenciales en los plazos previstos.', 'Piano di continuità o di ripristino assente, obsoleto o mai testato, che impedisce la ripresa delle attività essenziali nei tempi previsti.')),
  r('core.risk.financial-reporting', 'TRANSVERSAL', l('Une information comptable ou financière erronée est produite', 'Incorrect accounting or financial information is produced', 'Es werden fehlerhafte Buchhaltungs- oder Finanzinformationen erstellt', 'Se produce información contable o financiera errónea', 'Vengono prodotte informazioni contabili o finanziarie errate'), 'core.process.finance.accounting',
    l('Insuffisance de la piste d’audit ou des contrôles comptables entraînant une information financière erronée ou un retard de clôture.', 'Weak audit trail or accounting controls leading to incorrect financial information or a delayed closing.', 'Unzureichender Prüfpfad oder unzureichende Buchhaltungskontrollen, die zu fehlerhaften Finanzinformationen oder einem verspäteten Abschluss führen.', 'Pista de auditoría o controles contables insuficientes que provocan información financiera errónea o un retraso en el cierre.', 'Pista di controllo o controlli contabili insufficienti che causano informazioni finanziarie errate o un ritardo nella chiusura.')),
  r('core.risk.obligation-missed', 'TRANSVERSAL', l('Une obligation contractuelle ou réglementaire n’est pas respectée', 'A contractual or regulatory obligation is not met', 'Eine vertragliche oder regulatorische Pflicht wird nicht eingehalten', 'No se cumple una obligación contractual o reglamentaria', 'Un obbligo contrattuale o normativo non viene rispettato'), 'core.process.govern.compliance',
    l('Contrat mal suivi (échéance, réversibilité, responsabilité) ou obligation réglementaire non respectée, exposant à un litige ou à une sanction.', 'Poorly monitored contract (deadline, reversibility, liability) or unmet regulatory obligation, leading to a dispute or a penalty.', 'Schlecht überwachter Vertrag (Frist, Rückführbarkeit, Haftung) oder nicht erfüllte regulatorische Pflicht, die zu einem Rechtsstreit oder einer Sanktion führt.', 'Contrato mal seguido (vencimiento, reversibilidad, responsabilidad) u obligación reglamentaria incumplida, que expone a un litigio o a una sanción.', 'Contratto seguito male (scadenza, reversibilità, responsabilità) o obbligo normativo non rispettato, che espone a un contenzioso o a una sanzione.')),
  r('finance.risk.aml', 'FINANCE', l('Une opération de blanchiment n’est ni détectée ni déclarée', 'A money-laundering transaction is neither detected nor reported', 'Eine Geldwäschetransaktion wird weder erkannt noch gemeldet', 'Una operación de blanqueo no se detecta ni se declara', 'Un’operazione di riciclaggio non viene né individuata né segnalata'), 'finance.process.accounts',
    l('Défaillance des dispositifs de vigilance (connaissance client, détection des opérations atypiques, déclaration de soupçon) exposant à un risque pénal et réglementaire.', 'Failure of due-diligence arrangements (customer knowledge, detection of unusual transactions, suspicious activity reporting) leading to criminal and regulatory exposure.', 'Versagen der Sorgfaltsmaßnahmen (Kundenkenntnis, Erkennung ungewöhnlicher Transaktionen, Verdachtsmeldung) mit straf- und aufsichtsrechtlichen Folgen.', 'Fallo de los dispositivos de diligencia debida (conocimiento del cliente, detección de operaciones atípicas, comunicación de operaciones sospechosas) que expone a un riesgo penal y reglamentario.', 'Carenza dei presidi di adeguata verifica (conoscenza del cliente, rilevazione di operazioni anomale, segnalazione di operazioni sospette) che espone a un rischio penale e normativo.')),
]

/**
 * Catégorie bâloise de chaque risque du catalogue (BALE_1 fraude interne, 2 fraude externe,
 * 3 emploi et sécurité au travail, 4 clients, produits et pratiques commerciales, 5 dommages aux
 * actifs corporels, 6 interruption d'activité et pannes de systèmes, 7 exécution, livraison et gestion
 * des processus). Classement proposé, à revoir avec la revue métier.
 */
export const RISK_BALE: Record<string, 1 | 2 | 3 | 4 | 5 | 6 | 7> = {
  'core.risk.payment-fraud': 2, 'core.risk.ransomware': 2, 'core.risk.supplier-outage': 6, 'core.risk.data-leak': 4,
  'core.risk.key-person': 3, 'core.risk.process-error': 7, 'core.risk.privileged-access': 2, 'core.risk.leavers': 7,
  'core.risk.backup-failure': 6, 'core.risk.unpatched': 6, 'core.risk.supplier-contract': 7, 'core.risk.detection-gap': 2,
  'core.risk.internal-fraud': 1, 'core.risk.segregation': 1, 'core.risk.workplace': 3, 'core.risk.personal-data': 4,
  'core.risk.mis-selling': 4, 'core.risk.premises': 5, 'core.risk.it-outage': 6, 'core.risk.continuity-plan': 6,
  'core.risk.financial-reporting': 7, 'core.risk.obligation-missed': 7,
  'finance.risk.payment-routing': 7, 'finance.risk.account-takeover': 2, 'finance.risk.credit-data': 7, 'finance.risk.channel-outage': 6,
  'finance.risk.reconciliation': 7, 'finance.risk.sanction-screening': 4, 'finance.risk.card-data': 2, 'finance.risk.aml': 4,
  'assurance.risk.claim-fraud': 2, 'assurance.risk.claim-delay': 7, 'assurance.risk.pricing': 7, 'assurance.risk.broker-data': 7,
  'assurance.risk.policy-change': 7, 'assurance.risk.reserve': 7, 'assurance.risk.customer-data': 4,
  'energie.risk.scada': 2, 'energie.risk.outage': 6, 'energie.risk.imbalance': 7, 'energie.risk.field-safety': 3,
  'energie.risk.contractor-access': 2, 'energie.risk.metering-error': 7, 'energie.risk.customer-data': 4,
  'transport.risk.planning-outage': 6, 'transport.risk.delay': 7, 'transport.risk.cargo-theft': 2, 'transport.risk.accident': 5,
  'transport.risk.stock-error': 7, 'transport.risk.maintenance': 7, 'transport.risk.telematics': 4,
  'telecom.risk.outage': 6, 'telecom.risk.config-change': 6, 'telecom.risk.traffic-data': 4, 'telecom.risk.sim-swap': 2,
  'telecom.risk.revenue-leak': 7, 'telecom.risk.billing-error': 7, 'telecom.risk.request-error': 7,
  'sante.risk.patient-data': 4, 'sante.risk.care-outage': 6, 'sante.risk.result-error': 7, 'sante.risk.stockout': 7,
  'sante.risk.record-integrity': 7, 'sante.risk.device': 6, 'sante.risk.consent': 4,
  'industrie.risk.ot-stop': 6, 'industrie.risk.quality': 7, 'industrie.risk.spares': 7, 'industrie.risk.supplier': 7,
  'industrie.risk.traceability': 7, 'industrie.risk.safety': 3, 'industrie.risk.remote-maintenance': 2,
  'public.risk.portal-outage': 6, 'public.risk.identity': 2, 'public.risk.grant-error': 7, 'public.risk.local-outage': 6,
  'public.risk.case-leak': 4, 'public.risk.stale-data': 7, 'public.risk.open-data': 4,
  'commerce.risk.checkout': 6, 'commerce.risk.stock': 7, 'commerce.risk.delivery': 7, 'commerce.risk.customer-data': 4,
  'commerce.risk.returns': 7, 'commerce.risk.pricing': 7, 'commerce.risk.loyalty': 2,
  'saas.risk.release': 6, 'saas.risk.tenant-isolation': 4, 'saas.risk.cloud-outage': 6, 'saas.risk.support-access': 4,
  'saas.risk.integration': 6, 'saas.risk.secrets': 7, 'saas.risk.tenant-restore': 6,
  'services.risk.deadline': 7, 'services.risk.confidentiality': 4, 'services.risk.scope': 7, 'services.risk.billing': 7,
  'services.risk.expertise': 3, 'services.risk.subcontractor': 7, 'services.risk.client-access': 1,
}
