/** Contenu générique des patterns du lot 2 : suggestions à qualifier, jamais des faits présumés. */
import { L, ae, bs, er, me, ms, ss, type PatternItem, type Tr } from './exemples-patterns-core'

type Subject = { code: string; label: Tr }
const subjects: Subject[] = [
  { code: 'APPLICATIONS_MOBILES', label: L('applications et terminaux mobiles', 'mobile applications and devices', 'mobile Anwendungen und Geräte', 'aplicaciones y terminales móviles', 'applicazioni e dispositivi mobili') },
  { code: 'CLOUD_SAAS', label: L('services SaaS', 'SaaS services', 'SaaS-Dienste', 'servicios SaaS', 'servizi SaaS') },
  { code: 'CLOUD_IAAS_PAAS', label: L('hébergement IaaS/PaaS', 'IaaS/PaaS hosting', 'IaaS/PaaS-Hosting', 'alojamiento IaaS/PaaS', 'hosting IaaS/PaaS') },
  { code: 'SAUVEGARDE', label: L('infrastructure de sauvegarde', 'backup infrastructure', 'Backup-Infrastruktur', 'infraestructura de copia de seguridad', 'infrastruttura di backup') },
  { code: 'SUPERVISION', label: L('journalisation et supervision', 'logging and monitoring', 'Protokollierung und Überwachung', 'registro y supervisión', 'registrazione e monitoraggio') },
  { code: 'IA_SERVICES', label: L('services d’intelligence artificielle', 'artificial intelligence services', 'Dienste künstlicher Intelligenz', 'servicios de inteligencia artificial', 'servizi di intelligenza artificiale') },
  { code: 'SI_ISOLE', label: L('système isolé ou déconnecté', 'isolated or disconnected system', 'isoliertes oder getrenntes System', 'sistema aislado o desconectado', 'sistema isolato o disconnesso') },
  { code: 'SI_INDUSTRIEL', label: L('systèmes industriels et objets connectés', 'industrial systems and connected objects', 'industrielle Systeme und vernetzte Objekte', 'sistemas industriales y objetos conectados', 'sistemi industriali e oggetti connessi') },
  { code: 'SI_PATRIMONIAL', label: L('patrimoine applicatif ancien', 'legacy application estate', 'alte Anwendungslandschaft', 'patrimonio aplicativo antiguo', 'patrimonio applicativo datato') },
]
const tx = (s: Tr, a: Tr): Tr => [`${s[0]} — ${a[0]}`, `${s[1]} — ${a[1]}`, `${s[2]} — ${a[2]}`, `${s[3]} — ${a[3]}`, `${s[4]} — ${a[4]}`]
const ASSET = L('composants, comptes et données associés', 'associated components, accounts and data', 'zugehörige Komponenten, Konten und Daten', 'componentes, cuentas y datos asociados', 'componenti, account e dati associati')
const LOSS = L('indisponibilité, altération ou divulgation non maîtrisée', 'uncontrolled unavailability, alteration or disclosure', 'unkontrollierte Nichtverfügbarkeit, Veränderung oder Offenlegung', 'indisponibilidad, alteración o divulgación no controlada', 'indisponibilità, alterazione o divulgazione non controllata')

export const LOT2_ITEMS: PatternItem[] = subjects.flatMap(({ code, label }) => {
  const p = [code] as const
  return [
    bs(p, tx(label, ASSET), 'LOGICIEL', tx(label, L('à inventorier avec ses dépendances, propriétaires et données traitées', 'to inventory with its dependencies, owners and processed data', 'mit Abhängigkeiten, Verantwortlichen und verarbeiteten Daten zu inventarisieren', 'que debe inventariarse con dependencias, responsables y datos tratados', 'da inventariare con dipendenze, responsabili e dati trattati'))),
    er(p, tx(label, LOSS), [L('Interruption de l’activité', 'Business interruption', 'Unterbrechung der Tätigkeit', 'Interrupción de la actividad', 'Interruzione dell’attività')], 3),
    ss(p, 'D', tx(label, L('est compromis ou indisponible faute de mesures adaptées (D)', 'is compromised or unavailable because safeguards are inadequate (A)', 'wird wegen unzureichender Maßnahmen kompromittiert oder nicht verfügbar (V)', 'queda comprometido o no disponible por medidas inadecuadas (D)', 'è compromesso o indisponibile per misure inadeguate (D)')), tx(label, L('Une dépendance technique, humaine ou fournisseur n’est pas maîtrisée', 'A technical, human or supplier dependency is not controlled', 'Eine technische, menschliche oder Lieferantenabhängigkeit ist nicht beherrscht', 'No se controla una dependencia técnica, humana o de proveedor', 'Una dipendenza tecnica, umana o di fornitore non è controllata')), 2, 3),
    ae(p, 'ACCES_INITIAL', 'T1190', tx(label, L('Exploitation d’une faiblesse ou d’une configuration non maîtrisée', 'Exploitation of a weakness or unmanaged configuration', 'Ausnutzung einer Schwachstelle oder unbeherrschten Konfiguration', 'Explotación de una debilidad o configuración no controlada', 'Sfruttamento di una debolezza o configurazione non controllata')), tx(label, L('Le scénario est à adapter aux composants réellement présents', 'The scenario must be adapted to the components actually present', 'Das Szenario ist an die tatsächlich vorhandenen Komponenten anzupassen', 'El escenario debe adaptarse a los componentes realmente presentes', 'Lo scenario va adattato ai componenti realmente presenti'))),
    me(p, tx(label, L('revue de sécurité et de dépendances', 'security and dependency review', 'Sicherheits- und Abhängigkeitsprüfung', 'revisión de seguridad y dependencias', 'revisione della sicurezza e delle dipendenze')), 'ORGANISATIONNELLE', 'ISO/IEC 27001:2022', tx(label, L('Qualifier les risques, responsabilités et conditions d’exploitation avant mise en service', 'Qualify risks, responsibilities and operating conditions before go-live', 'Risiken, Verantwortlichkeiten und Betriebsbedingungen vor Inbetriebnahme klären', 'Calificar riesgos, responsabilidades y condiciones operativas antes de la puesta en servicio', 'Qualificare rischi, responsabilità e condizioni operative prima della messa in servizio'))),
    ms(p, tx(label, L('durcissement, suivi et exercice de restauration ou de réponse', 'hardening, monitoring and restoration or response exercise', 'Härtung, Überwachung und Wiederherstellungs- oder Reaktionsübung', 'endurecimiento, seguimiento y ejercicio de restauración o respuesta', 'hardening, monitoraggio ed esercizio di ripristino o risposta')), tx(label, L('Choisir des mesures proportionnées et vérifier régulièrement leur efficacité', 'Choose proportionate safeguards and regularly verify their effectiveness', 'Angemessene Maßnahmen wählen und ihre Wirksamkeit regelmäßig prüfen', 'Elegir medidas proporcionales y verificar regularmente su eficacia', 'Scegliere misure proporzionate e verificarne regolarmente l’efficacia')), 'TECHNIQUE', 'RESILIENCE', 2),
  ]
})
