/**
 * Contenu des patterns « Télémaintenance », « Administration et exploitation » (système d'administration, flux internes
 * au datacenter), « Postes et usages » (SI bureautique, SI de très petite entreprise), « SI sensible » et de leurs
 * COMBINAISONS (plusieurs patterns requis). Générique ; textes ×5 dans la donnée. Contenu « à relire par un expert ».
 */
import { L, bs, er, sr, ss, ae, ms, pp, type PatternItem } from '@/lib/exemples-patterns-core'

const TELEMAINT = ['TELEMAINTENANCE'] as const
const ADMIN = ['SI_ADMINISTRATION'] as const
const DC = ['FLUX_INTERNES_DC'] as const
const BURO = ['BUREAUTIQUE'] as const
const TPE = ['SI_TPE'] as const
const SENS = ['SI_SENSIBLE'] as const
const ISO = 'ISO/IEC 27001:2022, annexe A'

export const ADMIN_POSTES_ITEMS: PatternItem[] = [
  // ═══ Télémaintenance ═══════════════════════════════════════════════════════════════════════════
  bs(TELEMAINT, L('Accès de télémaintenance d’un éditeur, d’un constructeur ou d’un prestataire', 'Remote-maintenance access for a vendor, manufacturer or provider', 'Fernwartungszugang eines Herstellers oder Dienstleisters', 'Acceso de telemantenimiento de un editor, fabricante o proveedor', 'Accesso di teleassistenza di un fornitore, costruttore o prestatore'), 'RESEAU',
    L('Canal (VPN, outil de prise de main) par lequel un tiers intervient à distance sur des équipements ou applications', 'Channel (VPN, remote-control tool) through which a third party works remotely on equipment or applications', 'Kanal (VPN, Fernsteuerungswerkzeug), über den ein Dritter aus der Ferne an Geräten oder Anwendungen arbeitet', 'Canal (VPN, herramienta de toma de control) por el que un tercero interviene a distancia en equipos o aplicaciones', 'Canale (VPN, strumento di controllo remoto) attraverso cui una terza parte interviene da remoto su apparecchiature o applicazioni')),
  bs(TELEMAINT, L('Comptes nominatifs ou partagés des intervenants externes', 'Named or shared accounts of external engineers', 'Namentliche oder gemeinsam genutzte Konten externer Techniker', 'Cuentas nominativas o compartidas de los intervinientes externos', 'Account nominativi o condivisi degli interventi esterni'), 'LOGICIEL',
    L('Identifiants du prestataire, souvent permanents et peu surveillés', 'Provider credentials, often permanent and poorly monitored', 'Zugangsdaten des Dienstleisters, oft dauerhaft und wenig überwacht', 'Credenciales del proveedor, a menudo permanentes y poco vigiladas', 'Credenziali del fornitore, spesso permanenti e poco monitorate')),
  er(TELEMAINT, L('Prise de main malveillante sur un équipement par le canal de télémaintenance', 'Malicious takeover of equipment through the remote-maintenance channel', 'Böswillige Übernahme eines Geräts über den Fernwartungskanal', 'Toma de control malintencionada de un equipo por el canal de telemantenimiento', 'Presa di controllo malevola di un’apparecchiatura attraverso il canale di teleassistenza'),
    [L('Arrêt ou dérèglement de l’équipement', 'Equipment shutdown or malfunction', 'Ausfall oder Fehlfunktion des Geräts', 'Parada o desajuste del equipo', 'Arresto o malfunzionamento dell’apparecchiatura'), L('Accès illégitime au SI', 'Unauthorised access to the IS', 'Unberechtigter Zugriff auf das IS', 'Acceso ilegítimo al SI', 'Accesso illegittimo al SI')], 4),
  ss(TELEMAINT, 'I', L('Un attaquant compromet le prestataire puis agit sur le SI par la télémaintenance, sans que l’intervention soit distinguée d’une opération légitime (I)', 'An attacker compromises the provider then acts on the IS through remote maintenance, indistinguishable from a legitimate operation (I)', 'Ein Angreifer kompromittiert den Dienstleister und handelt über die Fernwartung im IS, ununterscheidbar von einer legitimen Maßnahme (I)', 'Un atacante compromete al proveedor y actúa sobre el SI por telemantenimiento, sin que se distinga de una operación legítima (I)', 'Un attaccante compromette il fornitore e agisce sul SI tramite teleassistenza, senza che l’intervento si distingua da un’operazione legittima (I)'),
    L('Accès permanent, sans second facteur ni enregistrement de session, aux équipements les plus sensibles', 'Permanent access, without second factor or session recording, to the most sensitive equipment', 'Dauerhafter Zugang ohne zweiten Faktor oder Sitzungsaufzeichnung zu den sensibelsten Geräten', 'Acceso permanente, sin segundo factor ni grabación de sesión, a los equipos más sensibles', 'Accesso permanente, senza secondo fattore né registrazione della sessione, alle apparecchiature più sensibili'), 3, 4),
  ae(TELEMAINT, 'ACCES_INITIAL', 'T1199', L('Utilisation d’une relation de confiance : connexion par le compte d’un prestataire de maintenance', 'Trusted-relationship abuse: sign-in through a maintenance provider’s account', 'Missbrauch einer Vertrauensbeziehung: Anmeldung über das Konto eines Wartungsdienstleisters', 'Abuso de una relación de confianza: conexión con la cuenta de un proveedor de mantenimiento', 'Abuso di una relazione di fiducia: accesso con l’account di un fornitore di manutenzione'),
    L('L’attaquant hérite des droits et du canal du prestataire', 'The attacker inherits the provider’s rights and channel', 'Der Angreifer erbt die Rechte und den Kanal des Dienstleisters', 'El atacante hereda los derechos y el canal del proveedor', 'L’attaccante eredita i diritti e il canale del fornitore')),
  ms(TELEMAINT, L('Télémaintenance à la demande : accès ouvert pour une intervention précise, avec validation et durée limitée', 'On-demand remote maintenance: access opened for a specific intervention, with approval and limited duration', 'Fernwartung auf Anforderung: Zugang für einen bestimmten Einsatz, mit Freigabe und begrenzter Dauer', 'Telemantenimiento a petición: acceso abierto para una intervención concreta, con validación y duración limitada', 'Teleassistenza su richiesta: accesso aperto per un intervento preciso, con approvazione e durata limitata'),
    L('Pas de connexion permanente ; accès nominatif avec second facteur, via un bastion qui enregistre les sessions', 'No permanent connection; named access with second factor, through a bastion that records sessions', 'Keine Dauerverbindung; namentlicher Zugang mit zweitem Faktor über einen Bastion-Host, der Sitzungen aufzeichnet', 'Sin conexión permanente; acceso nominativo con segundo factor, a través de un bastión que graba las sesiones', 'Nessuna connessione permanente; accesso nominativo con secondo fattore, tramite un bastion che registra le sessioni'),
    'PREVENTIVE', 'PROTECTION', 1),
  ms(TELEMAINT, L('Clauses contractuelles et audit des prestataires de télémaintenance', 'Contract clauses and audit of remote-maintenance providers', 'Vertragsklauseln und Audit der Fernwartungsdienstleister', 'Cláusulas contractuales y auditoría de los proveedores de telemantenimiento', 'Clausole contrattuali e audit dei fornitori di teleassistenza'),
    L('Exiger sécurité des postes du prestataire, notification d’incident et droit d’audit', 'Require security of the provider’s workstations, incident notification and audit rights', 'Sicherheit der Arbeitsplätze des Dienstleisters, Vorfallmeldung und Auditrecht verlangen', 'Exigir la seguridad de los puestos del proveedor, notificación de incidentes y derecho de auditoría', 'Richiedere la sicurezza delle postazioni del fornitore, la notifica degli incidenti e il diritto di audit'),
    'ORGANISATIONNELLE', 'GOUVERNANCE', 2, [ISO]),

  // ═══ Système d'administration ══════════════════════════════════════════════════════════════════
  bs(ADMIN, L('Annuaire central et comptes à privilèges', 'Central directory and privileged accounts', 'Zentrales Verzeichnis und privilegierte Konten', 'Directorio central y cuentas con privilegios', 'Directory centrale e account privilegiati'), 'LOGICIEL',
    L('Annuaire d’identités et comptes d’administration dont la compromission donne la maîtrise de tout le SI', 'Identity directory and administration accounts whose compromise gives control of the whole IS', 'Identitätsverzeichnis und Administrationskonten, deren Kompromittierung die Kontrolle über das gesamte IS verschafft', 'Directorio de identidades y cuentas de administración cuyo compromiso da el control de todo el SI', 'Directory delle identità e account di amministrazione la cui compromissione dà il controllo di tutto il SI')),
  bs(ADMIN, L('Postes d’administration, bastion et outils de déploiement', 'Administration workstations, bastion host and deployment tools', 'Administrationsarbeitsplätze, Bastion-Host und Deployment-Werkzeuge', 'Puestos de administración, bastión y herramientas de despliegue', 'Postazioni di amministrazione, bastion e strumenti di distribuzione'), 'MATERIEL',
    L('Outils qui permettent d’agir sur l’ensemble des serveurs et postes', 'Tools that allow acting on all servers and workstations', 'Werkzeuge, mit denen auf alle Server und Arbeitsplätze eingewirkt werden kann', 'Herramientas que permiten actuar sobre todos los servidores y puestos', 'Strumenti che permettono di agire su tutti i server e le postazioni')),
  er(ADMIN, L('Prise de contrôle du système d’administration par un attaquant', 'Takeover of the administration system by an attacker', 'Übernahme des Administrationssystems durch einen Angreifer', 'Toma de control del sistema de administración por un atacante', 'Presa di controllo del sistema di amministrazione da parte di un attaccante'),
    [L('Compromission généralisée du SI', 'Widespread compromise of the IS', 'Umfassende Kompromittierung des IS', 'Compromiso generalizado del SI', 'Compromissione generalizzata del SI'), L('Déploiement d’un rançongiciel sur tout le parc', 'Ransomware deployed across the whole estate', 'Ransomware-Verteilung im gesamten Bestand', 'Despliegue de ransomware en todo el parque', 'Distribuzione di ransomware su tutto il parco')], 4),
  ss(ADMIN, 'D', L('Un attaquant obtient des droits d’administrateur de domaine et chiffre l’ensemble des serveurs (D)', 'An attacker obtains domain-admin rights and encrypts all servers (D)', 'Ein Angreifer erlangt Domänenadministrator-Rechte und verschlüsselt alle Server (D)', 'Un atacante obtiene derechos de administrador de dominio y cifra todos los servidores (D)', 'Un attaccante ottiene i diritti di amministratore di dominio e cifra tutti i server (D)'),
    L('Comptes d’administration utilisés sur des postes ordinaires, sans cloisonnement du système d’administration', 'Administration accounts used on ordinary workstations, without segregation of the administration system', 'Administrationskonten auf normalen Arbeitsplätzen genutzt, ohne Trennung des Administrationssystems', 'Cuentas de administración usadas en puestos ordinarios, sin segregación del sistema de administración', 'Account di amministrazione usati su postazioni ordinarie, senza segregazione del sistema di amministrazione'), 3, 4),
  ae(ADMIN, 'ESCALADE_PRIVILEGES', 'T1078', L('Réutilisation d’un compte à privilèges dont l’identifiant a été capturé sur un poste ordinaire', 'Reuse of a privileged account whose credentials were captured on an ordinary workstation', 'Wiederverwendung eines privilegierten Kontos, dessen Zugangsdaten auf einem normalen Arbeitsplatz abgegriffen wurden', 'Reutilización de una cuenta con privilegios cuyas credenciales se capturaron en un puesto ordinario', 'Riutilizzo di un account privilegiato le cui credenziali sono state catturate su una postazione ordinaria'),
    L('Vol de secret en mémoire ou de jeton d’authentification', 'Theft of a secret in memory or of an authentication token', 'Diebstahl eines Geheimnisses im Speicher oder eines Authentifizierungstokens', 'Robo de un secreto en memoria o de un token de autenticación', 'Furto di un segreto in memoria o di un token di autenticazione')),
  ms(ADMIN, L('Postes d’administration dédiés et comptes d’administration distincts des comptes courants', 'Dedicated administration workstations and administration accounts separate from everyday accounts', 'Dedizierte Administrationsarbeitsplätze und von Alltagskonten getrennte Administrationskonten', 'Puestos de administración dedicados y cuentas de administración distintas de las cuentas habituales', 'Postazioni di amministrazione dedicate e account di amministrazione distinti dagli account ordinari'),
    L('Aucun usage de messagerie ou de navigation avec un compte à privilèges ; accès aux serveurs par un bastion', 'No mail or browsing with a privileged account; server access through a bastion', 'Keine Nutzung von E-Mail oder Browser mit einem privilegierten Konto; Serverzugriff über einen Bastion-Host', 'Ningún uso de correo o navegación con una cuenta con privilegios; acceso a los servidores por un bastión', 'Nessun uso di posta o navigazione con un account privilegiato; accesso ai server tramite un bastion'),
    'PREVENTIVE', 'PROTECTION', 1),
  ms(ADMIN, L('Journalisation et revue des actions d’administration, détection des créations de comptes privilégiés', 'Logging and review of administration actions, detection of privileged account creation', 'Protokollierung und Prüfung von Administrationsaktionen, Erkennung der Anlage privilegierter Konten', 'Registro y revisión de las acciones de administración, detección de la creación de cuentas privilegiadas', 'Registrazione e revisione delle azioni di amministrazione, rilevamento della creazione di account privilegiati'),
    L('Alerte sur toute modification de groupe d’administrateurs ; revue trimestrielle des comptes à privilèges', 'Alert on any change to administrator groups; quarterly review of privileged accounts', 'Alarm bei jeder Änderung von Administratorgruppen; vierteljährliche Prüfung privilegierter Konten', 'Alerta ante cualquier cambio en los grupos de administradores; revisión trimestral de las cuentas con privilegios', 'Allarme su ogni modifica dei gruppi di amministratori; revisione trimestrale degli account privilegiati'),
    'DETECTIVE', 'DEFENSE', 1),

  // ═══ Flux internes au datacenter ═══════════════════════════════════════════════════════════════
  bs(DC, L('Segments réseau et règles de filtrage entre serveurs du datacenter', 'Network segments and filtering rules between data-centre servers', 'Netzsegmente und Filterregeln zwischen Servern im Rechenzentrum', 'Segmentos de red y reglas de filtrado entre servidores del centro de datos', 'Segmenti di rete e regole di filtraggio tra server del datacenter'), 'RESEAU',
    L('Découpage qui limite la propagation d’une compromission entre serveurs (flux « est-ouest »)', 'Partitioning that limits the spread of a compromise between servers (east-west flows)', 'Aufteilung, die die Ausbreitung einer Kompromittierung zwischen Servern begrenzt („Ost-West“-Flüsse)', 'Segmentación que limita la propagación de un compromiso entre servidores (flujos «este-oeste»)', 'Suddivisione che limita la propagazione di una compromissione tra server (flussi «est-ovest»)')),
  er(DC, L('Propagation rapide d’une compromission à tous les serveurs d’un même segment', 'Rapid spread of a compromise to all servers of the same segment', 'Schnelle Ausbreitung einer Kompromittierung auf alle Server desselben Segments', 'Propagación rápida de un compromiso a todos los servidores de un mismo segmento', 'Rapida propagazione di una compromissione a tutti i server dello stesso segmento'),
    [L('Indisponibilité simultanée de nombreuses applications', 'Simultaneous unavailability of many applications', 'Gleichzeitiger Ausfall vieler Anwendungen', 'Indisponibilidad simultánea de numerosas aplicaciones', 'Indisponibilità simultanea di numerose applicazioni')], 4),
  ss(DC, 'D', L('Un rançongiciel se propage d’un serveur à tous les serveurs du datacenter faute de segmentation interne (D)', 'Ransomware spreads from one server to every data-centre server for lack of internal segmentation (D)', 'Ransomware verbreitet sich mangels interner Segmentierung von einem Server auf alle Server im Rechenzentrum (D)', 'Un ransomware se propaga de un servidor a todos los servidores del centro de datos por falta de segmentación interna (D)', 'Un ransomware si propaga da un server a tutti i server del datacenter per mancanza di segmentazione interna (D)'),
    L('Le premier serveur compromis atteint librement les autres, y compris sauvegardes et supervision', 'The first compromised server freely reaches the others, including backups and monitoring', 'Der erste kompromittierte Server erreicht frei die anderen, einschließlich Backups und Überwachung', 'El primer servidor comprometido alcanza libremente a los demás, incluidas copias y supervisión', 'Il primo server compromesso raggiunge liberamente gli altri, inclusi backup e monitoraggio'), 3, 4),
  ae(DC, 'MOUVEMENT_LATERAL', 'T1021', L('Déplacement latéral entre serveurs par protocoles d’administration autorisés (SMB, RDP, SSH)', 'Lateral movement between servers through allowed administration protocols (SMB, RDP, SSH)', 'Seitwärtsbewegung zwischen Servern über erlaubte Administrationsprotokolle (SMB, RDP, SSH)', 'Movimiento lateral entre servidores mediante protocolos de administración autorizados (SMB, RDP, SSH)', 'Movimento laterale tra server tramite protocolli di amministrazione autorizzati (SMB, RDP, SSH)'),
    L('Absence de filtrage interne : tout serveur peut joindre tout autre serveur', 'No internal filtering: any server can reach any other server', 'Keine interne Filterung: jeder Server erreicht jeden anderen', 'Sin filtrado interno: cualquier servidor puede alcanzar a cualquier otro', 'Nessun filtraggio interno: ogni server può raggiungere ogni altro')),
  ms(DC, L('Segmentation et micro-segmentation : seuls les flux nécessaires entre serveurs sont autorisés', 'Segmentation and micro-segmentation: only the necessary flows between servers are allowed', 'Segmentierung und Mikrosegmentierung: nur notwendige Flüsse zwischen Servern sind erlaubt', 'Segmentación y microsegmentación: solo se autorizan los flujos necesarios entre servidores', 'Segmentazione e microsegmentazione: sono consentiti solo i flussi necessari tra i server'),
    L('Matrice de flux documentée, règle « tout interdit sauf » et revue annuelle', 'Documented flow matrix, default-deny rule and yearly review', 'Dokumentierte Flussmatrix, Standard-Verbotsregel und jährliche Prüfung', 'Matriz de flujos documentada, regla «todo prohibido salvo» y revisión anual', 'Matrice dei flussi documentata, regola «tutto vietato salvo» e revisione annuale'),
    'TECHNIQUE', 'PROTECTION', 1),
  ms(DC, L('Détection des mouvements latéraux (supervision des flux internes et des authentifications)', 'Detection of lateral movement (monitoring of internal flows and authentications)', 'Erkennung von Seitwärtsbewegungen (Überwachung interner Flüsse und Authentifizierungen)', 'Detección de movimientos laterales (supervisión de flujos internos y autenticaciones)', 'Rilevamento dei movimenti laterali (monitoraggio dei flussi interni e delle autenticazioni)'),
    L('Alertes sur les connexions d’administration inhabituelles entre serveurs', 'Alerts on unusual administration connections between servers', 'Warnungen bei ungewöhnlichen Administrationsverbindungen zwischen Servern', 'Alertas ante conexiones de administración inusuales entre servidores', 'Allarmi sulle connessioni di amministrazione insolite tra server'),
    'DETECTIVE', 'DEFENSE', 2),

  // ═══ SI bureautique ════════════════════════════════════════════════════════════════════════════
  bs(BURO, L('Postes de travail et messagerie des utilisateurs', 'User workstations and mailboxes', 'Arbeitsplätze und Postfächer der Nutzer', 'Puestos de trabajo y buzones de los usuarios', 'Postazioni di lavoro e caselle di posta degli utenti'), 'MATERIEL',
    L('Parc d’ordinateurs, messagerie et partages de fichiers, principal point d’entrée des attaques', 'Fleet of computers, e-mail and file shares, the main entry point for attacks', 'Computerbestand, E-Mail und Dateifreigaben, Haupteinfallstor für Angriffe', 'Parque de ordenadores, correo y recursos compartidos, principal punto de entrada de los ataques', 'Parco di computer, posta elettronica e condivisioni di file, principale punto di ingresso degli attacchi')),
  bs(BURO, L('Imprimantes, copieurs et équipements en réseau', 'Printers, copiers and networked equipment', 'Drucker, Kopierer und vernetzte Geräte', 'Impresoras, copiadoras y equipos en red', 'Stampanti, fotocopiatrici e apparecchiature in rete'), 'MATERIEL',
    L('Équipements rarement mis à jour qui conservent parfois des documents et des identifiants', 'Equipment rarely updated that sometimes keeps documents and credentials', 'Selten aktualisierte Geräte, die teils Dokumente und Zugangsdaten speichern', 'Equipos rara vez actualizados que a veces conservan documentos y credenciales', 'Apparecchiature raramente aggiornate che talvolta conservano documenti e credenziali')),
  er(BURO, L('Chiffrement des postes et des partages par un rançongiciel arrivé par la messagerie', 'Encryption of workstations and shares by ransomware delivered through e-mail', 'Verschlüsselung von Arbeitsplätzen und Freigaben durch per E-Mail eingeschleuste Ransomware', 'Cifrado de puestos y recursos compartidos por un ransomware llegado por correo', 'Cifratura di postazioni e condivisioni da parte di un ransomware arrivato per posta elettronica'),
    [L('Arrêt de l’activité bureautique', 'Halt of office activity', 'Stillstand der Büroarbeit', 'Parada de la actividad ofimática', 'Arresto dell’attività d’ufficio'), L('Perte de documents', 'Loss of documents', 'Verlust von Dokumenten', 'Pérdida de documentos', 'Perdita di documenti')], 4),
  sr(BURO, L('Cybercriminel utilisant l’hameçonnage de masse', 'Cybercriminal using mass phishing', 'Cyberkrimineller mit Massen-Phishing', 'Cibercriminal que usa phishing masivo', 'Cybercriminale che usa phishing di massa'), 'CYBERCRIMINEL',
    L('Acteur qui envoie des messages piégés à grande échelle pour installer un logiciel malveillant', 'Actor sending booby-trapped messages at scale to install malware', 'Akteur, der in großem Umfang präparierte Nachrichten versendet, um Schadsoftware zu installieren', 'Actor que envía mensajes trampa a gran escala para instalar software malicioso', 'Attore che invia su larga scala messaggi trappola per installare software malevolo'),
    L('Gain financier, rançongiciel', 'Financial gain, ransomware', 'Finanzieller Gewinn, Ransomware', 'Beneficio económico, ransomware', 'Guadagno economico, ransomware'),
    L('Kits de hameçonnage, pièces jointes piégées, services de diffusion', 'Phishing kits, booby-trapped attachments, distribution services', 'Phishing-Kits, präparierte Anhänge, Verteildienste', 'Kits de phishing, adjuntos trampa, servicios de difusión', 'Kit di phishing, allegati trappola, servizi di diffusione'), 4),
  ae(BURO, 'ACCES_INITIAL', 'T1566', L('Hameçonnage d’un collaborateur par pièce jointe ou lien piégé', 'Phishing of an employee through a booby-trapped attachment or link', 'Phishing eines Mitarbeiters über präparierten Anhang oder Link', 'Phishing a un empleado mediante un adjunto o enlace trampa', 'Phishing di un collaboratore tramite allegato o link trappola'),
    L('Ouverture d’un document piégé qui installe un logiciel malveillant ou vole des identifiants', 'Opening of a booby-trapped document that installs malware or steals credentials', 'Öffnen eines präparierten Dokuments, das Schadsoftware installiert oder Zugangsdaten stiehlt', 'Apertura de un documento trampa que instala software malicioso o roba credenciales', 'Apertura di un documento trappola che installa software malevolo o ruba credenziali')),
  ms(BURO, L('Filtrage de la messagerie, correctifs réguliers et sensibilisation à l’hameçonnage', 'Mail filtering, regular patching and phishing awareness', 'E-Mail-Filterung, regelmäßiges Patchen und Phishing-Sensibilisierung', 'Filtrado del correo, parches regulares y sensibilización sobre el phishing', 'Filtraggio della posta, aggiornamenti regolari e sensibilizzazione sul phishing'),
    L('Analyse des pièces jointes, mises à jour mensuelles des postes et exercices de simulation', 'Attachment analysis, monthly workstation updates and simulation exercises', 'Anhangsanalyse, monatliche Arbeitsplatz-Updates und Simulationsübungen', 'Análisis de adjuntos, actualizaciones mensuales de los puestos y ejercicios de simulación', 'Analisi degli allegati, aggiornamenti mensili delle postazioni ed esercizi di simulazione'),
    'PREVENTIVE', 'PROTECTION', 1),
  ms(BURO, L('Sauvegardes déconnectées des postes et des partages, restauration testée', 'Backups disconnected from workstations and shares, restoration tested', 'Von Arbeitsplätzen und Freigaben getrennte Backups, getestete Wiederherstellung', 'Copias de seguridad desconectadas de los puestos y recursos compartidos, restauración probada', 'Backup scollegati da postazioni e condivisioni, ripristino testato'),
    L('Au moins une copie hors ligne ou immuable, restauration d’essai chaque trimestre', 'At least one offline or immutable copy, trial restoration each quarter', 'Mindestens eine Offline- oder unveränderliche Kopie, Testwiederherstellung jedes Quartal', 'Al menos una copia fuera de línea o inmutable, restauración de prueba cada trimestre', 'Almeno una copia offline o immutabile, ripristino di prova ogni trimestre'),
    'CORRECTIVE', 'RESILIENCE', 1),

  // ═══ SI de très petite entreprise ══════════════════════════════════════════════════════════════
  bs(TPE, L('Box internet, ordinateurs et NAS de la structure', 'Internet router, computers and NAS of the business', 'Internet-Router, Computer und NAS des Betriebs', 'Router de Internet, ordenadores y NAS de la estructura', 'Router internet, computer e NAS della struttura'), 'MATERIEL',
    L('Équipements grand public, rarement mis à jour, sans administrateur dédié', 'Consumer equipment, rarely updated, with no dedicated administrator', 'Consumer-Geräte, selten aktualisiert, ohne eigenen Administrator', 'Equipos de uso doméstico, rara vez actualizados, sin administrador dedicado', 'Apparecchiature di fascia consumer, raramente aggiornate, senza amministratore dedicato')),
  bs(TPE, L('Comptes partagés et mots de passe réutilisés', 'Shared accounts and reused passwords', 'Gemeinsame Konten und wiederverwendete Passwörter', 'Cuentas compartidas y contraseñas reutilizadas', 'Account condivisi e password riutilizzate'), 'LOGICIEL',
    L('Un même identifiant pour plusieurs personnes ou plusieurs services', 'The same login for several people or services', 'Dieselbe Anmeldung für mehrere Personen oder Dienste', 'Un mismo identificador para varias personas o servicios', 'Lo stesso accesso per più persone o servizi')),
  er(TPE, L('Perte définitive des données de la structure (panne, vol, chiffrement) faute de sauvegarde exploitable', 'Permanent loss of the business’s data (failure, theft, encryption) for lack of a usable backup', 'Dauerhafter Verlust der Betriebsdaten (Ausfall, Diebstahl, Verschlüsselung) mangels brauchbarer Sicherung', 'Pérdida definitiva de los datos de la estructura (avería, robo, cifrado) por falta de copia utilizable', 'Perdita definitiva dei dati della struttura (guasto, furto, cifratura) per mancanza di un backup utilizzabile'),
    [L('Arrêt prolongé de l’activité', 'Prolonged halt of activity', 'Längerer Stillstand der Tätigkeit', 'Parada prolongada de la actividad', 'Arresto prolungato dell’attività'), L('Risque pour la survie de la structure', 'Risk to the survival of the business', 'Gefahr für den Fortbestand des Betriebs', 'Riesgo para la supervivencia de la estructura', 'Rischio per la sopravvivenza della struttura')], 4),
  ss(TPE, 'D', L('Un rançongiciel chiffre l’unique poste et la sauvegarde connectée, sans possibilité de restauration (D)', 'Ransomware encrypts the only workstation and the connected backup, with no way to restore (D)', 'Ransomware verschlüsselt den einzigen Arbeitsplatz und die verbundene Sicherung, ohne Wiederherstellungsmöglichkeit (D)', 'Un ransomware cifra el único puesto y la copia conectada, sin posibilidad de restauración (D)', 'Un ransomware cifra l’unica postazione e il backup collegato, senza possibilità di ripristino (D)'),
    L('Sauvegarde sur un disque toujours branché et aucun plan de reprise', 'Backup on an always-connected disk and no recovery plan', 'Sicherung auf einer dauerhaft angeschlossenen Platte und kein Wiederanlaufplan', 'Copia en un disco siempre conectado y ningún plan de recuperación', 'Backup su un disco sempre collegato e nessun piano di ripristino'), 3, 4),
  ms(TPE, L('Sauvegarde simple et robuste : une copie hors ligne et une copie hors site, restauration essayée', 'Simple and robust backup: one offline copy and one off-site copy, restoration tried', 'Einfache und robuste Sicherung: eine Offline-Kopie und eine externe Kopie, Wiederherstellung erprobt', 'Copia de seguridad sencilla y robusta: una copia fuera de línea y una fuera del sitio, restauración probada', 'Backup semplice e robusto: una copia offline e una fuori sede, ripristino provato'),
    L('Règle 3-2-1 adaptée à la taille de la structure, avec un geste de restauration documenté', 'The 3-2-1 rule adapted to the size of the business, with a documented restoration procedure', 'Die 3-2-1-Regel, angepasst an die Betriebsgröße, mit dokumentiertem Wiederherstellungsablauf', 'Regla 3-2-1 adaptada al tamaño de la estructura, con un procedimiento de restauración documentado', 'Regola 3-2-1 adattata alla dimensione della struttura, con una procedura di ripristino documentata'),
    'CORRECTIVE', 'RESILIENCE', 1),
  ms(TPE, L('Un compte par personne, mots de passe uniques et second facteur sur la messagerie et les services en ligne', 'One account per person, unique passwords and a second factor on mail and online services', 'Ein Konto pro Person, eindeutige Passwörter und zweiter Faktor für E-Mail und Online-Dienste', 'Una cuenta por persona, contraseñas únicas y segundo factor en el correo y los servicios en línea', 'Un account per persona, password uniche e secondo fattore su posta e servizi online'),
    L('Gestionnaire de mots de passe, fin des comptes partagés, droits d’administration réservés à une personne', 'Password manager, end of shared accounts, administration rights restricted to one person', 'Passwortmanager, Ende gemeinsamer Konten, Administratorrechte nur für eine Person', 'Gestor de contraseñas, fin de las cuentas compartidas, derechos de administración reservados a una persona', 'Gestore di password, fine degli account condivisi, diritti di amministrazione riservati a una persona'),
    'TECHNIQUE', 'PROTECTION', 1),
  pp(TPE, L('Prestataire informatique unique', 'Single IT provider', 'Einziger IT-Dienstleister', 'Proveedor informático único', 'Fornitore informatico unico'), 'PRESTATAIRE', 4, 4, 2, 3),

  // ═══ SI sensible ═══════════════════════════════════════════════════════════════════════════════
  bs(SENS, L('Système d’information cloisonné traitant des informations sensibles', 'Compartmentalised information system handling sensitive information', 'Abgeschottetes Informationssystem für sensible Informationen', 'Sistema de información compartimentado que trata información sensible', 'Sistema informativo compartimentato che tratta informazioni sensibili'), 'MATERIEL',
    L('SI ou périmètre soumis à homologation renforcée, avec ses propres règles d’accès et d’administration', 'IS or scope subject to reinforced accreditation, with its own access and administration rules', 'IS oder Geltungsbereich mit verstärkter Akkreditierung und eigenen Zugriffs- und Administrationsregeln', 'SI o perímetro sometido a homologación reforzada, con sus propias reglas de acceso y administración', 'SI o perimetro soggetto a omologazione rafforzata, con proprie regole di accesso e amministrazione')),
  er(SENS, L('Divulgation d’informations sensibles à un tiers non habilité', 'Disclosure of sensitive information to an unauthorised third party', 'Offenlegung sensibler Informationen an einen unbefugten Dritten', 'Divulgación de información sensible a un tercero no autorizado', 'Divulgazione di informazioni sensibili a una terza parte non autorizzata'),
    [L('Atteinte aux intérêts fondamentaux de l’organisation', 'Damage to the organisation’s fundamental interests', 'Schädigung der grundlegenden Interessen der Organisation', 'Perjuicio a los intereses fundamentales de la organización', 'Danno agli interessi fondamentali dell’organizzazione'), L('Sanctions et perte d’habilitation', 'Sanctions and loss of accreditation', 'Sanktionen und Verlust der Akkreditierung', 'Sanciones y pérdida de habilitación', 'Sanzioni e perdita di abilitazione')], 4),
  ss(SENS, 'C', L('Un attaquant ciblé et persistant exfiltre des informations sensibles à partir d’un SI insuffisamment cloisonné (C)', 'A targeted, persistent attacker exfiltrates sensitive information from an insufficiently compartmentalised IS (C)', 'Ein gezielter, hartnäckiger Angreifer exfiltriert sensible Informationen aus einem unzureichend abgeschotteten IS (C)', 'Un atacante dirigido y persistente exfiltra información sensible de un SI insuficientemente compartimentado (C)', 'Un attaccante mirato e persistente esfiltra informazioni sensibili da un SI insufficientemente compartimentato (C)'),
    L('Passerelles et échanges avec d’autres SI non maîtrisés, administration depuis le SI général', 'Gateways and exchanges with other uncontrolled IS, administration from the general IS', 'Gateways und Austausch mit anderen, nicht kontrollierten IS, Administration aus dem allgemeinen IS', 'Pasarelas e intercambios con otros SI no controlados, administración desde el SI general', 'Gateway e scambi con altri SI non controllati, amministrazione dal SI generale'), 2, 4),
  ms(SENS, L('Homologation du SI et revue périodique de sa décision', 'Accreditation of the IS and periodic review of its decision', 'Akkreditierung des IS und regelmäßige Überprüfung der Entscheidung', 'Homologación del SI y revisión periódica de su decisión', 'Omologazione del SI e revisione periodica della relativa decisione'),
    L('Dossier d’homologation tenu à jour, risques résiduels acceptés par l’autorité, renouvellement avant échéance', 'Up-to-date accreditation file, residual risks accepted by the authority, renewal before expiry', 'Aktuelle Akkreditierungsunterlagen, vom Verantwortlichen akzeptierte Restrisiken, Erneuerung vor Ablauf', 'Expediente de homologación al día, riesgos residuales aceptados por la autoridad, renovación antes del vencimiento', 'Fascicolo di omologazione aggiornato, rischi residui accettati dall’autorità, rinnovo prima della scadenza'),
    'ORGANISATIONNELLE', 'GOUVERNANCE', 1),
  ms(SENS, L('Cloisonnement physique ou logique du SI sensible et administration depuis un système dédié', 'Physical or logical separation of the sensitive IS and administration from a dedicated system', 'Physische oder logische Trennung des sensiblen IS und Administration über ein dediziertes System', 'Separación física o lógica del SI sensible y administración desde un sistema dedicado', 'Separazione fisica o logica del SI sensibile e amministrazione da un sistema dedicato'),
    L('Aucune administration ni échange depuis le SI général sans passerelle maîtrisée et journalisée', 'No administration or exchange from the general IS without a controlled, logged gateway', 'Keine Administration oder kein Austausch aus dem allgemeinen IS ohne kontrolliertes, protokolliertes Gateway', 'Ninguna administración ni intercambio desde el SI general sin pasarela controlada y registrada', 'Nessuna amministrazione né scambio dal SI generale senza gateway controllato e registrato'),
    'TECHNIQUE', 'PROTECTION', 1),
  ms(SENS, L('Habilitation nominative, cryptographie qualifiée et journalisation renforcée des accès', 'Named clearance, qualified cryptography and reinforced access logging', 'Namentliche Ermächtigung, qualifizierte Kryptografie und verstärkte Zugriffsprotokollierung', 'Habilitación nominativa, criptografía cualificada y registro reforzado de accesos', 'Abilitazione nominativa, crittografia qualificata e registrazione rafforzata degli accessi'),
    L('Accès limité aux personnes habilitées, produits de sécurité qualifiés lorsqu’ils existent, traces conservées et revues', 'Access limited to cleared people, qualified security products where they exist, logs kept and reviewed', 'Zugriff nur für ermächtigte Personen, qualifizierte Sicherheitsprodukte, soweit vorhanden, Protokolle aufbewahrt und geprüft', 'Acceso limitado a las personas habilitadas, productos de seguridad cualificados cuando existen, trazas conservadas y revisadas', 'Accesso limitato alle persone abilitate, prodotti di sicurezza qualificati dove esistono, tracce conservate e riviste'),
    'PREVENTIVE', 'PROTECTION', 2),

  // ═══ COMBINAISONS (plusieurs patterns requis, BE-5) ════════════════════════════════════════════
  // EXPOSITION_INTERNET + SI_SENSIBLE
  bs(['EXPOSITION_INTERNET', 'SI_SENSIBLE'], L('Passerelle d’échange maîtrisée entre le service exposé et le SI sensible', 'Controlled exchange gateway between the exposed service and the sensitive IS', 'Kontrolliertes Austausch-Gateway zwischen dem exponierten Dienst und dem sensiblen IS', 'Pasarela de intercambio controlada entre el servicio expuesto y el SI sensible', 'Gateway di scambio controllato tra il servizio esposto e il SI sensibile'), 'RESEAU',
    L('Point unique, filtré et journalisé par lequel passent les échanges ; aucune connexion directe entre Internet et le SI sensible', 'Single, filtered and logged point through which exchanges pass; no direct connection between the Internet and the sensitive IS', 'Einziger, gefilterter und protokollierter Punkt für den Austausch; keine direkte Verbindung zwischen Internet und sensiblem IS', 'Punto único, filtrado y registrado por el que pasan los intercambios; ninguna conexión directa entre Internet y el SI sensible', 'Punto unico, filtrato e registrato attraverso cui passano gli scambi; nessuna connessione diretta tra Internet e SI sensibile')),
  ms(['EXPOSITION_INTERNET', 'SI_SENSIBLE'], L('Cloisonnement renforcé entre les services exposés et le SI sensible, sans flux entrant direct', 'Reinforced separation between exposed services and the sensitive IS, with no direct inbound flow', 'Verstärkte Trennung zwischen exponierten Diensten und sensiblem IS, ohne direkten eingehenden Fluss', 'Segregación reforzada entre los servicios expuestos y el SI sensible, sin flujo entrante directo', 'Separazione rafforzata tra i servizi esposti e il SI sensibile, senza flusso in entrata diretto'),
    L('Les données ne sont tirées que depuis le SI sensible, jamais poussées depuis Internet', 'Data is only pulled from the sensitive IS, never pushed from the Internet', 'Daten werden nur aus dem sensiblen IS abgerufen, nie aus dem Internet hineingeschoben', 'Los datos solo se extraen desde el SI sensible, nunca se empujan desde Internet', 'I dati sono prelevati solo dal SI sensibile, mai spinti da Internet'),
    'PREVENTIVE', 'PROTECTION', 1),
  // TELEMAINTENANCE + SI_INDUSTRIEL
  er(['TELEMAINTENANCE', 'SI_INDUSTRIEL'], L('Prise de main à distance sur des automates ou des équipements industriels par un canal de maintenance', 'Remote takeover of PLCs or industrial equipment through a maintenance channel', 'Fernübernahme von SPS oder Industrieanlagen über einen Wartungskanal', 'Toma de control remota de autómatas o equipos industriales por un canal de mantenimiento', 'Presa di controllo da remoto di PLC o apparecchiature industriali tramite un canale di manutenzione'),
    [L('Arrêt ou dégradation du procédé industriel', 'Shutdown or degradation of the industrial process', 'Stillstand oder Beeinträchtigung des Industrieprozesses', 'Parada o degradación del proceso industrial', 'Arresto o degrado del processo industriale'), L('Risque pour la sécurité des personnes et de l’environnement', 'Risk to people’s safety and the environment', 'Gefahr für Sicherheit von Personen und Umwelt', 'Riesgo para la seguridad de las personas y el medio ambiente', 'Rischio per la sicurezza delle persone e dell’ambiente')], 4),
  ms(['TELEMAINTENANCE', 'SI_INDUSTRIEL'], L('Télémaintenance industrielle encadrée : clé physique ou validation locale avant toute prise de main', 'Supervised industrial remote maintenance: physical key or on-site approval before any remote takeover', 'Beaufsichtigte industrielle Fernwartung: physischer Schlüssel oder Freigabe vor Ort vor jeder Fernübernahme', 'Telemantenimiento industrial controlado: llave física o validación local antes de cualquier toma de control', 'Teleassistenza industriale controllata: chiave fisica o approvazione locale prima di ogni presa di controllo'),
    L('Passage par une zone intermédiaire, sessions enregistrées et surveillées par un opérateur du site', 'Pass through an intermediate zone, with sessions recorded and watched by a site operator', 'Weg über eine Zwischenzone, Sitzungen aufgezeichnet und von einem Standortbetreiber überwacht', 'Paso por una zona intermedia, sesiones grabadas y vigiladas por un operador del sitio', 'Passaggio attraverso una zona intermedia, sessioni registrate e sorvegliate da un operatore del sito'),
    'PREVENTIVE', 'PROTECTION', 1),
  // SI_TPE + EXTERNALISATION_DONNEES
  er(['SI_TPE', 'EXTERNALISATION_DONNEES'], L('Dépendance à un prestataire unique, sans réversibilité : défaillance ou rupture du contrat', 'Dependence on a single provider, with no reversibility: failure or contract termination', 'Abhängigkeit von einem einzigen Dienstleister ohne Reversibilität: Ausfall oder Vertragsende', 'Dependencia de un proveedor único, sin reversibilidad: fallo o ruptura del contrato', 'Dipendenza da un fornitore unico, senza reversibilità: guasto o rottura del contratto'),
    [L('Perte d’accès aux données et aux outils', 'Loss of access to data and tools', 'Verlust des Zugriffs auf Daten und Werkzeuge', 'Pérdida de acceso a los datos y a las herramientas', 'Perdita di accesso ai dati e agli strumenti'), L('Arrêt de l’activité', 'Halt of activity', 'Stillstand der Tätigkeit', 'Parada de la actividad', 'Arresto dell’attività')], 4),
  ms(['SI_TPE', 'EXTERNALISATION_DONNEES'], L('Clause de réversibilité et copie régulière des données chez la structure elle-même', 'Reversibility clause and regular copy of the data held by the business itself', 'Reversibilitätsklausel und regelmäßige Kopie der Daten beim Betrieb selbst', 'Cláusula de reversibilidad y copia regular de los datos en poder de la propia estructura', 'Clausola di reversibilità e copia regolare dei dati presso la struttura stessa'),
    L('Exporter les données dans un format exploitable et conserver les accès d’administration aux comptes en ligne', 'Export data in a usable format and keep administration access to the online accounts', 'Daten in nutzbarem Format exportieren und Administratorzugriff auf die Online-Konten behalten', 'Exportar los datos en un formato utilizable y conservar el acceso de administración a las cuentas en línea', 'Esportare i dati in un formato utilizzabile e mantenere l’accesso di amministrazione agli account online'),
    'CORRECTIVE', 'RESILIENCE', 1),
]
