/**
 * Contenu des patterns du lot 2 et du SI standard : peu d'éléments, rangés du plus utile au moins utile (l'affichage
 * est plafonné, cf. MAX_EXEMPLES_PAR_PATTERN). Suggestions à qualifier, jamais des faits présumés.
 */
import { L, ae, bs, er, me, ms, pp, sr, ss, type PatternItem } from './exemples-patterns-core'

const STD = ['SI_STANDARD'] as const
const MOBILE = ['APPLICATIONS_MOBILES'] as const
const SAAS = ['CLOUD_SAAS'] as const
const IAAS = ['CLOUD_IAAS_PAAS'] as const
const SAUV = ['SAUVEGARDE'] as const
const SUPERV = ['SUPERVISION'] as const
const IA = ['IA_SERVICES'] as const
const ISOLE = ['SI_ISOLE'] as const
const INDUS = ['SI_INDUSTRIEL'] as const
const PATRI = ['SI_PATRIMONIAL'] as const

const INTERRUPTION = L('Interruption de l’activité', 'Business interruption', 'Unterbrechung der Tätigkeit', 'Interrupción de la actividad', 'Interruzione dell’attività')
const PERTE_DONNEES = L('Perte de données', 'Data loss', 'Datenverlust', 'Pérdida de datos', 'Perdita di dati')
const CONFIDENTIALITE = L('Atteinte à la confidentialité des données', 'Breach of data confidentiality', 'Verletzung der Vertraulichkeit der Daten', 'Vulneración de la confidencialidad de los datos', 'Violazione della riservatezza dei dati')
const IMAGE = L('Atteinte à l’image', 'Reputational damage', 'Imageschaden', 'Daño a la imagen', 'Danno all’immagine')
const FRAUDE = L('Préjudice financier (fraude)', 'Financial loss (fraud)', 'Finanzieller Schaden (Betrug)', 'Perjuicio económico (fraude)', 'Danno economico (frode)')
const REGLEMENTAIRE = L('Manquement aux obligations de protection des données', 'Breach of data protection obligations', 'Verstoß gegen Datenschutzpflichten', 'Incumplimiento de las obligaciones de protección de datos', 'Violazione degli obblighi di protezione dei dati')

export const LOT2_ITEMS: PatternItem[] = [
  // ═══ SI standard ═══════════════════════════════════════════════════════════════════════════════
  bs(STD, L('Postes de travail et serveurs du SI', 'IS workstations and servers', 'Arbeitsplätze und Server des IS', 'Puestos de trabajo y servidores del SI', 'Postazioni di lavoro e server del SI'), 'MATERIEL',
    L('Équipements courants, à tenir à jour et à inventorier', 'Everyday equipment, to keep up to date and inventoried', 'Alltägliche Geräte, die aktuell zu halten und zu inventarisieren sind', 'Equipos habituales, que deben mantenerse actualizados e inventariados', 'Apparecchiature ordinarie, da mantenere aggiornate e inventariate')),
  bs(STD, L('Annuaire des comptes et des droits (Active Directory ou équivalent)', 'Account and rights directory (Active Directory or equivalent)', 'Verzeichnis der Konten und Rechte (Active Directory oder gleichwertig)', 'Directorio de cuentas y derechos (Active Directory o equivalente)', 'Directory degli account e dei diritti (Active Directory o equivalente)'), 'LOGICIEL',
    L('Cible prioritaire : qui le contrôle contrôle tout le SI', 'Prime target: whoever controls it controls the whole IS', 'Vorrangiges Ziel: Wer es kontrolliert, kontrolliert das gesamte IS', 'Objetivo prioritario: quien lo controla controla todo el SI', 'Bersaglio prioritario: chi lo controlla controlla l’intero SI')),
  er(STD, L('Indisponibilité générale du SI après une attaque par rançongiciel', 'Complete IS outage after a ransomware attack', 'Vollständiger Ausfall des IS nach einem Ransomware-Angriff', 'Indisponibilidad general del SI tras un ataque de ransomware', 'Indisponibilità generale del SI dopo un attacco ransomware'), [INTERRUPTION, PERTE_DONNEES], 4),
  ss(STD, 'D', L('Un rançongiciel entré par un poste se propage et chiffre les serveurs et les sauvegardes accessibles (D)', 'Ransomware entering through a workstation spreads and encrypts servers and reachable backups (D)', 'Über einen Arbeitsplatz eingedrungene Ransomware breitet sich aus und verschlüsselt Server und erreichbare Sicherungen (D)', 'Un ransomware que entra por un puesto se propaga y cifra los servidores y las copias de seguridad accesibles (D)', 'Un ransomware entrato da una postazione si propaga e cifra i server e i backup raggiungibili (D)'),
    L('Scénario le plus fréquent pour un SI sans particularité', 'Most frequent scenario for an IS with no particular feature', 'Häufigstes Szenario für ein IS ohne Besonderheiten', 'Escenario más frecuente para un SI sin particularidades', 'Scenario più frequente per un SI senza particolarità'), 3, 4),
  ae(STD, 'ACCES_INITIAL', 'T1078', L('Utilisation d’un compte valide dérobé (mot de passe faible ou réutilisé)', 'Use of a stolen valid account (weak or reused password)', 'Nutzung eines gestohlenen gültigen Kontos (schwaches oder wiederverwendetes Passwort)', 'Uso de una cuenta válida robada (contraseña débil o reutilizada)', 'Uso di un account valido rubato (password debole o riutilizzata)'),
    L('Identifiants obtenus par hameçonnage, fuite ou devinés', 'Credentials obtained by phishing, leak or guessing', 'Durch Phishing, Leak oder Erraten erlangte Zugangsdaten', 'Credenciales obtenidas por phishing, fuga o adivinadas', 'Credenziali ottenute tramite phishing, fuga o indovinate')),
  ms(STD, L('Hygiène de base : mises à jour, comptes nominatifs, mots de passe robustes, protection antivirale', 'Basic hygiene: updates, named accounts, strong passwords, antivirus protection', 'Grundhygiene: Updates, persönliche Konten, starke Passwörter, Virenschutz', 'Higiene básica: actualizaciones, cuentas nominativas, contraseñas robustas, protección antivirus', 'Igiene di base: aggiornamenti, account nominativi, password robuste, protezione antivirus'),
    L('Socle qui évite la majorité des attaques opportunistes', 'Baseline that prevents most opportunistic attacks', 'Basis, die die meisten opportunistischen Angriffe verhindert', 'Base que evita la mayoría de los ataques oportunistas', 'Base che evita la maggior parte degli attacchi opportunistici'), 'PREVENTIVE', 'PROTECTION', 1),
  ms(STD, L('Sauvegardes dont une copie hors ligne, testées par une restauration régulière', 'Backups including an offline copy, tested by regular restores', 'Sicherungen mit einer Offline-Kopie, durch regelmäßige Wiederherstellung getestet', 'Copias de seguridad con una copia fuera de línea, probadas con restauraciones periódicas', 'Backup con una copia offline, verificati con ripristini regolari'),
    L('Condition pour repartir après un rançongiciel', 'Prerequisite to recover after ransomware', 'Voraussetzung für den Wiederanlauf nach Ransomware', 'Condición para recuperarse tras un ransomware', 'Condizione per ripartire dopo un ransomware'), 'CORRECTIVE', 'RESILIENCE', 1),

  // ═══ Applications et terminaux mobiles ═════════════════════════════════════════════════════════
  bs(MOBILE, L('Application mobile publiée et l’API qu’elle appelle', 'Published mobile app and the API it calls', 'Veröffentlichte mobile App und die von ihr aufgerufene API', 'Aplicación móvil publicada y la API a la que llama', 'App mobile pubblicata e l’API che richiama'), 'LOGICIEL',
    L('L’application peut être analysée par n’importe qui : la sécurité doit reposer sur l’API', 'Anyone can analyse the app: security must rely on the API', 'Jeder kann die App analysieren: Die Sicherheit muss auf der API beruhen', 'Cualquiera puede analizar la aplicación: la seguridad debe basarse en la API', 'Chiunque può analizzare l’app: la sicurezza deve basarsi sull’API')),
  bs(MOBILE, L('Terminaux mobiles professionnels et leur gestion de flotte (MDM)', 'Corporate mobile devices and their fleet management (MDM)', 'Dienstliche Mobilgeräte und ihre Flottenverwaltung (MDM)', 'Terminales móviles profesionales y su gestión de flota (MDM)', 'Dispositivi mobili aziendali e la loro gestione (MDM)'), 'MATERIEL',
    L('Appareils souvent perdus, volés ou utilisés hors des locaux', 'Devices often lost, stolen or used off-site', 'Geräte, die oft verloren, gestohlen oder außer Haus genutzt werden', 'Dispositivos a menudo perdidos, robados o usados fuera de las instalaciones', 'Dispositivi spesso persi, rubati o usati fuori sede')),
  er(MOBILE, L('Prise de contrôle de comptes d’utilisateurs par une application clonée ou une API mal protégée', 'Takeover of user accounts through a cloned app or a poorly protected API', 'Übernahme von Benutzerkonten über eine geklonte App oder eine schlecht geschützte API', 'Toma de control de cuentas de usuarios mediante una aplicación clonada o una API mal protegida', 'Presa di controllo di account utente tramite un’app clonata o un’API mal protetta'), [FRAUDE, IMAGE], 3),
  sr(MOBILE, L('Fraudeur diffusant des applications clonées ou détournant l’API mobile', 'Fraudster spreading cloned apps or abusing the mobile API', 'Betrüger, der geklonte Apps verbreitet oder die mobile API missbraucht', 'Defraudador que difunde aplicaciones clonadas o desvía la API móvil', 'Truffatore che diffonde app clonate o abusa dell’API mobile'), 'CYBERCRIMINEL',
    L('Acteur qui analyse l’application pour automatiser des fraudes ou piéger les utilisateurs', 'Actor analysing the app to automate fraud or trap users', 'Akteur, der die App analysiert, um Betrug zu automatisieren oder Nutzer zu täuschen', 'Actor que analiza la aplicación para automatizar fraudes o engañar a los usuarios', 'Attore che analizza l’app per automatizzare frodi o ingannare gli utenti'),
    L('Gain financier, revente de comptes', 'Financial gain, account resale', 'Finanzieller Gewinn, Weiterverkauf von Konten', 'Beneficio económico, reventa de cuentas', 'Guadagno economico, rivendita di account'),
    L('Outils de rétro-ingénierie, faux magasins d’applications, robots', 'Reverse-engineering tools, fake app stores, bots', 'Reverse-Engineering-Werkzeuge, gefälschte App-Stores, Bots', 'Herramientas de ingeniería inversa, tiendas de aplicaciones falsas, bots', 'Strumenti di reverse engineering, falsi app store, bot'), 3),
  ss(MOBILE, 'C', L('Un fraudeur trouve dans l’application des secrets ou des appels d’API non contrôlés et accède aux comptes d’autres utilisateurs (C)', 'A fraudster finds secrets or unchecked API calls in the app and accesses other users’ accounts (C)', 'Ein Betrüger findet in der App Geheimnisse oder ungeprüfte API-Aufrufe und greift auf Konten anderer Nutzer zu (C)', 'Un defraudador encuentra en la aplicación secretos o llamadas a la API no controladas y accede a las cuentas de otros usuarios (C)', 'Un truffatore trova nell’app segreti o chiamate API non controllate e accede agli account di altri utenti (C)'),
    L('Contrôles faits dans l’application et non par le serveur', 'Checks performed in the app rather than by the server', 'Prüfungen in der App statt auf dem Server', 'Controles realizados en la aplicación y no por el servidor', 'Controlli effettuati nell’app e non dal server'), 3, 3),
  pp(MOBILE, L('Éditeur ou agence de développement de l’application mobile', 'Mobile app publisher or development agency', 'Herausgeber oder Entwicklungsagentur der mobilen App', 'Editor o agencia de desarrollo de la aplicación móvil', 'Editore o agenzia di sviluppo dell’app mobile'), 'PRESTATAIRE', 3, 3, 2, 2),
  ae(MOBILE, 'ACCES_INITIAL', 'T1190', L('Appel direct de l’API mobile en contournant les contrôles de l’application', 'Direct call to the mobile API bypassing the app’s checks', 'Direkter Aufruf der mobilen API unter Umgehung der App-Prüfungen', 'Llamada directa a la API móvil eludiendo los controles de la aplicación', 'Chiamata diretta all’API mobile aggirando i controlli dell’app'),
    L('Requêtes forgées pour lire ou modifier les données d’autres comptes', 'Forged requests to read or change other accounts’ data', 'Gefälschte Anfragen, um Daten anderer Konten zu lesen oder zu ändern', 'Peticiones falsificadas para leer o modificar datos de otras cuentas', 'Richieste contraffatte per leggere o modificare i dati di altri account')),
  me(MOBILE, L('Développement sécurisé et test d’intrusion de l’application avant chaque version majeure, imposés au prestataire', 'Secure development and penetration test of the app before each major release, required from the provider', 'Sichere Entwicklung und Penetrationstest der App vor jeder Hauptversion, vom Dienstleister verlangt', 'Desarrollo seguro y prueba de intrusión de la aplicación antes de cada versión principal, exigidos al proveedor', 'Sviluppo sicuro e penetration test dell’app prima di ogni versione principale, richiesti al fornitore'), 'ORGANISATIONNELLE', '8.30',
    L('Exigences écrites dans le contrat de développement', 'Requirements written into the development contract', 'Im Entwicklungsvertrag festgelegte Anforderungen', 'Requisitos escritos en el contrato de desarrollo', 'Requisiti scritti nel contratto di sviluppo')),
  ms(MOBILE, L('Tous les contrôles d’accès faits côté serveur : l’API ne fait jamais confiance à l’application', 'All access checks on the server side: the API never trusts the app', 'Alle Zugriffsprüfungen serverseitig: Die API vertraut der App nie', 'Todos los controles de acceso en el servidor: la API nunca confía en la aplicación', 'Tutti i controlli di accesso lato server: l’API non si fida mai dell’app'),
    L('Aucun secret ni règle de sécurité ne repose sur le code de l’application', 'No secret or security rule relies on the app’s code', 'Kein Geheimnis und keine Sicherheitsregel beruht auf dem App-Code', 'Ningún secreto ni regla de seguridad depende del código de la aplicación', 'Nessun segreto o regola di sicurezza dipende dal codice dell’app'), 'PREVENTIVE', 'PROTECTION', 1),
  ms(MOBILE, L('Gestion de flotte : chiffrement, verrouillage et effacement à distance des terminaux perdus', 'Fleet management: encryption, locking and remote wipe of lost devices', 'Flottenverwaltung: Verschlüsselung, Sperre und Fernlöschung verlorener Geräte', 'Gestión de flota: cifrado, bloqueo y borrado remoto de los terminales perdidos', 'Gestione della flotta: cifratura, blocco e cancellazione remota dei dispositivi persi'),
    L('Limite l’impact d’un terminal perdu ou volé', 'Limits the impact of a lost or stolen device', 'Begrenzt die Folgen eines verlorenen oder gestohlenen Geräts', 'Limita el impacto de un terminal perdido o robado', 'Limita l’impatto di un dispositivo perso o rubato'), 'TECHNIQUE', 'PROTECTION', 2),

  // ═══ Services en ligne (SaaS) ══════════════════════════════════════════════════════════════════
  bs(SAAS, L('Services en ligne (messagerie, collaboratif, applications métier) et leurs comptes d’administration', 'Online services (mail, collaboration, business apps) and their admin accounts', 'Onlinedienste (E-Mail, Zusammenarbeit, Fachanwendungen) und ihre Administratorkonten', 'Servicios en línea (correo, colaboración, aplicaciones de negocio) y sus cuentas de administración', 'Servizi online (posta, collaborazione, applicazioni di business) e i relativi account di amministrazione'), 'LOGICIEL',
    L('Accessibles depuis Internet : le compte est la seule barrière', 'Reachable from the Internet: the account is the only barrier', 'Aus dem Internet erreichbar: Das Konto ist die einzige Barriere', 'Accesibles desde Internet: la cuenta es la única barrera', 'Raggiungibili da Internet: l’account è l’unica barriera')),
  bs(SAAS, L('Données de l’organisation stockées chez l’éditeur du service', 'Organisation data stored by the service provider', 'Beim Diensteanbieter gespeicherte Daten der Organisation', 'Datos de la organización almacenados por el proveedor del servicio', 'Dati dell’organizzazione conservati presso il fornitore del servizio'), 'DONNEES',
    L('Localisation, réversibilité et durée de conservation à connaître', 'Location, reversibility and retention period to be known', 'Standort, Reversibilität und Aufbewahrungsdauer müssen bekannt sein', 'Ubicación, reversibilidad y plazo de conservación que deben conocerse', 'Ubicazione, reversibilità e durata di conservazione da conoscere')),
  er(SAAS, L('Fuite de données par un partage public ou une mauvaise configuration du service en ligne', 'Data leak through a public share or a misconfigured online service', 'Datenabfluss durch eine öffentliche Freigabe oder einen falsch konfigurierten Onlinedienst', 'Fuga de datos por un enlace público o una mala configuración del servicio en línea', 'Fuga di dati tramite una condivisione pubblica o un servizio online mal configurato'), [CONFIDENTIALITE, REGLEMENTAIRE], 3),
  ss(SAAS, 'C', L('Un attaquant prend le contrôle d’un compte d’administration du service en ligne et exporte les données (C)', 'An attacker takes over an admin account of the online service and exports the data (C)', 'Ein Angreifer übernimmt ein Administratorkonto des Onlinedienstes und exportiert die Daten (C)', 'Un atacante toma el control de una cuenta de administración del servicio en línea y exporta los datos (C)', 'Un attaccante prende il controllo di un account di amministrazione del servizio online ed esporta i dati (C)'),
    L('Compte sans second facteur ou jeton de session volé', 'Account without second factor or stolen session token', 'Konto ohne zweiten Faktor oder gestohlenes Sitzungstoken', 'Cuenta sin segundo factor o token de sesión robado', 'Account senza secondo fattore o token di sessione rubato'), 3, 4),
  // Libellé identique à l'exemple générique (5 langues) : une seule ligne, badge « architecture ».
  pp(SAAS, L('Fournisseur SaaS (Office 365, etc.)', 'SaaS vendor (Office 365, etc.)', 'SaaS-Anbieter (Office 365, usw.)', 'Proveedor SaaS (Office 365, etc.)', 'Fornitore SaaS (Office 365, ecc.)'), 'FOURNISSEUR', 3, 2, 4, 3),
  ae(SAAS, 'ACCES_INITIAL', 'T1528', L('Vol d’un jeton d’accès par une fausse demande d’autorisation d’application', 'Theft of an access token through a fake app consent request', 'Diebstahl eines Zugriffstokens über eine gefälschte App-Berechtigungsanfrage', 'Robo de un token de acceso mediante una falsa solicitud de autorización de aplicación', 'Furto di un token di accesso tramite una falsa richiesta di autorizzazione di un’app'),
    L('Contourne le mot de passe et le second facteur', 'Bypasses the password and the second factor', 'Umgeht Passwort und zweiten Faktor', 'Elude la contraseña y el segundo factor', 'Aggira la password e il secondo fattore')),
  me(SAAS, L('Clauses de réversibilité, de localisation des données et de notification d’incident dans le contrat du service', 'Reversibility, data location and incident notification clauses in the service contract', 'Klauseln zu Reversibilität, Datenstandort und Vorfallmeldung im Dienstvertrag', 'Cláusulas de reversibilidad, ubicación de los datos y notificación de incidentes en el contrato del servicio', 'Clausole di reversibilità, ubicazione dei dati e notifica degli incidenti nel contratto del servizio'), 'ORGANISATIONNELLE', '5.23',
    L('Vérifiées avant souscription et revues au renouvellement', 'Checked before subscribing and reviewed at renewal', 'Vor dem Abschluss geprüft und bei Verlängerung überprüft', 'Verificadas antes de la suscripción y revisadas en la renovación', 'Verificate prima della sottoscrizione e riesaminate al rinnovo')),
  ms(SAAS, L('Authentification multifacteur et comptes d’administration dédiés pour les services en ligne', 'Multi-factor authentication and dedicated admin accounts for online services', 'Mehrfaktor-Authentifizierung und eigene Administratorkonten für Onlinedienste', 'Autenticación multifactor y cuentas de administración dedicadas para los servicios en línea', 'Autenticazione a più fattori e account di amministrazione dedicati per i servizi online'),
    L('Mesure la plus efficace contre la prise de compte', 'Most effective measure against account takeover', 'Wirksamste Maßnahme gegen Kontoübernahme', 'Medida más eficaz contra la toma de cuentas', 'Misura più efficace contro il furto di account'), 'PREVENTIVE', 'PROTECTION', 1),
  ms(SAAS, L('Revue périodique des partages externes et de la configuration de sécurité du service', 'Periodic review of external shares and of the service’s security configuration', 'Regelmäßige Überprüfung externer Freigaben und der Sicherheitskonfiguration des Dienstes', 'Revisión periódica de los enlaces externos y de la configuración de seguridad del servicio', 'Revisione periodica delle condivisioni esterne e della configurazione di sicurezza del servizio'),
    L('Détecte les partages publics oubliés', 'Detects forgotten public shares', 'Erkennt vergessene öffentliche Freigaben', 'Detecta enlaces públicos olvidados', 'Rileva condivisioni pubbliche dimenticate'), 'DETECTIVE', 'DEFENSE', 2),

  // ═══ Hébergement en nuage (IaaS / PaaS) ════════════════════════════════════════════════════════
  bs(IAAS, L('Comptes, rôles et clés d’accès de la plateforme cloud', 'Cloud platform accounts, roles and access keys', 'Konten, Rollen und Zugriffsschlüssel der Cloud-Plattform', 'Cuentas, roles y claves de acceso de la plataforma en la nube', 'Account, ruoli e chiavi di accesso della piattaforma cloud'), 'LOGICIEL',
    L('Une clé d’accès trop large donne la main sur toute l’infrastructure', 'An overly broad access key gives control of the whole infrastructure', 'Ein zu weit gefasster Zugriffsschlüssel gibt Kontrolle über die gesamte Infrastruktur', 'Una clave de acceso demasiado amplia da el control de toda la infraestructura', 'Una chiave di accesso troppo ampia dà il controllo dell’intera infrastruttura')),
  bs(IAAS, L('Stockages et bases de données hébergés', 'Hosted storage and databases', 'Gehostete Speicher und Datenbanken', 'Almacenamientos y bases de datos alojados', 'Storage e database ospitati'), 'DONNEES',
    L('Peuvent devenir publics par une simple erreur de configuration', 'Can become public through a simple configuration error', 'Können durch einen einfachen Konfigurationsfehler öffentlich werden', 'Pueden volverse públicos por un simple error de configuración', 'Possono diventare pubblici per un semplice errore di configurazione')),
  er(IAAS, L('Exposition publique de données par un stockage cloud mal configuré', 'Public exposure of data through a misconfigured cloud storage', 'Öffentliche Preisgabe von Daten durch einen falsch konfigurierten Cloud-Speicher', 'Exposición pública de datos por un almacenamiento en la nube mal configurado', 'Esposizione pubblica di dati tramite uno storage cloud mal configurato'), [CONFIDENTIALITE, IMAGE], 3),
  ss(IAAS, 'C', L('Un attaquant récupère une clé d’accès cloud publiée par erreur et exfiltre les stockages (C)', 'An attacker retrieves a cloud access key published by mistake and exfiltrates the storage (C)', 'Ein Angreifer erlangt einen versehentlich veröffentlichten Cloud-Zugriffsschlüssel und exfiltriert die Speicher (C)', 'Un atacante obtiene una clave de acceso a la nube publicada por error y exfiltra los almacenamientos (C)', 'Un attaccante recupera una chiave di accesso cloud pubblicata per errore ed esfiltra gli storage (C)'),
    L('Clé laissée dans un dépôt de code ou une image', 'Key left in a code repository or an image', 'In einem Code-Repository oder einem Image zurückgelassener Schlüssel', 'Clave olvidada en un repositorio de código o una imagen', 'Chiave lasciata in un repository di codice o in un’immagine'), 3, 4),
  pp(IAAS, L('Hébergeur cloud (AWS/Azure/GCP)', 'Cloud host (AWS/Azure/GCP)', 'Cloud-Anbieter (AWS/Azure/GCP)', 'Proveedor de nube (AWS/Azure/GCP)', 'Provider cloud (AWS/Azure/GCP)'), 'FOURNISSEUR', 4, 3, 4, 3),
  ae(IAAS, 'ACCES_INITIAL', 'T1552', L('Récupération de secrets ou de clés d’accès laissés dans du code ou des images', 'Retrieval of secrets or access keys left in code or images', 'Auslesen von Geheimnissen oder Zugriffsschlüsseln in Code oder Images', 'Recuperación de secretos o claves de acceso dejados en el código o en imágenes', 'Recupero di segreti o chiavi di accesso lasciati nel codice o nelle immagini'),
    L('Recherche automatisée dans les dépôts publics', 'Automated search in public repositories', 'Automatisierte Suche in öffentlichen Repositories', 'Búsqueda automatizada en repositorios públicos', 'Ricerca automatizzata nei repository pubblici')),
  me(IAAS, L('Responsabilités partagées documentées avec le fournisseur et suivi de ses attestations de sécurité', 'Shared responsibilities documented with the provider and follow-up of its security attestations', 'Mit dem Anbieter dokumentierte geteilte Verantwortung und Verfolgung seiner Sicherheitsnachweise', 'Responsabilidades compartidas documentadas con el proveedor y seguimiento de sus certificaciones de seguridad', 'Responsabilità condivise documentate con il fornitore e verifica delle sue attestazioni di sicurezza'), 'ORGANISATIONNELLE', '5.23',
    L('Ce que le fournisseur sécurise et ce qui reste à votre charge', 'What the provider secures and what remains your responsibility', 'Was der Anbieter absichert und was in Ihrer Verantwortung bleibt', 'Lo que asegura el proveedor y lo que queda a su cargo', 'Ciò che il fornitore protegge e ciò che resta a vostro carico')),
  ms(IAAS, L('Moindre privilège sur les rôles cloud et contrôle automatique des configurations (stockages publics, ports ouverts)', 'Least privilege on cloud roles and automatic configuration checks (public storage, open ports)', 'Minimale Rechte für Cloud-Rollen und automatische Konfigurationsprüfung (öffentliche Speicher, offene Ports)', 'Mínimo privilegio en los roles de la nube y control automático de las configuraciones (almacenamientos públicos, puertos abiertos)', 'Privilegio minimo sui ruoli cloud e controllo automatico delle configurazioni (storage pubblici, porte aperte)'),
    L('Évite les expositions accidentelles', 'Prevents accidental exposure', 'Verhindert versehentliche Preisgabe', 'Evita las exposiciones accidentales', 'Evita esposizioni accidentali'), 'PREVENTIVE', 'PROTECTION', 1),
  ms(IAAS, L('Journalisation des actions d’administration de la plateforme cloud', 'Logging of cloud platform administration actions', 'Protokollierung der Verwaltungsaktionen auf der Cloud-Plattform', 'Registro de las acciones de administración de la plataforma en la nube', 'Registrazione delle azioni di amministrazione della piattaforma cloud'),
    L('Permet de retracer l’usage d’une clé volée', 'Makes it possible to trace the use of a stolen key', 'Ermöglicht die Rückverfolgung eines gestohlenen Schlüssels', 'Permite rastrear el uso de una clave robada', 'Consente di ricostruire l’uso di una chiave rubata'), 'DETECTIVE', 'DEFENSE', 2),

  // ═══ Infrastructure de sauvegarde ══════════════════════════════════════════════════════════════
  bs(SAUV, L('Serveurs, logiciel et console de sauvegarde', 'Backup servers, software and console', 'Backup-Server, -Software und -Konsole', 'Servidores, software y consola de copias de seguridad', 'Server, software e console di backup'), 'LOGICIEL',
    L('Cible prioritaire des rançongiciels avant le chiffrement', 'Prime ransomware target before encryption', 'Vorrangiges Ziel von Ransomware vor der Verschlüsselung', 'Objetivo prioritario del ransomware antes del cifrado', 'Bersaglio prioritario dei ransomware prima della cifratura')),
  bs(SAUV, L('Copies de sauvegarde hors ligne ou immuables', 'Offline or immutable backup copies', 'Offline- oder unveränderliche Sicherungskopien', 'Copias de seguridad fuera de línea o inmutables', 'Copie di backup offline o immutabili'), 'DONNEES',
    L('Dernier recours si tout le reste est chiffré', 'Last resort if everything else is encrypted', 'Letzter Ausweg, wenn alles andere verschlüsselt ist', 'Último recurso si todo lo demás está cifrado', 'Ultima risorsa se tutto il resto è cifrato')),
  er(SAUV, L('Impossibilité de restaurer après un incident : sauvegardes chiffrées, effacées ou jamais testées', 'Inability to restore after an incident: backups encrypted, erased or never tested', 'Keine Wiederherstellung nach einem Vorfall möglich: Sicherungen verschlüsselt, gelöscht oder nie getestet', 'Imposibilidad de restaurar tras un incidente: copias cifradas, borradas o nunca probadas', 'Impossibilità di ripristinare dopo un incidente: backup cifrati, cancellati o mai verificati'), [INTERRUPTION, PERTE_DONNEES], 4),
  ss(SAUV, 'D', L('Un rançongiciel détruit d’abord les sauvegardes accessibles depuis le SI, puis chiffre la production (D)', 'Ransomware first destroys the backups reachable from the IS, then encrypts production (D)', 'Ransomware zerstört zuerst die vom IS erreichbaren Sicherungen und verschlüsselt dann die Produktion (D)', 'Un ransomware destruye primero las copias accesibles desde el SI y luego cifra la producción (D)', 'Un ransomware distrugge prima i backup raggiungibili dal SI, poi cifra la produzione (D)'),
    L('Console de sauvegarde gérée avec les comptes de l’annuaire de production', 'Backup console managed with production directory accounts', 'Backup-Konsole mit Konten des Produktionsverzeichnisses verwaltet', 'Consola de copias gestionada con las cuentas del directorio de producción', 'Console di backup gestita con gli account della directory di produzione'), 3, 4),
  pp(SAUV, L('Prestataire de sauvegarde externalisée', 'Outsourced backup provider', 'Dienstleister für ausgelagerte Datensicherung', 'Proveedor de copias de seguridad externalizadas', 'Fornitore di backup esternalizzato'), 'PRESTATAIRE', 3, 3, 3, 3),
  ae(SAUV, 'IMPACT', 'T1490', L('Suppression des sauvegardes et des copies instantanées avant le chiffrement', 'Deletion of backups and snapshots before encryption', 'Löschen von Sicherungen und Snapshots vor der Verschlüsselung', 'Eliminación de las copias de seguridad e instantáneas antes del cifrado', 'Cancellazione di backup e snapshot prima della cifratura'),
    L('Empêche toute restauration rapide', 'Prevents any quick restore', 'Verhindert jede schnelle Wiederherstellung', 'Impide cualquier restauración rápida', 'Impedisce qualsiasi ripristino rapido')),
  me(SAUV, L('Délais de restauration garantis par contrat et tests de restauration conjoints avec le prestataire', 'Restore times guaranteed by contract and joint restore tests with the provider', 'Vertraglich garantierte Wiederherstellungszeiten und gemeinsame Wiederherstellungstests mit dem Dienstleister', 'Plazos de restauración garantizados por contrato y pruebas de restauración conjuntas con el proveedor', 'Tempi di ripristino garantiti dal contratto e test di ripristino congiunti con il fornitore'), 'ORGANISATIONNELLE', '8.13',
    L('Le délai réel est mesuré, pas supposé', 'The actual time is measured, not assumed', 'Die tatsächliche Dauer wird gemessen, nicht angenommen', 'El plazo real se mide, no se supone', 'Il tempo reale viene misurato, non presunto')),
  ms(SAUV, L('Au moins une copie hors ligne ou immuable, isolée de l’annuaire de production', 'At least one offline or immutable copy, isolated from the production directory', 'Mindestens eine Offline- oder unveränderliche Kopie, getrennt vom Produktionsverzeichnis', 'Al menos una copia fuera de línea o inmutable, aislada del directorio de producción', 'Almeno una copia offline o immutabile, isolata dalla directory di produzione'),
    L('Un attaquant administrateur du SI ne peut pas l’effacer', 'An attacker with IS admin rights cannot erase it', 'Ein Angreifer mit IS-Administratorrechten kann sie nicht löschen', 'Un atacante administrador del SI no puede borrarla', 'Un attaccante amministratore del SI non può cancellarla'), 'PREVENTIVE', 'RESILIENCE', 1),
  ms(SAUV, L('Tests de restauration réguliers avec mesure du délai réel', 'Regular restore tests measuring the actual time', 'Regelmäßige Wiederherstellungstests mit Messung der tatsächlichen Dauer', 'Pruebas de restauración periódicas con medición del plazo real', 'Test di ripristino regolari con misura del tempo reale'),
    L('Confronte le délai réel aux besoins des métiers', 'Compares the actual time with business needs', 'Vergleicht die tatsächliche Dauer mit dem Bedarf der Fachbereiche', 'Compara el plazo real con las necesidades del negocio', 'Confronta il tempo reale con le esigenze del business'), 'CORRECTIVE', 'RESILIENCE', 1),

  // ═══ Journalisation et supervision ═════════════════════════════════════════════════════════════
  bs(SUPERV, L('Collecte centralisée des journaux et outil de supervision de sécurité', 'Centralised log collection and security monitoring tool', 'Zentrale Protokollsammlung und Sicherheitsüberwachungswerkzeug', 'Recogida centralizada de registros y herramienta de supervisión de seguridad', 'Raccolta centralizzata dei log e strumento di monitoraggio della sicurezza'), 'LOGICIEL',
    L('Sans journaux, une attaque passe inaperçue et ne peut pas être reconstituée', 'Without logs, an attack goes unnoticed and cannot be reconstructed', 'Ohne Protokolle bleibt ein Angriff unbemerkt und kann nicht rekonstruiert werden', 'Sin registros, un ataque pasa desapercibido y no puede reconstruirse', 'Senza log, un attacco passa inosservato e non può essere ricostruito')),
  er(SUPERV, L('Attaque non détectée pendant des semaines faute de journaux exploitables', 'Attack undetected for weeks for lack of usable logs', 'Wochenlang unentdeckter Angriff mangels verwertbarer Protokolle', 'Ataque no detectado durante semanas por falta de registros utilizables', 'Attacco non rilevato per settimane per mancanza di log utilizzabili'), [CONFIDENTIALITE, INTERRUPTION], 3),
  ss(SUPERV, 'I', L('Un attaquant désactive les outils de sécurité et efface les journaux pour masquer ses actions (I)', 'An attacker disables security tools and erases logs to hide their actions (I)', 'Ein Angreifer deaktiviert Sicherheitswerkzeuge und löscht Protokolle, um seine Aktionen zu verbergen (I)', 'Un atacante desactiva las herramientas de seguridad y borra los registros para ocultar sus acciones (I)', 'Un attaccante disattiva gli strumenti di sicurezza e cancella i log per nascondere le proprie azioni (I)'),
    L('Journaux conservés sur les machines compromises', 'Logs kept on the compromised machines', 'Protokolle auf den kompromittierten Rechnern gespeichert', 'Registros conservados en las máquinas comprometidas', 'Log conservati sulle macchine compromesse'), 2, 3),
  pp(SUPERV, L('Prestataire de supervision de sécurité (SOC externalisé)', 'Security monitoring provider (outsourced SOC)', 'Dienstleister für Sicherheitsüberwachung (ausgelagertes SOC)', 'Proveedor de supervisión de seguridad (SOC externalizado)', 'Fornitore di monitoraggio della sicurezza (SOC esternalizzato)'), 'PRESTATAIRE', 3, 3, 3, 3),
  ae(SUPERV, 'PERSISTANCE', 'T1562', L('Désactivation des agents de sécurité et effacement des journaux', 'Disabling security agents and erasing logs', 'Deaktivieren von Sicherheitsagenten und Löschen von Protokollen', 'Desactivación de los agentes de seguridad y borrado de los registros', 'Disattivazione degli agenti di sicurezza e cancellazione dei log'),
    L('Prépare une action discrète et durable', 'Prepares a discreet and lasting action', 'Bereitet eine unauffällige und dauerhafte Aktion vor', 'Prepara una acción discreta y duradera', 'Prepara un’azione discreta e duratura')),
  me(SUPERV, L('Périmètre supervisé, délais d’alerte et escalade définis dans le contrat avec le SOC', 'Monitored scope, alert times and escalation defined in the SOC contract', 'Überwachter Umfang, Alarmierungsfristen und Eskalation im SOC-Vertrag festgelegt', 'Perímetro supervisado, plazos de alerta y escalado definidos en el contrato con el SOC', 'Perimetro monitorato, tempi di allerta ed escalation definiti nel contratto con il SOC'), 'ORGANISATIONNELLE', '5.22',
    L('Revus à chaque incident réel ou exercice', 'Reviewed after each real incident or exercise', 'Nach jedem echten Vorfall oder jeder Übung überprüft', 'Revisados tras cada incidente real o ejercicio', 'Riesaminati dopo ogni incidente reale o esercitazione')),
  ms(SUPERV, L('Journaux des accès et des actions sensibles centralisés, protégés et conservés', 'Logs of sensitive access and actions centralised, protected and retained', 'Protokolle sensibler Zugriffe und Aktionen zentralisiert, geschützt und aufbewahrt', 'Registros de los accesos y acciones sensibles centralizados, protegidos y conservados', 'Log degli accessi e delle azioni sensibili centralizzati, protetti e conservati'),
    L('Hors de portée d’un attaquant présent sur les machines', 'Out of reach of an attacker on the machines', 'Außer Reichweite eines Angreifers auf den Rechnern', 'Fuera del alcance de un atacante presente en las máquinas', 'Fuori dalla portata di un attaccante presente sulle macchine'), 'DETECTIVE', 'DEFENSE', 1),
  ms(SUPERV, L('Règles de détection revues après chaque incident et chaque exercice', 'Detection rules reviewed after each incident and exercise', 'Erkennungsregeln nach jedem Vorfall und jeder Übung überprüft', 'Reglas de detección revisadas tras cada incidente y ejercicio', 'Regole di rilevamento riesaminate dopo ogni incidente ed esercitazione'),
    L('La détection progresse avec l’expérience', 'Detection improves with experience', 'Die Erkennung verbessert sich mit der Erfahrung', 'La detección mejora con la experiencia', 'Il rilevamento migliora con l’esperienza'), 'DETECTIVE', 'DEFENSE', 2),

  // ═══ Services d’intelligence artificielle ══════════════════════════════════════════════════════
  bs(IA, L('Services d’IA utilisés par les collaborateurs (assistants, traduction, synthèse)', 'AI services used by staff (assistants, translation, summarisation)', 'Von Mitarbeitenden genutzte KI-Dienste (Assistenten, Übersetzung, Zusammenfassung)', 'Servicios de IA utilizados por el personal (asistentes, traducción, síntesis)', 'Servizi di IA usati dal personale (assistenti, traduzione, sintesi)'), 'LOGICIEL',
    L('Souvent adoptés sans validation : à recenser', 'Often adopted without approval: to be listed', 'Oft ohne Freigabe eingeführt: zu erfassen', 'A menudo adoptados sin validación: hay que inventariarlos', 'Spesso adottati senza approvazione: da censire')),
  bs(IA, L('Données et documents transmis aux modèles d’IA', 'Data and documents sent to AI models', 'An KI-Modelle übermittelte Daten und Dokumente', 'Datos y documentos enviados a los modelos de IA', 'Dati e documenti inviati ai modelli di IA'), 'DONNEES',
    L('Peuvent sortir de l’organisation à chaque requête', 'May leave the organisation with every request', 'Können die Organisation bei jeder Anfrage verlassen', 'Pueden salir de la organización con cada consulta', 'Possono uscire dall’organizzazione a ogni richiesta')),
  er(IA, L('Divulgation de données confidentielles ou personnelles saisies dans un service d’IA externe', 'Disclosure of confidential or personal data entered into an external AI service', 'Offenlegung vertraulicher oder personenbezogener Daten, die in einen externen KI-Dienst eingegeben wurden', 'Divulgación de datos confidenciales o personales introducidos en un servicio de IA externo', 'Divulgazione di dati riservati o personali inseriti in un servizio di IA esterno'), [CONFIDENTIALITE, REGLEMENTAIRE], 3),
  sr(IA, L('Attaquant manipulant un assistant d’IA par des instructions cachées', 'Attacker manipulating an AI assistant through hidden instructions', 'Angreifer, der einen KI-Assistenten über versteckte Anweisungen manipuliert', 'Atacante que manipula un asistente de IA mediante instrucciones ocultas', 'Attaccante che manipola un assistente di IA con istruzioni nascoste'), 'CYBERCRIMINEL',
    L('Acteur qui glisse des instructions dans des documents, courriels ou pages pour détourner un assistant connecté aux données', 'Actor slipping instructions into documents, emails or pages to hijack an assistant connected to data', 'Akteur, der Anweisungen in Dokumente, E-Mails oder Seiten einschleust, um einen mit Daten verbundenen Assistenten zu kapern', 'Actor que introduce instrucciones en documentos, correos o páginas para desviar un asistente conectado a los datos', 'Attore che inserisce istruzioni in documenti, e-mail o pagine per dirottare un assistente collegato ai dati'),
    L('Vol de données, fraude', 'Data theft, fraud', 'Datendiebstahl, Betrug', 'Robo de datos, fraude', 'Furto di dati, frode'),
    L('Contenus piégés, connaissance des assistants grand public', 'Booby-trapped content, knowledge of mainstream assistants', 'Präparierte Inhalte, Kenntnis gängiger Assistenten', 'Contenidos trampa, conocimiento de los asistentes de uso general', 'Contenuti trappola, conoscenza degli assistenti di largo consumo'), 2),
  ss(IA, 'C', L('Un document piégé amène l’assistant d’IA à divulguer des données internes ou à agir sans validation (C)', 'A booby-trapped document leads the AI assistant to disclose internal data or act without approval (C)', 'Ein präpariertes Dokument bringt den KI-Assistenten dazu, interne Daten preiszugeben oder ohne Freigabe zu handeln (C)', 'Un documento trampa lleva al asistente de IA a divulgar datos internos o a actuar sin validación (C)', 'Un documento trappola induce l’assistente di IA a divulgare dati interni o ad agire senza approvazione (C)'),
    L('Assistant disposant de trop de droits sur les données', 'Assistant with too many rights over data', 'Assistent mit zu vielen Rechten auf die Daten', 'Asistente con demasiados derechos sobre los datos', 'Assistente con troppi diritti sui dati'), 2, 3),
  pp(IA, L('Fournisseur du service ou du modèle d’IA', 'AI service or model provider', 'Anbieter des KI-Dienstes oder -Modells', 'Proveedor del servicio o del modelo de IA', 'Fornitore del servizio o del modello di IA'), 'FOURNISSEUR', 2, 3, 3, 2),
  ae(IA, 'EXFILTRATION', 'T1567', L('Saisie de données internes dans un service d’IA grand public non autorisé', 'Entering internal data into an unauthorised consumer AI service', 'Eingabe interner Daten in einen nicht zugelassenen öffentlichen KI-Dienst', 'Introducción de datos internos en un servicio de IA de uso general no autorizado', 'Inserimento di dati interni in un servizio di IA di largo consumo non autorizzato'),
    L('Fuite involontaire, mais sortie réelle des données', 'Unintentional leak, but data actually leaves', 'Unbeabsichtigter Abfluss, aber die Daten verlassen tatsächlich das Haus', 'Fuga involuntaria, pero los datos salen realmente', 'Fuga involontaria, ma i dati escono davvero')),
  me(IA, L('Conditions d’utilisation des données par le fournisseur d’IA : pas de réutilisation pour l’entraînement, localisation connue', 'Data use terms for the AI provider: no reuse for training, known location', 'Bedingungen für die Datennutzung durch den KI-Anbieter: keine Wiederverwendung zum Training, bekannter Standort', 'Condiciones de uso de los datos por el proveedor de IA: sin reutilización para el entrenamiento, ubicación conocida', 'Condizioni di uso dei dati da parte del fornitore di IA: nessun riutilizzo per l’addestramento, ubicazione nota'), 'ORGANISATIONNELLE', '5.23',
    L('Vérifiées avant d’autoriser le service', 'Checked before authorising the service', 'Vor der Zulassung des Dienstes geprüft', 'Verificadas antes de autorizar el servicio', 'Verificate prima di autorizzare il servizio')),
  ms(IA, L('Liste des services d’IA autorisés et règles sur les données qu’on peut y saisir', 'List of authorised AI services and rules on the data that may be entered', 'Liste der zugelassenen KI-Dienste und Regeln zu den Daten, die eingegeben werden dürfen', 'Lista de servicios de IA autorizados y reglas sobre los datos que pueden introducirse', 'Elenco dei servizi di IA autorizzati e regole sui dati che si possono inserire'),
    L('Donne une alternative autorisée aux usages non maîtrisés', 'Provides an authorised alternative to uncontrolled use', 'Bietet eine zugelassene Alternative zu unkontrollierter Nutzung', 'Ofrece una alternativa autorizada a los usos no controlados', 'Offre un’alternativa autorizzata agli usi non controllati'), 'ORGANISATIONNELLE', 'GOUVERNANCE', 1),
  ms(IA, L('Droits limités des assistants d’IA connectés aux données et validation humaine des actions', 'Limited rights for AI assistants connected to data and human approval of actions', 'Begrenzte Rechte für mit Daten verbundene KI-Assistenten und menschliche Freigabe der Aktionen', 'Derechos limitados de los asistentes de IA conectados a los datos y validación humana de las acciones', 'Diritti limitati degli assistenti di IA collegati ai dati e approvazione umana delle azioni'),
    L('Réduit l’effet d’une manipulation', 'Reduces the effect of a manipulation', 'Verringert die Wirkung einer Manipulation', 'Reduce el efecto de una manipulación', 'Riduce l’effetto di una manipolazione'), 'PREVENTIVE', 'PROTECTION', 2),

  // ═══ SI isolé ou déconnecté ════════════════════════════════════════════════════════════════════
  bs(ISOLE, L('Réseau isolé et ses postes, sans lien avec Internet', 'Isolated network and its workstations, with no Internet link', 'Isoliertes Netz und seine Arbeitsplätze ohne Internetverbindung', 'Red aislada y sus puestos, sin conexión a Internet', 'Rete isolata e relative postazioni, senza collegamento a Internet'), 'RESEAU',
    L('Mises à jour rares : une intrusion y reste longtemps efficace', 'Rare updates: an intrusion stays effective for a long time', 'Seltene Updates: Ein Eindringen bleibt lange wirksam', 'Actualizaciones escasas: una intrusión sigue siendo eficaz mucho tiempo', 'Aggiornamenti rari: un’intrusione resta efficace a lungo')),
  bs(ISOLE, L('Supports amovibles et passerelle d’échange vers le SI isolé', 'Removable media and exchange gateway to the isolated IS', 'Wechseldatenträger und Austausch-Gateway zum isolierten IS', 'Soportes extraíbles y pasarela de intercambio hacia el SI aislado', 'Supporti rimovibili e gateway di scambio verso il SI isolato'), 'MATERIEL',
    L('Seule voie d’entrée : à contrôler strictement', 'Only way in: to be strictly controlled', 'Einziger Zugangsweg: streng zu kontrollieren', 'Única vía de entrada: debe controlarse estrictamente', 'Unica via di ingresso: da controllare rigorosamente')),
  er(ISOLE, L('Introduction d’un code malveillant dans le SI isolé par un support amovible', 'Malware introduced into the isolated IS through removable media', 'Einschleusen von Schadcode in das isolierte IS über einen Wechseldatenträger', 'Introducción de código malicioso en el SI aislado mediante un soporte extraíble', 'Introduzione di codice malevolo nel SI isolato tramite un supporto rimovibile'), [INTERRUPTION, L('Altération des données ou des traitements', 'Alteration of data or processing', 'Veränderung von Daten oder Verarbeitungen', 'Alteración de los datos o de los tratamientos', 'Alterazione dei dati o dei trattamenti')], 3),
  ss(ISOLE, 'I', L('Une clé USB infectée lors d’une mise à jour introduit un code malveillant dans le réseau isolé (I)', 'A USB stick infected during an update introduces malware into the isolated network (I)', 'Ein bei einem Update infizierter USB-Stick bringt Schadcode in das isolierte Netz (I)', 'Una memoria USB infectada durante una actualización introduce código malicioso en la red aislada (I)', 'Una chiavetta USB infettata durante un aggiornamento introduce codice malevolo nella rete isolata (I)'),
    L('Supports non décontaminés avant usage', 'Media not cleaned before use', 'Vor der Nutzung nicht dekontaminierte Datenträger', 'Soportes no descontaminados antes de su uso', 'Supporti non decontaminati prima dell’uso'), 2, 4),
  pp(ISOLE, L('Prestataire intervenant sur site sur le SI isolé', 'Provider working on site on the isolated IS', 'Vor Ort am isolierten IS tätiger Dienstleister', 'Proveedor que interviene in situ en el SI aislado', 'Fornitore che interviene in loco sul SI isolato'), 'PRESTATAIRE', 2, 4, 2, 3),
  me(ISOLE, L('Supports et ordinateurs des intervenants contrôlés à l’entrée, jamais branchés directement', 'Contractors’ media and laptops checked on entry, never plugged in directly', 'Datenträger und Rechner der Dienstleister bei der Ankunft geprüft, nie direkt angeschlossen', 'Soportes y ordenadores de los intervinientes controlados a la entrada, nunca conectados directamente', 'Supporti e computer degli intervenuti controllati all’ingresso, mai collegati direttamente'), 'PHYSIQUE', '7.10',
    L('Passage obligatoire par la station de décontamination', 'Mandatory pass through the cleaning station', 'Pflichtdurchlauf durch die Dekontaminationsstation', 'Paso obligatorio por la estación de descontaminación', 'Passaggio obbligatorio dalla stazione di decontaminazione')),
  ae(ISOLE, 'ACCES_INITIAL', 'T1091', L('Propagation par un support amovible infecté', 'Spread through infected removable media', 'Verbreitung über einen infizierten Wechseldatenträger', 'Propagación mediante un soporte extraíble infectado', 'Propagazione tramite un supporto rimovibile infetto'),
    L('Franchit l’isolement réseau', 'Crosses the network isolation', 'Überwindet die Netzisolation', 'Atraviesa el aislamiento de red', 'Supera l’isolamento di rete')),
  ms(ISOLE, L('Station de décontamination et procédure d’échange contrôlée pour tout support entrant', 'Cleaning station and controlled exchange procedure for any incoming media', 'Dekontaminationsstation und kontrolliertes Austauschverfahren für jeden eingehenden Datenträger', 'Estación de descontaminación y procedimiento de intercambio controlado para todo soporte entrante', 'Stazione di decontaminazione e procedura di scambio controllata per ogni supporto in ingresso'),
    L('Rien n’entre sans passer par la station', 'Nothing enters without going through the station', 'Nichts gelangt hinein, ohne die Station zu passieren', 'Nada entra sin pasar por la estación', 'Nulla entra senza passare dalla stazione'), 'PREVENTIVE', 'PROTECTION', 1),
  ms(ISOLE, L('Vérification régulière qu’aucune liaison non déclarée ne rompt l’isolement', 'Regular check that no undeclared link breaks the isolation', 'Regelmäßige Prüfung, dass keine nicht deklarierte Verbindung die Isolation aufhebt', 'Verificación periódica de que ningún enlace no declarado rompe el aislamiento', 'Verifica regolare che nessun collegamento non dichiarato rompa l’isolamento'),
    L('Modem, accès sans fil ou passerelle oubliés', 'Forgotten modem, wireless access or gateway', 'Vergessenes Modem, Funkzugang oder Gateway', 'Módem, acceso inalámbrico o pasarela olvidados', 'Modem, accesso wireless o gateway dimenticati'), 'DETECTIVE', 'DEFENSE', 2),

  // ═══ Systèmes industriels et objets connectés ══════════════════════════════════════════════════
  bs(INDUS, L('Automates, supervision industrielle et postes d’ingénierie', 'PLCs, industrial supervision and engineering workstations', 'SPS, industrielle Leittechnik und Engineering-Arbeitsplätze', 'Autómatas, supervisión industrial y puestos de ingeniería', 'PLC, supervisione industriale e postazioni di ingegneria'), 'MATERIEL',
    L('Durée de vie longue, mises à jour difficiles', 'Long service life, difficult updates', 'Lange Lebensdauer, schwierige Updates', 'Larga vida útil, actualizaciones difíciles', 'Lunga durata, aggiornamenti difficili')),
  bs(INDUS, L('Objets connectés et capteurs déployés sur site', 'Connected objects and sensors deployed on site', 'Vor Ort eingesetzte vernetzte Objekte und Sensoren', 'Objetos conectados y sensores desplegados en el sitio', 'Oggetti connessi e sensori installati sul sito'), 'MATERIEL',
    L('Souvent livrés avec des mots de passe par défaut', 'Often delivered with default passwords', 'Oft mit Standardpasswörtern ausgeliefert', 'A menudo entregados con contraseñas por defecto', 'Spesso forniti con password predefinite')),
  er(INDUS, L('Arrêt ou fonctionnement dangereux d’une installation après une action malveillante', 'Shutdown or dangerous operation of a facility after a malicious action', 'Stillstand oder gefährlicher Betrieb einer Anlage nach einer böswilligen Handlung', 'Parada o funcionamiento peligroso de una instalación tras una acción maliciosa', 'Arresto o funzionamento pericoloso di un impianto dopo un’azione malevola'), [L('Atteinte à la sécurité des personnes', 'Harm to people’s safety', 'Gefährdung der Sicherheit von Personen', 'Daño a la seguridad de las personas', 'Danno alla sicurezza delle persone'), L('Arrêt de la production', 'Production stoppage', 'Produktionsstillstand', 'Parada de la producción', 'Arresto della produzione')], 4),
  sr(INDUS, L('Groupe étatique ou hacktiviste ciblant les installations industrielles', 'State-sponsored or hacktivist group targeting industrial facilities', 'Staatliche oder hacktivistische Gruppe, die Industrieanlagen angreift', 'Grupo estatal o hacktivista que ataca instalaciones industriales', 'Gruppo statale o hacktivista che prende di mira impianti industriali'), 'ETAT_NATION',
    L('Acteur cherchant à perturber des installations physiques, parfois pour un effet politique ou démonstratif', 'Actor seeking to disrupt physical facilities, sometimes for political or demonstrative effect', 'Akteur, der physische Anlagen stören will, teils aus politischen oder demonstrativen Gründen', 'Actor que busca perturbar instalaciones físicas, a veces con un efecto político o demostrativo', 'Attore che cerca di perturbare impianti fisici, talvolta con effetto politico o dimostrativo'),
    L('Perturbation, démonstration de force', 'Disruption, show of force', 'Störung, Machtdemonstration', 'Perturbación, demostración de fuerza', 'Perturbazione, dimostrazione di forza'),
    L('Outils spécialisés pour les protocoles industriels', 'Specialised tools for industrial protocols', 'Spezialwerkzeuge für Industrieprotokolle', 'Herramientas especializadas para los protocolos industriales', 'Strumenti specializzati per i protocolli industriali'), 2),
  ss(INDUS, 'D', L('Un attaquant passe du réseau bureautique au réseau industriel et modifie la logique d’un automate (D)', 'An attacker moves from the office network to the industrial network and alters a PLC’s logic (D)', 'Ein Angreifer gelangt vom Büronetz ins Industrienetz und ändert die Logik einer SPS (D)', 'Un atacante pasa de la red ofimática a la red industrial y modifica la lógica de un autómata (D)', 'Un attaccante passa dalla rete d’ufficio alla rete industriale e modifica la logica di un PLC (D)'),
    L('Réseaux bureautique et industriel insuffisamment séparés', 'Office and industrial networks insufficiently separated', 'Büro- und Industrienetz unzureichend getrennt', 'Redes ofimática e industrial insuficientemente separadas', 'Reti d’ufficio e industriale insufficientemente separate'), 2, 4),
  pp(INDUS, L('Intégrateur ou constructeur des systèmes industriels', 'Industrial systems integrator or manufacturer', 'Integrator oder Hersteller der Industriesysteme', 'Integrador o fabricante de los sistemas industriales', 'Integratore o costruttore dei sistemi industriali'), 'PRESTATAIRE', 3, 4, 2, 2),
  ae(INDUS, 'IMPACT', 'T0831', L('Modification des consignes ou du programme d’un automate', 'Changing a PLC’s setpoints or program', 'Änderung der Sollwerte oder des Programms einer SPS', 'Modificación de las consignas o del programa de un autómata', 'Modifica dei parametri o del programma di un PLC'),
    L('Effet physique direct sur l’installation', 'Direct physical effect on the facility', 'Direkte physische Wirkung auf die Anlage', 'Efecto físico directo sobre la instalación', 'Effetto fisico diretto sull’impianto')),
  me(INDUS, L('Exigences de cybersécurité dans les contrats d’intégration et de maintenance industrielle', 'Cybersecurity requirements in industrial integration and maintenance contracts', 'Cybersicherheitsanforderungen in Verträgen zur industriellen Integration und Wartung', 'Requisitos de ciberseguridad en los contratos de integración y mantenimiento industrial', 'Requisiti di cybersicurezza nei contratti di integrazione e manutenzione industriale'), 'ORGANISATIONNELLE', '5.20',
    L('Comptes, accès à distance et mises à jour encadrés', 'Accounts, remote access and updates governed', 'Konten, Fernzugriff und Updates geregelt', 'Cuentas, accesos remotos y actualizaciones regulados', 'Account, accessi remoti e aggiornamenti regolamentati')),
  ms(INDUS, L('Cloisonnement du réseau industriel et flux filtrés avec le réseau bureautique', 'Segregation of the industrial network with filtered flows to the office network', 'Trennung des Industrienetzes mit gefilterten Datenflüssen zum Büronetz', 'Segmentación de la red industrial y flujos filtrados con la red ofimática', 'Segregazione della rete industriale e flussi filtrati con la rete d’ufficio'),
    L('Empêche le rebond depuis la bureautique', 'Prevents pivoting from the office network', 'Verhindert den Sprung aus dem Büronetz', 'Impide el salto desde la red ofimática', 'Impedisce il rimbalzo dalla rete d’ufficio'), 'PREVENTIVE', 'PROTECTION', 1),
  ms(INDUS, L('Inventaire des équipements industriels et des versions installées', 'Inventory of industrial equipment and installed versions', 'Inventar der Industrieanlagen und installierten Versionen', 'Inventario de los equipos industriales y de las versiones instaladas', 'Inventario delle apparecchiature industriali e delle versioni installate'),
    L('Base pour suivre les vulnérabilités', 'Basis for tracking vulnerabilities', 'Grundlage für die Verfolgung von Schwachstellen', 'Base para seguir las vulnerabilidades', 'Base per seguire le vulnerabilità'), 'ORGANISATIONNELLE', 'GOUVERNANCE', 2),

  // ═══ Patrimoine applicatif ancien ══════════════════════════════════════════════════════════════
  bs(PATRI, L('Application ancienne ou grand système hors support de l’éditeur', 'Legacy application or mainframe out of vendor support', 'Altanwendung oder Großrechner ohne Herstellersupport', 'Aplicación antigua o gran sistema sin soporte del editor', 'Applicazione datata o mainframe fuori supporto del fornitore'), 'LOGICIEL',
    L('Plus de correctifs de sécurité publiés', 'No more security patches released', 'Keine Sicherheitsupdates mehr', 'Ya no se publican parches de seguridad', 'Non vengono più rilasciate patch di sicurezza')),
  bs(PATRI, L('Systèmes d’exploitation et bases de données non mis à jour', 'Operating systems and databases not updated', 'Nicht aktualisierte Betriebssysteme und Datenbanken', 'Sistemas operativos y bases de datos no actualizados', 'Sistemi operativi e database non aggiornati'), 'LOGICIEL',
    L('Maintenus en l’état pour ne pas casser l’application', 'Kept as is so as not to break the application', 'Unverändert belassen, um die Anwendung nicht zu beschädigen', 'Mantenidos tal cual para no romper la aplicación', 'Mantenuti così come sono per non rompere l’applicazione')),
  er(PATRI, L('Exploitation d’une vulnérabilité connue impossible à corriger sur une application ancienne', 'Exploitation of a known, unpatchable vulnerability in a legacy application', 'Ausnutzung einer bekannten, nicht behebbaren Schwachstelle einer Altanwendung', 'Explotación de una vulnerabilidad conocida imposible de corregir en una aplicación antigua', 'Sfruttamento di una vulnerabilità nota impossibile da correggere in un’applicazione datata'), [CONFIDENTIALITE, INTERRUPTION], 3),
  ss(PATRI, 'I', L('Un attaquant exploite une faille publique d’un composant non maintenu pour altérer les données de l’application (I)', 'An attacker exploits a public flaw in an unmaintained component to alter the application’s data (I)', 'Ein Angreifer nutzt eine öffentliche Lücke einer nicht gewarteten Komponente, um die Daten der Anwendung zu verändern (I)', 'Un atacante explota una falla pública de un componente sin mantenimiento para alterar los datos de la aplicación (I)', 'Un attaccante sfrutta una falla pubblica di un componente non mantenuto per alterare i dati dell’applicazione (I)'),
    L('Composant accessible depuis le reste du SI', 'Component reachable from the rest of the IS', 'Komponente aus dem übrigen IS erreichbar', 'Componente accesible desde el resto del SI', 'Componente raggiungibile dal resto del SI'), 3, 3),
  pp(PATRI, L('Prestataire de maintenance de l’application ancienne', 'Legacy application maintenance provider', 'Wartungsdienstleister der Altanwendung', 'Proveedor de mantenimiento de la aplicación antigua', 'Fornitore di manutenzione dell’applicazione datata'), 'PRESTATAIRE', 4, 3, 2, 2),
  ae(PATRI, 'ACCES_INITIAL', 'T1190', L('Exploitation d’une vulnérabilité publique d’un composant hors support', 'Exploitation of a public vulnerability in an unsupported component', 'Ausnutzung einer öffentlichen Schwachstelle einer nicht unterstützten Komponente', 'Explotación de una vulnerabilidad pública de un componente sin soporte', 'Sfruttamento di una vulnerabilità pubblica di un componente fuori supporto'),
    L('Code d’exploitation souvent disponible librement', 'Exploit code often freely available', 'Exploit-Code oft frei verfügbar', 'Código de explotación a menudo disponible libremente', 'Codice di exploit spesso liberamente disponibile')),
  me(PATRI, L('Maintien en conditions de sécurité et transmission des connaissances exigés du prestataire', 'Security maintenance and knowledge transfer required from the provider', 'Sicherheitswartung und Wissenstransfer vom Dienstleister verlangt', 'Mantenimiento de la seguridad y transferencia de conocimientos exigidos al proveedor', 'Mantenimento della sicurezza e trasferimento delle conoscenze richiesti al fornitore'), 'ORGANISATIONNELLE', '5.22',
    L('Évite la dépendance à une seule personne', 'Avoids dependence on a single person', 'Vermeidet die Abhängigkeit von einer einzelnen Person', 'Evita la dependencia de una sola persona', 'Evita la dipendenza da una sola persona')),
  ms(PATRI, L('Isolement de l’application ancienne et filtrage strict des flux qui l’atteignent', 'Isolation of the legacy application and strict filtering of the flows reaching it', 'Isolierung der Altanwendung und strenge Filterung der Datenflüsse zu ihr', 'Aislamiento de la aplicación antigua y filtrado estricto de los flujos que la alcanzan', 'Isolamento dell’applicazione datata e filtraggio rigoroso dei flussi che la raggiungono'),
    L('Compense l’absence de correctifs', 'Compensates for the lack of patches', 'Gleicht fehlende Updates aus', 'Compensa la ausencia de parches', 'Compensa l’assenza di patch'), 'PREVENTIVE', 'PROTECTION', 1),
  ms(PATRI, L('Plan de remplacement daté, validé par la direction', 'Dated replacement plan, approved by management', 'Datierter Ablöseplan, von der Leitung genehmigt', 'Plan de sustitución fechado, validado por la dirección', 'Piano di sostituzione datato, approvato dalla direzione'),
    L('Le risque résiduel est accepté pour une durée limitée', 'The residual risk is accepted for a limited period', 'Das Restrisiko wird für einen begrenzten Zeitraum akzeptiert', 'El riesgo residual se acepta por un tiempo limitado', 'Il rischio residuo è accettato per un periodo limitato'), 'ORGANISATIONNELLE', 'GOUVERNANCE', 2),
]
