/**
 * exemples-protection-sociale.ts — Exemples d'ateliers (1 à 5) pour les organismes de protection sociale
 * (régimes de base, assurance maladie obligatoire…), organisés en réseau.
 *
 * Même format que `exemples-sectoriels-ext.ts` : textes ×5 dans la donnée, `profs` = sous-profession (id du
 * sous-secteur sans le préfixe `protsoc-`), éléments sans `profs` = socle commun de la famille. Exemples
 * GÉNÉRIQUES : aucun organisme réel n'est cité. Suggestions à qualifier, contenu « à relire par un expert ».
 *
 * Module pur → testé (protection-sociale.test.ts).
 */
import type { ExtItem, Tr } from '@/lib/exemples-sectoriels-ext'

const L = (fr: string, en: string, de: string, es: string, it: string): Tr => [fr, en, de, es, it]
type P = readonly string[] | null
const F = 'protection_sociale' as const
const mk = (category: ExtItem['category'], profs: P, data: Record<string, unknown>): ExtItem => ({ famille: F, category, ...(profs ? { profs } : {}), data })
const vm = (profs: P, nom: Tr, type: 'PROCESSUS' | 'INFORMATION', description: Tr, responsable: Tr, d: number, i: number, c: number, t: number) =>
  mk('valeursMetier', profs, { nom, type, description, responsable, disponibilite: d, integrite: i, confidentialite: c, tracabilite: t })
const bs = (profs: P, nom: Tr, type: string, description: Tr) => mk('biensSupports', profs, { nom, type, description })
const er = (profs: P, description: Tr, impacts: Tr[], graviteDefaut: number) => mk('evenementsRedoutes', profs, { description, impacts, graviteDefaut })
const sr = (profs: P, nom: Tr, categorie: string, description: Tr, motivation: Tr, ressources: Tr, pertinenceDefaut: number) =>
  mk('sourcesRisque', profs, { nom, categorie, description, motivation, ressources, pertinenceDefaut })
const ss = (profs: P, critere: 'C' | 'I' | 'D' | 'T', nom: Tr, description: Tr, vraisemblanceDefaut: number, graviteDefaut: number) =>
  mk('scenariosStrategiques', profs, { critere, nom, description, vraisemblanceDefaut, graviteDefaut })
const pp = (profs: P, nom: Tr, type: string, dependance: number, penetration: number, maturite: number, confiance: number) =>
  mk('partiesPrenantes', profs, { nom, type, dependance, penetration, maturite, confiance })
const ae = (profs: P, type: string, attack: string, nom: Tr, description: Tr) => mk('actionsElementaires', profs, { type, attack, nom, description })
const me = (profs: P, mesure: Tr, type: 'ORGANISATIONNELLE' | 'TECHNIQUE' | 'DETECTIVE', iso27005: string, description: Tr) =>
  mk('mesuresEcosysteme', profs, { mesure, type, iso27005, description })
const ms = (profs: P, nom: Tr, description: Tr, type: 'ORGANISATIONNELLE' | 'TECHNIQUE' | 'DETECTIVE', categorieEbios: 'GOUVERNANCE' | 'PROTECTION' | 'DEFENSE' | 'RESILIENCE', prioriteDefaut: 1 | 2 | 3, references?: string[]) =>
  mk('mesures', profs, { nom, description, type, categorieEbios, prioriteDefaut, ...(references ? { references } : {}) })

const RGPD = 'RGPD — Règlement (UE) 2016/679'
const ISO = 'ISO/IEC 27001:2022, annexe A'
const RGS = 'RGS — Référentiel général de sécurité, version 2.0'

const IMP_MASSE = L('Des milliers d’assurés touchés', 'Thousands of insured persons affected', 'Tausende Versicherte betroffen', 'Miles de asegurados afectados', 'Migliaia di assicurati coinvolti')
const IMP_CONFIANCE = L('Atteinte à la confiance dans le service public', 'Loss of trust in the public service', 'Vertrauensverlust in den öffentlichen Dienst', 'Pérdida de confianza en el servicio público', 'Perdita di fiducia nel servizio pubblico')
const IMP_CNIL = L('Notification à l’autorité de protection des données', 'Notification to the data protection authority', 'Meldung an die Datenschutzbehörde', 'Notificación a la autoridad de protección de datos', 'Notifica all’autorità per la protezione dei dati')

export const PROTECTION_SOCIALE_ITEMS: ExtItem[] = [
  // ═══════════════════════════ Socle commun ═══════════════════════════
  vm(null, L('Ouverture et maintien des droits des assurés et de leurs ayants droit', 'Opening and maintaining the entitlements of insured persons and their dependants', 'Begründung und Pflege der Ansprüche von Versicherten und Angehörigen', 'Apertura y mantenimiento de los derechos de los asegurados y sus beneficiarios', 'Apertura e mantenimento dei diritti degli assicurati e dei loro aventi diritto'), 'PROCESSUS',
    L('Affiliation, rattachement des ayants droit, changements de situation', 'Enrolment, linking of dependants, changes of circumstances', 'Aufnahme, Zuordnung von Angehörigen, Änderungen der Lebenssituation', 'Afiliación, vinculación de beneficiarios, cambios de situación', 'Affiliazione, collegamento degli aventi diritto, cambi di situazione'),
    L('Direction de la gestion des droits', 'Entitlements department', 'Abteilung Anspruchsverwaltung', 'Dirección de gestión de derechos', 'Direzione gestione dei diritti'), 3, 4, 4, 4),
  vm(null, L('Liquidation et paiement des prestations en nature et en espèces', 'Processing and payment of benefits in kind and in cash', 'Abwicklung und Zahlung von Sach- und Geldleistungen', 'Liquidación y pago de prestaciones en especie y en metálico', 'Liquidazione e pagamento delle prestazioni in natura e in denaro'), 'PROCESSUS',
    L('Remboursements, revenus de remplacement, paiements aux professionnels et établissements', 'Reimbursements, replacement income, payments to professionals and facilities', 'Erstattungen, Lohnersatzleistungen, Zahlungen an Leistungserbringer und Einrichtungen', 'Reembolsos, rentas de sustitución, pagos a profesionales y centros', 'Rimborsi, redditi sostitutivi, pagamenti a professionisti e strutture'),
    L('Direction des prestations', 'Benefits department', 'Abteilung Leistungen', 'Dirección de prestaciones', 'Direzione prestazioni'), 4, 4, 3, 4),
  vm(null, L('Référentiel des bénéficiaires et identifiants des assurés', 'Beneficiary register and identifiers of insured persons', 'Begünstigtenregister und Kennungen der Versicherten', 'Registro de beneficiarios e identificadores de los asegurados', 'Anagrafe dei beneficiari e identificativi degli assicurati'), 'INFORMATION',
    L('Base de référence consultée par tous les processus et par les partenaires', 'Reference database used by every process and by partners', 'Referenzdatenbank, die von allen Prozessen und Partnern genutzt wird', 'Base de referencia consultada por todos los procesos y por los socios', 'Base di riferimento consultata da tutti i processi e dai partner'),
    L('DSI / DPO', 'IT department / DPO', 'IT-Abteilung / DSB', 'Dirección de sistemas / DPD', 'Direzione sistemi informativi / DPO'), 3, 4, 4, 4),
  bs(null, L('Chaînes de traitement de masse (traitements de nuit, ordonnanceur)', 'Mass processing chains (night batches, scheduler)', 'Massenverarbeitungsketten (Nachtläufe, Scheduler)', 'Cadenas de tratamiento masivo (procesos nocturnos, planificador)', 'Catene di elaborazione massiva (batch notturni, scheduler)'), 'LOGICIEL',
    L('Calculent et ordonnent les paiements de millions de dossiers', 'Calculate and order payments for millions of files', 'Berechnen und veranlassen Zahlungen für Millionen von Vorgängen', 'Calculan y ordenan los pagos de millones de expedientes', 'Calcolano e dispongono i pagamenti di milioni di pratiche')),
  bs(null, L('Compte usager en ligne et application mobile', 'Online user account and mobile app', 'Online-Versichertenkonto und mobile App', 'Cuenta de usuario en línea y aplicación móvil', 'Account utente online e app mobile'), 'LOGICIEL',
    L('Démarches, attestations, coordonnées bancaires, messagerie', 'Procedures, certificates, bank details, messaging', 'Anträge, Bescheinigungen, Bankverbindung, Nachrichten', 'Trámites, certificados, datos bancarios, mensajería', 'Pratiche, attestati, coordinate bancarie, messaggistica')),
  bs(null, L('Postes et habilitations des agents de gestion', 'Workstations and access rights of case handlers', 'Arbeitsplätze und Berechtigungen der Sachbearbeiter', 'Puestos y habilitaciones de los gestores', 'Postazioni e abilitazioni degli operatori di gestione'), 'PERSONNEL',
    L('Milliers d’agents disposant d’accès aux données des assurés', 'Thousands of staff with access to insured persons’ data', 'Tausende Mitarbeitende mit Zugriff auf Versichertendaten', 'Miles de agentes con acceso a los datos de los asegurados', 'Migliaia di operatori con accesso ai dati degli assicurati')),
  er(null, L('Paiements erronés en masse après une régression d’un traitement de masse', 'Mass incorrect payments after a regression in a mass processing chain', 'Massenhaft fehlerhafte Zahlungen nach einer Regression in einer Massenverarbeitung', 'Pagos erróneos en masa tras una regresión de un tratamiento masivo', 'Pagamenti errati in massa dopo una regressione di un’elaborazione massiva'),
    [IMP_MASSE, L('Indus à recouvrer ou retards de paiement', 'Overpayments to recover or late payments', 'Rückforderungen oder Zahlungsverzug', 'Pagos indebidos que recuperar o retrasos de pago', 'Indebiti da recuperare o ritardi di pagamento'), IMP_CONFIANCE], 4),
  er(null, L('Détournement de prestations par changement frauduleux de coordonnées bancaires', 'Diversion of benefits through fraudulent changes of bank details', 'Umleitung von Leistungen durch betrügerische Änderung der Bankverbindung', 'Desvío de prestaciones por cambio fraudulento de datos bancarios', 'Dirottamento di prestazioni tramite modifica fraudolenta delle coordinate bancarie'),
    [L('Préjudice financier pour l’organisme et les assurés', 'Financial loss for the organisation and insured persons', 'Finanzieller Schaden für die Einrichtung und die Versicherten', 'Perjuicio económico para el organismo y los asegurados', 'Danno finanziario per l’ente e gli assicurati'), IMP_CONFIANCE], 3),
  er(null, L('Consultation illégitime de données d’assurés par des agents', 'Unauthorised viewing of insured persons’ data by staff', 'Unberechtigte Einsicht in Versichertendaten durch Mitarbeitende', 'Consulta ilegítima de datos de asegurados por agentes', 'Consultazione illegittima dei dati degli assicurati da parte degli operatori'),
    [L('Atteinte à la vie privée', 'Invasion of privacy', 'Verletzung der Privatsphäre', 'Atentado contra la intimidad', 'Violazione della riservatezza'), IMP_CNIL], 3),
  sr(null, L('Réseau de fraude organisée', 'Organised fraud ring', 'Organisierter Betrugsring', 'Red de fraude organizada', 'Rete di frode organizzata'), 'CYBERCRIMINEL',
    L('Faux professionnels, fausses prescriptions, comptes usurpés', 'Fake professionals, fake prescriptions, hijacked accounts', 'Falsche Leistungserbringer, gefälschte Verordnungen, übernommene Konten', 'Falsos profesionales, recetas falsas, cuentas usurpadas', 'Falsi professionisti, prescrizioni false, account usurpati'),
    L('Lucratif', 'Financial gain', 'Finanzieller Gewinn', 'Lucro', 'Lucro'),
    L('Organisation, faux documents, comptes bancaires de passage', 'Organisation, forged documents, mule bank accounts', 'Organisation, gefälschte Dokumente, Durchlaufkonten', 'Organización, documentos falsos, cuentas puente', 'Organizzazione, documenti falsi, conti di transito'), 3),
  sr(null, L('Agent interne curieux ou corrompu', 'Curious or corrupt insider', 'Neugieriger oder bestochener Innentäter', 'Agente interno curioso o corrupto', 'Operatore interno curioso o corrotto'), 'EMPLOYE_MALVEILLANT',
    L('Consulte ou modifie des dossiers hors de ses missions', 'Views or changes files outside their duties', 'Sieht Vorgänge außerhalb seiner Aufgaben ein oder ändert sie', 'Consulta o modifica expedientes fuera de sus funciones', 'Consulta o modifica pratiche al di fuori delle proprie mansioni'),
    L('Curiosité, rémunération par un tiers', 'Curiosity, payment by a third party', 'Neugier, Bezahlung durch Dritte', 'Curiosidad, remuneración por un tercero', 'Curiosità, compenso da parte di terzi'),
    L('Accès légitimes aux applications de gestion', 'Legitimate access to case-management applications', 'Legitimer Zugang zu den Verwaltungsanwendungen', 'Acceso legítimo a las aplicaciones de gestión', 'Accesso legittimo alle applicazioni di gestione'), 3),
  sr(null, L('Groupe de rançongiciel ciblant le secteur public', 'Ransomware group targeting the public sector', 'Ransomware-Gruppe mit Fokus auf den öffentlichen Sektor', 'Grupo de ransomware que ataca al sector público', 'Gruppo ransomware che prende di mira il settore pubblico'), 'CYBERCRIMINEL',
    L('Cherche à paralyser les paiements pour obtenir une rançon', 'Seeks to paralyse payments to obtain a ransom', 'Will die Zahlungen lahmlegen, um Lösegeld zu erpressen', 'Busca paralizar los pagos para obtener un rescate', 'Cerca di paralizzare i pagamenti per ottenere un riscatto'),
    L('Extorsion', 'Extortion', 'Erpressung', 'Extorsión', 'Estorsione'),
    L('Courtiers d’accès initial, outils de chiffrement', 'Initial access brokers, encryption tools', 'Initial-Access-Broker, Verschlüsselungswerkzeuge', 'Intermediarios de acceso inicial, herramientas de cifrado', 'Broker di accesso iniziale, strumenti di cifratura'), 3),
  ss(null, 'I', L('Changement d’IBAN en masse à partir de comptes usagers usurpés (I)', 'Mass IBAN changes from hijacked user accounts (I)', 'Massenhafte IBAN-Änderungen über übernommene Versichertenkonten (I)', 'Cambio masivo de IBAN desde cuentas de usuario usurpadas (I)', 'Modifica massiva dell’IBAN da account utente usurpati (I)'),
    L('Les prestations sont versées sur des comptes contrôlés par les fraudeurs', 'Benefits are paid into fraudster-controlled accounts', 'Leistungen werden auf von Betrügern kontrollierte Konten gezahlt', 'Las prestaciones se abonan en cuentas controladas por los defraudadores', 'Le prestazioni vengono versate su conti controllati dai truffatori'), 3, 3),
  ss(null, 'D', L('Un rançongiciel arrête les chaînes de paiement (D)', 'Ransomware halts the payment chains (D)', 'Ransomware stoppt die Zahlungsketten (D)', 'Un ransomware detiene las cadenas de pago (D)', 'Un ransomware arresta le catene di pagamento (D)'),
    L('Revenus de remplacement et remboursements bloqués plusieurs jours', 'Replacement income and reimbursements blocked for several days', 'Lohnersatz und Erstattungen mehrere Tage blockiert', 'Rentas de sustitución y reembolsos bloqueados varios días', 'Redditi sostitutivi e rimborsi bloccati per più giorni'), 2, 4),
  ss(null, 'C', L('Un agent consulte les dossiers de proches ou de personnalités (C)', 'A staff member views files of relatives or public figures (C)', 'Ein Mitarbeiter sieht Vorgänge von Angehörigen oder Prominenten ein (C)', 'Un agente consulta expedientes de allegados o personalidades (C)', 'Un operatore consulta le pratiche di familiari o personalità (C)'),
    L('Aucun motif demandé, aucune revue des consultations', 'No reason required, no review of look-ups', 'Kein Grund erforderlich, keine Prüfung der Abrufe', 'Sin motivo exigido ni revisión de las consultas', 'Nessun motivo richiesto, nessuna revisione delle consultazioni'), 3, 3),
  pp(null, L('Autorité de protection des données', 'Data protection authority', 'Datenschutzaufsichtsbehörde', 'Autoridad de protección de datos', 'Autorità per la protezione dei dati'), 'ORGANISME_REGULATION', 2, 1, 4, 4),
  pp(null, L('Éditeurs et intégrateurs des applications de gestion', 'Vendors and integrators of case-management applications', 'Hersteller und Integratoren der Verwaltungsanwendungen', 'Fabricantes e integradores de las aplicaciones de gestión', 'Fornitori e integratori delle applicazioni di gestione'), 'PRESTATAIRE', 4, 4, 3, 3),
  pp(null, L('Prestataire d’éditique et de courrier de masse', 'Mass print and mail provider', 'Dienstleister für Druck und Massenpost', 'Proveedor de impresión y correo masivo', 'Fornitore di stampa e posta massiva'), 'PRESTATAIRE', 3, 2, 2, 2),
  ae(null, 'ACCES_INITIAL', 'T1078', L('Connexion à un compte usager avec des identifiants réutilisés', 'Sign-in to a user account with reused credentials', 'Anmeldung an einem Versichertenkonto mit wiederverwendeten Zugangsdaten', 'Acceso a una cuenta de usuario con credenciales reutilizadas', 'Accesso a un account utente con credenziali riutilizzate'),
    L('Identifiants issus de fuites d’autres services', 'Credentials leaked from other services', 'Zugangsdaten aus Leaks anderer Dienste', 'Credenciales filtradas de otros servicios', 'Credenziali trapelate da altri servizi')),
  ae(null, 'IMPACT', 'T1565.001', L('Modification des coordonnées bancaires pour détourner des paiements', 'Change of bank details to divert payments', 'Änderung der Bankverbindung zur Umleitung von Zahlungen', 'Modificación de datos bancarios para desviar pagos', 'Modifica delle coordinate bancarie per dirottare i pagamenti'),
    L('Le paiement suivant part vers le compte du fraudeur', 'The next payment goes to the fraudster’s account', 'Die nächste Zahlung geht auf das Konto des Betrügers', 'El siguiente pago va a la cuenta del defraudador', 'Il pagamento successivo va sul conto del truffatore')),
  ae(null, 'EXFILTRATION', 'T1213', L('Consultations répétées du référentiel des bénéficiaires par un compte d’agent', 'Repeated look-ups of the beneficiary register by a staff account', 'Wiederholte Abfragen des Begünstigtenregisters über ein Mitarbeiterkonto', 'Consultas repetidas del registro de beneficiarios por una cuenta de agente', 'Consultazioni ripetute dell’anagrafe dei beneficiari da un account operatore'),
    L('Volumes et cibles inhabituels pour la fonction', 'Volumes and targets unusual for the role', 'Für die Funktion ungewöhnliche Mengen und Ziele', 'Volúmenes y objetivos inusuales para la función', 'Volumi e obiettivi insoliti per la funzione')),
  me(null, L('Clauses de sécurité, d’audit et de notification dans les contrats des prestataires de gestion et d’éditique', 'Security, audit and notification clauses in contracts with administration and print providers', 'Sicherheits-, Audit- und Meldeklauseln in Verträgen mit Verwaltungs- und Druckdienstleistern', 'Cláusulas de seguridad, auditoría y notificación en los contratos de proveedores de gestión e impresión', 'Clausole di sicurezza, audit e notifica nei contratti dei fornitori di gestione e stampa'),
    'ORGANISATIONNELLE', '5.20', L('Délai de notification chiffré et droit d’audit', 'Quantified notification deadline and audit right', 'Bezifferte Meldefrist und Auditrecht', 'Plazo de notificación cuantificado y derecho de auditoría', 'Termine di notifica quantificato e diritto di audit')),
  me(null, L('Accès des prestataires aux environnements de production ouverts à la demande et tracés', 'Provider access to production environments opened on demand and logged', 'Zugriffe von Dienstleistern auf Produktionsumgebungen nur auf Anfrage und protokolliert', 'Accesos de proveedores a los entornos de producción abiertos bajo demanda y trazados', 'Accessi dei fornitori agli ambienti di produzione aperti su richiesta e tracciati'),
    'TECHNIQUE', '5.15', L('Revue trimestrielle des comptes de prestataires', 'Quarterly review of provider accounts', 'Vierteljährliche Überprüfung der Dienstleisterkonten', 'Revisión trimestral de las cuentas de proveedores', 'Revisione trimestrale degli account dei fornitori')),
  ms(null, L('Délai de sécurité et confirmation sur l’ancien canal avant tout paiement vers de nouvelles coordonnées bancaires', 'Cooling-off period and confirmation on the former channel before any payment to new bank details', 'Sicherheitsfrist und Bestätigung über den bisherigen Kanal vor jeder Zahlung auf eine neue Bankverbindung', 'Plazo de seguridad y confirmación por el canal anterior antes de cualquier pago a nuevos datos bancarios', 'Periodo di sicurezza e conferma sul canale precedente prima di ogni pagamento verso nuove coordinate'),
    L('Aucun paiement vers un nouvel IBAN avant confirmation de l’assuré', 'No payment to a new IBAN before the insured person confirms', 'Keine Zahlung auf eine neue IBAN vor Bestätigung durch den Versicherten', 'Ningún pago a un nuevo IBAN antes de la confirmación del asegurado', 'Nessun pagamento verso un nuovo IBAN prima della conferma dell’assicurato'),
    'ORGANISATIONNELLE', 'PROTECTION', 1),
  ms(null, L('Motif de consultation obligatoire et revue des consultations atypiques par les agents', 'Mandatory reason for access and review of atypical look-ups by staff', 'Pflichtangabe des Abrufgrunds und Prüfung auffälliger Abrufe durch Mitarbeitende', 'Motivo de consulta obligatorio y revisión de las consultas atípicas de los agentes', 'Motivo di consultazione obbligatorio e revisione delle consultazioni anomale degli operatori'),
    L('Personnalités, proches et volumes inhabituels revus chaque mois', 'Public figures, relatives and unusual volumes reviewed monthly', 'Prominente, Angehörige und ungewöhnliche Mengen werden monatlich geprüft', 'Personalidades, allegados y volúmenes inusuales revisados cada mes', 'Personalità, familiari e volumi insoliti rivisti ogni mese'),
    'DETECTIVE', 'DEFENSE', 1, [`${RGPD}, art. 32`]),
  ms(null, L('Tests de non-régression sur les montants avant toute mise en production d’un traitement de masse', 'Regression tests on amounts before any release of a mass processing chain', 'Regressionstests der Beträge vor jeder Inbetriebnahme einer Massenverarbeitung', 'Pruebas de no regresión de los importes antes de cualquier puesta en producción de un tratamiento masivo', 'Test di non regressione sugli importi prima di ogni messa in produzione di un’elaborazione massiva'),
    L('Jeu de dossiers de référence aux montants connus', 'Reference set of files with known amounts', 'Referenzbestand von Vorgängen mit bekannten Beträgen', 'Conjunto de expedientes de referencia con importes conocidos', 'Insieme di pratiche di riferimento con importi noti'),
    'ORGANISATIONNELLE', 'PROTECTION', 1, [`${ISO}, mesure 8.32`]),
  ms(null, L('Rapprochement des paiements par lot avant remise bancaire (totaux de contrôle)', 'Batch payment reconciliation before bank submission (control totals)', 'Abgleich der Zahlungen je Lauf vor Übergabe an die Bank (Kontrollsummen)', 'Conciliación de los pagos por lote antes de la remesa bancaria (totales de control)', 'Riconciliazione dei pagamenti per lotto prima dell’invio in banca (totali di controllo)'),
    L('Écart bloquant au-delà du seuil convenu', 'Discrepancy beyond the agreed threshold blocks the batch', 'Abweichung über der vereinbarten Schwelle blockiert den Lauf', 'Una diferencia superior al umbral acordado bloquea el lote', 'Uno scostamento oltre la soglia concordata blocca il lotto'),
    'DETECTIVE', 'DEFENSE', 1),
  ms(null, L('Homologation de sécurité de chaque téléservice avant mise en service et à échéance', 'Security accreditation of each online service before go-live and at expiry', 'Sicherheitsakkreditierung jedes Online-Dienstes vor Inbetriebnahme und bei Ablauf', 'Homologación de seguridad de cada teleservicio antes de su puesta en servicio y a su vencimiento', 'Omologazione di sicurezza di ogni servizio online prima dell’avvio e alla scadenza'),
    L('Décision de l’autorité d’homologation fondée sur l’analyse de risques', 'Decision by the accreditation authority based on the risk analysis', 'Entscheidung der Akkreditierungsstelle auf Grundlage der Risikoanalyse', 'Decisión de la autoridad de homologación basada en el análisis de riesgos', 'Decisione dell’autorità di omologazione basata sull’analisi dei rischi'),
    'ORGANISATIONNELLE', 'GOUVERNANCE', 1, [RGS]),
  ms(null, L('Plan de continuité des paiements prioritaires (revenus de remplacement)', 'Continuity plan for priority payments (replacement income)', 'Kontinuitätsplan für vorrangige Zahlungen (Lohnersatzleistungen)', 'Plan de continuidad de los pagos prioritarios (rentas de sustitución)', 'Piano di continuità dei pagamenti prioritari (redditi sostitutivi)'),
    L('Ordre de reprise connu et exercé', 'Known and rehearsed recovery order', 'Bekannte und geübte Wiederanlaufreihenfolge', 'Orden de reanudación conocido y ejercitado', 'Ordine di ripresa noto ed esercitato'),
    'ORGANISATIONNELLE', 'RESILIENCE', 2),

  // ═══════════════════════════ Tête de réseau ═══════════════════════════
  vm(['tete-reseau'], L('Pilotage national de la maîtrise des risques et des référentiels de contrôle', 'National steering of risk control and control standards', 'Nationale Steuerung der Risikokontrolle und der Kontrollstandards', 'Dirección nacional del control de riesgos y de los referenciales de control', 'Pilotaggio nazionale del controllo dei rischi e dei referenziali di controllo'), 'PROCESSUS',
    L('Référentiels diffusés à tout le réseau et consolidation des résultats', 'Standards distributed to the whole network and consolidation of results', 'An das ganze Netz verteilte Standards und Konsolidierung der Ergebnisse', 'Referenciales difundidos a toda la red y consolidación de resultados', 'Referenziali diffusi a tutta la rete e consolidamento dei risultati'),
    L('Direction de la maîtrise des risques', 'Risk control department', 'Abteilung Risikokontrolle', 'Dirección de control de riesgos', 'Direzione controllo dei rischi'), 3, 4, 3, 4),
  er(['tete-reseau'], L('Un paramétrage national erroné se propage à toutes les entités du réseau', 'A wrong national setting spreads to every entity of the network', 'Eine fehlerhafte nationale Einstellung breitet sich auf alle Einheiten des Netzes aus', 'Una parametrización nacional errónea se propaga a todas las entidades de la red', 'Un’impostazione nazionale errata si propaga a tutte le entità della rete'),
    [IMP_MASSE, L('Correction coordonnée dans tout le réseau', 'Coordinated correction across the network', 'Koordinierte Korrektur im ganzen Netz', 'Corrección coordinada en toda la red', 'Correzione coordinata in tutta la rete')], 4),
  ss(['tete-reseau'], 'I', L('Une erreur de paramétrage national se propage à toutes les caisses (I)', 'A national configuration error spreads to every fund office (I)', 'Ein nationaler Einstellungsfehler breitet sich auf alle Kassen aus (I)', 'Un error de parametrización nacional se propaga a todas las cajas (I)', 'Un errore di configurazione nazionale si propaga a tutte le casse (I)'),
    L('Aucune recette nationale ni déploiement progressif', 'No national acceptance test nor gradual roll-out', 'Keine nationale Abnahme und keine schrittweise Einführung', 'Sin recepción nacional ni despliegue progresivo', 'Nessun collaudo nazionale né rilascio progressivo'), 2, 4),
  pp(['tete-reseau'], L('Entités du réseau (caisses, centres)', 'Network entities (fund offices, centres)', 'Einheiten des Netzes (Kassen, Zentren)', 'Entidades de la red (cajas, centros)', 'Entità della rete (casse, centri)'), 'PARTENAIRE', 4, 3, 3, 3),
  ms(['tete-reseau'], L('Contrôles de référence déclinés dans chaque entité et consolidés', 'Reference controls rolled out to each entity and consolidated', 'Referenzkontrollen in jeder Einheit ausgerollt und konsolidiert', 'Controles de referencia desplegados en cada entidad y consolidados', 'Controlli di riferimento declinati in ogni entità e consolidati'),
    L('Mêmes contrôles partout, résultats comparables', 'Same controls everywhere, comparable results', 'Überall dieselben Kontrollen, vergleichbare Ergebnisse', 'Mismos controles en todas partes, resultados comparables', 'Stessi controlli ovunque, risultati comparabili'),
    'ORGANISATIONNELLE', 'GOUVERNANCE', 1),

  // ═══════════════════════════ Caisse locale ═══════════════════════════
  vm(['caisse-locale'], L('Accueil des assurés et traitement des demandes (guichet, téléphone, courrier)', 'Reception of insured persons and handling of requests (counter, phone, mail)', 'Empfang der Versicherten und Bearbeitung von Anträgen (Schalter, Telefon, Post)', 'Atención a los asegurados y tramitación de solicitudes (ventanilla, teléfono, correo)', 'Accoglienza degli assicurati e trattamento delle richieste (sportello, telefono, posta)'), 'PROCESSUS',
    L('Point de contact où l’identité de l’assuré doit être vérifiée', 'Contact point where the insured person’s identity must be checked', 'Kontaktstelle, an der die Identität des Versicherten geprüft werden muss', 'Punto de contacto donde debe verificarse la identidad del asegurado', 'Punto di contatto in cui deve essere verificata l’identità dell’assicurato'),
    L('Direction de la relation aux assurés', 'Customer relations department', 'Abteilung Versichertenbetreuung', 'Dirección de relación con los asegurados', 'Direzione relazioni con gli assicurati'), 3, 3, 4, 3),
  bs(['caisse-locale'], L('Applications de gestion des dossiers et de numérisation du courrier', 'Case-management and mail-scanning applications', 'Anwendungen für Vorgangsverwaltung und Postdigitalisierung', 'Aplicaciones de gestión de expedientes y digitalización del correo', 'Applicazioni di gestione delle pratiche e digitalizzazione della posta'), 'LOGICIEL',
    L('Traitent les pièces reçues des assurés', 'Process documents received from insured persons', 'Verarbeiten von Versicherten eingereichte Unterlagen', 'Tratan los documentos recibidos de los asegurados', 'Trattano i documenti ricevuti dagli assicurati')),
  er(['caisse-locale'], L('Usurpation d’identité au guichet ou au téléphone pour modifier un dossier', 'Identity fraud at the counter or by phone to change a file', 'Identitätsbetrug am Schalter oder per Telefon zur Änderung eines Vorgangs', 'Usurpación de identidad en ventanilla o por teléfono para modificar un expediente', 'Furto d’identità allo sportello o al telefono per modificare una pratica'),
    [L('Prestations détournées', 'Diverted benefits', 'Umgeleitete Leistungen', 'Prestaciones desviadas', 'Prestazioni dirottate'), IMP_CONFIANCE], 3),
  ae(['caisse-locale'], 'ACCES_INITIAL', 'T1656', L('Appel téléphonique se faisant passer pour un assuré pour changer ses coordonnées', 'Phone call impersonating an insured person to change their details', 'Anruf unter falscher Identität eines Versicherten zur Änderung seiner Daten', 'Llamada telefónica haciéndose pasar por un asegurado para cambiar sus datos', 'Telefonata spacciandosi per un assicurato per modificarne i dati'),
    L('Informations personnelles obtenues sur les réseaux sociaux', 'Personal information gathered from social networks', 'Über soziale Netzwerke beschaffte persönliche Informationen', 'Información personal obtenida en las redes sociales', 'Informazioni personali raccolte sui social network')),
  ms(['caisse-locale'], L('Vérification d’identité renforcée pour les changements sensibles demandés au téléphone ou au guichet', 'Enhanced identity checks for sensitive changes requested by phone or at the counter', 'Verstärkte Identitätsprüfung bei sensiblen Änderungen per Telefon oder am Schalter', 'Verificación de identidad reforzada para los cambios sensibles solicitados por teléfono o en ventanilla', 'Verifica dell’identità rafforzata per le modifiche sensibili richieste al telefono o allo sportello'),
    L('Questions de contrôle, rappel sur un numéro connu, pièce justificative', 'Security questions, call-back on a known number, supporting document', 'Kontrollfragen, Rückruf unter bekannter Nummer, Nachweis', 'Preguntas de control, devolución de llamada a un número conocido, justificante', 'Domande di controllo, richiamata su un numero noto, documento giustificativo'),
    'ORGANISATIONNELLE', 'PROTECTION', 1),

  // ═══════════════════════════ Contrôle médical ═══════════════════════════
  vm(['controle-medical'], L('Avis médicaux, arrêts de travail et accords préalables', 'Medical opinions, sick leave and prior approvals', 'Medizinische Gutachten, Arbeitsunfähigkeit und Vorabgenehmigungen', 'Dictámenes médicos, bajas laborales y autorizaciones previas', 'Pareri medici, assenze per malattia e autorizzazioni preventive'), 'INFORMATION',
    L('Données couvertes par le secret médical (RGPD art. 9)', 'Data covered by medical secrecy (GDPR Art. 9)', 'Der ärztlichen Schweigepflicht unterliegende Daten (DSGVO Art. 9)', 'Datos amparados por el secreto médico (RGPD art. 9)', 'Dati coperti dal segreto medico (GDPR art. 9)'),
    L('Médecin-chef du service', 'Chief medical officer', 'Leitender Arzt des Dienstes', 'Médico jefe del servicio', 'Medico responsabile del servizio'), 3, 4, 4, 4),
  er(['controle-medical'], L('Divulgation de données médicales d’assurés couvertes par le secret médical', 'Disclosure of insured persons’ medical data covered by medical secrecy', 'Offenlegung ärztlicher Daten von Versicherten, die der Schweigepflicht unterliegen', 'Divulgación de datos médicos de asegurados amparados por el secreto médico', 'Divulgazione di dati medici degli assicurati coperti dal segreto medico'),
    [L('Atteinte grave à la vie privée', 'Serious invasion of privacy', 'Schwere Verletzung der Privatsphäre', 'Grave atentado contra la intimidad', 'Grave violazione della riservatezza'), IMP_CNIL], 4),
  sr(['controle-medical'], L('Employeur ou tiers cherchant à connaître l’état de santé d’un assuré', 'Employer or third party seeking to learn an insured person’s health status', 'Arbeitgeber oder Dritter, der den Gesundheitszustand eines Versicherten erfahren will', 'Empleador o tercero que busca conocer el estado de salud de un asegurado', 'Datore di lavoro o terzo che cerca di conoscere lo stato di salute di un assicurato'), 'AUTRE',
    L('Sollicite un agent ou exploite une erreur d’envoi', 'Approaches a staff member or exploits a mailing error', 'Spricht Mitarbeitende an oder nutzt einen Versandfehler aus', 'Solicita a un agente o aprovecha un error de envío', 'Sollecita un operatore o sfrutta un errore di invio'),
    L('Contentieux, décision d’embauche', 'Litigation, hiring decision', 'Rechtsstreit, Einstellungsentscheidung', 'Litigio, decisión de contratación', 'Contenzioso, decisione di assunzione'),
    L('Faibles', 'Low', 'Gering', 'Bajos', 'Scarse'), 2),
  me(['controle-medical'], L('Engagements de confidentialité des prestataires intervenant sur les systèmes du service médical', 'Confidentiality undertakings from providers working on the medical service systems', 'Vertraulichkeitsverpflichtungen der Dienstleister an den Systemen des medizinischen Dienstes', 'Compromisos de confidencialidad de los proveedores que intervienen en los sistemas del servicio médico', 'Impegni di riservatezza dei fornitori che intervengono sui sistemi del servizio medico'),
    'ORGANISATIONNELLE', '6.6', L('Signés avant tout accès', 'Signed before any access', 'Vor jedem Zugriff unterzeichnet', 'Firmados antes de cualquier acceso', 'Firmati prima di ogni accesso')),
  ms(['controle-medical'], L('Cloisonnement des données médicales, accessibles aux seuls personnels du service médical', 'Segregation of medical data, accessible only to medical service staff', 'Abschottung der medizinischen Daten, nur für das Personal des medizinischen Dienstes zugänglich', 'Separación de los datos médicos, accesibles solo al personal del servicio médico', 'Separazione dei dati medici, accessibili al solo personale del servizio medico'),
    L('Habilitations dédiées et journalisation des accès', 'Dedicated access rights and access logging', 'Eigene Berechtigungen und Protokollierung der Zugriffe', 'Habilitaciones específicas y registro de accesos', 'Abilitazioni dedicate e registrazione degli accessi'),
    'TECHNIQUE', 'PROTECTION', 1, [`${RGPD}, art. 9 et 32`]),

  // ═══════════════════════════ Centre de production ═══════════════════════════
  bs(['production'], L('Grands systèmes et ordonnanceur des traitements de masse', 'Mainframes and mass-processing scheduler', 'Großrechner und Scheduler der Massenverarbeitung', 'Grandes sistemas y planificador de los tratamientos masivos', 'Mainframe e scheduler delle elaborazioni massive'), 'LOGICIEL',
    L('Cœur des calculs et des paiements', 'Core of calculations and payments', 'Kern der Berechnungen und Zahlungen', 'Núcleo de los cálculos y pagos', 'Cuore dei calcoli e dei pagamenti')),
  bs(['production'], L('Plateforme d’éditique et de courrier de masse', 'Mass print and mail platform', 'Plattform für Druck und Massenpost', 'Plataforma de impresión y correo masivo', 'Piattaforma di stampa e posta massiva'), 'SOUS_TRAITANCE',
    L('Décomptes, attestations et notifications envoyés aux assurés', 'Statements, certificates and notices sent to insured persons', 'An Versicherte versandte Abrechnungen, Bescheinigungen und Mitteilungen', 'Liquidaciones, certificados y notificaciones enviados a los asegurados', 'Estratti, attestati e notifiche inviati agli assicurati')),
  er(['production'], L('Arrêt prolongé des traitements de nuit retardant tous les paiements', 'Prolonged stop of night batches delaying all payments', 'Längerer Stillstand der Nachtläufe verzögert alle Zahlungen', 'Parada prolongada de los procesos nocturnos que retrasa todos los pagos', 'Arresto prolungato dei batch notturni che ritarda tutti i pagamenti'),
    [IMP_MASSE, IMP_CONFIANCE], 4),
  ae(['production'], 'IMPACT', 'T1486', L('Chiffrement des serveurs d’ordonnancement et de paiement', 'Encryption of scheduling and payment servers', 'Verschlüsselung der Scheduling- und Zahlungsserver', 'Cifrado de los servidores de planificación y pago', 'Cifratura dei server di schedulazione e pagamento'),
    L('Après suppression des sauvegardes accessibles', 'After deletion of reachable backups', 'Nach Löschung erreichbarer Sicherungen', 'Tras borrar las copias accesibles', 'Dopo la cancellazione dei backup raggiungibili')),
  ms(['production'], L('Bastion d’administration des grands systèmes et des ordonnanceurs', 'Administration bastion for mainframes and schedulers', 'Administrations-Bastion für Großrechner und Scheduler', 'Bastión de administración de los grandes sistemas y planificadores', 'Bastion di amministrazione dei mainframe e degli scheduler'),
    L('Comptes nominatifs, double facteur, sessions enregistrées', 'Named accounts, two-factor, recorded sessions', 'Persönliche Konten, Zwei-Faktor, aufgezeichnete Sitzungen', 'Cuentas nominativas, doble factor, sesiones grabadas', 'Account nominativi, doppio fattore, sessioni registrate'),
    'TECHNIQUE', 'PROTECTION', 1, [`${ISO}, mesure 8.2`]),
  ms(['production'], L('Sauvegardes hors ligne des chaînes de paiement et reprise testée', 'Offline backups of payment chains and tested recovery', 'Offline-Sicherungen der Zahlungsketten und getesteter Wiederanlauf', 'Copias fuera de línea de las cadenas de pago y recuperación probada', 'Backup offline delle catene di pagamento e ripresa testata'),
    L('Temps de reprise mesuré au moins une fois par an', 'Recovery time measured at least once a year', 'Wiederanlaufzeit mindestens einmal jährlich gemessen', 'Tiempo de recuperación medido al menos una vez al año', 'Tempo di ripresa misurato almeno una volta all’anno'),
    'TECHNIQUE', 'RESILIENCE', 1, [`${ISO}, mesure 8.13`]),

  // ═══════════════════════════ Services en ligne aux usagers ═══════════════════════════
  vm(['services-usagers'], L('Services en ligne aux assurés (démarches, attestations, messagerie)', 'Online services for insured persons (procedures, certificates, messaging)', 'Online-Dienste für Versicherte (Anträge, Bescheinigungen, Nachrichten)', 'Servicios en línea para los asegurados (trámites, certificados, mensajería)', 'Servizi online per gli assicurati (pratiche, attestati, messaggistica)'), 'PROCESSUS',
    L('Utilisés par des millions d’usagers', 'Used by millions of users', 'Von Millionen Nutzern verwendet', 'Utilizados por millones de usuarios', 'Utilizzati da milioni di utenti'),
    L('Direction du numérique', 'Digital department', 'Digitalabteilung', 'Dirección digital', 'Direzione digitale'), 4, 3, 4, 3),
  bs(['services-usagers'], L('Fournisseur d’identité des usagers et carte d’assurance dématérialisée', 'User identity provider and digital insurance card', 'Identitätsanbieter für Versicherte und digitale Versicherungskarte', 'Proveedor de identidad de los usuarios y tarjeta sanitaria digital', 'Provider di identità degli utenti e tessera assicurativa digitale'), 'LOGICIEL',
    L('Authentification et présentation des droits chez les professionnels', 'Authentication and proof of entitlement at professionals', 'Authentifizierung und Nachweis der Ansprüche bei Leistungserbringern', 'Autenticación y acreditación de derechos ante los profesionales', 'Autenticazione e prova dei diritti presso i professionisti')),
  er(['services-usagers'], L('Usurpation massive de comptes usagers', 'Mass takeover of user accounts', 'Massenhafte Übernahme von Versichertenkonten', 'Usurpación masiva de cuentas de usuario', 'Usurpazione massiva di account utente'),
    [IMP_MASSE, L('Détournements de prestations', 'Benefit diversions', 'Leistungsumleitungen', 'Desvíos de prestaciones', 'Dirottamenti di prestazioni'), IMP_CONFIANCE], 3),
  ae(['services-usagers'], 'ACCES_INITIAL', 'T1110.004', L('Bourrage d’identifiants sur le compte usager', 'Credential stuffing on the user account', 'Credential Stuffing auf dem Versichertenkonto', 'Relleno de credenciales en la cuenta de usuario', 'Credential stuffing sull’account utente'),
    L('Automatisé, réparti sur de nombreuses adresses', 'Automated, spread over many addresses', 'Automatisiert, über viele Adressen verteilt', 'Automatizado, repartido en muchas direcciones', 'Automatizzato, distribuito su molti indirizzi')),
  ms(['services-usagers'], L('Authentification renforcée pour les opérations sensibles du compte usager', 'Stronger authentication for sensitive operations on the user account', 'Verstärkte Authentifizierung für sensible Vorgänge im Versichertenkonto', 'Autenticación reforzada para las operaciones sensibles de la cuenta de usuario', 'Autenticazione rafforzata per le operazioni sensibili dell’account utente'),
    L('Changement d’IBAN, d’adresse ou de moyen de connexion', 'Change of IBAN, address or sign-in method', 'Änderung von IBAN, Adresse oder Anmeldeverfahren', 'Cambio de IBAN, dirección o medio de acceso', 'Modifica di IBAN, indirizzo o metodo di accesso'),
    'TECHNIQUE', 'PROTECTION', 1, [`${ISO}, mesure 8.5`]),
  ms(['services-usagers'], L('Détection du bourrage d’identifiants et blocage progressif', 'Credential-stuffing detection and progressive lockout', 'Erkennung von Credential Stuffing und schrittweise Sperrung', 'Detección del relleno de credenciales y bloqueo progresivo', 'Rilevamento del credential stuffing e blocco progressivo'),
    L('Alerte au centre de supervision', 'Alert to the monitoring centre', 'Alarm an das Überwachungszentrum', 'Alerta al centro de supervisión', 'Allerta al centro di monitoraggio'),
    'TECHNIQUE', 'DEFENSE', 1),

  // ═══════════════════════════ Services aux professionnels de santé ═══════════════════════════
  vm(['services-pro'], L('Téléservices aux professionnels de santé (droits des patients, facturation)', 'Online services for health professionals (patient entitlements, billing)', 'Online-Dienste für Gesundheitsfachkräfte (Patientenansprüche, Abrechnung)', 'Teleservicios para los profesionales sanitarios (derechos de los pacientes, facturación)', 'Servizi online per i professionisti sanitari (diritti dei pazienti, fatturazione)'), 'PROCESSUS',
    L('Consultation des droits et envoi des factures', 'Entitlement checks and invoice submission', 'Anspruchsprüfung und Rechnungsversand', 'Consulta de derechos y envío de facturas', 'Consultazione dei diritti e invio delle fatture'),
    L('Direction des relations avec les professionnels', 'Professional relations department', 'Abteilung Beziehungen zu Leistungserbringern', 'Dirección de relaciones con los profesionales', 'Direzione relazioni con i professionisti'), 4, 4, 4, 4),
  er(['services-pro'], L('Extraction massive de données d’assurés à partir de comptes de professionnels compromis', 'Mass extraction of insured persons’ data from compromised professional accounts', 'Massenhafte Extraktion von Versichertendaten über kompromittierte Konten von Leistungserbringern', 'Extracción masiva de datos de asegurados desde cuentas de profesionales comprometidas', 'Estrazione massiva di dati degli assicurati da account di professionisti compromessi'),
    [IMP_MASSE, IMP_CNIL], 4),
  sr(['services-pro'], L('Revendeur d’accès à des comptes de professionnels de santé', 'Seller of access to health professional accounts', 'Händler von Zugängen zu Konten von Gesundheitsfachkräften', 'Revendedor de accesos a cuentas de profesionales sanitarios', 'Rivenditore di accessi ad account di professionisti sanitari'), 'CYBERCRIMINEL',
    L('Vole et revend des accès aux téléservices', 'Steals and resells access to online services', 'Stiehlt und verkauft Zugänge zu Online-Diensten', 'Roba y revende accesos a los teleservicios', 'Ruba e rivende accessi ai servizi online'),
    L('Lucratif', 'Financial gain', 'Finanzieller Gewinn', 'Lucro', 'Lucro'),
    L('Logiciels voleurs d’identifiants, hameçonnage', 'Infostealers, phishing', 'Infostealer, Phishing', 'Programas ladrones de credenciales, phishing', 'Infostealer, phishing'), 3),
  ae(['services-pro'], 'EXFILTRATION', 'T1119', L('Interrogations automatisées des droits de patients depuis un compte de professionnel', 'Automated patient entitlement queries from a professional account', 'Automatisierte Abfragen von Patientenansprüchen über ein Konto eines Leistungserbringers', 'Consultas automatizadas de derechos de pacientes desde una cuenta de profesional', 'Interrogazioni automatizzate dei diritti dei pazienti da un account di professionista'),
    L('Volumes sans rapport avec l’activité du professionnel', 'Volumes unrelated to the professional’s activity', 'Mengen ohne Bezug zur Tätigkeit des Leistungserbringers', 'Volúmenes sin relación con la actividad del profesional', 'Volumi senza rapporto con l’attività del professionista')),
  ms(['services-pro'], L('Authentification forte des professionnels et quotas de consultation', 'Strong authentication of professionals and look-up quotas', 'Starke Authentifizierung der Leistungserbringer und Abrufkontingente', 'Autenticación fuerte de los profesionales y cuotas de consulta', 'Autenticazione forte dei professionisti e quote di consultazione'),
    L('Carte de professionnel ou équivalent, quotas par professionnel', 'Professional card or equivalent, per-professional quotas', 'Berufsausweis oder gleichwertig, Kontingente je Leistungserbringer', 'Tarjeta profesional o equivalente, cuotas por profesional', 'Tessera professionale o equivalente, quote per professionista'),
    'TECHNIQUE', 'PROTECTION', 1),
  ms(['services-pro'], L('Détection des volumes de consultation atypiques par professionnel', 'Detection of atypical look-up volumes per professional', 'Erkennung auffälliger Abrufmengen je Leistungserbringer', 'Detección de volúmenes de consulta atípicos por profesional', 'Rilevamento di volumi di consultazione anomali per professionista'),
    L('Suspension préventive et contact du professionnel', 'Preventive suspension and contact with the professional', 'Vorsorgliche Sperrung und Kontaktaufnahme mit dem Leistungserbringer', 'Suspensión preventiva y contacto con el profesional', 'Sospensione preventiva e contatto con il professionista'),
    'DETECTIVE', 'DEFENSE', 1),

  // ═══════════════════════════ Risques professionnels ═══════════════════════════
  vm(['risques-pro'], L('Reconnaissance des accidents du travail et maladies professionnelles, tarification des employeurs', 'Recognition of work accidents and occupational diseases, employer rate setting', 'Anerkennung von Arbeitsunfällen und Berufskrankheiten, Beitragsbemessung der Arbeitgeber', 'Reconocimiento de accidentes de trabajo y enfermedades profesionales, tarificación de los empleadores', 'Riconoscimento di infortuni sul lavoro e malattie professionali, tariffazione dei datori di lavoro'), 'PROCESSUS',
    L('Décisions opposables aux employeurs et aux victimes', 'Decisions binding on employers and victims', 'Für Arbeitgeber und Betroffene verbindliche Entscheidungen', 'Decisiones oponibles a empleadores y víctimas', 'Decisioni opponibili a datori di lavoro e vittime'),
    L('Direction des risques professionnels', 'Occupational risks department', 'Abteilung Berufsrisiken', 'Dirección de riesgos profesionales', 'Direzione rischi professionali'), 3, 4, 3, 4),
  er(['risques-pro'], L('Erreur de tarification touchant de nombreux employeurs', 'Rating error affecting many employers', 'Bemessungsfehler, der viele Arbeitgeber betrifft', 'Error de tarificación que afecta a muchos empleadores', 'Errore di tariffazione che colpisce molti datori di lavoro'),
    [L('Contestations et contentieux', 'Disputes and litigation', 'Einsprüche und Rechtsstreitigkeiten', 'Impugnaciones y contencioso', 'Contestazioni e contenzioso'), IMP_CONFIANCE], 3),
  pp(['risques-pro'], L('Employeurs et leurs tiers déclarants', 'Employers and their third-party filers', 'Arbeitgeber und ihre externen Meldestellen', 'Empleadores y sus terceros declarantes', 'Datori di lavoro e i loro intermediari dichiaranti'), 'CLIENT', 2, 2, 2, 2),
  ms(['risques-pro'], L('Double contrôle des paramètres de tarification avant notification aux employeurs', 'Dual check of rating parameters before notifying employers', 'Vier-Augen-Prüfung der Bemessungsparameter vor Mitteilung an die Arbeitgeber', 'Doble control de los parámetros de tarificación antes de notificar a los empleadores', 'Doppio controllo dei parametri di tariffazione prima della notifica ai datori di lavoro'),
    L('Échantillon de calculs revérifiés', 'Sample of recalculated rates', 'Stichprobe nachgerechneter Werte', 'Muestra de cálculos verificados', 'Campione di calcoli riverificati'),
    'ORGANISATIONNELLE', 'PROTECTION', 2),

  // ═══════════════════════════ Gestion du risque et prévention ═══════════════════════════
  vm(['prevention'], L('Programmes de dépistage et d’accompagnement des patients (invitations, suivi)', 'Screening and patient support programmes (invitations, follow-up)', 'Früherkennungs- und Begleitprogramme (Einladungen, Nachverfolgung)', 'Programas de cribado y acompañamiento de pacientes (invitaciones, seguimiento)', 'Programmi di screening e accompagnamento dei pazienti (inviti, follow-up)'), 'PROCESSUS',
    L('Ciblage de populations à partir de données de santé', 'Targeting populations based on health data', 'Zielgruppenauswahl anhand von Gesundheitsdaten', 'Selección de poblaciones a partir de datos de salud', 'Selezione delle popolazioni a partire da dati sanitari'),
    L('Direction de la prévention', 'Prevention department', 'Abteilung Prävention', 'Dirección de prevención', 'Direzione prevenzione'), 2, 4, 4, 3),
  er(['prevention'], L('Envoi d’invitations ou de résultats à de mauvais destinataires', 'Invitations or results sent to the wrong recipients', 'Einladungen oder Ergebnisse an falsche Empfänger', 'Envío de invitaciones o resultados a destinatarios equivocados', 'Invio di inviti o risultati a destinatari sbagliati'),
    [L('Divulgation de données de santé', 'Disclosure of health data', 'Offenlegung von Gesundheitsdaten', 'Divulgación de datos de salud', 'Divulgazione di dati sanitari'), IMP_CNIL], 3),
  ms(['prevention'], L('Contrôle des fichiers de ciblage avant chaque campagne (destinataires, minimisation)', 'Check of targeting files before each campaign (recipients, minimisation)', 'Prüfung der Zielgruppendateien vor jeder Kampagne (Empfänger, Minimierung)', 'Control de los ficheros de selección antes de cada campaña (destinatarios, minimización)', 'Controllo dei file di selezione prima di ogni campagna (destinatari, minimizzazione)'),
    L('Échantillon vérifié et validé par le responsable du programme', 'Sample checked and approved by the programme owner', 'Stichprobe geprüft und vom Programmverantwortlichen freigegeben', 'Muestra verificada y validada por el responsable del programa', 'Campione verificato e approvato dal responsabile del programma'),
    'ORGANISATIONNELLE', 'PROTECTION', 2, [`${RGPD}, art. 5`]),

  // ═══════════════════════════ Lutte contre la fraude ═══════════════════════════
  vm(['fraude'], L('Détection et traitement de la fraude (signalements, enquêtes, contentieux)', 'Fraud detection and handling (reports, investigations, litigation)', 'Erkennung und Bearbeitung von Betrug (Meldungen, Ermittlungen, Rechtsstreitigkeiten)', 'Detección y tratamiento del fraude (denuncias, investigaciones, contencioso)', 'Rilevamento e trattamento delle frodi (segnalazioni, indagini, contenzioso)'), 'PROCESSUS',
    L('Préjudice détecté, évité et recouvré', 'Loss detected, prevented and recovered', 'Erkannter, verhinderter und zurückgeholter Schaden', 'Perjuicio detectado, evitado y recuperado', 'Danno rilevato, evitato e recuperato'),
    L('Direction de la lutte contre la fraude', 'Anti-fraud department', 'Abteilung Betrugsbekämpfung', 'Dirección de lucha contra el fraude', 'Direzione antifrode'), 2, 4, 4, 4),
  bs(['fraude'], L('Outils d’exploration de données et de ciblage des contrôles', 'Data mining and control-targeting tools', 'Werkzeuge für Datenanalyse und Kontrollauswahl', 'Herramientas de minería de datos y selección de controles', 'Strumenti di analisi dei dati e di selezione dei controlli'), 'LOGICIEL',
    L('Scores et règles de détection', 'Detection scores and rules', 'Erkennungsscores und -regeln', 'Puntuaciones y reglas de detección', 'Punteggi e regole di rilevamento')),
  er(['fraude'], L('Fuite des critères de ciblage permettant de contourner les contrôles', 'Leak of targeting criteria allowing controls to be bypassed', 'Abfluss der Auswahlkriterien, der die Umgehung der Kontrollen ermöglicht', 'Fuga de los criterios de selección que permite eludir los controles', 'Fuga dei criteri di selezione che consente di eludere i controlli'),
    [L('Fraude non détectée', 'Undetected fraud', 'Unerkannter Betrug', 'Fraude no detectado', 'Frode non rilevata'), L('Perte d’efficacité du dispositif', 'Loss of effectiveness of the system', 'Wirksamkeitsverlust des Dispositivs', 'Pérdida de eficacia del dispositivo', 'Perdita di efficacia del dispositivo')], 3),
  sr(['fraude'], L('Fraudeur interne protégeant un réseau', 'Insider protecting a fraud ring', 'Innentäter, der einen Betrugsring schützt', 'Defraudador interno que protege una red', 'Truffatore interno che protegge una rete'), 'EMPLOYE_MALVEILLANT',
    L('Écarte des dossiers des contrôles ou divulgue les critères', 'Removes files from controls or discloses criteria', 'Nimmt Vorgänge von Kontrollen aus oder gibt Kriterien preis', 'Excluye expedientes de los controles o divulga los criterios', 'Esclude pratiche dai controlli o divulga i criteri'),
    L('Lucratif', 'Financial gain', 'Finanzieller Gewinn', 'Lucro', 'Lucro'),
    L('Accès aux outils de ciblage', 'Access to targeting tools', 'Zugang zu den Auswahlwerkzeugen', 'Acceso a las herramientas de selección', 'Accesso agli strumenti di selezione'), 2),
  ms(['fraude'], L('Habilitations restreintes et journalisées sur les outils de ciblage', 'Restricted and logged access to targeting tools', 'Eingeschränkte und protokollierte Berechtigungen für die Auswahlwerkzeuge', 'Habilitaciones restringidas y registradas en las herramientas de selección', 'Abilitazioni limitate e registrate sugli strumenti di selezione'),
    L('Revue semestrielle des personnes habilitées', 'Half-yearly review of authorised staff', 'Halbjährliche Überprüfung der berechtigten Personen', 'Revisión semestral de las personas habilitadas', 'Revisione semestrale delle persone abilitate'),
    'TECHNIQUE', 'PROTECTION', 1),
  ms(['fraude'], L('Contrôle humain des décisions issues des algorithmes de ciblage', 'Human oversight of decisions from targeting algorithms', 'Menschliche Aufsicht über Entscheidungen aus Auswahlalgorithmen', 'Control humano de las decisiones procedentes de los algoritmos de selección', 'Controllo umano delle decisioni derivanti dagli algoritmi di selezione'),
    L('Aucune sanction sans examen par un agent', 'No sanction without review by a staff member', 'Keine Sanktion ohne Prüfung durch einen Mitarbeitenden', 'Ninguna sanción sin examen por un agente', 'Nessuna sanzione senza esame da parte di un operatore'),
    'ORGANISATIONNELLE', 'GOUVERNANCE', 1, ['Règlement (UE) 2024/1689 (intelligence artificielle) — applicabilité à vérifier']),

  // ═══════════════════════════ Données nationales ═══════════════════════════
  vm(['donnees'], L('Mise à disposition de données nationales pour la recherche et les statistiques publiques', 'Provision of national data for research and official statistics', 'Bereitstellung nationaler Daten für Forschung und amtliche Statistik', 'Puesta a disposición de datos nacionales para la investigación y las estadísticas públicas', 'Messa a disposizione di dati nazionali per la ricerca e le statistiche pubbliche'), 'PROCESSUS',
    L('Extractions pseudonymisées pour des projets autorisés', 'Pseudonymised extracts for authorised projects', 'Pseudonymisierte Auszüge für genehmigte Projekte', 'Extracciones seudonimizadas para proyectos autorizados', 'Estrazioni pseudonimizzate per progetti autorizzati'),
    L('Direction des données', 'Data department', 'Datenabteilung', 'Dirección de datos', 'Direzione dei dati'), 2, 4, 4, 4),
  er(['donnees'], L('Réidentification de personnes à partir de données mises à disposition', 'Re-identification of people from provided data', 'Re-Identifizierung von Personen aus bereitgestellten Daten', 'Reidentificación de personas a partir de datos puestos a disposición', 'Reidentificazione di persone a partire dai dati messi a disposizione'),
    [L('Atteinte grave à la vie privée', 'Serious invasion of privacy', 'Schwere Verletzung der Privatsphäre', 'Grave atentado contra la intimidad', 'Grave violazione della riservatezza'), IMP_CNIL], 4),
  ms(['donnees'], L('Revue du risque de réidentification avant chaque mise à disposition', 'Re-identification risk review before each data release', 'Prüfung des Re-Identifizierungsrisikos vor jeder Bereitstellung', 'Revisión del riesgo de reidentificación antes de cada puesta a disposición', 'Revisione del rischio di reidentificazione prima di ogni messa a disposizione'),
    L('Seuils de petits effectifs, agrégation', 'Small-count thresholds, aggregation', 'Schwellen für kleine Fallzahlen, Aggregation', 'Umbrales de efectivos pequeños, agregación', 'Soglie per piccoli numeri, aggregazione'),
    'ORGANISATIONNELLE', 'PROTECTION', 1, [`${RGPD}, art. 89`]),

  // ═══════════════════════════ International ═══════════════════════════
  vm(['international'], L('Prise en charge des soins à l’étranger et échanges avec les institutions étrangères', 'Coverage of care abroad and exchanges with foreign institutions', 'Übernahme von Behandlungen im Ausland und Austausch mit ausländischen Trägern', 'Cobertura de la asistencia en el extranjero e intercambios con instituciones extranjeras', 'Copertura delle cure all’estero e scambi con istituzioni estere'), 'PROCESSUS',
    L('Remboursements et créances entre institutions', 'Reimbursements and claims between institutions', 'Erstattungen und Forderungen zwischen Trägern', 'Reembolsos y créditos entre instituciones', 'Rimborsi e crediti tra istituzioni'),
    L('Service des relations internationales', 'International relations service', 'Abteilung internationale Beziehungen', 'Servicio de relaciones internacionales', 'Servizio relazioni internazionali'), 2, 4, 3, 4),
  bs(['international'], L('Échanges électroniques avec les institutions de sécurité sociale étrangères', 'Electronic exchanges with foreign social security institutions', 'Elektronischer Austausch mit ausländischen Sozialversicherungsträgern', 'Intercambios electrónicos con instituciones de seguridad social extranjeras', 'Scambi elettronici con le istituzioni di sicurezza sociale estere'), 'RESEAU',
    L('Flux normalisés entre pays', 'Standardised flows between countries', 'Standardisierte Datenflüsse zwischen Ländern', 'Flujos normalizados entre países', 'Flussi standardizzati tra paesi')),
  er(['international'], L('Remboursement de soins fictifs à l’étranger sur faux justificatifs', 'Reimbursement of fictitious care abroad on forged documents', 'Erstattung fiktiver Auslandsbehandlungen auf Grundlage gefälschter Belege', 'Reembolso de asistencia ficticia en el extranjero con justificantes falsos', 'Rimborso di cure fittizie all’estero su giustificativi falsi'),
    [L('Prestations indues', 'Undue benefits', 'Unberechtigte Leistungen', 'Prestaciones indebidas', 'Prestazioni indebite')], 2),
  ms(['international'], L('Contrôle renforcé des justificatifs étrangers et des montants atypiques', 'Enhanced checks of foreign documents and atypical amounts', 'Verstärkte Prüfung ausländischer Belege und auffälliger Beträge', 'Control reforzado de los justificantes extranjeros y de los importes atípicos', 'Controllo rafforzato dei giustificativi esteri e degli importi atipici'),
    L('Vérification auprès de l’institution du pays concerné', 'Verification with the institution of the country concerned', 'Prüfung beim Träger des betreffenden Landes', 'Verificación ante la institución del país correspondiente', 'Verifica presso l’istituzione del paese interessato'),
    'DETECTIVE', 'DEFENSE', 2),

  // ═══════════════════════════ Action sanitaire et sociale ═══════════════════════════
  vm(['action-sociale'], L('Attribution des aides individuelles (dossiers, commissions, paiements)', 'Granting of individual assistance (files, committees, payments)', 'Gewährung von Einzelbeihilfen (Anträge, Ausschüsse, Zahlungen)', 'Concesión de ayudas individuales (expedientes, comisiones, pagos)', 'Attribuzione degli aiuti individuali (pratiche, commissioni, pagamenti)'), 'PROCESSUS',
    L('Données sociales sensibles des demandeurs', 'Sensitive social data of applicants', 'Sensible Sozialdaten der Antragsteller', 'Datos sociales sensibles de los solicitantes', 'Dati sociali sensibili dei richiedenti'),
    L('Service de l’action sociale', 'Social support service', 'Abteilung Sozialhilfe', 'Servicio de acción social', 'Servizio di azione sociale'), 2, 4, 4, 4),
  er(['action-sociale'], L('Attribution d’aides indues par favoritisme ou fraude documentaire', 'Undue assistance granted through favouritism or document fraud', 'Unberechtigte Beihilfen durch Begünstigung oder Dokumentenbetrug', 'Concesión de ayudas indebidas por favoritismo o fraude documental', 'Attribuzione di aiuti indebiti per favoritismo o frode documentale'),
    [L('Préjudice financier', 'Financial loss', 'Finanzieller Schaden', 'Perjuicio económico', 'Danno finanziario'), IMP_CONFIANCE], 2),
  ms(['action-sociale'], L('Séparation entre instruction, décision et paiement des aides', 'Separation between processing, decision and payment of assistance', 'Trennung von Bearbeitung, Entscheidung und Zahlung der Beihilfen', 'Separación entre instrucción, decisión y pago de las ayudas', 'Separazione tra istruttoria, decisione e pagamento degli aiuti'),
    L('Aucune personne ne réalise seule les trois étapes', 'No one carries out all three steps alone', 'Niemand führt alle drei Schritte allein aus', 'Nadie realiza solo las tres etapas', 'Nessuno esegue da solo le tre fasi'),
    'ORGANISATIONNELLE', 'PROTECTION', 2),

  // ═══════════════════════════ Gestion pour le compte d'autres régimes ═══════════════════════════
  vm(['mandats'], L('Gestion pour le compte d’autres régimes et reddition de comptes', 'Administration on behalf of other schemes and reporting', 'Verwaltung im Auftrag anderer Systeme und Rechenschaftslegung', 'Gestión por cuenta de otros regímenes y rendición de cuentas', 'Gestione per conto di altri regimi e rendicontazione'), 'PROCESSUS',
    L('Données de plusieurs régimes dans les mêmes systèmes', 'Data of several schemes in the same systems', 'Daten mehrerer Systeme in denselben Anwendungen', 'Datos de varios regímenes en los mismos sistemas', 'Dati di più regimi negli stessi sistemi'),
    L('Direction des partenariats', 'Partnerships department', 'Abteilung Partnerschaften', 'Dirección de alianzas', 'Direzione partenariati'), 3, 4, 4, 4),
  er(['mandats'], L('Données d’un régime mandant exposées à un autre (rupture de cloisonnement)', 'Data of one mandating scheme exposed to another (segregation failure)', 'Daten eines auftraggebenden Systems einem anderen offengelegt (Trennungsfehler)', 'Datos de un régimen mandante expuestos a otro (fallo de separación)', 'Dati di un regime mandante esposti a un altro (rottura della separazione)'),
    [IMP_CNIL, L('Rupture de la convention de gestion', 'Breach of the administration agreement', 'Verletzung der Verwaltungsvereinbarung', 'Ruptura del convenio de gestión', 'Rottura della convenzione di gestione')], 4),
  ms(['mandats'], L('Cloisonnement des données par régime mandant et reddition de comptes périodique', 'Data segregation per mandating scheme and periodic reporting', 'Datentrennung je auftraggebendem System und regelmäßige Rechenschaftslegung', 'Separación de los datos por régimen mandante y rendición de cuentas periódica', 'Separazione dei dati per regime mandante e rendicontazione periodica'),
    L('Tests de non-régression du cloisonnement à chaque version', 'Segregation regression tests at each release', 'Regressionstests der Trennung bei jeder Version', 'Pruebas de no regresión de la separación en cada versión', 'Test di non regressione della separazione a ogni versione'),
    'TECHNIQUE', 'PROTECTION', 1),
]
