/**
 * Contenu des patterns « Exposition et zones de sécurité » (lot 1) : exposition sur Internet, DMZ, zone de confiance,
 * zone de moindre confiance, accès distant. Générique (valable pour tout secteur) ; textes ×5 dans la donnée.
 * Références citées par intitulé et version, sans reprise d'exigence. Contenu « à relire par un expert ».
 */
import { L, bs, er, sr, ss, ae, ms, me, type PatternItem } from '@/lib/exemples-patterns-core'

const INTERNET = ['EXPOSITION_INTERNET'] as const
const DMZ = ['DMZ'] as const
const CONF = ['ZONE_CONFIANCE'] as const
const MOINDRE = ['ZONE_MOINDRE_CONFIANCE'] as const
const DISTANT = ['ACCES_DISTANT'] as const
const OWASP = 'OWASP Top 10 — 2021'

export const EXPOSITION_ITEMS: PatternItem[] = [
  // ═══ Exposition sur Internet ═══════════════════════════════════════════════════════════════════
  bs(INTERNET, L('Application web ou téléservice exposé sur Internet', 'Web application or online service exposed to the Internet', 'Im Internet erreichbare Webanwendung oder Online-Dienst', 'Aplicación web o servicio en línea expuesto a Internet', 'Applicazione web o servizio online esposto a Internet'), 'LOGICIEL',
    L('Portail, site transactionnel ou espace client joignable depuis Internet, avec comptes utilisateurs', 'Portal, transactional site or customer area reachable from the Internet, with user accounts', 'Portal, Transaktionsseite oder Kundenbereich aus dem Internet erreichbar, mit Benutzerkonten', 'Portal, sitio transaccional o área de cliente accesible desde Internet, con cuentas de usuario', 'Portale, sito transazionale o area clienti raggiungibile da Internet, con account utente')),
  bs(INTERNET, L('Noms de domaine, DNS et certificats TLS publics', 'Domain names, DNS and public TLS certificates', 'Domainnamen, DNS und öffentliche TLS-Zertifikate', 'Nombres de dominio, DNS y certificados TLS públicos', 'Nomi di dominio, DNS e certificati TLS pubblici'), 'RESEAU',
    L('Enregistrement des domaines, zones DNS et certificats dont dépend l’accessibilité et la confiance du service', 'Domain registration, DNS zones and certificates the service’s reachability and trust depend on', 'Domainregistrierung, DNS-Zonen und Zertifikate, von denen Erreichbarkeit und Vertrauen des Dienstes abhängen', 'Registro de dominios, zonas DNS y certificados de los que dependen la accesibilidad y la confianza del servicio', 'Registrazione dei domini, zone DNS e certificati da cui dipendono la raggiungibilità e la fiducia nel servizio')),
  bs(INTERNET, L('Protection contre les attaques par déni de service (service anti-DDoS, répartiteur de charge)', 'Denial-of-service protection (anti-DDoS service, load balancer)', 'Schutz gegen Denial-of-Service-Angriffe (Anti-DDoS-Dienst, Lastverteiler)', 'Protección contra ataques de denegación de servicio (servicio anti-DDoS, balanceador de carga)', 'Protezione da attacchi di negazione del servizio (servizio anti-DDoS, bilanciatore di carico)'), 'RESEAU',
    L('Dispositif en frontal qui absorbe ou filtre les attaques volumétriques et applicatives', 'Front-end mechanism that absorbs or filters volumetric and application attacks', 'Frontend-Mechanismus, der volumetrische und anwendungsbezogene Angriffe absorbiert oder filtert', 'Dispositivo frontal que absorbe o filtra los ataques volumétricos y de aplicación', 'Dispositivo in prima linea che assorbe o filtra gli attacchi volumetrici e applicativi')),
  er(INTERNET, L('Service indisponible pour les usagers à la suite d’une attaque par déni de service', 'Service unavailable to users following a denial-of-service attack', 'Dienst für Nutzer nach einem Denial-of-Service-Angriff nicht verfügbar', 'Servicio no disponible para los usuarios tras un ataque de denegación de servicio', 'Servizio non disponibile agli utenti a seguito di un attacco di negazione del servizio'),
    [L('Perte de confiance des usagers', 'Loss of user trust', 'Vertrauensverlust bei den Nutzern', 'Pérdida de confianza de los usuarios', 'Perdita di fiducia degli utenti'), L('Interruption de l’activité en ligne', 'Interruption of online activity', 'Unterbrechung der Online-Aktivität', 'Interrupción de la actividad en línea', 'Interruzione dell’attività online')], 3),
  er(INTERNET, L('Défiguration du site ou compromission du service exposé par un tiers', 'Defacement of the site or compromise of the exposed service by a third party', 'Verunstaltung der Website oder Kompromittierung des exponierten Dienstes durch Dritte', 'Desfiguración del sitio o compromiso del servicio expuesto por un tercero', 'Defacement del sito o compromissione del servizio esposto da parte di terzi'),
    [L('Atteinte à l’image', 'Damage to reputation', 'Rufschädigung', 'Daño a la imagen', 'Danno all’immagine'), L('Diffusion de contenus frauduleux aux usagers', 'Distribution of fraudulent content to users', 'Verbreitung betrügerischer Inhalte an Nutzer', 'Difusión de contenidos fraudulentos a los usuarios', 'Diffusione di contenuti fraudolenti agli utenti')], 3),
  sr(INTERNET, L('Cybercriminel opportuniste scannant Internet', 'Opportunistic cybercriminal scanning the Internet', 'Opportunistischer Cyberkrimineller, der das Internet scannt', 'Cibercriminal oportunista que rastrea Internet', 'Cybercriminale opportunista che scansiona Internet'), 'CYBERCRIMINEL',
    L('Acteur qui recherche en continu des services exposés vulnérables ou mal configurés', 'Actor continuously searching for vulnerable or misconfigured exposed services', 'Akteur, der laufend nach verwundbaren oder falsch konfigurierten exponierten Diensten sucht', 'Actor que busca de forma continua servicios expuestos vulnerables o mal configurados', 'Attore che cerca di continuo servizi esposti vulnerabili o mal configurati'),
    L('Gain financier, revente d’accès, rançongiciel', 'Financial gain, resale of access, ransomware', 'Finanzieller Gewinn, Weiterverkauf von Zugängen, Ransomware', 'Beneficio económico, reventa de accesos, ransomware', 'Guadagno economico, rivendita di accessi, ransomware'),
    L('Outils automatisés, exploits publics, listes d’identifiants volés', 'Automated tools, public exploits, stolen credential lists', 'Automatisierte Werkzeuge, öffentliche Exploits, gestohlene Zugangsdaten', 'Herramientas automatizadas, exploits públicos, listas de credenciales robadas', 'Strumenti automatizzati, exploit pubblici, elenchi di credenziali rubate'), 4),
  ss(INTERNET, 'C', L('Un attaquant exploite une vulnérabilité du service exposé et exfiltre les données des usagers (C)', 'An attacker exploits a vulnerability in the exposed service and exfiltrates user data (C)', 'Ein Angreifer nutzt eine Schwachstelle des exponierten Dienstes und exfiltriert Nutzerdaten (C)', 'Un atacante explota una vulnerabilidad del servicio expuesto y exfiltra los datos de los usuarios (C)', 'Un attaccante sfrutta una vulnerabilità del servizio esposto ed esfiltra i dati degli utenti (C)'),
    L('Injection, faille d’authentification ou configuration d’exposition faible menant à l’extraction de données', 'Injection, authentication flaw or weak exposure configuration leading to data extraction', 'Injection, Authentifizierungsfehler oder schwache Exposition führen zur Datenextraktion', 'Inyección, fallo de autenticación o configuración de exposición débil que lleva a la extracción de datos', 'Injection, falla di autenticazione o configurazione di esposizione debole che porta all’estrazione di dati'), 3, 4),
  ae(INTERNET, 'ACCES_INITIAL', 'T1190', L('Exploitation d’une vulnérabilité de l’application exposée sur Internet', 'Exploitation of a vulnerability in the Internet-facing application', 'Ausnutzung einer Schwachstelle der aus dem Internet erreichbaren Anwendung', 'Explotación de una vulnerabilidad de la aplicación expuesta a Internet', 'Sfruttamento di una vulnerabilità dell’applicazione esposta a Internet'),
    L('Injection, désérialisation ou faille d’un composant non corrigé accessible sans authentification', 'Injection, deserialisation or flaw in an unpatched component reachable without authentication', 'Injection, Deserialisierung oder Fehler in einer ungepatchten, ohne Anmeldung erreichbaren Komponente', 'Inyección, deserialización o fallo de un componente sin parchear accesible sin autenticación', 'Injection, deserializzazione o falla di un componente non aggiornato raggiungibile senza autenticazione')),
  ms(INTERNET, L('Inventaire des services exposés sur Internet et balayage externe régulier', 'Inventory of Internet-exposed services and regular external scanning', 'Inventar der im Internet exponierten Dienste und regelmäßiges externes Scannen', 'Inventario de los servicios expuestos a Internet y escaneo externo periódico', 'Inventario dei servizi esposti a Internet e scansione esterna periodica'),
    L('Recenser tout ce qui est joignable depuis Internet, supprimer l’inutile et vérifier chaque mois ce qui est réellement visible', 'List everything reachable from the Internet, remove what is not needed and check monthly what is actually visible', 'Alles erfassen, was aus dem Internet erreichbar ist, Überflüssiges entfernen und monatlich prüfen, was tatsächlich sichtbar ist', 'Inventariar todo lo accesible desde Internet, eliminar lo innecesario y comprobar cada mes lo que realmente es visible', 'Censire tutto ciò che è raggiungibile da Internet, eliminare il superfluo e verificare ogni mese ciò che è realmente visibile'),
    'PREVENTIVE', 'PROTECTION', 1),
  ms(INTERNET, L('Pare-feu applicatif (WAF), correctifs rapides et tests d’intrusion avant mise en ligne', 'Web application firewall (WAF), fast patching and penetration tests before go-live', 'Web Application Firewall (WAF), schnelles Patchen und Penetrationstests vor der Inbetriebnahme', 'Cortafuegos de aplicaciones web (WAF), parcheo rápido y pruebas de intrusión antes de la puesta en línea', 'Web application firewall (WAF), aggiornamenti rapidi e test di intrusione prima della messa online'),
    L('Filtrer les attaques courantes, corriger sous quelques jours les failles critiques et tester toute nouvelle exposition', 'Filter common attacks, fix critical flaws within days and test every new exposure', 'Gängige Angriffe filtern, kritische Schwachstellen binnen Tagen beheben und jede neue Exposition testen', 'Filtrar los ataques habituales, corregir en pocos días los fallos críticos y probar toda nueva exposición', 'Filtrare gli attacchi comuni, correggere in pochi giorni le falle critiche e testare ogni nuova esposizione'),
    'TECHNIQUE', 'PROTECTION', 1, [OWASP]),
  ms(INTERNET, L('Authentification forte et limitation des tentatives sur les comptes exposés', 'Strong authentication and attempt limiting on exposed accounts', 'Starke Authentifizierung und Begrenzung von Versuchen bei exponierten Konten', 'Autenticación fuerte y limitación de intentos en las cuentas expuestas', 'Autenticazione forte e limitazione dei tentativi sugli account esposti'),
    L('Imposer un second facteur aux comptes à privilèges, bloquer le bourrage d’identifiants et surveiller les connexions inhabituelles', 'Require a second factor for privileged accounts, block credential stuffing and monitor unusual sign-ins', 'Zweiten Faktor für privilegierte Konten verlangen, Credential Stuffing blockieren und ungewöhnliche Anmeldungen überwachen', 'Exigir un segundo factor a las cuentas con privilegios, bloquear el relleno de credenciales y vigilar los accesos inusuales', 'Imporre un secondo fattore agli account privilegiati, bloccare il credential stuffing e monitorare gli accessi insoliti'),
    'TECHNIQUE', 'PROTECTION', 2),

  // ═══ Zone démilitarisée (DMZ) ══════════════════════════════════════════════════════════════════
  bs(DMZ, L('Serveurs frontaux et reverse proxy en DMZ', 'Front-end servers and reverse proxies in the DMZ', 'Frontend-Server und Reverse-Proxys in der DMZ', 'Servidores frontales y proxy inverso en la DMZ', 'Server frontend e reverse proxy in DMZ'), 'MATERIEL',
    L('Serveurs qui reçoivent le trafic d’Internet et le relaient vers le SI interne sans l’exposer directement', 'Servers that receive Internet traffic and relay it to the internal IS without exposing it directly', 'Server, die Internetverkehr empfangen und an das interne IS weiterleiten, ohne es direkt zu exponieren', 'Servidores que reciben el tráfico de Internet y lo retransmiten al SI interno sin exponerlo directamente', 'Server che ricevono il traffico da Internet e lo inoltrano al SI interno senza esporlo direttamente')),
  bs(DMZ, L('Pare-feux et règles de filtrage entre Internet, la DMZ et le SI interne', 'Firewalls and filtering rules between the Internet, the DMZ and the internal IS', 'Firewalls und Filterregeln zwischen Internet, DMZ und internem IS', 'Cortafuegos y reglas de filtrado entre Internet, la DMZ y el SI interno', 'Firewall e regole di filtraggio tra Internet, DMZ e SI interno'), 'RESEAU',
    L('Matrice de flux autorisés dont l’exactitude et l’entretien conditionnent le cloisonnement', 'Matrix of allowed flows whose accuracy and upkeep determine the segregation', 'Matrix der erlaubten Flüsse, deren Richtigkeit und Pflege die Trennung bestimmen', 'Matriz de flujos autorizados cuya exactitud y mantenimiento condicionan la segregación', 'Matrice dei flussi autorizzati la cui correttezza e manutenzione condizionano la segregazione')),
  er(DMZ, L('Compromission d’un serveur de la DMZ servant de rebond vers le SI interne', 'Compromise of a DMZ server used as a pivot into the internal IS', 'Kompromittierung eines DMZ-Servers als Sprungbrett ins interne IS', 'Compromiso de un servidor de la DMZ utilizado como salto hacia el SI interno', 'Compromissione di un server in DMZ usato come trampolino verso il SI interno'),
    [L('Intrusion dans le SI interne', 'Intrusion into the internal IS', 'Eindringen in das interne IS', 'Intrusión en el SI interno', 'Intrusione nel SI interno'), L('Perte de maîtrise du cloisonnement', 'Loss of control over segregation', 'Kontrollverlust über die Trennung', 'Pérdida de control de la segregación', 'Perdita di controllo della segregazione')], 4),
  ss(DMZ, 'C', L('Un attaquant prend le contrôle d’un frontal de la DMZ puis exploite des flux autorisés vers le cœur du SI (C)', 'An attacker takes control of a DMZ front end then abuses allowed flows into the core IS (C)', 'Ein Angreifer übernimmt ein DMZ-Frontend und nutzt erlaubte Flüsse zum Kern-IS (C)', 'Un atacante toma el control de un frontal de la DMZ y luego aprovecha flujos autorizados hacia el núcleo del SI (C)', 'Un attaccante prende il controllo di un frontend in DMZ e poi sfrutta flussi autorizzati verso il cuore del SI (C)'),
    L('Règles trop larges entre la DMZ et l’interne qui permettent d’atteindre bases de données et annuaire', 'Rules too broad between the DMZ and the inside allowing databases and the directory to be reached', 'Zu weit gefasste Regeln zwischen DMZ und Intern, die Datenbanken und Verzeichnis erreichbar machen', 'Reglas demasiado amplias entre la DMZ y el interior que permiten alcanzar bases de datos y directorio', 'Regole troppo ampie tra DMZ e interno che permettono di raggiungere database e directory'), 3, 4),
  ae(DMZ, 'MOUVEMENT_LATERAL', 'T1021', L('Rebond depuis un serveur de la DMZ vers le SI interne par un flux autorisé', 'Pivot from a DMZ server into the internal IS through an allowed flow', 'Sprung von einem DMZ-Server ins interne IS über einen erlaubten Fluss', 'Salto desde un servidor de la DMZ hacia el SI interno por un flujo autorizado', 'Salto da un server in DMZ al SI interno attraverso un flusso autorizzato'),
    L('Utilisation d’un compte de service ou d’une règle de pare-feu trop permissive pour atteindre les serveurs internes', 'Use of a service account or an overly permissive firewall rule to reach internal servers', 'Nutzung eines Dienstkontos oder einer zu freizügigen Firewall-Regel, um interne Server zu erreichen', 'Uso de una cuenta de servicio o de una regla de cortafuegos demasiado permisiva para llegar a los servidores internos', 'Uso di un account di servizio o di una regola di firewall troppo permissiva per raggiungere i server interni')),
  ms(DMZ, L('Aucune connexion initiée depuis la DMZ vers l’interne sans besoin documenté ; flux restreints au strict nécessaire', 'No connection initiated from the DMZ to the inside without a documented need; flows limited to the strict minimum', 'Keine aus der DMZ initiierte Verbindung nach intern ohne dokumentierten Bedarf; Flüsse auf das Notwendige beschränkt', 'Ninguna conexión iniciada desde la DMZ hacia el interior sin necesidad documentada; flujos limitados a lo estrictamente necesario', 'Nessuna connessione avviata dalla DMZ verso l’interno senza necessità documentata; flussi limitati allo stretto necessario'),
    L('Revue des règles au moins une fois par an et à chaque changement, suppression des règles obsolètes', 'Review rules at least yearly and at each change, remove obsolete rules', 'Regeln mindestens jährlich und bei jeder Änderung prüfen, veraltete Regeln entfernen', 'Revisar las reglas al menos una vez al año y en cada cambio, eliminar las obsoletas', 'Rivedere le regole almeno una volta all’anno e a ogni modifica, eliminare quelle obsolete'),
    'PREVENTIVE', 'PROTECTION', 1),
  ms(DMZ, L('Durcissement et supervision des serveurs de la DMZ, mises à jour prioritaires', 'Hardening and monitoring of DMZ servers, priority updates', 'Härtung und Überwachung der DMZ-Server, priorisierte Updates', 'Endurecimiento y supervisión de los servidores de la DMZ, actualizaciones prioritarias', 'Hardening e monitoraggio dei server in DMZ, aggiornamenti prioritari'),
    L('Configuration minimale, journalisation centralisée et détection des comportements anormaux sur ces serveurs exposés', 'Minimal configuration, centralised logging and detection of abnormal behaviour on these exposed servers', 'Minimalkonfiguration, zentrale Protokollierung und Erkennung abnormalen Verhaltens auf diesen exponierten Servern', 'Configuración mínima, registro centralizado y detección de comportamientos anómalos en estos servidores expuestos', 'Configurazione minima, registrazione centralizzata e rilevamento di comportamenti anomali su questi server esposti'),
    'TECHNIQUE', 'DEFENSE', 2),

  // ═══ Zone de confiance ═════════════════════════════════════════════════════════════════════════
  bs(CONF, L('Serveurs de données et de traitements sensibles en zone de confiance', 'Sensitive data and processing servers in the trusted zone', 'Server für sensible Daten und Verarbeitungen in der vertrauenswürdigen Zone', 'Servidores de datos y tratamientos sensibles en la zona de confianza', 'Server di dati e trattamenti sensibili in zona di fiducia'), 'MATERIEL',
    L('Bases de données et applications dont la compromission aurait l’impact le plus élevé, hébergées dans une zone à accès restreint', 'Databases and applications whose compromise would have the highest impact, hosted in a restricted-access zone', 'Datenbanken und Anwendungen, deren Kompromittierung die größten Folgen hätte, in einer Zone mit eingeschränktem Zugriff', 'Bases de datos y aplicaciones cuyo compromiso tendría el mayor impacto, alojadas en una zona de acceso restringido', 'Database e applicazioni la cui compromissione avrebbe l’impatto maggiore, ospitate in una zona ad accesso ristretto')),
  bs(CONF, L('Contrôle des accès à la zone de confiance (annuaire, comptes d’administration, bastion)', 'Access control to the trusted zone (directory, administration accounts, bastion)', 'Zugriffskontrolle auf die vertrauenswürdige Zone (Verzeichnis, Administrationskonten, Bastion)', 'Control de acceso a la zona de confianza (directorio, cuentas de administración, bastión)', 'Controllo degli accessi alla zona di fiducia (directory, account di amministrazione, bastion)'), 'LOGICIEL',
    L('Mécanismes qui décident qui peut entrer dans la zone et avec quels droits', 'Mechanisms that decide who can enter the zone and with which rights', 'Mechanismen, die entscheiden, wer die Zone mit welchen Rechten betreten darf', 'Mecanismos que deciden quién puede entrar en la zona y con qué derechos', 'Meccanismi che decidono chi può entrare nella zona e con quali diritti')),
  er(CONF, L('Intrusion dans la zone de confiance et exfiltration des données les plus sensibles', 'Intrusion into the trusted zone and exfiltration of the most sensitive data', 'Eindringen in die vertrauenswürdige Zone und Exfiltration der sensibelsten Daten', 'Intrusión en la zona de confianza y exfiltración de los datos más sensibles', 'Intrusione nella zona di fiducia ed esfiltrazione dei dati più sensibili'),
    [L('Violation de données sensibles', 'Breach of sensitive data', 'Verletzung sensibler Daten', 'Violación de datos sensibles', 'Violazione di dati sensibili'), L('Sanctions et perte de confiance', 'Sanctions and loss of trust', 'Sanktionen und Vertrauensverlust', 'Sanciones y pérdida de confianza', 'Sanzioni e perdita di fiducia')], 4),
  ss(CONF, 'C', L('Un attaquant escalade ses privilèges depuis une zone moins protégée jusqu’à la zone de confiance (C)', 'An attacker escalates privileges from a less protected zone up to the trusted zone (C)', 'Ein Angreifer eskaliert Privilegien aus einer weniger geschützten Zone bis zur vertrauenswürdigen Zone (C)', 'Un atacante escala privilegios desde una zona menos protegida hasta la zona de confianza (C)', 'Un attaccante aumenta i privilegi da una zona meno protetta fino alla zona di fiducia (C)'),
    L('Un compte d’administration réutilisé entre zones donne accès aux données les plus sensibles', 'An administration account reused across zones gives access to the most sensitive data', 'Ein zonenübergreifend wiederverwendetes Administrationskonto verschafft Zugang zu den sensibelsten Daten', 'Una cuenta de administración reutilizada entre zonas da acceso a los datos más sensibles', 'Un account di amministrazione riutilizzato tra zone dà accesso ai dati più sensibili'), 2, 4),
  ms(CONF, L('Accès à la zone de confiance par des postes et comptes dédiés, avec authentification forte', 'Access to the trusted zone from dedicated workstations and accounts, with strong authentication', 'Zugriff auf die vertrauenswürdige Zone von dedizierten Arbeitsplätzen und Konten aus, mit starker Authentifizierung', 'Acceso a la zona de confianza desde puestos y cuentas dedicados, con autenticación fuerte', 'Accesso alla zona di fiducia da postazioni e account dedicati, con autenticazione forte'),
    L('Aucun compte ni poste partagé avec d’autres zones ; accès limité aux personnes nominativement autorisées', 'No account or workstation shared with other zones; access limited to named authorised people', 'Kein Konto und kein Arbeitsplatz mit anderen Zonen geteilt; Zugriff nur für namentlich berechtigte Personen', 'Ninguna cuenta ni puesto compartidos con otras zonas; acceso limitado a personas autorizadas nominalmente', 'Nessun account né postazione condivisi con altre zone; accesso limitato alle persone autorizzate nominativamente'),
    'PREVENTIVE', 'PROTECTION', 1),
  ms(CONF, L('Chiffrement des données sensibles et journalisation des accès à la zone', 'Encryption of sensitive data and logging of access to the zone', 'Verschlüsselung sensibler Daten und Protokollierung der Zugriffe auf die Zone', 'Cifrado de los datos sensibles y registro de los accesos a la zona', 'Cifratura dei dati sensibili e registrazione degli accessi alla zona'),
    L('Conserver et revoir régulièrement les traces d’accès ; chiffrer au repos et en transit', 'Keep and regularly review access logs; encrypt at rest and in transit', 'Zugriffsprotokolle aufbewahren und regelmäßig prüfen; im Ruhezustand und bei der Übertragung verschlüsseln', 'Conservar y revisar periódicamente los registros de acceso; cifrar en reposo y en tránsito', 'Conservare e rivedere regolarmente le tracce di accesso; cifrare a riposo e in transito'),
    'DETECTIVE', 'DEFENSE', 2),

  // ═══ Zone de moindre confiance ═════════════════════════════════════════════════════════════════
  bs(MOINDRE, L('Réseau invités, BYOD et équipements non maîtrisés', 'Guest network, BYOD and unmanaged equipment', 'Gästenetz, BYOD und nicht kontrollierte Geräte', 'Red de invitados, BYOD y equipos no controlados', 'Rete ospiti, BYOD e apparecchiature non controllate'), 'RESEAU',
    L('Connexions de visiteurs, terminaux personnels, laboratoire ou partenaires sur site dont le niveau de sécurité n’est pas garanti', 'Visitor connections, personal devices, laboratory or on-site partners whose security level is not guaranteed', 'Besucherverbindungen, private Geräte, Labor oder Partner vor Ort, deren Sicherheitsniveau nicht gewährleistet ist', 'Conexiones de visitantes, dispositivos personales, laboratorio o socios in situ cuyo nivel de seguridad no está garantizado', 'Connessioni di visitatori, dispositivi personali, laboratorio o partner in sede il cui livello di sicurezza non è garantito')),
  bs(MOINDRE, L('Filtrage et passerelle entre la zone de moindre confiance et le SI', 'Filtering and gateway between the lower-trust zone and the IS', 'Filterung und Gateway zwischen der Zone mit geringerem Vertrauen und dem IS', 'Filtrado y pasarela entre la zona de menor confianza y el SI', 'Filtraggio e gateway tra la zona a minore fiducia e il SI'), 'RESEAU',
    L('Dispositifs qui isolent cette zone et n’autorisent que des flux explicites vers l’extérieur ou le SI', 'Devices that isolate this zone and only allow explicit flows to the outside or the IS', 'Einrichtungen, die diese Zone isolieren und nur ausdrückliche Flüsse nach außen oder ins IS erlauben', 'Dispositivos que aíslan esta zona y solo permiten flujos explícitos hacia el exterior o el SI', 'Dispositivi che isolano questa zona e consentono solo flussi espliciti verso l’esterno o il SI')),
  er(MOINDRE, L('Équipement non maîtrisé infecté qui contamine le réseau interne', 'Infected unmanaged device contaminating the internal network', 'Infiziertes, nicht kontrolliertes Gerät, das das interne Netz verseucht', 'Equipo no controlado infectado que contamina la red interna', 'Dispositivo non controllato infetto che contamina la rete interna'),
    [L('Propagation de logiciels malveillants', 'Spread of malware', 'Ausbreitung von Schadsoftware', 'Propagación de software malicioso', 'Propagazione di software malevolo'), L('Interruption de l’activité', 'Interruption of activity', 'Unterbrechung der Tätigkeit', 'Interrupción de la actividad', 'Interruzione dell’attività')], 3),
  ss(MOINDRE, 'I', L('Un appareil d’un visiteur ou d’un partenaire sert de point d’entrée vers des ressources internes mal cloisonnées (I)', 'A visitor’s or partner’s device is used as an entry point to poorly segregated internal resources (I)', 'Ein Gerät eines Besuchers oder Partners dient als Einstiegspunkt zu schlecht getrennten internen Ressourcen (I)', 'Un dispositivo de un visitante o socio sirve de punto de entrada a recursos internos mal segregados (I)', 'Un dispositivo di un visitatore o partner funge da punto di ingresso verso risorse interne poco segregate (I)'),
    L('L’absence de séparation permet de scanner et d’atteindre des serveurs ou imprimantes du réseau interne', 'The lack of separation allows scanning and reaching servers or printers on the internal network', 'Fehlende Trennung erlaubt das Scannen und Erreichen von Servern oder Druckern im internen Netz', 'La falta de separación permite escanear y alcanzar servidores o impresoras de la red interna', 'L’assenza di separazione consente di scansionare e raggiungere server o stampanti della rete interna'), 3, 3),
  ae(MOINDRE, 'MOUVEMENT_LATERAL', 'T1046', L('Balayage du réseau interne depuis la zone invités ou un appareil non maîtrisé', 'Scanning of the internal network from the guest zone or an unmanaged device', 'Scan des internen Netzes aus der Gästezone oder von einem nicht kontrollierten Gerät', 'Escaneo de la red interna desde la zona de invitados o un equipo no controlado', 'Scansione della rete interna dalla zona ospiti o da un dispositivo non controllato'),
    L('Découverte de services internes accessibles faute de cloisonnement', 'Discovery of internal services reachable for lack of segregation', 'Entdeckung interner Dienste, die mangels Trennung erreichbar sind', 'Descubrimiento de servicios internos accesibles por falta de segregación', 'Scoperta di servizi interni raggiungibili per mancanza di segregazione')),
  ms(MOINDRE, L('Cloisonnement strict des réseaux invités et BYOD, sans accès aux ressources internes', 'Strict segregation of guest and BYOD networks, with no access to internal resources', 'Strikte Trennung von Gäste- und BYOD-Netzen ohne Zugriff auf interne Ressourcen', 'Segregación estricta de las redes de invitados y BYOD, sin acceso a recursos internos', 'Segregazione rigorosa delle reti ospiti e BYOD, senza accesso alle risorse interne'),
    L('Réseaux distincts, accès Internet seul, authentification des appareils et durée de session limitée', 'Separate networks, Internet-only access, device authentication and limited session time', 'Getrennte Netze, nur Internetzugang, Geräteauthentifizierung und begrenzte Sitzungsdauer', 'Redes distintas, solo acceso a Internet, autenticación de dispositivos y duración de sesión limitada', 'Reti distinte, solo accesso a Internet, autenticazione dei dispositivi e durata di sessione limitata'),
    'PREVENTIVE', 'PROTECTION', 1),
  ms(MOINDRE, L('Contrôle de conformité des appareils avant toute connexion au SI (antivirus, correctifs, chiffrement)', 'Device compliance check before any connection to the IS (antivirus, patches, encryption)', 'Konformitätsprüfung der Geräte vor jeder Verbindung mit dem IS (Virenschutz, Patches, Verschlüsselung)', 'Control de conformidad de los dispositivos antes de cualquier conexión al SI (antivirus, parches, cifrado)', 'Controllo di conformità dei dispositivi prima di qualsiasi connessione al SI (antivirus, aggiornamenti, cifratura)'),
    L('Ne donner accès qu’aux appareils conformes ; refuser ou isoler les autres', 'Only give access to compliant devices; refuse or isolate the others', 'Nur konformen Geräten Zugriff gewähren; andere ablehnen oder isolieren', 'Dar acceso solo a los dispositivos conformes; rechazar o aislar los demás', 'Dare accesso solo ai dispositivi conformi; rifiutare o isolare gli altri'),
    'TECHNIQUE', 'PROTECTION', 2),

  // ═══ Accès distant des utilisateurs ════════════════════════════════════════════════════════════
  bs(DISTANT, L('Passerelle d’accès distant (VPN, accès « zero trust », bureau virtuel)', 'Remote access gateway (VPN, zero-trust access, virtual desktop)', 'Fernzugriffs-Gateway (VPN, Zero-Trust-Zugang, virtueller Desktop)', 'Pasarela de acceso remoto (VPN, acceso «zero trust», escritorio virtual)', 'Gateway di accesso remoto (VPN, accesso «zero trust», desktop virtuale)'), 'LOGICIEL',
    L('Service qui ouvre le SI aux utilisateurs en télétravail ou en déplacement, exposé sur Internet par nature', 'Service opening the IS to teleworking or travelling users, exposed to the Internet by nature', 'Dienst, der das IS für Telearbeitende oder Reisende öffnet und naturgemäß im Internet exponiert ist', 'Servicio que abre el SI a los usuarios en teletrabajo o desplazamiento, expuesto a Internet por naturaleza', 'Servizio che apre il SI agli utenti in telelavoro o in trasferta, esposto a Internet per natura')),
  bs(DISTANT, L('Postes nomades et domicile des télétravailleurs', 'Mobile workstations and teleworkers’ home environment', 'Mobile Arbeitsplätze und häusliches Umfeld der Telearbeitenden', 'Puestos móviles y entorno doméstico de los teletrabajadores', 'Postazioni mobili e ambiente domestico dei telelavoratori'), 'MATERIEL',
    L('Ordinateurs hors des locaux, connectés à des réseaux domestiques ou publics non maîtrisés', 'Computers outside the premises, connected to uncontrolled home or public networks', 'Computer außerhalb der Räumlichkeiten, verbunden mit nicht kontrollierten Heim- oder öffentlichen Netzen', 'Ordenadores fuera de los locales, conectados a redes domésticas o públicas no controladas', 'Computer fuori sede, collegati a reti domestiche o pubbliche non controllate')),
  er(DISTANT, L('Accès frauduleux au SI par un compte distant compromis', 'Fraudulent access to the IS through a compromised remote account', 'Betrügerischer Zugriff auf das IS über ein kompromittiertes Fernzugriffskonto', 'Acceso fraudulento al SI mediante una cuenta remota comprometida', 'Accesso fraudolento al SI tramite un account remoto compromesso'),
    [L('Intrusion dans le SI', 'Intrusion into the IS', 'Eindringen in das IS', 'Intrusión en el SI', 'Intrusione nel SI'), L('Vol de données', 'Data theft', 'Datendiebstahl', 'Robo de datos', 'Furto di dati')], 4),
  sr(DISTANT, L('Cybercriminel ciblant les accès distants (identifiants volés, hameçonnage)', 'Cybercriminal targeting remote access (stolen credentials, phishing)', 'Cyberkrimineller, der Fernzugriffe angreift (gestohlene Zugangsdaten, Phishing)', 'Cibercriminal que ataca los accesos remotos (credenciales robadas, phishing)', 'Cybercriminale che prende di mira gli accessi remoti (credenziali rubate, phishing)'), 'CYBERCRIMINEL',
    L('Acteur qui achète ou vole des identifiants de VPN et de messagerie pour entrer sans effraction', 'Actor buying or stealing VPN and mail credentials to get in without breaking in', 'Akteur, der VPN- und Mail-Zugangsdaten kauft oder stiehlt, um ohne Einbruch einzudringen', 'Actor que compra o roba credenciales de VPN y correo para entrar sin forzar nada', 'Attore che acquista o ruba credenziali VPN e di posta per entrare senza effrazione'),
    L('Gain financier, rançongiciel', 'Financial gain, ransomware', 'Finanzieller Gewinn, Ransomware', 'Beneficio económico, ransomware', 'Guadagno economico, ransomware'),
    L('Marchés d’identifiants, kits de hameçonnage, outils de contournement du second facteur', 'Credential marketplaces, phishing kits, second-factor bypass tools', 'Zugangsdaten-Marktplätze, Phishing-Kits, Werkzeuge zur Umgehung des zweiten Faktors', 'Mercados de credenciales, kits de phishing, herramientas de elusión del segundo factor', 'Mercati di credenziali, kit di phishing, strumenti di aggiramento del secondo fattore'), 4),
  ss(DISTANT, 'C', L('Un attaquant se connecte par l’accès distant avec des identifiants volés et exfiltre des données (C)', 'An attacker signs in through remote access with stolen credentials and exfiltrates data (C)', 'Ein Angreifer meldet sich mit gestohlenen Zugangsdaten per Fernzugriff an und exfiltriert Daten (C)', 'Un atacante se conecta por el acceso remoto con credenciales robadas y exfiltra datos (C)', 'Un attaccante si connette dall’accesso remoto con credenziali rubate ed esfiltra dati (C)'),
    L('Absence de second facteur ou second facteur contourné sur l’accès distant', 'No second factor or bypassed second factor on remote access', 'Kein zweiter Faktor oder umgangener zweiter Faktor beim Fernzugriff', 'Falta de segundo factor o segundo factor eludido en el acceso remoto', 'Assenza di secondo fattore o secondo fattore aggirato sull’accesso remoto'), 3, 4),
  ae(DISTANT, 'ACCES_INITIAL', 'T1133', L('Utilisation d’un service d’accès distant exposé avec des identifiants valides volés', 'Use of an exposed remote service with stolen valid credentials', 'Nutzung eines exponierten Fernzugriffsdienstes mit gestohlenen gültigen Zugangsdaten', 'Uso de un servicio de acceso remoto expuesto con credenciales válidas robadas', 'Uso di un servizio di accesso remoto esposto con credenziali valide rubate'),
    L('Connexion depuis l’extérieur qui ressemble à un usage légitime et passe inaperçue', 'Connection from outside that looks like legitimate use and goes unnoticed', 'Verbindung von außen, die legitimer Nutzung ähnelt und unbemerkt bleibt', 'Conexión desde el exterior que parece un uso legítimo y pasa inadvertida', 'Connessione dall’esterno che sembra un uso legittimo e passa inosservata')),
  ms(DISTANT, L('Authentification multifacteur obligatoire sur tout accès distant', 'Mandatory multi-factor authentication on all remote access', 'Verpflichtende Mehrfaktor-Authentifizierung für jeden Fernzugriff', 'Autenticación multifactor obligatoria en todo acceso remoto', 'Autenticazione multifattore obbligatoria su ogni accesso remoto'),
    L('Second facteur résistant à l’hameçonnage pour les comptes à privilèges ; fin des mots de passe seuls', 'Phishing-resistant second factor for privileged accounts; no more password-only access', 'Phishing-resistenter zweiter Faktor für privilegierte Konten; keine reinen Passwortanmeldungen mehr', 'Segundo factor resistente al phishing para las cuentas con privilegios; fin de los accesos solo con contraseña', 'Secondo fattore resistente al phishing per gli account privilegiati; fine degli accessi con sola password'),
    'TECHNIQUE', 'PROTECTION', 1),
  ms(DISTANT, L('Postes distants gérés (chiffrement, correctifs, antivirus) et accès limité aux ressources nécessaires', 'Managed remote workstations (encryption, patches, antivirus) and access limited to needed resources', 'Verwaltete Fernarbeitsplätze (Verschlüsselung, Patches, Virenschutz) und auf nötige Ressourcen beschränkter Zugriff', 'Puestos remotos gestionados (cifrado, parches, antivirus) y acceso limitado a los recursos necesarios', 'Postazioni remote gestite (cifratura, aggiornamenti, antivirus) e accesso limitato alle risorse necessarie'),
    L('Politique de poste vérifiée à la connexion ; droits au moindre privilège ; surveillance des connexions inhabituelles', 'Workstation policy checked at connection; least-privilege rights; monitoring of unusual connections', 'Arbeitsplatzrichtlinie bei der Verbindung geprüft; Rechte nach dem Minimalprinzip; Überwachung ungewöhnlicher Verbindungen', 'Política de puesto verificada en la conexión; derechos de mínimo privilegio; vigilancia de conexiones inusuales', 'Policy della postazione verificata alla connessione; diritti di minimo privilegio; monitoraggio delle connessioni insolite'),
    'TECHNIQUE', 'DEFENSE', 2),
  me(DISTANT, L('Exigences de sécurité du télétravail et de l’accès distant dans les contrats avec les prestataires', 'Telework and remote-access security requirements in contracts with providers', 'Sicherheitsanforderungen für Telearbeit und Fernzugriff in Verträgen mit Dienstleistern', 'Requisitos de seguridad del teletrabajo y del acceso remoto en los contratos con proveedores', 'Requisiti di sicurezza del telelavoro e dell’accesso remoto nei contratti con i fornitori'), 'ORGANISATIONNELLE', '5.19',
    L('Les prestataires qui se connectent à distance appliquent les mêmes règles d’authentification et de traçabilité', 'Providers connecting remotely apply the same authentication and traceability rules', 'Dienstleister, die sich aus der Ferne verbinden, wenden dieselben Authentifizierungs- und Nachvollziehbarkeitsregeln an', 'Los proveedores que se conectan a distancia aplican las mismas reglas de autenticación y trazabilidad', 'I fornitori che si connettono da remoto applicano le stesse regole di autenticazione e tracciabilità')),
]
