// ─── Incidents types propres à un secteur (catalogue 1.10) — à sélectionner, rechercher et compléter (PUR) ───────────────
// Complète le catalogue générique (`incident-types-catalogue.ts`) par des événements caractéristiques d'un métier : ils
// préremplissent l'intitulé, le type d'événement et la liste « à compléter » ; ils ne décrivent JAMAIS un fait (aucune date,
// aucun chiffre, aucune gravité). Le caractère significatif et les déclarations aux autorités restent des décisions de l'entité.
// Contenu à relire par un expert du secteur (cf. catalogue-review-status).
import type { CauseRacineType, IncidentCategorie, IncidentType } from './incident-types-catalogue'

type Localized = Record<'fr' | 'en' | 'de' | 'es' | 'it', string>
const l = (fr: string, en: string, de: string, es: string, it: string): Localized => ({ fr, en, de, es, it })

const s = (sector: string, slug: string, categorie: IncidentCategorie, title: Localized, aliases: string[],
  o: { tic?: boolean; donnees?: boolean; cause: CauseRacineType; aCompleter: string[]; regimes?: string[]; its?: string }): IncidentType =>
  ({ key: `${sector.toLowerCase()}.${slug}`, sector, categorie, title, aliases, tic: o.tic ?? false, donnees: o.donnees ?? false, causeRacine: o.cause, aCompleter: o.aCompleter, regimes: o.regimes ?? [], ...(o.tic && o.its ? { itsType: [o.its] } : {}) })

export const SECTOR_INCIDENT_TYPES: IncidentType[] = [
  // ── Administration publique ──
  s('PUBLIC', 'service-outage', 'CONTINUITE', l('Indisponibilité d’un téléservice ou d’un service aux usagers', 'Unavailability of an e-service or a citizen service', 'Ausfall eines E-Service oder Bürgerdienstes', 'Indisponibilidad de un servicio electrónico o de un servicio a los usuarios', 'Indisponibilità di un servizio digitale o di un servizio ai cittadini'), ['teleservice', 'portail usagers', 'etat civil', 'service public', 'guichet'], { tic: true, cause: 'SYSTEMES', aCompleter: ['systemes', 'debut_fin', 'clients', 'mesures'], its: 'System failure' }),
  s('PUBLIC', 'case-data-leak', 'DONNEES_PERSONNELLES', l('Divulgation de dossiers d’usagers ou de données d’administrés', 'Disclosure of citizens’ case files or constituents’ data', 'Offenlegung von Bürgerakten oder Daten Verwaltungskunden', 'Divulgación de expedientes de usuarios o datos de administrados', 'Divulgazione di fascicoli dei cittadini o di dati degli amministrati'), ['dossier usager', 'donnees administres', 'fuite mairie', 'rgpd collectivite'], { donnees: true, cause: 'PERSONNES', aCompleter: ['donnees', 'personnes', 'mesures', 'autorites', 'preuves'], regimes: ['RGPD_33'] }),
  s('PUBLIC', 'procurement-irregularity', 'AUTRE', l('Irrégularité dans une procédure de commande publique ou une subvention', 'Irregularity in a public procurement procedure or grant', 'Unregelmäßigkeit in einem Vergabeverfahren oder bei einem Zuschuss', 'Irregularidad en un procedimiento de contratación pública o subvención', 'Irregolarità in una procedura di appalto pubblico o in una sovvenzione'), ['marche public', 'attribution', 'subvention', 'conflit d interets', 'favoritisme'], { cause: 'PROCESSUS', aCompleter: ['mesures', 'pertes', 'autorites', 'preuves'], regimes: ['INTERNE'] }),
  // ── Banque / Finance ──
  s('FINANCE', 'instant-payment-fraud', 'FRAUDE', l('Fraude sur virement instantané ou détournement de paiement', 'Instant-payment fraud or payment diversion', 'Betrug bei Sofortüberweisung oder Zahlungsumleitung', 'Fraude en transferencia instantánea o desvío de pago', 'Frode su bonifico istantaneo o dirottamento di pagamento'), ['virement instantane', 'sct inst', 'detournement paiement', 'fraude virement', 'rappel de fonds'], { tic: true, cause: 'EXTERNE', aCompleter: ['pertes', 'clients', 'vecteur', 'mesures', 'autorites', 'preuves'], its: 'Payment-related' }),
  s('FINANCE', 'sanctions-breach', 'AUTRE', l('Opération réalisée avec une contrepartie sous sanctions ou gel des avoirs non appliqué', 'Transaction with a sanctioned counterparty or an asset freeze not applied', 'Transaktion mit sanktionierter Gegenpartei oder nicht angewandtes Einfrieren von Vermögenswerten', 'Operación con una contraparte sancionada o congelación de activos no aplicada', 'Operazione con una controparte sanzionata o congelamento dei beni non applicato'), ['sanctions', 'gel des avoirs', 'filtrage', 'contrepartie sanctionnee', 'ofac', 'embargo'], { cause: 'PROCESSUS', aCompleter: ['clients', 'pertes', 'autorites', 'preuves', 'mesures'], regimes: ['INTERNE'] }),
  s('FINANCE', 'reporting-error', 'PROCESSUS', l('Erreur dans un état réglementaire ou comptable transmis', 'Error in a regulatory or accounting return submitted', 'Fehler in einer eingereichten aufsichtlichen oder buchhalterischen Meldung', 'Error en un estado reglamentario o contable remitido', 'Errore in un prospetto regolamentare o contabile trasmesso'), ['etat reglementaire', 'remise', 'reporting', 'erreur comptable', 'declaration erronee'], { cause: 'PROCESSUS', aCompleter: ['systemes', 'mesures', 'autorites', 'pertes'] }),
  // ── Assurance / Mutuelle ──
  s('ASSURANCE', 'claims-payment-error', 'PROCESSUS', l('Indemnisation versée à tort, en double ou à un mauvais bénéficiaire', 'Claim paid wrongly, twice or to the wrong beneficiary', 'Schadenzahlung zu Unrecht, doppelt oder an den falschen Begünstigten', 'Indemnización abonada indebidamente, por duplicado o a un beneficiario equivocado', 'Indennizzo pagato per errore, due volte o a un beneficiario sbagliato'), ['indemnisation', 'sinistre', 'double paiement', 'mauvais beneficiaire', 'prestation'], { cause: 'PROCESSUS', aCompleter: ['clients', 'pertes', 'mesures', 'preuves'] }),
  s('ASSURANCE', 'policyholder-data-leak', 'DONNEES_PERSONNELLES', l('Divulgation de données de santé ou financières d’assurés ou d’adhérents', 'Disclosure of policyholders’ or members’ health or financial data', 'Offenlegung von Gesundheits- oder Finanzdaten von Versicherten oder Mitgliedern', 'Divulgación de datos de salud o financieros de asegurados o socios', 'Divulgazione di dati sanitari o finanziari di assicurati o soci'), ['donnees de sante', 'assures', 'adherents', 'fuite assurance', 'mutuelle', 'rgpd'], { tic: true, donnees: true, cause: 'PERSONNES', aCompleter: ['donnees', 'personnes', 'vecteur', 'mesures', 'autorites', 'preuves'], regimes: ['RGPD_33', 'NIS2'], its: 'Cybersecurity-related' }),
  s('ASSURANCE', 'claims-fraud-ring', 'FRAUDE', l('Réseau organisé de fausses déclarations de sinistre détecté', 'Organised ring of false claims detected', 'Organisiertes Netzwerk falscher Schadenmeldungen entdeckt', 'Red organizada de falsas declaraciones de siniestro detectada', 'Rete organizzata di false denunce di sinistro individuata'), ['fraude sinistre', 'fausse declaration', 'reseau', 'fraude organisee', 'expertise'], { cause: 'EXTERNE', aCompleter: ['clients', 'pertes', 'mesures', 'autorites', 'preuves'] }),
  // ── Défense / Sécurité nationale ──
  s('DEFENSE', 'classified-media-loss', 'SECURITE_PHYSIQUE', l('Perte, vol ou divulgation d’un support ou d’une information classifiée', 'Loss, theft or disclosure of a classified medium or information', 'Verlust, Diebstahl oder Offenlegung eines Verschlusssachen-Datenträgers oder einer Verschlusssache', 'Pérdida, robo o divulgación de un soporte o información clasificada', 'Perdita, furto o divulgazione di un supporto o di un’informazione classificata'), ['support classifie', 'secret defense', 'igi 1300', 'perte support', 'compromission', 'confidentiel defense'], { donnees: false, cause: 'PERSONNES', aCompleter: ['donnees', 'personnes', 'mesures', 'autorites', 'preuves'], regimes: ['INTERNE'] }),
  s('DEFENSE', 'targeted-intrusion', 'CYBER', l('Intrusion ciblée visant des données de conception ou des programmes', 'Targeted intrusion aimed at design data or programmes', 'Gezielter Angriff auf Konstruktionsdaten oder Programme', 'Intrusión selectiva dirigida a datos de diseño o programas', 'Intrusione mirata a dati di progetto o programmi'), ['apt', 'espionnage', 'attaque etatique', 'exfiltration conception', 'intrusion ciblee'], { tic: true, donnees: true, cause: 'EXTERNE', aCompleter: ['systemes', 'vecteur', 'indicateurs', 'donnees', 'mesures', 'autorites', 'preuves'], regimes: ['NIS2', 'INTERNE'], its: 'Cybersecurity-related' }),
  s('DEFENSE', 'unauthorised-export', 'AUTRE', l('Exportation ou transfert d’un bien ou d’une technologie sans autorisation', 'Export or transfer of a good or technology without authorisation', 'Ausfuhr oder Transfer eines Guts oder einer Technologie ohne Genehmigung', 'Exportación o transferencia de un bien o tecnología sin autorización', 'Esportazione o trasferimento di un bene o di una tecnologia senza autorizzazione'), ['export', 'double usage', 'licence', 'transfert technologie', 'douane'], { cause: 'PROCESSUS', aCompleter: ['mesures', 'autorites', 'preuves', 'pertes'], regimes: ['INTERNE'] }),
  // ── Éducation / Recherche ──
  s('EDUCATION', 'exam-leak', 'AUTRE', l('Divulgation d’un sujet d’examen ou fraude massive à une épreuve', 'Leak of an exam paper or mass cheating', 'Offenlegung einer Prüfungsaufgabe oder massenhafter Täuschungsversuch', 'Filtración de un examen o fraude masivo en una prueba', 'Divulgazione di un testo d’esame o frode di massa in una prova'), ['sujet d examen', 'fraude examen', 'triche', 'epreuve', 'concours'], { cause: 'PERSONNES', aCompleter: ['personnes', 'mesures', 'autorites', 'preuves'], regimes: ['INTERNE'] }),
  s('EDUCATION', 'campus-ransomware', 'CYBER', l('Rançongiciel ou intrusion paralysant l’environnement numérique, la scolarité ou la recherche', 'Ransomware or intrusion paralysing the learning environment, student registry or research', 'Ransomware oder Angriff legt Lernumgebung, Studierendenverwaltung oder Forschung lahm', 'Ransomware o intrusión que paraliza el entorno digital, la secretaría o la investigación', 'Ransomware o intrusione che paralizza l’ambiente digitale, la segreteria o la ricerca'), ['universite', 'ent', 'rancongiciel campus', 'etablissement', 'scolarite'], { tic: true, donnees: true, cause: 'EXTERNE', aCompleter: ['systemes', 'vecteur', 'indicateurs', 'donnees', 'mesures', 'autorites'], regimes: ['NIS2', 'RGPD_33'], its: 'Cybersecurity-related' }),
  s('EDUCATION', 'student-data-leak', 'DONNEES_PERSONNELLES', l('Divulgation de données d’étudiants, d’élèves ou de mineurs', 'Disclosure of student, pupil or minors’ data', 'Offenlegung von Daten von Studierenden, Schülern oder Minderjährigen', 'Divulgación de datos de estudiantes, alumnos o menores', 'Divulgazione di dati di studenti, alunni o minori'), ['donnees etudiants', 'eleves', 'mineurs', 'notes', 'dossier scolaire'], { donnees: true, cause: 'PERSONNES', aCompleter: ['donnees', 'personnes', 'mesures', 'autorites', 'preuves'], regimes: ['RGPD_33'] }),
  // ── Énergie / Utilities ──
  s('ENERGIE', 'supply-interruption', 'CONTINUITE', l('Interruption de la fourniture ou de la distribution à des clients', 'Interruption of supply or distribution to customers', 'Unterbrechung der Versorgung oder Verteilung an Kunden', 'Interrupción del suministro o distribución a clientes', 'Interruzione della fornitura o della distribuzione ai clienti'), ['coupure', 'panne reseau', 'black out', 'distribution', 'delestage', 'interruption alimentation'], { tic: true, cause: 'SYSTEMES', aCompleter: ['systemes', 'debut_fin', 'clients', 'mesures', 'autorites'], regimes: ['NIS2'], its: 'System failure' }),
  s('ENERGIE', 'ot-intrusion', 'CYBER', l('Intrusion ou perturbation d’un système de conduite industriel (SCADA)', 'Intrusion into or disruption of an industrial control system (SCADA)', 'Eindringen in oder Störung eines industriellen Leitsystems (SCADA)', 'Intrusión o perturbación de un sistema de control industrial (SCADA)', 'Intrusione o perturbazione di un sistema di controllo industriale (SCADA)'), ['scada', 'ot', 'systeme de conduite', 'automate', 'poste electrique', 'ics'], { tic: true, cause: 'EXTERNE', aCompleter: ['systemes', 'vecteur', 'indicateurs', 'mesures', 'autorites', 'preuves'], regimes: ['NIS2'], its: 'Cybersecurity-related' }),
  s('ENERGIE', 'field-accident', 'SECURITE_PHYSIQUE', l('Accident ou incident de sécurité lors d’une intervention sur ouvrage', 'Accident or safety incident during work on equipment', 'Unfall oder Sicherheitsvorfall bei Arbeiten an Anlagen', 'Accidente o incidente de seguridad durante una intervención en instalaciones', 'Incidente o infortunio di sicurezza durante un intervento sugli impianti'), ['accident du travail', 'consignation', 'electrisation', 'intervention terrain', 'ouvrage'], { cause: 'PROCESSUS', aCompleter: ['personnes', 'mesures', 'autorites', 'preuves'] }),
  // ── Industrie ──
  s('INDUSTRIE', 'production-stop', 'CONTINUITE', l('Arrêt de production ou d’une ligne suite à un incident informatique ou de commande', 'Production or line stoppage following an IT or control incident', 'Produktions- oder Linienstillstand nach IT- oder Steuerungsvorfall', 'Parada de producción o de una línea tras un incidente informático o de control', 'Fermo della produzione o di una linea a seguito di un incidente informatico o di controllo'), ['arret production', 'ligne', 'automate', 'ot', 'atelier', 'usine', 'arret ligne'], { tic: true, cause: 'SYSTEMES', aCompleter: ['systemes', 'debut_fin', 'clients', 'mesures', 'pertes'], regimes: ['NIS2'], its: 'System failure' }),
  s('INDUSTRIE', 'product-recall', 'PROCESSUS', l('Défaut de produit livré imposant un rappel ou un retrait', 'Defect in delivered product requiring a recall or withdrawal', 'Mangel an ausgeliefertem Produkt erfordert Rückruf oder Rücknahme', 'Defecto en producto entregado que exige una retirada', 'Difetto in un prodotto consegnato che impone un richiamo o un ritiro'), ['rappel produit', 'non conformite', 'defaut qualite', 'retrait', 'lot defectueux'], { cause: 'PROCESSUS', aCompleter: ['clients', 'mesures', 'pertes', 'autorites', 'preuves'] }),
  s('INDUSTRIE', 'industrial-accident', 'SECURITE_PHYSIQUE', l('Accident industriel (incendie, explosion, rejet, accident du travail grave)', 'Industrial accident (fire, explosion, release, serious workplace accident)', 'Industrieunfall (Brand, Explosion, Freisetzung, schwerer Arbeitsunfall)', 'Accidente industrial (incendio, explosión, vertido, accidente laboral grave)', 'Incidente industriale (incendio, esplosione, sversamento, grave infortunio sul lavoro)'), ['accident industriel', 'incendie usine', 'explosion', 'rejet', 'seveso', 'accident du travail'], { cause: 'PROCESSUS', aCompleter: ['personnes', 'debut_fin', 'mesures', 'autorites', 'pertes', 'preuves'] }),
  // ── Informatique / Numérique ──
  s('SAAS', 'service-outage', 'CONTINUITE', l('Indisponibilité du service ou d’une région d’hébergement pour des clients', 'Service or hosting-region outage affecting customers', 'Ausfall des Dienstes oder einer Hosting-Region mit Kundenauswirkungen', 'Caída del servicio o de una región de alojamiento con impacto en clientes', 'Indisponibilità del servizio o di una regione di hosting con impatto sui clienti'), ['panne saas', 'incident de service', 'sla', 'region cloud', 'indisponibilite plateforme'], { tic: true, cause: 'SYSTEMES', aCompleter: ['systemes', 'debut_fin', 'clients', 'prestataire', 'mesures'], regimes: ['NIS2'], its: 'System failure' }),
  s('SAAS', 'tenant-breach', 'DONNEES_PERSONNELLES', l('Accès aux données d’un client par un autre client ou par un tiers (rupture d’isolation)', 'Access to one customer’s data by another customer or a third party (isolation failure)', 'Zugriff auf Kundendaten durch einen anderen Kunden oder Dritte (Isolationsfehler)', 'Acceso a los datos de un cliente por otro cliente o un tercero (fallo de aislamiento)', 'Accesso ai dati di un cliente da parte di un altro cliente o di un terzo (rottura dell’isolamento)'), ['isolation', 'multi tenant', 'fuite inter clients', 'idor', 'donnees clients'], { tic: true, donnees: true, cause: 'SYSTEMES', aCompleter: ['systemes', 'donnees', 'clients', 'vecteur', 'mesures', 'autorites'], regimes: ['RGPD_33', 'NIS2'], its: 'Cybersecurity-related' }),
  s('SAAS', 'secrets-exposed', 'CYBER', l('Secrets, clés d’API ou jetons exposés (dépôt de code, journaux, configuration)', 'Secrets, API keys or tokens exposed (code repository, logs, configuration)', 'Geheimnisse, API-Schlüssel oder Token offengelegt (Code-Repository, Logs, Konfiguration)', 'Secretos, claves de API o tokens expuestos (repositorio de código, registros, configuración)', 'Segreti, chiavi API o token esposti (repository di codice, log, configurazione)'), ['cle api', 'secret', 'token', 'github', 'depot', 'credentials exposes'], { tic: true, cause: 'PROCESSUS', aCompleter: ['systemes', 'vecteur', 'indicateurs', 'mesures', 'clients'], its: 'Cybersecurity-related' }),
  // ── Santé / Médico-social ──
  s('SANTE', 'patient-data-breach', 'DONNEES_PERSONNELLES', l('Divulgation ou accès indu à des données de santé de patients', 'Disclosure of or undue access to patients’ health data', 'Offenlegung oder unbefugter Zugriff auf Patientengesundheitsdaten', 'Divulgación o acceso indebido a datos de salud de pacientes', 'Divulgazione o accesso indebito a dati sanitari dei pazienti'), ['donnees de sante', 'dossier patient', 'acces indu', 'secret medical', 'hds', 'violation de donnees'], { tic: true, donnees: true, cause: 'PERSONNES', aCompleter: ['donnees', 'personnes', 'mesures', 'autorites', 'preuves'], regimes: ['RGPD_33', 'NIS2'], its: 'Cybersecurity-related' }),
  s('SANTE', 'care-system-outage', 'CONTINUITE', l('Indisponibilité du dossier patient ou d’une application de soins (mode dégradé)', 'Unavailability of the patient record or a care application (degraded mode)', 'Ausfall der Patientenakte oder einer Versorgungsanwendung (Notbetrieb)', 'Indisponibilidad de la historia clínica o de una aplicación asistencial (modo degradado)', 'Indisponibilità della cartella clinica o di un’applicazione di cura (modalità degradata)'), ['dossier patient', 'mode degrade', 'panne hopital', 'urgences', 'imagerie', 'prescription'], { tic: true, cause: 'SYSTEMES', aCompleter: ['systemes', 'debut_fin', 'personnes', 'mesures', 'autorites'], regimes: ['NIS2'], its: 'System failure' }),
  s('SANTE', 'medical-event', 'PROCESSUS', l('Événement indésirable lié à l’identification d’un patient, à un médicament ou à un dispositif', 'Adverse event linked to patient identification, a medicine or a device', 'Unerwünschtes Ereignis im Zusammenhang mit Patientenidentifikation, Arzneimittel oder Gerät', 'Evento adverso vinculado a la identificación del paciente, un medicamento o un dispositivo', 'Evento avverso legato all’identificazione del paziente, a un farmaco o a un dispositivo'), ['evenement indesirable', 'erreur medicamenteuse', 'identitovigilance', 'dispositif medical', 'materiovigilance'], { cause: 'PROCESSUS', aCompleter: ['personnes', 'mesures', 'autorites', 'preuves'] }),
  // ── Télécommunications ──
  s('TELECOM', 'major-network-outage', 'CONTINUITE', l('Panne majeure du réseau ou d’un service (voix, données, appels d’urgence)', 'Major network or service outage (voice, data, emergency calls)', 'Schwere Netz- oder Dienststörung (Sprache, Daten, Notrufe)', 'Caída mayor de la red o de un servicio (voz, datos, llamadas de emergencia)', 'Guasto maggiore della rete o di un servizio (voce, dati, chiamate di emergenza)'), ['panne reseau', 'coupure mobile', 'appels urgence', 'fibre', 'coeur de reseau', 'indisponibilite'], { tic: true, cause: 'SYSTEMES', aCompleter: ['systemes', 'debut_fin', 'clients', 'mesures', 'autorites'], regimes: ['NIS2'], its: 'System failure' }),
  s('TELECOM', 'sim-swap-wave', 'FRAUDE', l('Vague de remplacements de SIM ou de portabilités frauduleux', 'Wave of fraudulent SIM replacements or number ports', 'Welle betrügerischer SIM-Ersetzungen oder Rufnummernmitnahmen', 'Oleada de sustituciones de SIM o portabilidades fraudulentas', 'Ondata di sostituzioni SIM o portabilità fraudolente'), ['sim swap', 'portabilite', 'usurpation de ligne', 'fraude sim', 'detournement ligne'], { tic: true, donnees: true, cause: 'EXTERNE', aCompleter: ['clients', 'vecteur', 'mesures', 'autorites', 'preuves'], regimes: ['RGPD_33'], its: 'Cybersecurity-related' }),
  s('TELECOM', 'signalling-abuse', 'CYBER', l('Abus de signalisation (interception, localisation d’abonnés) ou compromission du cœur de réseau', 'Signalling abuse (interception, subscriber location) or core-network compromise', 'Signalisierungsmissbrauch (Abhören, Teilnehmerortung) oder Kernnetz-Kompromittierung', 'Abuso de señalización (interceptación, localización de abonados) o compromiso del núcleo de red', 'Abuso della segnalazione (intercettazione, localizzazione degli abbonati) o compromissione del core network'), ['ss7', 'diameter', 'signalisation', 'interception', 'localisation abonne', 'coeur de reseau'], { tic: true, donnees: true, cause: 'EXTERNE', aCompleter: ['systemes', 'vecteur', 'indicateurs', 'clients', 'mesures', 'autorites'], regimes: ['NIS2', 'RGPD_33'], its: 'Cybersecurity-related' }),
  // ── Transports / Logistique ──
  s('TRANSPORT', 'road-accident', 'SECURITE_PHYSIQUE', l('Accident de la route impliquant un véhicule, un conducteur ou une marchandise de l’entreprise', 'Road accident involving a company vehicle, driver or cargo', 'Verkehrsunfall mit Firmenfahrzeug, Fahrer oder Ladung', 'Accidente de carretera con un vehículo, conductor o mercancía de la empresa', 'Incidente stradale che coinvolge un veicolo, un conducente o un carico dell’azienda'), ['accident routier', 'collision', 'vehicule', 'conducteur', 'sinistre flotte'], { cause: 'PERSONNES', aCompleter: ['personnes', 'debut_fin', 'mesures', 'autorites', 'pertes', 'preuves'] }),
  s('TRANSPORT', 'cargo-theft', 'SECURITE_PHYSIQUE', l('Vol ou détournement d’une cargaison ou d’un véhicule', 'Theft or diversion of a shipment or vehicle', 'Diebstahl oder Umleitung einer Ladung oder eines Fahrzeugs', 'Robo o desvío de una carga o de un vehículo', 'Furto o dirottamento di un carico o di un veicolo'), ['vol cargaison', 'detournement', 'camion vole', 'marchandise volee', 'piratage fret'], { cause: 'EXTERNE', aCompleter: ['clients', 'debut_fin', 'mesures', 'pertes', 'autorites', 'preuves'] }),
  s('TRANSPORT', 'planning-system-outage', 'CONTINUITE', l('Panne du système de planification ou de gestion des transports', 'Planning or transport-management system outage', 'Ausfall des Planungs- oder Transportmanagementsystems', 'Caída del sistema de planificación o gestión del transporte', 'Guasto del sistema di pianificazione o gestione dei trasporti'), ['tms', 'planification', 'tournees', 'systeme transport', 'panne wms'], { tic: true, cause: 'SYSTEMES', aCompleter: ['systemes', 'debut_fin', 'clients', 'mesures', 'pertes'], regimes: ['NIS2'], its: 'System failure' }),
  // ── Commerce / Distribution ──
  s('COMMERCE', 'card-data-compromise', 'CYBER', l('Compromission de données de cartes de paiement (caisses, terminaux, site de vente)', 'Compromise of payment-card data (tills, terminals, online store)', 'Kompromittierung von Zahlungskartendaten (Kassen, Terminals, Online-Shop)', 'Compromiso de datos de tarjetas de pago (cajas, terminales, tienda en línea)', 'Compromissione di dati di carte di pagamento (casse, terminali, negozio online)'), ['carte bancaire', 'skimming', 'pci', 'terminal paiement', 'magecart', 'caisse'], { tic: true, donnees: true, cause: 'EXTERNE', aCompleter: ['systemes', 'vecteur', 'indicateurs', 'donnees', 'clients', 'mesures', 'autorites'], regimes: ['RGPD_33'], its: 'Cybersecurity-related' }),
  s('COMMERCE', 'wrong-price', 'PROCESSUS', l('Prix erroné publié et appliqué aux ventes (magasin ou en ligne)', 'Wrong price published and applied to sales (in store or online)', 'Falscher Preis veröffentlicht und bei Verkäufen angewendet (Geschäft oder online)', 'Precio erróneo publicado y aplicado a las ventas (tienda o en línea)', 'Prezzo errato pubblicato e applicato alle vendite (negozio o online)'), ['erreur de prix', 'prix errone', 'tarif', 'promotion erronee', 'catalogue'], { cause: 'PROCESSUS', aCompleter: ['systemes', 'debut_fin', 'clients', 'pertes', 'mesures'] }),
  s('COMMERCE', 'product-safety-alert', 'PROCESSUS', l('Alerte de sécurité ou rappel concernant un produit vendu', 'Safety alert or recall concerning a product sold', 'Sicherheitswarnung oder Rückruf zu einem verkauften Produkt', 'Alerta de seguridad o retirada de un producto vendido', 'Allerta di sicurezza o richiamo relativo a un prodotto venduto'), ['rappel conso', 'alerte securite', 'produit dangereux', 'retrait produit', 'rappel produit'], { cause: 'TIERS', aCompleter: ['clients', 'mesures', 'autorites', 'pertes', 'preuves'] }),
  // ── Services professionnels ──
  s('SERVICES', 'client-data-disclosure', 'DONNEES_PERSONNELLES', l('Divulgation d’informations ou de documents confidentiels d’un client', 'Disclosure of a client’s confidential information or documents', 'Offenlegung vertraulicher Informationen oder Dokumente eines Kunden', 'Divulgación de información o documentos confidenciales de un cliente', 'Divulgazione di informazioni o documenti riservati di un cliente'), ['secret professionnel', 'dossier client', 'fuite cabinet', 'document confidentiel', 'mauvais destinataire'], { tic: true, donnees: true, cause: 'PERSONNES', aCompleter: ['donnees', 'clients', 'mesures', 'autorites', 'preuves'], regimes: ['RGPD_33'], its: 'Cybersecurity-related' }),
  s('SERVICES', 'mailbox-compromise', 'FRAUDE', l('Messagerie d’un associé ou collaborateur compromise utilisée pour tromper des clients', 'Partner’s or employee’s mailbox compromised and used to deceive clients', 'Postfach eines Partners oder Mitarbeiters kompromittiert und zur Täuschung von Kunden genutzt', 'Correo de un socio o empleado comprometido y utilizado para engañar a clientes', 'Casella di posta di un socio o dipendente compromessa e usata per ingannare i clienti'), ['faux rib', 'messagerie compromise', 'fraude au president', 'bec', 'usurpation associe'], { tic: true, cause: 'EXTERNE', aCompleter: ['systemes', 'vecteur', 'clients', 'pertes', 'mesures', 'autorites', 'preuves'], its: 'Cybersecurity-related' }),
  s('SERVICES', 'missed-deadline', 'PROCESSUS', l('Échéance légale ou contractuelle d’un client manquée', 'A client’s legal or contractual deadline missed', 'Gesetzliche oder vertragliche Frist eines Kunden versäumt', 'Plazo legal o contractual de un cliente incumplido', 'Scadenza legale o contrattuale di un cliente mancata'), ['delai manque', 'forclusion', 'echeance', 'retard livrable', 'responsabilite professionnelle'], { cause: 'PROCESSUS', aCompleter: ['clients', 'pertes', 'mesures', 'preuves'] }),
  // ── Agriculture / Agroalimentaire ──
  s('AGRICOLE', 'food-contamination', 'PROCESSUS', l('Contamination ou non-conformité alimentaire détectée sur des produits distribués', 'Food contamination or non-conformity detected on distributed products', 'Lebensmittelkontamination oder Nichtkonformität bei verteilten Produkten festgestellt', 'Contaminación o no conformidad alimentaria detectada en productos distribuidos', 'Contaminazione o non conformità alimentare rilevata su prodotti distribuiti'), ['contamination', 'listeria', 'salmonelle', 'toxi infection', 'rappel conso', 'allergene'], { cause: 'PROCESSUS', aCompleter: ['clients', 'mesures', 'autorites', 'pertes', 'preuves'] }),
  s('AGRICOLE', 'cold-chain-failure', 'CONTINUITE', l('Rupture de la chaîne du froid (panne de froid, transport non réfrigéré)', 'Cold-chain failure (refrigeration breakdown, unrefrigerated transport)', 'Kühlkettenunterbrechung (Kälteausfall, ungekühlter Transport)', 'Ruptura de la cadena de frío (avería de frío, transporte sin refrigeración)', 'Rottura della catena del freddo (guasto del freddo, trasporto non refrigerato)'), ['chaine du froid', 'panne frigorifique', 'temperature', 'chambre froide', 'denrees perdues'], { cause: 'SYSTEMES', aCompleter: ['systemes', 'debut_fin', 'clients', 'pertes', 'mesures'] }),
  s('AGRICOLE', 'production-system-attack', 'CYBER', l('Intrusion ou arrêt du pilotage des lignes de production ou d’équipements agricoles connectés', 'Intrusion or stoppage of production-line controls or connected farm equipment', 'Eindringen oder Stillstand der Steuerung von Produktionslinien oder vernetzten Landmaschinen', 'Intrusión o parada del control de líneas de producción o de equipos agrícolas conectados', 'Intrusione o fermo del controllo di linee di produzione o di apparecchiature agricole connesse'), ['ot agroalimentaire', 'ligne de production', 'tracteur connecte', 'automate', 'ransomware cooperative'], { tic: true, cause: 'EXTERNE', aCompleter: ['systemes', 'vecteur', 'indicateurs', 'mesures', 'pertes'], regimes: ['NIS2'], its: 'Cybersecurity-related' }),
  // ── Immobilier / Construction ──
  s('IMMOBILIER', 'wire-fraud', 'FRAUDE', l('Virement détourné par faux RIB lors d’une vente, d’un loyer ou d’un paiement de travaux', 'Transfer diverted through fake bank details during a sale, rent or works payment', 'Überweisung durch gefälschte Kontodaten bei Verkauf, Miete oder Bauzahlung umgeleitet', 'Transferencia desviada mediante un IBAN falso en una venta, alquiler o pago de obras', 'Bonifico dirottato con coordinate bancarie false durante una vendita, un affitto o un pagamento di lavori'), ['faux rib', 'fraude notaire', 'virement detourne', 'usurpation', 'fonds de clients'], { tic: true, cause: 'EXTERNE', aCompleter: ['pertes', 'clients', 'vecteur', 'mesures', 'autorites', 'preuves'], its: 'Cybersecurity-related' }),
  s('IMMOBILIER', 'site-accident', 'SECURITE_PHYSIQUE', l('Accident grave ou chute sur un chantier', 'Serious accident or fall on a construction site', 'Schwerer Unfall oder Absturz auf einer Baustelle', 'Accidente grave o caída en una obra', 'Grave incidente o caduta in un cantiere'), ['accident chantier', 'chute', 'bth', 'accident du travail', 'securite chantier'], { cause: 'PROCESSUS', aCompleter: ['personnes', 'debut_fin', 'mesures', 'autorites', 'preuves', 'pertes'] }),
  s('IMMOBILIER', 'tenant-file-leak', 'DONNEES_PERSONNELLES', l('Divulgation de dossiers de locataires, d’acquéreurs ou de copropriétaires', 'Disclosure of tenant, buyer or co-owner files', 'Offenlegung von Akten von Mietern, Käufern oder Eigentümern', 'Divulgación de expedientes de inquilinos, compradores o copropietarios', 'Divulgazione di fascicoli di inquilini, acquirenti o condomini'), ['dossier locataire', 'pieces identite', 'syndic', 'agence', 'fuite dossiers'], { donnees: true, cause: 'PERSONNES', aCompleter: ['donnees', 'personnes', 'mesures', 'autorites', 'preuves'], regimes: ['RGPD_33'] }),
  // ── Médias / Culture ──
  s('MEDIA', 'account-hijack', 'CYBER', l('Compte de publication ou réseau social piraté diffusant de faux contenus', 'Publishing or social account hijacked spreading false content', 'Veröffentlichungs- oder Social-Media-Konto übernommen und verbreitet falsche Inhalte', 'Cuenta de publicación o red social pirateada que difunde contenidos falsos', 'Account di pubblicazione o social violato che diffonde contenuti falsi'), ['compte piraté', 'reseau social', 'faux tweet', 'defiguration', 'usurpation media'], { tic: true, cause: 'EXTERNE', aCompleter: ['systemes', 'vecteur', 'indicateurs', 'mesures', 'clients'], its: 'Cybersecurity-related' }),
  s('MEDIA', 'broadcast-interruption', 'CONTINUITE', l('Interruption de la diffusion ou de la publication en direct', 'Interruption of live broadcast or publication', 'Unterbrechung der Live-Ausstrahlung oder -Veröffentlichung', 'Interrupción de la emisión o publicación en directo', 'Interruzione della trasmissione o pubblicazione in diretta'), ['panne antenne', 'coupure direct', 'diffusion', 'site indisponible', 'ddos media'], { tic: true, cause: 'SYSTEMES', aCompleter: ['systemes', 'debut_fin', 'clients', 'mesures'], its: 'System failure' }),
  s('MEDIA', 'pre-release-leak', 'CYBER', l('Fuite d’un contenu inédit ou d’une source confidentielle', 'Leak of unreleased content or a confidential source', 'Leak eines unveröffentlichten Inhalts oder einer vertraulichen Quelle', 'Filtración de un contenido inédito o de una fuente confidencial', 'Fuga di un contenuto inedito o di una fonte riservata'), ['fuite contenu', 'avant diffusion', 'source confidentielle', 'piratage', 'epreuves'], { tic: true, donnees: true, cause: 'PERSONNES', aCompleter: ['donnees', 'vecteur', 'mesures', 'preuves'], its: 'Cybersecurity-related' }),
  // ── Tourisme / Hôtellerie-restauration ──
  s('TOURISME', 'booking-fraud', 'FRAUDE', l('Fraude sur des réservations ou prise de contrôle d’un compte de réservation', 'Booking fraud or takeover of a booking account', 'Buchungsbetrug oder Übernahme eines Buchungskontos', 'Fraude en reservas o usurpación de una cuenta de reservas', 'Frode sulle prenotazioni o presa di controllo di un account di prenotazione'), ['fausse reservation', 'compte booking', 'extranet', 'usurpation reservation', 'paiement frauduleux'], { tic: true, cause: 'EXTERNE', aCompleter: ['systemes', 'vecteur', 'clients', 'pertes', 'mesures', 'preuves'], its: 'Cybersecurity-related' }),
  s('TOURISME', 'food-poisoning', 'SECURITE_PHYSIQUE', l('Intoxication alimentaire ou incident sanitaire touchant des clients', 'Food poisoning or hygiene incident affecting guests', 'Lebensmittelvergiftung oder Hygienevorfall mit betroffenen Gästen', 'Intoxicación alimentaria o incidente sanitario que afecta a clientes', 'Intossicazione alimentare o incidente igienico-sanitario che coinvolge gli ospiti'), ['intoxication', 'toxi infection', 'allergene', 'hygiene', 'restauration collective'], { cause: 'PROCESSUS', aCompleter: ['personnes', 'debut_fin', 'mesures', 'autorites', 'preuves', 'pertes'] }),
  s('TOURISME', 'guest-data-leak', 'DONNEES_PERSONNELLES', l('Divulgation de données de clients (identité, documents de voyage, paiements)', 'Disclosure of guest data (identity, travel documents, payments)', 'Offenlegung von Gästedaten (Identität, Reisedokumente, Zahlungen)', 'Divulgación de datos de clientes (identidad, documentos de viaje, pagos)', 'Divulgazione di dati degli ospiti (identità, documenti di viaggio, pagamenti)'), ['fiches clients', 'carte bancaire', 'passeport', 'fuite hotel', 'rgpd tourisme'], { tic: true, donnees: true, cause: 'EXTERNE', aCompleter: ['systemes', 'donnees', 'personnes', 'vecteur', 'mesures', 'autorites'], regimes: ['RGPD_33'], its: 'Cybersecurity-related' }),
  // ── Associations / ESS ──
  s('ASSOCIATIONS', 'treasury-fraud', 'FRAUDE', l('Détournement de fonds ou paiement frauduleux au détriment de l’association', 'Misappropriation of funds or fraudulent payment to the organisation’s detriment', 'Veruntreuung von Geldern oder betrügerische Zahlung zulasten der Organisation', 'Desvío de fondos o pago fraudulento en perjuicio de la asociación', 'Sottrazione di fondi o pagamento fraudolento a danno dell’associazione'), ['detournement', 'tresorier', 'faux virement', 'usurpation dirigeant', 'fraude association'], { cause: 'PERSONNES', aCompleter: ['pertes', 'mesures', 'autorites', 'preuves'] }),
  s('ASSOCIATIONS', 'member-data-leak', 'DONNEES_PERSONNELLES', l('Divulgation de données d’adhérents, de donateurs ou de bénéficiaires vulnérables', 'Disclosure of member, donor or vulnerable-beneficiary data', 'Offenlegung von Daten von Mitgliedern, Spendern oder schutzbedürftigen Begünstigten', 'Divulgación de datos de socios, donantes o beneficiarios vulnerables', 'Divulgazione di dati di soci, donatori o beneficiari vulnerabili'), ['adherents', 'donateurs', 'beneficiaires', 'fichier', 'fuite association'], { donnees: true, cause: 'PERSONNES', aCompleter: ['donnees', 'personnes', 'mesures', 'autorites', 'preuves'], regimes: ['RGPD_33'] }),
  s('ASSOCIATIONS', 'volunteer-harm', 'SECURITE_PHYSIQUE', l('Préjudice subi par un bénévole ou un bénéficiaire lors d’une activité', 'Harm suffered by a volunteer or beneficiary during an activity', 'Schaden eines Ehrenamtlichen oder Begünstigten bei einer Aktivität', 'Daño sufrido por un voluntario o beneficiario durante una actividad', 'Danno subito da un volontario o beneficiario durante un’attività'), ['accident benevole', 'maltraitance', 'comportement inapproprie', 'evenement', 'secours'], { cause: 'PERSONNES', aCompleter: ['personnes', 'debut_fin', 'mesures', 'autorites', 'preuves'] }),
]
