/**
 * Pack « banque / assurance / mutuelle » (catalogue 1.9) : domaines de contrôle propres à ces métiers et contrôles-types par domaine.
 * Mêmes règles que les autres packs : suggestions à qualifier (responsable, périmètre, échantillon), jamais d'exécution, de seuil,
 * de date, de résultat ni de conformité acquise. Les `references` citent le texte d'origine (intitulé officiel, version) pour
 * ancrer chaque domaine ; elles NE reproduisent AUCUN libellé d'exigence. Contenu à soumettre à la revue métier
 * (docs/specs/catalogue-revue-metier.md) : périodicités et échantillons sont des points de départ, à adapter à la taille de l'entité.
 * Les mutuelles relèvent du pack « Assurance » (Code de la mutualité) ; leurs contrôles propres sont regroupés dans le domaine « adhérents ».
 */
import type { CatalogueItem, Localized, SectorCode } from './sector-suggestions'

const l = (fr: string, en: string, de: string, es: string, it: string): Localized => ({ fr, en, de, es, it })
type Periodicite = NonNullable<CatalogueItem['periodicite']>
type CType = NonNullable<CatalogueItem['controlType']>
const p = (sector: SectorCode, key: string, title: Localized): CatalogueItem => ({ key, sector, kind: 'PROCESS', title })
const c = (sector: SectorCode, key: string, title: Localized, processKey: string, periodicite: Periodicite, controlType: CType, references?: string[]): CatalogueItem =>
  ({ key, sector, kind: 'CONTROL', title, processKey, periodicite, controlType, ...(references ? { references } : {}) })

const ARRETE_2014 = 'Arrêté du 3 novembre 2014 relatif au contrôle interne des entreprises du secteur de la banque, des services de paiement et des services d’investissement soumises au contrôle de l’ACPR'
const DORA = 'Règlement (UE) 2022/2554 (DORA)'
const S2 = 'Directive 2009/138/CE (Solvabilité II)'
const CMF_LCBFT = 'Code monétaire et financier, livre V, titre VI (LCB-FT, gel des avoirs)'
const CMUT = 'Code de la mutualité'

export const BANCASSURANCE_ITEMS: CatalogueItem[] = [
  // ═══ Banque — domaines ════════════════════════════════════════════════════
  p('FINANCE', 'finance.process.governance', l('Piloter le contrôle interne et la gouvernance des risques', 'Run internal control and risk governance', 'Internes Kontrollsystem und Risikogovernance steuern', 'Dirigir el control interno y la gobernanza de riesgos', 'Governare il controllo interno e la governance dei rischi')),
  p('FINANCE', 'finance.process.markets', l('Gérer les opérations de marché, la liquidité et le bilan', 'Manage market operations, liquidity and the balance sheet', 'Marktgeschäfte, Liquidität und Bilanz steuern', 'Gestionar las operaciones de mercado, la liquidez y el balance', 'Gestire le operazioni di mercato, la liquidità e il bilancio')),
  p('FINANCE', 'finance.process.aml', l('Lutter contre le blanchiment et le financement du terrorisme, appliquer les sanctions', 'Combat money laundering and terrorist financing, apply sanctions', 'Geldwäsche und Terrorismusfinanzierung bekämpfen, Sanktionen anwenden', 'Luchar contra el blanqueo y la financiación del terrorismo, aplicar sanciones', 'Contrastare il riciclaggio e il finanziamento del terrorismo, applicare le sanzioni')),
  p('FINANCE', 'finance.process.compliance', l('Protéger la clientèle et assurer la conformité des services', 'Protect customers and ensure service compliance', 'Kunden schützen und Konformität der Dienstleistungen sicherstellen', 'Proteger a la clientela y asegurar la conformidad de los servicios', 'Tutelare la clientela e garantire la conformità dei servizi')),
  p('FINANCE', 'finance.process.reporting', l('Produire l’information comptable et réglementaire', 'Produce accounting and regulatory reporting', 'Rechnungslegung und aufsichtliches Meldewesen erstellen', 'Elaborar la información contable y reglamentaria', 'Produrre l’informativa contabile e regolamentare')),
  p('FINANCE', 'finance.process.ict', l('Maîtriser les risques liés aux TIC et aux prestataires', 'Control ICT and third-party provider risks', 'IKT-Risiken und Dienstleisterrisiken beherrschen', 'Controlar los riesgos de las TIC y de los proveedores', 'Controllare i rischi delle TIC e dei fornitori')),

  // ── Banque — gouvernance et contrôle interne
  c('FINANCE', 'finance.control.control-plan', l('Revue de la réalisation du plan de contrôle permanent (niveaux 1 et 2)', 'Review of the completion of the permanent control plan (levels 1 and 2)', 'Überprüfung der Umsetzung des Plans der laufenden Kontrollen (Stufen 1 und 2)', 'Revisión de la ejecución del plan de control permanente (niveles 1 y 2)', 'Revisione dell’esecuzione del piano di controllo permanente (livelli 1 e 2)'), 'finance.process.governance', 'TRIMESTRIEL', 'DETECTIF', [ARRETE_2014]),
  c('FINANCE', 'finance.control.delegations', l('Revue des délégations de pouvoirs et de signature', 'Review of powers and signing delegations', 'Überprüfung der Befugnis- und Zeichnungsdelegationen', 'Revisión de las delegaciones de poderes y de firma', 'Revisione delle deleghe di poteri e di firma'), 'finance.process.governance', 'SEMESTRIEL', 'PREVENTIF', [ARRETE_2014]),
  c('FINANCE', 'finance.control.incident-escalation', l('Contrôle de la remontée des incidents significatifs de contrôle interne à la direction', 'Check that significant internal-control incidents are escalated to management', 'Prüfung der Eskalation wesentlicher Vorfälle des internen Kontrollsystems an die Geschäftsleitung', 'Control de la escalada de los incidentes significativos de control interno a la dirección', 'Verifica dell’escalation degli incidenti significativi di controllo interno alla direzione'), 'finance.process.governance', 'TRIMESTRIEL', 'DETECTIF', [ARRETE_2014]),
  // ── Banque — crédit
  c('FINANCE', 'finance.control.credit-sample', l('Contrôle par échantillon des dossiers de crédit (analyse, garanties, délégation)', 'Sample check of credit files (analysis, collateral, delegation)', 'Stichprobenprüfung von Kreditakten (Analyse, Sicherheiten, Delegation)', 'Control por muestreo de los expedientes de crédito (análisis, garantías, delegación)', 'Controllo a campione delle pratiche di credito (analisi, garanzie, delega)'), 'finance.process.credit', 'MENSUEL', 'DETECTIF', [ARRETE_2014]),
  c('FINANCE', 'finance.control.credit-limits', l('Suivi des dépassements de limites de risque de contrepartie et de concentration', 'Monitoring of counterparty and concentration limit breaches', 'Überwachung von Überschreitungen der Gegenpartei- und Konzentrationslimite', 'Seguimiento de los excesos de límites de contraparte y de concentración', 'Monitoraggio dei superamenti dei limiti di controparte e di concentrazione'), 'finance.process.credit', 'MENSUEL', 'DETECTIF', [ARRETE_2014]),
  c('FINANCE', 'finance.control.default-classification', l('Revue du classement des créances sensibles et en défaut et des provisions associées', 'Review of the classification of watch-list and defaulted exposures and related provisions', 'Überprüfung der Einstufung gefährdeter und ausgefallener Forderungen und der zugehörigen Rückstellungen', 'Revisión de la clasificación de los créditos dudosos y en incumplimiento y de sus provisiones', 'Revisione della classificazione dei crediti deteriorati e in default e dei relativi accantonamenti'), 'finance.process.credit', 'TRIMESTRIEL', 'DETECTIF', [ARRETE_2014]),
  c('FINANCE', 'finance.control.collateral-valuation', l('Revue de la valorisation et de la mise à jour des garanties', 'Review of collateral valuation and updates', 'Überprüfung von Bewertung und Aktualisierung der Sicherheiten', 'Revisión de la valoración y actualización de las garantías', 'Revisione della valutazione e dell’aggiornamento delle garanzie'), 'finance.process.credit', 'SEMESTRIEL', 'DETECTIF', [ARRETE_2014]),
  // ── Banque — marchés, liquidité, bilan
  c('FINANCE', 'finance.control.market-limits', l('Contrôle du respect des limites de marché et de leur suivi', 'Check of compliance with market limits and their monitoring', 'Prüfung der Einhaltung der Marktlimite und ihrer Überwachung', 'Control del cumplimiento de los límites de mercado y de su seguimiento', 'Verifica del rispetto dei limiti di mercato e del loro monitoraggio'), 'finance.process.markets', 'MENSUEL', 'DETECTIF', [ARRETE_2014]),
  c('FINANCE', 'finance.control.valuation-check', l('Vérification indépendante de la valorisation des positions', 'Independent verification of position valuation', 'Unabhängige Überprüfung der Bewertung von Positionen', 'Verificación independiente de la valoración de las posiciones', 'Verifica indipendente della valutazione delle posizioni'), 'finance.process.markets', 'MENSUEL', 'DETECTIF', [ARRETE_2014]),
  c('FINANCE', 'finance.control.liquidity-ratios', l('Contrôle du calcul et du suivi des ratios de liquidité et de financement', 'Check of the calculation and monitoring of liquidity and funding ratios', 'Prüfung der Berechnung und Überwachung der Liquiditäts- und Refinanzierungskennzahlen', 'Control del cálculo y seguimiento de los ratios de liquidez y financiación', 'Verifica del calcolo e del monitoraggio degli indicatori di liquidità e di finanziamento'), 'finance.process.markets', 'MENSUEL', 'DETECTIF', ['Règlement (UE) n° 575/2013 (CRR)']),
  // ── Banque — paiements et canaux
  c('FINANCE', 'finance.control.payment-four-eyes', l('Contrôle du principe des quatre yeux sur les opérations de paiement sensibles', 'Check of the four-eyes principle on sensitive payment operations', 'Prüfung des Vier-Augen-Prinzips bei sensiblen Zahlungsvorgängen', 'Control del principio de los cuatro ojos en las operaciones de pago sensibles', 'Verifica del principio dei quattro occhi sulle operazioni di pagamento sensibili'), 'finance.process.payments', 'MENSUEL', 'PREVENTIF', [ARRETE_2014]),
  c('FINANCE', 'finance.control.fraud-monitoring', l('Revue des alertes de surveillance de la fraude sur les moyens de paiement', 'Review of payment-fraud monitoring alerts', 'Überprüfung der Warnmeldungen der Betrugsüberwachung bei Zahlungsmitteln', 'Revisión de las alertas de vigilancia del fraude en medios de pago', 'Revisione degli avvisi di monitoraggio delle frodi sugli strumenti di pagamento'), 'finance.process.payments', 'MENSUEL', 'DETECTIF', ['Directive (UE) 2015/2366 (DSP2)']),
  c('FINANCE', 'finance.control.strong-authentication', l('Vérification de l’application de l’authentification forte du client sur les canaux numériques', 'Check that strong customer authentication is applied on digital channels', 'Prüfung der Anwendung der starken Kundenauthentifizierung auf digitalen Kanälen', 'Verificación de la aplicación de la autenticación reforzada del cliente en los canales digitales', 'Verifica dell’applicazione dell’autenticazione forte del cliente sui canali digitali'), 'finance.process.channels', 'TRIMESTRIEL', 'PREVENTIF', ['Directive (UE) 2015/2366 (DSP2)', 'Règlement délégué (UE) 2018/389']),
  // ── Banque — LCB-FT et sanctions
  c('FINANCE', 'finance.control.kyc-sample', l('Contrôle par échantillon de la connaissance client et de sa mise à jour périodique', 'Sample check of customer due diligence and its periodic update', 'Stichprobenprüfung der Kundenidentifizierung und ihrer regelmäßigen Aktualisierung', 'Control por muestreo del conocimiento del cliente y de su actualización periódica', 'Controllo a campione dell’adeguata verifica della clientela e del suo aggiornamento periodico'), 'finance.process.aml', 'TRIMESTRIEL', 'DETECTIF', [CMF_LCBFT]),
  c('FINANCE', 'finance.control.aml-alerts', l('Revue de la qualité et des délais de traitement des alertes de surveillance des opérations', 'Review of the quality and timeliness of transaction-monitoring alert handling', 'Überprüfung von Qualität und Fristen der Bearbeitung von Transaktionsüberwachungswarnungen', 'Revisión de la calidad y de los plazos de tratamiento de las alertas de vigilancia de operaciones', 'Revisione della qualità e dei tempi di trattamento degli avvisi di monitoraggio delle operazioni'), 'finance.process.aml', 'MENSUEL', 'DETECTIF', [CMF_LCBFT]),
  c('FINANCE', 'finance.control.str-quality', l('Contrôle de la qualité et du respect des délais des déclarations de soupçon', 'Check of the quality and timeliness of suspicious transaction reports', 'Prüfung von Qualität und Fristeinhaltung der Verdachtsmeldungen', 'Control de la calidad y del cumplimiento de plazos de las comunicaciones de operaciones sospechosas', 'Verifica della qualità e del rispetto dei termini delle segnalazioni di operazioni sospette'), 'finance.process.aml', 'TRIMESTRIEL', 'DETECTIF', [CMF_LCBFT]),
  c('FINANCE', 'finance.control.asset-freeze', l('Vérification du filtrage des listes de gel des avoirs et de ses mises à jour', 'Check of asset-freeze list screening and its updates', 'Prüfung des Abgleichs mit Listen zum Einfrieren von Vermögenswerten und seiner Aktualisierungen', 'Verificación del filtrado de las listas de inmovilización de activos y de sus actualizaciones', 'Verifica del filtraggio delle liste di congelamento dei beni e dei suoi aggiornamenti'), 'finance.process.aml', 'MENSUEL', 'PREVENTIF', [CMF_LCBFT]),
  // ── Banque — conformité et protection de la clientèle
  c('FINANCE', 'finance.control.suitability', l('Contrôle par échantillon de l’adéquation des produits et services d’investissement proposés', 'Sample check of the suitability of investment products and services offered', 'Stichprobenprüfung der Eignung angebotener Anlageprodukte und -dienstleistungen', 'Control por muestreo de la idoneidad de los productos y servicios de inversión ofrecidos', 'Controllo a campione dell’adeguatezza dei prodotti e servizi di investimento offerti'), 'finance.process.compliance', 'TRIMESTRIEL', 'DETECTIF', ['Directive 2014/65/UE (MIF II)']),
  c('FINANCE', 'finance.control.complaints', l('Revue du traitement des réclamations clients et de leurs délais', 'Review of customer complaint handling and timelines', 'Überprüfung der Bearbeitung von Kundenbeschwerden und der Fristen', 'Revisión del tratamiento de las reclamaciones de clientes y de sus plazos', 'Revisione della gestione dei reclami dei clienti e dei relativi tempi'), 'finance.process.compliance', 'TRIMESTRIEL', 'DETECTIF', [ARRETE_2014]),
  c('FINANCE', 'finance.control.marketing-review', l('Contrôle préalable des communications commerciales et de l’information précontractuelle', 'Prior review of marketing communications and pre-contractual information', 'Vorabprüfung von Werbemitteilungen und vorvertraglichen Informationen', 'Control previo de las comunicaciones comerciales y de la información precontractual', 'Verifica preventiva delle comunicazioni commerciali e dell’informativa precontrattuale'), 'finance.process.compliance', 'TRIMESTRIEL', 'PREVENTIF'),
  // ── Banque — information comptable et réglementaire
  c('FINANCE', 'finance.control.regulatory-reporting', l('Contrôle de la qualité des données et de la réconciliation comptable-prudentielle avant remise des états réglementaires', 'Check of data quality and accounting-to-prudential reconciliation before regulatory returns are filed', 'Prüfung der Datenqualität und der Abstimmung Rechnungswesen–Aufsicht vor Einreichung der aufsichtlichen Meldungen', 'Control de la calidad de los datos y de la conciliación contable-prudencial antes de remitir los estados reglamentarios', 'Verifica della qualità dei dati e della riconciliazione contabile-prudenziale prima dell’invio delle segnalazioni regolamentari'), 'finance.process.reporting', 'TRIMESTRIEL', 'PREVENTIF', ['Règlement d’exécution (UE) 2021/451']),
  c('FINANCE', 'finance.control.suspense-accounts', l('Revue des rapprochements comptables et des comptes d’attente', 'Review of accounting reconciliations and suspense accounts', 'Überprüfung der Kontenabstimmungen und Durchlaufkonten', 'Revisión de las conciliaciones contables y de las cuentas transitorias', 'Revisione delle riconciliazioni contabili e dei conti transitori'), 'finance.process.reporting', 'MENSUEL', 'DETECTIF', [ARRETE_2014]),
  // ── Banque — TIC et prestataires (DORA)
  c('FINANCE', 'finance.control.ict-register', l('Revue du registre d’information des accords contractuels avec les prestataires de services TIC', 'Review of the register of information on contractual arrangements with ICT service providers', 'Überprüfung des Informationsregisters der vertraglichen Vereinbarungen mit IKT-Drittdienstleistern', 'Revisión del registro de información de los acuerdos contractuales con proveedores de servicios TIC', 'Revisione del registro delle informazioni sugli accordi contrattuali con i fornitori di servizi TIC'), 'finance.process.ict', 'TRIMESTRIEL', 'DETECTIF', [DORA]),
  c('FINANCE', 'finance.control.critical-providers', l('Suivi des niveaux de service et des incidents des prestataires de fonctions critiques ou importantes', 'Monitoring of service levels and incidents of providers of critical or important functions', 'Überwachung der Servicelevel und Vorfälle von Dienstleistern kritischer oder wichtiger Funktionen', 'Seguimiento de los niveles de servicio y de los incidentes de los proveedores de funciones críticas o importantes', 'Monitoraggio dei livelli di servizio e degli incidenti dei fornitori di funzioni critiche o importanti'), 'finance.process.ict', 'TRIMESTRIEL', 'DETECTIF', [DORA, ARRETE_2014]),
  c('FINANCE', 'finance.control.resilience-testing', l('Suivi du programme annuel de tests de résilience opérationnelle numérique et de ses remédiations', 'Follow-up of the annual digital operational resilience testing programme and its remediation', 'Nachverfolgung des jährlichen Testprogramms zur digitalen operationalen Resilienz und seiner Behebungsmaßnahmen', 'Seguimiento del programa anual de pruebas de resiliencia operativa digital y de sus correcciones', 'Monitoraggio del programma annuale di test di resilienza operativa digitale e delle relative azioni correttive'), 'finance.process.ict', 'TRIMESTRIEL', 'DETECTIF', [DORA]),
  c('FINANCE', 'finance.control.incident-reporting-drill', l('Test de la chaîne de classification et de déclaration des incidents TIC majeurs', 'Test of the classification and reporting chain for major ICT-related incidents', 'Test der Kette zur Klassifizierung und Meldung schwerwiegender IKT-bezogener Vorfälle', 'Prueba de la cadena de clasificación y notificación de incidentes graves relacionados con las TIC', 'Test della catena di classificazione e notifica degli incidenti gravi connessi alle TIC'), 'finance.process.ict', 'SEMESTRIEL', 'PREVENTIF', [DORA]),

  // ═══ Assurance et mutuelle — domaines ═════════════════════════════════════
  p('ASSURANCE', 'assurance.process.governance', l('Piloter le système de gouvernance et les fonctions clés', 'Run the system of governance and the key functions', 'Governance-System und Schlüsselfunktionen steuern', 'Dirigir el sistema de gobernanza y las funciones fundamentales', 'Governare il sistema di governance e le funzioni fondamentali')),
  p('ASSURANCE', 'assurance.process.orsa', l('Évaluer les risques et la solvabilité (ORSA) et piloter le capital', 'Assess risks and solvency (ORSA) and manage capital', 'Risiken und Solvabilität beurteilen (ORSA) und Kapital steuern', 'Evaluar los riesgos y la solvencia (ORSA) y gestionar el capital', 'Valutare i rischi e la solvibilità (ORSA) e gestire il capitale')),
  p('ASSURANCE', 'assurance.process.reserving', l('Constituer et suivre les provisions techniques', 'Establish and monitor technical provisions', 'Versicherungstechnische Rückstellungen bilden und überwachen', 'Constituir y supervisar las provisiones técnicas', 'Costituire e monitorare le riserve tecniche')),
  p('ASSURANCE', 'assurance.process.investments', l('Gérer les placements et la réassurance', 'Manage investments and reinsurance', 'Kapitalanlagen und Rückversicherung steuern', 'Gestionar las inversiones y el reaseguro', 'Gestire gli investimenti e la riassicurazione')),
  p('ASSURANCE', 'assurance.process.aml', l('Lutter contre le blanchiment et le financement du terrorisme, appliquer le gel des avoirs', 'Combat money laundering and terrorist financing, apply asset freezes', 'Geldwäsche und Terrorismusfinanzierung bekämpfen, Einfrieren von Vermögenswerten anwenden', 'Luchar contra el blanqueo y la financiación del terrorismo, aplicar la inmovilización de activos', 'Contrastare il riciclaggio e il finanziamento del terrorismo, applicare il congelamento dei beni')),
  p('ASSURANCE', 'assurance.process.members', l('Gérer les adhérents, les cotisations et les prestations (mutuelles)', 'Manage members, contributions and benefits (mutual insurers)', 'Mitglieder, Beiträge und Leistungen verwalten (Versicherungsvereine auf Gegenseitigkeit)', 'Gestionar a los mutualistas, las cuotas y las prestaciones (mutualidades)', 'Gestire gli aderenti, i contributi e le prestazioni (mutue)')),
  p('ASSURANCE', 'assurance.process.ict', l('Maîtriser les risques liés aux TIC et aux prestataires', 'Control ICT and third-party provider risks', 'IKT-Risiken und Dienstleisterrisiken beherrschen', 'Controlar los riesgos de las TIC y de los proveedores', 'Controllare i rischi delle TIC e dei fornitori')),

  // ── Assurance — gouvernance et fonctions clés
  c('ASSURANCE', 'assurance.control.key-functions', l('Revue de l’indépendance et des rapports annuels des fonctions clés (risques, conformité, audit interne, actuariat)', 'Review of the independence and annual reports of the key functions (risk, compliance, internal audit, actuarial)', 'Überprüfung der Unabhängigkeit und der Jahresberichte der Schlüsselfunktionen (Risiko, Compliance, Interne Revision, Versicherungsmathematik)', 'Revisión de la independencia y de los informes anuales de las funciones fundamentales (riesgos, cumplimiento, auditoría interna, actuarial)', 'Revisione dell’indipendenza e delle relazioni annuali delle funzioni fondamentali (rischi, conformità, revisione interna, attuariale)'), 'assurance.process.governance', 'ANNUEL', 'DETECTIF', [`${S2}, art. 44 à 48`]),
  c('ASSURANCE', 'assurance.control.policies-review', l('Revue annuelle des politiques écrites approuvées par l’organe d’administration', 'Annual review of the written policies approved by the administrative body', 'Jährliche Überprüfung der vom Verwaltungsorgan genehmigten schriftlichen Leitlinien', 'Revisión anual de las políticas escritas aprobadas por el órgano de administración', 'Revisione annuale delle politiche scritte approvate dall’organo amministrativo'), 'assurance.process.governance', 'ANNUEL', 'PREVENTIF', [`${S2}, art. 41`]),
  c('ASSURANCE', 'assurance.control.fit-proper', l('Contrôle de la compétence et de l’honorabilité des dirigeants effectifs et des responsables de fonctions clés', 'Check of the fitness and propriety of persons who effectively run the undertaking and key function holders', 'Prüfung der fachlichen Qualifikation und Zuverlässigkeit der tatsächlichen Leiter und Inhaber von Schlüsselfunktionen', 'Control de la competencia y honorabilidad de los dirigentes efectivos y de los responsables de funciones fundamentales', 'Verifica dei requisiti di competenza e onorabilità dei dirigenti effettivi e dei titolari di funzioni fondamentali'), 'assurance.process.governance', 'ANNUEL', 'PREVENTIF', [`${S2}, art. 42`]),
  c('ASSURANCE', 'assurance.control.governance-escalation', l('Suivi des décisions et des alertes remontées aux instances de gouvernance', 'Follow-up of decisions and alerts escalated to governance bodies', 'Nachverfolgung von Beschlüssen und Warnmeldungen an die Governance-Gremien', 'Seguimiento de las decisiones y alertas elevadas a los órganos de gobierno', 'Monitoraggio delle decisioni e degli avvisi riportati agli organi di governo'), 'assurance.process.governance', 'TRIMESTRIEL', 'DETECTIF', [`${S2}, art. 46`]),
  // ── Assurance — ORSA et capital
  c('ASSURANCE', 'assurance.control.orsa-process', l('Contrôle de la réalisation et de l’approbation de l’évaluation interne des risques et de la solvabilité (ORSA)', 'Check of the performance and approval of the own risk and solvency assessment (ORSA)', 'Prüfung der Durchführung und Genehmigung der unternehmenseigenen Risiko- und Solvabilitätsbeurteilung (ORSA)', 'Control de la realización y aprobación de la evaluación interna de riesgos y solvencia (ORSA)', 'Verifica dello svolgimento e dell’approvazione della valutazione interna del rischio e della solvibilità (ORSA)'), 'assurance.process.orsa', 'ANNUEL', 'DETECTIF', [`${S2}, art. 45`]),
  c('ASSURANCE', 'assurance.control.solvency-coverage', l('Suivi de la couverture du capital de solvabilité requis et des fonds propres éligibles', 'Monitoring of coverage of the solvency capital requirement and eligible own funds', 'Überwachung der Bedeckung der Solvenzkapitalanforderung und der anrechnungsfähigen Eigenmittel', 'Seguimiento de la cobertura del capital de solvencia obligatorio y de los fondos propios admisibles', 'Monitoraggio della copertura del requisito patrimoniale di solvibilità e dei fondi propri ammissibili'), 'assurance.process.orsa', 'TRIMESTRIEL', 'DETECTIF', [S2]),
  c('ASSURANCE', 'assurance.control.risk-appetite', l('Suivi du respect des limites d’appétence au risque', 'Monitoring of compliance with risk-appetite limits', 'Überwachung der Einhaltung der Risikoappetit-Limite', 'Seguimiento del cumplimiento de los límites de apetito al riesgo', 'Monitoraggio del rispetto dei limiti di propensione al rischio'), 'assurance.process.orsa', 'TRIMESTRIEL', 'DETECTIF', [`${S2}, art. 44`]),
  // ── Assurance — souscription et tarification
  c('ASSURANCE', 'assurance.control.underwriting-delegations', l('Contrôle du respect des délégations de souscription', 'Check of compliance with underwriting delegations', 'Prüfung der Einhaltung der Zeichnungsvollmachten', 'Control del cumplimiento de las delegaciones de suscripción', 'Verifica del rispetto delle deleghe di sottoscrizione'), 'assurance.process.underwrite', 'MENSUEL', 'DETECTIF'),
  c('ASSURANCE', 'assurance.control.new-business-sample', l('Contrôle par échantillon des affaires nouvelles (acceptation, pièces, tarif appliqué)', 'Sample check of new business (acceptance, documents, tariff applied)', 'Stichprobenprüfung von Neugeschäft (Annahme, Unterlagen, angewandter Tarif)', 'Control por muestreo de las nuevas contrataciones (aceptación, documentos, tarifa aplicada)', 'Controllo a campione dei nuovi affari (accettazione, documenti, tariffa applicata)'), 'assurance.process.underwrite', 'MENSUEL', 'DETECTIF'),
  // ── Assurance — provisions techniques
  c('ASSURANCE', 'assurance.control.reserve-backtesting', l('Revue du suivi des provisions techniques (comparaison estimations / réalisé)', 'Review of technical provision monitoring (estimates versus experience)', 'Überprüfung der Überwachung der versicherungstechnischen Rückstellungen (Schätzung gegen Erfahrung)', 'Revisión del seguimiento de las provisiones técnicas (estimaciones frente a lo realizado)', 'Revisione del monitoraggio delle riserve tecniche (stime rispetto al consuntivo)'), 'assurance.process.reserving', 'TRIMESTRIEL', 'DETECTIF', [`${S2}, art. 48`]),
  c('ASSURANCE', 'assurance.control.actuarial-data-quality', l('Contrôle de la qualité et de l’exhaustivité des données utilisées pour le calcul des provisions', 'Check of the quality and completeness of the data used to calculate provisions', 'Prüfung von Qualität und Vollständigkeit der für die Rückstellungsberechnung verwendeten Daten', 'Control de la calidad y exhaustividad de los datos utilizados para calcular las provisiones', 'Verifica della qualità e completezza dei dati utilizzati per il calcolo delle riserve'), 'assurance.process.reserving', 'TRIMESTRIEL', 'PREVENTIF', [`${S2}, art. 82`]),
  // ── Assurance — sinistres
  c('ASSURANCE', 'assurance.control.claims-delays', l('Contrôle du respect des délais de traitement et de règlement des sinistres', 'Check of compliance with claims handling and settlement timelines', 'Prüfung der Einhaltung der Fristen für Schadenbearbeitung und -regulierung', 'Control del cumplimiento de los plazos de tramitación y pago de siniestros', 'Verifica del rispetto dei termini di gestione e liquidazione dei sinistri'), 'assurance.process.claims', 'MENSUEL', 'DETECTIF'),
  c('ASSURANCE', 'assurance.control.claims-segregation', l('Contrôle des délégations de règlement et de la séparation des tâches en gestion des sinistres', 'Check of settlement delegations and segregation of duties in claims handling', 'Prüfung der Regulierungsvollmachten und der Funktionstrennung in der Schadenbearbeitung', 'Control de las delegaciones de liquidación y de la separación de funciones en la gestión de siniestros', 'Verifica delle deleghe di liquidazione e della separazione dei compiti nella gestione dei sinistri'), 'assurance.process.claims', 'TRIMESTRIEL', 'PREVENTIF'),
  c('ASSURANCE', 'assurance.control.delegated-managers', l('Contrôle des gestionnaires délégataires (sinistres, tiers payant, administration des contrats)', 'Oversight of delegated managers (claims, third-party payment, policy administration)', 'Überwachung delegierter Verwalter (Schäden, Direktabrechnung, Vertragsverwaltung)', 'Control de los gestores delegados (siniestros, tercero pagador, administración de contratos)', 'Controllo dei gestori delegati (sinistri, terzo pagante, amministrazione dei contratti)'), 'assurance.process.claims', 'TRIMESTRIEL', 'DETECTIF', [`${S2}, art. 49`]),
  // ── Assurance — distribution
  c('ASSURANCE', 'assurance.control.advice-sample', l('Contrôle par échantillon du recueil des exigences et besoins et du devoir de conseil', 'Sample check of the demands-and-needs assessment and the duty of advice', 'Stichprobenprüfung der Bedarfsermittlung und der Beratungspflicht', 'Control por muestreo de la recogida de exigencias y necesidades y del deber de asesoramiento', 'Controllo a campione della rilevazione di richieste ed esigenze e dell’obbligo di consulenza'), 'assurance.process.brokers', 'TRIMESTRIEL', 'DETECTIF', ['Directive (UE) 2016/97 (DDA)']),
  c('ASSURANCE', 'assurance.control.intermediaries', l('Vérification de l’immatriculation et de la formation continue des intermédiaires et du réseau', 'Check of registration and continuing training of intermediaries and the network', 'Prüfung von Registrierung und Weiterbildung der Vermittler und des Vertriebsnetzes', 'Verificación del registro y de la formación continua de los intermediarios y de la red', 'Verifica dell’iscrizione e della formazione continua degli intermediari e della rete'), 'assurance.process.brokers', 'SEMESTRIEL', 'PREVENTIF', ['Directive (UE) 2016/97 (DDA)']),
  c('ASSURANCE', 'assurance.control.product-governance', l('Revue de la gouvernance des produits (approbation, marché cible, revue périodique)', 'Review of product governance (approval, target market, periodic review)', 'Überprüfung der Produktgovernance (Genehmigung, Zielmarkt, regelmäßige Überprüfung)', 'Revisión de la gobernanza de productos (aprobación, mercado objetivo, revisión periódica)', 'Revisione della governance dei prodotti (approvazione, mercato di riferimento, revisione periodica)'), 'assurance.process.brokers', 'ANNUEL', 'PREVENTIF', ['Règlement délégué (UE) 2017/2358']),
  c('ASSURANCE', 'assurance.control.complaints', l('Revue du traitement des réclamations des assurés et adhérents', 'Review of the handling of policyholder and member complaints', 'Überprüfung der Bearbeitung von Beschwerden von Versicherungsnehmern und Mitgliedern', 'Revisión del tratamiento de las reclamaciones de asegurados y mutualistas', 'Revisione della gestione dei reclami di assicurati e aderenti'), 'assurance.process.policy', 'TRIMESTRIEL', 'DETECTIF', ['Recommandation ACPR 2022-R-01 du 9 mai 2022 sur le traitement des réclamations']),
  // ── Assurance — placements et réassurance
  c('ASSURANCE', 'assurance.control.investment-limits', l('Contrôle du respect de la politique de placement et des limites de concentration (principe de la personne prudente)', 'Check of compliance with the investment policy and concentration limits (prudent person principle)', 'Prüfung der Einhaltung der Anlagepolitik und der Konzentrationslimite (Grundsatz der unternehmerischen Vorsicht)', 'Control del cumplimiento de la política de inversión y de los límites de concentración (principio de prudencia)', 'Verifica del rispetto della politica di investimento e dei limiti di concentrazione (principio della persona prudente)'), 'assurance.process.investments', 'MENSUEL', 'DETECTIF', [`${S2}, art. 132`]),
  c('ASSURANCE', 'assurance.control.reinsurance', l('Revue de la couverture de réassurance et de la qualité des réassureurs', 'Review of reinsurance cover and the quality of reinsurers', 'Überprüfung des Rückversicherungsschutzes und der Qualität der Rückversicherer', 'Revisión de la cobertura de reaseguro y de la calidad de los reaseguradores', 'Revisione della copertura riassicurativa e della qualità dei riassicuratori'), 'assurance.process.investments', 'ANNUEL', 'DETECTIF', [S2]),
  // ── Assurance — LCB-FT
  c('ASSURANCE', 'assurance.control.aml-life', l('Contrôle de la connaissance client, des bénéficiaires et de la surveillance des opérations (assurance vie)', 'Check of customer and beneficiary due diligence and transaction monitoring (life insurance)', 'Prüfung von Kunden- und Begünstigtenidentifizierung und Transaktionsüberwachung (Lebensversicherung)', 'Control del conocimiento del cliente, de los beneficiarios y de la vigilancia de operaciones (seguro de vida)', 'Verifica dell’adeguata verifica di clienti e beneficiari e del monitoraggio delle operazioni (assicurazione vita)'), 'assurance.process.aml', 'TRIMESTRIEL', 'DETECTIF', [CMF_LCBFT]),
  c('ASSURANCE', 'assurance.control.asset-freeze', l('Vérification du filtrage des listes de gel des avoirs sur le portefeuille et les bénéficiaires', 'Check of asset-freeze list screening of the portfolio and beneficiaries', 'Prüfung des Abgleichs von Bestand und Begünstigten mit Listen zum Einfrieren von Vermögenswerten', 'Verificación del filtrado de cartera y beneficiarios con las listas de inmovilización de activos', 'Verifica del filtraggio di portafoglio e beneficiari con le liste di congelamento dei beni'), 'assurance.process.aml', 'MENSUEL', 'PREVENTIF', [CMF_LCBFT]),
  // ── Mutuelles — adhérents
  c('ASSURANCE', 'assurance.control.member-contributions', l('Contrôle de l’appel des cotisations et du suivi des impayés des adhérents', 'Check of contribution calls and follow-up of members’ unpaid amounts', 'Prüfung der Beitragsanforderung und der Nachverfolgung offener Mitgliedsbeiträge', 'Control de la emisión de cuotas y del seguimiento de los impagos de los mutualistas', 'Verifica della richiesta dei contributi e del monitoraggio degli insoluti degli aderenti'), 'assurance.process.members', 'MENSUEL', 'DETECTIF', [CMUT]),
  c('ASSURANCE', 'assurance.control.statutes-assembly', l('Contrôle du respect des statuts et de la préparation de l’assemblée générale (convocation, quorum, votes)', 'Check of compliance with the statutes and preparation of the general assembly (notice, quorum, votes)', 'Prüfung der Einhaltung der Satzung und der Vorbereitung der Mitgliederversammlung (Einberufung, Beschlussfähigkeit, Abstimmungen)', 'Control del cumplimiento de los estatutos y de la preparación de la asamblea general (convocatoria, quórum, votaciones)', 'Verifica del rispetto dello statuto e della preparazione dell’assemblea generale (convocazione, quorum, votazioni)'), 'assurance.process.members', 'ANNUEL', 'PREVENTIF', [CMUT]),
  c('ASSURANCE', 'assurance.control.benefits-sample', l('Contrôle par échantillon des prestations santé et prévoyance versées (droits ouverts, tiers payant)', 'Sample check of health and protection benefits paid (entitlement, third-party payment)', 'Stichprobenprüfung gezahlter Gesundheits- und Vorsorgeleistungen (Anspruch, Direktabrechnung)', 'Control por muestreo de las prestaciones de salud y previsión abonadas (derechos abiertos, tercero pagador)', 'Controllo a campione delle prestazioni sanitarie e di previdenza erogate (diritti, terzo pagante)'), 'assurance.process.members', 'MENSUEL', 'DETECTIF', [CMUT]),
  // ── Assurance — TIC et prestataires (DORA)
  c('ASSURANCE', 'assurance.control.ict-register', l('Revue du registre d’information des accords contractuels avec les prestataires de services TIC', 'Review of the register of information on contractual arrangements with ICT service providers', 'Überprüfung des Informationsregisters der vertraglichen Vereinbarungen mit IKT-Drittdienstleistern', 'Revisión del registro de información de los acuerdos contractuales con proveedores de servicios TIC', 'Revisione del registro delle informazioni sugli accordi contrattuali con i fornitori di servizi TIC'), 'assurance.process.ict', 'TRIMESTRIEL', 'DETECTIF', [DORA]),
  c('ASSURANCE', 'assurance.control.critical-providers', l('Suivi des niveaux de service et des incidents des prestataires de fonctions critiques ou importantes', 'Monitoring of service levels and incidents of providers of critical or important functions', 'Überwachung der Servicelevel und Vorfälle von Dienstleistern kritischer oder wichtiger Funktionen', 'Seguimiento de los niveles de servicio y de los incidentes de los proveedores de funciones críticas o importantes', 'Monitoraggio dei livelli di servizio e degli incidenti dei fornitori di funzioni critiche o importanti'), 'assurance.process.ict', 'TRIMESTRIEL', 'DETECTIF', [DORA, `${S2}, art. 49`]),
  c('ASSURANCE', 'assurance.control.resilience-testing', l('Suivi du programme annuel de tests de résilience opérationnelle numérique et de ses remédiations', 'Follow-up of the annual digital operational resilience testing programme and its remediation', 'Nachverfolgung des jährlichen Testprogramms zur digitalen operationalen Resilienz und seiner Behebungsmaßnahmen', 'Seguimiento del programa anual de pruebas de resiliencia operativa digital y de sus correcciones', 'Monitoraggio del programma annuale di test di resilienza operativa digitale e delle relative azioni correttive'), 'assurance.process.ict', 'TRIMESTRIEL', 'DETECTIF', [DORA]),
  c('ASSURANCE', 'assurance.control.incident-reporting-drill', l('Test de la chaîne de classification et de déclaration des incidents TIC majeurs', 'Test of the classification and reporting chain for major ICT-related incidents', 'Test der Kette zur Klassifizierung und Meldung schwerwiegender IKT-bezogener Vorfälle', 'Prueba de la cadena de clasificación y notificación de incidentes graves relacionados con las TIC', 'Test della catena di classificazione e notifica degli incidenti gravi connessi alle TIC'), 'assurance.process.ict', 'SEMESTRIEL', 'PREVENTIF', [DORA]),
]
