/**
 * Pack « Défense / Sécurité nationale » (catalogue 1.10) : industrie de défense, sous-traitants d'organismes
 * relevant de la défense, opérateurs d'importance vitale. Suggestions à qualifier (responsable, périmètre, échantillon) :
 * jamais d'exécution, de seuil, de date, de résultat ni de conformité acquise. Les `references` citent le texte
 * d'origine ; elles ne reproduisent AUCUN libellé d'exigence. Contenu à relire par un expert du secteur
 * (statut « à relire » affiché) ; le niveau de classification et les exigences contractuelles priment toujours.
 */
import { sectorPack, U_NB, U_PCT, U_DAYS } from './catalogue-pack-builder'

const IGI = 'Instruction générale interministérielle n° 1300 sur la protection du secret de la défense nationale'
const CDEF = 'Code de la défense (protection du potentiel scientifique et technique, opérateurs d’importance vitale)'
const DUAL = 'Règlement (UE) 2021/821 (biens à double usage)'
const NIS2 = 'Directive (UE) 2022/2555 (NIS 2)'

const b = sectorPack('DEFENSE')

b.process('programmes', ['Conduire les programmes et les contrats de défense', 'Run defense programmes and contracts', 'Verteidigungsprogramme und -verträge steuern', 'Dirigir los programas y contratos de defensa', 'Gestire i programmi e i contratti di difesa'])
b.process('classified', ['Protéger les informations et supports classifiés', 'Protect classified information and media', 'Verschlusssachen und Datenträger schützen', 'Proteger la información y los soportes clasificados', 'Proteggere le informazioni e i supporti classificati'])
b.process('habilitation', ['Habiliter et suivre les personnes', 'Clear and follow up personnel', 'Personal sicherheitsüberprüfen und begleiten', 'Habilitar y hacer el seguimiento del personal', 'Abilitare e seguire il personale'])
b.process('export', ['Contrôler les exportations et les transferts', 'Control exports and transfers', 'Ausfuhren und Transfers kontrollieren', 'Controlar las exportaciones y transferencias', 'Controllare le esportazioni e i trasferimenti'])
b.process('supply', ['Maîtriser la chaîne d’approvisionnement et la sous-traitance', 'Control the supply chain and subcontracting', 'Lieferkette und Unterauftragsvergabe beherrschen', 'Controlar la cadena de suministro y la subcontratación', 'Controllare la catena di fornitura e il subappalto'])
b.process('sites', ['Sécuriser les sites et les systèmes sensibles', 'Secure sensitive sites and systems', 'Sensible Standorte und Systeme sichern', 'Proteger los sitios y sistemas sensibles', 'Proteggere i siti e i sistemi sensibili'])

// ── Risques (12) ─────────────────────────────────────────────────────────────
b.risk('classified-leak', 4, ['Une information classifiée est divulguée à une personne non habilitée', 'Classified information is disclosed to an uncleared person', 'Eine Verschlusssache wird einer nicht ermächtigten Person offengelegt', 'Se divulga información clasificada a una persona no habilitada', 'Un’informazione classificata viene divulgata a una persona non abilitata'], 'classified')
b.risk('media-loss', 5, ['Un support classifié est perdu ou volé lors d’un transport', 'A classified medium is lost or stolen in transit', 'Ein Verschlusssachen-Datenträger geht beim Transport verloren oder wird gestohlen', 'Un soporte clasificado se pierde o es robado durante el transporte', 'Un supporto classificato viene perso o rubato durante il trasporto'], 'classified')
b.risk('apt-intrusion', 2, ['Une intrusion étatique ciblée exfiltre des données de conception', 'A state-sponsored intrusion exfiltrates design data', 'Ein staatlich gesteuerter Angriff entwendet Konstruktionsdaten', 'Una intrusión estatal selectiva exfiltra datos de diseño', 'Un’intrusione di matrice statale esfiltra dati di progetto'], 'sites')
b.risk('insider', 1, ['Un collaborateur habilité détourne des informations sensibles', 'A cleared employee diverts sensitive information', 'Ein ermächtigter Mitarbeiter entwendet sensible Informationen', 'Un empleado habilitado desvía información sensible', 'Un dipendente abilitato sottrae informazioni sensibili'], 'habilitation')
b.risk('expired-clearance', 7, ['Une personne accède à des informations avec une habilitation échue', 'A person accesses information with an expired clearance', 'Eine Person greift mit abgelaufener Ermächtigung auf Informationen zu', 'Una persona accede a información con una habilitación caducada', 'Una persona accede a informazioni con un’abilitazione scaduta'], 'habilitation')
b.risk('unauthorised-export', 7, ['Un bien ou une technologie sensible est exporté sans autorisation', 'A sensitive good or technology is exported without authorisation', 'Ein sensibles Gut oder eine Technologie wird ohne Genehmigung ausgeführt', 'Un bien o tecnología sensible se exporta sin autorización', 'Un bene o una tecnologia sensibile viene esportato senza autorizzazione'], 'export')
b.risk('supplier-compromise', 2, ['Un sous-traitant compromis sert de vecteur d’attaque', 'A compromised subcontractor becomes an attack vector', 'Ein kompromittierter Unterauftragnehmer dient als Angriffsvektor', 'Un subcontratista comprometido sirve de vector de ataque', 'Un subappaltatore compromesso diventa vettore di attacco'], 'supply')
b.risk('counterfeit', 7, ['Un composant contrefait ou altéré est intégré à un équipement', 'A counterfeit or tampered component is built into equipment', 'Ein gefälschtes oder manipuliertes Bauteil wird in ein Gerät eingebaut', 'Un componente falsificado o alterado se integra en un equipo', 'Un componente contraffatto o alterato viene integrato in un’apparecchiatura'], 'supply')
b.risk('site-intrusion', 5, ['Une personne non autorisée pénètre dans une zone protégée', 'An unauthorised person enters a protected area', 'Eine unbefugte Person betritt einen geschützten Bereich', 'Una persona no autorizada entra en una zona protegida', 'Una persona non autorizzata entra in un’area protetta'], 'sites')
b.risk('isolated-network', 6, ['Un réseau cloisonné est relié par erreur à un réseau non maîtrisé', 'An isolated network is connected by mistake to an uncontrolled network', 'Ein abgeschottetes Netz wird versehentlich mit einem nicht beherrschten Netz verbunden', 'Una red aislada se conecta por error a una red no controlada', 'Una rete isolata viene collegata per errore a una rete non controllata'], 'sites')
b.risk('programme-delay', 7, ['Un jalon de programme est manqué faute de capacité ou de pièces', 'A programme milestone is missed for lack of capacity or parts', 'Ein Programm-Meilenstein wird mangels Kapazität oder Teilen verfehlt', 'Se incumple un hito del programa por falta de capacidad o piezas', 'Una milestone di programma viene mancata per mancanza di capacità o di componenti'], 'programmes')
b.risk('key-skill', 3, ['Une compétence rare habilitée devient indisponible sans relève', 'A rare cleared skill becomes unavailable without backup', 'Eine seltene ermächtigte Kompetenz fällt ohne Vertretung aus', 'Una competencia rara habilitada deja de estar disponible sin relevo', 'Una competenza rara abilitata diventa indisponibile senza sostituto'], 'habilitation')

// ── Contrôles (20) ───────────────────────────────────────────────────────────
b.control('classified-inventory', ['Inventaire et rapprochement des supports classifiés détenus', 'Inventory and reconciliation of classified media held', 'Bestandsaufnahme und Abgleich der gehaltenen Verschlusssachen-Datenträger', 'Inventario y conciliación de los soportes clasificados en custodia', 'Inventario e riconciliazione dei supporti classificati detenuti'], 'classified', 'SEMESTRIEL', 'DETECTIF', ['classified-leak', 'media-loss'], [IGI])
b.control('need-to-know', ['Revue des listes d’accès aux informations classifiées (besoin d’en connaître)', 'Review of access lists to classified information (need to know)', 'Überprüfung der Zugangslisten zu Verschlusssachen (Kenntnis nur bei Bedarf)', 'Revisión de las listas de acceso a información clasificada (necesidad de conocer)', 'Revisione degli elenchi di accesso alle informazioni classificate (necessità di sapere)'], 'classified', 'TRIMESTRIEL', 'DETECTIF', ['classified-leak', 'insider'], [IGI])
b.control('transport-chain', ['Contrôle par échantillon de la chaîne de transport des supports classifiés', 'Sample check of the transport chain for classified media', 'Stichprobenprüfung der Transportkette für Verschlusssachen-Datenträger', 'Control por muestreo de la cadena de transporte de soportes clasificados', 'Controllo a campione della catena di trasporto dei supporti classificati'], 'classified', 'TRIMESTRIEL', 'DETECTIF', ['media-loss'], [IGI])
b.control('destruction', ['Vérification de la destruction tracée des supports en fin de vie', 'Check of traced destruction of end-of-life media', 'Prüfung der nachgewiesenen Vernichtung ausgesonderter Datenträger', 'Verificación de la destrucción trazada de los soportes al final de su vida útil', 'Verifica della distruzione tracciata dei supporti a fine vita'], 'classified', 'SEMESTRIEL', 'DETECTIF', ['classified-leak'], [IGI])
b.control('clearance-expiry', ['Suivi des échéances d’habilitation et retrait des accès à l’échéance', 'Follow-up of clearance expiry dates and removal of access on expiry', 'Überwachung der Ablauftermine von Ermächtigungen und Entzug der Zugänge bei Ablauf', 'Seguimiento de los vencimientos de habilitación y retirada de accesos al vencimiento', 'Monitoraggio delle scadenze delle abilitazioni e rimozione degli accessi alla scadenza'], 'habilitation', 'MENSUEL', 'PREVENTIF', ['expired-clearance'], [IGI])
b.control('clearance-need', ['Revue de la justification des habilitations par poste', 'Review of the justification of clearances per position', 'Überprüfung der Begründung von Ermächtigungen je Stelle', 'Revisión de la justificación de las habilitaciones por puesto', 'Revisione della giustificazione delle abilitazioni per posizione'], 'habilitation', 'ANNUEL', 'DETECTIF', ['expired-clearance', 'insider'], [IGI])
b.control('awareness', ['Vérification du suivi de la sensibilisation à la protection du secret', 'Check that secrecy-protection awareness has been completed', 'Prüfung der Teilnahme an der Geheimschutz-Sensibilisierung', 'Verificación del seguimiento de la sensibilización sobre protección del secreto', 'Verifica della partecipazione alla sensibilizzazione sulla protezione del segreto'], 'habilitation', 'ANNUEL', 'PREVENTIF', ['classified-leak', 'insider'])
b.control('departure-debrief', ['Contrôle du débriefing et du retrait des accès au départ d’un collaborateur habilité', 'Check of debriefing and access removal when a cleared employee leaves', 'Prüfung der Abschlussbelehrung und des Zugangsentzugs beim Ausscheiden ermächtigter Mitarbeiter', 'Control de la reunión informativa y de la retirada de accesos a la salida de un empleado habilitado', 'Controllo del debriefing e della rimozione degli accessi all’uscita di un dipendente abilitato'], 'habilitation', 'MENSUEL', 'DETECTIF', ['insider', 'expired-clearance'])
b.control('export-licence', ['Contrôle des licences d’exportation avant chaque expédition ou transfert', 'Check of export licences before each shipment or transfer', 'Prüfung der Ausfuhrgenehmigungen vor jeder Lieferung oder Übermittlung', 'Control de las licencias de exportación antes de cada envío o transferencia', 'Controllo delle licenze di esportazione prima di ogni spedizione o trasferimento'], 'export', 'MENSUEL', 'PREVENTIF', ['unauthorised-export'], [DUAL])
b.control('technical-data-transfer', ['Revue des transferts de données techniques vers l’étranger', 'Review of technical data transfers abroad', 'Überprüfung von Übermittlungen technischer Daten ins Ausland', 'Revisión de las transferencias de datos técnicos al extranjero', 'Revisione dei trasferimenti di dati tecnici verso l’estero'], 'export', 'TRIMESTRIEL', 'DETECTIF', ['unauthorised-export', 'classified-leak'], [DUAL])
b.control('end-use', ['Vérification des certificats d’utilisation finale reçus', 'Check of end-use certificates received', 'Prüfung der eingegangenen Endverbleibserklärungen', 'Verificación de los certificados de uso final recibidos', 'Verifica dei certificati di uso finale ricevuti'], 'export', 'TRIMESTRIEL', 'DETECTIF', ['unauthorised-export'], [DUAL])
b.control('subcontractor-flowdown', ['Vérification de la répercussion des clauses de sécurité chez les sous-traitants', 'Check that security clauses are passed down to subcontractors', 'Prüfung der Weitergabe von Sicherheitsklauseln an Unterauftragnehmer', 'Verificación del traslado de las cláusulas de seguridad a los subcontratistas', 'Verifica del recepimento delle clausole di sicurezza da parte dei subappaltatori'], 'supply', 'ANNUEL', 'PREVENTIF', ['supplier-compromise', 'classified-leak'])
b.control('supplier-assessment', ['Évaluation de sécurité des fournisseurs de rang 1 sensibles', 'Security assessment of sensitive tier-1 suppliers', 'Sicherheitsbewertung sensibler Lieferanten der ersten Ebene', 'Evaluación de seguridad de los proveedores sensibles de primer nivel', 'Valutazione di sicurezza dei fornitori sensibili di primo livello'], 'supply', 'ANNUEL', 'DETECTIF', ['supplier-compromise'], [NIS2])
b.control('component-provenance', ['Contrôle par échantillon de la provenance et de l’intégrité des composants critiques', 'Sample check of provenance and integrity of critical components', 'Stichprobenprüfung von Herkunft und Integrität kritischer Bauteile', 'Control por muestreo de la procedencia e integridad de los componentes críticos', 'Controllo a campione della provenienza e dell’integrità dei componenti critici'], 'supply', 'TRIMESTRIEL', 'DETECTIF', ['counterfeit'])
b.control('physical-access-log', ['Revue des journaux d’accès aux zones protégées', 'Review of access logs to protected areas', 'Überprüfung der Zutrittsprotokolle zu geschützten Bereichen', 'Revisión de los registros de acceso a las zonas protegidas', 'Revisione dei registri di accesso alle aree protette'], 'sites', 'MENSUEL', 'DETECTIF', ['site-intrusion'], [CDEF])
b.control('visitor-escort', ['Contrôle par échantillon de l’accompagnement des visiteurs en zone sensible', 'Sample check of visitor escorting in sensitive areas', 'Stichprobenprüfung der Besucherbegleitung in sensiblen Bereichen', 'Control por muestreo del acompañamiento de visitantes en zonas sensibles', 'Controllo a campione dell’accompagnamento dei visitatori nelle aree sensibili'], 'sites', 'TRIMESTRIEL', 'DETECTIF', ['site-intrusion'])
b.control('network-isolation', ['Vérification du cloisonnement des réseaux sensibles', 'Check of isolation of sensitive networks', 'Überprüfung der Abschottung sensibler Netze', 'Verificación del aislamiento de las redes sensibles', 'Verifica dell’isolamento delle reti sensibili'], 'sites', 'TRIMESTRIEL', 'DETECTIF', ['isolated-network', 'apt-intrusion'])
b.control('removable-media', ['Contrôle de l’usage des supports amovibles sur les postes sensibles', 'Check of removable-media use on sensitive workstations', 'Kontrolle der Nutzung von Wechseldatenträgern auf sensiblen Arbeitsplätzen', 'Control del uso de soportes extraíbles en puestos sensibles', 'Controllo dell’uso di supporti rimovibili sulle postazioni sensibili'], 'sites', 'MENSUEL', 'DETECTIF', ['classified-leak', 'apt-intrusion'])
b.control('threat-hunting', ['Revue des alertes de détection ciblant les données de conception', 'Review of detection alerts targeting design data', 'Überprüfung von Erkennungswarnungen zu Konstruktionsdaten', 'Revisión de las alertas de detección sobre datos de diseño', 'Revisione degli alert di rilevamento sui dati di progetto'], 'sites', 'MENSUEL', 'DETECTIF', ['apt-intrusion'])
b.control('programme-milestones', ['Revue des jalons de programme et des dépendances critiques', 'Review of programme milestones and critical dependencies', 'Überprüfung der Programm-Meilensteine und kritischen Abhängigkeiten', 'Revisión de los hitos del programa y de las dependencias críticas', 'Revisione delle milestone di programma e delle dipendenze critiche'], 'programmes', 'MENSUEL', 'DETECTIF', ['programme-delay'])

// ── Indicateurs (8) ──────────────────────────────────────────────────────────
b.kri('expiring-clearances', ['Habilitations arrivant à échéance sans renouvellement engagé', 'Clearances nearing expiry with no renewal started', 'Ablaufende Ermächtigungen ohne eingeleitete Verlängerung', 'Habilitaciones próximas a caducar sin renovación iniciada', 'Abilitazioni in scadenza senza rinnovo avviato'], 'habilitation', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('media-discrepancies', ['Écarts d’inventaire des supports classifiés', 'Classified media inventory discrepancies', 'Abweichungen bei der Bestandsaufnahme von Verschlusssachen-Datenträgern', 'Diferencias de inventario de soportes clasificados', 'Discrepanze nell’inventario dei supporti classificati'], 'classified', U_NB, 'HAUSSE', 'TRIMESTRIEL')
b.kri('security-events', ['Événements de sécurité relatifs à la protection du secret déclarés', 'Reported security events relating to secrecy protection', 'Gemeldete Sicherheitsereignisse zum Geheimschutz', 'Eventos de seguridad notificados relativos a la protección del secreto', 'Eventi di sicurezza segnalati relativi alla protezione del segreto'], 'classified', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('suppliers-unassessed', ['Fournisseurs sensibles sans évaluation de sécurité à jour', 'Sensitive suppliers without an up-to-date security assessment', 'Sensible Lieferanten ohne aktuelle Sicherheitsbewertung', 'Proveedores sensibles sin evaluación de seguridad actualizada', 'Fornitori sensibili senza valutazione di sicurezza aggiornata'], 'supply', U_NB, 'HAUSSE', 'SEMESTRIEL')
b.kri('export-without-licence', ['Expéditions sans licence ou autorisation vérifiée avant départ', 'Shipments without a licence or authorisation checked before dispatch', 'Lieferungen ohne vor Versand geprüfte Genehmigung', 'Envíos sin licencia o autorización verificada antes de la salida', 'Spedizioni senza licenza o autorizzazione verificata prima della partenza'], 'export', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('unreviewed-access', ['Habilitations sans revue du besoin d’en connaître depuis plus d’un an', 'Clearances without a need-to-know review for over a year', 'Ermächtigungen ohne Bedarfsprüfung seit über einem Jahr', 'Habilitaciones sin revisión de la necesidad de conocer desde hace más de un año', 'Abilitazioni senza revisione della necessità di sapere da oltre un anno'], 'habilitation', U_PCT, 'HAUSSE', 'TRIMESTRIEL')
b.kri('zone-breaches', ['Anomalies d’accès aux zones protégées constatées', 'Access anomalies in protected areas found', 'Festgestellte Zutrittsanomalien in geschützten Bereichen', 'Anomalías de acceso a zonas protegidas detectadas', 'Anomalie di accesso alle aree protette rilevate'], 'sites', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('milestone-slip', ['Retard moyen des jalons de programme', 'Average slippage of programme milestones', 'Durchschnittliche Verzögerung der Programm-Meilensteine', 'Retraso medio de los hitos del programa', 'Ritardo medio delle milestone di programma'], 'programmes', U_DAYS, 'HAUSSE', 'MENSUEL')

// ── Missions d’audit (4) ─────────────────────────────────────────────────────
b.audit('classified-handling', ['Audit de la protection des supports classifiés', 'Audit of the protection of classified media', 'Audit des Schutzes von Verschlusssachen-Datenträgern', 'Auditoría de la protección de los soportes clasificados', 'Audit della protezione dei supporti classificati'], 'classified', ['classified-leak', 'media-loss'], [
  ['Les supports classifiés sont inventoriés, localisés et rapprochés régulièrement', 'Classified media are inventoried, located and reconciled regularly', 'Verschlusssachen-Datenträger werden erfasst, lokalisiert und regelmäßig abgeglichen', 'Los soportes clasificados se inventarían, localizan y concilian regularmente', 'I supporti classificati sono inventariati, localizzati e riconciliati regolarmente'],
  ['Les accès sont limités aux personnes habilitées ayant le besoin d’en connaître', 'Access is limited to cleared persons with a need to know', 'Der Zugang ist auf ermächtigte Personen mit Kenntnisbedarf beschränkt', 'El acceso se limita a las personas habilitadas con necesidad de conocer', 'L’accesso è limitato alle persone abilitate con necessità di sapere'],
  ['Le transport et la destruction des supports sont tracés et autorisés', 'Transport and destruction of media are traced and authorised', 'Transport und Vernichtung der Datenträger sind nachvollziehbar und genehmigt', 'El transporte y la destrucción de los soportes están trazados y autorizados', 'Il trasporto e la distruzione dei supporti sono tracciati e autorizzati'],
  ['Les incidents et pertes sont signalés dans les délais prévus', 'Incidents and losses are reported within the prescribed time', 'Vorfälle und Verluste werden fristgerecht gemeldet', 'Los incidentes y pérdidas se notifican en los plazos previstos', 'Gli incidenti e le perdite sono segnalati nei termini previsti'],
])
b.audit('clearance-lifecycle', ['Audit du cycle de vie des habilitations', 'Audit of the clearance lifecycle', 'Audit des Lebenszyklus der Ermächtigungen', 'Auditoría del ciclo de vida de las habilitaciones', 'Audit del ciclo di vita delle abilitazioni'], 'habilitation', ['expired-clearance', 'insider'], [
  ['Chaque habilitation est justifiée par le poste et approuvée par la bonne autorité', 'Each clearance is justified by the position and approved by the right authority', 'Jede Ermächtigung ist durch die Stelle begründet und von der zuständigen Stelle genehmigt', 'Cada habilitación está justificada por el puesto y aprobada por la autoridad adecuada', 'Ogni abilitazione è giustificata dalla posizione e approvata dall’autorità competente'],
  ['Les échéances sont suivies et les accès retirés à l’échéance', 'Expiry dates are tracked and access removed on expiry', 'Ablauftermine werden überwacht und Zugänge bei Ablauf entzogen', 'Los vencimientos se siguen y los accesos se retiran al vencimiento', 'Le scadenze sono monitorate e gli accessi rimossi alla scadenza'],
  ['Les départs et mutations déclenchent un débriefing et un retrait des accès', 'Departures and transfers trigger a debriefing and access removal', 'Abgänge und Versetzungen lösen Abschlussbelehrung und Zugangsentzug aus', 'Las salidas y traslados activan una reunión informativa y la retirada de accesos', 'Le uscite e i trasferimenti attivano un debriefing e la rimozione degli accessi'],
  ['La sensibilisation est réalisée et son suivi est conservé', 'Awareness training is delivered and its follow-up retained', 'Sensibilisierungen werden durchgeführt und nachgehalten', 'La sensibilización se realiza y se conserva su seguimiento', 'La sensibilizzazione è svolta e il suo monitoraggio conservato'],
])
b.audit('export-control', ['Audit du contrôle des exportations et des transferts', 'Audit of export and transfer control', 'Audit der Ausfuhr- und Transferkontrolle', 'Auditoría del control de exportaciones y transferencias', 'Audit del controllo di esportazioni e trasferimenti'], 'export', ['unauthorised-export'], [
  ['Les biens et technologies sont classés avant toute expédition ou transfert', 'Goods and technologies are classified before any shipment or transfer', 'Güter und Technologien werden vor Lieferung oder Übermittlung eingestuft', 'Los bienes y tecnologías se clasifican antes de cualquier envío o transferencia', 'I beni e le tecnologie sono classificati prima di ogni spedizione o trasferimento'],
  ['Les licences sont obtenues, suivies et leurs conditions respectées', 'Licences are obtained, followed and their conditions respected', 'Genehmigungen werden eingeholt, nachverfolgt und ihre Auflagen eingehalten', 'Las licencias se obtienen, se siguen y se respetan sus condiciones', 'Le licenze sono ottenute, seguite e le loro condizioni rispettate'],
  ['Les transferts immatériels de données techniques sont contrôlés', 'Intangible transfers of technical data are controlled', 'Immaterielle Übermittlungen technischer Daten werden kontrolliert', 'Las transferencias inmateriales de datos técnicos están controladas', 'I trasferimenti immateriali di dati tecnici sono controllati'],
  ['Les registres sont conservés et accessibles aux autorités', 'Records are kept and available to the authorities', 'Aufzeichnungen werden aufbewahrt und den Behörden zugänglich gemacht', 'Los registros se conservan y están a disposición de las autoridades', 'I registri sono conservati e accessibili alle autorità'],
])
b.audit('supply-chain', ['Audit de la maîtrise de la chaîne d’approvisionnement sensible', 'Audit of sensitive supply-chain control', 'Audit der Beherrschung der sensiblen Lieferkette', 'Auditoría del control de la cadena de suministro sensible', 'Audit del controllo della catena di fornitura sensibile'], 'supply', ['supplier-compromise', 'counterfeit'], [
  ['Les fournisseurs sensibles sont identifiés et évalués avant contractualisation', 'Sensitive suppliers are identified and assessed before contracting', 'Sensible Lieferanten werden vor Vertragsschluss identifiziert und bewertet', 'Los proveedores sensibles se identifican y evalúan antes de contratar', 'I fornitori sensibili sono identificati e valutati prima della contrattualizzazione'],
  ['Les exigences de sécurité sont répercutées dans les contrats et la sous-traitance en cascade', 'Security requirements are passed down in contracts and cascading subcontracting', 'Sicherheitsanforderungen sind in Verträgen und in der Unterauftragskette weitergegeben', 'Los requisitos de seguridad se trasladan a los contratos y a la subcontratación en cascada', 'I requisiti di sicurezza sono trasferiti nei contratti e nel subappalto a cascata'],
  ['L’intégrité et la provenance des composants critiques sont vérifiées', 'Integrity and provenance of critical components are verified', 'Integrität und Herkunft kritischer Bauteile werden geprüft', 'Se verifican la integridad y la procedencia de los componentes críticos', 'L’integrità e la provenienza dei componenti critici sono verificate'],
  ['Les écarts constatés chez un fournisseur donnent lieu à un plan d’action suivi', 'Gaps found at a supplier lead to a tracked action plan', 'Bei einem Lieferanten festgestellte Abweichungen führen zu einem nachverfolgten Maßnahmenplan', 'Las desviaciones detectadas en un proveedor dan lugar a un plan de acción con seguimiento', 'Le non conformità rilevate presso un fornitore danno luogo a un piano d’azione monitorato'],
])

export const DEFENSE_PACK = b.pack
