/**
 * Pack « Éducation / Recherche » (catalogue 1.10) : établissements d'enseignement, universités, organismes de recherche.
 * Suggestions à qualifier : jamais d'exécution, de seuil, de date, de résultat ni de conformité acquise. Les `references`
 * citent le texte d'origine sans reproduire d'exigence. Contenu à relire par un expert du secteur (statut « à relire »).
 */
import { sectorPack, U_NB, U_PCT, U_DAYS } from './catalogue-pack-builder'

const RGPD = 'Règlement (UE) 2016/679 (RGPD)'
const PPST = 'Dispositif de protection du potentiel scientifique et technique de la nation (PPST)'

const b = sectorPack('EDUCATION')

b.process('teaching', ['Dispenser les enseignements et suivre la scolarité', 'Deliver teaching and follow student progress', 'Lehre durchführen und Studienverlauf begleiten', 'Impartir la enseñanza y seguir la escolaridad', 'Erogare la didattica e seguire la carriera degli studenti'])
b.process('exams', ['Organiser les examens et délivrer les diplômes', 'Run examinations and award qualifications', 'Prüfungen organisieren und Abschlüsse vergeben', 'Organizar los exámenes y expedir los títulos', 'Organizzare gli esami e rilasciare i titoli'])
b.process('research', ['Conduire la recherche et protéger les données de recherche', 'Conduct research and protect research data', 'Forschung betreiben und Forschungsdaten schützen', 'Realizar la investigación y proteger los datos de investigación', 'Condurre la ricerca e proteggere i dati di ricerca'])
b.process('students', ['Accueillir les étudiants et gérer leurs données', 'Admit students and manage their data', 'Studierende aufnehmen und ihre Daten verwalten', 'Acoger a los estudiantes y gestionar sus datos', 'Accogliere gli studenti e gestire i loro dati'])
b.process('campus-it', ['Exploiter le système d’information et les services numériques du campus', 'Operate the campus information system and digital services', 'Campus-Informationssystem und digitale Dienste betreiben', 'Operar el sistema de información y los servicios digitales del campus', 'Gestire il sistema informativo e i servizi digitali del campus'])
b.process('partners', ['Gérer les partenariats, financements et la valorisation', 'Manage partnerships, funding and technology transfer', 'Partnerschaften, Finanzierung und Verwertung steuern', 'Gestionar las alianzas, la financiación y la valorización', 'Gestire partnership, finanziamenti e valorizzazione'])

b.risk('student-data-leak', 4, ['Des données d’étudiants ou de mineurs sont divulguées', 'Student or minors’ data is disclosed', 'Daten von Studierenden oder Minderjährigen werden offengelegt', 'Se divulgan datos de estudiantes o menores', 'Vengono divulgati dati di studenti o minori'], 'students')
b.risk('exam-cheating', 1, ['Un sujet d’examen est divulgué avant l’épreuve', 'An exam paper is leaked before the test', 'Eine Prüfungsaufgabe wird vor der Prüfung bekannt', 'Un examen se filtra antes de la prueba', 'Un testo d’esame viene divulgato prima della prova'], 'exams')
b.risk('grade-tampering', 1, ['Des notes ou des diplômes sont modifiés frauduleusement', 'Grades or diplomas are fraudulently altered', 'Noten oder Abschlüsse werden betrügerisch verändert', 'Se modifican fraudulentamente notas o títulos', 'Voti o diplomi vengono modificati fraudolentemente'], 'exams')
b.risk('ransomware-campus', 2, ['Un rançongiciel paralyse l’ENT, la messagerie et la scolarité', 'Ransomware paralyses the learning environment, email and registry', 'Ransomware legt Lernplattform, E-Mail und Studierendenverwaltung lahm', 'Un ransomware paraliza el entorno digital, el correo y la secretaría', 'Un ransomware paralizza l’ambiente digitale, la posta e la segreteria'], 'campus-it')
b.risk('research-theft', 2, ['Des résultats de recherche sensibles sont exfiltrés avant publication ou dépôt de brevet', 'Sensitive research results are exfiltrated before publication or patent filing', 'Sensible Forschungsergebnisse werden vor Veröffentlichung oder Patentanmeldung entwendet', 'Resultados de investigación sensibles se exfiltran antes de publicarlos o patentarlos', 'Risultati di ricerca sensibili vengono esfiltrati prima della pubblicazione o del deposito del brevetto'], 'research')
b.risk('research-integrity', 7, ['Des données de recherche sont perdues ou altérées sans possibilité de reproduire les résultats', 'Research data is lost or altered so results cannot be reproduced', 'Forschungsdaten gehen verloren oder werden verändert, sodass Ergebnisse nicht reproduzierbar sind', 'Se pierden o alteran datos de investigación y los resultados no son reproducibles', 'I dati di ricerca vengono persi o alterati e i risultati non sono riproducibili'], 'research')
b.risk('open-network', 2, ['Un équipement non géré du réseau ouvert sert de point d’entrée', 'An unmanaged device on the open network serves as an entry point', 'Ein nicht verwaltetes Gerät im offenen Netz dient als Einfallstor', 'Un equipo no gestionado de la red abierta sirve de punto de entrada', 'Un dispositivo non gestito della rete aperta funge da punto di ingresso'], 'campus-it')
b.risk('account-reuse', 2, ['Des comptes d’étudiants ou de chercheurs sont usurpés par hameçonnage', 'Student or researcher accounts are hijacked through phishing', 'Konten von Studierenden oder Forschenden werden durch Phishing übernommen', 'Se usurpan cuentas de estudiantes o investigadores mediante phishing', 'Gli account di studenti o ricercatori vengono sottratti tramite phishing'], 'campus-it')
b.risk('grant-misuse', 1, ['Un financement de recherche est utilisé hors des conditions de la convention', 'Research funding is used outside the terms of the agreement', 'Fördermittel werden außerhalb der Vertragsbedingungen verwendet', 'Una financiación de investigación se utiliza fuera de las condiciones del convenio', 'Un finanziamento di ricerca viene utilizzato al di fuori delle condizioni della convenzione'], 'partners')
b.risk('partner-leak', 4, ['Un partenaire académique ou industriel diffuse des données partagées', 'An academic or industrial partner releases shared data', 'Ein akademischer oder industrieller Partner gibt gemeinsam genutzte Daten weiter', 'Un socio académico o industrial difunde datos compartidos', 'Un partner accademico o industriale diffonde dati condivisi'], 'partners')
b.risk('safety-lab', 3, ['Un accident de laboratoire touche des personnes ou interrompt des travaux', 'A laboratory accident harms people or halts work', 'Ein Laborunfall gefährdet Personen oder unterbricht Arbeiten', 'Un accidente de laboratorio afecta a personas o interrumpe los trabajos', 'Un incidente di laboratorio colpisce persone o interrompe i lavori'], 'research')
b.risk('enrolment-outage', 6, ['Une indisponibilité du système d’inscription survient en période de rentrée', 'The enrolment system is unavailable during the intake period', 'Das Einschreibesystem fällt in der Einschreibephase aus', 'El sistema de matrícula no está disponible durante el periodo de inscripción', 'Il sistema di iscrizione non è disponibile nel periodo delle iscrizioni'], 'students')

b.control('student-access-review', ['Revue des accès aux dossiers d’étudiants', 'Review of access to student records', 'Überprüfung der Zugriffe auf Studierendenakten', 'Revisión de los accesos a los expedientes de estudiantes', 'Revisione degli accessi ai fascicoli degli studenti'], 'students', 'TRIMESTRIEL', 'DETECTIF', ['student-data-leak'], [RGPD])
b.control('minors-data', ['Vérification des durées de conservation des données d’étudiants et de mineurs', 'Check of retention periods for student and minors’ data', 'Prüfung der Aufbewahrungsfristen für Daten von Studierenden und Minderjährigen', 'Verificación de los plazos de conservación de datos de estudiantes y menores', 'Verifica dei tempi di conservazione dei dati di studenti e minori'], 'students', 'ANNUEL', 'DETECTIF', ['student-data-leak'], [RGPD])
b.control('processors', ['Vérification des clauses de protection des données des prestataires de services numériques éducatifs', 'Check of data-protection clauses of educational digital-service providers', 'Prüfung der Datenschutzklauseln digitaler Bildungsdienstleister', 'Verificación de las cláusulas de protección de datos de los proveedores de servicios digitales educativos', 'Verifica delle clausole di protezione dei dati dei fornitori di servizi digitali didattici'], 'students', 'ANNUEL', 'PREVENTIF', ['student-data-leak', 'partner-leak'], [RGPD])
b.control('enrolment-failover', ['Test du mode dégradé d’inscription avant la période de rentrée', 'Test of the fallback enrolment procedure before the intake period', 'Test des Notbetriebs der Einschreibung vor der Einschreibephase', 'Prueba del modo degradado de matrícula antes del periodo de inscripción', 'Test della procedura di iscrizione degradata prima del periodo delle iscrizioni'], 'students', 'ANNUEL', 'PREVENTIF', ['enrolment-outage'])
b.control('exam-paper-custody', ['Contrôle de la chaîne de garde des sujets d’examen', 'Check of the chain of custody of exam papers', 'Prüfung der Verwahrkette der Prüfungsaufgaben', 'Control de la cadena de custodia de los exámenes', 'Controllo della catena di custodia dei testi d’esame'], 'exams', 'SEMESTRIEL', 'PREVENTIF', ['exam-cheating'])
b.control('grade-changes', ['Revue des modifications de notes après publication', 'Review of grade changes after publication', 'Überprüfung von Notenänderungen nach Veröffentlichung', 'Revisión de las modificaciones de notas tras la publicación', 'Revisione delle modifiche ai voti dopo la pubblicazione'], 'exams', 'MENSUEL', 'DETECTIF', ['grade-tampering'])
b.control('diploma-register', ['Rapprochement du registre des diplômes délivrés avec les décisions de jury', 'Reconciliation of the diploma register with jury decisions', 'Abgleich des Abschlussregisters mit den Prüfungsausschussbeschlüssen', 'Conciliación del registro de títulos expedidos con las decisiones del tribunal', 'Riconciliazione del registro dei diplomi rilasciati con le decisioni della commissione'], 'exams', 'ANNUEL', 'DETECTIF', ['grade-tampering'])
b.control('remote-exam', ['Contrôle par échantillon des conditions de surveillance des examens à distance', 'Sample check of invigilation conditions for remote exams', 'Stichprobenprüfung der Aufsichtsbedingungen bei Fernprüfungen', 'Control por muestreo de las condiciones de vigilancia de los exámenes a distancia', 'Controllo a campione delle condizioni di sorveglianza degli esami a distanza'], 'exams', 'SEMESTRIEL', 'DETECTIF', ['exam-cheating'])
b.control('research-data-backup', ['Test de restauration des données de recherche', 'Restoration test of research data', 'Wiederherstellungstest der Forschungsdaten', 'Prueba de restauración de los datos de investigación', 'Test di ripristino dei dati di ricerca'], 'research', 'SEMESTRIEL', 'DETECTIF', ['research-integrity'])
b.control('sensitive-labs', ['Revue des accès aux laboratoires et données sensibles (zones à régime restrictif)', 'Review of access to sensitive laboratories and data (restricted zones)', 'Überprüfung der Zugänge zu sensiblen Laboren und Daten (Zonen mit Zugangsbeschränkung)', 'Revisión de los accesos a laboratorios y datos sensibles (zonas restringidas)', 'Revisione degli accessi a laboratori e dati sensibili (zone a regime restrittivo)'], 'research', 'TRIMESTRIEL', 'DETECTIF', ['research-theft'], [PPST])
b.control('foreign-collab', ['Examen des collaborations et accueils de chercheurs étrangers sur les domaines sensibles', 'Review of collaborations and visiting foreign researchers in sensitive fields', 'Prüfung von Kooperationen und Gastforschenden aus dem Ausland in sensiblen Bereichen', 'Examen de las colaboraciones y acogidas de investigadores extranjeros en ámbitos sensibles', 'Esame delle collaborazioni e degli ospiti ricercatori stranieri in ambiti sensibili'], 'research', 'SEMESTRIEL', 'PREVENTIF', ['research-theft'], [PPST])
b.control('lab-notebook', ['Contrôle par échantillon de la traçabilité des cahiers de laboratoire et jeux de données', 'Sample check of lab-notebook and dataset traceability', 'Stichprobenprüfung der Nachvollziehbarkeit von Laborbüchern und Datensätzen', 'Control por muestreo de la trazabilidad de los cuadernos de laboratorio y conjuntos de datos', 'Controllo a campione della tracciabilità dei quaderni di laboratorio e dei dataset'], 'research', 'ANNUEL', 'DETECTIF', ['research-integrity'])
b.control('lab-safety-inspection', ['Vérification des inspections de sécurité des laboratoires', 'Check of laboratory safety inspections', 'Prüfung der Sicherheitsbegehungen der Labore', 'Verificación de las inspecciones de seguridad de los laboratorios', 'Verifica delle ispezioni di sicurezza dei laboratori'], 'research', 'SEMESTRIEL', 'DETECTIF', ['safety-lab'])
b.control('mfa-accounts', ['Vérification de l’authentification renforcée des comptes à privilèges et de recherche', 'Check of strong authentication for privileged and research accounts', 'Prüfung der starken Authentifizierung privilegierter Konten und Forschungskonten', 'Verificación de la autenticación reforzada de las cuentas privilegiadas y de investigación', 'Verifica dell’autenticazione forte per gli account privilegiati e di ricerca'], 'campus-it', 'TRIMESTRIEL', 'DETECTIF', ['account-reuse'])
b.control('unmanaged-devices', ['Détection des équipements non gérés sur le réseau', 'Detection of unmanaged devices on the network', 'Erkennung nicht verwalteter Geräte im Netz', 'Detección de equipos no gestionados en la red', 'Rilevamento dei dispositivi non gestiti sulla rete'], 'campus-it', 'MENSUEL', 'DETECTIF', ['open-network'])
b.control('phishing-awareness', ['Exercice de sensibilisation à l’hameçonnage pour étudiants et personnels', 'Phishing awareness exercise for students and staff', 'Phishing-Sensibilisierungsübung für Studierende und Beschäftigte', 'Ejercicio de sensibilización sobre phishing para estudiantes y personal', 'Esercitazione di sensibilizzazione sul phishing per studenti e personale'], 'campus-it', 'SEMESTRIEL', 'PREVENTIF', ['account-reuse', 'ransomware-campus'])
b.control('learning-platform-backup', ['Test de reprise des plateformes pédagogiques et de la scolarité', 'Recovery test of learning platforms and student registry', 'Wiederanlauftest von Lernplattformen und Studierendenverwaltung', 'Prueba de recuperación de las plataformas pedagógicas y de la secretaría', 'Test di ripristino delle piattaforme didattiche e della segreteria'], 'campus-it', 'SEMESTRIEL', 'DETECTIF', ['ransomware-campus'])
b.control('funding-eligibility', ['Contrôle par échantillon de l’éligibilité des dépenses imputées aux financements de recherche', 'Sample check of eligibility of expenses charged to research funding', 'Stichprobenprüfung der Förderfähigkeit von Ausgaben auf Forschungsmittel', 'Control por muestreo de la elegibilidad de los gastos imputados a financiación de investigación', 'Controllo a campione dell’ammissibilità delle spese imputate ai finanziamenti di ricerca'], 'partners', 'TRIMESTRIEL', 'DETECTIF', ['grant-misuse'])
b.control('partner-agreements', ['Vérification des clauses de confidentialité et de propriété intellectuelle des conventions de partenariat', 'Check of confidentiality and IP clauses in partnership agreements', 'Prüfung der Vertraulichkeits- und IP-Klauseln in Kooperationsverträgen', 'Verificación de las cláusulas de confidencialidad y propiedad intelectual de los convenios de colaboración', 'Verifica delle clausole di riservatezza e proprietà intellettuale degli accordi di partnership'], 'partners', 'ANNUEL', 'PREVENTIF', ['partner-leak', 'research-theft'])

b.control('exam-room-access', ['Contrôle par échantillon de l’identité des candidats et des accès aux salles d’examen', 'Sample check of candidate identity and access to exam rooms', 'Stichprobenprüfung der Identität der Prüflinge und des Zutritts zu Prüfungsräumen', 'Control por muestreo de la identidad de los candidatos y del acceso a las salas de examen', 'Controllo a campione dell’identità dei candidati e dell’accesso alle aule d’esame'], 'exams', 'SEMESTRIEL', 'DETECTIF', ['exam-cheating'])

b.kri('phishing-reports', ['Comptes étudiants ou personnels compromis', 'Compromised student or staff accounts', 'Kompromittierte Studierenden- oder Mitarbeiterkonten', 'Cuentas de estudiantes o personal comprometidas', 'Account di studenti o personale compromessi'], 'campus-it', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('platform-availability', ['Disponibilité de l’environnement numérique de travail en période d’examens', 'Availability of the learning environment during exam periods', 'Verfügbarkeit der Lernumgebung in Prüfungsphasen', 'Disponibilidad del entorno digital de trabajo en periodos de exámenes', 'Disponibilità dell’ambiente digitale di lavoro nei periodi d’esame'], 'campus-it', U_PCT, 'BAISSE', 'MENSUEL')
b.kri('unmanaged', ['Équipements non gérés détectés sur le réseau', 'Unmanaged devices detected on the network', 'Im Netz erkannte nicht verwaltete Geräte', 'Equipos no gestionados detectados en la red', 'Dispositivi non gestiti rilevati sulla rete'], 'campus-it', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('grade-corrections', ['Corrections de notes après publication', 'Grade corrections after publication', 'Notenkorrekturen nach Veröffentlichung', 'Correcciones de notas tras la publicación', 'Correzioni dei voti dopo la pubblicazione'], 'exams', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('data-requests', ['Demandes d’exercice de droits sur des données d’étudiants traitées hors délai', 'Student data-rights requests handled late', 'Verspätet bearbeitete Betroffenenanfragen von Studierenden', 'Solicitudes de ejercicio de derechos de estudiantes tramitadas fuera de plazo', 'Richieste di esercizio dei diritti degli studenti gestite in ritardo'], 'students', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('research-restore-age', ['Ancienneté du dernier test de restauration des données de recherche', 'Age of the last research-data restoration test', 'Alter des letzten Wiederherstellungstests der Forschungsdaten', 'Antigüedad de la última prueba de restauración de datos de investigación', 'Anzianità dell’ultimo test di ripristino dei dati di ricerca'], 'research', U_DAYS, 'HAUSSE', 'MENSUEL')
b.kri('lab-incidents', ['Incidents de sécurité en laboratoire déclarés', 'Reported laboratory safety incidents', 'Gemeldete Sicherheitsvorfälle im Labor', 'Incidentes de seguridad en laboratorio notificados', 'Incidenti di sicurezza di laboratorio segnalati'], 'research', U_NB, 'HAUSSE', 'TRIMESTRIEL')
b.kri('funding-ineligible', ['Dépenses de recherche contestées ou inéligibles relevées', 'Contested or ineligible research expenses found', 'Beanstandete oder nicht förderfähige Forschungsausgaben', 'Gastos de investigación impugnados o no elegibles detectados', 'Spese di ricerca contestate o non ammissibili rilevate'], 'partners', U_NB, 'HAUSSE', 'TRIMESTRIEL')

b.audit('student-data', ['Audit de la protection des données d’étudiants', 'Audit of student data protection', 'Audit des Schutzes von Studierendendaten', 'Auditoría de la protección de datos de estudiantes', 'Audit della protezione dei dati degli studenti'], 'students', ['student-data-leak'], [
  ['Les accès aux dossiers sont limités aux fonctions concernées et tracés', 'Access to records is limited to the relevant roles and logged', 'Der Zugriff auf Akten ist auf die zuständigen Funktionen beschränkt und protokolliert', 'El acceso a los expedientes se limita a las funciones afectadas y queda registrado', 'L’accesso ai fascicoli è limitato alle funzioni interessate e tracciato'],
  ['Les durées de conservation sont définies et appliquées', 'Retention periods are defined and applied', 'Aufbewahrungsfristen sind festgelegt und werden angewendet', 'Los plazos de conservación están definidos y se aplican', 'I tempi di conservazione sono definiti e applicati'],
  ['Les outils numériques éducatifs sont encadrés par un contrat de sous-traitance', 'Educational digital tools are covered by a processing agreement', 'Digitale Bildungswerkzeuge sind durch einen Auftragsverarbeitungsvertrag abgedeckt', 'Las herramientas digitales educativas están amparadas por un contrato de encargado del tratamiento', 'Gli strumenti digitali didattici sono coperti da un contratto di trattamento'],
  ['Les demandes d’exercice de droits sont traitées dans les délais', 'Data-rights requests are handled on time', 'Betroffenenanfragen werden fristgerecht bearbeitet', 'Las solicitudes de ejercicio de derechos se tramitan en plazo', 'Le richieste di esercizio dei diritti sono gestite nei termini'],
])
b.audit('exams', ['Audit de l’intégrité des examens et des diplômes', 'Audit of exam and diploma integrity', 'Audit der Integrität von Prüfungen und Abschlüssen', 'Auditoría de la integridad de exámenes y títulos', 'Audit dell’integrità di esami e diplomi'], 'exams', ['exam-cheating', 'grade-tampering'], [
  ['Les sujets sont protégés de leur conception à leur passation', 'Exam papers are protected from design to sitting', 'Prüfungsaufgaben sind von der Erstellung bis zur Durchführung geschützt', 'Los exámenes están protegidos desde su elaboración hasta su realización', 'I testi d’esame sono protetti dalla preparazione allo svolgimento'],
  ['Les notes ne peuvent être modifiées qu’avec une justification tracée', 'Grades can only be changed with a traced justification', 'Noten können nur mit nachvollziehbarer Begründung geändert werden', 'Las notas solo pueden modificarse con una justificación trazada', 'I voti possono essere modificati solo con una giustificazione tracciata'],
  ['Les décisions de jury sont conservées et rapprochées des diplômes délivrés', 'Jury decisions are retained and reconciled with issued diplomas', 'Prüfungsausschussbeschlüsse werden aufbewahrt und mit ausgestellten Abschlüssen abgeglichen', 'Las decisiones del tribunal se conservan y se concilian con los títulos expedidos', 'Le decisioni della commissione sono conservate e riconciliate con i diplomi rilasciati'],
  ['Les examens à distance disposent de garanties de surveillance proportionnées', 'Remote exams have proportionate invigilation safeguards', 'Fernprüfungen verfügen über angemessene Aufsichtsvorkehrungen', 'Los exámenes a distancia disponen de garantías de vigilancia proporcionadas', 'Gli esami a distanza dispongono di garanzie di sorveglianza proporzionate'],
])
b.audit('research-protection', ['Audit de la protection des données et résultats de recherche', 'Audit of the protection of research data and results', 'Audit des Schutzes von Forschungsdaten und -ergebnissen', 'Auditoría de la protección de los datos y resultados de investigación', 'Audit della protezione dei dati e dei risultati di ricerca'], 'research', ['research-theft', 'research-integrity'], [
  ['Les travaux sensibles sont identifiés et leurs accès restreints', 'Sensitive work is identified and its access restricted', 'Sensible Arbeiten sind identifiziert und der Zugang beschränkt', 'Los trabajos sensibles están identificados y su acceso restringido', 'I lavori sensibili sono identificati e il loro accesso limitato'],
  ['Les données de recherche sont sauvegardées et restaurables', 'Research data is backed up and restorable', 'Forschungsdaten werden gesichert und sind wiederherstellbar', 'Los datos de investigación se respaldan y son restaurables', 'I dati di ricerca sono sottoposti a backup e ripristinabili'],
  ['Les collaborations extérieures sont encadrées par une convention', 'External collaborations are covered by an agreement', 'Externe Kooperationen sind vertraglich geregelt', 'Las colaboraciones externas están amparadas por un convenio', 'Le collaborazioni esterne sono coperte da una convenzione'],
  ['L’accueil de chercheurs extérieurs suit une procédure de vérification', 'Visiting researchers are admitted through a verification procedure', 'Gastforschende werden nach einem Prüfverfahren aufgenommen', 'La acogida de investigadores externos sigue un procedimiento de verificación', 'L’accoglienza di ricercatori esterni segue una procedura di verifica'],
])
b.audit('campus-resilience', ['Audit de la continuité des services numériques du campus', 'Audit of campus digital-service continuity', 'Audit der Kontinuität der digitalen Campus-Dienste', 'Auditoría de la continuidad de los servicios digitales del campus', 'Audit della continuità dei servizi digitali del campus'], 'campus-it', ['ransomware-campus', 'enrolment-outage', 'open-network'], [
  ['Les services critiques de la période de rentrée et d’examens sont identifiés', 'Services critical to the intake and exam periods are identified', 'Für Einschreibe- und Prüfungsphasen kritische Dienste sind identifiziert', 'Los servicios críticos del periodo de inscripción y exámenes están identificados', 'I servizi critici per i periodi di iscrizione ed esami sono identificati'],
  ['Les sauvegardes sont isolées et des restaurations sont testées', 'Backups are isolated and restorations tested', 'Sicherungen sind isoliert und Wiederherstellungen werden getestet', 'Las copias de seguridad están aisladas y las restauraciones se prueban', 'I backup sono isolati e i ripristini testati'],
  ['Le réseau ouvert est séparé des systèmes sensibles', 'The open network is separated from sensitive systems', 'Das offene Netz ist von sensiblen Systemen getrennt', 'La red abierta está separada de los sistemas sensibles', 'La rete aperta è separata dai sistemi sensibili'],
  ['Un mode dégradé et des communications de crise sont prévus', 'A fallback mode and crisis communications are planned', 'Ein Notbetrieb und Krisenkommunikation sind vorgesehen', 'Se prevén un modo degradado y comunicaciones de crisis', 'Sono previsti una modalità degradata e comunicazioni di crisi'],
])

export const EDUCATION_PACK = b.pack
