/**
 * Approfondissement des packs « Transports / Logistique », « Commerce / Distribution » et « Services professionnels »
 * (catalogue 1.10). Complète les éléments existants (mêmes processus) : suggestions à qualifier, jamais d'exécution, de seuil,
 * de date, de résultat ni de conformité acquise. Les `references` citent le texte d'origine sans reproduire d'exigence.
 * Contenu à relire par un expert du secteur (statut « à relire »).
 */
import { sectorPack, U_NB, U_PCT, U_DAYS } from './catalogue-pack-builder'

const RGPD = 'Règlement (UE) 2016/679 (RGPD)'
const NIS2 = 'Directive (UE) 2022/2555 (NIS 2)'
const TEMPS_CONDUITE = 'Règlement (CE) n° 561/2006 (temps de conduite et de repos)'
const ADR = 'Accord ADR (transport international de marchandises dangereuses par route)'
const PCI = 'PCI DSS v4.0.1 (norme de sécurité des données de l’industrie des cartes de paiement)'
const CONSO = 'Code de la consommation'
const ISO27001 = 'ISO/IEC 27001:2022'

// ════════════════════════════ Transports / Logistique ═══════════════════════
const tr = sectorPack('TRANSPORT')
tr.risk('driver-hours', 7, ['Des temps de conduite ou de repos de conducteurs sont dépassés', 'Drivers’ driving or rest time limits are exceeded', 'Lenk- oder Ruhezeiten von Fahrern werden überschritten', 'Se superan los tiempos de conducción o descanso de los conductores', 'I tempi di guida o di riposo dei conducenti vengono superati'], 'move')
tr.risk('dangerous-goods', 3, ['Une marchandise dangereuse est mal déclarée, emballée ou chargée', 'Dangerous goods are wrongly declared, packed or loaded', 'Gefahrgut wird falsch deklariert, verpackt oder verladen', 'Una mercancía peligrosa se declara, embala o carga incorrectamente', 'Una merce pericolosa viene dichiarata, imballata o caricata in modo errato'], 'move')
tr.risk('customs-error', 7, ['Une erreur de déclaration douanière bloque ou pénalise un envoi', 'A customs-declaration error blocks or penalises a shipment', 'Ein Zollanmeldungsfehler blockiert oder sanktioniert eine Sendung', 'Un error en la declaración aduanera bloquea o penaliza un envío', 'Un errore di dichiarazione doganale blocca o penalizza una spedizione'], 'plan')
tr.risk('fleet-cyber', 2, ['Un système embarqué ou de gestion de flotte est compromis', 'An on-board or fleet-management system is compromised', 'Ein Bordsystem oder Flottenmanagementsystem wird kompromittiert', 'Un sistema embarcado o de gestión de flota se ve comprometido', 'Un sistema di bordo o di gestione della flotta viene compromesso'], 'fleet')
tr.risk('subcontracted-carrier', 7, ['Un transporteur sous-traitant défaille ou ne respecte pas les exigences de sécurité', 'A subcontracted carrier fails or does not meet security requirements', 'Ein Subunternehmer-Spediteur fällt aus oder erfüllt Sicherheitsanforderungen nicht', 'Un transportista subcontratado falla o incumple los requisitos de seguridad', 'Un vettore subappaltatore viene meno o non rispetta i requisiti di sicurezza'], 'plan')
tr.control('driver-hours-review', ['Revue des relevés de temps de conduite et de repos des conducteurs', 'Review of drivers’ driving and rest-time records', 'Überprüfung der Lenk- und Ruhezeitaufzeichnungen der Fahrer', 'Revisión de los registros de tiempos de conducción y descanso de los conductores', 'Revisione delle registrazioni dei tempi di guida e riposo dei conducenti'], 'move', 'MENSUEL', 'DETECTIF', ['driver-hours', 'accident'], [TEMPS_CONDUITE])
tr.control('licence-validity', ['Vérification de la validité des permis et qualifications des conducteurs', 'Check of drivers’ licence and qualification validity', 'Prüfung der Gültigkeit von Führerscheinen und Qualifikationen der Fahrer', 'Verificación de la validez de los permisos y cualificaciones de los conductores', 'Verifica della validità di patenti e qualifiche dei conducenti'], 'move', 'TRIMESTRIEL', 'PREVENTIF', ['accident', 'driver-hours'])
tr.control('dangerous-goods-check', ['Contrôle par échantillon de la documentation et du chargement des marchandises dangereuses', 'Sample check of dangerous-goods documentation and loading', 'Stichprobenprüfung von Dokumentation und Verladung von Gefahrgut', 'Control por muestreo de la documentación y de la carga de mercancías peligrosas', 'Controllo a campione della documentazione e del carico delle merci pericolose'], 'move', 'MENSUEL', 'DETECTIF', ['dangerous-goods'], [ADR])
tr.control('safety-adviser', ['Revue du rapport annuel du conseiller à la sécurité et du suivi de ses recommandations', 'Review of the safety adviser’s annual report and follow-up of recommendations', 'Überprüfung des Jahresberichts des Sicherheitsberaters und Nachverfolgung der Empfehlungen', 'Revisión del informe anual del consejero de seguridad y seguimiento de sus recomendaciones', 'Revisione della relazione annuale del consulente per la sicurezza e dei suoi suggerimenti'], 'move', 'ANNUEL', 'DETECTIF', ['dangerous-goods'], [ADR])
tr.control('incident-analysis', ['Analyse des accidents et incidents de circulation et suivi des actions', 'Analysis of road accidents and incidents and follow-up of actions', 'Analyse von Verkehrsunfällen und Vorfällen und Nachverfolgung der Maßnahmen', 'Análisis de accidentes e incidentes de circulación y seguimiento de acciones', 'Analisi di incidenti stradali ed eventi e monitoraggio delle azioni'], 'move', 'TRIMESTRIEL', 'DETECTIF', ['accident'])
tr.control('route-risk', ['Revue de la planification des tournées à risque (zones, horaires, valeur des marchandises)', 'Review of planning of high-risk routes (areas, times, cargo value)', 'Überprüfung der Planung riskanter Touren (Gebiete, Zeiten, Warenwert)', 'Revisión de la planificación de rutas de riesgo (zonas, horarios, valor de la mercancía)', 'Revisione della pianificazione dei percorsi a rischio (zone, orari, valore della merce)'], 'plan', 'TRIMESTRIEL', 'PREVENTIF', ['cargo-theft', 'delay'])
tr.control('seal-checks', ['Contrôle par échantillon des scellés et de la remise des marchandises', 'Sample check of seals and delivery of goods', 'Stichprobenprüfung von Plomben und Warenübergabe', 'Control por muestreo de los precintos y de la entrega de las mercancías', 'Controllo a campione dei sigilli e della consegna delle merci'], 'move', 'MENSUEL', 'DETECTIF', ['cargo-theft'])
tr.control('tracking-alerts', ['Revue des alertes de géolocalisation (arrêts anormaux, déviations)', 'Review of tracking alerts (abnormal stops, deviations)', 'Überprüfung der Ortungswarnungen (auffällige Halte, Abweichungen)', 'Revisión de las alertas de geolocalización (paradas anómalas, desvíos)', 'Revisione degli alert di localizzazione (soste anomale, deviazioni)'], 'move', 'MENSUEL', 'DETECTIF', ['cargo-theft', 'telematics'])
tr.control('telematics-access', ['Revue des accès aux données de géolocalisation et de télématique', 'Review of access to tracking and telematics data', 'Überprüfung der Zugriffe auf Ortungs- und Telematikdaten', 'Revisión de los accesos a datos de geolocalización y telemática', 'Revisione degli accessi ai dati di geolocalizzazione e telematica'], 'fleet', 'TRIMESTRIEL', 'DETECTIF', ['telematics'], [RGPD])
tr.control('fleet-system-security', ['Revue des accès et des mises à jour des systèmes embarqués et de gestion de flotte', 'Review of access and updates of on-board and fleet-management systems', 'Überprüfung von Zugriffen und Updates der Bord- und Flottenmanagementsysteme', 'Revisión de los accesos y actualizaciones de los sistemas embarcados y de gestión de flota', 'Revisione di accessi e aggiornamenti dei sistemi di bordo e di gestione della flotta'], 'fleet', 'TRIMESTRIEL', 'DETECTIF', ['fleet-cyber'], [NIS2])
tr.control('tms-recovery', ['Test de reprise du système de planification et de gestion des transports', 'Recovery test of the planning and transport-management system', 'Wiederanlauftest des Planungs- und Transportmanagementsystems', 'Prueba de recuperación del sistema de planificación y gestión del transporte', 'Test di ripristino del sistema di pianificazione e gestione dei trasporti'], 'plan', 'SEMESTRIEL', 'DETECTIF', ['planning-outage'])
tr.control('manual-fallback', ['Exercice de fonctionnement en mode manuel en cas de panne du système de planification', 'Manual-mode exercise if the planning system fails', 'Übung zum manuellen Betrieb bei Ausfall des Planungssystems', 'Ejercicio de funcionamiento manual en caso de caída del sistema de planificación', 'Esercitazione di funzionamento manuale in caso di guasto del sistema di pianificazione'], 'plan', 'ANNUEL', 'PREVENTIF', ['planning-outage', 'delay'])
tr.control('customs-sample', ['Contrôle par échantillon de la conformité des déclarations en douane', 'Sample check of customs-declaration accuracy', 'Stichprobenprüfung der Richtigkeit von Zollanmeldungen', 'Control por muestreo de la exactitud de las declaraciones en aduana', 'Controllo a campione della correttezza delle dichiarazioni doganali'], 'plan', 'MENSUEL', 'DETECTIF', ['customs-error'])
tr.control('carrier-qualification', ['Vérification des assurances, licences et exigences de sécurité des transporteurs sous-traitants', 'Check of insurance, licences and security requirements of subcontracted carriers', 'Prüfung von Versicherungen, Lizenzen und Sicherheitsanforderungen der Subunternehmer-Spediteure', 'Verificación de seguros, licencias y requisitos de seguridad de los transportistas subcontratados', 'Verifica di assicurazioni, licenze e requisiti di sicurezza dei vettori subappaltatori'], 'plan', 'ANNUEL', 'PREVENTIF', ['subcontracted-carrier'])
tr.control('warehouse-access', ['Revue des accès physiques aux entrepôts et aux zones de forte valeur', 'Review of physical access to warehouses and high-value zones', 'Überprüfung des physischen Zutritts zu Lagern und hochwertigen Bereichen', 'Revisión de los accesos físicos a almacenes y zonas de alto valor', 'Revisione degli accessi fisici a magazzini e zone di alto valore'], 'warehouse', 'TRIMESTRIEL', 'DETECTIF', ['cargo-theft'])
tr.control('inventory-adjustments', ['Revue des ajustements de stock manuels en entrepôt', 'Review of manual stock adjustments in the warehouse', 'Überprüfung manueller Bestandskorrekturen im Lager', 'Revisión de los ajustes manuales de stock en almacén', 'Revisione delle rettifiche manuali di giacenza in magazzino'], 'warehouse', 'MENSUEL', 'DETECTIF', ['stock-error', 'cargo-theft'])
tr.control('forklift-safety', ['Vérification des habilitations de conduite d’engins et des contrôles périodiques', 'Check of equipment-operator authorisations and periodic inspections', 'Prüfung der Fahrberechtigungen für Flurförderzeuge und wiederkehrender Prüfungen', 'Verificación de las habilitaciones de conducción de equipos y de los controles periódicos', 'Verifica delle abilitazioni alla guida di mezzi e dei controlli periodici'], 'warehouse', 'TRIMESTRIEL', 'PREVENTIF', ['accident'])
tr.control('planning-data-restore', ['Test de restauration des données de planification et de tachygraphe', 'Restoration test of planning and tachograph data', 'Wiederherstellungstest von Planungs- und Fahrtenschreiberdaten', 'Prueba de restauración de los datos de planificación y tacógrafo', 'Test di ripristino dei dati di pianificazione e cronotachigrafo'], 'plan', 'SEMESTRIEL', 'DETECTIF', ['planning-outage', 'driver-hours'])
tr.kri('driver-hours-breaches', ['Infractions aux temps de conduite et de repos détectées', 'Driving and rest-time infringements detected', 'Festgestellte Verstöße gegen Lenk- und Ruhezeiten', 'Infracciones de tiempos de conducción y descanso detectadas', 'Infrazioni dei tempi di guida e riposo rilevate'], 'move', U_NB, 'HAUSSE', 'MENSUEL')
tr.kri('road-incidents', ['Accidents et incidents de circulation impliquant la flotte', 'Road accidents and incidents involving the fleet', 'Verkehrsunfälle und Vorfälle mit Flottenfahrzeugen', 'Accidentes e incidentes de circulación con vehículos de la flota', 'Incidenti stradali ed eventi che coinvolgono la flotta'], 'move', U_NB, 'HAUSSE', 'MENSUEL')
tr.kri('cargo-losses', ['Envois perdus, volés ou endommagés', 'Shipments lost, stolen or damaged', 'Verlorene, gestohlene oder beschädigte Sendungen', 'Envíos perdidos, robados o dañados', 'Spedizioni perse, rubate o danneggiate'], 'move', U_PCT, 'HAUSSE', 'MENSUEL')
tr.kri('inventory-accuracy', ['Écarts d’inventaire en entrepôt', 'Warehouse inventory discrepancies', 'Bestandsabweichungen im Lager', 'Diferencias de inventario en almacén', 'Discrepanze di inventario in magazzino'], 'warehouse', U_PCT, 'HAUSSE', 'MENSUEL')
tr.kri('customs-rejections', ['Déclarations en douane rejetées ou rectifiées', 'Customs declarations rejected or amended', 'Abgelehnte oder berichtigte Zollanmeldungen', 'Declaraciones aduaneras rechazadas o rectificadas', 'Dichiarazioni doganali respinte o rettificate'], 'plan', U_NB, 'HAUSSE', 'MENSUEL')
tr.kri('planning-downtime', ['Durée d’indisponibilité du système de planification', 'Downtime of the planning system', 'Ausfallzeit des Planungssystems', 'Tiempo de indisponibilidad del sistema de planificación', 'Tempo di indisponibilità del sistema di pianificazione'], 'plan', U_DAYS, 'HAUSSE', 'MENSUEL')
tr.audit('road-safety', ['Audit de la sécurité routière et de la conformité des conducteurs', 'Audit of road safety and driver compliance', 'Audit der Verkehrssicherheit und der Fahrer-Compliance', 'Auditoría de la seguridad vial y de la conformidad de los conductores', 'Audit della sicurezza stradale e della conformità dei conducenti'], 'move', ['accident', 'driver-hours', 'maintenance'], [
  ['Les temps de conduite et de repos sont suivis et les écarts traités', 'Driving and rest times are monitored and gaps handled', 'Lenk- und Ruhezeiten werden überwacht und Abweichungen bearbeitet', 'Los tiempos de conducción y descanso se supervisan y las desviaciones se tratan', 'I tempi di guida e riposo sono monitorati e gli scostamenti trattati'],
  ['Les permis et qualifications sont à jour', 'Licences and qualifications are up to date', 'Führerscheine und Qualifikationen sind aktuell', 'Los permisos y cualificaciones están al día', 'Patenti e qualifiche sono aggiornate'],
  ['L’entretien des véhicules suit le plan défini', 'Vehicle maintenance follows the defined plan', 'Die Fahrzeugwartung folgt dem festgelegten Plan', 'El mantenimiento de los vehículos sigue el plan definido', 'La manutenzione dei veicoli segue il piano definito'],
  ['Les accidents sont analysés et les actions suivies', 'Accidents are analysed and actions followed up', 'Unfälle werden analysiert und Maßnahmen nachverfolgt', 'Los accidentes se analizan y se hace seguimiento de las acciones', 'Gli incidenti sono analizzati e le azioni monitorate'],
])
tr.audit('cargo-security', ['Audit de la sûreté des marchandises et des entrepôts', 'Audit of cargo and warehouse security', 'Audit der Sicherheit von Waren und Lagern', 'Auditoría de la seguridad de mercancías y almacenes', 'Audit della sicurezza di merci e magazzini'], 'warehouse', ['cargo-theft', 'stock-error'], [
  ['Les zones sensibles sont protégées et les accès contrôlés', 'Sensitive areas are protected and access controlled', 'Sensible Bereiche sind geschützt und der Zutritt kontrolliert', 'Las zonas sensibles están protegidas y los accesos controlados', 'Le zone sensibili sono protette e gli accessi controllati'],
  ['Les envois de forte valeur suivent un parcours sécurisé', 'High-value shipments follow a secured route', 'Hochwertige Sendungen folgen einem gesicherten Weg', 'Los envíos de alto valor siguen un recorrido seguro', 'Le spedizioni di alto valore seguono un percorso protetto'],
  ['Les inventaires sont rapprochés et les écarts expliqués', 'Inventories are reconciled and differences explained', 'Bestände werden abgeglichen und Abweichungen erklärt', 'Los inventarios se concilian y las diferencias se explican', 'Gli inventari sono riconciliati e le differenze spiegate'],
  ['Les alertes de suivi des envois sont traitées', 'Shipment-tracking alerts are handled', 'Warnungen der Sendungsverfolgung werden bearbeitet', 'Las alertas de seguimiento de envíos se tratan', 'Gli alert di tracciamento delle spedizioni sono gestiti'],
])
tr.audit('regulated-transport', ['Audit des transports réglementés (marchandises dangereuses, douane)', 'Audit of regulated transport (dangerous goods, customs)', 'Audit regulierter Transporte (Gefahrgut, Zoll)', 'Auditoría de los transportes regulados (mercancías peligrosas, aduana)', 'Audit dei trasporti regolamentati (merci pericolose, dogana)'], 'plan', ['dangerous-goods', 'customs-error', 'subcontracted-carrier'], [
  ['Les exigences applicables aux marchandises transportées sont identifiées', 'Requirements applicable to goods carried are identified', 'Für die beförderten Güter geltende Anforderungen sind identifiziert', 'Los requisitos aplicables a las mercancías transportadas están identificados', 'I requisiti applicabili alle merci trasportate sono identificati'],
  ['La documentation de transport est complète et contrôlée', 'Transport documentation is complete and checked', 'Die Transportdokumentation ist vollständig und wird geprüft', 'La documentación de transporte está completa y se controla', 'La documentazione di trasporto è completa e controllata'],
  ['Les transporteurs sous-traitants sont qualifiés avant mission', 'Subcontracted carriers are qualified before assignment', 'Subunternehmer-Spediteure werden vor dem Einsatz qualifiziert', 'Los transportistas subcontratados se cualifican antes de la misión', 'I vettori subappaltatori sono qualificati prima dell’incarico'],
  ['Les erreurs de déclaration sont analysées et corrigées', 'Declaration errors are analysed and corrected', 'Anmeldefehler werden analysiert und korrigiert', 'Los errores de declaración se analizan y corrigen', 'Gli errori di dichiarazione sono analizzati e corretti'],
])

// ════════════════════════════ Commerce / Distribution ═══════════════════════
const co = sectorPack('COMMERCE')
co.risk('card-data', 2, ['Des données de cartes de paiement sont compromises en magasin ou en ligne', 'Payment-card data is compromised in store or online', 'Zahlungskartendaten werden im Geschäft oder online kompromittiert', 'Se comprometen datos de tarjetas de pago en tienda o en línea', 'I dati delle carte di pagamento vengono compromessi in negozio o online'], 'sell')
co.risk('refund-fraud', 1, ['Des remboursements ou retours frauduleux sont validés en caisse ou en ligne', 'Fraudulent refunds or returns are validated at the till or online', 'Betrügerische Erstattungen oder Retouren werden an der Kasse oder online bestätigt', 'Se validan devoluciones o reembolsos fraudulentos en caja o en línea', 'Rimborsi o resi fraudolenti vengono convalidati in cassa o online'], 'returns')
co.risk('shrinkage', 1, ['Des pertes de stock (vol, casse, démarque) dépassent le niveau attendu', 'Stock losses (theft, breakage, shrink) exceed the expected level', 'Bestandsverluste (Diebstahl, Bruch, Schwund) übersteigen das erwartete Maß', 'Las pérdidas de stock (robo, rotura, merma) superan el nivel previsto', 'Le perdite di magazzino (furti, rotture, cali) superano il livello atteso'], 'stock')
co.risk('product-safety', 3, ['Un produit non conforme ou dangereux est vendu et doit être rappelé', 'A non-compliant or dangerous product is sold and must be recalled', 'Ein nicht konformes oder gefährliches Produkt wird verkauft und muss zurückgerufen werden', 'Se vende un producto no conforme o peligroso y debe retirarse', 'Un prodotto non conforme o pericoloso viene venduto e deve essere richiamato'], 'stock')
co.risk('consumer-law', 7, ['Une pratique commerciale (promotion, information du consommateur) enfreint les règles de consommation', 'A commercial practice (promotion, consumer information) breaches consumer rules', 'Eine Geschäftspraxis (Aktion, Verbraucherinformation) verstößt gegen Verbraucherrecht', 'Una práctica comercial (promoción, información al consumidor) infringe las normas de consumo', 'Una pratica commerciale (promozione, informazione al consumatore) viola le norme sul consumo'], 'sell')
co.control('pci-scope-retail', ['Revue du périmètre et de la sécurité de l’environnement de paiement (magasin et en ligne)', 'Review of the scope and security of the payment environment (store and online)', 'Überprüfung von Umfang und Sicherheit der Zahlungsumgebung (Geschäft und online)', 'Revisión del perímetro y de la seguridad del entorno de pago (tienda y en línea)', 'Revisione del perimetro e della sicurezza dell’ambiente di pagamento (negozio e online)'], 'sell', 'ANNUEL', 'DETECTIF', ['card-data'], [PCI])
co.control('terminal-tamper', ['Inspection des terminaux de paiement et des caisses (altération, remplacement)', 'Inspection of payment terminals and tills (tampering, substitution)', 'Inspektion der Zahlungsterminals und Kassen (Manipulation, Austausch)', 'Inspección de los terminales de pago y cajas (manipulación, sustitución)', 'Ispezione dei terminali di pagamento e delle casse (manomissione, sostituzione)'], 'sell', 'MENSUEL', 'DETECTIF', ['card-data'], [PCI])
co.control('web-skimming', ['Contrôle de l’intégrité des scripts de la page de paiement en ligne', 'Check of the integrity of scripts on the online payment page', 'Prüfung der Integrität der Skripte auf der Online-Zahlungsseite', 'Control de la integridad de los scripts de la página de pago en línea', 'Controllo dell’integrità degli script della pagina di pagamento online'], 'sell', 'MENSUEL', 'DETECTIF', ['card-data', 'checkout'], [PCI])
co.control('cash-handling', ['Contrôle par échantillon des écarts de caisse et des remises en banque', 'Sample check of till differences and bank deposits', 'Stichprobenprüfung von Kassendifferenzen und Bankeinzahlungen', 'Control por muestreo de las diferencias de caja y de los ingresos en banco', 'Controllo a campione delle differenze di cassa e dei versamenti in banca'], 'sell', 'MENSUEL', 'DETECTIF', ['refund-fraud', 'shrinkage'])
co.control('refund-review', ['Revue des remboursements et annulations en caisse ou en ligne par opérateur', 'Review of refunds and cancellations at the till or online by operator', 'Überprüfung von Erstattungen und Stornos an der Kasse oder online je Bediener', 'Revisión de los reembolsos y anulaciones en caja o en línea por operador', 'Revisione di rimborsi e annullamenti in cassa o online per operatore'], 'returns', 'MENSUEL', 'DETECTIF', ['refund-fraud'])
co.control('return-policy', ['Contrôle par échantillon des retours sans ticket et des motifs de remboursement', 'Sample check of returns without receipt and refund reasons', 'Stichprobenprüfung von Retouren ohne Beleg und der Erstattungsgründe', 'Control por muestreo de las devoluciones sin ticket y de los motivos de reembolso', 'Controllo a campione dei resi senza scontrino e dei motivi di rimborso'], 'returns', 'MENSUEL', 'DETECTIF', ['returns', 'refund-fraud'])
co.control('shrink-analysis', ['Analyse de la démarque inconnue par magasin et par catégorie', 'Analysis of unknown shrink by store and category', 'Analyse des unbekannten Schwunds nach Filiale und Kategorie', 'Análisis de la merma desconocida por tienda y categoría', 'Analisi dei cali ignoti per negozio e categoria'], 'stock', 'MENSUEL', 'DETECTIF', ['shrinkage', 'stock'])
co.control('receiving-check', ['Contrôle par échantillon des réceptions de marchandises (quantité, qualité)', 'Sample check of goods receipts (quantity, quality)', 'Stichprobenprüfung von Wareneingängen (Menge, Qualität)', 'Control por muestreo de las recepciones de mercancías (cantidad, calidad)', 'Controllo a campione dei ricevimenti merci (quantità, qualità)'], 'stock', 'MENSUEL', 'DETECTIF', ['stock', 'shrinkage'])
co.control('product-compliance', ['Vérification des certificats et de la conformité des produits avant mise en vente', 'Check of certificates and product compliance before going on sale', 'Prüfung von Zertifikaten und Produktkonformität vor Verkaufsstart', 'Verificación de certificados y conformidad de los productos antes de su venta', 'Verifica dei certificati e della conformità dei prodotti prima della messa in vendita'], 'stock', 'TRIMESTRIEL', 'PREVENTIF', ['product-safety'])
co.control('recall-exercise', ['Exercice de retrait de produit simulé jusqu’au point de vente', 'Simulated product withdrawal exercise down to the point of sale', 'Übung zu einem simulierten Produktrückruf bis zur Verkaufsstelle', 'Ejercicio de retirada simulada de un producto hasta el punto de venta', 'Esercitazione di ritiro simulato di un prodotto fino al punto vendita'], 'stock', 'ANNUEL', 'DETECTIF', ['product-safety'])
co.control('marketing-claims', ['Revue des promotions, prix barrés et allégations avant diffusion', 'Review of promotions, reference prices and claims before release', 'Überprüfung von Aktionen, Referenzpreisen und Werbeaussagen vor Veröffentlichung', 'Revisión de promociones, precios tachados y alegaciones antes de su difusión', 'Revisione di promozioni, prezzi barrati e dichiarazioni prima della diffusione'], 'sell', 'MENSUEL', 'PREVENTIF', ['consumer-law', 'pricing'], [CONSO])
co.control('online-terms', ['Contrôle de l’information précontractuelle et des conditions de vente en ligne', 'Check of pre-contract information and online terms of sale', 'Prüfung der vorvertraglichen Informationen und der Online-Verkaufsbedingungen', 'Control de la información precontractual y de las condiciones de venta en línea', 'Controllo dell’informazione precontrattuale e delle condizioni di vendita online'], 'sell', 'SEMESTRIEL', 'PREVENTIF', ['consumer-law'], [CONSO])
co.control('customer-data-access', ['Revue des accès aux fichiers clients et aux données de fidélité', 'Review of access to customer files and loyalty data', 'Überprüfung der Zugriffe auf Kundendateien und Treuedaten', 'Revisión de los accesos a ficheros de clientes y datos de fidelidad', 'Revisione degli accessi ai file clienti e ai dati di fidelizzazione'], 'sell', 'TRIMESTRIEL', 'DETECTIF', ['customer-data', 'loyalty'], [RGPD])
co.control('loyalty-anomalies', ['Détection des anomalies sur les comptes de fidélité (connexions, utilisation de points)', 'Detection of anomalies on loyalty accounts (logins, point redemption)', 'Erkennung von Auffälligkeiten bei Treuekonten (Anmeldungen, Punkteeinlösung)', 'Detección de anomalías en cuentas de fidelidad (conexiones, uso de puntos)', 'Rilevamento di anomalie sugli account fedeltà (accessi, utilizzo dei punti)'], 'sell', 'MENSUEL', 'DETECTIF', ['loyalty'])
co.control('delivery-sample', ['Contrôle par échantillon des livraisons non reçues ou contestées', 'Sample check of undelivered or disputed deliveries', 'Stichprobenprüfung nicht zugestellter oder beanstandeter Lieferungen', 'Control por muestreo de las entregas no recibidas o impugnadas', 'Controllo a campione delle consegne non ricevute o contestate'], 'ship', 'MENSUEL', 'DETECTIF', ['delivery'])
co.control('peak-readiness', ['Test de charge et de reprise des systèmes de vente avant les périodes de pointe', 'Load and recovery test of sales systems before peak periods', 'Last- und Wiederanlauftest der Verkaufssysteme vor Spitzenzeiten', 'Prueba de carga y recuperación de los sistemas de venta antes de los periodos punta', 'Test di carico e ripristino dei sistemi di vendita prima dei periodi di picco'], 'sell', 'ANNUEL', 'PREVENTIF', ['checkout'])
co.control('supplier-quality', ['Revue des évaluations qualité et sécurité des fournisseurs de produits sensibles', 'Review of quality and safety assessments of suppliers of sensitive products', 'Überprüfung der Qualitäts- und Sicherheitsbewertungen von Lieferanten sensibler Produkte', 'Revisión de las evaluaciones de calidad y seguridad de los proveedores de productos sensibles', 'Revisione delle valutazioni di qualità e sicurezza dei fornitori di prodotti sensibili'], 'stock', 'ANNUEL', 'PREVENTIF', ['product-safety'])
co.control('price-sync', ['Contrôle de la cohérence des prix entre caisses, site en ligne et étiquettes', 'Check of price consistency between tills, online store and labels', 'Prüfung der Preiskonsistenz zwischen Kassen, Online-Shop und Etiketten', 'Control de la coherencia de precios entre cajas, tienda en línea y etiquetas', 'Controllo della coerenza dei prezzi tra casse, negozio online ed etichette'], 'sell', 'MENSUEL', 'DETECTIF', ['pricing', 'consumer-law'], [CONSO])
co.kri('refund-ratio', ['Part des remboursements et annulations dans le chiffre d’affaires', 'Refunds and cancellations as a share of sales', 'Anteil von Erstattungen und Stornos am Umsatz', 'Peso de reembolsos y anulaciones en las ventas', 'Quota di rimborsi e annullamenti sul fatturato'], 'returns', U_PCT, 'HAUSSE', 'MENSUEL')
co.kri('unknown-shrink', ['Démarque inconnue', 'Unknown shrink', 'Unbekannter Schwund', 'Merma desconocida', 'Cali ignoti'], 'stock', U_PCT, 'HAUSSE', 'MENSUEL')
co.kri('till-differences', ['Écarts de caisse relevés', 'Till differences recorded', 'Festgestellte Kassendifferenzen', 'Diferencias de caja registradas', 'Differenze di cassa rilevate'], 'sell', U_NB, 'HAUSSE', 'MENSUEL')
co.kri('product-alerts', ['Alertes de sécurité ou rappels produits reçus', 'Product-safety alerts or recalls received', 'Eingegangene Produktsicherheitswarnungen oder Rückrufe', 'Alertas de seguridad o retiradas de productos recibidas', 'Allerte di sicurezza o richiami di prodotto ricevuti'], 'stock', U_NB, 'HAUSSE', 'MENSUEL')
co.kri('delivery-failures', ['Livraisons non conformes ou non reçues', 'Non-compliant or undelivered deliveries', 'Nicht konforme oder nicht zugestellte Lieferungen', 'Entregas no conformes o no recibidas', 'Consegne non conformi o non ricevute'], 'ship', U_PCT, 'HAUSSE', 'MENSUEL')
co.kri('loyalty-compromised', ['Comptes de fidélité signalés comme compromis', 'Loyalty accounts reported as compromised', 'Als kompromittiert gemeldete Treuekonten', 'Cuentas de fidelidad señaladas como comprometidas', 'Account fedeltà segnalati come compromessi'], 'sell', U_NB, 'HAUSSE', 'MENSUEL')
co.audit('retail-cash', ['Audit des encaissements, remboursements et de la démarque', 'Audit of cash handling, refunds and shrink', 'Audit von Kassenführung, Erstattungen und Schwund', 'Auditoría de cobros, reembolsos y merma', 'Audit di incassi, rimborsi e cali'], 'sell', ['refund-fraud', 'shrinkage', 'stock'], [
  ['Les droits de caisse et d’annulation sont limités par profil', 'Till and cancellation rights are limited by profile', 'Kassen- und Stornorechte sind profilabhängig begrenzt', 'Los derechos de caja y anulación se limitan por perfil', 'I diritti di cassa e annullamento sono limitati per profilo'],
  ['Les remboursements sont revus et les anomalies analysées', 'Refunds are reviewed and anomalies analysed', 'Erstattungen werden geprüft und Auffälligkeiten analysiert', 'Los reembolsos se revisan y las anomalías se analizan', 'I rimborsi sono rivisti e le anomalie analizzate'],
  ['Les inventaires sont rapprochés et la démarque expliquée', 'Inventories are reconciled and shrink explained', 'Bestände werden abgeglichen und Schwund erklärt', 'Los inventarios se concilian y la merma se explica', 'Gli inventari sono riconciliati e i cali spiegati'],
  ['Les remises en banque sont rapprochées des ventes', 'Bank deposits are reconciled with sales', 'Bankeinzahlungen werden mit Verkäufen abgeglichen', 'Los ingresos en banco se concilian con las ventas', 'I versamenti in banca sono riconciliati con le vendite'],
])
co.audit('payment-security', ['Audit de la sécurité des paiements et des données clients', 'Audit of payment and customer-data security', 'Audit der Zahlungssicherheit und der Kundendaten', 'Auditoría de la seguridad de los pagos y de los datos de clientes', 'Audit della sicurezza dei pagamenti e dei dati dei clienti'], 'sell', ['card-data', 'customer-data', 'loyalty'], [
  ['Le périmètre de données de cartes est cartographié et réduit', 'The cardholder-data scope is mapped and reduced', 'Der Umfang der Kartendaten ist erfasst und reduziert', 'El perímetro de datos de tarjetas está cartografiado y reducido', 'Il perimetro dei dati delle carte è mappato e ridotto'],
  ['Les terminaux et la page de paiement en ligne sont protégés et contrôlés', 'Terminals and the online payment page are protected and monitored', 'Terminals und Online-Zahlungsseite sind geschützt und werden überwacht', 'Los terminales y la página de pago en línea están protegidos y vigilados', 'I terminali e la pagina di pagamento online sono protetti e monitorati'],
  ['Les accès aux données clients sont limités et tracés', 'Access to customer data is limited and logged', 'Zugriffe auf Kundendaten sind begrenzt und protokolliert', 'Los accesos a datos de clientes son limitados y quedan registrados', 'Gli accessi ai dati dei clienti sono limitati e tracciati'],
  ['Les comptes de fidélité sont protégés contre la prise de contrôle', 'Loyalty accounts are protected against takeover', 'Treuekonten sind gegen Übernahme geschützt', 'Las cuentas de fidelidad están protegidas frente a la usurpación', 'Gli account fedeltà sono protetti dalla presa di controllo'],
])
co.audit('product-compliance', ['Audit de la conformité des produits et des pratiques commerciales', 'Audit of product compliance and commercial practices', 'Audit von Produktkonformität und Geschäftspraktiken', 'Auditoría de la conformidad de los productos y de las prácticas comerciales', 'Audit della conformità dei prodotti e delle pratiche commerciali'], 'stock', ['product-safety', 'consumer-law', 'pricing'], [
  ['Les produits sont vérifiés avant mise en vente', 'Products are checked before going on sale', 'Produkte werden vor dem Verkaufsstart geprüft', 'Los productos se verifican antes de su venta', 'I prodotti sono verificati prima della messa in vendita'],
  ['Un retrait de produit est exercé jusqu’au point de vente', 'A product withdrawal is exercised down to the point of sale', 'Ein Produktrückruf wird bis zur Verkaufsstelle geübt', 'Se ejercita una retirada de producto hasta el punto de venta', 'Un ritiro di prodotto è esercitato fino al punto vendita'],
  ['Les promotions et prix sont validés avant diffusion', 'Promotions and prices are validated before release', 'Aktionen und Preise werden vor Veröffentlichung validiert', 'Las promociones y precios se validan antes de su difusión', 'Promozioni e prezzi sono convalidati prima della diffusione'],
  ['Les réclamations clients sont suivies et analysées', 'Customer complaints are tracked and analysed', 'Kundenbeschwerden werden nachverfolgt und analysiert', 'Las reclamaciones de clientes se siguen y analizan', 'I reclami dei clienti sono monitorati e analizzati'],
])

// ════════════════════════════ Services professionnels ═══════════════════════
const sv = sectorPack('SERVICES')
sv.risk('data-protection-client', 4, ['Des données personnelles confiées par un client sont traitées hors du cadre convenu', 'Personal data entrusted by a client is processed outside the agreed framework', 'Von einem Kunden anvertraute personenbezogene Daten werden außerhalb des vereinbarten Rahmens verarbeitet', 'Datos personales confiados por un cliente se tratan fuera del marco acordado', 'Dati personali affidati da un cliente vengono trattati al di fuori del quadro concordato'], 'perform')
sv.risk('professional-liability', 7, ['Une faute professionnelle engage la responsabilité du cabinet', 'A professional error engages the firm’s liability', 'Ein Berufsfehler begründet die Haftung der Kanzlei', 'Un error profesional compromete la responsabilidad de la firma', 'Un errore professionale impegna la responsabilità dello studio'], 'perform')
sv.risk('independence', 7, ['Un conflit d’intérêts ou un manquement d’indépendance n’est pas détecté avant l’acceptation d’une mission', 'A conflict of interest or independence breach goes undetected before accepting an engagement', 'Ein Interessenkonflikt oder eine Unabhängigkeitsverletzung wird vor Annahme eines Mandats nicht erkannt', 'No se detecta un conflicto de intereses o una falta de independencia antes de aceptar un encargo', 'Un conflitto di interessi o una violazione dell’indipendenza non viene rilevato prima di accettare un incarico'], 'contract')
sv.risk('client-funds', 1, ['Des fonds de clients ou des honoraires encaissés sont mal affectés ou détournés', 'Client funds or fees collected are misallocated or misappropriated', 'Kundengelder oder vereinnahmte Honorare werden falsch zugeordnet oder veruntreut', 'Fondos de clientes u honorarios cobrados se asignan mal o se desvían', 'Fondi dei clienti o onorari incassati vengono assegnati male o sottratti'], 'bill')
sv.risk('email-compromise', 2, ['La messagerie d’un associé ou d’un collaborateur est compromise et sert à tromper des clients', 'A partner’s or employee’s mailbox is compromised and used to deceive clients', 'Das Postfach eines Partners oder Mitarbeiters wird kompromittiert und zur Täuschung von Kunden genutzt', 'El correo de un socio o empleado se ve comprometido y se usa para engañar a clientes', 'La casella di posta di un socio o dipendente viene compromessa e usata per ingannare i clienti'], 'perform')
sv.control('conflict-check', ['Contrôle des conflits d’intérêts avant acceptation de chaque mission', 'Conflict-of-interest check before accepting each engagement', 'Interessenkonfliktprüfung vor Annahme jedes Mandats', 'Control de conflictos de intereses antes de aceptar cada encargo', 'Verifica dei conflitti di interessi prima di accettare ogni incarico'], 'contract', 'MENSUEL', 'PREVENTIF', ['independence'])
sv.control('engagement-letters', ['Vérification de la signature de la lettre de mission avant démarrage des travaux', 'Check that the engagement letter is signed before work starts', 'Prüfung der Unterzeichnung des Mandatsschreibens vor Arbeitsbeginn', 'Verificación de la firma de la carta de encargo antes de iniciar los trabajos', 'Verifica della firma della lettera di incarico prima dell’inizio dei lavori'], 'contract', 'MENSUEL', 'PREVENTIF', ['scope', 'professional-liability'])
sv.control('scope-changes', ['Revue des demandes de changement de périmètre et de leur validation par le client', 'Review of scope-change requests and their client approval', 'Überprüfung von Umfangsänderungen und deren Freigabe durch den Kunden', 'Revisión de las solicitudes de cambio de alcance y de su validación por el cliente', 'Revisione delle richieste di modifica del perimetro e della loro approvazione da parte del cliente'], 'perform', 'MENSUEL', 'DETECTIF', ['scope'])
sv.control('quality-review', ['Revue qualité par un second associé des livrables à fort enjeu', 'Second-partner quality review of high-stakes deliverables', 'Qualitätsprüfung hochriskanter Leistungen durch einen zweiten Partner', 'Revisión de calidad por un segundo socio de los entregables de alto riesgo', 'Revisione di qualità da parte di un secondo socio dei deliverable ad alto rischio'], 'perform', 'MENSUEL', 'PREVENTIF', ['professional-liability', 'deadline'])
sv.control('deadline-tracking', ['Suivi des échéances contractuelles et légales par dossier', 'Tracking of contractual and legal deadlines per file', 'Nachverfolgung vertraglicher und gesetzlicher Fristen je Akte', 'Seguimiento de los plazos contractuales y legales por expediente', 'Monitoraggio delle scadenze contrattuali e legali per pratica'], 'perform', 'MENSUEL', 'DETECTIF', ['deadline'])
sv.control('capacity-planning', ['Revue de la charge et de la disponibilité des compétences clés par mission', 'Review of workload and availability of key skills per engagement', 'Überprüfung von Auslastung und Verfügbarkeit von Schlüsselkompetenzen je Mandat', 'Revisión de la carga y disponibilidad de competencias clave por encargo', 'Revisione del carico e della disponibilità delle competenze chiave per incarico'], 'perform', 'MENSUEL', 'DETECTIF', ['expertise', 'deadline'])
sv.control('subcontractor-confidentiality', ['Vérification des engagements de confidentialité et de sécurité des sous-traitants', 'Check of subcontractors’ confidentiality and security commitments', 'Prüfung der Vertraulichkeits- und Sicherheitszusagen von Unterauftragnehmern', 'Verificación de los compromisos de confidencialidad y seguridad de los subcontratistas', 'Verifica degli impegni di riservatezza e sicurezza dei subappaltatori'], 'perform', 'ANNUEL', 'PREVENTIF', ['subcontractor', 'confidentiality'])
sv.control('client-file-access', ['Revue des accès aux dossiers clients (cloisonnement par mission)', 'Review of access to client files (segregation by engagement)', 'Überprüfung der Zugriffe auf Kundenakten (Trennung je Mandat)', 'Revisión de los accesos a expedientes de clientes (segregación por encargo)', 'Revisione degli accessi ai fascicoli dei clienti (segregazione per incarico)'], 'perform', 'TRIMESTRIEL', 'DETECTIF', ['client-access', 'confidentiality'])
sv.control('need-to-know-walls', ['Contrôle des cloisonnements d’information entre missions en situation sensible', 'Check of information barriers between engagements in sensitive situations', 'Kontrolle der Informationsbarrieren zwischen Mandaten in sensiblen Situationen', 'Control de las barreras de información entre encargos en situaciones sensibles', 'Controllo delle barriere informative tra incarichi in situazioni sensibili'], 'perform', 'TRIMESTRIEL', 'DETECTIF', ['independence', 'confidentiality'])
sv.control('mfa-mailboxes', ['Vérification de l’authentification renforcée des messageries et des outils de partage de documents', 'Check of strong authentication on mailboxes and document-sharing tools', 'Prüfung der starken Authentifizierung von Postfächern und Dokumentenfreigabe-Werkzeugen', 'Verificación de la autenticación reforzada de los correos y herramientas de compartición de documentos', 'Verifica dell’autenticazione forte di caselle di posta e strumenti di condivisione documenti'], 'perform', 'TRIMESTRIEL', 'DETECTIF', ['email-compromise'], [ISO27001])
sv.control('payment-instruction-callback', ['Rappel de vérification de toute instruction de paiement ou changement de coordonnées bancaires', 'Call-back verification of any payment instruction or bank-detail change', 'Rückruf-Verifizierung jeder Zahlungsanweisung oder Änderung von Bankverbindungen', 'Verificación telefónica de toda instrucción de pago o cambio de datos bancarios', 'Richiamata di verifica di ogni istruzione di pagamento o modifica di coordinate bancarie'], 'bill', 'MENSUEL', 'PREVENTIF', ['email-compromise', 'client-funds'])
sv.control('client-account-reconciliation', ['Rapprochement des comptes de fonds de clients avec les dossiers', 'Reconciliation of client-fund accounts with files', 'Abgleich der Kundengeldkonten mit den Akten', 'Conciliación de las cuentas de fondos de clientes con los expedientes', 'Riconciliazione dei conti dei fondi dei clienti con le pratiche'], 'bill', 'MENSUEL', 'DETECTIF', ['client-funds'])
sv.control('time-recording', ['Contrôle par échantillon de la saisie des temps et de leur facturation', 'Sample check of time recording and its billing', 'Stichprobenprüfung der Zeiterfassung und ihrer Abrechnung', 'Control por muestreo del registro de tiempos y de su facturación', 'Controllo a campione della registrazione dei tempi e della relativa fatturazione'], 'bill', 'MENSUEL', 'DETECTIF', ['billing'])
sv.control('invoice-credit-notes', ['Revue des avoirs et annulations de facturation', 'Review of credit notes and invoice cancellations', 'Überprüfung von Gutschriften und Rechnungsstornos', 'Revisión de abonos y anulaciones de facturación', 'Revisione delle note di credito e degli annullamenti di fatturazione'], 'bill', 'MENSUEL', 'DETECTIF', ['billing'])
sv.control('knowledge-retention', ['Vérification de la documentation et de la transmission des savoir-faire clés', 'Check of documentation and transfer of key know-how', 'Prüfung der Dokumentation und Weitergabe von Schlüsselwissen', 'Verificación de la documentación y transmisión de conocimientos clave', 'Verifica della documentazione e della trasmissione del know-how chiave'], 'knowledge', 'ANNUEL', 'PREVENTIF', ['expertise'])
sv.control('insurance-liability', ['Revue de la couverture de responsabilité civile professionnelle et de ses plafonds', 'Review of professional liability insurance cover and limits', 'Überprüfung der Berufshaftpflichtdeckung und ihrer Höchstgrenzen', 'Revisión de la cobertura de responsabilidad civil profesional y de sus límites', 'Revisione della copertura di responsabilità civile professionale e dei relativi massimali'], 'perform', 'ANNUEL', 'PREVENTIF', ['professional-liability'])
sv.control('data-processing-terms', ['Vérification des clauses de traitement de données dans les contrats clients', 'Check of data-processing clauses in client contracts', 'Prüfung der Datenverarbeitungsklauseln in Kundenverträgen', 'Verificación de las cláusulas de tratamiento de datos en los contratos con clientes', 'Verifica delle clausole di trattamento dei dati nei contratti con i clienti'], 'contract', 'ANNUEL', 'PREVENTIF', ['data-protection-client'], [RGPD])
sv.control('backup-restore-sv', ['Test de restauration des dossiers clients et de la comptabilité', 'Restoration test of client files and accounting', 'Wiederherstellungstest von Kundenakten und Buchhaltung', 'Prueba de restauración de los expedientes de clientes y de la contabilidad', 'Test di ripristino dei fascicoli dei clienti e della contabilità'], 'knowledge', 'SEMESTRIEL', 'DETECTIF', ['deadline', 'confidentiality'])
sv.kri('conflict-flags', ['Alertes de conflit d’intérêts levées à l’acceptation', 'Conflict-of-interest flags raised at acceptance', 'Bei Annahme ausgelöste Interessenkonflikt-Hinweise', 'Alertas de conflicto de intereses emitidas en la aceptación', 'Segnalazioni di conflitto di interessi emesse all’accettazione'], 'contract', U_NB, 'HAUSSE', 'TRIMESTRIEL')
sv.kri('missions-without-letter', ['Missions démarrées sans lettre de mission signée', 'Engagements started without a signed engagement letter', 'Ohne unterzeichnetes Mandatsschreiben begonnene Mandate', 'Encargos iniciados sin carta de encargo firmada', 'Incarichi avviati senza lettera di incarico firmata'], 'contract', U_NB, 'HAUSSE', 'MENSUEL')
sv.kri('claims', ['Réclamations ou mises en cause de clients', 'Client complaints or claims', 'Beschwerden oder Inanspruchnahmen von Kunden', 'Reclamaciones o demandas de clientes', 'Reclami o contestazioni dei clienti'], 'perform', U_NB, 'HAUSSE', 'MENSUEL')
sv.kri('over-budget', ['Missions dépassant le budget d’heures validé', 'Engagements exceeding the approved hours budget', 'Mandate, die das genehmigte Stundenbudget überschreiten', 'Encargos que superan el presupuesto de horas aprobado', 'Incarichi che superano il budget di ore approvato'], 'bill', U_PCT, 'HAUSSE', 'MENSUEL')
sv.kri('key-person-concentration', ['Missions dépendant d’une seule personne', 'Engagements relying on a single person', 'Mandate, die von einer einzigen Person abhängen', 'Encargos que dependen de una sola persona', 'Incarichi dipendenti da una sola persona'], 'knowledge', U_NB, 'HAUSSE', 'TRIMESTRIEL')
sv.kri('data-requests', ['Demandes d’exercice de droits relayées par les clients traitées hors délai', 'Data-rights requests relayed by clients handled late', 'Von Kunden weitergeleitete Betroffenenanfragen, die verspätet bearbeitet wurden', 'Solicitudes de ejercicio de derechos transmitidas por clientes tramitadas fuera de plazo', 'Richieste di esercizio dei diritti inoltrate dai clienti gestite in ritardo'], 'perform', U_NB, 'HAUSSE', 'MENSUEL')
sv.audit('engagement-quality', ['Audit de l’acceptation et de la qualité des missions', 'Audit of engagement acceptance and quality', 'Audit der Mandatsannahme und Qualität', 'Auditoría de la aceptación y calidad de los encargos', 'Audit dell’accettazione e della qualità degli incarichi'], 'contract', ['independence', 'scope', 'professional-liability', 'deadline'], [
  ['Les conflits d’intérêts sont vérifiés avant chaque mission', 'Conflicts of interest are checked before each engagement', 'Interessenkonflikte werden vor jedem Mandat geprüft', 'Los conflictos de intereses se verifican antes de cada encargo', 'I conflitti di interessi sono verificati prima di ogni incarico'],
  ['Les lettres de mission précisent le périmètre et les responsabilités', 'Engagement letters set out scope and responsibilities', 'Mandatsschreiben legen Umfang und Verantwortlichkeiten fest', 'Las cartas de encargo precisan el alcance y las responsabilidades', 'Le lettere di incarico precisano il perimetro e le responsabilità'],
  ['Les livrables à fort enjeu font l’objet d’une revue indépendante', 'High-stakes deliverables undergo independent review', 'Hochriskante Leistungen werden unabhängig geprüft', 'Los entregables de alto riesgo se someten a revisión independiente', 'I deliverable ad alto rischio sono sottoposti a revisione indipendente'],
  ['Les échéances sont suivies et les dépassements expliqués', 'Deadlines are tracked and overruns explained', 'Fristen werden überwacht und Überschreitungen erklärt', 'Los plazos se siguen y los retrasos se explican', 'Le scadenze sono monitorate e i superamenti spiegati'],
])
sv.audit('client-data', ['Audit de la protection des informations et données clients', 'Audit of client information and data protection', 'Audit des Schutzes von Kundeninformationen und -daten', 'Auditoría de la protección de la información y datos de clientes', 'Audit della protezione delle informazioni e dei dati dei clienti'], 'perform', ['confidentiality', 'client-access', 'data-protection-client', 'email-compromise'], [
  ['Les dossiers clients sont cloisonnés par mission', 'Client files are segregated by engagement', 'Kundenakten sind je Mandat getrennt', 'Los expedientes de clientes están segregados por encargo', 'I fascicoli dei clienti sono segregati per incarico'],
  ['Les accès sont revus et tracés', 'Access is reviewed and logged', 'Zugriffe werden überprüft und protokolliert', 'Los accesos se revisan y registran', 'Gli accessi sono rivisti e tracciati'],
  ['Les messageries et outils de partage sont protégés par une authentification renforcée', 'Mailboxes and sharing tools are protected by strong authentication', 'Postfächer und Freigabewerkzeuge sind durch starke Authentifizierung geschützt', 'Los correos y herramientas de compartición están protegidos con autenticación reforzada', 'Caselle di posta e strumenti di condivisione sono protetti da autenticazione forte'],
  ['Les sous-traitants sont soumis à des obligations de confidentialité', 'Subcontractors are bound by confidentiality obligations', 'Unterauftragnehmer unterliegen Vertraulichkeitspflichten', 'Los subcontratistas están sujetos a obligaciones de confidencialidad', 'I subappaltatori sono vincolati da obblighi di riservatezza'],
])
sv.audit('billing-funds', ['Audit de la facturation et des fonds clients', 'Audit of billing and client funds', 'Audit von Abrechnung und Kundengeldern', 'Auditoría de la facturación y de los fondos de clientes', 'Audit della fatturazione e dei fondi dei clienti'], 'bill', ['billing', 'client-funds', 'email-compromise'], [
  ['Les temps sont saisis et facturés selon les conditions convenues', 'Time is recorded and billed per the agreed terms', 'Zeiten werden erfasst und nach den vereinbarten Bedingungen abgerechnet', 'Los tiempos se registran y facturan según las condiciones acordadas', 'I tempi sono registrati e fatturati secondo le condizioni concordate'],
  ['Les avoirs et annulations sont autorisés', 'Credit notes and cancellations are authorised', 'Gutschriften und Stornos sind genehmigt', 'Los abonos y anulaciones están autorizados', 'Le note di credito e gli annullamenti sono autorizzati'],
  ['Les fonds de clients sont séparés et rapprochés', 'Client funds are segregated and reconciled', 'Kundengelder sind getrennt und werden abgeglichen', 'Los fondos de clientes están separados y se concilian', 'I fondi dei clienti sono separati e riconciliati'],
  ['Les instructions de paiement sont vérifiées par un canal indépendant', 'Payment instructions are verified through an independent channel', 'Zahlungsanweisungen werden über einen unabhängigen Kanal geprüft', 'Las instrucciones de pago se verifican por un canal independiente', 'Le istruzioni di pagamento sono verificate tramite un canale indipendente'],
])
sv.audit('key-skills', ['Audit de la gestion des compétences clés et de la continuité des missions', 'Audit of key-skills management and engagement continuity', 'Audit der Verwaltung von Schlüsselkompetenzen und der Mandatskontinuität', 'Auditoría de la gestión de competencias clave y de la continuidad de los encargos', 'Audit della gestione delle competenze chiave e della continuità degli incarichi'], 'knowledge', ['expertise', 'subcontractor', 'deadline'], [
  ['Les compétences critiques sont identifiées avec une relève', 'Critical skills are identified with backup', 'Kritische Kompetenzen sind mit Vertretung identifiziert', 'Las competencias críticas están identificadas con relevo', 'Le competenze critiche sono identificate con un sostituto'],
  ['La charge des équipes est pilotée', 'Team workload is managed', 'Die Auslastung der Teams wird gesteuert', 'La carga de los equipos se gestiona', 'Il carico dei team è gestito'],
  ['Les sous-traitants sont qualifiés et suivis', 'Subcontractors are qualified and monitored', 'Unterauftragnehmer werden qualifiziert und überwacht', 'Los subcontratistas se cualifican y supervisan', 'I subappaltatori sono qualificati e monitorati'],
  ['Les savoir-faire clés sont documentés', 'Key know-how is documented', 'Schlüsselwissen ist dokumentiert', 'Los conocimientos clave están documentados', 'Il know-how chiave è documentato'],
])

export const DEEPEN_C_PACKS = [tr.pack, co.pack, sv.pack]
