/**
 * Pack « Protection sociale / Sécurité sociale » (catalogue 1.14) : organismes de sécurité sociale organisés en réseau
 * (droits, liquidation, paiements de masse, contrôle médical, services en ligne, professionnels de santé, risques
 * professionnels, données nationales, lutte contre la fraude). Suggestions à qualifier : jamais d'exécution, de seuil,
 * de date, de résultat ni de conformité acquise. Les `references` citent le texte d'origine et sa version sans en
 * reproduire le contenu. Exemples génériques ; contenu « à relire par un expert du secteur ».
 */
import { sectorPack, U_NB, U_PCT, U_DAYS, type Tr } from './catalogue-pack-builder'

const RGPD = 'RGPD — Règlement (UE) 2016/679'
const RGS = 'RGS — Référentiel général de sécurité, version 2.0'
const NIS2 = 'NIS2 — Directive (UE) 2022/2555, art. 21'
const ISO = 'ISO/IEC 27001:2022, annexe A'
const IA = 'Règlement (UE) 2024/1689 (intelligence artificielle)'
const U_EUR: Tr = ['euros', 'euros', 'Euro', 'euros', 'euro']

const b = sectorPack('PROTECTION_SOCIALE')

b.process('rights', ['Ouvrir et maintenir les droits des assurés', 'Open and maintain insured persons’ entitlements', 'Ansprüche der Versicherten begründen und pflegen', 'Abrir y mantener los derechos de los asegurados', 'Aprire e mantenere i diritti degli assicurati'], 'core.process.deliver')
b.process('claims', ['Liquider et payer les prestations', 'Process and pay benefits', 'Leistungen abwickeln und zahlen', 'Liquidar y pagar las prestaciones', 'Liquidare e pagare le prestazioni'], 'core.process.finance')
b.process('medical', ['Rendre les avis du contrôle médical', 'Issue medical review opinions', 'Gutachten des medizinischen Prüfdienstes erstellen', 'Emitir los dictámenes del control médico', 'Rendere i pareri del controllo medico'], 'core.process.deliver')
b.process('users', ['Servir les usagers en ligne et à l’accueil', 'Serve users online and at reception', 'Versicherte online und am Empfang betreuen', 'Atender a los usuarios en línea y en ventanilla', 'Servire gli utenti online e allo sportello'], 'core.process.deliver')
b.process('pros', ['Servir les professionnels de santé', 'Serve health professionals', 'Gesundheitsfachkräfte betreuen', 'Atender a los profesionales sanitarios', 'Servire i professionisti sanitari'], 'core.process.deliver')
b.process('occupational', ['Gérer les risques professionnels et la tarification des employeurs', 'Manage occupational risks and employer rates', 'Berufsrisiken und Beitragsbemessung der Arbeitgeber verwalten', 'Gestionar los riesgos profesionales y la tarificación de los empleadores', 'Gestire i rischi professionali e la tariffazione dei datori di lavoro'], 'core.process.deliver')
b.process('data', ['Exploiter et mettre à disposition les données nationales', 'Use and provide national data', 'Nationale Daten nutzen und bereitstellen', 'Explotar y poner a disposición los datos nacionales', 'Sfruttare e mettere a disposizione i dati nazionali'], 'core.process.digital')
b.process('production', ['Produire les traitements de masse et les paiements', 'Run mass processing and payments', 'Massenverarbeitung und Zahlungen produzieren', 'Producir los tratamientos masivos y los pagos', 'Produrre le elaborazioni massive e i pagamenti'], 'core.process.digital')
b.process('fraud', ['Lutter contre la fraude', 'Fight fraud', 'Betrug bekämpfen', 'Luchar contra el fraude', 'Contrastare la frode'], 'core.process.govern')

b.risk('mass-payment-error', 7, ['Une régression d’un traitement de masse provoque des paiements erronés pour de nombreux assurés', 'A regression in mass processing causes incorrect payments for many insured persons', 'Eine Regression in der Massenverarbeitung führt zu fehlerhaften Zahlungen für viele Versicherte', 'Una regresión de un tratamiento masivo provoca pagos erróneos a muchos asegurados', 'Una regressione di un’elaborazione massiva provoca pagamenti errati per molti assicurati'], 'claims')
b.risk('iban-diversion', 2, ['Des prestations sont détournées par changement frauduleux de coordonnées bancaires', 'Benefits are diverted through fraudulent bank-detail changes', 'Leistungen werden durch betrügerische Änderung der Bankverbindung umgeleitet', 'Se desvían prestaciones mediante el cambio fraudulento de datos bancarios', 'Le prestazioni vengono dirottate tramite modifica fraudolenta delle coordinate bancarie'], 'claims')
b.risk('agent-snooping', 1, ['Un agent consulte des données d’assurés sans lien avec ses missions', 'A staff member views insured persons’ data unrelated to their duties', 'Ein Mitarbeitender sieht Versichertendaten ohne Bezug zu seinen Aufgaben ein', 'Un agente consulta datos de asegurados sin relación con sus funciones', 'Un operatore consulta dati degli assicurati estranei alle proprie mansioni'], 'rights')
b.risk('user-account-takeover', 2, ['Des comptes usagers sont usurpés à grande échelle', 'User accounts are taken over at scale', 'Versichertenkonten werden in großem Umfang übernommen', 'Se usurpan cuentas de usuario a gran escala', 'Account utente vengono usurpati su larga scala'], 'users')
b.risk('pro-account-abuse', 2, ['Des comptes de professionnels de santé compromis servent à extraire des données d’assurés', 'Compromised health professional accounts are used to extract insured persons’ data', 'Kompromittierte Konten von Gesundheitsfachkräften werden zur Extraktion von Versichertendaten genutzt', 'Cuentas comprometidas de profesionales sanitarios sirven para extraer datos de asegurados', 'Account compromessi di professionisti sanitari servono a estrarre dati degli assicurati'], 'pros')
b.risk('production-ransomware', 6, ['Un rançongiciel paralyse les chaînes de traitement et de paiement', 'Ransomware paralyses processing and payment chains', 'Ransomware legt die Verarbeitungs- und Zahlungsketten lahm', 'Un ransomware paraliza las cadenas de tratamiento y pago', 'Un ransomware paralizza le catene di elaborazione e pagamento'], 'production')
b.risk('batch-outage', 6, ['Un arrêt prolongé des traitements de nuit retarde les paiements', 'A prolonged stop of night batches delays payments', 'Ein längerer Ausfall der Nachtläufe verzögert die Zahlungen', 'Una parada prolongada de los procesos nocturnos retrasa los pagos', 'Un arresto prolungato dei batch notturni ritarda i pagamenti'], 'production')
b.risk('medical-secrecy-breach', 4, ['Des données couvertes par le secret médical sont divulguées', 'Data covered by medical secrecy is disclosed', 'Der ärztlichen Schweigepflicht unterliegende Daten werden offengelegt', 'Se divulgan datos amparados por el secreto médico', 'Vengono divulgati dati coperti dal segreto medico'], 'medical')
b.risk('reidentification', 4, ['Des personnes sont réidentifiées à partir de données nationales mises à disposition', 'People are re-identified from provided national data', 'Personen werden aus bereitgestellten nationalen Daten re-identifiziert', 'Se reidentifica a personas a partir de datos nacionales puestos a disposición', 'Persone vengono reidentificate a partire da dati nazionali messi a disposizione'], 'data')
b.risk('tariff-error', 7, ['Une erreur de tarification touche de nombreux employeurs', 'A rating error affects many employers', 'Ein Bemessungsfehler betrifft viele Arbeitgeber', 'Un error de tarificación afecta a muchos empleadores', 'Un errore di tariffazione colpisce molti datori di lavoro'], 'occupational')
b.risk('fake-professional', 2, ['Un faux professionnel de santé facture des actes fictifs', 'A fake health professional bills fictitious services', 'Ein falscher Leistungserbringer rechnet fiktive Leistungen ab', 'Un falso profesional sanitario factura actos ficticios', 'Un falso professionista sanitario fattura prestazioni fittizie'], 'fraud')
b.risk('forged-prescriptions', 2, ['Des prescriptions falsifiées sont remboursées', 'Forged prescriptions are reimbursed', 'Gefälschte Verordnungen werden erstattet', 'Se reembolsan recetas falsificadas', 'Vengono rimborsate prescrizioni falsificate'], 'fraud')
b.risk('internal-fraud', 1, ['Un agent crée des bénéficiaires fictifs ou détourne des paiements', 'A staff member creates fictitious beneficiaries or diverts payments', 'Ein Mitarbeitender legt fiktive Begünstigte an oder leitet Zahlungen um', 'Un agente crea beneficiarios ficticios o desvía pagos', 'Un operatore crea beneficiari fittizi o dirotta pagamenti'], 'fraud')
b.risk('algorithm-bias', 4, ['Un algorithme de ciblage ou d’aide à la décision produit des décisions biaisées ou contestées', 'A targeting or decision-support algorithm produces biased or contested decisions', 'Ein Auswahl- oder Entscheidungsunterstützungsalgorithmus erzeugt verzerrte oder angefochtene Entscheidungen', 'Un algoritmo de selección o de ayuda a la decisión produce decisiones sesgadas o impugnadas', 'Un algoritmo di selezione o di supporto alle decisioni produce decisioni distorte o contestate'], 'fraud')

b.control('non-regression-amounts', ['Contrôle des tests de non-régression sur les montants des mises en production du mois', 'Check of regression tests on amounts for the month’s releases', 'Kontrolle der Regressionstests der Beträge für die Inbetriebnahmen des Monats', 'Control de las pruebas de no regresión de los importes de las puestas en producción del mes', 'Controllo dei test di non regressione sugli importi dei rilasci del mese'], 'claims', 'MENSUEL', 'DETECTIF', ['mass-payment-error'], [`${ISO}, mesure 8.32`])
b.control('batch-control-totals', ['Vérification des totaux de contrôle des lots de paiement avant remise bancaire', 'Check of payment batch control totals before bank submission', 'Prüfung der Kontrollsummen der Zahlungsläufe vor Übergabe an die Bank', 'Verificación de los totales de control de los lotes de pago antes de la remesa bancaria', 'Verifica dei totali di controllo dei lotti di pagamento prima dell’invio in banca'], 'claims', 'MENSUEL', 'DETECTIF', ['mass-payment-error'])
b.control('iban-change-sample', ['Contrôle par échantillon des changements de coordonnées bancaires (confirmation, délai de sécurité)', 'Sample check of bank detail changes (confirmation, cooling-off period)', 'Stichprobenkontrolle von Änderungen der Bankverbindung (Bestätigung, Sicherheitsfrist)', 'Control por muestreo de los cambios de datos bancarios (confirmación, plazo de seguridad)', 'Controllo a campione delle modifiche delle coordinate bancarie (conferma, periodo di sicurezza)'], 'claims', 'MENSUEL', 'DETECTIF', ['iban-diversion'])
b.control('agent-consultation-review', ['Revue des consultations atypiques de dossiers par les agents (motif, personnalités, proches)', 'Review of atypical file look-ups by staff (reason, public figures, relatives)', 'Prüfung auffälliger Vorgangsabrufe durch Mitarbeitende (Grund, Prominente, Angehörige)', 'Revisión de las consultas atípicas de expedientes por los agentes (motivo, personalidades, allegados)', 'Revisione delle consultazioni anomale delle pratiche da parte degli operatori (motivo, personalità, familiari)'], 'rights', 'MENSUEL', 'DETECTIF', ['agent-snooping'], [`${RGPD}, art. 32`])
b.control('access-recertification', ['Recertification des habilitations des agents aux applications de gestion', 'Recertification of staff access rights to case-management applications', 'Rezertifizierung der Berechtigungen der Mitarbeitenden in den Verwaltungsanwendungen', 'Recertificación de las habilitaciones de los agentes en las aplicaciones de gestión', 'Ricertificazione delle abilitazioni degli operatori alle applicazioni di gestione'], 'rights', 'SEMESTRIEL', 'DETECTIF', ['agent-snooping', 'internal-fraud'])
b.control('user-mfa-coverage', ['Vérification de l’authentification renforcée des opérations sensibles du compte usager', 'Check of stronger authentication for sensitive user-account operations', 'Prüfung der verstärkten Authentifizierung sensibler Vorgänge im Versichertenkonto', 'Verificación de la autenticación reforzada de las operaciones sensibles de la cuenta de usuario', 'Verifica dell’autenticazione rafforzata delle operazioni sensibili dell’account utente'], 'users', 'TRIMESTRIEL', 'DETECTIF', ['user-account-takeover'], [`${ISO}, mesure 8.5`])
b.control('credential-stuffing-alerts', ['Revue des alertes de bourrage d’identifiants et des blocages de comptes usagers', 'Review of credential-stuffing alerts and user account lockouts', 'Prüfung der Alarme zu Credential Stuffing und der Sperrungen von Versichertenkonten', 'Revisión de las alertas de relleno de credenciales y de los bloqueos de cuentas de usuario', 'Revisione degli allarmi di credential stuffing e dei blocchi degli account utente'], 'users', 'MENSUEL', 'DETECTIF', ['user-account-takeover'])
b.control('pro-volume-anomalies', ['Revue des volumes de consultation atypiques par professionnel de santé', 'Review of atypical look-up volumes per health professional', 'Prüfung auffälliger Abrufmengen je Gesundheitsfachkraft', 'Revisión de los volúmenes de consulta atípicos por profesional sanitario', 'Revisione dei volumi di consultazione anomali per professionista sanitario'], 'pros', 'MENSUEL', 'DETECTIF', ['pro-account-abuse'])
b.control('pro-auth-review', ['Vérification de l’authentification forte des professionnels sur les téléservices', 'Check of strong authentication of professionals on online services', 'Prüfung der starken Authentifizierung der Leistungserbringer in den Online-Diensten', 'Verificación de la autenticación fuerte de los profesionales en los teleservicios', 'Verifica dell’autenticazione forte dei professionisti sui servizi online'], 'pros', 'TRIMESTRIEL', 'DETECTIF', ['pro-account-abuse'])
b.control('offline-backup-test', ['Test de restauration des sauvegardes hors ligne des chaînes de paiement', 'Restoration test of offline backups of payment chains', 'Wiederherstellungstest der Offline-Sicherungen der Zahlungsketten', 'Prueba de restauración de las copias fuera de línea de las cadenas de pago', 'Test di ripristino dei backup offline delle catene di pagamento'], 'production', 'SEMESTRIEL', 'DETECTIF', ['production-ransomware'], [`${ISO}, mesure 8.13`])
b.control('admin-bastion-review', ['Revue des comptes et sessions d’administration des grands systèmes', 'Review of mainframe administration accounts and sessions', 'Prüfung der Administrationskonten und -sitzungen der Großrechner', 'Revisión de las cuentas y sesiones de administración de los grandes sistemas', 'Revisione degli account e delle sessioni di amministrazione dei mainframe'], 'production', 'TRIMESTRIEL', 'DETECTIF', ['production-ransomware'])
b.control('payment-continuity-test', ['Exercice du plan de continuité des paiements prioritaires', 'Exercise of the priority payments continuity plan', 'Übung des Kontinuitätsplans für vorrangige Zahlungen', 'Ejercicio del plan de continuidad de los pagos prioritarios', 'Esercitazione del piano di continuità dei pagamenti prioritari'], 'production', 'ANNUEL', 'DETECTIF', ['batch-outage', 'production-ransomware'], [`${ISO}, mesure 5.30`])
b.control('medical-data-segregation', ['Vérification du cloisonnement des données médicales et des habilitations du service médical', 'Check of medical data segregation and medical service access rights', 'Prüfung der Abschottung medizinischer Daten und der Berechtigungen des medizinischen Dienstes', 'Verificación de la separación de los datos médicos y de las habilitaciones del servicio médico', 'Verifica della separazione dei dati medici e delle abilitazioni del servizio medico'], 'medical', 'SEMESTRIEL', 'DETECTIF', ['medical-secrecy-breach'], [`${RGPD}, art. 9`])
b.control('reid-review', ['Analyse du risque de réidentification avant chaque mise à disposition de données', 'Re-identification risk analysis before each data release', 'Analyse des Re-Identifizierungsrisikos vor jeder Datenbereitstellung', 'Análisis del riesgo de reidentificación antes de cada puesta a disposición de datos', 'Analisi del rischio di reidentificazione prima di ogni messa a disposizione di dati'], 'data', 'TRIMESTRIEL', 'PREVENTIF', ['reidentification'], [`${RGPD}, art. 89`])
b.control('tariff-double-check', ['Double contrôle des paramètres de tarification des employeurs avant notification', 'Dual check of employer rating parameters before notification', 'Vier-Augen-Prüfung der Bemessungsparameter der Arbeitgeber vor der Mitteilung', 'Doble control de los parámetros de tarificación de los empleadores antes de la notificación', 'Doppio controllo dei parametri di tariffazione dei datori di lavoro prima della notifica'], 'occupational', 'TRIMESTRIEL', 'PREVENTIF', ['tariff-error'])
b.control('fraud-alert-review', ['Revue des alertes de fraude et suivi de leur traitement', 'Review of fraud alerts and follow-up of their handling', 'Prüfung der Betrugsalarme und Nachverfolgung ihrer Bearbeitung', 'Revisión de las alertas de fraude y seguimiento de su tratamiento', 'Revisione degli allarmi di frode e follow-up del loro trattamento'], 'fraud', 'MENSUEL', 'DETECTIF', ['fake-professional', 'forged-prescriptions'])
b.control('pro-registration-check', ['Contrôle par échantillon de l’enregistrement des nouveaux professionnels (identité, autorisation d’exercice)', 'Sample check of new professionals’ registration (identity, licence to practise)', 'Stichprobenkontrolle der Registrierung neuer Leistungserbringer (Identität, Berufszulassung)', 'Control por muestreo del registro de nuevos profesionales (identidad, habilitación para ejercer)', 'Controllo a campione della registrazione dei nuovi professionisti (identità, abilitazione all’esercizio)'], 'fraud', 'TRIMESTRIEL', 'DETECTIF', ['fake-professional'])
b.control('prescription-sample', ['Contrôle par échantillon des prescriptions à fort montant ou atypiques', 'Sample check of high-value or atypical prescriptions', 'Stichprobenkontrolle hoher oder auffälliger Verordnungen', 'Control por muestreo de las recetas de importe elevado o atípicas', 'Controllo a campione delle prescrizioni di importo elevato o atipiche'], 'fraud', 'MENSUEL', 'DETECTIF', ['forged-prescriptions'])
b.control('internal-fraud-segregation', ['Vérification de la séparation des tâches entre création de bénéficiaire, modification de coordonnées et paiement', 'Check of segregation of duties between beneficiary creation, detail changes and payment', 'Prüfung der Funktionstrennung zwischen Anlegen von Begünstigten, Datenänderung und Zahlung', 'Verificación de la separación de funciones entre creación de beneficiarios, modificación de datos y pago', 'Verifica della separazione dei compiti tra creazione del beneficiario, modifica dei dati e pagamento'], 'fraud', 'SEMESTRIEL', 'PREVENTIF', ['internal-fraud', 'iban-diversion'])
b.control('algorithm-human-review', ['Revue des décisions issues des algorithmes (contrôle humain, biais, contestations)', 'Review of algorithm-driven decisions (human oversight, bias, disputes)', 'Prüfung algorithmisch gestützter Entscheidungen (menschliche Aufsicht, Verzerrungen, Einsprüche)', 'Revisión de las decisiones procedentes de algoritmos (control humano, sesgos, impugnaciones)', 'Revisione delle decisioni derivanti da algoritmi (controllo umano, distorsioni, contestazioni)'], 'fraud', 'SEMESTRIEL', 'DETECTIF', ['algorithm-bias'], [IA])
b.control('teleservice-homologation', ['Vérification que chaque téléservice dispose d’une homologation de sécurité en cours de validité', 'Check that each online service holds a valid security accreditation', 'Prüfung, dass jeder Online-Dienst über eine gültige Sicherheitsakkreditierung verfügt', 'Verificación de que cada teleservicio dispone de una homologación de seguridad vigente', 'Verifica che ogni servizio online disponga di un’omologazione di sicurezza valida'], 'users', 'ANNUEL', 'PREVENTIF', ['user-account-takeover', 'pro-account-abuse'], [RGS])
b.control('nis2-measures-review', ['Revue des mesures de gestion des risques de cybersécurité', 'Review of cybersecurity risk-management measures', 'Überprüfung der Maßnahmen zum Cybersicherheits-Risikomanagement', 'Revisión de las medidas de gestión de riesgos de ciberseguridad', 'Revisione delle misure di gestione dei rischi di cibersicurezza'], 'production', 'ANNUEL', 'DETECTIF', ['production-ransomware'], [NIS2])

b.kri('iban-changes', ['Changements de coordonnées bancaires', 'Bank detail changes', 'Änderungen der Bankverbindung', 'Cambios de datos bancarios', 'Modifiche delle coordinate bancarie'], 'claims', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('undue-detected', ['Montant des indus détectés', 'Amount of overpayments detected', 'Betrag der festgestellten Überzahlungen', 'Importe de los pagos indebidos detectados', 'Importo degli indebiti rilevati'], 'claims', U_EUR, 'HAUSSE', 'MENSUEL')
b.kri('fraud-avoided', ['Préjudice de fraude évité', 'Fraud loss prevented', 'Verhinderter Betrugsschaden', 'Perjuicio por fraude evitado', 'Danno da frode evitato'], 'fraud', U_EUR, 'BAISSE', 'TRIMESTRIEL')
b.kri('fraud-processing-time', ['Délai moyen de traitement des signalements de fraude', 'Average handling time of fraud reports', 'Durchschnittliche Bearbeitungszeit von Betrugsmeldungen', 'Plazo medio de tratamiento de las denuncias de fraude', 'Tempo medio di trattamento delle segnalazioni di frode'], 'fraud', U_DAYS, 'HAUSSE', 'MENSUEL')
b.kri('atypical-consultations', ['Consultations atypiques par des agents', 'Atypical look-ups by staff', 'Auffällige Abrufe durch Mitarbeitende', 'Consultas atípicas de agentes', 'Consultazioni anomale da parte degli operatori'], 'rights', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('user-account-takeovers', ['Comptes usagers usurpés signalés', 'Reported hijacked user accounts', 'Gemeldete übernommene Versichertenkonten', 'Cuentas de usuario usurpadas notificadas', 'Account utente usurpati segnalati'], 'users', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('pro-accounts-compromised', ['Comptes de professionnels compromis signalés', 'Reported compromised professional accounts', 'Gemeldete kompromittierte Konten von Leistungserbringern', 'Cuentas de profesionales comprometidas notificadas', 'Account di professionisti compromessi segnalati'], 'pros', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('replacement-income-delay', ['Délai moyen de paiement des revenus de remplacement', 'Average payment time of replacement income', 'Durchschnittliche Zahlungsdauer der Lohnersatzleistungen', 'Plazo medio de pago de las rentas de sustitución', 'Tempo medio di pagamento dei redditi sostitutivi'], 'claims', U_DAYS, 'HAUSSE', 'MENSUEL')
b.kri('teleservice-availability', ['Disponibilité des téléservices', 'Online service availability', 'Verfügbarkeit der Online-Dienste', 'Disponibilidad de los teleservicios', 'Disponibilità dei servizi online'], 'users', U_PCT, 'BAISSE', 'MENSUEL')
b.kri('contested-automated-decisions', ['Décisions automatisées contestées', 'Contested automated decisions', 'Angefochtene automatisierte Entscheidungen', 'Decisiones automatizadas impugnadas', 'Decisioni automatizzate contestate'], 'fraud', U_NB, 'HAUSSE', 'TRIMESTRIEL')

b.audit('fraud-framework', ['Audit du dispositif de lutte contre la fraude', 'Audit of the anti-fraud framework', 'Audit des Dispositivs zur Betrugsbekämpfung', 'Auditoría del dispositivo de lucha contra el fraude', 'Audit del dispositivo antifrode'], 'fraud', ['fake-professional', 'forged-prescriptions', 'internal-fraud'], [
  ['Les typologies de fraude sont identifiées et revues', 'Fraud typologies are identified and reviewed', 'Betrugstypologien sind identifiziert und werden überprüft', 'Las tipologías de fraude están identificadas y revisadas', 'Le tipologie di frode sono identificate e riviste'],
  ['Les alertes sont traitées dans les délais et tracées', 'Alerts are handled on time and traced', 'Alarme werden fristgerecht bearbeitet und nachvollzogen', 'Las alertas se tratan a tiempo y se registran', 'Gli allarmi sono trattati nei tempi e tracciati'],
  ['La séparation des tâches limite la fraude interne', 'Segregation of duties limits internal fraud', 'Funktionstrennung begrenzt Innenbetrug', 'La separación de funciones limita el fraude interno', 'La separazione dei compiti limita la frode interna'],
  ['Le préjudice détecté, évité et recouvré est mesuré', 'Loss detected, prevented and recovered is measured', 'Erkannter, verhinderter und zurückgeholter Schaden wird gemessen', 'Se mide el perjuicio detectado, evitado y recuperado', 'Il danno rilevato, evitato e recuperato è misurato'],
])
b.audit('mass-processing', ['Audit des traitements de masse et des paiements', 'Audit of mass processing and payments', 'Audit der Massenverarbeitung und Zahlungen', 'Auditoría de los tratamientos masivos y los pagos', 'Audit delle elaborazioni massive e dei pagamenti'], 'production', ['mass-payment-error', 'batch-outage', 'production-ransomware'], [
  ['Les mises en production sont précédées de tests de non-régression sur les montants', 'Releases are preceded by regression tests on amounts', 'Inbetriebnahmen gehen Regressionstests der Beträge voraus', 'Las puestas en producción van precedidas de pruebas de no regresión de los importes', 'I rilasci sono preceduti da test di non regressione sugli importi'],
  ['Les lots de paiement sont rapprochés avant remise bancaire', 'Payment batches are reconciled before bank submission', 'Zahlungsläufe werden vor Übergabe an die Bank abgeglichen', 'Los lotes de pago se concilian antes de la remesa bancaria', 'I lotti di pagamento sono riconciliati prima dell’invio in banca'],
  ['Les sauvegardes hors ligne sont restaurées avec succès', 'Offline backups are restored successfully', 'Offline-Sicherungen werden erfolgreich wiederhergestellt', 'Las copias fuera de línea se restauran con éxito', 'I backup offline vengono ripristinati con successo'],
  ['L’administration des grands systèmes passe par un bastion', 'Mainframe administration goes through a bastion', 'Die Administration der Großrechner läuft über einen Bastion', 'La administración de los grandes sistemas pasa por un bastión', 'L’amministrazione dei mainframe passa attraverso un bastion'],
])
b.audit('agent-access', ['Audit des habilitations et des consultations des agents', 'Audit of staff access rights and look-ups', 'Audit der Berechtigungen und Abrufe der Mitarbeitenden', 'Auditoría de las habilitaciones y consultas de los agentes', 'Audit delle abilitazioni e delle consultazioni degli operatori'], 'rights', ['agent-snooping', 'internal-fraud'], [
  ['Les habilitations correspondent aux fonctions', 'Access rights match job roles', 'Berechtigungen entsprechen den Funktionen', 'Las habilitaciones corresponden a las funciones', 'Le abilitazioni corrispondono alle funzioni'],
  ['Les consultations sensibles sont motivées et revues', 'Sensitive look-ups are justified and reviewed', 'Sensible Abrufe sind begründet und werden geprüft', 'Las consultas sensibles están motivadas y revisadas', 'Le consultazioni sensibili sono motivate e riviste'],
  ['Les départs et mutations entraînent le retrait des droits', 'Departures and transfers trigger rights removal', 'Austritte und Versetzungen führen zum Entzug der Rechte', 'Las bajas y traslados conllevan la retirada de derechos', 'Le uscite e i trasferimenti comportano la revoca dei diritti'],
  ['Les campagnes de recertification sont menées à terme', 'Recertification campaigns are completed', 'Rezertifizierungskampagnen werden abgeschlossen', 'Las campañas de recertificación se completan', 'Le campagne di ricertificazione sono portate a termine'],
])
b.audit('data-provision', ['Audit de la mise à disposition des données nationales', 'Audit of national data provision', 'Audit der Bereitstellung nationaler Daten', 'Auditoría de la puesta a disposición de los datos nacionales', 'Audit della messa a disposizione dei dati nazionali'], 'data', ['reidentification'], [
  ['Chaque mise à disposition repose sur une autorisation documentée', 'Each data release relies on a documented authorisation', 'Jede Bereitstellung beruht auf einer dokumentierten Genehmigung', 'Cada puesta a disposición se basa en una autorización documentada', 'Ogni messa a disposizione si basa su un’autorizzazione documentata'],
  ['Le risque de réidentification est analysé', 'Re-identification risk is analysed', 'Das Re-Identifizierungsrisiko wird analysiert', 'Se analiza el riesgo de reidentificación', 'Il rischio di reidentificazione è analizzato'],
  ['Les accès aux extractions sont limités et tracés', 'Access to extracts is limited and traced', 'Zugriffe auf Auszüge sind begrenzt und nachvollziehbar', 'Los accesos a las extracciones están limitados y trazados', 'Gli accessi alle estrazioni sono limitati e tracciati'],
  ['Les données sont détruites à l’échéance du projet', 'Data is destroyed when the project ends', 'Daten werden bei Projektende gelöscht', 'Los datos se destruyen al vencimiento del proyecto', 'I dati sono distrutti alla scadenza del progetto'],
])
b.audit('teleservices', ['Audit de la sécurité des téléservices aux usagers et aux professionnels', 'Audit of online service security for users and professionals', 'Audit der Sicherheit der Online-Dienste für Versicherte und Leistungserbringer', 'Auditoría de la seguridad de los teleservicios para usuarios y profesionales', 'Audit della sicurezza dei servizi online per utenti e professionisti'], 'users', ['user-account-takeover', 'pro-account-abuse'], [
  ['Chaque téléservice est homologué et l’homologation est à jour', 'Each online service is accredited and the accreditation is current', 'Jeder Online-Dienst ist akkreditiert und die Akkreditierung ist aktuell', 'Cada teleservicio está homologado y la homologación está vigente', 'Ogni servizio online è omologato e l’omologazione è aggiornata'],
  ['Les opérations sensibles exigent une authentification renforcée', 'Sensitive operations require stronger authentication', 'Sensible Vorgänge erfordern verstärkte Authentifizierung', 'Las operaciones sensibles exigen una autenticación reforzada', 'Le operazioni sensibili richiedono un’autenticazione rafforzata'],
  ['Les abus automatisés sont détectés et bloqués', 'Automated abuse is detected and blocked', 'Automatisierter Missbrauch wird erkannt und blockiert', 'Los abusos automatizados se detectan y bloquean', 'Gli abusi automatizzati sono rilevati e bloccati'],
  ['Les volumes de consultation des professionnels sont supervisés', 'Professionals’ look-up volumes are monitored', 'Abrufmengen der Leistungserbringer werden überwacht', 'Se supervisan los volúmenes de consulta de los profesionales', 'I volumi di consultazione dei professionisti sono monitorati'],
])

export const PROTECTION_SOCIALE_PACK = b.pack
