/**
 * Packs SECTORIELS de contrôles-types, KRI candidats et missions d'audit types (catalogue 1.5).
 * Ils COMPLÈTENT le socle transversal (`sector-suggestions.ts`) sans le dupliquer et se rattachent
 * aux processus du secteur. Mêmes règles que le socle : suggestions à qualifier, jamais d'exécution,
 * de seuil, de valeur mesurée, de date, de notation ni de constat ; aucun libellé réglementaire présumé.
 * Contenu à soumettre à la revue métier (docs/specs/catalogue-revue-metier.md).
 */
import type { CatalogueItem, Localized, SectorCode } from './sector-suggestions'

const l = (fr: string, en: string, de: string, es: string, it: string): Localized => ({ fr, en, de, es, it })
type Periodicite = NonNullable<CatalogueItem['periodicite']>
const c = (sector: SectorCode, key: string, title: Localized, processKey: string, periodicite: Periodicite, controlType: NonNullable<CatalogueItem['controlType']>): CatalogueItem =>
  ({ key, sector, kind: 'CONTROL', title, processKey, periodicite, controlType })
const k = (sector: SectorCode, key: string, title: Localized, processKey: string, unite: Localized, sens: 'HAUSSE' | 'BAISSE', periodicite: Exclude<Periodicite, 'HEBDOMADAIRE'>): CatalogueItem =>
  ({ key, sector, kind: 'KRI', title, processKey, unite, sens, periodicite })
const a = (sector: SectorCode, key: string, title: Localized, processKey: string, points: Localized[]): CatalogueItem =>
  ({ key, sector, kind: 'AUDIT', title, processKey, points })

const pct = l('%', '%', '%', '%', '%')
const nb = l('nombre', 'count', 'Anzahl', 'número', 'numero')
const jours = l('jours', 'days', 'Tage', 'días', 'giorni')
const heures = l('heures', 'hours', 'Stunden', 'horas', 'ore')

export const SECTOR_PACK_ITEMS: CatalogueItem[] = [
  // ── Finance ────────────────────────────────────────────────────────────────
  c('FINANCE', 'finance.control.reconciliation', l('Revue des suspens de rapprochement non résolus', 'Review of unresolved reconciliation breaks', 'Überprüfung ungeklärter Abstimmungsdifferenzen', 'Revisión de las partidas de conciliación pendientes', 'Revisione delle partite di riconciliazione non risolte'), 'finance.process.payments', 'MENSUEL', 'DETECTIF'),
  c('FINANCE', 'finance.control.sanctions-alerts', l('Revue par échantillon des alertes de filtrage des sanctions clôturées', 'Sample review of closed sanctions-screening alerts', 'Stichprobenprüfung geschlossener Sanktions-Screening-Alarme', 'Revisión por muestreo de las alertas de filtrado de sanciones cerradas', 'Revisione a campione degli alert di screening sanzioni chiusi'), 'finance.process.payments', 'MENSUEL', 'DETECTIF'),
  k('FINANCE', 'finance.kri.reconciliation-breaks', l('Suspens de rapprochement de plus de 30 jours', 'Reconciliation breaks older than 30 days', 'Abstimmungsdifferenzen älter als 30 Tage', 'Partidas de conciliación con más de 30 días', 'Partite di riconciliazione aperte da oltre 30 giorni'), 'finance.process.payments', nb, 'HAUSSE', 'MENSUEL'),
  k('FINANCE', 'finance.kri.channel-availability', l('Disponibilité des canaux bancaires numériques', 'Availability of digital banking channels', 'Verfügbarkeit der digitalen Bankkanäle', 'Disponibilidad de los canales de banca digital', 'Disponibilità dei canali bancari digitali'), 'finance.process.channels', pct, 'BAISSE', 'MENSUEL'),
  a('FINANCE', 'finance.audit.payment-chain', l('Audit de la chaîne d’exécution des paiements', 'Audit of the payment execution chain', 'Audit der Zahlungsausführungskette', 'Auditoría de la cadena de ejecución de pagos', 'Audit della catena di esecuzione dei pagamenti'), 'finance.process.payments', [
    l('Les ordres de paiement sont autorisés selon les délégations en vigueur', 'Payment orders are authorised according to current delegations', 'Zahlungsaufträge werden gemäß den geltenden Vollmachten genehmigt', 'Las órdenes de pago se autorizan según las delegaciones vigentes', 'Gli ordini di pagamento sono autorizzati secondo le deleghe vigenti'),
    l('Les fichiers de paiement sont protégés contre toute modification entre validation et émission', 'Payment files are protected against alteration between approval and transmission', 'Zahlungsdateien sind zwischen Freigabe und Übermittlung gegen Veränderung geschützt', 'Los ficheros de pago están protegidos frente a modificaciones entre la validación y el envío', 'I file di pagamento sono protetti da modifiche tra approvazione e invio'),
    l('Les rejets et retours de paiement sont suivis jusqu’à leur résolution', 'Payment rejects and returns are tracked until resolved', 'Zahlungsrückweisungen und -rückläufer werden bis zur Klärung verfolgt', 'Los rechazos y devoluciones de pagos se siguen hasta su resolución', 'I rifiuti e i resi di pagamento sono seguiti fino alla risoluzione'),
    l('Un mode dégradé est prévu en cas d’indisponibilité du système de paiement', 'A fallback procedure exists if the payment system is unavailable', 'Für einen Ausfall des Zahlungssystems ist ein Notbetrieb vorgesehen', 'Existe un modo degradado en caso de indisponibilidad del sistema de pagos', 'È prevista una modalità degradata in caso di indisponibilità del sistema di pagamento'),
  ]),

  // ── Assurance ──────────────────────────────────────────────────────────────
  c('ASSURANCE', 'assurance.control.claims-sample', l('Contrôle par échantillon des sinistres indemnisés', 'Sample check of settled claims', 'Stichprobenprüfung regulierter Schäden', 'Control por muestreo de los siniestros indemnizados', 'Controllo a campione dei sinistri liquidati'), 'assurance.process.claims', 'MENSUEL', 'DETECTIF'),
  c('ASSURANCE', 'assurance.control.pricing-change', l('Revue des changements de paramètres tarifaires', 'Review of pricing parameter changes', 'Überprüfung von Änderungen an Tarifparametern', 'Revisión de los cambios de parámetros de tarificación', 'Revisione delle modifiche ai parametri tariffari'), 'assurance.process.underwrite', 'TRIMESTRIEL', 'DETECTIF'),
  k('ASSURANCE', 'assurance.kri.claims-backlog', l('Sinistres en attente au-delà du délai de traitement cible', 'Claims pending beyond the target handling time', 'Schäden, die über die Zielbearbeitungszeit hinaus offen sind', 'Siniestros pendientes más allá del plazo objetivo de tramitación', 'Sinistri in attesa oltre il tempo di gestione obiettivo'), 'assurance.process.claims', nb, 'HAUSSE', 'MENSUEL'),
  k('ASSURANCE', 'assurance.kri.broker-data-rejects', l('Taux de dossiers de distributeurs rejetés pour données incomplètes', 'Rate of distributor files rejected for incomplete data', 'Quote der wegen unvollständiger Daten abgelehnten Vertriebsakten', 'Tasa de expedientes de distribuidores rechazados por datos incompletos', 'Tasso di pratiche dei distributori respinte per dati incompleti'), 'assurance.process.brokers', pct, 'HAUSSE', 'MENSUEL'),
  a('ASSURANCE', 'assurance.audit.claims', l('Audit de la gestion des sinistres', 'Audit of claims handling', 'Audit der Schadenbearbeitung', 'Auditoría de la gestión de siniestros', 'Audit della gestione dei sinistri'), 'assurance.process.claims', [
    l('Les délégations de règlement sont définies et respectées', 'Settlement authorities are defined and respected', 'Regulierungsvollmachten sind festgelegt und werden eingehalten', 'Las delegaciones de liquidación están definidas y se respetan', 'Le deleghe di liquidazione sono definite e rispettate'),
    l('Les indicateurs de fraude sont examinés avant indemnisation', 'Fraud indicators are examined before settlement', 'Betrugsindikatoren werden vor der Regulierung geprüft', 'Los indicadores de fraude se examinan antes de indemnizar', 'Gli indicatori di frode sono esaminati prima della liquidazione'),
    l('Les délais de traitement sont suivis et les retards expliqués', 'Handling times are monitored and delays explained', 'Bearbeitungszeiten werden überwacht und Verzögerungen begründet', 'Los plazos de tramitación se siguen y los retrasos se justifican', 'I tempi di gestione sono monitorati e i ritardi motivati'),
    l('Les données de santé ou financières des assurés ne sont consultées qu’en cas de besoin', 'Policyholder health or financial data is accessed only when needed', 'Gesundheits- oder Finanzdaten der Versicherten werden nur bei Bedarf eingesehen', 'Los datos de salud o financieros de los asegurados solo se consultan cuando es necesario', 'I dati sanitari o finanziari degli assicurati sono consultati solo in caso di necessità'),
  ]),

  // ── Santé ──────────────────────────────────────────────────────────────────
  c('SANTE', 'sante.control.record-access', l('Revue des accès aux dossiers de santé hors parcours de soins', 'Review of health-record access outside the care pathway', 'Überprüfung von Zugriffen auf Gesundheitsakten außerhalb des Behandlungsverlaufs', 'Revisión de los accesos a historias clínicas fuera del proceso asistencial', 'Revisione degli accessi ai fascicoli sanitari al di fuori del percorso di cura'), 'sante.process.records', 'MENSUEL', 'DETECTIF'),
  c('SANTE', 'sante.control.specimen-identity', l('Contrôle par échantillon de l’identification des patients sur les prélèvements', 'Sample check of patient identification on specimens', 'Stichprobenprüfung der Patientenidentifikation an Proben', 'Control por muestreo de la identificación del paciente en las muestras', 'Controllo a campione dell’identificazione del paziente sui campioni'), 'sante.process.lab', 'MENSUEL', 'DETECTIF'),
  k('SANTE', 'sante.kri.care-downtime', l('Durée d’indisponibilité des applications de soins', 'Downtime of care applications', 'Ausfallzeit der Versorgungsanwendungen', 'Tiempo de indisponibilidad de las aplicaciones asistenciales', 'Tempo di indisponibilità delle applicazioni cliniche'), 'sante.process.care', heures, 'HAUSSE', 'MENSUEL'),
  k('SANTE', 'sante.kri.stockouts', l('Ruptures de médicaments ou dispositifs essentiels', 'Stockouts of essential medicines or devices', 'Engpässe bei wesentlichen Arzneimitteln oder Geräten', 'Roturas de stock de medicamentos o dispositivos esenciales', 'Rotture di stock di farmaci o dispositivi essenziali'), 'sante.process.supply', nb, 'HAUSSE', 'MENSUEL'),
  a('SANTE', 'sante.audit.records', l('Audit de la confidentialité des dossiers de santé', 'Audit of health-record confidentiality', 'Audit der Vertraulichkeit von Gesundheitsakten', 'Auditoría de la confidencialidad de las historias clínicas', 'Audit della riservatezza dei fascicoli sanitari'), 'sante.process.records', [
    l('Les profils d’accès correspondent aux fonctions des soignants', 'Access profiles match caregivers’ roles', 'Zugriffsprofile entsprechen den Funktionen des Pflegepersonals', 'Los perfiles de acceso corresponden a las funciones del personal sanitario', 'I profili di accesso corrispondono ai ruoli del personale sanitario'),
    l('Les accès sont tracés et les traces sont revues', 'Access is logged and logs are reviewed', 'Zugriffe werden protokolliert und die Protokolle überprüft', 'Los accesos quedan registrados y los registros se revisan', 'Gli accessi sono tracciati e i log vengono riesaminati'),
    l('Les accès d’urgence (« bris de glace ») sont justifiés a posteriori', 'Emergency (“break-glass”) access is justified afterwards', 'Notfallzugriffe („Break-Glass“) werden nachträglich begründet', 'Los accesos de urgencia («romper el cristal») se justifican a posteriori', 'Gli accessi di emergenza («break-glass») sono giustificati a posteriori'),
    l('Les consentements et oppositions des patients sont pris en compte', 'Patients’ consents and objections are taken into account', 'Einwilligungen und Widersprüche der Patienten werden berücksichtigt', 'Se tienen en cuenta los consentimientos y oposiciones de los pacientes', 'I consensi e le opposizioni dei pazienti sono presi in considerazione'),
  ]),

  // ── Secteur public ─────────────────────────────────────────────────────────
  c('PUBLIC', 'public.control.grant-sample', l('Contrôle par échantillon des aides versées', 'Sample check of grants paid', 'Stichprobenprüfung ausgezahlter Förderungen', 'Control por muestreo de las ayudas abonadas', 'Controllo a campione dei contributi erogati'), 'public.process.grants', 'TRIMESTRIEL', 'DETECTIF'),
  c('PUBLIC', 'public.control.open-data-review', l('Relecture des jeux de données avant publication en données ouvertes', 'Review of datasets before open-data publication', 'Prüfung von Datensätzen vor der Veröffentlichung als offene Daten', 'Revisión de los conjuntos de datos antes de su publicación como datos abiertos', 'Revisione dei dataset prima della pubblicazione come dati aperti'), 'public.process.citizens', 'MENSUEL', 'PREVENTIF'),
  k('PUBLIC', 'public.kri.portal-availability', l('Disponibilité des portails de services aux usagers', 'Availability of citizen service portals', 'Verfügbarkeit der Bürgerserviceportale', 'Disponibilidad de los portales de servicios a la ciudadanía', 'Disponibilità dei portali dei servizi ai cittadini'), 'public.process.citizens', pct, 'BAISSE', 'MENSUEL'),
  k('PUBLIC', 'public.kri.grant-corrections', l('Aides corrigées ou récupérées après versement', 'Grants corrected or recovered after payment', 'Nach Auszahlung korrigierte oder zurückgeforderte Förderungen', 'Ayudas corregidas o reintegradas tras su abono', 'Contributi rettificati o recuperati dopo l’erogazione'), 'public.process.grants', nb, 'HAUSSE', 'TRIMESTRIEL'),
  a('PUBLIC', 'public.audit.grants', l('Audit de l’instruction des aides et subventions', 'Audit of grant and subsidy processing', 'Audit der Bearbeitung von Förderungen und Zuschüssen', 'Auditoría de la tramitación de ayudas y subvenciones', 'Audit dell’istruttoria di contributi e sovvenzioni'), 'public.process.grants', [
    l('Les critères d’éligibilité sont documentés et appliqués de façon homogène', 'Eligibility criteria are documented and applied consistently', 'Förderkriterien sind dokumentiert und werden einheitlich angewandt', 'Los criterios de elegibilidad están documentados y se aplican de forma homogénea', 'I criteri di ammissibilità sono documentati e applicati in modo uniforme'),
    l('L’instruction et la décision sont confiées à des personnes différentes', 'Assessment and decision are performed by different people', 'Prüfung und Entscheidung erfolgen durch verschiedene Personen', 'La instrucción y la decisión corresponden a personas distintas', 'Istruttoria e decisione sono affidate a persone diverse'),
    l('Les pièces justificatives sont vérifiées avant versement', 'Supporting documents are checked before payment', 'Nachweise werden vor der Auszahlung geprüft', 'Los justificantes se verifican antes del abono', 'I documenti giustificativi sono verificati prima dell’erogazione'),
    l('Les versements indus sont détectés et récupérés', 'Undue payments are detected and recovered', 'Rechtsgrundlose Zahlungen werden erkannt und zurückgefordert', 'Los pagos indebidos se detectan y se reintegran', 'I pagamenti indebiti sono individuati e recuperati'),
  ]),

  // ── Logiciels et SaaS ──────────────────────────────────────────────────────
  c('SAAS', 'saas.control.release-review', l('Revue des mises en production sans validation ni plan de retour arrière', 'Review of releases without approval or rollback plan', 'Überprüfung von Releases ohne Freigabe oder Rückfallplan', 'Revisión de las puestas en producción sin validación ni plan de vuelta atrás', 'Revisione dei rilasci senza approvazione né piano di rollback'), 'saas.process.build', 'MENSUEL', 'DETECTIF'),
  c('SAAS', 'saas.control.support-access', l('Revue des accès du support aux environnements clients', 'Review of support access to customer environments', 'Überprüfung der Support-Zugriffe auf Kundenumgebungen', 'Revisión de los accesos del soporte a los entornos de clientes', 'Revisione degli accessi del supporto agli ambienti dei clienti'), 'saas.process.support', 'MENSUEL', 'DETECTIF'),
  k('SAAS', 'saas.kri.failed-changes', l('Taux de mises en production suivies d’un incident', 'Rate of releases followed by an incident', 'Quote der Releases mit nachfolgendem Vorfall', 'Tasa de puestas en producción seguidas de un incidente', 'Tasso di rilasci seguiti da un incidente'), 'saas.process.build', pct, 'HAUSSE', 'MENSUEL'),
  k('SAAS', 'saas.kri.platform-availability', l('Disponibilité de la plateforme pour les clients', 'Platform availability for customers', 'Verfügbarkeit der Plattform für Kunden', 'Disponibilidad de la plataforma para los clientes', 'Disponibilità della piattaforma per i clienti'), 'saas.process.host', pct, 'BAISSE', 'MENSUEL'),
  a('SAAS', 'saas.audit.change', l('Audit de la gestion des changements et des mises en production', 'Audit of change and release management', 'Audit des Änderungs- und Release-Managements', 'Auditoría de la gestión de cambios y puestas en producción', 'Audit della gestione dei cambiamenti e dei rilasci'), 'saas.process.build', [
    l('Chaque changement est relu par une autre personne que son auteur', 'Every change is reviewed by someone other than its author', 'Jede Änderung wird von einer anderen Person als dem Autor geprüft', 'Cada cambio es revisado por una persona distinta de su autor', 'Ogni modifica è rivista da una persona diversa dall’autore'),
    l('Les tests automatisés sont exécutés avant la mise en production', 'Automated tests run before release', 'Automatisierte Tests laufen vor dem Release', 'Las pruebas automatizadas se ejecutan antes de la puesta en producción', 'I test automatizzati sono eseguiti prima del rilascio'),
    l('Les secrets sont absents du code et des journaux', 'Secrets are kept out of code and logs', 'Geheimnisse sind weder im Code noch in Protokollen enthalten', 'Los secretos no figuran en el código ni en los registros', 'I segreti non compaiono nel codice né nei log'),
    l('Un retour arrière est possible et a été testé', 'Rollback is possible and has been tested', 'Ein Rollback ist möglich und wurde getestet', 'La vuelta atrás es posible y se ha probado', 'Il rollback è possibile ed è stato testato'),
  ]),

  // ── Industrie ──────────────────────────────────────────────────────────────
  c('INDUSTRIE', 'industrie.control.remote-access', l('Revue des accès de télémaintenance aux équipements industriels', 'Review of remote-maintenance access to industrial equipment', 'Überprüfung der Fernwartungszugänge zu Industrieanlagen', 'Revisión de los accesos de telemantenimiento a los equipos industriales', 'Revisione degli accessi di teleassistenza alle apparecchiature industriali'), 'industrie.process.maintain', 'TRIMESTRIEL', 'DETECTIF'),
  c('INDUSTRIE', 'industrie.control.batch-release', l('Contrôle par échantillon des libérations de lots', 'Sample check of batch releases', 'Stichprobenprüfung der Chargenfreigaben', 'Control por muestreo de la liberación de lotes', 'Controllo a campione dei rilasci dei lotti'), 'industrie.process.quality', 'MENSUEL', 'DETECTIF'),
  k('INDUSTRIE', 'industrie.kri.unplanned-stops', l('Heures d’arrêt non planifié de production', 'Hours of unplanned production stoppage', 'Stunden ungeplanter Produktionsstillstände', 'Horas de parada no planificada de producción', 'Ore di fermo produzione non pianificato'), 'industrie.process.produce', heures, 'HAUSSE', 'MENSUEL'),
  k('INDUSTRIE', 'industrie.kri.unsupported-ot', l('Équipements industriels dont le système n’est plus maintenu', 'Industrial equipment running unsupported systems', 'Industrieanlagen mit nicht mehr unterstützten Systemen', 'Equipos industriales con sistemas sin soporte', 'Apparecchiature industriali con sistemi non più supportati'), 'industrie.process.maintain', nb, 'HAUSSE', 'TRIMESTRIEL'),
  a('INDUSTRIE', 'industrie.audit.ot', l('Audit de la sécurité des systèmes industriels', 'Audit of industrial control system security', 'Audit der Sicherheit industrieller Steuerungssysteme', 'Auditoría de la seguridad de los sistemas industriales', 'Audit della sicurezza dei sistemi industriali'), 'industrie.process.produce', [
    l('Une cartographie à jour des équipements et des flux existe', 'An up-to-date map of equipment and flows exists', 'Eine aktuelle Übersicht über Anlagen und Datenflüsse liegt vor', 'Existe un inventario actualizado de equipos y flujos', 'Esiste una mappatura aggiornata di apparecchiature e flussi'),
    l('Les réseaux industriels sont séparés des réseaux de gestion', 'Industrial networks are separated from business networks', 'Industrienetze sind von den Büronetzen getrennt', 'Las redes industriales están separadas de las redes de gestión', 'Le reti industriali sono separate dalle reti gestionali'),
    l('Les accès de télémaintenance sont nominatifs, limités et tracés', 'Remote-maintenance access is individual, limited and logged', 'Fernwartungszugänge sind personengebunden, begrenzt und protokolliert', 'Los accesos de telemantenimiento son nominativos, limitados y trazados', 'Gli accessi di teleassistenza sono nominativi, limitati e tracciati'),
    l('Un mode de fonctionnement dégradé ou manuel est prévu et exercé', 'A degraded or manual operating mode is planned and exercised', 'Ein Notbetrieb oder manueller Betrieb ist vorgesehen und wird geübt', 'Existe un modo de funcionamiento degradado o manual que se ejercita', 'È prevista ed esercitata una modalità di funzionamento degradata o manuale'),
  ]),

  // ── Commerce ───────────────────────────────────────────────────────────────
  c('COMMERCE', 'commerce.control.price-changes', l('Revue des changements de prix publiés', 'Review of published price changes', 'Überprüfung veröffentlichter Preisänderungen', 'Revisión de los cambios de precios publicados', 'Revisione delle variazioni di prezzo pubblicate'), 'commerce.process.sell', 'HEBDOMADAIRE', 'DETECTIF'),
  c('COMMERCE', 'commerce.control.inventory-count', l('Inventaire tournant des stocks par échantillon', 'Sample cycle count of inventory', 'Stichprobenartige permanente Inventur', 'Inventario rotativo por muestreo de las existencias', 'Inventario rotativo a campione delle scorte'), 'commerce.process.stock', 'MENSUEL', 'DETECTIF'),
  k('COMMERCE', 'commerce.kri.stock-gaps', l('Écart entre stock théorique et stock compté', 'Gap between book and counted inventory', 'Abweichung zwischen Buch- und Zählbestand', 'Diferencia entre existencias teóricas y contadas', 'Scostamento tra giacenza teorica e giacenza contata'), 'commerce.process.stock', pct, 'HAUSSE', 'MENSUEL'),
  k('COMMERCE', 'commerce.kri.checkout-downtime', l('Durée d’indisponibilité de l’encaissement', 'Checkout downtime', 'Ausfallzeit der Kassensysteme', 'Tiempo de indisponibilidad del cobro', 'Tempo di indisponibilità delle casse'), 'commerce.process.sell', heures, 'HAUSSE', 'MENSUEL'),
  a('COMMERCE', 'commerce.audit.online-sales', l('Audit de la vente et de l’encaissement en ligne', 'Audit of online sales and payment collection', 'Audit des Online-Verkaufs und Zahlungseinzugs', 'Auditoría de la venta y el cobro en línea', 'Audit della vendita e dell’incasso online'), 'commerce.process.sell', [
    l('Les données de paiement ne sont pas conservées au-delà du nécessaire', 'Payment data is not kept longer than necessary', 'Zahlungsdaten werden nicht länger als nötig gespeichert', 'Los datos de pago no se conservan más de lo necesario', 'I dati di pagamento non sono conservati oltre il necessario'),
    l('Les comptes clients sont protégés contre la prise de contrôle', 'Customer accounts are protected against takeover', 'Kundenkonten sind gegen Übernahme geschützt', 'Las cuentas de clientes están protegidas frente a su usurpación', 'Gli account dei clienti sono protetti contro la presa di controllo'),
    l('Les changements de prix et de promotions sont validés avant publication', 'Price and promotion changes are approved before publication', 'Preis- und Aktionsänderungen werden vor der Veröffentlichung freigegeben', 'Los cambios de precios y promociones se validan antes de su publicación', 'Le modifiche di prezzi e promozioni sono approvate prima della pubblicazione'),
    l('Les encaissements sont rapprochés des commandes', 'Collected payments are reconciled with orders', 'Zahlungseingänge werden mit den Bestellungen abgeglichen', 'Los cobros se concilian con los pedidos', 'Gli incassi sono riconciliati con gli ordini'),
  ]),

  // ── Services professionnels ────────────────────────────────────────────────
  c('SERVICES', 'services.control.engagement-acceptance', l('Revue des acceptations de missions (conflits d’intérêts, périmètre)', 'Review of engagement acceptance (conflicts of interest, scope)', 'Überprüfung der Auftragsannahme (Interessenkonflikte, Umfang)', 'Revisión de la aceptación de encargos (conflictos de intereses, alcance)', 'Revisione dell’accettazione degli incarichi (conflitti di interesse, perimetro)'), 'services.process.contract', 'TRIMESTRIEL', 'DETECTIF'),
  c('SERVICES', 'services.control.unbilled-work', l('Revue des prestations réalisées non facturées', 'Review of delivered but unbilled work', 'Überprüfung erbrachter, nicht abgerechneter Leistungen', 'Revisión de los servicios prestados no facturados', 'Revisione delle prestazioni erogate non fatturate'), 'services.process.bill', 'MENSUEL', 'DETECTIF'),
  k('SERVICES', 'services.kri.missed-deadlines', l('Échéances clients manquées', 'Missed customer deadlines', 'Versäumte Kundenfristen', 'Plazos de clientes incumplidos', 'Scadenze dei clienti mancate'), 'services.process.perform', nb, 'HAUSSE', 'MENSUEL'),
  k('SERVICES', 'services.kri.unbilled-age', l('Ancienneté moyenne des prestations non facturées', 'Average age of unbilled work', 'Durchschnittsalter nicht abgerechneter Leistungen', 'Antigüedad media de los servicios no facturados', 'Anzianità media delle prestazioni non fatturate'), 'services.process.bill', jours, 'HAUSSE', 'MENSUEL'),
  a('SERVICES', 'services.audit.confidentiality', l('Audit de la confidentialité des dossiers clients', 'Audit of client file confidentiality', 'Audit der Vertraulichkeit von Kundenakten', 'Auditoría de la confidencialidad de los expedientes de clientes', 'Audit della riservatezza delle pratiche dei clienti'), 'services.process.knowledge', [
    l('Les dossiers clients ne sont accessibles qu’aux équipes de la mission', 'Client files are accessible only to the engagement team', 'Kundenakten sind nur für das Auftragsteam zugänglich', 'Los expedientes de clientes solo son accesibles para el equipo del encargo', 'Le pratiche dei clienti sono accessibili solo al team dell’incarico'),
    l('Les échanges de documents avec les clients passent par des canaux protégés', 'Document exchanges with clients use protected channels', 'Der Dokumentenaustausch mit Kunden erfolgt über geschützte Kanäle', 'Los intercambios de documentos con los clientes usan canales protegidos', 'Gli scambi di documenti con i clienti avvengono tramite canali protetti'),
    l('Les sous-traitants sont tenus à la confidentialité et perdent leurs accès en fin de mission', 'Subcontractors are bound by confidentiality and lose access at the end of the engagement', 'Subunternehmer sind zur Vertraulichkeit verpflichtet und verlieren ihren Zugang bei Auftragsende', 'Los subcontratistas están sujetos a confidencialidad y pierden el acceso al final del encargo', 'I subappaltatori sono vincolati alla riservatezza e perdono l’accesso a fine incarico'),
    l('Les dossiers sont archivés ou détruits selon la durée convenue', 'Files are archived or destroyed according to the agreed period', 'Akten werden nach der vereinbarten Frist archiviert oder vernichtet', 'Los expedientes se archivan o destruyen según el plazo acordado', 'Le pratiche sono archiviate o distrutte secondo il periodo concordato'),
  ]),
]
