/**
 * Catalogue 1.12 : compléments santé (portail d'accès aux données de santé, entrepôt de données de santé, flux reçus),
 * mutuelle santé (détournement de remboursements, délégation de gestion, flux de tiers payant) et nouveau secteur
 * « Technique / Interconnexion de SI » (prestataire qui livre des données, échange métier, API exposées, plateforme
 * d'intégration). Suggestions à qualifier : jamais d'exécution, de seuil, de date, de résultat ni de conformité acquise.
 * Les `references` citent le texte d'origine et sa version sans reproduire d'exigence. Contenu « à relire par un expert ».
 */
import { sectorPack, tagPatterns, U_NB, U_PCT, U_MIN } from './catalogue-pack-builder'

const ISO = 'ISO/IEC 27001:2022, annexe A'
const OWASP_API = 'OWASP API Security Top 10 — 2023'
const DORA = 'DORA — Règlement (UE) 2022/2554'
const RGPD = 'RGPD — Règlement (UE) 2016/679'

// ════════════════════════════ Santé — compléments ═══════════════════════════
const sante = sectorPack('SANTE')
sante.process('portal', ['Ouvrir l’accès des patients et des professionnels aux données de santé', 'Open health data access to patients and professionals', 'Patienten und Fachkräften Zugang zu Gesundheitsdaten geben', 'Abrir el acceso de pacientes y profesionales a los datos de salud', 'Aprire l’accesso di pazienti e professionisti ai dati sanitari'], 'sante.process.records')
sante.process('reuse', ['Réutiliser les données de santé pour la recherche', 'Reuse health data for research', 'Gesundheitsdaten für die Forschung weiterverwenden', 'Reutilizar los datos de salud para la investigación', 'Riutilizzare i dati sanitari per la ricerca'], 'sante.process.records')
sante.risk('portal-account-takeover', 2, ['Un compte patient du portail est usurpé et ses documents de santé sont consultés', 'A patient portal account is taken over and its health documents are viewed', 'Ein Patientenkonto im Portal wird übernommen und seine Gesundheitsdokumente werden eingesehen', 'Se usurpa una cuenta de paciente del portal y se consultan sus documentos de salud', 'Un account paziente del portale viene usurpato e i suoi documenti sanitari vengono consultati'], 'portal')
sante.risk('portal-object-authz', 4, ['Un défaut d’autorisation de l’API du portail expose les documents d’autres patients', 'An authorisation flaw in the portal API exposes other patients’ documents', 'Ein Autorisierungsfehler der Portal-API legt Dokumente anderer Patienten offen', 'Un fallo de autorización de la API del portal expone documentos de otros pacientes', 'Un difetto di autorizzazione dell’API del portale espone i documenti di altri pazienti'], 'portal')
sante.risk('portal-wrong-patient', 7, ['Un document est publié sur le portail d’un autre patient (erreur d’identité)', 'A document is published to another patient’s portal account (identity error)', 'Ein Dokument wird im Portal eines anderen Patienten veröffentlicht (Identitätsfehler)', 'Se publica un documento en el portal de otro paciente (error de identidad)', 'Un documento viene pubblicato sul portale di un altro paziente (errore di identità)'], 'portal')
sante.risk('eds-reidentification', 4, ['Des patients sont réidentifiés à partir de données pseudonymisées de recherche', 'Patients are re-identified from pseudonymised research data', 'Patienten werden aus pseudonymisierten Forschungsdaten re-identifiziert', 'Se reidentifica a pacientes a partir de datos de investigación seudonimizados', 'Pazienti vengono reidentificati a partire da dati di ricerca pseudonimizzati'], 'reuse')
sante.risk('eds-export', 1, ['Des données de santé sortent de l’espace de recherche sécurisé hors autorisation', 'Health data leaves the secure research workspace without authorisation', 'Gesundheitsdaten verlassen die sichere Forschungsumgebung ohne Genehmigung', 'Datos de salud salen del espacio de investigación seguro sin autorización', 'Dati sanitari escono dall’ambiente di ricerca sicuro senza autorizzazione'], 'reuse')
sante.risk('feed-integrity', 7, ['Un flux reçu d’un laboratoire, d’un prestataire ou d’un établissement partenaire est altéré ou rattaché au mauvais dossier', 'A flow received from a laboratory, provider or partner facility is altered or matched to the wrong record', 'Ein von einem Labor, Dienstleister oder Partner empfangener Datenfluss ist verändert oder wird der falschen Akte zugeordnet', 'Un flujo recibido de un laboratorio, proveedor o centro asociado está alterado o vinculado a la historia equivocada', 'Un flusso ricevuto da un laboratorio, fornitore o struttura partner è alterato o abbinato al fascicolo sbagliato'], 'sante.process.records')
sante.control('portal-mfa-coverage', ['Vérification de la couverture du double facteur sur les comptes du portail (patients et professionnels)', 'Check of two-factor coverage on portal accounts (patients and professionals)', 'Prüfung der Zwei-Faktor-Abdeckung der Portalkonten (Patienten und Fachkräfte)', 'Verificación de la cobertura del doble factor en las cuentas del portal (pacientes y profesionales)', 'Verifica della copertura del doppio fattore sugli account del portale (pazienti e professionisti)'], 'portal', 'MENSUEL', 'DETECTIF', ['portal-account-takeover'], [`${ISO}, mesure 8.5`])
sante.control('portal-authz-tests', ['Tests du contrôle d’autorisation objet par objet de l’API du portail', 'Testing of object-level authorisation on the portal API', 'Tests der Autorisierung auf Objektebene der Portal-API', 'Pruebas del control de autorización objeto por objeto de la API del portal', 'Test del controllo di autorizzazione oggetto per oggetto dell’API del portale'], 'portal', 'TRIMESTRIEL', 'DETECTIF', ['portal-object-authz'], [`${OWASP_API}, API1`])
sante.control('portal-identity-check', ['Contrôle par échantillon du rapprochement d’identité (INS) des documents publiés sur le portail', 'Sample check of identity matching (INS) of documents published on the portal', 'Stichprobenprüfung des Identitätsabgleichs (INS) der im Portal veröffentlichten Dokumente', 'Control por muestreo del cotejo de identidad (INS) de los documentos publicados en el portal', 'Controllo a campione del riscontro di identità (INS) dei documenti pubblicati sul portale'], 'portal', 'MENSUEL', 'DETECTIF', ['portal-wrong-patient'], ['Code de la santé publique, art. L. 1111-8-1 (identifiant national de santé)'])
sante.control('eds-export-review', ['Revue des demandes de sortie de résultats de l’espace de recherche', 'Review of output requests from the research workspace', 'Prüfung der Ausgabeanträge aus der Forschungsumgebung', 'Revisión de las solicitudes de salida de resultados del espacio de investigación', 'Revisione delle richieste di uscita dei risultati dall’ambiente di ricerca'], 'reuse', 'MENSUEL', 'DETECTIF', ['eds-export', 'eds-reidentification'], ['CNIL — référentiel relatif aux entrepôts de données de santé (2021)'])
sante.control('eds-reid-check', ['Analyse du risque de réidentification avant chaque mise à disposition de données', 'Re-identification risk analysis before each data release', 'Analyse des Re-Identifizierungsrisikos vor jeder Datenbereitstellung', 'Análisis del riesgo de reidentificación antes de cada puesta a disposición de datos', 'Analisi del rischio di reidentificazione prima di ogni messa a disposizione dei dati'], 'reuse', 'TRIMESTRIEL', 'PREVENTIF', ['eds-reidentification'])
sante.control('eds-project-rights', ['Revue des habilitations par projet de recherche et fermeture à échéance', 'Review of access rights per research project and closure at expiry', 'Überprüfung der Berechtigungen je Forschungsprojekt und Schließung bei Ablauf', 'Revisión de las habilitaciones por proyecto de investigación y cierre al vencimiento', 'Revisione delle abilitazioni per progetto di ricerca e chiusura alla scadenza'], 'reuse', 'SEMESTRIEL', 'DETECTIF', ['eds-export'])
sante.control('feed-integrity-check', ['Contrôle des rejets et anomalies d’identité des flux reçus (laboratoires, prestataires, partenaires)', 'Check of rejections and identity anomalies in received flows (laboratories, providers, partners)', 'Kontrolle von Ablehnungen und Identitätsauffälligkeiten empfangener Datenflüsse (Labore, Dienstleister, Partner)', 'Control de rechazos y anomalías de identidad de los flujos recibidos (laboratorios, proveedores, socios)', 'Controllo di scarti e anomalie di identità dei flussi ricevuti (laboratori, fornitori, partner)'], 'sante.process.records', 'MENSUEL', 'DETECTIF', ['feed-integrity'])
sante.kri('portal-takeovers', ['Comptes du portail signalés comme usurpés', 'Portal accounts reported as taken over', 'Als übernommen gemeldete Portalkonten', 'Cuentas del portal notificadas como usurpadas', 'Account del portale segnalati come usurpati'], 'portal', U_NB, 'HAUSSE', 'MENSUEL')
sante.kri('portal-mfa-rate', ['Part des comptes du portail protégés par un double facteur', 'Share of portal accounts protected by two-factor authentication', 'Anteil der durch Zwei-Faktor geschützten Portalkonten', 'Proporción de cuentas del portal protegidas por doble factor', 'Quota di account del portale protetti da doppio fattore'], 'portal', U_PCT, 'BAISSE', 'MENSUEL')
sante.kri('eds-refused-outputs', ['Sorties de résultats refusées par le contrôle de l’espace de recherche', 'Outputs refused by the research workspace check', 'Von der Kontrolle der Forschungsumgebung abgelehnte Ausgaben', 'Salidas de resultados rechazadas por el control del espacio de investigación', 'Uscite di risultati rifiutate dal controllo dell’ambiente di ricerca'], 'reuse', U_NB, 'HAUSSE', 'MENSUEL')
sante.kri('feed-rejects', ['Taux de rejet des flux reçus', 'Rejection rate of received flows', 'Ablehnungsquote empfangener Datenflüsse', 'Tasa de rechazo de los flujos recibidos', 'Tasso di scarto dei flussi ricevuti'], 'sante.process.records', U_PCT, 'HAUSSE', 'MENSUEL')
sante.audit('portal', ['Audit de la sécurité du portail d’accès aux données de santé', 'Audit of the health-data access portal security', 'Audit der Sicherheit des Zugangsportals für Gesundheitsdaten', 'Auditoría de la seguridad del portal de acceso a datos de salud', 'Audit della sicurezza del portale di accesso ai dati sanitari'], 'portal', ['portal-account-takeover', 'portal-object-authz', 'portal-wrong-patient'], [
  ['L’authentification des patients et des professionnels résiste à l’usurpation de compte', 'Patient and professional authentication resists account takeover', 'Die Authentifizierung von Patienten und Fachkräften widersteht Kontoübernahmen', 'La autenticación de pacientes y profesionales resiste la usurpación de cuentas', 'L’autenticazione di pazienti e professionisti resiste all’usurpazione degli account'],
  ['Chaque appel de l’API vérifie le droit d’accès au document demandé', 'Every API call checks the right to access the requested document', 'Jeder API-Aufruf prüft das Zugriffsrecht auf das angeforderte Dokument', 'Cada llamada a la API verifica el derecho de acceso al documento solicitado', 'Ogni chiamata API verifica il diritto di accesso al documento richiesto'],
  ['Aucun document n’est publié sans identité qualifiée et validation', 'No document is published without a qualified identity and validation', 'Kein Dokument wird ohne qualifizierte Identität und Freigabe veröffentlicht', 'Ningún documento se publica sin identidad cualificada y validación', 'Nessun documento viene pubblicato senza identità qualificata e validazione'],
  ['Les accès anormaux sont détectés et traités', 'Abnormal access is detected and handled', 'Auffällige Zugriffe werden erkannt und behandelt', 'Los accesos anómalos se detectan y se tratan', 'Gli accessi anomali sono rilevati e gestiti'],
])
sante.audit('eds', ['Audit de l’entrepôt de données de santé et de son espace de recherche', 'Audit of the health data warehouse and its research workspace', 'Audit des Gesundheitsdaten-Warehouse und seiner Forschungsumgebung', 'Auditoría del almacén de datos de salud y de su espacio de investigación', 'Audit del data warehouse sanitario e del suo ambiente di ricerca'], 'reuse', ['eds-reidentification', 'eds-export'], [
  ['Chaque projet dispose d’une autorisation et d’un périmètre de données documentés', 'Each project has a documented authorisation and data scope', 'Jedes Projekt hat eine dokumentierte Genehmigung und einen Datenumfang', 'Cada proyecto dispone de una autorización y un perímetro de datos documentados', 'Ogni progetto dispone di un’autorizzazione e di un perimetro di dati documentati'],
  ['La table de correspondance des pseudonymes est séparée et protégée', 'The pseudonym mapping table is separated and protected', 'Die Zuordnungstabelle der Pseudonyme ist getrennt und geschützt', 'La tabla de correspondencia de seudónimos está separada y protegida', 'La tabella di corrispondenza degli pseudonimi è separata e protetta'],
  ['Les sorties de résultats sont contrôlées avant diffusion', 'Outputs are checked before release', 'Ausgaben werden vor der Freigabe geprüft', 'Las salidas de resultados se controlan antes de su difusión', 'Le uscite dei risultati sono controllate prima della diffusione'],
  ['Les oppositions des patients sont appliquées à tous les projets', 'Patient objections are applied to all projects', 'Widersprüche von Patienten werden auf alle Projekte angewendet', 'Las oposiciones de los pacientes se aplican a todos los proyectos', 'Le opposizioni dei pazienti sono applicate a tutti i progetti'],
])

// ════════════════════════════ Mutuelle santé — compléments ══════════════════
const ass = sectorPack('ASSURANCE')
ass.risk('iban-diversion', 2, ['Des remboursements sont détournés par la modification des coordonnées bancaires d’adhérents', 'Reimbursements are diverted by changing members’ bank details', 'Erstattungen werden durch Änderung der Bankverbindung von Mitgliedern umgeleitet', 'Se desvían reembolsos mediante la modificación de los datos bancarios de afiliados', 'I rimborsi vengono dirottati modificando le coordinate bancarie degli iscritti'], 'assurance.process.claims')
ass.risk('delegate-segregation', 4, ['Un délégataire de gestion expose les données des adhérents à un autre organisme ou à un tiers', 'A delegated administrator exposes members’ data to another insurer or a third party', 'Ein beauftragter Verwaltungsdienstleister legt Mitgliederdaten einem anderen Versicherer oder Dritten offen', 'Un gestor delegado expone los datos de los afiliados a otra entidad o a un tercero', 'Un gestore delegato espone i dati degli iscritti a un altro ente o a terzi'], 'assurance.process.claims')
ass.risk('tpa-feed', 7, ['Un flux de tiers payant ou de décomptes reçu est erroné et entraîne des paiements indus', 'A received direct-billing or statement flow is wrong and leads to undue payments', 'Ein empfangener Direktabrechnungs- oder Abrechnungsdatenfluss ist fehlerhaft und führt zu unberechtigten Zahlungen', 'Un flujo de tercero pagador o de liquidaciones recibido es erróneo y provoca pagos indebidos', 'Un flusso di terzo pagante o di estratti ricevuto è errato e provoca pagamenti indebiti'], 'assurance.process.claims')
ass.control('iban-change-review', ['Contrôle par échantillon des changements de coordonnées bancaires d’adhérents (confirmation, délai, double validation)', 'Sample check of members’ bank detail changes (confirmation, cooling-off, dual approval)', 'Stichprobenkontrolle von Änderungen der Bankverbindung von Mitgliedern (Bestätigung, Frist, Vier-Augen-Prinzip)', 'Control por muestreo de los cambios de datos bancarios de afiliados (confirmación, plazo, doble validación)', 'Controllo a campione delle modifiche delle coordinate bancarie degli iscritti (conferma, termine, doppia validazione)'], 'assurance.process.claims', 'MENSUEL', 'DETECTIF', ['iban-diversion'])
ass.control('member-area-mfa', ['Vérification de l’authentification forte de l’espace adhérent pour les opérations sensibles', 'Check of strong authentication in the member area for sensitive operations', 'Prüfung der starken Authentifizierung im Mitgliederbereich für sensible Vorgänge', 'Verificación de la autenticación fuerte del área de afiliado para operaciones sensibles', 'Verifica dell’autenticazione forte dell’area iscritti per le operazioni sensibili'], 'assurance.process.claims', 'SEMESTRIEL', 'DETECTIF', ['iban-diversion'])
ass.control('delegate-reporting', ['Revue des rapports de sécurité, d’incidents et de contrôle remis par les délégataires de gestion', 'Review of security, incident and control reports from delegated administrators', 'Prüfung der Sicherheits-, Vorfall- und Kontrollberichte der beauftragten Verwaltungsdienstleister', 'Revisión de los informes de seguridad, incidentes y control de los gestores delegados', 'Revisione dei rapporti di sicurezza, incidenti e controllo dei gestori delegati'], 'assurance.process.claims', 'TRIMESTRIEL', 'DETECTIF', ['delegate-segregation'], ['Directive 2009/138/CE (Solvabilité II), art. 49', 'Règlement délégué (UE) 2015/35, art. 274'])
ass.control('tpa-feed-reconciliation', ['Rapprochement des flux de tiers payant et de décomptes avec les paiements (totaux de contrôle, doublons)', 'Reconciliation of direct-billing and statement flows with payments (control totals, duplicates)', 'Abgleich der Direktabrechnungs- und Abrechnungsdatenflüsse mit den Zahlungen (Kontrollsummen, Dubletten)', 'Conciliación de los flujos de tercero pagador y liquidaciones con los pagos (totales de control, duplicados)', 'Riconciliazione dei flussi di terzo pagante e degli estratti con i pagamenti (totali di controllo, duplicati)'], 'assurance.process.claims', 'MENSUEL', 'DETECTIF', ['tpa-feed'])
ass.kri('iban-changes', ['Changements de coordonnées bancaires d’adhérents', 'Members’ bank detail changes', 'Änderungen der Bankverbindung von Mitgliedern', 'Cambios de datos bancarios de afiliados', 'Modifiche delle coordinate bancarie degli iscritti'], 'assurance.process.claims', U_NB, 'HAUSSE', 'MENSUEL')
ass.kri('tpa-feed-gaps', ['Écarts de rapprochement des flux de tiers payant', 'Direct-billing flow reconciliation gaps', 'Abgleichsdifferenzen der Direktabrechnungsdatenflüsse', 'Diferencias de conciliación de los flujos de tercero pagador', 'Scostamenti di riconciliazione dei flussi di terzo pagante'], 'assurance.process.claims', U_NB, 'HAUSSE', 'MENSUEL')

// ════════════════════════ Technique / Interconnexion de SI ══════════════════
const tq = sectorPack('TRANSVERSAL', 'technique')
tq.process('exchange', ['Exploiter les échanges de données entre systèmes d’information', 'Operate data exchanges between information systems', 'Datenaustausch zwischen IT-Systemen betreiben', 'Operar los intercambios de datos entre sistemas de información', 'Gestire gli scambi di dati tra sistemi informativi'], 'core.process.digital')
tq.process('onboard', ['Raccorder et suivre les partenaires et prestataires interconnectés', 'Connect and monitor interconnected partners and providers', 'Gekoppelte Partner und Dienstleister anbinden und überwachen', 'Conectar y supervisar a los socios y proveedores interconectados', 'Collegare e monitorare partner e fornitori interconnessi'], 'core.process.buy')
tq.process('receive', ['Recevoir et intégrer les données livrées par des tiers', 'Receive and integrate data delivered by third parties', 'Von Dritten gelieferte Daten empfangen und übernehmen', 'Recibir e integrar los datos entregados por terceros', 'Ricevere e integrare i dati consegnati da terzi'], 'exchange')
tq.process('expose', ['Exposer des API à des partenaires et clients', 'Expose APIs to partners and customers', 'APIs für Partner und Kunden bereitstellen', 'Exponer API a socios y clientes', 'Esporre API a partner e clienti'], 'exchange')
tq.process('integrate', ['Administrer la plateforme d’intégration et de transfert de fichiers', 'Administer the integration and file-transfer platform', 'Integrations- und Dateitransferplattform administrieren', 'Administrar la plataforma de integración y de transferencia de ficheros', 'Amministrare la piattaforma di integrazione e di trasferimento file'], 'exchange')

tq.risk('forged-feed', 2, ['Des données falsifiées reçues d’un partenaire compromis sont intégrées dans les traitements', 'Falsified data received from a compromised partner is integrated into processing', 'Von einem kompromittierten Partner empfangene gefälschte Daten werden in die Verarbeitung übernommen', 'Datos falsificados recibidos de un socio comprometido se integran en los tratamientos', 'Dati falsificati ricevuti da un partner compromesso vengono integrati nelle elaborazioni'], 'receive')
tq.risk('corrupt-feed', 7, ['Un fichier reçu incomplet, corrompu ou rejoué est intégré sans détection', 'An incomplete, corrupted or replayed file is integrated without detection', 'Eine unvollständige, beschädigte oder wiederholt eingespielte Datei wird unbemerkt übernommen', 'Un fichero recibido incompleto, corrupto o reenviado se integra sin detección', 'Un file ricevuto incompleto, corrotto o riprodotto viene integrato senza rilevamento'], 'receive')
tq.risk('late-feed', 6, ['Une livraison attendue n’arrive pas et son absence n’est pas détectée', 'An expected delivery does not arrive and its absence goes unnoticed', 'Eine erwartete Lieferung bleibt aus und ihr Fehlen wird nicht bemerkt', 'Una entrega esperada no llega y su ausencia no se detecta', 'Una consegna attesa non arriva e la sua assenza non viene rilevata'], 'receive')
tq.risk('format-change', 7, ['Un changement de format non annoncé fausse l’intégration des données', 'An unannounced format change distorts data integration', 'Eine unangekündigte Formatänderung verfälscht die Datenübernahme', 'Un cambio de formato no anunciado falsea la integración de los datos', 'Un cambio di formato non annunciato falsa l’integrazione dei dati'], 'receive')
tq.risk('secret-theft', 2, ['Un secret d’API ou une clé d’échange est volé et réutilisé', 'An API secret or exchange key is stolen and reused', 'Ein API-Geheimnis oder Austauschschlüssel wird gestohlen und wiederverwendet', 'Se roba y reutiliza un secreto de API o una clave de intercambio', 'Un segreto API o una chiave di scambio viene rubato e riutilizzato'], 'exchange')
tq.risk('pivot', 6, ['Un attaquant rebondit depuis un partenaire interconnecté vers le système d’information interne', 'An attacker pivots from an interconnected partner into the internal information system', 'Ein Angreifer gelangt über einen gekoppelten Partner in das interne IT-System', 'Un atacante salta desde un socio interconectado hacia el sistema de información interno', 'Un attaccante rimbalza da un partner interconnesso verso il sistema informativo interno'], 'exchange')
tq.risk('over-sharing', 4, ['Des données personnelles sont transmises au-delà du besoin du partenaire', 'Personal data is sent beyond the partner’s needs', 'Personenbezogene Daten werden über den Bedarf des Partners hinaus übermittelt', 'Se transmiten datos personales más allá de la necesidad del socio', 'Dati personali vengono trasmessi oltre il fabbisogno del partner'], 'exchange')
tq.risk('api-bola', 4, ['Une API exposée laisse accéder aux données d’autres clients', 'An exposed API allows access to other customers’ data', 'Eine bereitgestellte API ermöglicht den Zugriff auf Daten anderer Kunden', 'Una API expuesta permite acceder a los datos de otros clientes', 'Un’API esposta consente di accedere ai dati di altri clienti'], 'expose')
tq.risk('api-abuse', 2, ['Une API est moissonnée ou saturée par un usage automatisé', 'An API is scraped or overloaded by automated use', 'Eine API wird durch automatisierte Nutzung abgegriffen oder überlastet', 'Una API es objeto de recolección o saturación por un uso automatizado', 'Un’API viene sottoposta a scraping o saturata da un uso automatizzato'], 'expose')
tq.risk('platform-compromise', 6, ['La plateforme d’intégration est compromise et donne accès à toutes les applications reliées', 'The integration platform is compromised and gives access to all linked applications', 'Die Integrationsplattform wird kompromittiert und verschafft Zugriff auf alle verbundenen Anwendungen', 'La plataforma de integración se ve comprometida y da acceso a todas las aplicaciones enlazadas', 'La piattaforma di integrazione viene compromessa e dà accesso a tutte le applicazioni collegate'], 'integrate')
tq.risk('platform-outage', 6, ['Une panne de la plateforme d’intégration bloque l’ensemble des flux', 'An integration platform outage blocks all flows', 'Ein Ausfall der Integrationsplattform blockiert alle Datenflüsse', 'Una avería de la plataforma de integración bloquea todos los flujos', 'Un guasto della piattaforma di integrazione blocca tutti i flussi'], 'integrate')
tq.risk('partner-lockin', 7, ['La sortie d’un prestataire interconnecté est impossible faute de réversibilité', 'Exiting an interconnected provider is impossible for lack of reversibility', 'Der Ausstieg aus einem gekoppelten Dienstleister ist mangels Reversibilität unmöglich', 'La salida de un proveedor interconectado es imposible por falta de reversibilidad', 'L’uscita da un fornitore interconnesso è impossibile per mancanza di reversibilità'], 'onboard')
tq.risk('unmanaged-interco', 7, ['Une interconnexion existe sans convention ni propriétaire identifié', 'An interconnection exists without an agreement or an identified owner', 'Eine Kopplung besteht ohne Vereinbarung oder benannten Verantwortlichen', 'Existe una interconexión sin convenio ni propietario identificado', 'Esiste un’interconnessione senza convenzione né responsabile identificato'], 'onboard')

tq.control('interco-inventory', ['Revue de l’inventaire des interconnexions et de leur nécessité', 'Review of the interconnection inventory and its necessity', 'Überprüfung des Kopplungsverzeichnisses und seiner Notwendigkeit', 'Revisión del inventario de interconexiones y de su necesidad', 'Revisione dell’inventario delle interconnessioni e della loro necessità'], 'onboard', 'ANNUEL', 'DETECTIF', ['unmanaged-interco'], [`${ISO}, mesure 5.9`])
tq.control('interco-agreement', ['Vérification qu’une convention d’interconnexion signée existe pour chaque flux', 'Check that a signed interconnection agreement exists for each flow', 'Prüfung, dass für jeden Datenfluss eine unterzeichnete Kopplungsvereinbarung vorliegt', 'Verificación de que existe un convenio de interconexión firmado para cada flujo', 'Verifica dell’esistenza di una convenzione di interconnessione firmata per ogni flusso'], 'onboard', 'ANNUEL', 'PREVENTIF', ['unmanaged-interco', 'over-sharing', 'pivot'], [`${ISO}, mesure 5.14`])
tq.control('partner-assessment', ['Évaluation de la sécurité des partenaires et prestataires avant raccordement puis chaque année', 'Security assessment of partners and providers before connection, then yearly', 'Sicherheitsbewertung von Partnern und Dienstleistern vor dem Anschluss und danach jährlich', 'Evaluación de la seguridad de socios y proveedores antes de la conexión y luego cada año', 'Valutazione della sicurezza di partner e fornitori prima del collegamento e poi ogni anno'], 'onboard', 'ANNUEL', 'PREVENTIF', ['pivot', 'forged-feed'], [`${ISO}, mesure 5.19`])
tq.control('contract-clauses', ['Vérification des clauses contractuelles (sécurité, notification d’incident, audit, réversibilité)', 'Check of contractual clauses (security, incident notification, audit, reversibility)', 'Prüfung der Vertragsklauseln (Sicherheit, Vorfallmeldung, Audit, Reversibilität)', 'Verificación de las cláusulas contractuales (seguridad, notificación de incidentes, auditoría, reversibilidad)', 'Verifica delle clausole contrattuali (sicurezza, notifica degli incidenti, audit, reversibilità)'], 'onboard', 'ANNUEL', 'PREVENTIF', ['partner-lockin', 'pivot'], [`${ISO}, mesure 5.20`, `${DORA}, art. 30`])
tq.control('exit-plan-test', ['Test du plan de sortie d’un prestataire interconnecté critique', 'Test of the exit plan for a critical interconnected provider', 'Test des Ausstiegsplans für einen kritischen gekoppelten Dienstleister', 'Prueba del plan de salida de un proveedor interconectado crítico', 'Test del piano di uscita da un fornitore interconnesso critico'], 'onboard', 'ANNUEL', 'DETECTIF', ['partner-lockin'], [`${DORA}, art. 28`])
tq.control('flow-filtering-review', ['Revue des règles de filtrage des flux d’interconnexion', 'Review of interconnection flow filtering rules', 'Überprüfung der Filterregeln der Kopplungsdatenflüsse', 'Revisión de las reglas de filtrado de los flujos de interconexión', 'Revisione delle regole di filtraggio dei flussi di interconnessione'], 'exchange', 'SEMESTRIEL', 'DETECTIF', ['pivot'], [`${ISO}, mesure 8.22`])
tq.control('secret-rotation', ['Vérification de la rotation des secrets d’API, clés et certificats d’échange', 'Check of rotation of API secrets, exchange keys and certificates', 'Prüfung der Rotation von API-Geheimnissen, Austauschschlüsseln und Zertifikaten', 'Verificación de la rotación de secretos de API, claves y certificados de intercambio', 'Verifica della rotazione di segreti API, chiavi e certificati di scambio'], 'exchange', 'TRIMESTRIEL', 'DETECTIF', ['secret-theft'])
tq.control('technical-accounts-review', ['Revue des comptes techniques d’échange et de leurs droits', 'Review of technical exchange accounts and their rights', 'Überprüfung der technischen Austauschkonten und ihrer Rechte', 'Revisión de las cuentas técnicas de intercambio y de sus derechos', 'Revisione degli account tecnici di scambio e dei relativi diritti'], 'exchange', 'TRIMESTRIEL', 'DETECTIF', ['secret-theft', 'platform-compromise'])
tq.control('completeness-check', ['Contrôle par échantillon des contrôles de complétude et d’intégrité des livraisons (comptes, totaux, empreintes)', 'Sample check of delivery completeness and integrity checks (counts, totals, hashes)', 'Stichprobenprüfung der Vollständigkeits- und Integritätskontrollen der Lieferungen (Anzahl, Summen, Hashes)', 'Control por muestreo de los controles de completitud e integridad de las entregas (recuentos, totales, huellas)', 'Controllo a campione dei controlli di completezza e integrità delle consegne (conteggi, totali, impronte)'], 'receive', 'MENSUEL', 'DETECTIF', ['corrupt-feed', 'forged-feed'])
tq.control('quarantine-review', ['Revue des livraisons mises en quarantaine et de leur traitement', 'Review of quarantined deliveries and how they were handled', 'Überprüfung der in Quarantäne gestellten Lieferungen und ihrer Behandlung', 'Revisión de las entregas en cuarentena y de su tratamiento', 'Revisione delle consegne messe in quarantena e del loro trattamento'], 'receive', 'MENSUEL', 'DETECTIF', ['forged-feed', 'format-change'])
tq.control('replay-detection-test', ['Test de la détection des rejeux de livraisons', 'Test of delivery replay detection', 'Test der Erkennung wiederholt eingespielter Lieferungen', 'Prueba de la detección de reenvíos de entregas', 'Test del rilevamento delle consegne riprodotte'], 'receive', 'SEMESTRIEL', 'DETECTIF', ['corrupt-feed'])
tq.control('late-delivery-alerts', ['Revue des alertes de retard ou d’absence de livraison', 'Review of late or missing delivery alerts', 'Überprüfung der Alarme bei verspäteten oder fehlenden Lieferungen', 'Revisión de las alertas de retraso o ausencia de entrega', 'Revisione degli allarmi di ritardo o mancata consegna'], 'receive', 'MENSUEL', 'DETECTIF', ['late-feed'])
tq.control('change-notice', ['Vérification que chaque changement de format annoncé a fait l’objet d’une recette commune', 'Check that each announced format change went through joint acceptance testing', 'Prüfung, dass jede angekündigte Formatänderung gemeinsam abgenommen wurde', 'Verificación de que cada cambio de formato anunciado ha sido objeto de una recepción conjunta', 'Verifica che ogni cambio di formato annunciato sia stato oggetto di un collaudo congiunto'], 'receive', 'TRIMESTRIEL', 'PREVENTIF', ['format-change'], [`${ISO}, mesure 5.22`])
tq.control('reconciliation', ['Rapprochement périodique des données échangées entre les deux systèmes', 'Periodic reconciliation of data exchanged between the two systems', 'Regelmäßiger Abgleich der zwischen beiden Systemen ausgetauschten Daten', 'Conciliación periódica de los datos intercambiados entre ambos sistemas', 'Riconciliazione periodica dei dati scambiati tra i due sistemi'], 'exchange', 'MENSUEL', 'DETECTIF', ['corrupt-feed'])
tq.control('data-minimisation-review', ['Revue de la minimisation des données transmises à chaque partenaire', 'Review of minimisation of data sent to each partner', 'Überprüfung der Minimierung der an jeden Partner übermittelten Daten', 'Revisión de la minimización de los datos transmitidos a cada socio', 'Revisione della minimizzazione dei dati trasmessi a ciascun partner'], 'exchange', 'ANNUEL', 'DETECTIF', ['over-sharing'], [`${RGPD}, art. 5`])
tq.control('api-authz-tests', ['Tests automatisés du contrôle d’autorisation des API exposées', 'Automated testing of exposed API authorisation checks', 'Automatisierte Tests der Autorisierungsprüfung bereitgestellter APIs', 'Pruebas automatizadas del control de autorización de las API expuestas', 'Test automatizzati del controllo di autorizzazione delle API esposte'], 'expose', 'TRIMESTRIEL', 'DETECTIF', ['api-bola'], [`${OWASP_API}, API1 et API3`])
tq.control('api-quota-review', ['Revue des quotas d’API et des usages anormaux détectés', 'Review of API quotas and detected abnormal use', 'Überprüfung der API-Kontingente und erkannter auffälliger Nutzung', 'Revisión de las cuotas de API y de los usos anómalos detectados', 'Revisione delle quote API e degli usi anomali rilevati'], 'expose', 'MENSUEL', 'DETECTIF', ['api-abuse'], [`${OWASP_API}, API4`])
tq.control('api-inventory', ['Revue de l’inventaire des API exposées et retrait des versions obsolètes', 'Review of the exposed API inventory and removal of obsolete versions', 'Überprüfung des Verzeichnisses bereitgestellter APIs und Entfernung veralteter Versionen', 'Revisión del inventario de API expuestas y retirada de las versiones obsoletas', 'Revisione dell’inventario delle API esposte e ritiro delle versioni obsolete'], 'expose', 'SEMESTRIEL', 'DETECTIF', ['api-bola', 'api-abuse'], [`${OWASP_API}, API9`])
tq.control('api-pentest', ['Test d’intrusion des API exposées', 'Penetration test of exposed APIs', 'Penetrationstest der bereitgestellten APIs', 'Prueba de intrusión de las API expuestas', 'Penetration test delle API esposte'], 'expose', 'ANNUEL', 'DETECTIF', ['api-bola', 'api-abuse'])
tq.control('platform-admin-review', ['Revue des comptes d’administration de la plateforme d’intégration', 'Review of integration platform administration accounts', 'Überprüfung der Administrationskonten der Integrationsplattform', 'Revisión de las cuentas de administración de la plataforma de integración', 'Revisione degli account di amministrazione della piattaforma di integrazione'], 'integrate', 'TRIMESTRIEL', 'DETECTIF', ['platform-compromise'])
tq.control('platform-recovery-test', ['Test de reprise de la plateforme d’intégration sans perte ni doublon de flux', 'Recovery test of the integration platform without lost or duplicated flows', 'Wiederanlauftest der Integrationsplattform ohne verlorene oder doppelte Datenflüsse', 'Prueba de recuperación de la plataforma de integración sin pérdida ni duplicado de flujos', 'Test di ripresa della piattaforma di integrazione senza perdite né duplicati di flussi'], 'integrate', 'ANNUEL', 'DETECTIF', ['platform-outage'])
tq.control('interco-cutoff-exercise', ['Exercice de coupure d’urgence d’une interconnexion et de fonctionnement sans le flux', 'Exercise of emergency interconnection cut-off and operation without the flow', 'Übung der Notfalltrennung einer Kopplung und des Betriebs ohne den Datenfluss', 'Ejercicio de corte de emergencia de una interconexión y de funcionamiento sin el flujo', 'Esercitazione di interruzione di emergenza di un’interconnessione e di funzionamento senza il flusso'], 'exchange', 'ANNUEL', 'CORRECTIF', ['pivot', 'platform-outage', 'late-feed'])
tq.control('log-correlation-review', ['Revue des journaux d’échange corrélés des deux côtés de l’interconnexion', 'Review of exchange logs correlated on both sides of the interconnection', 'Überprüfung der auf beiden Seiten der Kopplung korrelierten Austauschprotokolle', 'Revisión de los registros de intercambio correlacionados en ambos lados de la interconexión', 'Revisione dei log di scambio correlati da entrambe le parti dell’interconnessione'], 'exchange', 'MENSUEL', 'DETECTIF', ['pivot', 'secret-theft'], [`${ISO}, mesure 8.15`])

tq.kri('rejected-deliveries', ['Taux de livraisons rejetées ou mises en quarantaine', 'Rate of rejected or quarantined deliveries', 'Quote abgelehnter oder in Quarantäne gestellter Lieferungen', 'Tasa de entregas rechazadas o en cuarentena', 'Tasso di consegne rifiutate o messe in quarantena'], 'receive', U_PCT, 'HAUSSE', 'MENSUEL')
tq.kri('late-deliveries', ['Livraisons en retard au-delà du délai convenu', 'Deliveries late beyond the agreed time', 'Lieferungen mit Verzug über die vereinbarte Frist hinaus', 'Entregas con retraso más allá del plazo acordado', 'Consegne in ritardo oltre il termine concordato'], 'receive', U_NB, 'HAUSSE', 'MENSUEL')
tq.kri('reconciliation-gaps', ['Écarts de rapprochement entre les deux systèmes', 'Reconciliation gaps between the two systems', 'Abgleichsdifferenzen zwischen beiden Systemen', 'Diferencias de conciliación entre ambos sistemas', 'Scostamenti di riconciliazione tra i due sistemi'], 'exchange', U_NB, 'HAUSSE', 'MENSUEL')
tq.kri('secrets-overdue', ['Secrets, clés et certificats d’échange non renouvelés à échéance', 'Exchange secrets, keys and certificates not renewed on time', 'Nicht fristgerecht erneuerte Austauschgeheimnisse, -schlüssel und -zertifikate', 'Secretos, claves y certificados de intercambio no renovados a su vencimiento', 'Segreti, chiavi e certificati di scambio non rinnovati alla scadenza'], 'exchange', U_NB, 'HAUSSE', 'TRIMESTRIEL')
tq.kri('intercos-without-agreement', ['Interconnexions sans convention signée', 'Interconnections without a signed agreement', 'Kopplungen ohne unterzeichnete Vereinbarung', 'Interconexiones sin convenio firmado', 'Interconnessioni senza convenzione firmata'], 'onboard', U_NB, 'HAUSSE', 'SEMESTRIEL')
tq.kri('partner-incidents', ['Incidents de sécurité notifiés par les partenaires interconnectés', 'Security incidents notified by interconnected partners', 'Von gekoppelten Partnern gemeldete Sicherheitsvorfälle', 'Incidentes de seguridad notificados por los socios interconectados', 'Incidenti di sicurezza notificati dai partner interconnessi'], 'onboard', U_NB, 'HAUSSE', 'TRIMESTRIEL')
tq.kri('api-denied-requests', ['Requêtes d’API refusées pour défaut d’autorisation', 'API requests denied for lack of authorisation', 'Mangels Berechtigung abgelehnte API-Anfragen', 'Solicitudes de API denegadas por falta de autorización', 'Richieste API rifiutate per mancanza di autorizzazione'], 'expose', U_NB, 'HAUSSE', 'MENSUEL')
tq.kri('api-unowned', ['API exposées sans propriétaire identifié', 'Exposed APIs without an identified owner', 'Bereitgestellte APIs ohne benannten Verantwortlichen', 'API expuestas sin propietario identificado', 'API esposte senza responsabile identificato'], 'expose', U_NB, 'HAUSSE', 'SEMESTRIEL')
tq.kri('platform-downtime', ['Durée d’indisponibilité de la plateforme d’intégration', 'Integration platform downtime', 'Ausfallzeit der Integrationsplattform', 'Duración de indisponibilidad de la plataforma de integración', 'Durata di indisponibilità della piattaforma di integrazione'], 'integrate', U_MIN, 'HAUSSE', 'MENSUEL')

tq.audit('interco-governance', ['Audit de la gouvernance des interconnexions', 'Audit of interconnection governance', 'Audit der Steuerung der Kopplungen', 'Auditoría de la gobernanza de las interconexiones', 'Audit della governance delle interconnessioni'], 'onboard', ['unmanaged-interco', 'partner-lockin'], [
  ['Chaque interconnexion est inventoriée, a un propriétaire et une criticité', 'Each interconnection is inventoried, with an owner and a criticality', 'Jede Kopplung ist verzeichnet und hat einen Verantwortlichen und eine Kritikalität', 'Cada interconexión está inventariada, con propietario y criticidad', 'Ogni interconnessione è inventariata, con responsabile e criticità'],
  ['Une convention signée encadre chaque flux', 'A signed agreement governs each flow', 'Eine unterzeichnete Vereinbarung regelt jeden Datenfluss', 'Un convenio firmado regula cada flujo', 'Una convenzione firmata disciplina ogni flusso'],
  ['Les partenaires sont évalués avant raccordement et suivis ensuite', 'Partners are assessed before connection and monitored afterwards', 'Partner werden vor dem Anschluss bewertet und danach überwacht', 'Los socios se evalúan antes de la conexión y se supervisan después', 'I partner sono valutati prima del collegamento e poi monitorati'],
  ['Un plan de sortie existe pour les prestataires critiques', 'An exit plan exists for critical providers', 'Für kritische Dienstleister besteht ein Ausstiegsplan', 'Existe un plan de salida para los proveedores críticos', 'Esiste un piano di uscita per i fornitori critici'],
])
tq.audit('inbound-feeds', ['Audit de la maîtrise des flux reçus de prestataires', 'Audit of control over flows received from providers', 'Audit der Beherrschung der von Dienstleistern empfangenen Datenflüsse', 'Auditoría del control de los flujos recibidos de proveedores', 'Audit del controllo dei flussi ricevuti dai fornitori'], 'receive', ['forged-feed', 'corrupt-feed', 'late-feed', 'format-change'], [
  ['Chaque livraison est contrôlée en complétude et en intégrité avant intégration', 'Each delivery is checked for completeness and integrity before integration', 'Jede Lieferung wird vor der Übernahme auf Vollständigkeit und Integrität geprüft', 'Cada entrega se controla en completitud e integridad antes de su integración', 'Ogni consegna è controllata per completezza e integrità prima dell’integrazione'],
  ['Les rejeux et doublons sont détectés', 'Replays and duplicates are detected', 'Wiederholte Einspielungen und Dubletten werden erkannt', 'Se detectan los reenvíos y duplicados', 'Le riproduzioni e i duplicati sono rilevati'],
  ['Les retards de livraison déclenchent une alerte et une escalade', 'Late deliveries trigger an alert and escalation', 'Lieferverzug löst Alarm und Eskalation aus', 'Los retrasos de entrega activan una alerta y un escalado', 'I ritardi di consegna attivano un allarme e un’escalation'],
  ['Les changements de format sont annoncés et recettés', 'Format changes are announced and tested', 'Formatänderungen werden angekündigt und abgenommen', 'Los cambios de formato se anuncian y se prueban', 'I cambi di formato sono annunciati e collaudati'],
])
tq.audit('api-security', ['Audit de la sécurité des API exposées', 'Audit of exposed API security', 'Audit der Sicherheit bereitgestellter APIs', 'Auditoría de la seguridad de las API expuestas', 'Audit della sicurezza delle API esposte'], 'expose', ['api-bola', 'api-abuse'], [
  ['Les API exposées sont inventoriées et ont un propriétaire', 'Exposed APIs are inventoried and have an owner', 'Bereitgestellte APIs sind verzeichnet und haben einen Verantwortlichen', 'Las API expuestas están inventariadas y tienen propietario', 'Le API esposte sono inventariate e hanno un responsabile'],
  ['L’autorisation est vérifiée pour chaque objet et chaque propriété', 'Authorisation is checked for each object and property', 'Die Autorisierung wird für jedes Objekt und jede Eigenschaft geprüft', 'La autorización se verifica para cada objeto y cada propiedad', 'L’autorizzazione è verificata per ogni oggetto e ogni proprietà'],
  ['Des quotas limitent la consommation et les abus sont détectés', 'Quotas limit consumption and abuse is detected', 'Kontingente begrenzen den Verbrauch und Missbrauch wird erkannt', 'Las cuotas limitan el consumo y se detectan los abusos', 'Le quote limitano il consumo e gli abusi sono rilevati'],
  ['Les clés sont protégées, renouvelées et révocables', 'Keys are protected, renewed and revocable', 'Schlüssel sind geschützt, werden erneuert und sind widerrufbar', 'Las claves están protegidas, se renuevan y son revocables', 'Le chiavi sono protette, rinnovate e revocabili'],
])
tq.audit('integration-platform', ['Audit de la plateforme d’intégration et de transfert de fichiers', 'Audit of the integration and file-transfer platform', 'Audit der Integrations- und Dateitransferplattform', 'Auditoría de la plataforma de integración y de transferencia de ficheros', 'Audit della piattaforma di integrazione e di trasferimento file'], 'integrate', ['platform-compromise', 'platform-outage', 'secret-theft'], [
  ['L’administration est nominative, renforcée et journalisée', 'Administration is named, hardened and logged', 'Die Administration ist personenbezogen, gehärtet und protokolliert', 'La administración es nominativa, reforzada y registrada', 'L’amministrazione è nominativa, rafforzata e registrata'],
  ['Les secrets des connecteurs sont dans un coffre-fort', 'Connector secrets are kept in a vault', 'Die Geheimnisse der Konnektoren liegen in einem Tresor', 'Los secretos de los conectores están en una bóveda', 'I segreti dei connettori sono in un vault'],
  ['La reprise après panne est testée sans perte ni doublon', 'Recovery after failure is tested without loss or duplication', 'Der Wiederanlauf nach Ausfall wird ohne Verlust oder Dublette getestet', 'La recuperación tras avería se prueba sin pérdida ni duplicado', 'La ripresa dopo un guasto è testata senza perdite né duplicati'],
  ['La cartographie des flux est à jour', 'The flow map is up to date', 'Die Karte der Datenflüsse ist aktuell', 'El mapa de flujos está actualizado', 'La mappa dei flussi è aggiornata'],
])

// ════════════════════ Catalogue 1.13 — compléments issus du comparatif ══════════════════
// Analyseurs de fichiers et validation des entrées (interconnexions), pièces jointes de la messagerie d'un portail,
// test de continuité d'une plateforme de santé. Packs distincts pour dater les ajouts dans l'historique.
const tq13 = sectorPack('TRANSVERSAL', 'technique')
tq13.risk('parser-exploit', 6, ['Un fichier ou message reçu exploite l’analyseur pour exécuter du code ou lire des fichiers internes', 'A received file or message exploits the parser to run code or read internal files', 'Eine empfangene Datei oder Nachricht nutzt den Parser aus, um Code auszuführen oder interne Dateien zu lesen', 'Un fichero o mensaje recibido explota el analizador para ejecutar código o leer ficheros internos', 'Un file o messaggio ricevuto sfrutta il parser per eseguire codice o leggere file interni'], 'technique.process.receive')
tq13.control('input-validation-review', ['Revue de la validation des entrées et du durcissement des analyseurs de fichiers (tests avec des fichiers malformés)', 'Review of input validation and file-parser hardening (tests with malformed files)', 'Überprüfung der Eingabevalidierung und der Härtung der Datei-Parser (Tests mit fehlerhaften Dateien)', 'Revisión de la validación de entradas y del refuerzo de los analizadores de ficheros (pruebas con ficheros malformados)', 'Revisione della validazione degli input e del rafforzamento dei parser di file (test con file malformati)'], 'technique.process.receive', 'TRIMESTRIEL', 'DETECTIF', ['parser-exploit', 'technique.risk.forged-feed'], [`${ISO}, mesure 8.28`])
tq13.kri('malformed-files', ['Fichiers ou messages rejetés pour structure invalide', 'Files or messages rejected for invalid structure', 'Wegen ungültiger Struktur abgelehnte Dateien oder Nachrichten', 'Ficheros o mensajes rechazados por estructura no válida', 'File o messaggi rifiutati per struttura non valida'], 'technique.process.receive', U_NB, 'HAUSSE', 'MENSUEL')

const sante13 = sectorPack('SANTE')
sante13.risk('portal-malicious-attachment', 2, ['Une pièce jointe malveillante reçue par la messagerie d’un portail compromet le poste d’un soignant', 'A malicious attachment received through a portal’s messaging compromises a care worker’s workstation', 'Ein schädlicher Anhang aus den Portal-Nachrichten kompromittiert den Arbeitsplatz einer Pflegekraft', 'Un adjunto malicioso recibido por la mensajería de un portal compromete el puesto de un profesional', 'Un allegato malevolo ricevuto tramite la messaggistica di un portale compromette la postazione di un operatore'], 'sante.process.portal')
sante13.control('portal-attachment-scanning', ['Revue des pièces jointes bloquées ou mises en quarantaine par l’analyse de la messagerie du portail', 'Review of attachments blocked or quarantined by portal messaging scanning', 'Überprüfung der durch die Prüfung der Portal-Nachrichten blockierten oder in Quarantäne gestellten Anhänge', 'Revisión de los adjuntos bloqueados o en cuarentena por el análisis de la mensajería del portal', 'Revisione degli allegati bloccati o messi in quarantena dall’analisi della messaggistica del portale'], 'sante.process.portal', 'MENSUEL', 'DETECTIF', ['portal-malicious-attachment'], [`${ISO}, mesure 8.7`])
sante13.control('platform-continuity-test', ['Test du plan de continuité et de reprise d’une plateforme de santé (bascule, durées de reprise mesurées)', 'Test of the continuity and recovery plan of a health platform (failover, measured recovery times)', 'Test des Kontinuitäts- und Wiederanlaufplans einer Gesundheitsplattform (Umschaltung, gemessene Wiederanlaufzeiten)', 'Prueba del plan de continuidad y recuperación de una plataforma de salud (conmutación, tiempos de recuperación medidos)', 'Test del piano di continuità e ripresa di una piattaforma sanitaria (failover, tempi di ripresa misurati)'], 'sante.process.portal', 'ANNUEL', 'DETECTIF', ['sante.risk.care-outage'], [`${ISO}, mesure 5.30`])

export const SANTE_EXT_PACK = sante.pack
export const MUTUELLE_SANTE_PACK = ass.pack
// Ancien secteur « Technique / Interconnexion de SI » (supprimé, décision D1) : son contenu est rattaché aux patterns
// d'architecture, selon le processus de l'élément. Les clés `technique.*` restent inchangées (stabilité du journal).
const PATTERN_OF_PROCESS: Record<string, string> = {
  'technique.process.exchange': 'INTERCO_TIERS', 'technique.process.onboard': 'INTERCO_TIERS',
  'technique.process.receive': 'EXTERNALISATION_DONNEES', 'technique.process.expose': 'API_PARTENAIRES', 'technique.process.integrate': 'ECHANGE_FICHIERS',
}
const FILE_PARSING = new Set(['technique.risk.parser-exploit', 'technique.control.input-validation-review', 'technique.kri.malformed-files'])
const archiOf = (item: { key: string; kind: string; processKey?: string }): string[] => {
  if (FILE_PARSING.has(item.key)) return ['ECHANGE_FICHIERS']
  return [PATTERN_OF_PROCESS[item.kind === 'PROCESS' ? item.key : item.processKey ?? ''] ?? 'INTERCO_TIERS']
}
export const TECHNIQUE_PACK = tagPatterns(tq.pack, archiOf)
export const TECHNIQUE_V113_PACK = tagPatterns(tq13.pack, archiOf)
export const SANTE_V113_PACK = sante13.pack
