/**
 * Pack « Agriculture / Agroalimentaire » (catalogue 1.10) : exploitations, coopératives, industries agroalimentaires.
 * Suggestions à qualifier : jamais d'exécution, de seuil, de date, de résultat ni de conformité acquise. Les `references`
 * citent le texte d'origine sans reproduire d'exigence. Contenu à relire par un expert du secteur (statut « à relire »).
 */
import { sectorPack, U_NB, U_PCT, U_DAYS, U_HOURS } from './catalogue-pack-builder'

const HYG = 'Règlement (CE) n° 852/2004 (hygiène des denrées alimentaires)'
const GFL = 'Règlement (CE) n° 178/2002 (principes généraux de la législation alimentaire, traçabilité)'
const NIS2 = 'Directive (UE) 2022/2555 (NIS 2) — production, transformation et distribution de denrées alimentaires'

const b = sectorPack('AGRICOLE')

b.process('production', ['Produire et récolter', 'Produce and harvest', 'Erzeugen und ernten', 'Producir y cosechar', 'Produrre e raccogliere'])
b.process('processing', ['Transformer et conditionner les produits', 'Process and package products', 'Produkte verarbeiten und verpacken', 'Transformar y envasar los productos', 'Trasformare e confezionare i prodotti'])
b.process('quality', ['Assurer la sécurité sanitaire et la traçabilité', 'Ensure food safety and traceability', 'Lebensmittelsicherheit und Rückverfolgbarkeit sicherstellen', 'Garantizar la seguridad alimentaria y la trazabilidad', 'Garantire la sicurezza alimentare e la tracciabilità'])
b.process('cold-chain', ['Stocker et transporter sous température dirigée', 'Store and transport under controlled temperature', 'Temperaturgeführt lagern und transportieren', 'Almacenar y transportar a temperatura controlada', 'Stoccare e trasportare a temperatura controllata'])
b.process('sales', ['Vendre, contractualiser et livrer', 'Sell, contract and deliver', 'Verkaufen, vertraglich binden und liefern', 'Vender, contratar y entregar', 'Vendere, contrattualizzare e consegnare'])
b.process('farm-tech', ['Exploiter les équipements connectés et les systèmes de pilotage', 'Operate connected equipment and control systems', 'Vernetzte Anlagen und Steuerungssysteme betreiben', 'Operar los equipos conectados y los sistemas de control', 'Gestire le apparecchiature connesse e i sistemi di controllo'])

b.risk('contamination', 3, ['Une contamination alimentaire n’est pas détectée avant la mise sur le marché', 'Food contamination goes undetected before market release', 'Eine Lebensmittelkontamination wird vor dem Inverkehrbringen nicht erkannt', 'Una contaminación alimentaria no se detecta antes de comercializar', 'Una contaminazione alimentare non viene rilevata prima dell’immissione sul mercato'], 'quality')
b.risk('recall-failure', 7, ['Un rappel de lots ne peut pas être mené rapidement faute de traçabilité', 'A batch recall cannot be run quickly for lack of traceability', 'Ein Chargenrückruf ist mangels Rückverfolgbarkeit nicht zügig durchführbar', 'Una retirada de lotes no puede hacerse con rapidez por falta de trazabilidad', 'Un richiamo di lotti non può essere condotto rapidamente per mancanza di tracciabilità'], 'quality')
b.risk('cold-chain-break', 5, ['Une rupture de la chaîne du froid altère des produits', 'A cold-chain break spoils products', 'Eine Unterbrechung der Kühlkette verdirbt Produkte', 'Una ruptura de la cadena de frío deteriora productos', 'Un’interruzione della catena del freddo deteriora i prodotti'], 'cold-chain')
b.risk('process-control-attack', 2, ['Une intrusion sur le pilotage des lignes de production arrête ou dérègle la fabrication', 'An intrusion into production-line controls stops or disrupts manufacturing', 'Ein Eindringen in die Steuerung der Produktionslinien stoppt oder stört die Fertigung', 'Una intrusión en el control de las líneas de producción detiene o altera la fabricación', 'Un’intrusione nel controllo delle linee di produzione ferma o altera la produzione'], 'farm-tech')
b.risk('connected-equipment', 2, ['Un équipement agricole connecté est détourné ou immobilisé à distance', 'A connected farm machine is hijacked or remotely immobilised', 'Eine vernetzte Landmaschine wird übernommen oder aus der Ferne stillgelegt', 'Una máquina agrícola conectada es secuestrada o inmovilizada a distancia', 'Una macchina agricola connessa viene dirottata o immobilizzata da remoto'], 'farm-tech')
b.risk('supply-shortage', 6, ['Une pénurie d’intrants ou d’emballages interrompt la production', 'A shortage of inputs or packaging halts production', 'Ein Mangel an Betriebsmitteln oder Verpackungen unterbricht die Produktion', 'La escasez de insumos o envases interrumpe la producción', 'La carenza di input o imballaggi interrompe la produzione'], 'production')
b.risk('weather-event', 5, ['Un événement climatique détruit une part importante de la récolte ou du stock', 'A weather event destroys a large part of the harvest or stock', 'Ein Wetterereignis zerstört einen großen Teil der Ernte oder des Lagers', 'Un fenómeno climático destruye gran parte de la cosecha o del stock', 'Un evento climatico distrugge gran parte del raccolto o delle scorte'], 'production')
b.risk('label-error', 7, ['Un étiquetage erroné (allergènes, origine, DLC) expose les consommateurs', 'A labelling error (allergens, origin, expiry) exposes consumers', 'Eine fehlerhafte Kennzeichnung (Allergene, Herkunft, Verfallsdatum) gefährdet Verbraucher', 'Un etiquetado erróneo (alérgenos, origen, caducidad) expone a los consumidores', 'Un’etichettatura errata (allergeni, origine, scadenza) espone i consumatori'], 'processing')
b.risk('subsidy-error', 7, ['Une aide ou un paiement agricole est déclaré à tort ou non justifié', 'An agricultural aid or payment is wrongly declared or unjustified', 'Eine Agrarbeihilfe oder -zahlung wird fehlerhaft angegeben oder ist nicht belegt', 'Una ayuda o pago agrícola se declara indebidamente o carece de justificación', 'Un aiuto o pagamento agricolo viene dichiarato erroneamente o non è giustificato'], 'sales')
b.risk('payment-diversion', 2, ['Un paiement à un fournisseur ou coopérateur est détourné par usurpation', 'A payment to a supplier or cooperative member is diverted by impersonation', 'Eine Zahlung an einen Lieferanten oder Genossen wird durch Identitätsmissbrauch umgeleitet', 'Un pago a un proveedor o cooperativista se desvía por suplantación', 'Un pagamento a un fornitore o socio viene dirottato tramite furto di identità'], 'sales')
b.risk('worker-safety', 3, ['Un accident du travail grave survient sur une exploitation ou une chaîne', 'A serious workplace accident occurs on a farm or processing line', 'Auf einem Betrieb oder an einer Linie ereignet sich ein schwerer Arbeitsunfall', 'Se produce un accidente laboral grave en una explotación o línea', 'Si verifica un grave infortunio sul lavoro in un’azienda o su una linea'], 'production')
b.risk('seasonal-staff', 3, ['Un manque de main-d’œuvre saisonnière bloque la récolte ou la transformation', 'A seasonal labour shortage blocks harvest or processing', 'Ein Mangel an Saisonarbeitskräften blockiert Ernte oder Verarbeitung', 'La falta de mano de obra estacional bloquea la cosecha o la transformación', 'La carenza di manodopera stagionale blocca il raccolto o la trasformazione'], 'production')

b.control('haccp-points', ['Revue des points de maîtrise critiques et de leurs enregistrements', 'Review of critical control points and their records', 'Überprüfung der kritischen Kontrollpunkte und ihrer Aufzeichnungen', 'Revisión de los puntos de control crítico y de sus registros', 'Revisione dei punti critici di controllo e delle loro registrazioni'], 'quality', 'MENSUEL', 'DETECTIF', ['contamination'], [HYG])
b.control('lab-analysis', ['Suivi des analyses microbiologiques et physico-chimiques non conformes', 'Follow-up of non-compliant microbiological and physico-chemical analyses', 'Nachverfolgung nicht konformer mikrobiologischer und physikalisch-chemischer Analysen', 'Seguimiento de los análisis microbiológicos y fisicoquímicos no conformes', 'Monitoraggio delle analisi microbiologiche e fisico-chimiche non conformi'], 'quality', 'MENSUEL', 'DETECTIF', ['contamination'], [HYG])
b.control('mock-recall', ['Exercice de retrait ou rappel simulé d’un lot', 'Simulated batch withdrawal or recall exercise', 'Übung zu einem simulierten Chargenrückruf', 'Ejercicio de retirada o recuperación simulada de un lote', 'Esercitazione di ritiro o richiamo simulato di un lotto'], 'quality', 'ANNUEL', 'DETECTIF', ['recall-failure'], [GFL])
b.control('traceability-sample', ['Contrôle par échantillon de la traçabilité amont-aval des lots', 'Sample check of upstream-downstream batch traceability', 'Stichprobenprüfung der Rückverfolgbarkeit der Chargen entlang der Kette', 'Control por muestreo de la trazabilidad aguas arriba y abajo de los lotes', 'Controllo a campione della tracciabilità a monte e a valle dei lotti'], 'quality', 'TRIMESTRIEL', 'DETECTIF', ['recall-failure'], [GFL])
b.control('allergen-labels', ['Vérification de la conformité des étiquettes avant lancement ou changement de recette', 'Check of label compliance before launch or recipe change', 'Prüfung der Etikettenkonformität vor Einführung oder Rezepturänderung', 'Verificación de la conformidad de las etiquetas antes de un lanzamiento o cambio de receta', 'Verifica della conformità delle etichette prima del lancio o di una modifica di ricetta'], 'processing', 'TRIMESTRIEL', 'PREVENTIF', ['label-error'])
b.control('line-clearance', ['Contrôle du dégagement de ligne entre deux produits', 'Check of line clearance between two products', 'Prüfung der Linienfreigabe zwischen zwei Produkten', 'Control del despeje de línea entre dos productos', 'Controllo della pulizia di linea tra due prodotti'], 'processing', 'MENSUEL', 'DETECTIF', ['contamination', 'label-error'])
b.control('supplier-audit-food', ['Revue des audits et certificats des fournisseurs de matières premières', 'Review of audits and certificates of raw-material suppliers', 'Überprüfung von Audits und Zertifikaten der Rohwarenlieferanten', 'Revisión de las auditorías y certificados de los proveedores de materias primas', 'Revisione di audit e certificati dei fornitori di materie prime'], 'quality', 'ANNUEL', 'PREVENTIF', ['contamination'])
b.control('temperature-alarms', ['Revue des alarmes et relevés de température des chambres froides', 'Review of cold-room temperature alarms and readings', 'Überprüfung der Temperaturalarme und -aufzeichnungen der Kühlräume', 'Revisión de las alarmas y registros de temperatura de las cámaras frigoríficas', 'Revisione degli allarmi e delle registrazioni di temperatura delle celle frigorifere'], 'cold-chain', 'MENSUEL', 'DETECTIF', ['cold-chain-break'])
b.control('probe-calibration', ['Vérification de l’étalonnage des sondes de température', 'Check of temperature-probe calibration', 'Prüfung der Kalibrierung der Temperaturfühler', 'Verificación de la calibración de las sondas de temperatura', 'Verifica della taratura delle sonde di temperatura'], 'cold-chain', 'SEMESTRIEL', 'PREVENTIF', ['cold-chain-break'])
b.control('transport-temperature', ['Contrôle par échantillon des relevés de température en transport', 'Sample check of temperature records in transit', 'Stichprobenprüfung der Temperaturaufzeichnungen im Transport', 'Control por muestreo de los registros de temperatura en transporte', 'Controllo a campione delle registrazioni di temperatura durante il trasporto'], 'cold-chain', 'MENSUEL', 'DETECTIF', ['cold-chain-break'])
b.control('backup-power', ['Test des groupes de secours des installations de froid', 'Test of backup generators for refrigeration', 'Test der Notstromaggregate der Kälteanlagen', 'Prueba de los grupos de emergencia de las instalaciones de frío', 'Test dei gruppi di emergenza degli impianti di refrigerazione'], 'cold-chain', 'TRIMESTRIEL', 'PREVENTIF', ['cold-chain-break'])
b.control('ot-segmentation', ['Vérification du cloisonnement entre réseau bureautique et pilotage des lignes', 'Check of segregation between office network and line controls', 'Prüfung der Trennung zwischen Büronetz und Linien-Steuerung', 'Verificación de la segregación entre la red ofimática y el control de líneas', 'Verifica della separazione tra rete d’ufficio e controllo delle linee'], 'farm-tech', 'TRIMESTRIEL', 'DETECTIF', ['process-control-attack'], [NIS2])
b.control('remote-vendor-access', ['Revue des accès distants des fabricants d’équipements', 'Review of remote access by equipment manufacturers', 'Überprüfung der Fernzugriffe von Geräteherstellern', 'Revisión de los accesos remotos de los fabricantes de equipos', 'Revisione degli accessi remoti dei produttori di apparecchiature'], 'farm-tech', 'TRIMESTRIEL', 'DETECTIF', ['process-control-attack', 'connected-equipment'])
b.control('firmware-updates', ['Suivi des mises à jour des équipements connectés', 'Follow-up of connected-equipment updates', 'Nachverfolgung von Updates vernetzter Geräte', 'Seguimiento de las actualizaciones de los equipos conectados', 'Monitoraggio degli aggiornamenti delle apparecchiature connesse'], 'farm-tech', 'SEMESTRIEL', 'DETECTIF', ['connected-equipment'])
b.control('recipe-backup', ['Test de restauration des recettes et paramètres de lignes', 'Restoration test of recipes and line parameters', 'Wiederherstellungstest von Rezepturen und Linienparametern', 'Prueba de restauración de recetas y parámetros de líneas', 'Test di ripristino di ricette e parametri di linea'], 'farm-tech', 'SEMESTRIEL', 'DETECTIF', ['process-control-attack'])
b.control('critical-inputs', ['Revue des stocks et des fournisseurs alternatifs d’intrants critiques', 'Review of stocks and alternative suppliers of critical inputs', 'Überprüfung der Bestände und alternativen Lieferanten kritischer Betriebsmittel', 'Revisión de las existencias y proveedores alternativos de insumos críticos', 'Revisione delle scorte e dei fornitori alternativi di input critici'], 'production', 'TRIMESTRIEL', 'DETECTIF', ['supply-shortage'])
b.control('subsidy-declarations', ['Contrôle par échantillon des déclarations d’aides avant dépôt', 'Sample check of aid declarations before submission', 'Stichprobenprüfung von Beihilfeanträgen vor Einreichung', 'Control por muestreo de las declaraciones de ayudas antes de su presentación', 'Controllo a campione delle domande di aiuto prima della presentazione'], 'sales', 'ANNUEL', 'PREVENTIF', ['subsidy-error'])
b.control('bank-detail-changes', ['Rappel et validation indépendante de tout changement de coordonnées bancaires', 'Call-back and independent validation of any bank-detail change', 'Rückruf und unabhängige Freigabe jeder Änderung von Bankverbindungen', 'Verificación telefónica y validación independiente de todo cambio de datos bancarios', 'Richiamata e validazione indipendente di ogni modifica delle coordinate bancarie'], 'sales', 'MENSUEL', 'PREVENTIF', ['payment-diversion'])
b.control('safety-briefing', ['Vérification des consignes de sécurité et des habilitations des intervenants saisonniers', 'Check of safety briefings and authorisations of seasonal workers', 'Prüfung der Sicherheitsunterweisungen und Berechtigungen von Saisonkräften', 'Verificación de las instrucciones de seguridad y habilitaciones de los trabajadores estacionales', 'Verifica delle istruzioni di sicurezza e delle abilitazioni dei lavoratori stagionali'], 'production', 'TRIMESTRIEL', 'PREVENTIF', ['worker-safety', 'seasonal-staff'])
b.control('crop-insurance', ['Revue de la couverture d’assurance des aléas climatiques et des stocks', 'Review of insurance cover for weather hazards and stock', 'Überprüfung des Versicherungsschutzes für Wetterrisiken und Lagerbestände', 'Revisión de la cobertura de seguros frente a riesgos climáticos y existencias', 'Revisione della copertura assicurativa per eventi climatici e scorte'], 'production', 'ANNUEL', 'PREVENTIF', ['weather-event'])

b.kri('batch-nonconformity', ['Lots non conformes ou bloqués', 'Non-compliant or blocked batches', 'Nicht konforme oder gesperrte Chargen', 'Lotes no conformes o bloqueados', 'Lotti non conformi o bloccati'], 'quality', U_PCT, 'HAUSSE', 'MENSUEL')
b.kri('recall-time', ['Temps de reconstitution de la traçabilité lors des exercices de rappel', 'Time to reconstruct traceability in recall exercises', 'Zeit zur Rekonstruktion der Rückverfolgbarkeit bei Rückrufübungen', 'Tiempo de reconstrucción de la trazabilidad en los ejercicios de retirada', 'Tempo di ricostruzione della tracciabilità negli esercizi di richiamo'], 'quality', U_HOURS, 'HAUSSE', 'ANNUEL')
b.kri('temperature-excursions', ['Excursions de température hors limites', 'Out-of-range temperature excursions', 'Temperaturabweichungen außerhalb der Grenzwerte', 'Excursiones de temperatura fuera de límites', 'Escursioni di temperatura fuori limite'], 'cold-chain', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('production-downtime', ['Heures d’arrêt non planifié des lignes de production', 'Hours of unplanned production-line downtime', 'Stunden ungeplanter Stillstände der Produktionslinien', 'Horas de parada no planificada de las líneas de producción', 'Ore di fermo non pianificato delle linee di produzione'], 'farm-tech', U_HOURS, 'HAUSSE', 'MENSUEL')
b.kri('connected-unpatched', ['Équipements connectés avec mise à jour de sécurité en retard', 'Connected equipment with overdue security updates', 'Vernetzte Geräte mit überfälligen Sicherheitsupdates', 'Equipos conectados con actualización de seguridad atrasada', 'Apparecchiature connesse con aggiornamenti di sicurezza in ritardo'], 'farm-tech', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('labelling-corrections', ['Corrections d’étiquetage après impression', 'Labelling corrections after printing', 'Etikettenkorrekturen nach dem Druck', 'Correcciones de etiquetado tras la impresión', 'Correzioni di etichettatura dopo la stampa'], 'processing', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('input-coverage', ['Jours de couverture des intrants critiques', 'Days of cover of critical inputs', 'Reichweite kritischer Betriebsmittel in Tagen', 'Días de cobertura de insumos críticos', 'Giorni di copertura degli input critici'], 'production', U_DAYS, 'BAISSE', 'MENSUEL')
b.kri('workplace-accidents', ['Accidents du travail déclarés', 'Reported workplace accidents', 'Gemeldete Arbeitsunfälle', 'Accidentes laborales notificados', 'Infortuni sul lavoro denunciati'], 'production', U_NB, 'HAUSSE', 'MENSUEL')

b.audit('food-safety', ['Audit du dispositif de sécurité sanitaire', 'Audit of the food-safety system', 'Audit des Lebensmittelsicherheitssystems', 'Auditoría del sistema de seguridad alimentaria', 'Audit del sistema di sicurezza alimentare'], 'quality', ['contamination', 'label-error'], [
  ['Les dangers et points critiques sont analysés et revus à chaque changement', 'Hazards and critical points are analysed and reviewed at each change', 'Gefahren und kritische Punkte werden analysiert und bei jeder Änderung überprüft', 'Los peligros y puntos críticos se analizan y revisan en cada cambio', 'I pericoli e i punti critici sono analizzati e rivisti a ogni cambiamento'],
  ['Les enregistrements de surveillance sont complets et conservés', 'Monitoring records are complete and retained', 'Überwachungsaufzeichnungen sind vollständig und aufbewahrt', 'Los registros de vigilancia están completos y se conservan', 'Le registrazioni di sorveglianza sono complete e conservate'],
  ['Les produits non conformes sont isolés et traités', 'Non-conforming products are isolated and handled', 'Nicht konforme Produkte werden getrennt und behandelt', 'Los productos no conformes se aíslan y se tratan', 'I prodotti non conformi sono isolati e trattati'],
  ['L’étiquetage est contrôlé avant mise sur le marché', 'Labelling is checked before market release', 'Die Kennzeichnung wird vor dem Inverkehrbringen geprüft', 'El etiquetado se controla antes de comercializar', 'L’etichettatura è controllata prima dell’immissione sul mercato'],
])
b.audit('traceability-recall', ['Audit de la traçabilité et de la gestion des rappels', 'Audit of traceability and recall management', 'Audit der Rückverfolgbarkeit und des Rückrufmanagements', 'Auditoría de la trazabilidad y de la gestión de retiradas', 'Audit della tracciabilità e della gestione dei richiami'], 'quality', ['recall-failure'], [
  ['Chaque lot est rattaché à ses matières premières et à ses clients', 'Each batch is linked to its raw materials and customers', 'Jede Charge ist ihren Rohwaren und Kunden zugeordnet', 'Cada lote está vinculado a sus materias primas y clientes', 'Ogni lotto è collegato alle sue materie prime e ai suoi clienti'],
  ['Des exercices de rappel sont réalisés et leurs enseignements suivis', 'Recall exercises are carried out and lessons followed up', 'Rückrufübungen werden durchgeführt und Erkenntnisse nachverfolgt', 'Se realizan ejercicios de retirada y se da seguimiento a sus enseñanzas', 'Si svolgono esercitazioni di richiamo e se ne seguono gli insegnamenti'],
  ['La procédure d’information des autorités et des clients est définie', 'The procedure for informing authorities and customers is defined', 'Das Verfahren zur Information von Behörden und Kunden ist festgelegt', 'El procedimiento de información a autoridades y clientes está definido', 'La procedura di informazione di autorità e clienti è definita'],
  ['Les données de traçabilité sont sauvegardées et protégées', 'Traceability data is backed up and protected', 'Rückverfolgbarkeitsdaten sind gesichert und geschützt', 'Los datos de trazabilidad se respaldan y protegen', 'I dati di tracciabilità sono sottoposti a backup e protetti'],
])
b.audit('cold-chain', ['Audit de la chaîne du froid', 'Audit of the cold chain', 'Audit der Kühlkette', 'Auditoría de la cadena de frío', 'Audit della catena del freddo'], 'cold-chain', ['cold-chain-break'], [
  ['Les températures sont surveillées en continu avec alarme', 'Temperatures are monitored continuously with alarms', 'Temperaturen werden laufend mit Alarm überwacht', 'Las temperaturas se vigilan de forma continua con alarma', 'Le temperature sono monitorate in continuo con allarme'],
  ['Les sondes sont étalonnées et les relevés conservés', 'Probes are calibrated and readings retained', 'Fühler sind kalibriert und Aufzeichnungen aufbewahrt', 'Las sondas están calibradas y los registros se conservan', 'Le sonde sono tarate e le registrazioni conservate'],
  ['Les procédures de panne et les groupes de secours sont testés', 'Failure procedures and backup generators are tested', 'Störungsverfahren und Notstromaggregate werden getestet', 'Los procedimientos de avería y los grupos de emergencia se prueban', 'Le procedure di guasto e i gruppi di emergenza sono testati'],
  ['Les transporteurs sont évalués sur la maîtrise de la température', 'Carriers are assessed on temperature control', 'Transporteure werden hinsichtlich der Temperaturführung bewertet', 'Los transportistas se evalúan en el control de la temperatura', 'I trasportatori sono valutati sul controllo della temperatura'],
])
b.audit('farm-technology', ['Audit de la sécurité des équipements connectés et du pilotage', 'Audit of connected-equipment and control-system security', 'Audit der Sicherheit vernetzter Anlagen und Steuerungen', 'Auditoría de la seguridad de los equipos conectados y del control', 'Audit della sicurezza delle apparecchiature connesse e dei sistemi di controllo'], 'farm-tech', ['process-control-attack', 'connected-equipment'], [
  ['Les équipements connectés sont inventoriés avec leur propriétaire', 'Connected equipment is inventoried with its owner', 'Vernetzte Geräte sind mit Verantwortlichen inventarisiert', 'Los equipos conectados están inventariados con su responsable', 'Le apparecchiature connesse sono inventariate con il relativo responsabile'],
  ['Le réseau de pilotage est séparé du réseau bureautique', 'The control network is separated from the office network', 'Das Steuerungsnetz ist vom Büronetz getrennt', 'La red de control está separada de la red ofimática', 'La rete di controllo è separata dalla rete d’ufficio'],
  ['Les accès des fabricants sont limités, tracés et temporaires', 'Manufacturer access is limited, logged and temporary', 'Herstellerzugänge sind begrenzt, protokolliert und befristet', 'Los accesos de los fabricantes son limitados, trazados y temporales', 'Gli accessi dei produttori sono limitati, tracciati e temporanei'],
  ['Les paramètres de lignes sont sauvegardés et restaurables', 'Line parameters are backed up and restorable', 'Linienparameter sind gesichert und wiederherstellbar', 'Los parámetros de líneas están respaldados y son restaurables', 'I parametri di linea sono sottoposti a backup e ripristinabili'],
])

export const AGRICOLE_PACK = b.pack
