/**
 * Approfondissement des packs « Informatique / Numérique (SaaS) », « Santé / Médico-social » et « Télécommunications »
 * (catalogue 1.10). Complète les éléments existants (mêmes processus) : suggestions à qualifier, jamais d'exécution, de seuil,
 * de date, de résultat ni de conformité acquise. Les `references` citent le texte d'origine sans reproduire d'exigence.
 * Contenu à relire par un expert du secteur (statut « à relire »).
 */
import { sectorPack, U_NB, U_PCT, U_DAYS, U_MIN } from './catalogue-pack-builder'

const ISO27001 = 'ISO/IEC 27001:2022'
const RGPD = 'Règlement (UE) 2016/679 (RGPD)'
const NIS2 = 'Directive (UE) 2022/2555 (NIS 2)'
const CRA = 'Règlement (UE) 2024/2847 (législation sur la cyber-résilience)'
const HDS = 'Code de la santé publique — hébergement de données de santé'
const PGSSI = 'Politique générale de sécurité des systèmes d’information de santé (PGSSI-S)'
const MDR = 'Règlement (UE) 2017/745 (dispositifs médicaux)'
const CPCE = 'Code des postes et des communications électroniques'
const EPRIVACY = 'Directive 2002/58/CE (vie privée et communications électroniques)'

// ════════════════════════════ SaaS / Informatique ═══════════════════════════
const saas = sectorPack('SAAS')
saas.risk('supply-chain', 2, ['Une dépendance logicielle ou une chaîne de build compromise introduit du code malveillant', 'A compromised dependency or build pipeline introduces malicious code', 'Eine kompromittierte Abhängigkeit oder Build-Pipeline schleust Schadcode ein', 'Una dependencia o cadena de compilación comprometida introduce código malicioso', 'Una dipendenza o una pipeline di build compromessa introduce codice malevolo'], 'build')
saas.risk('vulnerability-disclosure', 2, ['Une vulnérabilité signalée n’est pas traitée avant sa divulgation publique', 'A reported vulnerability is not handled before public disclosure', 'Eine gemeldete Schwachstelle wird vor der öffentlichen Bekanntgabe nicht behoben', 'Una vulnerabilidad notificada no se trata antes de su divulgación pública', 'Una vulnerabilità segnalata non viene gestita prima della divulgazione pubblica'], 'build')
saas.risk('sla-breach', 7, ['Un niveau de service contractuel n’est pas tenu et déclenche des pénalités', 'A contractual service level is missed and triggers penalties', 'Ein vertragliches Service-Level wird verfehlt und löst Vertragsstrafen aus', 'No se cumple un nivel de servicio contractual y se activan penalizaciones', 'Un livello di servizio contrattuale non viene rispettato e fa scattare penali'], 'host')
saas.risk('data-residency', 4, ['Des données clients sont hébergées ou traitées hors de la zone convenue', 'Customer data is hosted or processed outside the agreed region', 'Kundendaten werden außerhalb der vereinbarten Region gehostet oder verarbeitet', 'Los datos de clientes se alojan o tratan fuera de la zona acordada', 'I dati dei clienti sono ospitati o trattati al di fuori dell’area concordata'], 'host')
saas.risk('offboarding', 7, ['La restitution ou la suppression des données d’un client à la fin du contrat n’est pas assurée', 'Return or deletion of a customer’s data at contract end is not ensured', 'Rückgabe oder Löschung von Kundendaten bei Vertragsende ist nicht gewährleistet', 'No se asegura la devolución o supresión de los datos de un cliente al finalizar el contrato', 'La restituzione o cancellazione dei dati di un cliente a fine contratto non è garantita'], 'onboard')
saas.control('dependency-scan', ['Suivi des vulnérabilités des dépendances logicielles et nomenclatures (SBOM)', 'Follow-up of software dependency vulnerabilities and bills of materials (SBOM)', 'Nachverfolgung von Schwachstellen in Abhängigkeiten und Software-Stücklisten (SBOM)', 'Seguimiento de las vulnerabilidades de dependencias de software y listas de materiales (SBOM)', 'Monitoraggio delle vulnerabilità delle dipendenze software e delle distinte (SBOM)'], 'build', 'MENSUEL', 'DETECTIF', ['supply-chain', 'release'], [CRA])
saas.control('pipeline-access', ['Revue des droits et secrets de la chaîne d’intégration et de livraison', 'Review of rights and secrets in the CI/CD pipeline', 'Überprüfung der Rechte und Geheimnisse der CI/CD-Pipeline', 'Revisión de los derechos y secretos de la cadena de integración y entrega', 'Revisione dei diritti e dei segreti della pipeline CI/CD'], 'build', 'TRIMESTRIEL', 'DETECTIF', ['supply-chain', 'secrets'])
saas.control('secret-scanning', ['Contrôle de la détection de secrets dans le code et les dépôts', 'Check of secret detection in code and repositories', 'Prüfung der Erkennung von Geheimnissen in Code und Repositories', 'Control de la detección de secretos en el código y los repositorios', 'Controllo del rilevamento di segreti nel codice e nei repository'], 'build', 'MENSUEL', 'DETECTIF', ['secrets'])
saas.control('pentest-follow-up', ['Suivi des constats de tests d’intrusion jusqu’à correction', 'Follow-up of penetration-test findings until fixed', 'Nachverfolgung von Penetrationstest-Feststellungen bis zur Behebung', 'Seguimiento de los hallazgos de pruebas de intrusión hasta su corrección', 'Monitoraggio dei rilievi dei penetration test fino alla correzione'], 'build', 'TRIMESTRIEL', 'DETECTIF', ['vulnerability-disclosure', 'release'])
saas.control('disclosure-process', ['Revue du traitement des signalements de vulnérabilités reçus', 'Review of handling of received vulnerability reports', 'Überprüfung der Bearbeitung eingegangener Schwachstellenmeldungen', 'Revisión del tratamiento de las notificaciones de vulnerabilidades recibidas', 'Revisione della gestione delle segnalazioni di vulnerabilità ricevute'], 'build', 'TRIMESTRIEL', 'DETECTIF', ['vulnerability-disclosure'], [CRA])
saas.control('tenant-isolation-test', ['Test d’isolation entre clients (contrôles d’accès inter-locataires)', 'Cross-tenant isolation test (cross-tenant access controls)', 'Isolationstest zwischen Mandanten (mandantenübergreifende Zugriffskontrollen)', 'Prueba de aislamiento entre clientes (controles de acceso entre inquilinos)', 'Test di isolamento tra clienti (controlli di accesso tra tenant)'], 'host', 'SEMESTRIEL', 'DETECTIF', ['tenant-isolation'])
saas.control('infra-config-drift', ['Détection des dérives de configuration de l’infrastructure cloud', 'Detection of cloud-infrastructure configuration drift', 'Erkennung von Konfigurationsabweichungen der Cloud-Infrastruktur', 'Detección de desviaciones de configuración de la infraestructura cloud', 'Rilevamento delle derive di configurazione dell’infrastruttura cloud'], 'host', 'MENSUEL', 'DETECTIF', ['cloud-outage', 'tenant-isolation'])
saas.control('dr-test', ['Test de reprise après sinistre d’une région d’hébergement', 'Disaster-recovery test of a hosting region', 'Notfallwiederherstellungstest einer Hosting-Region', 'Prueba de recuperación ante desastres de una región de alojamiento', 'Test di disaster recovery di una regione di hosting'], 'host', 'ANNUEL', 'DETECTIF', ['cloud-outage', 'tenant-restore'])
saas.control('sla-report', ['Revue des mesures de disponibilité par rapport aux engagements contractuels', 'Review of availability measures against contractual commitments', 'Überprüfung der Verfügbarkeitsmessungen gegenüber vertraglichen Zusagen', 'Revisión de las mediciones de disponibilidad frente a los compromisos contractuales', 'Revisione delle misure di disponibilità rispetto agli impegni contrattuali'], 'host', 'MENSUEL', 'DETECTIF', ['sla-breach', 'cloud-outage'])
saas.control('residency-check', ['Vérification de la localisation des données et des sous-traitants ultérieurs', 'Check of data location and sub-processors', 'Prüfung des Datenstandorts und der Unterauftragsverarbeiter', 'Verificación de la ubicación de los datos y de los subencargados', 'Verifica della localizzazione dei dati e dei sub-responsabili'], 'host', 'SEMESTRIEL', 'DETECTIF', ['data-residency'], [RGPD])
saas.control('support-session-log', ['Revue des sessions d’assistance avec accès aux données clients', 'Review of support sessions with access to customer data', 'Überprüfung von Support-Sitzungen mit Zugriff auf Kundendaten', 'Revisión de las sesiones de soporte con acceso a datos de clientes', 'Revisione delle sessioni di supporto con accesso ai dati dei clienti'], 'support', 'MENSUEL', 'DETECTIF', ['support-access'])
saas.control('incident-comms', ['Exercice de communication client lors d’un incident de service', 'Customer-communication exercise during a service incident', 'Übung zur Kundenkommunikation bei einer Dienststörung', 'Ejercicio de comunicación con clientes durante un incidente de servicio', 'Esercitazione di comunicazione ai clienti durante un incidente di servizio'], 'support', 'ANNUEL', 'PREVENTIF', ['cloud-outage', 'sla-breach'])
saas.control('onboarding-config', ['Contrôle par échantillon de la configuration de sécurité des nouveaux clients', 'Sample check of security configuration of new customers', 'Stichprobenprüfung der Sicherheitskonfiguration neuer Kunden', 'Control por muestreo de la configuración de seguridad de los nuevos clientes', 'Controllo a campione della configurazione di sicurezza dei nuovi clienti'], 'onboard', 'TRIMESTRIEL', 'DETECTIF', ['integration', 'tenant-isolation'])
saas.control('integration-keys', ['Revue des clés et jetons d’API clients et leur rotation', 'Review of customer API keys and tokens and their rotation', 'Überprüfung von Kunden-API-Schlüsseln und -Token und ihrer Rotation', 'Revisión de las claves y tokens de API de clientes y su rotación', 'Revisione delle chiavi e dei token API dei clienti e della loro rotazione'], 'onboard', 'SEMESTRIEL', 'DETECTIF', ['integration', 'secrets'])
saas.control('offboarding-deletion', ['Vérification de la restitution et de la suppression des données à la sortie d’un client', 'Check of data return and deletion when a customer leaves', 'Prüfung von Rückgabe und Löschung der Daten beim Ausscheiden eines Kunden', 'Verificación de la devolución y supresión de datos a la salida de un cliente', 'Verifica della restituzione e cancellazione dei dati all’uscita di un cliente'], 'onboard', 'TRIMESTRIEL', 'DETECTIF', ['offboarding'], [RGPD])
saas.control('privileged-access-cloud', ['Revue des accès privilégiés à la production et aux consoles cloud', 'Review of privileged access to production and cloud consoles', 'Überprüfung privilegierter Zugriffe auf Produktion und Cloud-Konsolen', 'Revisión de los accesos privilegiados a producción y a las consolas cloud', 'Revisione degli accessi privilegiati alla produzione e alle console cloud'], 'host', 'TRIMESTRIEL', 'DETECTIF', ['support-access', 'tenant-isolation'], [ISO27001])
saas.control('change-approval-sample', ['Contrôle par échantillon de l’approbation des changements de production', 'Sample check of approval of production changes', 'Stichprobenprüfung der Genehmigung von Produktionsänderungen', 'Control por muestreo de la aprobación de los cambios en producción', 'Controllo a campione dell’approvazione delle modifiche in produzione'], 'build', 'MENSUEL', 'DETECTIF', ['release'], [ISO27001])
saas.control('mfa-staff', ['Vérification de l’authentification renforcée de tous les comptes du personnel et des prestataires', 'Check of strong authentication for all staff and contractor accounts', 'Prüfung der starken Authentifizierung aller Konten von Beschäftigten und Dienstleistern', 'Verificación de la autenticación reforzada de todas las cuentas del personal y de los proveedores', 'Verifica dell’autenticazione forte di tutti gli account di personale e fornitori'], 'support', 'TRIMESTRIEL', 'DETECTIF', ['support-access', 'secrets'], [ISO27001])
saas.kri('mean-time-to-patch', ['Délai moyen de correction des vulnérabilités critiques', 'Mean time to fix critical vulnerabilities', 'Mittlere Zeit bis zur Behebung kritischer Schwachstellen', 'Plazo medio de corrección de vulnerabilidades críticas', 'Tempo medio di correzione delle vulnerabilità critiche'], 'build', U_DAYS, 'HAUSSE', 'MENSUEL')
saas.kri('open-vulns', ['Vulnérabilités critiques ouvertes au-delà du délai cible', 'Critical vulnerabilities open beyond the target time', 'Kritische Schwachstellen, die über die Zielzeit hinaus offen sind', 'Vulnerabilidades críticas abiertas más allá del plazo objetivo', 'Vulnerabilità critiche aperte oltre il termine obiettivo'], 'build', U_NB, 'HAUSSE', 'MENSUEL')
saas.kri('sla-credits', ['Crédits de service ou pénalités versés', 'Service credits or penalties paid', 'Gezahlte Service-Gutschriften oder Vertragsstrafen', 'Créditos de servicio o penalizaciones abonados', 'Crediti di servizio o penali versati'], 'host', U_NB, 'HAUSSE', 'MENSUEL')
saas.kri('mttr', ['Durée moyenne de rétablissement après incident de service', 'Mean time to restore after a service incident', 'Mittlere Wiederherstellungszeit nach einer Dienststörung', 'Tiempo medio de restablecimiento tras un incidente de servicio', 'Tempo medio di ripristino dopo un incidente di servizio'], 'support', U_MIN, 'HAUSSE', 'MENSUEL')
saas.kri('support-data-access', ['Accès du support aux données clients sans ticket associé', 'Support access to customer data without an associated ticket', 'Support-Zugriffe auf Kundendaten ohne zugehöriges Ticket', 'Accesos del soporte a datos de clientes sin ticket asociado', 'Accessi del supporto ai dati dei clienti senza ticket associato'], 'support', U_NB, 'HAUSSE', 'MENSUEL')
saas.kri('stale-keys', ['Clés d’API non renouvelées depuis plus d’un an', 'API keys not rotated for over a year', 'Seit über einem Jahr nicht rotierte API-Schlüssel', 'Claves de API sin renovar desde hace más de un año', 'Chiavi API non ruotate da oltre un anno'], 'onboard', U_NB, 'HAUSSE', 'TRIMESTRIEL')
saas.audit('secure-development', ['Audit du cycle de développement sécurisé', 'Audit of the secure development lifecycle', 'Audit des sicheren Entwicklungszyklus', 'Auditoría del ciclo de desarrollo seguro', 'Audit del ciclo di sviluppo sicuro'], 'build', ['release', 'supply-chain', 'secrets', 'vulnerability-disclosure'], [
  ['Les changements sont revus et approuvés avant mise en production', 'Changes are reviewed and approved before production', 'Änderungen werden vor dem Produktivgang geprüft und genehmigt', 'Los cambios se revisan y aprueban antes de pasar a producción', 'Le modifiche sono riviste e approvate prima della messa in produzione'],
  ['Les dépendances et la chaîne de build sont surveillées', 'Dependencies and the build chain are monitored', 'Abhängigkeiten und die Build-Kette werden überwacht', 'Las dependencias y la cadena de compilación están vigiladas', 'Le dipendenze e la catena di build sono monitorate'],
  ['Les secrets ne sont pas stockés dans le code', 'Secrets are not stored in code', 'Geheimnisse werden nicht im Code gespeichert', 'Los secretos no se almacenan en el código', 'I segreti non sono memorizzati nel codice'],
  ['Un processus de gestion des vulnérabilités signalées est défini', 'A process for handling reported vulnerabilities is defined', 'Ein Prozess für gemeldete Schwachstellen ist festgelegt', 'Existe un proceso para gestionar las vulnerabilidades notificadas', 'È definito un processo per la gestione delle vulnerabilità segnalate'],
])
saas.audit('tenant-security', ['Audit de l’isolation et de la sécurité multi-clients', 'Audit of multi-tenant isolation and security', 'Audit von Mandantentrennung und Mehrmandanten-Sicherheit', 'Auditoría del aislamiento y de la seguridad multicliente', 'Audit dell’isolamento e della sicurezza multi-tenant'], 'host', ['tenant-isolation', 'support-access', 'data-residency'], [
  ['L’isolation entre clients est testée régulièrement', 'Isolation between customers is tested regularly', 'Die Trennung zwischen Kunden wird regelmäßig getestet', 'El aislamiento entre clientes se prueba regularmente', 'L’isolamento tra clienti è testato regolarmente'],
  ['Les accès privilégiés sont limités, temporaires et journalisés', 'Privileged access is limited, temporary and logged', 'Privilegierte Zugriffe sind begrenzt, befristet und protokolliert', 'Los accesos privilegiados son limitados, temporales y registrados', 'Gli accessi privilegiati sono limitati, temporanei e registrati'],
  ['La localisation des données et des sous-traitants est conforme au contrat', 'Data and sub-processor locations match the contract', 'Standort von Daten und Unterauftragsverarbeitern entspricht dem Vertrag', 'La ubicación de los datos y subencargados es conforme al contrato', 'La localizzazione dei dati e dei sub-responsabili è conforme al contratto'],
  ['Les clients sont informés des incidents affectant leurs données', 'Customers are informed of incidents affecting their data', 'Kunden werden über Vorfälle mit Auswirkungen auf ihre Daten informiert', 'Los clientes son informados de los incidentes que afectan a sus datos', 'I clienti sono informati degli incidenti che riguardano i loro dati'],
])
saas.audit('service-continuity', ['Audit de la continuité et de la reprise de service', 'Audit of service continuity and recovery', 'Audit von Servicekontinuität und Wiederherstellung', 'Auditoría de la continuidad y recuperación del servicio', 'Audit della continuità e del ripristino del servizio'], 'host', ['cloud-outage', 'tenant-restore', 'sla-breach'], [
  ['Les objectifs de reprise sont définis et alignés sur les engagements clients', 'Recovery objectives are defined and aligned with customer commitments', 'Wiederanlaufziele sind definiert und auf Kundenzusagen abgestimmt', 'Los objetivos de recuperación están definidos y alineados con los compromisos con clientes', 'Gli obiettivi di ripristino sono definiti e allineati agli impegni con i clienti'],
  ['Les sauvegardes sont chiffrées, isolées et leur restauration est testée', 'Backups are encrypted, isolated and restoration is tested', 'Sicherungen sind verschlüsselt, isoliert und ihre Wiederherstellung wird getestet', 'Las copias están cifradas, aisladas y su restauración se prueba', 'I backup sono cifrati, isolati e il ripristino è testato'],
  ['Les dépendances critiques à des tiers sont identifiées', 'Critical third-party dependencies are identified', 'Kritische Abhängigkeiten von Dritten sind identifiziert', 'Las dependencias críticas de terceros están identificadas', 'Le dipendenze critiche da terzi sono identificate'],
  ['Les incidents font l’objet d’un retour d’expérience', 'Incidents lead to a post-incident review', 'Vorfälle werden nachbereitet', 'Los incidentes dan lugar a una revisión posterior', 'Gli incidenti sono oggetto di un riesame successivo'],
])

// ════════════════════════════ Santé / Médico-social ═════════════════════════
const sante = sectorPack('SANTE')
sante.risk('ransomware-hospital', 2, ['Un rançongiciel paralyse les systèmes de soins et impose des procédures dégradées', 'Ransomware paralyses care systems and forces degraded procedures', 'Ransomware legt Versorgungssysteme lahm und erzwingt Notverfahren', 'Un ransomware paraliza los sistemas asistenciales y obliga a procedimientos degradados', 'Un ransomware paralizza i sistemi di cura e impone procedure degradate'], 'care')
sante.risk('medication-error', 3, ['Une erreur de prescription, de préparation ou d’administration d’un médicament atteint un patient', 'A prescribing, preparation or administration error reaches a patient', 'Ein Verordnungs-, Zubereitungs- oder Verabreichungsfehler erreicht einen Patienten', 'Un error de prescripción, preparación o administración de un medicamento alcanza a un paciente', 'Un errore di prescrizione, preparazione o somministrazione di un farmaco raggiunge un paziente'], 'care')
sante.risk('patient-identity', 3, ['Un patient est mal identifié et reçoit un acte ou un résultat destiné à un autre', 'A patient is misidentified and receives an act or result meant for another', 'Ein Patient wird falsch identifiziert und erhält eine Maßnahme oder ein Ergebnis eines anderen', 'Un paciente es mal identificado y recibe un acto o resultado de otro', 'Un paziente viene identificato male e riceve un atto o un risultato destinato a un altro'], 'records')
sante.risk('hds-provider', 6, ['Un hébergeur de données de santé défaille ou n’est pas certifié', 'A health-data host fails or is not certified', 'Ein Gesundheitsdaten-Hoster fällt aus oder ist nicht zertifiziert', 'Un alojador de datos de salud falla o carece de certificación', 'Un fornitore di hosting di dati sanitari viene meno o non è certificato'], 'records')
sante.risk('cold-chain-health', 5, ['Une rupture de la chaîne du froid altère des médicaments, vaccins ou prélèvements', 'A cold-chain break spoils medicines, vaccines or specimens', 'Eine Kühlketten-Unterbrechung verdirbt Arzneimittel, Impfstoffe oder Proben', 'Una ruptura de la cadena de frío deteriora medicamentos, vacunas o muestras', 'Un’interruzione della catena del freddo deteriora farmaci, vaccini o campioni'], 'supply')
sante.control('record-access-break-glass', ['Revue des accès d’urgence (« bris de glace ») aux dossiers patients', 'Review of emergency (“break-glass”) access to patient records', 'Überprüfung von Notfallzugriffen („Break-Glass“) auf Patientenakten', 'Revisión de los accesos de urgencia («romper el cristal») a historias de pacientes', 'Revisione degli accessi di emergenza («break-glass») ai fascicoli dei pazienti'], 'records', 'MENSUEL', 'DETECTIF', ['patient-data'], [PGSSI])
sante.control('vip-records', ['Contrôle des accès aux dossiers de personnes sensibles ou de l’entourage du personnel', 'Check of access to records of sensitive persons or staff relatives', 'Kontrolle der Zugriffe auf Akten sensibler Personen oder von Angehörigen des Personals', 'Control de los accesos a historias de personas sensibles o de allegados al personal', 'Controllo degli accessi ai fascicoli di persone sensibili o di familiari del personale'], 'records', 'MENSUEL', 'DETECTIF', ['patient-data'])
sante.control('hds-certificates', ['Vérification de la certification des hébergeurs de données de santé et des clauses contractuelles', 'Check of health-data host certification and contract clauses', 'Prüfung der Zertifizierung von Gesundheitsdaten-Hostern und der Vertragsklauseln', 'Verificación de la certificación de los alojadores de datos de salud y de las cláusulas contractuales', 'Verifica della certificazione dei fornitori di hosting di dati sanitari e delle clausole contrattuali'], 'records', 'ANNUEL', 'PREVENTIF', ['hds-provider', 'patient-data'], [HDS])
sante.control('patient-rights', ['Suivi des demandes d’accès et de rectification de dossiers patients', 'Follow-up of patient record access and rectification requests', 'Nachverfolgung von Auskunfts- und Berichtigungsanträgen zu Patientenakten', 'Seguimiento de las solicitudes de acceso y rectificación de historias de pacientes', 'Monitoraggio delle richieste di accesso e rettifica dei fascicoli dei pazienti'], 'records', 'MENSUEL', 'DETECTIF', ['patient-data', 'consent'], [RGPD])
sante.control('consent-sample', ['Contrôle par échantillon du recueil et du respect des consentements et oppositions', 'Sample check of collection and respect of consents and objections', 'Stichprobenprüfung der Einholung und Beachtung von Einwilligungen und Widersprüchen', 'Control por muestreo de la obtención y respeto de los consentimientos y oposiciones', 'Controllo a campione della raccolta e del rispetto di consensi e opposizioni'], 'records', 'TRIMESTRIEL', 'DETECTIF', ['consent'])
sante.control('duplicate-identities', ['Revue des doublons et collisions d’identités dans le dossier patient', 'Review of duplicate and colliding identities in the patient record', 'Überprüfung von Dubletten und Identitätskollisionen in der Patientenakte', 'Revisión de duplicados y colisiones de identidades en la historia del paciente', 'Revisione dei duplicati e delle collisioni di identità nel fascicolo del paziente'], 'records', 'MENSUEL', 'DETECTIF', ['patient-identity', 'record-integrity'])
sante.control('wristband-sample', ['Contrôle par échantillon de la vérification d’identité avant acte (bracelet, double vérification)', 'Sample check of identity verification before procedures (wristband, double check)', 'Stichprobenprüfung der Identitätsprüfung vor Maßnahmen (Armband, Doppelkontrolle)', 'Control por muestreo de la verificación de identidad antes de un acto (pulsera, doble verificación)', 'Controllo a campione della verifica dell’identità prima dell’atto (braccialetto, doppio controllo)'], 'care', 'MENSUEL', 'DETECTIF', ['patient-identity'])
sante.control('medication-circuit', ['Contrôle par échantillon du circuit du médicament (prescription, dispensation, administration)', 'Sample check of the medication circuit (prescribing, dispensing, administration)', 'Stichprobenprüfung des Medikationsprozesses (Verordnung, Abgabe, Verabreichung)', 'Control por muestreo del circuito del medicamento (prescripción, dispensación, administración)', 'Controllo a campione del circuito del farmaco (prescrizione, dispensazione, somministrazione)'], 'care', 'MENSUEL', 'DETECTIF', ['medication-error'])
sante.control('narcotics-reconciliation', ['Rapprochement des stocks de stupéfiants et médicaments à risque', 'Reconciliation of narcotics and high-risk medicine stocks', 'Abgleich der Bestände an Betäubungsmitteln und Hochrisikoarzneimitteln', 'Conciliación de las existencias de estupefacientes y medicamentos de riesgo', 'Riconciliazione delle scorte di stupefacenti e farmaci ad alto rischio'], 'supply', 'MENSUEL', 'DETECTIF', ['medication-error', 'stockout'])
sante.control('downtime-procedures', ['Exercice de fonctionnement en mode dégradé (sans dossier patient informatisé)', 'Exercise of degraded operation (without the electronic patient record)', 'Übung zum Notbetrieb (ohne elektronische Patientenakte)', 'Ejercicio de funcionamiento en modo degradado (sin historia clínica electrónica)', 'Esercitazione di funzionamento in modalità degradata (senza cartella clinica elettronica)'], 'care', 'ANNUEL', 'PREVENTIF', ['care-outage', 'ransomware-hospital'])
sante.control('backup-restore-care', ['Test de restauration des applications de soins et d’imagerie', 'Restoration test of care and imaging applications', 'Wiederherstellungstest der Versorgungs- und Bildgebungsanwendungen', 'Prueba de restauración de las aplicaciones asistenciales y de imagen', 'Test di ripristino delle applicazioni cliniche e di imaging'], 'care', 'SEMESTRIEL', 'DETECTIF', ['care-outage', 'ransomware-hospital'])
sante.control('biomedical-inventory', ['Rapprochement de l’inventaire des dispositifs médicaux connectés avec le réseau', 'Reconciliation of connected medical-device inventory with the network', 'Abgleich des Inventars vernetzter Medizinprodukte mit dem Netz', 'Conciliación del inventario de dispositivos médicos conectados con la red', 'Riconciliazione dell’inventario dei dispositivi medici connessi con la rete'], 'care', 'SEMESTRIEL', 'DETECTIF', ['device'], [MDR])
sante.control('device-vulnerabilities', ['Suivi des alertes de sécurité des constructeurs de dispositifs médicaux', 'Follow-up of manufacturers’ security alerts for medical devices', 'Nachverfolgung von Sicherheitswarnungen der Medizinproduktehersteller', 'Seguimiento de las alertas de seguridad de los fabricantes de dispositivos médicos', 'Monitoraggio degli avvisi di sicurezza dei produttori di dispositivi medici'], 'care', 'MENSUEL', 'DETECTIF', ['device'], [MDR])
sante.control('lab-quality', ['Revue des contrôles de qualité internes et externes de la biologie', 'Review of internal and external quality controls in the laboratory', 'Überprüfung der internen und externen Qualitätskontrollen im Labor', 'Revisión de los controles de calidad internos y externos del laboratorio', 'Revisione dei controlli di qualità interni ed esterni del laboratorio'], 'lab', 'MENSUEL', 'DETECTIF', ['result-error'])
sante.control('critical-results', ['Contrôle par échantillon de la transmission des résultats critiques', 'Sample check of transmission of critical results', 'Stichprobenprüfung der Übermittlung kritischer Ergebnisse', 'Control por muestreo de la transmisión de resultados críticos', 'Controllo a campione della trasmissione dei risultati critici'], 'lab', 'MENSUEL', 'DETECTIF', ['result-error'])
sante.control('cold-chain-health-logs', ['Revue des relevés et alarmes de température des enceintes froides', 'Review of temperature logs and alarms of cold storage', 'Überprüfung der Temperaturaufzeichnungen und -alarme der Kühlräume', 'Revisión de los registros y alarmas de temperatura de las cámaras frías', 'Revisione dei registri e degli allarmi di temperatura delle celle fredde'], 'supply', 'MENSUEL', 'DETECTIF', ['cold-chain-health'])
sante.control('stock-critical', ['Revue des stocks et substituts des produits de santé essentiels', 'Review of stocks and substitutes for essential health products', 'Überprüfung von Beständen und Alternativen wesentlicher Gesundheitsprodukte', 'Revisión de las existencias y sustitutos de los productos sanitarios esenciales', 'Revisione delle scorte e dei sostituti dei prodotti sanitari essenziali'], 'supply', 'TRIMESTRIEL', 'DETECTIF', ['stockout'])
sante.control('adverse-events', ['Revue des événements indésirables déclarés et suivi des actions correctives', 'Review of reported adverse events and follow-up of corrective actions', 'Überprüfung gemeldeter unerwünschter Ereignisse und Nachverfolgung von Korrekturmaßnahmen', 'Revisión de los eventos adversos notificados y seguimiento de las acciones correctivas', 'Revisione degli eventi avversi segnalati e monitoraggio delle azioni correttive'], 'care', 'TRIMESTRIEL', 'DETECTIF', ['medication-error', 'patient-identity'])
sante.kri('breakglass-accesses', ['Accès d’urgence aux dossiers sans justification a posteriori', 'Emergency record access without after-the-fact justification', 'Notfallzugriffe auf Akten ohne nachträgliche Begründung', 'Accesos de urgencia a historias sin justificación a posteriori', 'Accessi di emergenza ai fascicoli senza giustificazione a posteriori'], 'records', U_NB, 'HAUSSE', 'MENSUEL')
sante.kri('identity-duplicates', ['Doublons d’identités patients détectés', 'Duplicate patient identities detected', 'Erkannte Dubletten von Patientenidentitäten', 'Duplicados de identidades de pacientes detectados', 'Duplicati di identità dei pazienti rilevati'], 'records', U_NB, 'HAUSSE', 'MENSUEL')
sante.kri('medication-events', ['Événements indésirables liés au médicament déclarés', 'Reported medication-related adverse events', 'Gemeldete arzneimittelbezogene unerwünschte Ereignisse', 'Eventos adversos relacionados con medicamentos notificados', 'Eventi avversi correlati ai farmaci segnalati'], 'care', U_NB, 'HAUSSE', 'MENSUEL')
sante.kri('unpatched-devices', ['Dispositifs médicaux connectés avec correctif de sécurité en retard', 'Connected medical devices with overdue security patches', 'Vernetzte Medizinprodukte mit überfälligem Sicherheits-Patch', 'Dispositivos médicos conectados con parche de seguridad atrasado', 'Dispositivi medici connessi con patch di sicurezza in ritardo'], 'care', U_NB, 'HAUSSE', 'MENSUEL')
sante.kri('lab-turnaround', ['Délai de rendu des résultats urgents', 'Turnaround time of urgent results', 'Bearbeitungszeit dringender Ergebnisse', 'Plazo de entrega de resultados urgentes', 'Tempo di refertazione dei risultati urgenti'], 'lab', U_MIN, 'HAUSSE', 'MENSUEL')
sante.kri('cold-chain-excursions', ['Excursions de température en enceintes froides', 'Temperature excursions in cold storage', 'Temperaturabweichungen in Kühlräumen', 'Excursiones de temperatura en cámaras frías', 'Escursioni di temperatura nelle celle fredde'], 'supply', U_NB, 'HAUSSE', 'MENSUEL')
sante.audit('medication-safety', ['Audit de la sécurité du circuit du médicament', 'Audit of medication-circuit safety', 'Audit der Sicherheit des Medikationsprozesses', 'Auditoría de la seguridad del circuito del medicamento', 'Audit della sicurezza del circuito del farmaco'], 'care', ['medication-error', 'stockout'], [
  ['Les prescriptions sont complètes et vérifiées avant dispensation', 'Prescriptions are complete and checked before dispensing', 'Verordnungen sind vollständig und werden vor der Abgabe geprüft', 'Las prescripciones están completas y se verifican antes de la dispensación', 'Le prescrizioni sono complete e verificate prima della dispensazione'],
  ['Les médicaments à risque font l’objet d’une double vérification', 'High-risk medicines are double-checked', 'Hochrisikoarzneimittel werden doppelt geprüft', 'Los medicamentos de riesgo se verifican por doble control', 'I farmaci ad alto rischio sono sottoposti a doppio controllo'],
  ['Les événements indésirables sont déclarés et analysés', 'Adverse events are reported and analysed', 'Unerwünschte Ereignisse werden gemeldet und analysiert', 'Los eventos adversos se notifican y analizan', 'Gli eventi avversi sono segnalati e analizzati'],
  ['Les stocks des produits essentiels sont suivis', 'Stocks of essential products are monitored', 'Bestände wesentlicher Produkte werden überwacht', 'Las existencias de productos esenciales se supervisan', 'Le scorte dei prodotti essenziali sono monitorate'],
])
sante.audit('care-continuity', ['Audit de la continuité des systèmes de soins', 'Audit of care-system continuity', 'Audit der Kontinuität der Versorgungssysteme', 'Auditoría de la continuidad de los sistemas asistenciales', 'Audit della continuità dei sistemi di cura'], 'care', ['care-outage', 'ransomware-hospital', 'device'], [
  ['Les applications critiques de soins sont identifiées avec leurs secours', 'Critical care applications are identified with their backups', 'Kritische Versorgungsanwendungen sind mit Ersatzlösungen identifiziert', 'Las aplicaciones asistenciales críticas están identificadas con sus respaldos', 'Le applicazioni cliniche critiche sono identificate con i relativi backup'],
  ['Des procédures dégradées sont connues et exercées', 'Degraded procedures are known and exercised', 'Notfallverfahren sind bekannt und werden geübt', 'Los procedimientos degradados son conocidos y se ejercitan', 'Le procedure degradate sono note ed esercitate'],
  ['Les sauvegardes sont isolées et leur restauration testée', 'Backups are isolated and restoration tested', 'Sicherungen sind isoliert und ihre Wiederherstellung getestet', 'Las copias están aisladas y su restauración se prueba', 'I backup sono isolati e il ripristino testato'],
  ['Les dispositifs médicaux connectés sont inventoriés et protégés', 'Connected medical devices are inventoried and protected', 'Vernetzte Medizinprodukte sind inventarisiert und geschützt', 'Los dispositivos médicos conectados están inventariados y protegidos', 'I dispositivi medici connessi sono inventariati e protetti'],
])
sante.audit('patient-identity', ['Audit de l’identitovigilance', 'Audit of patient-identity management', 'Audit der Patientenidentitätssicherung', 'Auditoría de la identidad del paciente', 'Audit della gestione dell’identità del paziente'], 'records', ['patient-identity', 'record-integrity'], [
  ['Les règles de création et de fusion des identités sont définies', 'Rules for creating and merging identities are defined', 'Regeln für Anlage und Zusammenführung von Identitäten sind festgelegt', 'Las reglas de creación y fusión de identidades están definidas', 'Le regole di creazione e fusione delle identità sono definite'],
  ['Les doublons et collisions sont détectés et traités', 'Duplicates and collisions are detected and handled', 'Dubletten und Kollisionen werden erkannt und bearbeitet', 'Los duplicados y colisiones se detectan y tratan', 'I duplicati e le collisioni sono rilevati e trattati'],
  ['L’identité est vérifiée avant chaque acte à risque', 'Identity is checked before each high-risk act', 'Die Identität wird vor jeder risikoreichen Maßnahme geprüft', 'La identidad se verifica antes de cada acto de riesgo', 'L’identità è verificata prima di ogni atto a rischio'],
  ['Les événements d’identité erronée sont analysés', 'Wrong-identity events are analysed', 'Ereignisse mit falscher Identität werden analysiert', 'Los eventos de identidad errónea se analizan', 'Gli eventi di identità errata sono analizzati'],
])

// ════════════════════════════ Télécommunications ════════════════════════════
const tel = sectorPack('TELECOM')
tel.risk('signalling-abuse', 2, ['Une faille de signalisation permet l’interception ou la localisation d’abonnés', 'A signalling weakness allows interception or location of subscribers', 'Eine Schwachstelle in der Signalisierung ermöglicht Abhören oder Ortung von Teilnehmern', 'Una debilidad de señalización permite interceptar o localizar abonados', 'Una debolezza della segnalazione consente di intercettare o localizzare gli abbonati'], 'network')
tel.risk('core-compromise', 2, ['Un équipement ou un fournisseur de cœur de réseau est compromis', 'A core-network element or vendor is compromised', 'Ein Kernnetz-Element oder Lieferant wird kompromittiert', 'Un elemento o proveedor del núcleo de red se ve comprometido', 'Un elemento o fornitore del core network viene compromesso'], 'network')
tel.risk('ddos-customers', 2, ['Une attaque par déni de service sature le réseau ou des services clients', 'A denial-of-service attack saturates the network or customer services', 'Ein Denial-of-Service-Angriff überlastet das Netz oder Kundendienste', 'Un ataque de denegación de servicio satura la red o servicios de clientes', 'Un attacco denial of service satura la rete o i servizi ai clienti'], 'network')
tel.risk('site-power', 5, ['Une coupure d’énergie ou un sinistre prive des sites techniques de leur alimentation', 'A power cut or disaster deprives technical sites of power', 'Ein Stromausfall oder Schadensfall nimmt technischen Standorten die Stromversorgung', 'Un corte de energía o siniestro deja sin alimentación a sitios técnicos', 'Un’interruzione di corrente o un sinistro lascia i siti tecnici senza alimentazione'], 'network')
tel.risk('retention-obligations', 7, ['Les obligations de conservation et de communication de données aux autorités ne sont pas respectées', 'Data retention and disclosure obligations to authorities are not met', 'Pflichten zur Datenspeicherung und Herausgabe an Behörden werden nicht erfüllt', 'No se cumplen las obligaciones de conservación y comunicación de datos a las autoridades', 'Gli obblighi di conservazione e comunicazione dei dati alle autorità non sono rispettati'], 'lawful')
tel.control('network-change-sample', ['Contrôle par échantillon de l’approbation et du test des changements réseau', 'Sample check of approval and testing of network changes', 'Stichprobenprüfung der Genehmigung und des Tests von Netzänderungen', 'Control por muestreo de la aprobación y prueba de los cambios de red', 'Controllo a campione dell’approvazione e del test delle modifiche di rete'], 'network', 'MENSUEL', 'DETECTIF', ['config-change', 'outage'])
tel.control('rollback-plan', ['Vérification de l’existence d’un retour arrière avant changement majeur', 'Check of a rollback plan before a major change', 'Prüfung eines Rückfallplans vor größeren Änderungen', 'Verificación de un plan de marcha atrás antes de un cambio importante', 'Verifica di un piano di rollback prima di una modifica importante'], 'network', 'MENSUEL', 'PREVENTIF', ['config-change'])
tel.control('signalling-firewall', ['Revue des règles et alertes de filtrage de la signalisation', 'Review of signalling filtering rules and alerts', 'Überprüfung der Filterregeln und Warnungen der Signalisierung', 'Revisión de las reglas y alertas de filtrado de la señalización', 'Revisione delle regole e degli alert di filtraggio della segnalazione'], 'network', 'MENSUEL', 'DETECTIF', ['signalling-abuse', 'traffic-data'], [EPRIVACY])
tel.control('vendor-access', ['Revue des accès distants des équipementiers aux équipements de cœur de réseau', 'Review of vendors’ remote access to core-network equipment', 'Überprüfung der Fernzugriffe von Ausrüstern auf Kernnetz-Geräte', 'Revisión de los accesos remotos de los fabricantes a equipos del núcleo de red', 'Revisione degli accessi remoti dei produttori alle apparecchiature del core network'], 'network', 'TRIMESTRIEL', 'DETECTIF', ['core-compromise'], [NIS2])
tel.control('vendor-diversity', ['Revue de la dépendance à un équipementier unique pour les fonctions critiques', 'Review of reliance on a single vendor for critical functions', 'Überprüfung der Abhängigkeit von einem einzigen Ausrüster für kritische Funktionen', 'Revisión de la dependencia de un único fabricante para funciones críticas', 'Revisione della dipendenza da un unico fornitore per le funzioni critiche'], 'network', 'ANNUEL', 'DETECTIF', ['core-compromise', 'outage'], [NIS2])
tel.control('ddos-mitigation-test', ['Test du dispositif d’atténuation des attaques par déni de service', 'Test of denial-of-service mitigation', 'Test der Abwehr von Denial-of-Service-Angriffen', 'Prueba del dispositivo de mitigación de ataques de denegación de servicio', 'Test del dispositivo di mitigazione degli attacchi denial of service'], 'network', 'SEMESTRIEL', 'PREVENTIF', ['ddos-customers'])
tel.control('capacity-review', ['Revue de la capacité des liens et des équipements face aux pics de trafic', 'Review of link and equipment capacity against traffic peaks', 'Überprüfung der Kapazität von Verbindungen und Geräten gegenüber Verkehrsspitzen', 'Revisión de la capacidad de enlaces y equipos frente a picos de tráfico', 'Revisione della capacità di collegamenti e apparati rispetto ai picchi di traffico'], 'network', 'TRIMESTRIEL', 'DETECTIF', ['outage', 'ddos-customers'])
tel.control('power-backup-test', ['Test des alimentations de secours des sites techniques', 'Test of backup power at technical sites', 'Test der Notstromversorgung technischer Standorte', 'Prueba de las alimentaciones de respaldo de los sitios técnicos', 'Test delle alimentazioni di emergenza dei siti tecnici'], 'network', 'TRIMESTRIEL', 'PREVENTIF', ['site-power'])
tel.control('emergency-calls', ['Test du routage des appels d’urgence', 'Test of emergency-call routing', 'Test der Notrufweiterleitung', 'Prueba del encaminamiento de llamadas de emergencia', 'Test dell’instradamento delle chiamate di emergenza'], 'network', 'TRIMESTRIEL', 'DETECTIF', ['outage'], [CPCE])
tel.control('provisioning-sample', ['Contrôle par échantillon des activations et modifications de lignes (identité, autorisation)', 'Sample check of line activations and changes (identity, authorisation)', 'Stichprobenprüfung von Anschlussaktivierungen und -änderungen (Identität, Berechtigung)', 'Control por muestreo de las activaciones y cambios de líneas (identidad, autorización)', 'Controllo a campione delle attivazioni e modifiche di linee (identità, autorizzazione)'], 'provision', 'MENSUEL', 'DETECTIF', ['sim-swap'])
tel.control('port-out-fraud', ['Revue des demandes de portabilité et de remplacement de SIM suspectes', 'Review of suspicious number-porting and SIM-replacement requests', 'Überprüfung verdächtiger Rufnummernmitnahme- und SIM-Ersatzanträge', 'Revisión de las solicitudes sospechosas de portabilidad y sustitución de SIM', 'Revisione delle richieste sospette di portabilità e sostituzione SIM'], 'provision', 'MENSUEL', 'DETECTIF', ['sim-swap'])
tel.control('rating-tests', ['Test de non-régression des règles de valorisation avant mise en production d’une offre', 'Regression test of rating rules before launching an offer', 'Regressionstest der Tarifierungsregeln vor Einführung eines Angebots', 'Prueba de no regresión de las reglas de valorización antes de lanzar una oferta', 'Test di non regressione delle regole di valorizzazione prima del lancio di un’offerta'], 'billing', 'TRIMESTRIEL', 'PREVENTIF', ['billing-error'])
tel.control('cdr-reconciliation', ['Rapprochement des enregistrements d’appels réseau avec la facturation', 'Reconciliation of network call records with billing', 'Abgleich der Netz-Verbindungsdatensätze mit der Abrechnung', 'Conciliación de los registros de llamadas de red con la facturación', 'Riconciliazione dei record di chiamata di rete con la fatturazione'], 'billing', 'MENSUEL', 'DETECTIF', ['revenue-leak', 'billing-error'])
tel.control('lawful-requests-register', ['Revue du registre des réquisitions et du respect des délais de réponse', 'Review of the register of authority requests and response times', 'Überprüfung des Registers der Behördenanfragen und der Antwortfristen', 'Revisión del registro de requerimientos y del respeto de los plazos de respuesta', 'Revisione del registro delle richieste delle autorità e del rispetto dei tempi di risposta'], 'lawful', 'MENSUEL', 'DETECTIF', ['request-error', 'retention-obligations'], [CPCE])
tel.control('data-retention-purge', ['Contrôle de la conservation limitée et de la purge des données de trafic', 'Check of limited retention and purging of traffic data', 'Prüfung der begrenzten Speicherung und Löschung von Verkehrsdaten', 'Control de la conservación limitada y de la eliminación de los datos de tráfico', 'Controllo della conservazione limitata e della cancellazione dei dati di traffico'], 'lawful', 'SEMESTRIEL', 'DETECTIF', ['traffic-data', 'retention-obligations'], [EPRIVACY])
tel.control('subscriber-data-access', ['Revue des accès aux données d’abonnés et de trafic par les agents et prestataires', 'Review of staff and provider access to subscriber and traffic data', 'Überprüfung der Zugriffe von Beschäftigten und Dienstleistern auf Teilnehmer- und Verkehrsdaten', 'Revisión de los accesos del personal y de proveedores a datos de abonados y de tráfico', 'Revisione degli accessi di personale e fornitori ai dati degli abbonati e di traffico'], 'lawful', 'TRIMESTRIEL', 'DETECTIF', ['traffic-data'], [RGPD])
tel.control('incident-notification-drill', ['Exercice de notification d’un incident de sécurité significatif aux autorités', 'Exercise of notifying a significant security incident to authorities', 'Übung zur Meldung eines erheblichen Sicherheitsvorfalls an Behörden', 'Ejercicio de notificación de un incidente de seguridad significativo a las autoridades', 'Esercitazione di notifica di un incidente di sicurezza significativo alle autorità'], 'network', 'ANNUEL', 'PREVENTIF', ['outage', 'core-compromise'], [NIS2])
tel.control('lawful-interception-access', ['Revue des accès aux fonctions d’interception légale et aux outils de réquisition', 'Review of access to lawful-interception functions and request tools', 'Überprüfung der Zugriffe auf Funktionen der gesetzlichen Überwachung und Auskunftswerkzeuge', 'Revisión de los accesos a funciones de interceptación legal y herramientas de requerimiento', 'Revisione degli accessi alle funzioni di intercettazione legale e agli strumenti di richiesta'], 'lawful', 'TRIMESTRIEL', 'DETECTIF', ['request-error', 'traffic-data'], [CPCE])
tel.kri('major-incidents', ['Incidents de réseau affectant un grand nombre d’abonnés', 'Network incidents affecting many subscribers', 'Netzstörungen mit vielen betroffenen Teilnehmern', 'Incidentes de red que afectan a muchos abonados', 'Incidenti di rete che coinvolgono molti abbonati'], 'network', U_NB, 'HAUSSE', 'MENSUEL')
tel.kri('outage-minutes', ['Minutes d’indisponibilité des services critiques', 'Minutes of critical-service unavailability', 'Ausfallminuten kritischer Dienste', 'Minutos de indisponibilidad de servicios críticos', 'Minuti di indisponibilità dei servizi critici'], 'network', U_MIN, 'HAUSSE', 'MENSUEL')
tel.kri('sim-swap-cases', ['Remplacements de SIM contestés ou frauduleux', 'Disputed or fraudulent SIM replacements', 'Bestrittene oder betrügerische SIM-Ersetzungen', 'Sustituciones de SIM impugnadas o fraudulentas', 'Sostituzioni SIM contestate o fraudolente'], 'provision', U_NB, 'HAUSSE', 'MENSUEL')
tel.kri('unbilled-usage', ['Consommations réseau sans facturation rapprochée', 'Network usage without reconciled billing', 'Netznutzung ohne abgeglichene Abrechnung', 'Consumos de red sin facturación conciliada', 'Consumi di rete senza fatturazione riconciliata'], 'billing', U_PCT, 'HAUSSE', 'MENSUEL')
tel.kri('requests-late', ['Réquisitions traitées hors délai', 'Authority requests handled late', 'Verspätet bearbeitete Behördenanfragen', 'Requerimientos tramitados fuera de plazo', 'Richieste delle autorità gestite in ritardo'], 'lawful', U_NB, 'HAUSSE', 'MENSUEL')
tel.kri('power-autonomy', ['Sites techniques sans autonomie électrique suffisante', 'Technical sites without sufficient power autonomy', 'Technische Standorte ohne ausreichende Strom-Autonomie', 'Sitios técnicos sin autonomía eléctrica suficiente', 'Siti tecnici senza sufficiente autonomia elettrica'], 'network', U_NB, 'HAUSSE', 'TRIMESTRIEL')
tel.audit('network-resilience', ['Audit de la résilience du réseau', 'Audit of network resilience', 'Audit der Netzresilienz', 'Auditoría de la resiliencia de la red', 'Audit della resilienza della rete'], 'network', ['outage', 'ddos-customers', 'site-power', 'core-compromise'], [
  ['Les fonctions et sites critiques sont identifiés avec leurs secours', 'Critical functions and sites are identified with backups', 'Kritische Funktionen und Standorte sind mit Ersatzlösungen identifiziert', 'Las funciones y sitios críticos están identificados con sus respaldos', 'Le funzioni e i siti critici sono identificati con i relativi backup'],
  ['Les alimentations de secours et la capacité sont testées et revues', 'Backup power and capacity are tested and reviewed', 'Notstrom und Kapazität werden getestet und überprüft', 'Las alimentaciones de respaldo y la capacidad se prueban y revisan', 'Le alimentazioni di emergenza e la capacità sono testate e riviste'],
  ['Les mesures contre le déni de service sont éprouvées', 'Denial-of-service countermeasures are proven', 'Maßnahmen gegen Denial-of-Service sind erprobt', 'Las medidas contra denegación de servicio están probadas', 'Le misure contro il denial of service sono collaudate'],
  ['La dépendance aux équipementiers est évaluée', 'Dependence on vendors is assessed', 'Die Abhängigkeit von Ausrüstern wird bewertet', 'Se evalúa la dependencia de los fabricantes', 'La dipendenza dai fornitori di apparati è valutata'],
])
tel.audit('subscriber-protection', ['Audit de la protection des abonnés et des données de trafic', 'Audit of subscriber and traffic-data protection', 'Audit des Schutzes von Teilnehmern und Verkehrsdaten', 'Auditoría de la protección de abonados y datos de tráfico', 'Audit della protezione degli abbonati e dei dati di traffico'], 'provision', ['sim-swap', 'traffic-data', 'signalling-abuse'], [
  ['L’identité est vérifiée avant toute activation, portabilité ou remplacement de SIM', 'Identity is verified before any activation, porting or SIM replacement', 'Die Identität wird vor Aktivierung, Rufnummernmitnahme oder SIM-Ersatz geprüft', 'La identidad se verifica antes de toda activación, portabilidad o sustitución de SIM', 'L’identità è verificata prima di ogni attivazione, portabilità o sostituzione SIM'],
  ['Les accès aux données de trafic sont limités et journalisés', 'Access to traffic data is limited and logged', 'Zugriffe auf Verkehrsdaten sind begrenzt und protokolliert', 'Los accesos a datos de tráfico son limitados y quedan registrados', 'Gli accessi ai dati di traffico sono limitati e tracciati'],
  ['Les protections de signalisation sont en place et surveillées', 'Signalling protections are in place and monitored', 'Signalisierungsschutz ist vorhanden und wird überwacht', 'Las protecciones de señalización están implantadas y vigiladas', 'Le protezioni della segnalazione sono attive e monitorate'],
  ['Les durées de conservation sont définies et appliquées', 'Retention periods are defined and applied', 'Aufbewahrungsfristen sind festgelegt und werden angewendet', 'Los plazos de conservación están definidos y se aplican', 'I tempi di conservazione sono definiti e applicati'],
])
tel.audit('billing-assurance', ['Audit de la valorisation, de la facturation et de la protection du chiffre d’affaires', 'Audit of rating, billing and revenue protection', 'Audit von Tarifierung, Abrechnung und Erlössicherung', 'Auditoría de la valorización, facturación y protección de ingresos', 'Audit di valorizzazione, fatturazione e revenue assurance'], 'billing', ['revenue-leak', 'billing-error'], [
  ['Les règles de valorisation sont testées avant chaque nouvelle offre', 'Rating rules are tested before each new offer', 'Tarifierungsregeln werden vor jedem neuen Angebot getestet', 'Las reglas de valorización se prueban antes de cada nueva oferta', 'Le regole di valorizzazione sono testate prima di ogni nuova offerta'],
  ['Les enregistrements réseau sont rapprochés de la facturation', 'Network records are reconciled with billing', 'Netzdatensätze werden mit der Abrechnung abgeglichen', 'Los registros de red se concilian con la facturación', 'I record di rete sono riconciliati con la fatturazione'],
  ['Les écarts sont analysés et corrigés dans des délais définis', 'Differences are analysed and corrected within defined timeframes', 'Abweichungen werden innerhalb festgelegter Fristen analysiert und korrigiert', 'Las diferencias se analizan y corrigen en plazos definidos', 'Le differenze sono analizzate e corrette entro termini definiti'],
  ['Les fraudes d’usage sont détectées et suivies', 'Usage fraud is detected and followed up', 'Nutzungsbetrug wird erkannt und nachverfolgt', 'Los fraudes de uso se detectan y se les da seguimiento', 'Le frodi d’uso sono rilevate e monitorate'],
])

export const DEEPEN_B_PACKS = [saas.pack, sante.pack, tel.pack]
