/**
 * Pack « mutuelle santé » (catalogue 1.11) : trois contrôles manquants pour composer un plan de contrôle permanent
 * équilibré (données de santé, LCB-FT, continuité d'activité). Les autres domaines (gouvernance, honorabilité,
 * conseil, réclamations, prestations, cotisations, délégataires, résilience TIC, solvabilité) existent déjà dans le
 * pack assurance. Suggestions à qualifier : aucun seuil, aucune exécution ; contenu « à relire par un expert ».
 */
import { sectorPack } from './catalogue-pack-builder'

const mut = sectorPack('ASSURANCE')

mut.risk('aml-gap', 4, ['Un dispositif de lutte contre le blanchiment et le financement du terrorisme est incomplet ou non appliqué', 'An anti-money-laundering and counter-terrorist-financing framework is incomplete or not applied', 'Ein Dispositiv zur Bekämpfung von Geldwäsche und Terrorismusfinanzierung ist unvollständig oder wird nicht angewandt', 'Un dispositivo de lucha contra el blanqueo de capitales y la financiación del terrorismo está incompleto o no se aplica', 'Un dispositivo di contrasto al riciclaggio e al finanziamento del terrorismo è incompleto o non applicato'], 'aml')
mut.risk('health-data-misuse', 4, ['Des données de santé d’adhérents sont consultées ou exploitées hors de leur finalité', 'Members’ health data is accessed or used beyond its purpose', 'Gesundheitsdaten von Mitgliedern werden außerhalb ihres Zwecks abgerufen oder verwendet', 'Los datos de salud de los mutualistas se consultan o se utilizan fuera de su finalidad', 'I dati sanitari degli aderenti sono consultati o utilizzati oltre la loro finalità'], 'members')

mut.control('aml-framework', ['Contrôle du dispositif LCB-FT : classification des risques, vigilance proportionnée, examen des opérations atypiques et déclarations de soupçon', 'Check of the AML/CFT framework: risk classification, proportionate due diligence, review of atypical transactions and suspicious-transaction reports', 'Prüfung des GwG-Dispositivs: Risikoklassifizierung, verhältnismäßige Sorgfaltspflichten, Prüfung ungewöhnlicher Transaktionen und Verdachtsmeldungen', 'Control del dispositivo de lucha contra el blanqueo: clasificación de riesgos, diligencia proporcionada, examen de operaciones atípicas y comunicaciones de sospecha', 'Verifica del dispositivo antiriciclaggio: classificazione dei rischi, adeguata verifica proporzionata, esame delle operazioni atipiche e segnalazioni di operazioni sospette'], 'aml', 'TRIMESTRIEL', 'DETECTIF', ['aml-gap'], ['Code monétaire et financier, livre V, titre VI (LCB-FT, gel des avoirs)'])
mut.control('health-data-access', ['Revue des accès aux données de santé des adhérents et de leur traçabilité (habilitations, motifs de consultation)', 'Review of access to members’ health data and its traceability (authorisations, reasons for consultation)', 'Überprüfung der Zugriffe auf Gesundheitsdaten der Mitglieder und ihrer Nachvollziehbarkeit (Berechtigungen, Abrufgründe)', 'Revisión de los accesos a los datos de salud de los mutualistas y de su trazabilidad (habilitaciones, motivos de consulta)', 'Verifica degli accessi ai dati sanitari degli aderenti e della loro tracciabilità (autorizzazioni, motivi di consultazione)'], 'members', 'MENSUEL', 'DETECTIF', ['health-data-misuse', 'customer-data'], ['Règlement (UE) 2016/679 (RGPD), art. 9 et 32'])
mut.control('continuity-test', ['Test du plan de continuité d’activité et de reprise après sinistre sur les services critiques (gestion des adhérents, prestations, tiers payant)', 'Test of the business continuity and disaster recovery plan on critical services (member administration, benefits, third-party payment)', 'Test des Geschäftsfortführungs- und Notfallwiederherstellungsplans für kritische Dienste (Mitgliederverwaltung, Leistungen, Direktabrechnung)', 'Prueba del plan de continuidad de la actividad y de recuperación ante desastres en los servicios críticos (gestión de mutualistas, prestaciones, tercero pagador)', 'Test del piano di continuità operativa e di ripristino sui servizi critici (gestione degli aderenti, prestazioni, terzo pagante)'], 'ict', 'ANNUEL', 'DETECTIF', ['core.risk.continuity-plan', 'core.risk.it-outage'], ['Règlement (UE) 2022/2554 (DORA), art. 11 et 12'])
mut.control('remediation-followup', ['Suivi des plans d’action issus des contrôles, audits, incidents et réclamations (échéances, preuves de clôture, escalade)', 'Follow-up of action plans arising from controls, audits, incidents and complaints (deadlines, closure evidence, escalation)', 'Nachverfolgung von Maßnahmenplänen aus Kontrollen, Prüfungen, Vorfällen und Beschwerden (Fristen, Abschlussnachweise, Eskalation)', 'Seguimiento de los planes de acción derivados de controles, auditorías, incidentes y reclamaciones (plazos, pruebas de cierre, escalado)', 'Monitoraggio dei piani d’azione derivanti da controlli, audit, incidenti e reclami (scadenze, prove di chiusura, escalation)'], 'governance', 'TRIMESTRIEL', 'CORRECTIF', ['core.risk.obligation-missed'], ['Directive 2009/138/CE (Solvabilité II), art. 41 et 46'])

export const MUTUELLE_PACK = mut.pack
