/**
 * Exemples métier proposés, jamais instanciés automatiquement. Les identifiants
 * sont stables entre langues et versions ; les libellés peuvent évoluer.
 * Aucune cotation, obligation réputée satisfaite ou contrepartie fictive.
 */
import { SECTOR_PACK_ITEMS } from './sector-packs'
import { EXT_ITEMS } from './sector-packs-ext'
import { BANCASSURANCE_ITEMS } from './sector-packs-bancassurance'
import { RESILIENCE_TEST_TEMPLATES } from './catalogue-resilience'
import { RISK_BALE, MERGED_REGISTRY_RISKS } from './catalogue-risks'
import { CONTROL_RISKS, AUDIT_RISKS } from './catalogue-links'
import type { TestResilienceType } from './tests-resilience'

// Ordre = celui des secteurs de l'analyse de risque cyber (SECTEURS_ACTIVITE) ; l'assurance suit « Banque / Finance »
// dont elle relève dans l'analyse. Seuls les secteurs choisis par l'organisation sont proposés (cf. sector-selection).
export const SECTOR_CODES = [
  'PUBLIC', 'FINANCE', 'ASSURANCE', 'DEFENSE', 'EDUCATION', 'ENERGIE', 'INDUSTRIE', 'SAAS', 'SANTE', 'TELECOM', 'TRANSPORT',
  'COMMERCE', 'SERVICES', 'AGRICOLE', 'IMMOBILIER', 'MEDIA', 'TOURISME', 'ASSOCIATIONS', 'PROTECTION_SOCIALE', 'TECHNIQUE',
] as const
export type SectorCode = (typeof SECTOR_CODES)[number]
export type CatalogueLocale = 'fr' | 'en' | 'de' | 'es' | 'it'
export type Localized = Record<CatalogueLocale, string>
export type CatalogueItem = {
  key: string
  sector: SectorCode | 'TRANSVERSAL'
  kind: 'PROCESS' | 'RISK' | 'CONTROL' | 'KRI' | 'AUDIT' | 'RESILIENCE_TEST'
  title: Localized
  // Risques : description indicative (reprise de l'ancien socle du registre) — facultative.
  description?: Localized
  parentKey?: string
  processKey?: string
  // Contrôles seulement : périodicité et typologie SUGGÉRÉES (modifiables) ; aucune exécution ni efficacité n'est jamais créée.
  periodicite?: 'HEBDOMADAIRE' | 'MENSUEL' | 'TRIMESTRIEL' | 'SEMESTRIEL' | 'ANNUEL'
  controlType?: 'PREVENTIF' | 'DETECTIF' | 'CORRECTIF'
  // KRI seulement : unité, sens de dégradation et fréquence SUGGÉRÉS ; aucun seuil, aucune valeur mesurée.
  unite?: Localized
  sens?: 'HAUSSE' | 'BAISSE'
  // Mission d'audit seulement : points de revue types (programme) ; aucune date, aucune notation, aucun constat.
  points?: Localized[]
  // Plan de test de résilience modèle seulement : type de test (DORA art. 25 § 1, jamais TLPT) ; ni date, ni testeur, ni résultat.
  testType?: Exclude<TestResilienceType, 'TLPT'>
  // Textes d'origine cités (intitulé officiel, version) : ancrent le domaine ; ne reproduisent aucun libellé d'exigence. Reprises dans la description du contrôle créé.
  references?: string[]
}
export type SectorSuggestion = Omit<CatalogueItem, 'title' | 'unite' | 'points' | 'description'> & { title: string; description?: string; unite?: string; points?: string[]; packVersion: string; taxonomieCode?: string; riskKeys?: string[] }

const l = (fr: string, en: string, de: string, es: string, it: string): Localized => ({ fr, en, de, es, it })
const p = (key: string, sector: CatalogueItem['sector'], title: Localized, parentKey?: string): CatalogueItem => ({ key, sector, kind: 'PROCESS', title, parentKey })
const r = (key: string, sector: CatalogueItem['sector'], title: Localized, processKey: string): CatalogueItem => ({ key, sector, kind: 'RISK', title, processKey })

// Le socle transversal décrit des activités communes, pas une organisation idéale.
const TRANSVERSAL: CatalogueItem[] = [
  p('core.process.govern', 'TRANSVERSAL', l('Piloter les activités et les risques', 'Govern operations and risks', 'Betrieb und Risiken steuern', 'Dirigir actividades y riesgos', 'Governare attività e rischi')),
  p('core.process.finance', 'TRANSVERSAL', l('Gérer les finances et les paiements', 'Manage finance and payments', 'Finanzen und Zahlungen verwalten', 'Gestionar finanzas y pagos', 'Gestire finanze e pagamenti')),
  p('core.process.people', 'TRANSVERSAL', l('Gérer les collaborateurs', 'Manage people', 'Personal verwalten', 'Gestionar el personal', 'Gestire il personale')),
  p('core.process.buy', 'TRANSVERSAL', l('Acheter et piloter les fournisseurs', 'Buy and manage suppliers', 'Beschaffung und Lieferanten steuern', 'Comprar y gestionar proveedores', 'Acquistare e gestire fornitori')),
  p('core.process.digital', 'TRANSVERSAL', l('Exploiter les systèmes et les données', 'Operate systems and data', 'Systeme und Daten betreiben', 'Operar sistemas y datos', 'Gestire sistemi e dati')),
  p('core.process.deliver', 'TRANSVERSAL', l('Fournir les produits ou services', 'Deliver products or services', 'Produkte oder Dienste bereitstellen', 'Prestar productos o servicios', 'Erogare prodotti o servizi')),
  r('core.risk.payment-fraud', 'TRANSVERSAL', l('Un paiement est détourné après usurpation d’identité', 'A payment is diverted through impersonation', 'Eine Zahlung wird durch Identitätsmissbrauch umgeleitet', 'Un pago se desvía mediante suplantación de identidad', 'Un pagamento viene dirottato tramite furto di identità'), 'core.process.finance'),
  r('core.risk.ransomware', 'TRANSVERSAL', l('Un rançongiciel interrompt les activités essentielles', 'Ransomware disrupts essential operations', 'Ransomware unterbricht wesentliche Abläufe', 'Un ransomware interrumpe operaciones esenciales', 'Un ransomware interrompe le attività essenziali'), 'core.process.digital'),
  r('core.risk.supplier-outage', 'TRANSVERSAL', l('Un fournisseur essentiel devient indisponible', 'An essential supplier becomes unavailable', 'Ein wesentlicher Lieferant fällt aus', 'Un proveedor esencial deja de estar disponible', 'Un fornitore essenziale diventa indisponibile'), 'core.process.buy'),
  r('core.risk.data-leak', 'TRANSVERSAL', l('Des données sensibles sont divulguées', 'Sensitive data is disclosed', 'Vertrauliche Daten werden offengelegt', 'Se divulgan datos sensibles', 'Vengono divulgati dati sensibili'), 'core.process.digital'),
  r('core.risk.key-person', 'TRANSVERSAL', l('Une compétence clé devient indisponible sans relève', 'A key skill becomes unavailable without backup', 'Eine Schlüsselkompetenz fällt ohne Vertretung aus', 'Falta una competencia clave sin sustitución', 'Una competenza chiave manca senza sostituzione'), 'core.process.people'),
  r('core.risk.process-error', 'TRANSVERSAL', l('Une erreur de traitement affecte un service livré', 'A processing error affects a delivered service', 'Ein Bearbeitungsfehler beeinträchtigt eine Dienstleistung', 'Un error de proceso afecta a un servicio prestado', 'Un errore di processo compromette un servizio erogato'), 'core.process.deliver'),
  p('core.process.govern.strategy', 'TRANSVERSAL', l('Définir la stratégie et les objectifs', 'Define strategy and objectives', 'Strategie und Ziele festlegen', 'Definir la estrategia y los objetivos', 'Definire strategia e obiettivi'), 'core.process.govern'),
  p('core.process.govern.compliance', 'TRANSVERSAL', l('Suivre les risques et la conformité', 'Monitor risks and compliance', 'Risiken und Compliance überwachen', 'Supervisar riesgos y cumplimiento', 'Monitorare rischi e conformità'), 'core.process.govern'),
  p('core.process.govern.crisis', 'TRANSVERSAL', l('Gérer les incidents majeurs et les crises', 'Handle major incidents and crises', 'Schwere Vorfälle und Krisen bewältigen', 'Gestionar incidentes graves y crisis', 'Gestire incidenti gravi e crisi'), 'core.process.govern'),
  p('core.process.finance.accounting', 'TRANSVERSAL', l('Tenir la comptabilité et le budget', 'Keep accounts and budget', 'Buchhaltung und Budget führen', 'Llevar la contabilidad y el presupuesto', 'Tenere contabilità e budget'), 'core.process.finance'),
  p('core.process.finance.treasury', 'TRANSVERSAL', l('Piloter la trésorerie', 'Manage cash flow', 'Liquidität steuern', 'Gestionar la tesorería', 'Gestire la tesoreria'), 'core.process.finance'),
  p('core.process.finance.payments', 'TRANSVERSAL', l('Émettre et recevoir les paiements', 'Issue and receive payments', 'Zahlungen ausführen und empfangen', 'Emitir y recibir pagos', 'Emettere e ricevere pagamenti'), 'core.process.finance'),
  p('core.process.people.hiring', 'TRANSVERSAL', l('Recruter et accueillir les collaborateurs', 'Recruit and onboard staff', 'Personal gewinnen und einarbeiten', 'Reclutar e incorporar personal', 'Reclutare e inserire il personale'), 'core.process.people'),
  p('core.process.people.payroll', 'TRANSVERSAL', l('Gérer la paie et les absences', 'Run payroll and absences', 'Gehälter und Abwesenheiten verwalten', 'Gestionar nóminas y ausencias', 'Gestire paghe e assenze'), 'core.process.people'),
  p('core.process.people.skills', 'TRANSVERSAL', l('Développer et conserver les compétences', 'Develop and retain skills', 'Kompetenzen entwickeln und halten', 'Desarrollar y conservar competencias', 'Sviluppare e mantenere le competenze'), 'core.process.people'),
  p('core.process.buy.sourcing', 'TRANSVERSAL', l('Sélectionner et contractualiser les fournisseurs', 'Select and contract suppliers', 'Lieferanten auswählen und vertraglich binden', 'Seleccionar y contratar proveedores', 'Selezionare e contrattualizzare i fornitori'), 'core.process.buy'),
  p('core.process.buy.order', 'TRANSVERSAL', l('Commander et réceptionner', 'Order and receive goods', 'Bestellen und Wareneingang', 'Pedir y recibir', 'Ordinare e ricevere'), 'core.process.buy'),
  p('core.process.buy.review', 'TRANSVERSAL', l('Évaluer la performance des fournisseurs', 'Review supplier performance', 'Lieferantenleistung bewerten', 'Evaluar el desempeño de los proveedores', 'Valutare le prestazioni dei fornitori'), 'core.process.buy'),
  p('core.process.digital.iam', 'TRANSVERSAL', l('Gérer les accès et les identités', 'Manage access and identities', 'Zugriffe und Identitäten verwalten', 'Gestionar accesos e identidades', 'Gestire accessi e identità'), 'core.process.digital'),
  p('core.process.digital.backup', 'TRANSVERSAL', l('Sauvegarder et restaurer les données', 'Back up and restore data', 'Daten sichern und wiederherstellen', 'Respaldar y restaurar datos', 'Eseguire backup e ripristino dei dati'), 'core.process.digital'),
  p('core.process.digital.patch', 'TRANSVERSAL', l('Maintenir et mettre à jour les systèmes', 'Maintain and update systems', 'Systeme warten und aktualisieren', 'Mantener y actualizar sistemas', 'Manutenere e aggiornare i sistemi'), 'core.process.digital'),
  p('core.process.digital.monitor', 'TRANSVERSAL', l('Superviser et détecter les événements de sécurité', 'Monitor and detect security events', 'Sicherheitsereignisse überwachen und erkennen', 'Supervisar y detectar eventos de seguridad', 'Monitorare e rilevare eventi di sicurezza'), 'core.process.digital'),
  p('core.process.deliver.orders', 'TRANSVERSAL', l('Recevoir et traiter les demandes des clients', 'Receive and process customer requests', 'Kundenanfragen entgegennehmen und bearbeiten', 'Recibir y tramitar solicitudes de clientes', 'Ricevere ed elaborare le richieste dei clienti'), 'core.process.deliver'),
  p('core.process.deliver.aftersales', 'TRANSVERSAL', l('Assurer le suivi après livraison', 'Provide after-delivery support', 'Nachbetreuung nach der Lieferung sicherstellen', 'Prestar seguimiento posventa', 'Garantire l’assistenza post-consegna'), 'core.process.deliver'),
  r('core.risk.privileged-access', 'TRANSVERSAL', l('Un compte à privilèges est compromis', 'A privileged account is compromised', 'Ein privilegiertes Konto wird kompromittiert', 'Se compromete una cuenta con privilegios', 'Un account con privilegi viene compromesso'), 'core.process.digital.iam'),
  r('core.risk.leavers', 'TRANSVERSAL', l('Un collaborateur parti conserve des accès actifs', 'A departed employee keeps active access', 'Ein ausgeschiedener Mitarbeiter behält aktive Zugänge', 'Un empleado que se marchó conserva accesos activos', 'Un dipendente uscito mantiene accessi attivi'), 'core.process.digital.iam'),
  r('core.risk.backup-failure', 'TRANSVERSAL', l('Une sauvegarde est inutilisable au moment de la restauration', 'A backup cannot be restored when needed', 'Eine Sicherung lässt sich im Bedarfsfall nicht wiederherstellen', 'Una copia de seguridad no se puede restaurar cuando hace falta', 'Un backup non è ripristinabile quando serve'), 'core.process.digital.backup'),
  r('core.risk.unpatched', 'TRANSVERSAL', l('Une vulnérabilité connue n’est pas corrigée à temps', 'A known vulnerability is not fixed in time', 'Eine bekannte Schwachstelle wird nicht rechtzeitig behoben', 'Una vulnerabilidad conocida no se corrige a tiempo', 'Una vulnerabilità nota non viene corretta in tempo'), 'core.process.digital.patch'),
  r('core.risk.supplier-contract', 'TRANSVERSAL', l('Un contrat fournisseur ne couvre pas les exigences de sécurité', 'A supplier contract omits security requirements', 'Ein Lieferantenvertrag enthält keine Sicherheitsanforderungen', 'Un contrato con un proveedor no recoge los requisitos de seguridad', 'Un contratto con un fornitore non prevede i requisiti di sicurezza'), 'core.process.buy.sourcing'),
  r('core.risk.detection-gap', 'TRANSVERSAL', l('Une intrusion reste non détectée pendant des semaines', 'An intrusion goes undetected for weeks', 'Ein Eindringen bleibt wochenlang unentdeckt', 'Una intrusión pasa semanas sin detectarse', 'Un’intrusione resta non rilevata per settimane'), 'core.process.digital.monitor'),
]

const c = (key: string, title: Localized, processKey: string, periodicite: NonNullable<CatalogueItem['periodicite']>, controlType: NonNullable<CatalogueItem['controlType']>): CatalogueItem =>
  ({ key, sector: 'TRANSVERSAL', kind: 'CONTROL', title, processKey, periodicite, controlType })

// Contrôles-types : des pratiques courantes à qualifier par l'organisation (responsable, périmètre, échantillon), jamais des contrôles « réalisés ».
const TRANSVERSAL_CONTROLS: CatalogueItem[] = [
  c('core.control.access-review', l('Revue périodique des droits d’accès', 'Periodic review of access rights', 'Regelmäßige Überprüfung der Zugriffsrechte', 'Revisión periódica de los derechos de acceso', 'Revisione periodica dei diritti di accesso'), 'core.process.digital.iam', 'TRIMESTRIEL', 'DETECTIF'),
  c('core.control.privileged-review', l('Revue des comptes à privilèges', 'Review of privileged accounts', 'Überprüfung privilegierter Konten', 'Revisión de las cuentas con privilegios', 'Revisione degli account con privilegi'), 'core.process.digital.iam', 'TRIMESTRIEL', 'DETECTIF'),
  c('core.control.leavers', l('Vérification du retrait des accès des collaborateurs partis', 'Check that access of departed staff has been removed', 'Prüfung des Entzugs der Zugänge ausgeschiedener Mitarbeiter', 'Verificación de la retirada de accesos del personal saliente', 'Verifica della rimozione degli accessi del personale uscito'), 'core.process.digital.iam', 'MENSUEL', 'DETECTIF'),
  c('core.control.backup-restore', l('Test de restauration des sauvegardes', 'Backup restoration test', 'Test der Wiederherstellung von Sicherungen', 'Prueba de restauración de copias de seguridad', 'Test di ripristino dei backup'), 'core.process.digital.backup', 'SEMESTRIEL', 'DETECTIF'),
  c('core.control.patch-follow-up', l('Suivi des correctifs de sécurité en retard', 'Follow-up of overdue security patches', 'Nachverfolgung überfälliger Sicherheitspatches', 'Seguimiento de parches de seguridad pendientes', 'Monitoraggio delle patch di sicurezza in ritardo'), 'core.process.digital.patch', 'MENSUEL', 'DETECTIF'),
  c('core.control.security-alerts', l('Revue des alertes et journaux de sécurité', 'Review of security alerts and logs', 'Überprüfung von Sicherheitswarnungen und Protokollen', 'Revisión de alertas y registros de seguridad', 'Revisione di avvisi e log di sicurezza'), 'core.process.digital.monitor', 'MENSUEL', 'DETECTIF'),
  c('core.control.payment-validation', l('Contrôle par échantillon de la double validation des paiements', 'Sample check of dual approval of payments', 'Stichprobenprüfung der doppelten Zahlungsfreigabe', 'Control por muestreo de la doble validación de los pagos', 'Controllo a campione della doppia autorizzazione dei pagamenti'), 'core.process.finance.payments', 'MENSUEL', 'DETECTIF'),
  c('core.control.supplier-clauses', l('Vérification des clauses de sécurité des contrats fournisseurs', 'Check of security clauses in supplier contracts', 'Prüfung der Sicherheitsklauseln in Lieferantenverträgen', 'Verificación de las cláusulas de seguridad de los contratos con proveedores', 'Verifica delle clausole di sicurezza nei contratti con i fornitori'), 'core.process.buy.sourcing', 'ANNUEL', 'PREVENTIF'),
  c('core.control.supplier-review', l('Revue de performance des fournisseurs essentiels', 'Performance review of essential suppliers', 'Leistungsbewertung wesentlicher Lieferanten', 'Revisión del desempeño de los proveedores esenciales', 'Revisione delle prestazioni dei fornitori essenziali'), 'core.process.buy.review', 'ANNUEL', 'DETECTIF'),
]

const k = (key: string, title: Localized, processKey: string, unite: Localized, sens: 'HAUSSE' | 'BAISSE', periodicite: NonNullable<CatalogueItem['periodicite']>): CatalogueItem =>
  ({ key, sector: 'TRANSVERSAL', kind: 'KRI', title, processKey, unite, sens, periodicite })
const pct = l('%', '%', '%', '%', '%')
const nb = l('nombre', 'count', 'Anzahl', 'número', 'numero')
const jours = l('jours', 'days', 'Tage', 'días', 'giorni')

// Indicateurs candidats : seuils À DÉFINIR par l'organisation (appétence), aucune valeur mesurée, aucun voyant par défaut.
const TRANSVERSAL_KRIS: CatalogueItem[] = [
  k('core.kri.overdue-patches', l('Vulnérabilités critiques non corrigées dans les délais', 'Critical vulnerabilities not fixed on time', 'Kritische Schwachstellen nicht fristgerecht behoben', 'Vulnerabilidades críticas no corregidas a tiempo', 'Vulnerabilità critiche non corrette in tempo'), 'core.process.digital.patch', nb, 'HAUSSE', 'MENSUEL'),
  k('core.kri.leaver-accounts', l('Comptes actifs de collaborateurs partis', 'Active accounts of departed staff', 'Aktive Konten ausgeschiedener Mitarbeiter', 'Cuentas activas de personal saliente', 'Account attivi di personale uscito'), 'core.process.digital.iam', nb, 'HAUSSE', 'MENSUEL'),
  k('core.kri.privileged-accounts', l('Comptes à privilèges non revus depuis plus d’un trimestre', 'Privileged accounts not reviewed for over a quarter', 'Seit über einem Quartal nicht überprüfte privilegierte Konten', 'Cuentas con privilegios sin revisar desde hace más de un trimestre', 'Account con privilegi non rivisti da oltre un trimestre'), 'core.process.digital.iam', nb, 'HAUSSE', 'TRIMESTRIEL'),
  k('core.kri.backup-success', l('Taux de sauvegardes réussies', 'Backup success rate', 'Erfolgsquote der Sicherungen', 'Tasa de copias de seguridad correctas', 'Tasso di backup riusciti'), 'core.process.digital.backup', pct, 'BAISSE', 'MENSUEL'),
  k('core.kri.restore-age', l('Ancienneté du dernier test de restauration', 'Age of the last restoration test', 'Alter des letzten Wiederherstellungstests', 'Antigüedad de la última prueba de restauración', 'Anzianità dell’ultimo test di ripristino'), 'core.process.digital.backup', jours, 'HAUSSE', 'MENSUEL'),
  k('core.kri.security-incidents', l('Incidents de sécurité déclarés', 'Reported security incidents', 'Gemeldete Sicherheitsvorfälle', 'Incidentes de seguridad notificados', 'Incidenti di sicurezza segnalati'), 'core.process.govern.crisis', nb, 'HAUSSE', 'MENSUEL'),
  k('core.kri.phishing-click', l('Taux de clic aux simulations d’hameçonnage', 'Click rate in phishing simulations', 'Klickrate bei Phishing-Simulationen', 'Tasa de clics en simulaciones de phishing', 'Tasso di clic nelle simulazioni di phishing'), 'core.process.people.skills', pct, 'HAUSSE', 'TRIMESTRIEL'),
  k('core.kri.supplier-without-clauses', l('Fournisseurs essentiels sans clauses de sécurité', 'Essential suppliers without security clauses', 'Wesentliche Lieferanten ohne Sicherheitsklauseln', 'Proveedores esenciales sin cláusulas de seguridad', 'Fornitori essenziali senza clausole di sicurezza'), 'core.process.buy.sourcing', nb, 'HAUSSE', 'SEMESTRIEL'),
  k('core.kri.payment-exceptions', l('Paiements sensibles sans double validation', 'Sensitive payments without dual approval', 'Sensible Zahlungen ohne doppelte Freigabe', 'Pagos sensibles sin doble validación', 'Pagamenti sensibili senza doppia autorizzazione'), 'core.process.finance.payments', nb, 'HAUSSE', 'MENSUEL'),
]

const a = (key: string, title: Localized, processKey: string, points: Localized[]): CatalogueItem =>
  ({ key, sector: 'TRANSVERSAL', kind: 'AUDIT', title, processKey, points })

// Missions types : un programme de revue à adapter ; jamais une mission « réalisée » (ni date, ni notation, ni constat).
const TRANSVERSAL_AUDITS: CatalogueItem[] = [
  a('core.audit.access', l('Audit de la gestion des accès', 'Audit of access management', 'Audit der Zugriffsverwaltung', 'Auditoría de la gestión de accesos', 'Audit della gestione degli accessi'), 'core.process.digital.iam', [
    l('Les droits d’accès sont attribués sur demande validée', 'Access rights are granted on an approved request', 'Zugriffsrechte werden auf Basis genehmigter Anträge vergeben', 'Los derechos de acceso se conceden con una solicitud validada', 'I diritti di accesso sono assegnati su richiesta approvata'),
    l('Les revues périodiques des droits sont réalisées et tracées', 'Periodic access reviews are carried out and traced', 'Regelmäßige Berechtigungsprüfungen werden durchgeführt und nachvollziehbar dokumentiert', 'Las revisiones periódicas de derechos se realizan y se registran', 'Le revisioni periodiche dei diritti sono eseguite e tracciate'),
    l('Les accès des collaborateurs partis sont retirés dans les délais', 'Access of departed staff is removed on time', 'Zugänge ausgeschiedener Mitarbeiter werden fristgerecht entzogen', 'Los accesos del personal saliente se retiran a tiempo', 'Gli accessi del personale uscito sono rimossi nei tempi previsti'),
    l('Les comptes à privilèges sont limités et supervisés', 'Privileged accounts are limited and supervised', 'Privilegierte Konten sind begrenzt und werden überwacht', 'Las cuentas con privilegios están limitadas y supervisadas', 'Gli account con privilegi sono limitati e supervisionati'),
  ]),
  a('core.audit.backup', l('Audit des sauvegardes et de la restauration', 'Audit of backup and restoration', 'Audit von Datensicherung und Wiederherstellung', 'Auditoría de copias de seguridad y restauración', 'Audit di backup e ripristino'), 'core.process.digital.backup', [
    l('Le périmètre sauvegardé couvre les données essentielles', 'The backed-up scope covers essential data', 'Der gesicherte Umfang deckt die wesentlichen Daten ab', 'El perímetro respaldado cubre los datos esenciales', 'Il perimetro sottoposto a backup copre i dati essenziali'),
    l('Des tests de restauration sont réalisés et leurs résultats conservés', 'Restoration tests are performed and results kept', 'Wiederherstellungstests werden durchgeführt und die Ergebnisse aufbewahrt', 'Se realizan pruebas de restauración y se conservan los resultados', 'Sono eseguiti test di ripristino e ne sono conservati gli esiti'),
    l('Une copie est protégée contre la suppression ou le chiffrement malveillant', 'A copy is protected against malicious deletion or encryption', 'Eine Kopie ist gegen böswilliges Löschen oder Verschlüsseln geschützt', 'Una copia está protegida contra el borrado o cifrado malicioso', 'Una copia è protetta da cancellazione o cifratura dolosa'),
    l('Les échecs de sauvegarde sont détectés et traités', 'Backup failures are detected and handled', 'Sicherungsfehler werden erkannt und behandelt', 'Los fallos de copia se detectan y se tratan', 'I fallimenti dei backup sono rilevati e gestiti'),
  ]),
  a('core.audit.suppliers', l('Audit de la maîtrise des fournisseurs', 'Audit of supplier management', 'Audit der Lieferantensteuerung', 'Auditoría de la gestión de proveedores', 'Audit della gestione dei fornitori'), 'core.process.buy.sourcing', [
    l('Les fournisseurs essentiels sont identifiés et évalués avant contractualisation', 'Essential suppliers are identified and assessed before contracting', 'Wesentliche Lieferanten werden vor Vertragsabschluss identifiziert und bewertet', 'Los proveedores esenciales se identifican y evalúan antes de contratar', 'I fornitori essenziali sono identificati e valutati prima della contrattualizzazione'),
    l('Les contrats comportent des exigences de sécurité et de notification d’incident', 'Contracts include security and incident-notification requirements', 'Verträge enthalten Sicherheits- und Meldeanforderungen bei Vorfällen', 'Los contratos incluyen requisitos de seguridad y notificación de incidentes', 'I contratti includono requisiti di sicurezza e notifica degli incidenti'),
    l('Le suivi de la performance et des incidents fournisseurs est réalisé', 'Supplier performance and incidents are monitored', 'Leistung und Vorfälle der Lieferanten werden überwacht', 'Se supervisan el desempeño y los incidentes de los proveedores', 'Sono monitorati prestazioni e incidenti dei fornitori'),
    l('Une stratégie de sortie ou de remplacement est définie pour les services essentiels', 'An exit or replacement strategy exists for essential services', 'Für wesentliche Dienste existiert eine Exit- oder Ersatzstrategie', 'Existe una estrategia de salida o sustitución para los servicios esenciales', 'Esiste una strategia di uscita o sostituzione per i servizi essenziali'),
  ]),
  a('core.audit.payments', l('Audit des paiements sensibles', 'Audit of sensitive payments', 'Audit sensibler Zahlungen', 'Auditoría de pagos sensibles', 'Audit dei pagamenti sensibili'), 'core.process.finance.payments', [
    l('Les paiements sensibles nécessitent une double validation', 'Sensitive payments require dual approval', 'Sensible Zahlungen erfordern eine doppelte Freigabe', 'Los pagos sensibles requieren doble validación', 'I pagamenti sensibili richiedono una doppia autorizzazione'),
    l('Les changements de coordonnées bancaires sont vérifiés par un canal indépendant', 'Bank-detail changes are verified through an independent channel', 'Änderungen von Bankdaten werden über einen unabhängigen Kanal geprüft', 'Los cambios de datos bancarios se verifican por un canal independiente', 'Le modifiche delle coordinate bancarie sono verificate tramite un canale indipendente'),
    l('Les délégations et plafonds de paiement sont à jour', 'Payment delegations and limits are up to date', 'Zahlungsvollmachten und Limits sind aktuell', 'Las delegaciones y límites de pago están actualizados', 'Le deleghe e i massimali di pagamento sono aggiornati'),
    l('Les anomalies de paiement sont analysées et escaladées', 'Payment anomalies are analysed and escalated', 'Zahlungsanomalien werden analysiert und eskaliert', 'Las anomalías de pago se analizan y se escalan', 'Le anomalie di pagamento sono analizzate e segnalate'),
  ]),
]

const SECTOR_ITEMS: CatalogueItem[] = [
  // Finance : paiement, comptes, financement et relation client plutôt que conformité présumée.
  p('finance.process.payments', 'FINANCE', l('Exécuter les paiements', 'Execute payments', 'Zahlungen ausführen', 'Ejecutar pagos', 'Eseguire pagamenti'), 'core.process.deliver'),
  p('finance.process.accounts', 'FINANCE', l('Tenir les comptes clients', 'Maintain customer accounts', 'Kundenkonten führen', 'Mantener cuentas de clientes', 'Gestire i conti dei clienti'), 'core.process.deliver'),
  p('finance.process.credit', 'FINANCE', l('Octroyer et suivre les financements', 'Originate and monitor credit', 'Kredite vergeben und überwachen', 'Conceder y supervisar créditos', 'Erogare e monitorare finanziamenti'), 'core.process.deliver'),
  p('finance.process.channels', 'FINANCE', l('Exploiter les canaux bancaires numériques', 'Operate digital banking channels', 'Digitale Bankkanäle betreiben', 'Operar canales bancarios digitales', 'Gestire i canali bancari digitali'), 'core.process.digital'),
  r('finance.risk.payment-routing', 'FINANCE', l('Un paiement est envoyé au mauvais bénéficiaire', 'A payment reaches the wrong beneficiary', 'Eine Zahlung erreicht den falschen Empfänger', 'Un pago llega al beneficiario equivocado', 'Un pagamento raggiunge il beneficiario errato'), 'finance.process.payments'),
  r('finance.risk.account-takeover', 'FINANCE', l('Un compte client est usurpé par un fraudeur', 'A customer account is taken over fraudulently', 'Ein Kundenkonto wird betrügerisch übernommen', 'Se toma el control fraudulento de una cuenta de cliente', 'Un conto cliente viene acquisito fraudolentemente'), 'finance.process.accounts'),
  r('finance.risk.credit-data', 'FINANCE', l('Une décision de financement repose sur des données erronées', 'A credit decision relies on incorrect data', 'Eine Kreditentscheidung beruht auf falschen Daten', 'Una decisión de crédito se basa en datos erróneos', 'Una decisione di credito si basa su dati errati'), 'finance.process.credit'),
  r('finance.risk.channel-outage', 'FINANCE', l('La banque en ligne devient indisponible', 'Digital banking becomes unavailable', 'Online-Banking ist nicht verfügbar', 'La banca en línea deja de estar disponible', 'La banca online non è disponibile'), 'finance.process.channels'),
  r('finance.risk.reconciliation', 'FINANCE', l('Des opérations ne sont pas rapprochées à temps', 'Transactions are not reconciled in time', 'Transaktionen werden nicht rechtzeitig abgeglichen', 'Las operaciones no se concilian a tiempo', 'Le operazioni non vengono riconciliate in tempo'), 'finance.process.payments'),

  p('assurance.process.underwrite', 'ASSURANCE', l('Souscrire et tarifer les contrats', 'Underwrite and price policies', 'Verträge zeichnen und tarifieren', 'Suscribir y tarificar pólizas', 'Sottoscrivere e prezzare polizze'), 'core.process.deliver'),
  p('assurance.process.claims', 'ASSURANCE', l('Gérer les sinistres et indemnisations', 'Handle claims and settlements', 'Schäden und Entschädigungen bearbeiten', 'Gestionar siniestros e indemnizaciones', 'Gestire sinistri e indennizzi'), 'core.process.deliver'),
  p('assurance.process.brokers', 'ASSURANCE', l('Animer les courtiers et distributeurs', 'Manage brokers and distributors', 'Makler und Vertriebspartner betreuen', 'Gestionar corredores y distribuidores', 'Gestire broker e distributori'), 'core.process.deliver'),
  p('assurance.process.policy', 'ASSURANCE', l('Administrer les contrats en cours', 'Administer active policies', 'Laufende Verträge verwalten', 'Administrar pólizas vigentes', 'Amministrare polizze attive'), 'core.process.deliver'),
  r('assurance.risk.claim-fraud', 'ASSURANCE', l('Un sinistre frauduleux est indemnisé', 'A fraudulent claim is paid', 'Ein betrügerischer Schaden wird ausgezahlt', 'Se paga un siniestro fraudulento', 'Un sinistro fraudolento viene liquidato'), 'assurance.process.claims'),
  r('assurance.risk.claim-delay', 'ASSURANCE', l('Un sinistre légitime est traité trop tard', 'A valid claim is handled too late', 'Ein berechtigter Schaden wird zu spät bearbeitet', 'Un siniestro legítimo se tramita demasiado tarde', 'Un sinistro legittimo viene gestito troppo tardi'), 'assurance.process.claims'),
  r('assurance.risk.pricing', 'ASSURANCE', l('Une erreur de tarification déséquilibre un portefeuille', 'A pricing error harms a portfolio', 'Ein Tarifierungsfehler belastet ein Portfolio', 'Un error de tarificación perjudica la cartera', 'Un errore di prezzo danneggia il portafoglio'), 'assurance.process.underwrite'),
  r('assurance.risk.broker-data', 'ASSURANCE', l('Un distributeur transmet des données client inexactes', 'A distributor supplies inaccurate customer data', 'Ein Vertriebspartner liefert fehlerhafte Kundendaten', 'Un distribuidor envía datos inexactos de clientes', 'Un distributore invia dati cliente inesatti'), 'assurance.process.brokers'),
  r('assurance.risk.policy-change', 'ASSURANCE', l('Une modification de contrat n’est pas appliquée', 'A policy change is not applied', 'Eine Vertragsänderung wird nicht umgesetzt', 'No se aplica un cambio de póliza', 'Una modifica di polizza non viene applicata'), 'assurance.process.policy'),

  p('sante.process.care', 'SANTE', l('Prendre en charge les patients', 'Provide patient care', 'Patienten versorgen', 'Atender a los pacientes', 'Assistere i pazienti'), 'core.process.deliver'),
  p('sante.process.records', 'SANTE', l('Gérer les dossiers de santé', 'Manage health records', 'Gesundheitsakten verwalten', 'Gestionar historias clínicas', 'Gestire le cartelle cliniche'), 'core.process.digital'),
  p('sante.process.lab', 'SANTE', l('Réaliser les examens et rendre les résultats', 'Perform tests and report results', 'Untersuchungen durchführen und Ergebnisse melden', 'Realizar pruebas y comunicar resultados', 'Eseguire esami e comunicare risultati'), 'core.process.deliver'),
  p('sante.process.supply', 'SANTE', l('Approvisionner médicaments et dispositifs', 'Supply medicines and devices', 'Arzneimittel und Geräte bereitstellen', 'Suministrar medicamentos y dispositivos', 'Fornire farmaci e dispositivi'), 'core.process.buy'),
  r('sante.risk.patient-data', 'SANTE', l('Des données de santé de patients sont divulguées', 'Patient health data is disclosed', 'Gesundheitsdaten von Patienten werden offengelegt', 'Se divulgan datos de salud de pacientes', 'Vengono divulgati dati sanitari dei pazienti'), 'sante.process.records'),
  r('sante.risk.care-outage', 'SANTE', l('Une panne retarde la prise en charge', 'An outage delays patient care', 'Ein Ausfall verzögert die Versorgung', 'Una avería retrasa la atención', 'Un guasto ritarda l’assistenza'), 'sante.process.care'),
  r('sante.risk.result-error', 'SANTE', l('Un résultat d’examen est attribué au mauvais patient', 'A test result is assigned to the wrong patient', 'Ein Befund wird dem falschen Patienten zugeordnet', 'Un resultado se asigna al paciente equivocado', 'Un referto viene attribuito al paziente sbagliato'), 'sante.process.lab'),
  r('sante.risk.stockout', 'SANTE', l('Une rupture de stock perturbe les soins', 'A stockout disrupts care', 'Ein Lieferengpass beeinträchtigt die Versorgung', 'Una falta de existencias interrumpe la atención', 'Una carenza di scorte interrompe le cure'), 'sante.process.supply'),
  r('sante.risk.record-integrity', 'SANTE', l('Un dossier de santé est altéré ou incomplet', 'A health record is altered or incomplete', 'Eine Gesundheitsakte ist verändert oder unvollständig', 'Una historia clínica está alterada o incompleta', 'Una cartella clinica è alterata o incompleta'), 'sante.process.records'),

  p('public.process.citizens', 'PUBLIC', l('Rendre les services aux usagers', 'Deliver citizen services', 'Dienstleistungen für Bürger erbringen', 'Prestar servicios a la ciudadanía', 'Erogare servizi ai cittadini'), 'core.process.deliver'),
  p('public.process.grants', 'PUBLIC', l('Instruire les aides et subventions', 'Process grants and subsidies', 'Förderungen und Zuschüsse bearbeiten', 'Tramitar ayudas y subvenciones', 'Gestire aiuti e sovvenzioni'), 'core.process.finance'),
  p('public.process.identity', 'PUBLIC', l('Gérer les identités et accès des usagers', 'Manage citizen identities and access', 'Identitäten und Zugänge der Bürger verwalten', 'Gestionar identidades y accesos de usuarios', 'Gestire identità e accessi dei cittadini'), 'core.process.digital'),
  p('public.process.local', 'PUBLIC', l('Assurer la continuité des services territoriaux', 'Maintain local public services', 'Lokale öffentliche Dienste aufrechterhalten', 'Mantener servicios públicos locales', 'Mantenere i servizi pubblici locali'), 'core.process.deliver'),
  r('public.risk.portal-outage', 'PUBLIC', l('Un portail public devient indisponible', 'A public portal becomes unavailable', 'Ein Bürgerportal fällt aus', 'Un portal público deja de estar disponible', 'Un portale pubblico non è disponibile'), 'public.process.citizens'),
  r('public.risk.identity', 'PUBLIC', l('Une identité usager est usurpée', 'A citizen identity is impersonated', 'Eine Bürgeridentität wird missbraucht', 'Se suplanta la identidad de un usuario', 'L’identità di un cittadino viene usurpata'), 'public.process.identity'),
  r('public.risk.grant-error', 'PUBLIC', l('Une aide est versée à tort ou refusée à tort', 'A grant is paid or denied incorrectly', 'Eine Förderung wird falsch ausgezahlt oder verweigert', 'Una ayuda se paga o deniega erróneamente', 'Un contributo viene erogato o negato erroneamente'), 'public.process.grants'),
  r('public.risk.local-outage', 'PUBLIC', l('Une interruption prive les usagers d’un service local', 'An outage deprives citizens of a local service', 'Ein Ausfall entzieht Bürgern einen lokalen Dienst', 'Una interrupción priva a la ciudadanía de un servicio local', 'Un’interruzione priva i cittadini di un servizio locale'), 'public.process.local'),
  r('public.risk.case-leak', 'PUBLIC', l('Des dossiers administratifs sont divulgués', 'Administrative files are disclosed', 'Verwaltungsakten werden offengelegt', 'Se divulgan expedientes administrativos', 'Vengono divulgati fascicoli amministrativi'), 'public.process.citizens'),

  p('saas.process.build', 'SAAS', l('Développer et livrer le logiciel', 'Build and deliver software', 'Software entwickeln und ausliefern', 'Desarrollar y entregar software', 'Sviluppare e distribuire software'), 'core.process.deliver'),
  p('saas.process.host', 'SAAS', l('Héberger et exploiter la plateforme', 'Host and operate the platform', 'Plattform hosten und betreiben', 'Alojar y operar la plataforma', 'Ospitare e gestire la piattaforma'), 'core.process.digital'),
  p('saas.process.support', 'SAAS', l('Assister les clients et résoudre les incidents', 'Support customers and resolve incidents', 'Kunden unterstützen und Störungen beheben', 'Atender a clientes y resolver incidencias', 'Assistere i clienti e risolvere incidenti'), 'core.process.deliver'),
  p('saas.process.onboard', 'SAAS', l('Configurer et intégrer les nouveaux clients', 'Configure and onboard new customers', 'Neue Kunden einrichten und integrieren', 'Configurar e incorporar nuevos clientes', 'Configurare e integrare nuovi clienti'), 'core.process.deliver'),
  r('saas.risk.release', 'SAAS', l('Une mise en production interrompt des clients', 'A release disrupts customers', 'Ein Release unterbricht Kundendienste', 'Una versión interrumpe servicios a clientes', 'Un rilascio interrompe i servizi ai clienti'), 'saas.process.build'),
  r('saas.risk.tenant-isolation', 'SAAS', l('Les données d’un client deviennent visibles à un autre', 'One customer sees another customer’s data', 'Ein Kunde sieht Daten eines anderen Kunden', 'Un cliente ve datos de otro cliente', 'Un cliente vede i dati di un altro cliente'), 'saas.process.host'),
  r('saas.risk.cloud-outage', 'SAAS', l('Une dépendance cloud rend la plateforme indisponible', 'A cloud dependency makes the platform unavailable', 'Eine Cloud-Abhängigkeit legt die Plattform lahm', 'Una dependencia de nube deja inactiva la plataforma', 'Una dipendenza cloud rende indisponibile la piattaforma'), 'saas.process.host'),
  r('saas.risk.support-access', 'SAAS', l('Un accès de support expose des données client', 'Support access exposes customer data', 'Support-Zugriff legt Kundendaten offen', 'El acceso de soporte expone datos de clientes', 'L’accesso di supporto espone dati cliente'), 'saas.process.support'),
  r('saas.risk.integration', 'SAAS', l('Une intégration client échoue sans détection', 'A customer integration fails undetected', 'Eine Kundenintegration scheitert unbemerkt', 'Una integración de cliente falla sin detectarse', 'Un’integrazione cliente fallisce senza essere rilevata'), 'saas.process.onboard'),

  p('industrie.process.produce', 'INDUSTRIE', l('Produire et assembler', 'Manufacture and assemble', 'Produzieren und montieren', 'Producir y ensamblar', 'Produrre e assemblare'), 'core.process.deliver'),
  p('industrie.process.maintain', 'INDUSTRIE', l('Maintenir les équipements industriels', 'Maintain industrial equipment', 'Industrieanlagen instand halten', 'Mantener equipos industriales', 'Manutenere impianti industriali'), 'core.process.deliver'),
  p('industrie.process.quality', 'INDUSTRIE', l('Contrôler la qualité des produits', 'Control product quality', 'Produktqualität prüfen', 'Controlar la calidad del producto', 'Controllare la qualità dei prodotti'), 'core.process.deliver'),
  p('industrie.process.supply', 'INDUSTRIE', l('Planifier les approvisionnements', 'Plan supplies', 'Beschaffung planen', 'Planificar suministros', 'Pianificare gli approvvigionamenti'), 'core.process.buy'),
  r('industrie.risk.ot-stop', 'INDUSTRIE', l('Une panne ou intrusion arrête la production', 'An outage or intrusion stops production', 'Ein Ausfall oder Angriff stoppt die Produktion', 'Una avería o intrusión detiene la producción', 'Un guasto o attacco ferma la produzione'), 'industrie.process.produce'),
  r('industrie.risk.quality', 'INDUSTRIE', l('Un lot défectueux échappe au contrôle qualité', 'A defective batch passes quality checks', 'Eine fehlerhafte Charge besteht die Qualitätskontrolle', 'Un lote defectuoso supera el control de calidad', 'Un lotto difettoso supera il controllo qualità'), 'industrie.process.quality'),
  r('industrie.risk.spares', 'INDUSTRIE', l('Une pièce de rechange critique manque', 'A critical spare part is unavailable', 'Ein kritisches Ersatzteil fehlt', 'Falta una pieza de repuesto crítica', 'Manca un ricambio critico'), 'industrie.process.maintain'),
  r('industrie.risk.supplier', 'INDUSTRIE', l('Une rupture fournisseur bloque une ligne de production', 'A supplier disruption blocks a production line', 'Ein Lieferausfall blockiert eine Produktionslinie', 'Una interrupción del proveedor bloquea una línea', 'Un’interruzione del fornitore blocca una linea'), 'industrie.process.supply'),
  r('industrie.risk.traceability', 'INDUSTRIE', l('La traçabilité d’un lot devient incomplète', 'A batch loses traceability', 'Die Rückverfolgbarkeit einer Charge geht verloren', 'Se pierde la trazabilidad de un lote', 'Si perde la tracciabilità di un lotto'), 'industrie.process.quality'),

  p('commerce.process.sell', 'COMMERCE', l('Vendre et encaisser', 'Sell and collect payments', 'Verkaufen und Zahlungen einziehen', 'Vender y cobrar', 'Vendere e incassare'), 'core.process.deliver'),
  p('commerce.process.stock', 'COMMERCE', l('Gérer les stocks et réassorts', 'Manage inventory and replenishment', 'Bestände und Nachschub verwalten', 'Gestionar inventario y reposición', 'Gestire scorte e riordini'), 'core.process.buy'),
  p('commerce.process.ship', 'COMMERCE', l('Préparer et livrer les commandes', 'Prepare and deliver orders', 'Bestellungen vorbereiten und liefern', 'Preparar y entregar pedidos', 'Preparare e consegnare ordini'), 'core.process.deliver'),
  p('commerce.process.returns', 'COMMERCE', l('Traiter les retours et réclamations', 'Handle returns and complaints', 'Retouren und Beschwerden bearbeiten', 'Gestionar devoluciones y reclamaciones', 'Gestire resi e reclami'), 'core.process.deliver'),
  r('commerce.risk.checkout', 'COMMERCE', l('Une panne d’encaissement bloque les ventes', 'A checkout outage blocks sales', 'Ein Kassenausfall blockiert Verkäufe', 'Una avería de caja bloquea las ventas', 'Un guasto alle casse blocca le vendite'), 'commerce.process.sell'),
  r('commerce.risk.stock', 'COMMERCE', l('Un stock erroné provoque des ventes impossibles', 'Incorrect inventory causes unfulfillable sales', 'Falsche Bestände führen zu unerfüllbaren Verkäufen', 'Un inventario erróneo causa ventas imposibles', 'Scorte errate causano vendite non evadibili'), 'commerce.process.stock'),
  r('commerce.risk.delivery', 'COMMERCE', l('Des commandes sont livrées au mauvais destinataire', 'Orders are delivered to the wrong recipient', 'Bestellungen gehen an den falschen Empfänger', 'Se entregan pedidos al destinatario equivocado', 'Gli ordini sono consegnati al destinatario errato'), 'commerce.process.ship'),
  r('commerce.risk.customer-data', 'COMMERCE', l('Des données clients ou de paiement sont divulguées', 'Customer or payment data is disclosed', 'Kunden- oder Zahlungsdaten werden offengelegt', 'Se divulgan datos de clientes o pagos', 'Vengono divulgati dati clienti o di pagamento'), 'commerce.process.sell'),
  r('commerce.risk.returns', 'COMMERCE', l('Un retour client n’est pas traité correctement', 'A customer return is mishandled', 'Eine Kundenretoure wird falsch bearbeitet', 'Se gestiona mal una devolución', 'Un reso cliente viene gestito male'), 'commerce.process.returns'),

  p('services.process.contract', 'SERVICES', l('Contractualiser les missions clients', 'Contract customer engagements', 'Kundenaufträge vertraglich vereinbaren', 'Contratar encargos de clientes', 'Contrattualizzare incarichi cliente'), 'core.process.deliver'),
  p('services.process.perform', 'SERVICES', l('Réaliser les prestations', 'Perform customer services', 'Kundenleistungen erbringen', 'Prestar servicios al cliente', 'Erogare prestazioni ai clienti'), 'core.process.deliver'),
  p('services.process.bill', 'SERVICES', l('Facturer et suivre les encaissements', 'Bill and collect fees', 'Leistungen abrechnen und Zahlungen verfolgen', 'Facturar y cobrar honorarios', 'Fatturare e incassare compensi'), 'core.process.finance'),
  p('services.process.knowledge', 'SERVICES', l('Gérer les dossiers et connaissances', 'Manage cases and knowledge', 'Akten und Wissen verwalten', 'Gestionar expedientes y conocimiento', 'Gestire pratiche e conoscenza'), 'core.process.digital'),
  r('services.risk.deadline', 'SERVICES', l('Une échéance client importante est manquée', 'An important customer deadline is missed', 'Eine wichtige Kundenfrist wird versäumt', 'Se incumple un plazo importante del cliente', 'Si perde una scadenza importante del cliente'), 'services.process.perform'),
  r('services.risk.confidentiality', 'SERVICES', l('Un dossier client confidentiel est divulgué', 'A confidential customer file is disclosed', 'Eine vertrauliche Kundenakte wird offengelegt', 'Se divulga un expediente confidencial', 'Un fascicolo cliente riservato viene divulgato'), 'services.process.knowledge'),
  r('services.risk.scope', 'SERVICES', l('Une mission est réalisée hors du périmètre convenu', 'Work is delivered outside the agreed scope', 'Eine Leistung überschreitet den vereinbarten Umfang', 'Se presta un servicio fuera del alcance acordado', 'Una prestazione esce dal perimetro concordato'), 'services.process.contract'),
  r('services.risk.billing', 'SERVICES', l('Une prestation n’est pas facturée ou l’est deux fois', 'A service is not billed or is billed twice', 'Eine Leistung wird nicht oder doppelt abgerechnet', 'Un servicio no se factura o se factura dos veces', 'Una prestazione non viene fatturata o lo è due volte'), 'services.process.bill'),
  r('services.risk.expertise', 'SERVICES', l('Une expertise nécessaire manque pendant la mission', 'Needed expertise is unavailable during a project', 'Erforderliches Fachwissen fehlt während eines Auftrags', 'Falta experiencia necesaria durante un encargo', 'Manca una competenza necessaria durante l’incarico'), 'services.process.perform'),
  r('finance.risk.sanction-screening', 'FINANCE', l('Une contrepartie sous sanctions n’est pas détectée', 'A sanctioned counterparty is not detected', 'Eine sanktionierte Gegenpartei wird nicht erkannt', 'No se detecta una contraparte sancionada', 'Una controparte sanzionata non viene rilevata'), 'finance.process.payments'),
  r('finance.risk.card-data', 'FINANCE', l('Des données de cartes de paiement sont compromises', 'Payment card data is compromised', 'Zahlungskartendaten werden kompromittiert', 'Se comprometen datos de tarjetas de pago', 'I dati delle carte di pagamento vengono compromessi'), 'finance.process.channels'),
  r('assurance.risk.reserve', 'ASSURANCE', l('Les provisions techniques sont mal estimées', 'Technical reserves are misestimated', 'Versicherungstechnische Rückstellungen werden falsch geschätzt', 'Las provisiones técnicas se estiman mal', 'Le riserve tecniche sono stimate in modo errato'), 'assurance.process.policy'),
  r('assurance.risk.customer-data', 'ASSURANCE', l('Des données de santé ou financières d’assurés sont divulguées', 'Policyholder health or financial data is disclosed', 'Gesundheits- oder Finanzdaten von Versicherten werden offengelegt', 'Se divulgan datos de salud o financieros de asegurados', 'Vengono divulgati dati sanitari o finanziari degli assicurati'), 'assurance.process.underwrite'),
  r('sante.risk.device', 'SANTE', l('Un dispositif médical connecté est défaillant ou compromis', 'A connected medical device fails or is compromised', 'Ein vernetztes Medizinprodukt fällt aus oder wird kompromittiert', 'Un dispositivo médico conectado falla o se ve comprometido', 'Un dispositivo medico connesso si guasta o viene compromesso'), 'sante.process.care'),
  r('sante.risk.consent', 'SANTE', l('Un consentement ou une opposition du patient n’est pas respecté', 'A patient’s consent or objection is not honoured', 'Einwilligung oder Widerspruch eines Patienten wird nicht beachtet', 'No se respeta el consentimiento o la oposición de un paciente', 'Il consenso o l’opposizione di un paziente non viene rispettato'), 'sante.process.records'),
  r('public.risk.stale-data', 'PUBLIC', l('Une décision administrative est prise sur des données obsolètes', 'An administrative decision relies on outdated data', 'Eine Verwaltungsentscheidung beruht auf veralteten Daten', 'Una decisión administrativa se basa en datos obsoletos', 'Una decisione amministrativa si basa su dati obsoleti'), 'public.process.grants'),
  r('public.risk.open-data', 'PUBLIC', l('Une publication de données ouvertes expose des informations personnelles', 'An open-data release exposes personal information', 'Eine Veröffentlichung offener Daten legt personenbezogene Informationen offen', 'Una publicación de datos abiertos expone información personal', 'Una pubblicazione di dati aperti espone informazioni personali'), 'public.process.citizens'),
  r('saas.risk.secrets', 'SAAS', l('Des secrets ou clés d’API sont publiés par erreur', 'Secrets or API keys are published by mistake', 'Geheimnisse oder API-Schlüssel werden versehentlich veröffentlicht', 'Se publican por error secretos o claves de API', 'Segreti o chiavi API vengono pubblicati per errore'), 'saas.process.build'),
  r('saas.risk.tenant-restore', 'SAAS', l('Les données d’un client ne peuvent pas être restaurées isolément', 'One customer’s data cannot be restored on its own', 'Die Daten eines Kunden lassen sich nicht einzeln wiederherstellen', 'Los datos de un cliente no se pueden restaurar por separado', 'I dati di un cliente non possono essere ripristinati separatamente'), 'saas.process.host'),
  r('industrie.risk.safety', 'INDUSTRIE', l('Une défaillance de contrôle met en danger la sécurité des personnes', 'A control failure endangers people’s safety', 'Ein Steuerungsfehler gefährdet die Sicherheit von Personen', 'Un fallo de control pone en peligro la seguridad de las personas', 'Un guasto di controllo mette in pericolo la sicurezza delle persone'), 'industrie.process.produce'),
  r('industrie.risk.remote-maintenance', 'INDUSTRIE', l('Un accès de télémaintenance est détourné', 'A remote-maintenance access is hijacked', 'Ein Fernwartungszugang wird missbraucht', 'Se secuestra un acceso de telemantenimiento', 'Un accesso di teleassistenza viene sfruttato in modo illecito'), 'industrie.process.maintain'),
  r('commerce.risk.pricing', 'COMMERCE', l('Un prix erroné est publié et appliqué aux ventes', 'A wrong price is published and applied to sales', 'Ein falscher Preis wird veröffentlicht und angewendet', 'Se publica y aplica un precio erróneo a las ventas', 'Un prezzo errato viene pubblicato e applicato alle vendite'), 'commerce.process.sell'),
  r('commerce.risk.loyalty', 'COMMERCE', l('Des comptes de fidélité sont détournés', 'Loyalty accounts are hijacked', 'Treuekonten werden übernommen', 'Se secuestran cuentas de fidelidad', 'Gli account fedeltà vengono violati'), 'commerce.process.sell'),
  r('services.risk.subcontractor', 'SERVICES', l('Un sous-traitant manque à ses engagements sur une mission', 'A subcontractor fails its commitments on an engagement', 'Ein Subunternehmer erfüllt seine Zusagen bei einem Auftrag nicht', 'Un subcontratista incumple sus compromisos en un encargo', 'Un subappaltatore non rispetta gli impegni su un incarico'), 'services.process.perform'),
  r('services.risk.client-access', 'SERVICES', l('Un collaborateur accède à des dossiers clients sans nécessité', 'A staff member accesses client files without need', 'Ein Mitarbeiter greift ohne Notwendigkeit auf Kundenakten zu', 'Un empleado accede a expedientes de clientes sin necesidad', 'Un collaboratore accede a pratiche dei clienti senza necessidad'), 'services.process.knowledge'),
  // Énergie / utilities : continuité de la fourniture, systèmes de conduite, interventions terrain.
  p('energie.process.operate', 'ENERGIE', l('Exploiter les réseaux et installations', 'Operate networks and facilities', 'Netze und Anlagen betreiben', 'Operar redes e instalaciones', 'Gestire reti e impianti'), 'core.process.deliver'),
  p('energie.process.dispatch', 'ENERGIE', l('Équilibrer la production et la demande', 'Balance supply and demand', 'Erzeugung und Verbrauch ausgleichen', 'Equilibrar producción y demanda', 'Bilanciare produzione e domanda'), 'core.process.deliver'),
  p('energie.process.field', 'ENERGIE', l('Intervenir sur le terrain', 'Carry out field operations', 'Arbeiten vor Ort durchführen', 'Intervenir sobre el terreno', 'Eseguire interventi sul campo'), 'core.process.deliver'),
  p('energie.process.metering', 'ENERGIE', l('Relever, facturer et gérer les clients', 'Meter, bill and serve customers', 'Zählerstände erfassen, abrechnen und Kunden betreuen', 'Medir, facturar y atender a los clientes', 'Misurare, fatturare e gestire i clienti'), 'core.process.deliver'),
  r('energie.risk.scada', 'ENERGIE', l('Une intrusion sur un système de conduite perturbe la distribution', 'An intrusion into a control system disrupts distribution', 'Ein Eindringen in ein Leitsystem stört die Versorgung', 'Una intrusión en un sistema de control perturba la distribución', 'Un’intrusione in un sistema di controllo perturba la distribuzione'), 'energie.process.operate'),
  r('energie.risk.outage', 'ENERGIE', l('Une panne d’équipement interrompt l’alimentation de clients', 'Equipment failure cuts supply to customers', 'Ein Geräteausfall unterbricht die Versorgung von Kunden', 'Una avería de equipo interrumpe el suministro a clientes', 'Un guasto di un’apparecchiatura interrompe la fornitura ai clienti'), 'energie.process.operate'),
  r('energie.risk.imbalance', 'ENERGIE', l('Une erreur de prévision provoque un déséquilibre du réseau', 'A forecasting error causes a grid imbalance', 'Ein Prognosefehler verursacht ein Netzungleichgewicht', 'Un error de previsión provoca un desequilibrio de la red', 'Un errore di previsione provoca uno squilibrio della rete'), 'energie.process.dispatch'),
  r('energie.risk.field-safety', 'ENERGIE', l('Un accident survient lors d’une intervention terrain', 'An accident occurs during field work', 'Bei einem Einsatz vor Ort ereignet sich ein Unfall', 'Se produce un accidente durante una intervención sobre el terreno', 'Si verifica un incidente durante un intervento sul campo'), 'energie.process.field'),
  r('energie.risk.contractor-access', 'ENERGIE', l('Un prestataire de maintenance accède aux installations sans contrôle', 'A maintenance contractor accesses facilities without oversight', 'Ein Wartungsdienstleister greift unkontrolliert auf Anlagen zu', 'Un contratista de mantenimiento accede a las instalaciones sin control', 'Un fornitore di manutenzione accede agli impianti senza controllo'), 'energie.process.field'),
  r('energie.risk.metering-error', 'ENERGIE', l('Des relevés erronés faussent la facturation', 'Incorrect meter readings distort billing', 'Fehlerhafte Zählerstände verfälschen die Abrechnung', 'Lecturas erróneas falsean la facturación', 'Letture errate falsano la fatturazione'), 'energie.process.metering'),
  r('energie.risk.customer-data', 'ENERGIE', l('Des données de consommation de clients sont divulguées', 'Customer consumption data is disclosed', 'Verbrauchsdaten von Kunden werden offengelegt', 'Se divulgan datos de consumo de clientes', 'Vengono divulgati i dati di consumo dei clienti'), 'energie.process.metering'),

  // Transports / logistique : planification, acheminement, entrepôts, flotte.
  p('transport.process.plan', 'TRANSPORT', l('Planifier les tournées et les capacités', 'Plan routes and capacity', 'Touren und Kapazitäten planen', 'Planificar rutas y capacidades', 'Pianificare percorsi e capacità'), 'core.process.deliver'),
  p('transport.process.move', 'TRANSPORT', l('Transporter les marchandises ou les voyageurs', 'Carry goods or passengers', 'Waren oder Fahrgäste befördern', 'Transportar mercancías o viajeros', 'Trasportare merci o passeggeri'), 'core.process.deliver'),
  p('transport.process.warehouse', 'TRANSPORT', l('Gérer les entrepôts et les plateformes', 'Run warehouses and hubs', 'Lager und Umschlagplätze betreiben', 'Gestionar almacenes y plataformas', 'Gestire magazzini e piattaforme'), 'core.process.deliver'),
  p('transport.process.fleet', 'TRANSPORT', l('Entretenir la flotte de véhicules', 'Maintain the vehicle fleet', 'Fahrzeugflotte instand halten', 'Mantener la flota de vehículos', 'Manutenere la flotta di veicoli'), 'core.process.deliver'),
  r('transport.risk.planning-outage', 'TRANSPORT', l('Une panne du système de planification bloque les expéditions', 'A planning system outage blocks shipments', 'Ein Ausfall des Planungssystems blockiert den Versand', 'Una avería del sistema de planificación bloquea los envíos', 'Un guasto del sistema di pianificazione blocca le spedizioni'), 'transport.process.plan'),
  r('transport.risk.delay', 'TRANSPORT', l('Des retards en chaîne font manquer des engagements de livraison', 'Cascading delays cause missed delivery commitments', 'Kettenverzögerungen führen zu verpassten Lieferzusagen', 'Retrasos en cadena hacen incumplir compromisos de entrega', 'Ritardi a catena fanno mancare gli impegni di consegna'), 'transport.process.plan'),
  r('transport.risk.cargo-theft', 'TRANSPORT', l('Une cargaison est volée ou détournée', 'A shipment is stolen or diverted', 'Eine Sendung wird gestohlen oder umgeleitet', 'Se roba o desvía un envío', 'Un carico viene rubato o dirottato'), 'transport.process.move'),
  r('transport.risk.accident', 'TRANSPORT', l('Un accident de circulation implique un véhicule de l’entreprise', 'A road accident involves a company vehicle', 'Ein Verkehrsunfall betrifft ein Firmenfahrzeug', 'Un accidente de tráfico implica un vehículo de la empresa', 'Un incidente stradale coinvolge un veicolo aziendale'), 'transport.process.move'),
  r('transport.risk.stock-error', 'TRANSPORT', l('Une erreur d’inventaire en entrepôt provoque des expéditions erronées', 'A warehouse inventory error causes wrong shipments', 'Ein Bestandsfehler im Lager führt zu falschen Sendungen', 'Un error de inventario en el almacén provoca envíos erróneos', 'Un errore di inventario in magazzino causa spedizioni errate'), 'transport.process.warehouse'),
  r('transport.risk.maintenance', 'TRANSPORT', l('Un véhicule circule avec un entretien en retard', 'A vehicle operates with overdue maintenance', 'Ein Fahrzeug fährt mit überfälliger Wartung', 'Un vehículo circula con el mantenimiento atrasado', 'Un veicolo circola con la manutenzione scaduta'), 'transport.process.fleet'),
  r('transport.risk.telematics', 'TRANSPORT', l('Les données de géolocalisation des véhicules sont détournées', 'Vehicle tracking data is misused', 'Fahrzeugortungsdaten werden missbraucht', 'Se hace un uso indebido de los datos de geolocalización de los vehículos', 'I dati di geolocalizzazione dei veicoli vengono usati impropriamente'), 'transport.process.fleet'),

  // Télécommunications : réseau, activation des lignes, facturation, réquisitions.
  p('telecom.process.network', 'TELECOM', l('Exploiter le réseau et les services', 'Operate the network and services', 'Netz und Dienste betreiben', 'Operar la red y los servicios', 'Gestire la rete e i servizi'), 'core.process.deliver'),
  p('telecom.process.provision', 'TELECOM', l('Activer et modifier les lignes clients', 'Provision and change customer lines', 'Kundenanschlüsse schalten und ändern', 'Activar y modificar las líneas de clientes', 'Attivare e modificare le linee dei clienti'), 'core.process.deliver'),
  p('telecom.process.billing', 'TELECOM', l('Valoriser et facturer les consommations', 'Rate and bill usage', 'Verbrauch bewerten und abrechnen', 'Valorizar y facturar los consumos', 'Valorizzare e fatturare i consumi'), 'core.process.finance'),
  p('telecom.process.lawful', 'TELECOM', l('Traiter les réquisitions des autorités', 'Handle requests from authorities', 'Behördenanfragen bearbeiten', 'Tramitar los requerimientos de las autoridades', 'Gestire le richieste delle autorità'), 'core.process.govern'),
  r('telecom.risk.outage', 'TELECOM', l('Une panne majeure prive des clients de service, y compris des appels d’urgence', 'A major outage cuts customers off, including emergency calls', 'Ein schwerer Ausfall unterbricht den Dienst für Kunden, auch Notrufe', 'Una avería grave deja sin servicio a clientes, incluidas las llamadas de emergencia', 'Un guasto grave lascia i clienti senza servizio, comprese le chiamate di emergenza'), 'telecom.process.network'),
  r('telecom.risk.config-change', 'TELECOM', l('Une modification de configuration dégrade le réseau', 'A configuration change degrades the network', 'Eine Konfigurationsänderung beeinträchtigt das Netz', 'Un cambio de configuración degrada la red', 'Una modifica di configurazione degrada la rete'), 'telecom.process.network'),
  r('telecom.risk.traffic-data', 'TELECOM', l('Des données de trafic ou de localisation sont divulguées', 'Traffic or location data is disclosed', 'Verkehrs- oder Standortdaten werden offengelegt', 'Se divulgan datos de tráfico o de localización', 'Vengono divulgati dati di traffico o di localizzazione'), 'telecom.process.network'),
  r('telecom.risk.sim-swap', 'TELECOM', l('Une carte SIM est réattribuée frauduleusement à un tiers', 'A SIM card is fraudulently reassigned to someone else', 'Eine SIM-Karte wird betrügerisch einem Dritten zugewiesen', 'Una tarjeta SIM se reasigna fraudulentamente a un tercero', 'Una SIM viene riassegnata fraudolentemente a terzi'), 'telecom.process.provision'),
  r('telecom.risk.revenue-leak', 'TELECOM', l('Des consommations ne sont pas facturées', 'Usage goes unbilled', 'Verbrauch wird nicht abgerechnet', 'Hay consumos que no se facturan', 'Alcuni consumi non vengono fatturati'), 'telecom.process.billing'),
  r('telecom.risk.billing-error', 'TELECOM', l('Une erreur de tarification touche de nombreux clients', 'A rating error affects many customers', 'Ein Tarifierungsfehler betrifft viele Kunden', 'Un error de tarificación afecta a muchos clientes', 'Un errore di tariffazione colpisce molti clienti'), 'telecom.process.billing'),
  r('telecom.risk.request-error', 'TELECOM', l('Une réquisition est traitée hors délai ou de façon erronée', 'An authority request is handled late or incorrectly', 'Eine Behördenanfrage wird verspätet oder fehlerhaft bearbeitet', 'Un requerimiento se tramita fuera de plazo o de forma errónea', 'Una richiesta delle autorità viene gestita in ritardo o in modo errato'), 'telecom.process.lawful'),
]

/** Périodicité d'un contrôle ou d'un KRI : pour une petite structure (config `petiteStructure`), allégée d'un cran (hebdo→mensuel→trimestriel→semestriel) ; sinon inchangée. */
export function adaptPeriodicite<T extends NonNullable<CatalogueItem['periodicite']> | undefined>(p: T, petiteStructure: boolean): T {
  if (!petiteStructure || !p) return p
  const next: Record<string, NonNullable<CatalogueItem['periodicite']>> = { HEBDOMADAIRE: 'MENSUEL', MENSUEL: 'TRIMESTRIEL', TRIMESTRIEL: 'SEMESTRIEL' }
  return (next[p] ?? p) as T
}

export const CATALOGUE_PACK_VERSION = '1.14'

/** Jusqu'à trois activités déclarées ; aucune n'est déduite automatiquement. */
export function sanitizeSectorSelection(value: unknown): SectorCode[] | null {
  if (!Array.isArray(value) || value.length > 3 || value.some(code => typeof code !== 'string' || !SECTOR_CODES.includes(code as SectorCode))) return null
  return [...new Set(value as SectorCode[])]
}

/** Un secteur, plusieurs (organisation multisecteur : union des packs) ou aucun. */
export type SectorScope = SectorCode | readonly SectorCode[] | null

/** Socle + pack(s) choisi(s) ; sans secteur, seul le socle est retourné. Les clés sont propres à chaque secteur : l'union n'a pas de doublon. */
export function listSectorSuggestions(sector: SectorScope, locale: CatalogueLocale): SectorSuggestion[] {
  const chosen = new Set<string>(sector === null ? [] : typeof sector === 'string' ? [sector] : sector)
  const base = [...TRANSVERSAL, ...MERGED_REGISTRY_RISKS.filter(item => item.sector === 'TRANSVERSAL'), ...TRANSVERSAL_CONTROLS, ...TRANSVERSAL_KRIS, ...TRANSVERSAL_AUDITS, ...RESILIENCE_TEST_TEMPLATES.filter(item => item.sector === 'TRANSVERSAL')]
  const packs = SECTOR_CODES.filter(code => chosen.has(code)).flatMap(code => [...SECTOR_ITEMS, ...MERGED_REGISTRY_RISKS, ...SECTOR_PACK_ITEMS, ...BANCASSURANCE_ITEMS, ...EXT_ITEMS, ...RESILIENCE_TEST_TEMPLATES].filter(item => item.sector === code))
  return [...base, ...packs].map(({ title, unite, points, description, ...item }) => ({ ...item, title: title[locale], ...(description ? { description: description[locale] } : {}), ...(item.kind === 'RISK' && RISK_BALE[item.key] ? { taxonomieCode: `BALE_${RISK_BALE[item.key]}` } : {}), ...((item.kind === 'CONTROL' ? CONTROL_RISKS : item.kind === 'AUDIT' ? AUDIT_RISKS : {})[item.key] ? { riskKeys: (item.kind === 'CONTROL' ? CONTROL_RISKS : AUDIT_RISKS)[item.key] } : {}), ...(unite ? { unite: unite[locale] } : {}), ...(points ? { points: points.map(point => point[locale]) } : {}), packVersion: CATALOGUE_PACK_VERSION }))
}

export function searchSectorSuggestions(sector: SectorScope, locale: CatalogueLocale, query: string): SectorSuggestion[] {
  const normalized = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim()
  const words = normalized(query).split(/\s+/).filter(Boolean)
  return listSectorSuggestions(sector, locale).filter(item => words.every(word => normalized(item.title).includes(word)))
}
