/**
 * Catalogue 1.15 — éléments rattachés aux PATTERNS d'architecture de SI (docs/specs/patterns-architecture-besoins.md, lot A5) :
 * un risque, deux contrôles et un indicateur par pattern du lot 1 qui n'avait pas de contenu catalogue (les patterns
 * d'interconnexion reprennent le contenu de l'ancien secteur « Technique », cf. sector-packs-sante-technique.ts).
 * Proposés quand le pattern est coché, quel que soit le secteur. Suggestions à qualifier : jamais d'exécution, de seuil, de
 * date ni de conformité acquise. Contenu « à relire par un expert ».
 */
import { sectorPack, tagPatterns, U_NB, U_PCT } from './catalogue-pack-builder'

const ISO = 'ISO/IEC 27001:2022, annexe A'
const a = sectorPack('TRANSVERSAL', 'archi')

// ── SI standard (repli explicite de la création d'analyse) ──
a.risk('standard-unmanaged-baseline', 2, ['Un système courant est compromis faute d’un socle de sécurité connu et suivi', 'A standard information system is compromised because its security baseline is unknown or not maintained', 'Ein Standard-Informationssystem wird kompromittiert, weil seine Sicherheitsgrundlage unbekannt ist oder nicht gepflegt wird', 'Un sistema de información estándar se ve comprometido porque su línea de base de seguridad es desconocida o no se mantiene', 'Un sistema informativo standard viene compromesso perché la sua base di sicurezza è sconosciuta o non mantenuta'], 'core.process.digital.monitor')
a.control('standard-asset-baseline-review', ['Revue de l’inventaire, des propriétaires et du socle de sécurité du système', 'Review of the system inventory, owners and security baseline', 'Überprüfung von Inventar, Verantwortlichen und Sicherheitsgrundlage des Systems', 'Revisión del inventario, los responsables y la línea de base de seguridad del sistema', 'Revisione dell’inventario, dei responsabili e della base di sicurezza del sistema'], 'core.process.digital.monitor', 'ANNUEL', 'PREVENTIF', ['standard-unmanaged-baseline'], [ISO])
a.control('standard-security-updates-review', ['Vérification de l’application des mises à jour de sécurité sur les composants du système', 'Check that security updates are applied to system components', 'Prüfung, dass Sicherheitsupdates auf den Systemkomponenten angewendet werden', 'Verificación de la aplicación de actualizaciones de seguridad en los componentes del sistema', 'Verifica dell’applicazione degli aggiornamenti di sicurezza sui componenti del sistema'], 'core.process.digital.patch', 'MENSUEL', 'DETECTIF', ['standard-unmanaged-baseline'])
a.kri('standard-unmanaged-components', ['Composants du système sans propriétaire ou socle de sécurité documenté', 'System components without an owner or documented security baseline', 'Systemkomponenten ohne Verantwortlichen oder dokumentierte Sicherheitsgrundlage', 'Componentes del sistema sin responsable o línea de base de seguridad documentada', 'Componenti del sistema senza responsabile o base di sicurezza documentata'], 'core.process.digital.monitor', U_NB, 'HAUSSE', 'TRIMESTRIEL')

// ── Exposition sur Internet ──
a.risk('internet-exposed-vuln', 2, ['Une vulnérabilité d’un service exposé sur Internet est exploitée avant sa correction', 'A vulnerability in an Internet-exposed service is exploited before it is fixed', 'Eine Schwachstelle eines im Internet exponierten Dienstes wird vor der Behebung ausgenutzt', 'Se explota una vulnerabilidad de un servicio expuesto a Internet antes de corregirla', 'Una vulnerabilità di un servizio esposto a Internet viene sfruttata prima della correzione'], 'core.process.digital.patch')
a.control('internet-surface-scan', ['Balayage externe de la surface exposée sur Internet et comparaison avec l’inventaire', 'External scan of the Internet-exposed surface and comparison with the inventory', 'Externer Scan der im Internet exponierten Angriffsfläche und Abgleich mit dem Inventar', 'Escaneo externo de la superficie expuesta a Internet y comparación con el inventario', 'Scansione esterna della superficie esposta a Internet e confronto con l’inventario'], 'core.process.digital.monitor', 'MENSUEL', 'DETECTIF', ['internet-exposed-vuln'], [ISO])
a.control('internet-patch-deadline', ['Vérification du respect des délais de correction des failles critiques des services exposés', 'Check that critical flaws on exposed services are fixed within the deadlines', 'Prüfung der Einhaltung der Behebungsfristen für kritische Schwachstellen exponierter Dienste', 'Verificación del cumplimiento de los plazos de corrección de fallos críticos de servicios expuestos', 'Verifica del rispetto dei termini di correzione delle falle critiche dei servizi esposti'], 'core.process.digital.patch', 'MENSUEL', 'DETECTIF', ['internet-exposed-vuln'])
a.kri('internet-unpatched-days', ['Failles critiques de services exposés non corrigées au-delà du délai', 'Critical flaws on exposed services not fixed beyond the deadline', 'Kritische Schwachstellen exponierter Dienste, nicht innerhalb der Frist behoben', 'Fallos críticos de servicios expuestos sin corregir pasado el plazo', 'Falle critiche di servizi esposti non corrette oltre il termine'], 'core.process.digital.patch', U_NB, 'HAUSSE', 'MENSUEL')

// ── DMZ ──
a.risk('dmz-pivot', 2, ['Un serveur de la DMZ compromis sert de rebond vers le SI interne', 'A compromised DMZ server is used as a pivot into the internal IS', 'Ein kompromittierter DMZ-Server dient als Sprungbrett ins interne IS', 'Un servidor comprometido de la DMZ sirve de salto hacia el SI interno', 'Un server in DMZ compromesso funge da trampolino verso il SI interno'], 'core.process.digital.monitor')
a.control('dmz-rules-review', ['Revue des règles de filtrage entre Internet, la DMZ et le SI interne', 'Review of the filtering rules between the Internet, the DMZ and the internal IS', 'Überprüfung der Filterregeln zwischen Internet, DMZ und internem IS', 'Revisión de las reglas de filtrado entre Internet, la DMZ y el SI interno', 'Revisione delle regole di filtraggio tra Internet, DMZ e SI interno'], 'core.process.digital.monitor', 'SEMESTRIEL', 'PREVENTIF', ['dmz-pivot'])
a.control('dmz-hardening-check', ['Contrôle du durcissement et de la supervision des serveurs de la DMZ', 'Check of the hardening and monitoring of DMZ servers', 'Prüfung der Härtung und Überwachung der DMZ-Server', 'Control del endurecimiento y de la supervisión de los servidores de la DMZ', 'Verifica dell’hardening e del monitoraggio dei server in DMZ'], 'core.process.digital.monitor', 'TRIMESTRIEL', 'DETECTIF', ['dmz-pivot'])
a.kri('dmz-open-rules', ['Règles de filtrage DMZ vers l’interne sans justification documentée', 'DMZ-to-internal filtering rules without documented justification', 'DMZ-zu-intern-Filterregeln ohne dokumentierte Begründung', 'Reglas de filtrado de la DMZ al interior sin justificación documentada', 'Regole di filtraggio dalla DMZ verso l’interno senza giustificazione documentata'], 'core.process.digital.monitor', U_NB, 'HAUSSE', 'TRIMESTRIEL')

// ── Zone de confiance ──
a.risk('trust-zone-intrusion', 2, ['Un attaquant atteint la zone de confiance à partir d’une zone moins protégée', 'An attacker reaches the trusted zone from a less protected zone', 'Ein Angreifer erreicht die vertrauenswürdige Zone aus einer weniger geschützten Zone', 'Un atacante alcanza la zona de confianza desde una zona menos protegida', 'Un attaccante raggiunge la zona di fiducia da una zona meno protetta'], 'core.process.digital.iam')
a.control('trust-zone-access-review', ['Revue nominative des accès à la zone de confiance', 'Named review of access to the trusted zone', 'Namentliche Überprüfung der Zugriffe auf die vertrauenswürdige Zone', 'Revisión nominativa de los accesos a la zona de confianza', 'Revisione nominativa degli accessi alla zona di fiducia'], 'core.process.digital.iam', 'TRIMESTRIEL', 'PREVENTIF', ['trust-zone-intrusion'])
a.control('trust-zone-log-review', ['Revue des journaux d’accès et des flux entrants dans la zone de confiance', 'Review of access logs and inbound flows into the trusted zone', 'Überprüfung der Zugriffsprotokolle und eingehenden Flüsse in die vertrauenswürdige Zone', 'Revisión de los registros de acceso y de los flujos entrantes en la zona de confianza', 'Revisione dei log di accesso e dei flussi in ingresso nella zona di fiducia'], 'core.process.digital.monitor', 'MENSUEL', 'DETECTIF', ['trust-zone-intrusion'])
a.kri('trust-zone-shared-accounts', ['Comptes ou postes de la zone de confiance partagés avec d’autres zones', 'Accounts or workstations of the trusted zone shared with other zones', 'Mit anderen Zonen geteilte Konten oder Arbeitsplätze der vertrauenswürdigen Zone', 'Cuentas o puestos de la zona de confianza compartidos con otras zonas', 'Account o postazioni della zona di fiducia condivisi con altre zone'], 'core.process.digital.iam', U_NB, 'HAUSSE', 'TRIMESTRIEL')

// ── Zone de moindre confiance ──
a.risk('low-trust-contamination', 2, ['Un équipement non maîtrisé infecté contamine le réseau interne depuis une zone de moindre confiance', 'An infected unmanaged device contaminates the internal network from a lower-trust zone', 'Ein infiziertes, nicht kontrolliertes Gerät verseucht aus einer Zone mit geringerem Vertrauen das interne Netz', 'Un equipo no controlado infectado contamina la red interna desde una zona de menor confianza', 'Un dispositivo non controllato infetto contamina la rete interna da una zona a minore fiducia'], 'core.process.digital.monitor')
a.control('low-trust-segregation-test', ['Test d’étanchéité entre la zone de moindre confiance et le réseau interne', 'Isolation test between the lower-trust zone and the internal network', 'Dichtheitstest zwischen der Zone mit geringerem Vertrauen und dem internen Netz', 'Prueba de estanqueidad entre la zona de menor confianza y la red interna', 'Test di isolamento tra la zona a minore fiducia e la rete interna'], 'core.process.digital.monitor', 'SEMESTRIEL', 'DETECTIF', ['low-trust-contamination'])
a.control('low-trust-device-compliance', ['Contrôle de conformité des appareils avant connexion (BYOD, partenaires sur site)', 'Device compliance check before connection (BYOD, on-site partners)', 'Konformitätsprüfung der Geräte vor der Verbindung (BYOD, Partner vor Ort)', 'Control de conformidad de los dispositivos antes de conectarse (BYOD, socios in situ)', 'Controllo di conformità dei dispositivi prima della connessione (BYOD, partner in sede)'], 'core.process.digital.iam', 'TRIMESTRIEL', 'PREVENTIF', ['low-trust-contamination'])
a.kri('low-trust-noncompliant', ['Appareils non conformes détectés sur la zone de moindre confiance', 'Non-compliant devices detected on the lower-trust zone', 'Auf der Zone mit geringerem Vertrauen erkannte nicht konforme Geräte', 'Dispositivos no conformes detectados en la zona de menor confianza', 'Dispositivi non conformi rilevati nella zona a minore fiducia'], 'core.process.digital.monitor', U_NB, 'HAUSSE', 'MENSUEL')

// ── Accès distant ──
a.risk('remote-access-takeover', 2, ['Un accès distant est utilisé avec des identifiants volés pour entrer dans le SI', 'Remote access is used with stolen credentials to enter the IS', 'Ein Fernzugriff wird mit gestohlenen Zugangsdaten genutzt, um ins IS zu gelangen', 'Se usa un acceso remoto con credenciales robadas para entrar en el SI', 'Un accesso remoto viene usato con credenziali rubate per entrare nel SI'], 'core.process.digital.iam')
a.control('remote-mfa-coverage', ['Vérification de la couverture de l’authentification multifacteur sur tous les accès distants', 'Check of multi-factor authentication coverage on all remote access', 'Prüfung der Abdeckung der Mehrfaktor-Authentifizierung bei allen Fernzugriffen', 'Verificación de la cobertura de la autenticación multifactor en todos los accesos remotos', 'Verifica della copertura dell’autenticazione multifattore su tutti gli accessi remoti'], 'core.process.digital.iam', 'MENSUEL', 'DETECTIF', ['remote-access-takeover'])
a.control('remote-sessions-review', ['Revue des connexions distantes inhabituelles (horaires, pays, volumes)', 'Review of unusual remote connections (hours, countries, volumes)', 'Überprüfung ungewöhnlicher Fernverbindungen (Zeiten, Länder, Volumen)', 'Revisión de las conexiones remotas inusuales (horarios, países, volúmenes)', 'Revisione delle connessioni remote insolite (orari, paesi, volumi)'], 'core.process.digital.monitor', 'MENSUEL', 'DETECTIF', ['remote-access-takeover'])
a.kri('remote-without-mfa', ['Comptes avec accès distant sans second facteur', 'Accounts with remote access and no second factor', 'Konten mit Fernzugriff ohne zweiten Faktor', 'Cuentas con acceso remoto sin segundo factor', 'Account con accesso remoto senza secondo fattore'], 'core.process.digital.iam', U_NB, 'HAUSSE', 'MENSUEL')

// ── Télémaintenance ──
a.risk('telemaintenance-abuse', 2, ['L’accès de télémaintenance d’un tiers est détourné pour agir sur le SI', 'A third party’s remote-maintenance access is hijacked to act on the IS', 'Der Fernwartungszugang eines Dritten wird missbraucht, um auf das IS einzuwirken', 'El acceso de telemantenimiento de un tercero se desvía para actuar sobre el SI', 'L’accesso di teleassistenza di una terza parte viene dirottato per agire sul SI'], 'core.process.buy.sourcing')
a.control('telemaintenance-access-review', ['Revue des accès de télémaintenance ouverts et de leur justification', 'Review of open remote-maintenance access and its justification', 'Überprüfung der offenen Fernwartungszugänge und ihrer Begründung', 'Revisión de los accesos de telemantenimiento abiertos y de su justificación', 'Revisione degli accessi di teleassistenza aperti e della loro giustificazione'], 'core.process.buy.review', 'TRIMESTRIEL', 'PREVENTIF', ['telemaintenance-abuse'])
a.control('telemaintenance-session-recording', ['Contrôle de l’enregistrement et de la revue des sessions de télémaintenance', 'Check of the recording and review of remote-maintenance sessions', 'Prüfung der Aufzeichnung und Überprüfung von Fernwartungssitzungen', 'Control de la grabación y revisión de las sesiones de telemantenimiento', 'Verifica della registrazione e revisione delle sessioni di teleassistenza'], 'core.process.digital.monitor', 'MENSUEL', 'DETECTIF', ['telemaintenance-abuse'])
a.kri('telemaintenance-permanent', ['Accès de télémaintenance permanents (non ouverts à la demande)', 'Permanent remote-maintenance access (not opened on demand)', 'Dauerhafte Fernwartungszugänge (nicht auf Anforderung geöffnet)', 'Accesos de telemantenimiento permanentes (no abiertos a petición)', 'Accessi di teleassistenza permanenti (non aperti su richiesta)'], 'core.process.buy.review', U_NB, 'HAUSSE', 'TRIMESTRIEL')

// ── Système d'administration ──
a.risk('admin-system-takeover', 2, ['Le système d’administration est pris en main et donne la maîtrise de l’ensemble du SI', 'The administration system is taken over and gives control of the whole IS', 'Das Administrationssystem wird übernommen und verschafft die Kontrolle über das gesamte IS', 'Se toma el control del sistema de administración y se domina todo el SI', 'Il sistema di amministrazione viene preso in carico e dà il controllo di tutto il SI'], 'core.process.digital.iam')
a.control('admin-accounts-review', ['Revue des comptes à privilèges et des groupes d’administration', 'Review of privileged accounts and administration groups', 'Überprüfung der privilegierten Konten und Administrationsgruppen', 'Revisión de las cuentas con privilegios y de los grupos de administración', 'Revisione degli account privilegiati e dei gruppi di amministrazione'], 'core.process.digital.iam', 'TRIMESTRIEL', 'PREVENTIF', ['admin-system-takeover'])
a.control('admin-actions-log-review', ['Revue des actions d’administration journalisées (création de comptes, changements de groupes)', 'Review of logged administration actions (account creation, group changes)', 'Überprüfung protokollierter Administrationsaktionen (Kontoanlage, Gruppenänderungen)', 'Revisión de las acciones de administración registradas (creación de cuentas, cambios de grupos)', 'Revisione delle azioni di amministrazione registrate (creazione di account, modifiche ai gruppi)'], 'core.process.digital.monitor', 'MENSUEL', 'DETECTIF', ['admin-system-takeover'])
a.kri('admin-privileged-accounts', ['Comptes à privilèges actifs sans justification récente', 'Active privileged accounts with no recent justification', 'Aktive privilegierte Konten ohne aktuelle Begründung', 'Cuentas con privilegios activas sin justificación reciente', 'Account privilegiati attivi senza giustificazione recente'], 'core.process.digital.iam', U_NB, 'HAUSSE', 'TRIMESTRIEL')

// ── Flux internes au datacenter ──
a.risk('east-west-propagation', 6, ['Une compromission se propage rapidement entre serveurs faute de segmentation interne', 'A compromise spreads quickly between servers for lack of internal segmentation', 'Eine Kompromittierung breitet sich mangels interner Segmentierung schnell zwischen Servern aus', 'Un compromiso se propaga rápidamente entre servidores por falta de segmentación interna', 'Una compromissione si propaga rapidamente tra i server per mancanza di segmentazione interna'], 'core.process.digital.monitor')
a.control('east-west-matrix-review', ['Revue de la matrice des flux internes et suppression des flux inutiles', 'Review of the internal flow matrix and removal of unnecessary flows', 'Überprüfung der Matrix interner Flüsse und Entfernung unnötiger Flüsse', 'Revisión de la matriz de flujos internos y eliminación de los flujos innecesarios', 'Revisione della matrice dei flussi interni e rimozione dei flussi non necessari'], 'core.process.digital.monitor', 'SEMESTRIEL', 'PREVENTIF', ['east-west-propagation'])
a.control('east-west-lateral-detection-test', ['Test de détection des mouvements latéraux entre serveurs', 'Test of the detection of lateral movement between servers', 'Test der Erkennung von Seitwärtsbewegungen zwischen Servern', 'Prueba de detección de movimientos laterales entre servidores', 'Test di rilevamento dei movimenti laterali tra server'], 'core.process.digital.monitor', 'SEMESTRIEL', 'DETECTIF', ['east-west-propagation'])
a.kri('east-west-any-any-rules', ['Règles internes trop larges (tout vers tout)', 'Overly broad internal rules (any to any)', 'Zu weit gefasste interne Regeln (alles zu allem)', 'Reglas internas demasiado amplias (todo a todo)', 'Regole interne troppo ampie (tutto verso tutto)'], 'core.process.digital.monitor', U_NB, 'HAUSSE', 'TRIMESTRIEL')

// ── SI bureautique ──
a.risk('office-ransomware', 6, ['Un rançongiciel arrivé par la messagerie chiffre les postes et les partages', 'Ransomware delivered by e-mail encrypts workstations and shares', 'Per E-Mail eingeschleuste Ransomware verschlüsselt Arbeitsplätze und Freigaben', 'Un ransomware llegado por correo cifra los puestos y los recursos compartidos', 'Un ransomware arrivato per posta elettronica cifra postazioni e condivisioni'], 'core.process.digital.backup')
a.control('office-backup-restore-test', ['Test de restauration des sauvegardes des postes et des partages de fichiers', 'Restore test of workstation and file-share backups', 'Wiederherstellungstest der Sicherungen von Arbeitsplätzen und Dateifreigaben', 'Prueba de restauración de las copias de puestos y recursos compartidos', 'Test di ripristino dei backup di postazioni e condivisioni di file'], 'core.process.digital.backup', 'TRIMESTRIEL', 'CORRECTIF', ['office-ransomware'])
a.control('office-phishing-exercise', ['Exercice de simulation d’hameçonnage et suivi des signalements', 'Phishing simulation exercise and follow-up of reports', 'Phishing-Simulationsübung und Nachverfolgung der Meldungen', 'Ejercicio de simulación de phishing y seguimiento de los avisos', 'Esercizio di simulazione di phishing e monitoraggio delle segnalazioni'], 'core.process.people.skills', 'SEMESTRIEL', 'PREVENTIF', ['office-ransomware'])
a.kri('office-unpatched-workstations', ['Postes de travail avec correctifs critiques manquants', 'Workstations missing critical patches', 'Arbeitsplätze mit fehlenden kritischen Patches', 'Puestos de trabajo con parches críticos pendientes', 'Postazioni di lavoro con aggiornamenti critici mancanti'], 'core.process.digital.patch', U_PCT, 'HAUSSE', 'MENSUEL')

// ── SI de très petite entreprise ──
a.risk('tpe-data-loss', 6, ['Les données de la structure sont perdues faute de sauvegarde exploitable', 'The business’s data is lost for lack of a usable backup', 'Die Daten des Betriebs gehen mangels brauchbarer Sicherung verloren', 'Los datos de la estructura se pierden por falta de una copia utilizable', 'I dati della struttura vanno persi per mancanza di un backup utilizzabile'], 'core.process.digital.backup')
a.control('tpe-backup-check', ['Vérification que la sauvegarde hors ligne ou hors site est à jour et restaurable', 'Check that the offline or off-site backup is up to date and restorable', 'Prüfung, dass die Offline- oder externe Sicherung aktuell und wiederherstellbar ist', 'Verificación de que la copia fuera de línea o fuera del sitio está al día y es restaurable', 'Verifica che il backup offline o fuori sede sia aggiornato e ripristinabile'], 'core.process.digital.backup', 'MENSUEL', 'DETECTIF', ['tpe-data-loss'])
a.control('tpe-shared-accounts-review', ['Revue des comptes partagés et des mots de passe réutilisés', 'Review of shared accounts and reused passwords', 'Überprüfung gemeinsamer Konten und wiederverwendeter Passwörter', 'Revisión de las cuentas compartidas y de las contraseñas reutilizadas', 'Revisione degli account condivisi e delle password riutilizzate'], 'core.process.digital.iam', 'SEMESTRIEL', 'PREVENTIF', ['tpe-data-loss'])
a.kri('tpe-shared-accounts', ['Comptes partagés encore utilisés', 'Shared accounts still in use', 'Weiterhin genutzte gemeinsame Konten', 'Cuentas compartidas aún en uso', 'Account condivisi ancora in uso'], 'core.process.digital.iam', U_NB, 'HAUSSE', 'SEMESTRIEL')

// ── SI sensible ──
a.risk('sensitive-is-exfiltration', 2, ['Des informations sensibles sont exfiltrées d’un SI insuffisamment cloisonné', 'Sensitive information is exfiltrated from an insufficiently compartmentalised IS', 'Sensible Informationen werden aus einem unzureichend abgeschotteten IS exfiltriert', 'Se exfiltra información sensible de un SI insuficientemente compartimentado', 'Informazioni sensibili vengono esfiltrate da un SI insufficientemente compartimentato'], 'core.process.digital.iam')
a.control('sensitive-is-accreditation-review', ['Revue de la décision d’homologation et de ses réserves avant l’échéance', 'Review of the accreditation decision and its reservations before expiry', 'Überprüfung der Akkreditierungsentscheidung und ihrer Vorbehalte vor Ablauf', 'Revisión de la decisión de homologación y de sus reservas antes del vencimiento', 'Revisione della decisione di omologazione e delle sue riserve prima della scadenza'], 'core.process.govern.compliance', 'ANNUEL', 'PREVENTIF', ['sensitive-is-exfiltration'])
a.control('sensitive-is-gateway-review', ['Revue des passerelles et des échanges entre le SI sensible et les autres SI', 'Review of gateways and exchanges between the sensitive IS and other IS', 'Überprüfung der Gateways und des Austauschs zwischen dem sensiblen IS und anderen IS', 'Revisión de las pasarelas y de los intercambios entre el SI sensible y otros SI', 'Revisione dei gateway e degli scambi tra il SI sensibile e altri SI'], 'core.process.digital.monitor', 'TRIMESTRIEL', 'DETECTIF', ['sensitive-is-exfiltration'])
a.kri('sensitive-is-uncleared-access', ['Accès au SI sensible sans habilitation à jour', 'Access to the sensitive IS without up-to-date clearance', 'Zugriffe auf das sensible IS ohne aktuelle Ermächtigung', 'Accesos al SI sensible sin habilitación al día', 'Accessi al SI sensibile senza abilitazione aggiornata'], 'core.process.digital.iam', U_NB, 'HAUSSE', 'TRIMESTRIEL')

const PATTERN_OF_PREFIX: Array<[string, string]> = [
  ['standard-', 'SI_STANDARD'], ['internet-', 'EXPOSITION_INTERNET'], ['dmz-', 'DMZ'], ['trust-zone-', 'ZONE_CONFIANCE'], ['low-trust-', 'ZONE_MOINDRE_CONFIANCE'], ['remote-', 'ACCES_DISTANT'],
  ['telemaintenance-', 'TELEMAINTENANCE'], ['admin-', 'SI_ADMINISTRATION'], ['east-west-', 'FLUX_INTERNES_DC'], ['office-', 'BUREAUTIQUE'], ['tpe-', 'SI_TPE'], ['sensitive-is-', 'SI_SENSIBLE'],
]
export const PATTERNS_PACK = tagPatterns(a.pack, item => {
  const slug = item.key.split('.').slice(2).join('.')
  const hit = PATTERN_OF_PREFIX.find(([p]) => slug.startsWith(p))
  if (!hit) throw new Error(`pattern introuvable pour ${item.key}`)
  return [hit[1]]
})
void ISO
