/**
 * Pack « Associations / Économie sociale et solidaire » (catalogue 1.10) : associations, fondations, structures de l'ESS.
 * Suggestions à qualifier : jamais d'exécution, de seuil, de date, de résultat ni de conformité acquise. Les `references`
 * citent le texte d'origine sans reproduire d'exigence. Contenu à relire par un expert du secteur (statut « à relire »).
 */
import { sectorPack, U_NB, U_PCT, U_DAYS } from './catalogue-pack-builder'

const RGPD = 'Règlement (UE) 2016/679 (RGPD)'
const LOI1901 = 'Loi du 1er juillet 1901 relative au contrat d’association'
const LOI2000 = 'Loi n° 2000-321 du 12 avril 2000 relative aux droits des citoyens dans leurs relations avec les administrations (subventions)'
const LOI2021 = 'Loi n° 2021-1109 du 24 août 2021 confortant le respect des principes de la République (contrat d’engagement républicain)'

const b = sectorPack('ASSOCIATIONS')

b.process('governance', ['Assurer la gouvernance, les assemblées et la tenue des registres', 'Ensure governance, general meetings and record keeping', 'Governance, Versammlungen und Registerführung sicherstellen', 'Asegurar la gobernanza, las asambleas y la llevanza de registros', 'Assicurare la governance, le assemblee e la tenuta dei registri'])
b.process('funding', ['Obtenir et justifier les subventions et financements', 'Obtain and justify grants and funding', 'Zuschüsse und Finanzierungen einwerben und nachweisen', 'Obtener y justificar las subvenciones y financiaciones', 'Ottenere e rendicontare sovvenzioni e finanziamenti'])
b.process('donations', ['Collecter les dons et cotisations, délivrer les reçus', 'Collect donations and membership fees, issue receipts', 'Spenden und Beiträge einziehen, Bescheinigungen ausstellen', 'Recaudar donaciones y cuotas, expedir los recibos', 'Raccogliere donazioni e quote, rilasciare le ricevute'])
b.process('members', ['Gérer les adhérents, bénéficiaires et données associées', 'Manage members, beneficiaries and related data', 'Mitglieder, Begünstigte und zugehörige Daten verwalten', 'Gestionar los socios, los beneficiarios y sus datos', 'Gestire soci, beneficiari e dati associati'])
b.process('volunteers', ['Recruter, encadrer et protéger les bénévoles et salariés', 'Recruit, supervise and protect volunteers and employees', 'Ehrenamtliche und Beschäftigte gewinnen, anleiten und schützen', 'Reclutar, coordinar y proteger a voluntarios y empleados', 'Reclutare, coordinare e proteggere volontari e dipendenti'])
b.process('activities', ['Organiser les activités, événements et accueils de publics', 'Run activities, events and public reception', 'Aktivitäten, Veranstaltungen und Publikumsempfang durchführen', 'Organizar las actividades, eventos y acogida de públicos', 'Organizzare attività, eventi e accoglienza del pubblico'])

b.risk('treasurer-fraud', 1, ['Des fonds sont détournés par un dirigeant, un trésorier ou un salarié', 'Funds are misappropriated by an officer, treasurer or employee', 'Gelder werden von einem Vorstandsmitglied, Kassenwart oder Beschäftigten veruntreut', 'Un directivo, tesorero o empleado desvía fondos', 'Dei fondi vengono sottratti da un dirigente, tesoriere o dipendente'], 'governance')
b.risk('payment-diversion', 2, ['Un paiement est détourné après usurpation de l’identité d’un dirigeant ou d’un fournisseur', 'A payment is diverted after impersonation of an officer or supplier', 'Eine Zahlung wird nach Identitätsmissbrauch eines Vorstands oder Lieferanten umgeleitet', 'Un pago se desvía tras suplantar la identidad de un directivo o proveedor', 'Un pagamento viene dirottato dopo il furto d’identità di un dirigente o fornitore'], 'donations')
b.risk('grant-misuse', 7, ['Une subvention est utilisée hors de son objet ou insuffisamment justifiée', 'A grant is used outside its purpose or insufficiently justified', 'Ein Zuschuss wird zweckfremd verwendet oder unzureichend nachgewiesen', 'Una subvención se usa fuera de su objeto o se justifica insuficientemente', 'Una sovvenzione viene utilizzata fuori dal suo scopo o rendicontata in modo insufficiente'], 'funding')
b.risk('funder-dependence', 7, ['La perte d’un financeur principal met en péril l’activité', 'Losing a main funder jeopardises operations', 'Der Verlust eines Hauptfinanziers gefährdet den Betrieb', 'La pérdida de un financiador principal pone en peligro la actividad', 'La perdita di un finanziatore principale mette a rischio l’attività'], 'funding')
b.risk('donor-data', 4, ['Des données de donateurs, d’adhérents ou de bénéficiaires vulnérables sont divulguées', 'Data of donors, members or vulnerable beneficiaries is disclosed', 'Daten von Spendern, Mitgliedern oder schutzbedürftigen Begünstigten werden offengelegt', 'Se divulgan datos de donantes, socios o beneficiarios vulnerables', 'Vengono divulgati dati di donatori, soci o beneficiari vulnerabili'], 'members')
b.risk('sensitive-data', 4, ['Des données sensibles révélant opinions, santé ou situation sociale sont exposées', 'Sensitive data revealing opinions, health or social situation is exposed', 'Sensible Daten zu Überzeugungen, Gesundheit oder sozialer Lage werden offengelegt', 'Se exponen datos sensibles que revelan opiniones, salud o situación social', 'Vengono esposti dati sensibili che rivelano opinioni, salute o situazione sociale'], 'members')
b.risk('ransomware', 2, ['Un rançongiciel bloque les fichiers et le logiciel de gestion de l’association', 'Ransomware locks the files and management software of the organisation', 'Ransomware sperrt die Dateien und die Verwaltungssoftware der Organisation', 'Un ransomware bloquea los archivos y el software de gestión de la asociación', 'Un ransomware blocca i file e il software gestionale dell’associazione'], 'governance')
b.risk('volunteer-harm', 3, ['Un bénévole ou un bénéficiaire subit un préjudice lors d’une activité (accident, comportement inapproprié)', 'A volunteer or beneficiary suffers harm during an activity (accident, inappropriate behaviour)', 'Ein Ehrenamtlicher oder Begünstigter kommt bei einer Aktivität zu Schaden (Unfall, unangemessenes Verhalten)', 'Un voluntario o beneficiario sufre un daño durante una actividad (accidente, conducta inadecuada)', 'Un volontario o beneficiario subisce un danno durante un’attività (infortunio, comportamento inappropriato)'], 'volunteers')
b.risk('key-volunteer', 3, ['Le départ d’un bénévole clé fait perdre l’accès aux comptes et aux savoir-faire', 'A key volunteer’s departure causes loss of account access and know-how', 'Der Weggang eines Schlüsselehrenamtlichen führt zum Verlust von Kontozugängen und Know-how', 'La salida de un voluntario clave hace perder el acceso a cuentas y conocimientos', 'La partenza di un volontario chiave fa perdere l’accesso agli account e il know-how'], 'volunteers')
b.risk('event-incident', 5, ['Un événement accueillant du public se déroule sans cadre de sécurité adapté', 'An event with public attendance runs without a suitable safety framework', 'Eine Veranstaltung mit Publikum findet ohne angemessenes Sicherheitskonzept statt', 'Un evento con público se celebra sin un marco de seguridad adecuado', 'Un evento con pubblico si svolge senza un quadro di sicurezza adeguato'], 'activities')
b.risk('tax-receipts', 7, ['Des reçus fiscaux sont délivrés à tort ou sans justification suffisante', 'Tax receipts are issued wrongly or without sufficient justification', 'Spendenbescheinigungen werden zu Unrecht oder ohne ausreichende Begründung ausgestellt', 'Se expiden recibos fiscales indebidamente o sin justificación suficiente', 'Ricevute fiscali vengono rilasciate a torto o senza giustificazione sufficiente'], 'donations')
b.risk('governance-failure', 7, ['Les obligations statutaires (assemblées, comptes, déclarations) ne sont pas respectées', 'Statutory obligations (meetings, accounts, filings) are not met', 'Satzungs- und gesetzliche Pflichten (Versammlungen, Abschlüsse, Meldungen) werden nicht erfüllt', 'No se cumplen las obligaciones estatutarias (asambleas, cuentas, declaraciones)', 'Gli obblighi statutari (assemblee, bilanci, dichiarazioni) non sono rispettati'], 'governance')

b.control('dual-signature', ['Contrôle de la double signature ou validation des paiements au-dessus d’un seuil', 'Check of dual signature or approval of payments above a threshold', 'Prüfung der Zwei-Unterschriften-Regel oder Freigabe von Zahlungen über einer Schwelle', 'Control de la doble firma o validación de pagos por encima de un umbral', 'Controllo della doppia firma o autorizzazione dei pagamenti oltre una soglia'], 'governance', 'MENSUEL', 'PREVENTIF', ['treasurer-fraud', 'payment-diversion'])
b.control('bank-reconciliation', ['Rapprochement bancaire mensuel revu par une personne distincte du trésorier', 'Monthly bank reconciliation reviewed by someone other than the treasurer', 'Monatlicher Bankabgleich, geprüft von einer vom Kassenwart verschiedenen Person', 'Conciliación bancaria mensual revisada por una persona distinta del tesorero', 'Riconciliazione bancaria mensile rivista da una persona diversa dal tesoriere'], 'governance', 'MENSUEL', 'DETECTIF', ['treasurer-fraud'])
b.control('bank-detail-callback', ['Rappel de vérification avant tout changement de coordonnées bancaires ou paiement inhabituel', 'Call-back verification before any bank-detail change or unusual payment', 'Rückruf-Verifizierung vor jeder Änderung von Bankverbindungen oder ungewöhnlicher Zahlung', 'Verificación telefónica antes de cualquier cambio de datos bancarios o pago inusual', 'Richiamata di verifica prima di ogni modifica di coordinate bancarie o pagamento insolito'], 'donations', 'MENSUEL', 'PREVENTIF', ['payment-diversion'])
b.control('cash-handling', ['Contrôle par échantillon de la gestion des espèces et des quêtes', 'Sample check of cash and collection handling', 'Stichprobenprüfung der Handhabung von Bargeld und Sammlungen', 'Control por muestreo de la gestión de efectivo y colectas', 'Controllo a campione della gestione dei contanti e delle raccolte'], 'donations', 'TRIMESTRIEL', 'DETECTIF', ['treasurer-fraud'])
b.control('receipt-register', ['Rapprochement des reçus fiscaux émis avec les dons encaissés', 'Reconciliation of tax receipts issued with donations received', 'Abgleich ausgestellter Spendenbescheinigungen mit eingegangenen Spenden', 'Conciliación de los recibos fiscales emitidos con las donaciones cobradas', 'Riconciliazione delle ricevute fiscali emesse con le donazioni incassate'], 'donations', 'TRIMESTRIEL', 'DETECTIF', ['tax-receipts'])
b.control('membership-register', ['Rapprochement du registre des adhérents avec les cotisations encaissées', 'Reconciliation of the member register with membership fees received', 'Abgleich des Mitgliederverzeichnisses mit den eingegangenen Beiträgen', 'Conciliación del registro de socios con las cuotas cobradas', 'Riconciliazione del registro dei soci con le quote incassate'], 'members', 'SEMESTRIEL', 'DETECTIF', ['treasurer-fraud', 'governance-failure'])
b.control('grant-expenses', ['Revue de la correspondance entre dépenses engagées et objet de la subvention', 'Review of match between expenses incurred and grant purpose', 'Überprüfung der Übereinstimmung von Ausgaben mit dem Zuschusszweck', 'Revisión de la correspondencia entre gastos y objeto de la subvención', 'Revisione della corrispondenza tra spese sostenute e scopo della sovvenzione'], 'funding', 'TRIMESTRIEL', 'DETECTIF', ['grant-misuse'], [LOI2000])
b.control('grant-reports', ['Suivi du calendrier des comptes rendus financiers dus aux financeurs', 'Follow-up of the schedule of financial reports due to funders', 'Überwachung des Terminplans der gegenüber Geldgebern fälligen Verwendungsnachweise', 'Seguimiento del calendario de los informes financieros debidos a los financiadores', 'Monitoraggio del calendario delle rendicontazioni finanziarie dovute ai finanziatori'], 'funding', 'MENSUEL', 'PREVENTIF', ['grant-misuse'], [LOI2000])
b.control('funding-mix', ['Revue de la répartition des financements et de la dépendance aux principaux financeurs', 'Review of funding mix and reliance on main funders', 'Überprüfung der Finanzierungsstruktur und der Abhängigkeit von Hauptgeldgebern', 'Revisión de la distribución de financiaciones y de la dependencia de los principales financiadores', 'Revisione della ripartizione dei finanziamenti e della dipendenza dai principali finanziatori'], 'funding', 'SEMESTRIEL', 'DETECTIF', ['funder-dependence'])
b.control('republican-commitment', ['Vérification de la prise en compte du contrat d’engagement républicain dans les subventions reçues', 'Check that the republican commitment contract is taken into account for grants received', 'Prüfung der Berücksichtigung des Republikanischen Engagementvertrags bei erhaltenen Zuschüssen', 'Verificación de la consideración del contrato de compromiso republicano en las subvenciones recibidas', 'Verifica del rispetto del contratto di impegno repubblicano nelle sovvenzioni ricevute'], 'funding', 'ANNUEL', 'PREVENTIF', ['governance-failure'], [LOI2021])
b.control('member-data-access', ['Revue des accès aux fichiers d’adhérents, donateurs et bénéficiaires', 'Review of access to member, donor and beneficiary files', 'Überprüfung der Zugriffe auf Mitglieder-, Spender- und Begünstigtendateien', 'Revisión de los accesos a ficheros de socios, donantes y beneficiarios', 'Revisione degli accessi ai file di soci, donatori e beneficiari'], 'members', 'TRIMESTRIEL', 'DETECTIF', ['donor-data', 'sensitive-data'], [RGPD])
b.control('data-retention', ['Contrôle de la purge des données d’anciens adhérents et bénéficiaires', 'Check of purging of former members’ and beneficiaries’ data', 'Prüfung der Löschung von Daten ehemaliger Mitglieder und Begünstigter', 'Control de la eliminación de datos de antiguos socios y beneficiarios', 'Controllo dell’eliminazione dei dati di ex soci e beneficiari'], 'members', 'ANNUEL', 'DETECTIF', ['donor-data'], [RGPD])
b.control('shared-tools', ['Revue des outils partagés (tableurs, messageries, stockage) et de leurs partages publics', 'Review of shared tools (spreadsheets, messaging, storage) and their public sharing', 'Überprüfung gemeinsam genutzter Werkzeuge (Tabellen, Messenger, Speicher) und öffentlicher Freigaben', 'Revisión de las herramientas compartidas (hojas de cálculo, mensajería, almacenamiento) y de sus enlaces públicos', 'Revisione degli strumenti condivisi (fogli di calcolo, messaggistica, archiviazione) e delle loro condivisioni pubbliche'], 'members', 'TRIMESTRIEL', 'DETECTIF', ['sensitive-data', 'donor-data'])
b.control('backup-test', ['Test de restauration des sauvegardes de la base adhérents et de la comptabilité', 'Restoration test of member database and accounting backups', 'Wiederherstellungstest der Sicherungen von Mitgliederdatenbank und Buchhaltung', 'Prueba de restauración de las copias de la base de socios y de la contabilidad', 'Test di ripristino dei backup del database soci e della contabilità'], 'governance', 'SEMESTRIEL', 'DETECTIF', ['ransomware'])
b.control('account-handover', ['Vérification de la remise des accès et des mots de passe lors du départ d’un responsable', 'Check of handover of access and passwords when an officer leaves', 'Prüfung der Übergabe von Zugängen und Passwörtern beim Ausscheiden einer verantwortlichen Person', 'Verificación del traspaso de accesos y contraseñas cuando sale un responsable', 'Verifica della consegna di accessi e password quando un responsabile lascia'], 'volunteers', 'TRIMESTRIEL', 'PREVENTIF', ['key-volunteer', 'ransomware'])
b.control('mfa-admin', ['Vérification de l’authentification renforcée des comptes de banque, de messagerie et de gestion', 'Check of strong authentication on bank, email and management accounts', 'Prüfung der starken Authentifizierung der Bank-, E-Mail- und Verwaltungskonten', 'Verificación de la autenticación reforzada de las cuentas bancarias, de correo y de gestión', 'Verifica dell’autenticazione forte degli account bancari, di posta e gestionali'], 'governance', 'TRIMESTRIEL', 'DETECTIF', ['payment-diversion', 'ransomware'])
b.control('volunteer-screening', ['Vérification de l’accueil, de l’information et du contrôle des bénévoles intervenant auprès de publics fragiles', 'Check of onboarding, information and screening of volunteers working with vulnerable groups', 'Prüfung von Einarbeitung, Information und Überprüfung von Ehrenamtlichen mit schutzbedürftigen Gruppen', 'Verificación de la acogida, información y control de los voluntarios que intervienen con públicos frágiles', 'Verifica dell’accoglienza, dell’informazione e dei controlli sui volontari che operano con pubblici fragili'], 'volunteers', 'ANNUEL', 'PREVENTIF', ['volunteer-harm'])
b.control('insurance-cover', ['Revue de la couverture d’assurance (activités, bénévoles, événements)', 'Review of insurance cover (activities, volunteers, events)', 'Überprüfung des Versicherungsschutzes (Aktivitäten, Ehrenamtliche, Veranstaltungen)', 'Revisión de la cobertura de seguros (actividades, voluntarios, eventos)', 'Revisione della copertura assicurativa (attività, volontari, eventi)'], 'activities', 'ANNUEL', 'PREVENTIF', ['volunteer-harm', 'event-incident'])
b.control('event-safety-plan', ['Vérification de la préparation sécurité avant chaque événement accueillant du public', 'Check of safety preparation before each event with public attendance', 'Prüfung der Sicherheitsvorbereitung vor jeder Veranstaltung mit Publikum', 'Verificación de la preparación de seguridad antes de cada evento con público', 'Verifica della preparazione di sicurezza prima di ogni evento con pubblico'], 'activities', 'TRIMESTRIEL', 'PREVENTIF', ['event-incident'])
b.control('statutory-calendar', ['Suivi du calendrier statutaire (assemblées, approbation des comptes, déclarations)', 'Follow-up of the statutory calendar (meetings, approval of accounts, filings)', 'Überwachung des Satzungskalenders (Versammlungen, Genehmigung der Abschlüsse, Meldungen)', 'Seguimiento del calendario estatutario (asambleas, aprobación de cuentas, declaraciones)', 'Monitoraggio del calendario statutario (assemblee, approvazione dei bilanci, dichiarazioni)'], 'governance', 'TRIMESTRIEL', 'PREVENTIF', ['governance-failure'], [LOI1901])

b.kri('unreconciled-items', ['Opérations bancaires non rapprochées depuis plus d’un mois', 'Bank transactions unreconciled for over a month', 'Seit über einem Monat nicht abgestimmte Bankbuchungen', 'Operaciones bancarias sin conciliar desde hace más de un mes', 'Operazioni bancarie non riconciliate da oltre un mese'], 'governance', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('single-signatory', ['Paiements effectués par une seule personne au-dessus du seuil fixé', 'Payments made by a single person above the set threshold', 'Von einer einzigen Person über dem festgelegten Schwellenwert ausgeführte Zahlungen', 'Pagos realizados por una sola persona por encima del umbral fijado', 'Pagamenti effettuati da una sola persona oltre la soglia fissata'], 'governance', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('top-funder-share', ['Part du principal financeur dans les ressources', 'Share of the main funder in total resources', 'Anteil des Hauptgeldgebers an den Gesamtmitteln', 'Peso del principal financiador en los recursos', 'Quota del principale finanziatore sulle risorse'], 'funding', U_PCT, 'HAUSSE', 'SEMESTRIEL')
b.kri('reports-overdue', ['Comptes rendus de financeurs en retard', 'Funder reports overdue', 'Überfällige Verwendungsnachweise an Geldgeber', 'Informes a financiadores atrasados', 'Rendicontazioni ai finanziatori in ritardo'], 'funding', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('donation-reconciliation', ['Dons sans reçu fiscal rapproché', 'Donations without a reconciled tax receipt', 'Spenden ohne abgeglichene Spendenbescheinigung', 'Donaciones sin recibo fiscal conciliado', 'Donazioni senza ricevuta fiscale riconciliata'], 'donations', U_NB, 'HAUSSE', 'TRIMESTRIEL')
b.kri('data-requests', ['Demandes d’exercice de droits sur des données traitées hors délai', 'Data-rights requests handled late', 'Verspätet bearbeitete Betroffenenanfragen', 'Solicitudes de ejercicio de derechos tramitadas fuera de plazo', 'Richieste di esercizio dei diritti gestite in ritardo'], 'members', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('volunteer-turnover', ['Départs de bénévoles clés sans transmission formalisée', 'Key volunteers leaving without formal handover', 'Weggänge von Schlüsselehrenamtlichen ohne formelle Übergabe', 'Salidas de voluntarios clave sin traspaso formalizado', 'Uscite di volontari chiave senza passaggio di consegne formalizzato'], 'volunteers', U_NB, 'HAUSSE', 'TRIMESTRIEL')
b.kri('statutory-delay', ['Retard des obligations statutaires (jours après la date prévue)', 'Delay in statutory obligations (days after the due date)', 'Verzug bei satzungsmäßigen Pflichten (Tage nach dem Fälligkeitstermin)', 'Retraso de las obligaciones estatutarias (días tras la fecha prevista)', 'Ritardo degli obblighi statutari (giorni dopo la data prevista)'], 'governance', U_DAYS, 'HAUSSE', 'TRIMESTRIEL')

b.audit('financial-control', ['Audit du contrôle financier et de la gestion des fonds', 'Audit of financial control and fund management', 'Audit der Finanzkontrolle und Mittelverwaltung', 'Auditoría del control financiero y de la gestión de fondos', 'Audit del controllo finanziario e della gestione dei fondi'], 'governance', ['treasurer-fraud', 'payment-diversion'], [
  ['Les pouvoirs bancaires sont définis et à jour', 'Banking powers are defined and up to date', 'Bankvollmachten sind festgelegt und aktuell', 'Los poderes bancarios están definidos y actualizados', 'I poteri bancari sono definiti e aggiornati'],
  ['Les paiements importants sont validés par deux personnes', 'Large payments are approved by two people', 'Größere Zahlungen werden von zwei Personen freigegeben', 'Los pagos importantes los validan dos personas', 'I pagamenti rilevanti sono autorizzati da due persone'],
  ['Les rapprochements sont revus par une personne indépendante du trésorier', 'Reconciliations are reviewed by someone independent of the treasurer', 'Abstimmungen werden von einer vom Kassenwart unabhängigen Person geprüft', 'Las conciliaciones las revisa una persona independiente del tesorero', 'Le riconciliazioni sono riviste da una persona indipendente dal tesoriere'],
  ['Le conseil d’administration reçoit un suivi financier régulier', 'The board receives regular financial reporting', 'Der Vorstand erhält regelmäßig Finanzberichte', 'El consejo recibe un seguimiento financiero periódico', 'Il consiglio riceve un monitoraggio finanziario regolare'],
])
b.audit('funding-compliance', ['Audit de la gestion et de la justification des subventions', 'Audit of grant management and justification', 'Audit der Zuschussverwaltung und -nachweise', 'Auditoría de la gestión y justificación de subvenciones', 'Audit della gestione e della rendicontazione delle sovvenzioni'], 'funding', ['grant-misuse', 'funder-dependence'], [
  ['Les conventions de financement sont suivies avec leurs conditions et échéances', 'Funding agreements are tracked with their conditions and deadlines', 'Förderverträge werden mit Auflagen und Fristen nachverfolgt', 'Los convenios de financiación se siguen con sus condiciones y plazos', 'Le convenzioni di finanziamento sono seguite con condizioni e scadenze'],
  ['Les dépenses imputées sont éligibles et justifiées', 'Expenses charged are eligible and justified', 'Angesetzte Ausgaben sind förderfähig und belegt', 'Los gastos imputados son elegibles y están justificados', 'Le spese imputate sono ammissibili e giustificate'],
  ['Les comptes rendus sont remis dans les délais', 'Reports are delivered on time', 'Verwendungsnachweise werden fristgerecht vorgelegt', 'Los informes se entregan en plazo', 'Le rendicontazioni sono consegnate nei termini'],
  ['La dépendance aux financeurs est suivie et un plan est prévu en cas de perte', 'Funder dependence is monitored and a plan exists in case of loss', 'Die Abhängigkeit von Geldgebern wird beobachtet und ein Plan für einen Verlust liegt vor', 'La dependencia de los financiadores se sigue y existe un plan en caso de pérdida', 'La dipendenza dai finanziatori è monitorata ed esiste un piano in caso di perdita'],
])
b.audit('member-data', ['Audit de la protection des données des adhérents, donateurs et bénéficiaires', 'Audit of member, donor and beneficiary data protection', 'Audit des Datenschutzes für Mitglieder, Spender und Begünstigte', 'Auditoría de la protección de datos de socios, donantes y beneficiarios', 'Audit della protezione dei dati di soci, donatori e beneficiari'], 'members', ['donor-data', 'sensitive-data'], [
  ['Les données collectées sont limitées à ce qui est nécessaire', 'Data collected is limited to what is necessary', 'Erhobene Daten sind auf das Erforderliche beschränkt', 'Los datos recopilados se limitan a lo necesario', 'I dati raccolti sono limitati allo stretto necessario'],
  ['Les accès sont limités par rôle et les outils partagés maîtrisés', 'Access is limited by role and shared tools are controlled', 'Zugriffe sind rollenbasiert begrenzt und gemeinsam genutzte Werkzeuge kontrolliert', 'Los accesos se limitan por rol y las herramientas compartidas están controladas', 'Gli accessi sono limitati per ruolo e gli strumenti condivisi sono controllati'],
  ['Les données sensibles bénéficient d’une protection renforcée', 'Sensitive data receives enhanced protection', 'Sensible Daten sind besonders geschützt', 'Los datos sensibles cuentan con protección reforzada', 'I dati sensibili beneficiano di una protezione rafforzata'],
  ['Les sous-traitants (hébergeur, logiciel de gestion) sont encadrés par contrat', 'Processors (host, management software) are covered by contract', 'Auftragsverarbeiter (Hoster, Verwaltungssoftware) sind vertraglich eingebunden', 'Los encargados del tratamiento (alojamiento, software de gestión) están amparados por contrato', 'I responsabili del trattamento (hosting, software gestionale) sono coperti da contratto'],
])
b.audit('volunteers-activities', ['Audit de l’encadrement des bénévoles et des activités', 'Audit of volunteer supervision and activities', 'Audit der Betreuung Ehrenamtlicher und der Aktivitäten', 'Auditoría de la coordinación de voluntarios y de las actividades', 'Audit del coordinamento dei volontari e delle attività'], 'volunteers', ['volunteer-harm', 'event-incident', 'key-volunteer'], [
  ['Les rôles et responsabilités des bénévoles sont définis', 'Volunteer roles and responsibilities are defined', 'Rollen und Verantwortlichkeiten Ehrenamtlicher sind festgelegt', 'Los roles y responsabilidades de los voluntarios están definidos', 'I ruoli e le responsabilità dei volontari sono definiti'],
  ['Les intervenants auprès de publics fragiles sont informés et contrôlés', 'Those working with vulnerable groups are informed and screened', 'Personen, die mit schutzbedürftigen Gruppen arbeiten, sind informiert und überprüft', 'Quienes intervienen con públicos frágiles están informados y controlados', 'Chi opera con pubblici fragili è informato e controllato'],
  ['Les assurances couvrent les activités et événements', 'Insurance covers activities and events', 'Versicherungen decken Aktivitäten und Veranstaltungen ab', 'Los seguros cubren las actividades y eventos', 'Le assicurazioni coprono attività ed eventi'],
  ['Les accès et savoir-faire critiques sont transmis lors des départs', 'Critical access and know-how are handed over on departures', 'Kritische Zugänge und Know-how werden bei Abgängen übergeben', 'Los accesos y conocimientos críticos se traspasan en las salidas', 'Gli accessi e il know-how critici sono trasmessi alle uscite'],
])

export const ASSOCIATIONS_PACK = b.pack
