/**
 * Pack « Immobilier / Construction » (catalogue 1.10) : promotion, construction, gestion locative et syndic, agences.
 * Suggestions à qualifier : jamais d'exécution, de seuil, de date, de résultat ni de conformité acquise. Les `references`
 * citent le texte d'origine sans reproduire d'exigence. Contenu à relire par un expert du secteur (statut « à relire »).
 */
import { sectorPack, U_NB, U_PCT, U_DAYS } from './catalogue-pack-builder'

const HOGUET = 'Loi n° 70-9 du 2 janvier 1970 (loi Hoguet) réglementant les conditions d’exercice des activités relatives à certaines opérations portant sur les immeubles et les fonds de commerce'
const LCBFT = 'Code monétaire et financier, livre V, titre VI (LCB-FT) — professionnels de l’immobilier'
const RGPD = 'Règlement (UE) 2016/679 (RGPD)'
const CCH = 'Code de la construction et de l’habitation'

const b = sectorPack('IMMOBILIER')

b.process('projects', ['Conduire les opérations de promotion et de construction', 'Run development and construction projects', 'Projektentwicklungen und Bauvorhaben steuern', 'Dirigir las operaciones de promoción y construcción', 'Gestire le operazioni di sviluppo e costruzione'])
b.process('sites', ['Piloter les chantiers et la sécurité', 'Manage construction sites and safety', 'Baustellen und Arbeitssicherheit steuern', 'Dirigir las obras y la seguridad', 'Gestire i cantieri e la sicurezza'])
b.process('transactions', ['Réaliser les transactions et gérer les fonds des clients', 'Carry out transactions and handle client funds', 'Transaktionen abwickeln und Kundengelder verwalten', 'Realizar las transacciones y gestionar los fondos de clientes', 'Eseguire le transazioni e gestire i fondi dei clienti'])
b.process('property-mgmt', ['Gérer les biens, les locataires et les copropriétés', 'Manage properties, tenants and co-owned buildings', 'Immobilien, Mieter und Eigentümergemeinschaften verwalten', 'Gestionar los inmuebles, los inquilinos y las comunidades de propietarios', 'Gestire immobili, inquilini e condomini'])
b.process('assets', ['Exploiter, entretenir et sécuriser les bâtiments', 'Operate, maintain and secure buildings', 'Gebäude betreiben, instand halten und sichern', 'Operar, mantener y proteger los edificios', 'Gestire, manutenere e proteggere gli edifici'])
b.process('subcontracting', ['Contractualiser et suivre les entreprises et sous-traitants', 'Contract and follow up contractors and subcontractors', 'Unternehmen und Nachunternehmer beauftragen und steuern', 'Contratar y seguir a las empresas y subcontratistas', 'Contrattualizzare e seguire imprese e subappaltatori'])

b.risk('client-funds', 1, ['Des fonds de clients, dépôts de garantie ou charges de copropriété sont détournés', 'Client funds, deposits or service charges are misappropriated', 'Kundengelder, Kautionen oder Nebenkosten werden veruntreut', 'Se desvían fondos de clientes, depósitos de garantía o gastos de comunidad', 'Fondi dei clienti, depositi cauzionali o spese condominiali vengono sottratti'], 'transactions')
b.risk('wire-fraud', 2, ['Un virement d’acquéreur est détourné par faux RIB lors d’une vente', 'A buyer’s transfer is diverted through fake bank details during a sale', 'Eine Käuferüberweisung wird durch gefälschte Kontodaten bei einem Verkauf umgeleitet', 'La transferencia de un comprador se desvía mediante un IBAN falso en una venta', 'Il bonifico di un acquirente viene dirottato con coordinate bancarie false durante una vendita'], 'transactions')
b.risk('aml-real-estate', 4, ['Une opération immobilière sert au blanchiment sans vigilance suffisante', 'A property transaction is used for money laundering without adequate vigilance', 'Eine Immobilientransaktion dient der Geldwäsche ohne ausreichende Sorgfalt', 'Una operación inmobiliaria se usa para blanquear capitales sin diligencia suficiente', 'Un’operazione immobiliare serve al riciclaggio senza adeguata vigilanza'], 'transactions')
b.risk('tenant-data', 4, ['Des dossiers de locataires ou d’acquéreurs sont divulgués', 'Tenant or buyer files are disclosed', 'Akten von Mietern oder Käufern werden offengelegt', 'Se divulgan expedientes de inquilinos o compradores', 'Vengono divulgati fascicoli di inquilini o acquirenti'], 'property-mgmt')
b.risk('site-accident', 3, ['Un accident grave survient sur un chantier', 'A serious accident occurs on a construction site', 'Auf einer Baustelle ereignet sich ein schwerer Unfall', 'Ocurre un accidente grave en una obra', 'Si verifica un grave incidente in un cantiere'], 'sites')
b.risk('delay-overrun', 7, ['Un retard ou un dépassement de coût compromet l’équilibre d’une opération', 'A delay or cost overrun undermines the viability of a project', 'Eine Verzögerung oder Kostenüberschreitung gefährdet die Wirtschaftlichkeit eines Projekts', 'Un retraso o sobrecoste compromete el equilibrio de una operación', 'Un ritardo o un superamento dei costi compromette l’equilibrio di un’operazione'], 'projects')
b.risk('subcontractor-failure', 7, ['Une entreprise ou un sous-traitant défaille en cours de chantier', 'A contractor or subcontractor fails during construction', 'Ein Unternehmen oder Nachunternehmer fällt während der Bauphase aus', 'Una empresa o subcontratista incumple durante la obra', 'Un’impresa o un subappaltatore viene meno durante il cantiere'], 'subcontracting')
b.risk('undeclared-labour', 7, ['Un sous-traitant emploie du personnel non déclaré sur un chantier', 'A subcontractor uses undeclared workers on a site', 'Ein Nachunternehmer beschäftigt nicht gemeldete Arbeitskräfte auf einer Baustelle', 'Un subcontratista emplea personal no declarado en una obra', 'Un subappaltatore impiega personale non dichiarato in un cantiere'], 'subcontracting')
b.risk('defect-liability', 7, ['Un désordre de construction engage la garantie après réception', 'A construction defect triggers liability after handover', 'Ein Baumangel löst die Gewährleistung nach der Abnahme aus', 'Un defecto de construcción activa la garantía tras la recepción', 'Un difetto di costruzione fa scattare la garanzia dopo la consegna'], 'projects')
b.risk('building-systems', 2, ['Un système technique de bâtiment connecté est compromis (accès, chauffage, ascenseurs)', 'A connected building system is compromised (access, heating, lifts)', 'Ein vernetztes Gebäudesystem wird kompromittiert (Zutritt, Heizung, Aufzüge)', 'Un sistema técnico conectado del edificio se ve comprometido (acceso, calefacción, ascensores)', 'Un sistema tecnico connesso dell’edificio viene compromesso (accessi, riscaldamento, ascensori)'], 'assets')
b.risk('compliance-diagnostics', 7, ['Une obligation technique de sécurité du bâtiment n’est pas respectée (contrôles périodiques)', 'A technical building-safety obligation is missed (periodic inspections)', 'Eine technische Gebäudesicherheitspflicht wird nicht erfüllt (wiederkehrende Prüfungen)', 'No se cumple una obligación técnica de seguridad del edificio (revisiones periódicas)', 'Un obbligo tecnico di sicurezza dell’edificio non viene rispettato (verifiche periodiche)'], 'assets')
b.risk('rent-collection', 7, ['Des loyers ou charges ne sont pas appelés ou encaissés correctement', 'Rents or charges are not called or collected correctly', 'Mieten oder Nebenkosten werden nicht korrekt angefordert oder vereinnahmt', 'Los alquileres o gastos no se reclaman o cobran correctamente', 'Canoni o spese non vengono richiamati o incassati correttamente'], 'property-mgmt')

b.control('escrow-reconciliation', ['Rapprochement des comptes de fonds clients avec les mandats', 'Reconciliation of client-fund accounts with mandates', 'Abgleich der Kundengeldkonten mit den Aufträgen', 'Conciliación de las cuentas de fondos de clientes con los mandatos', 'Riconciliazione dei conti dei fondi clienti con i mandati'], 'transactions', 'MENSUEL', 'DETECTIF', ['client-funds'], [HOGUET])
b.control('payment-dual', ['Double validation des virements sortant de comptes clients', 'Dual approval of transfers out of client accounts', 'Doppelte Freigabe von Überweisungen aus Kundenkonten', 'Doble validación de las transferencias desde cuentas de clientes', 'Doppia autorizzazione dei bonifici da conti clienti'], 'transactions', 'MENSUEL', 'PREVENTIF', ['client-funds', 'wire-fraud'])
b.control('bank-details-callback', ['Rappel de vérification de tout RIB transmis par courriel avant paiement', 'Call-back verification of any bank details sent by email before payment', 'Rückruf-Verifizierung jeder per E-Mail übermittelten Bankverbindung vor Zahlung', 'Verificación telefónica de todo IBAN enviado por correo antes del pago', 'Richiamata di verifica di ogni IBAN inviato per e-mail prima del pagamento'], 'transactions', 'MENSUEL', 'PREVENTIF', ['wire-fraud'])
b.control('client-due-diligence', ['Contrôle par échantillon de la connaissance des clients et de l’origine des fonds', 'Sample check of client knowledge and source of funds', 'Stichprobenprüfung von Kundenkenntnis und Mittelherkunft', 'Control por muestreo del conocimiento del cliente y del origen de los fondos', 'Controllo a campione della conoscenza del cliente e dell’origine dei fondi'], 'transactions', 'TRIMESTRIEL', 'DETECTIF', ['aml-real-estate'], [LCBFT])
b.control('aml-declarations', ['Revue des opérations atypiques et des déclarations de soupçon', 'Review of atypical transactions and suspicious-activity reports', 'Überprüfung atypischer Transaktionen und Verdachtsmeldungen', 'Revisión de las operaciones atípicas y de las declaraciones de sospecha', 'Revisione delle operazioni atipiche e delle segnalazioni di operazioni sospette'], 'transactions', 'TRIMESTRIEL', 'DETECTIF', ['aml-real-estate'], [LCBFT])
b.control('mandate-register', ['Vérification de la tenue du registre des mandats et de la numérotation', 'Check of the mandate register and numbering', 'Prüfung der Führung des Auftragsregisters und der Nummerierung', 'Verificación de la llevanza del registro de mandatos y su numeración', 'Verifica della tenuta del registro dei mandati e della numerazione'], 'transactions', 'SEMESTRIEL', 'DETECTIF', ['client-funds'], [HOGUET])
b.control('tenant-file-access', ['Revue des accès aux dossiers de locataires et d’acquéreurs', 'Review of access to tenant and buyer files', 'Überprüfung der Zugriffe auf Mieter- und Käuferakten', 'Revisión de los accesos a expedientes de inquilinos y compradores', 'Revisione degli accessi ai fascicoli di inquilini e acquirenti'], 'property-mgmt', 'TRIMESTRIEL', 'DETECTIF', ['tenant-data'], [RGPD])
b.control('retention-files', ['Contrôle des durées de conservation des dossiers de candidats non retenus', 'Check of retention periods for files of unsuccessful applicants', 'Prüfung der Aufbewahrungsfristen für Akten abgelehnter Bewerber', 'Control de los plazos de conservación de los expedientes de candidatos no seleccionados', 'Controllo dei tempi di conservazione dei fascicoli dei candidati non selezionati'], 'property-mgmt', 'ANNUEL', 'DETECTIF', ['tenant-data'], [RGPD])
b.control('rent-calls', ['Contrôle par échantillon des appels de loyers et de charges et des régularisations', 'Sample check of rent and charge calls and settlements', 'Stichprobenprüfung der Miet- und Nebenkostenanforderungen und Abrechnungen', 'Control por muestreo de las llamadas de alquileres y gastos y sus regularizaciones', 'Controllo a campione dei richiami di canoni e spese e dei conguagli'], 'property-mgmt', 'TRIMESTRIEL', 'DETECTIF', ['rent-collection'])
b.control('arrears-follow-up', ['Suivi des impayés et des relances', 'Follow-up of arrears and reminders', 'Nachverfolgung von Zahlungsrückständen und Mahnungen', 'Seguimiento de los impagos y reclamaciones', 'Monitoraggio delle morosità e dei solleciti'], 'property-mgmt', 'MENSUEL', 'DETECTIF', ['rent-collection'])
b.control('site-safety-visits', ['Visites de sécurité de chantier et suivi des écarts', 'Construction-site safety visits and gap follow-up', 'Sicherheitsbegehungen der Baustelle und Nachverfolgung von Abweichungen', 'Visitas de seguridad de obra y seguimiento de desviaciones', 'Visite di sicurezza di cantiere e monitoraggio degli scostamenti'], 'sites', 'MENSUEL', 'DETECTIF', ['site-accident'])
b.control('site-access-register', ['Contrôle du registre d’accès et des habilitations des intervenants en chantier', 'Check of the site-access register and workers’ authorisations', 'Prüfung des Zutrittsregisters und der Berechtigungen der Baustellenbeschäftigten', 'Control del registro de acceso y de las habilitaciones de los intervinientes en obra', 'Controllo del registro degli accessi e delle abilitazioni degli addetti di cantiere'], 'sites', 'MENSUEL', 'DETECTIF', ['site-accident', 'undeclared-labour'])
b.control('subcontractor-vigilance', ['Vérification des attestations de vigilance et d’assurance des sous-traitants', 'Check of subcontractors’ compliance and insurance certificates', 'Prüfung der Compliance- und Versicherungsnachweise der Nachunternehmer', 'Verificación de los certificados de cumplimiento y seguro de los subcontratistas', 'Verifica delle attestazioni di regolarità e assicurative dei subappaltatori'], 'subcontracting', 'TRIMESTRIEL', 'PREVENTIF', ['undeclared-labour', 'subcontractor-failure'])
b.control('contractor-solvency', ['Suivi de la situation financière des entreprises titulaires de lots importants', 'Follow-up of the financial situation of contractors holding major packages', 'Beobachtung der finanziellen Lage von Unternehmen mit wesentlichen Losen', 'Seguimiento de la situación financiera de las empresas adjudicatarias de lotes importantes', 'Monitoraggio della situazione finanziaria delle imprese titolari di lotti rilevanti'], 'subcontracting', 'TRIMESTRIEL', 'DETECTIF', ['subcontractor-failure'])
b.control('budget-schedule', ['Revue du budget et du planning des opérations (écarts et révisions)', 'Review of project budget and schedule (variances and revisions)', 'Überprüfung von Budget und Terminplan der Vorhaben (Abweichungen und Änderungen)', 'Revisión del presupuesto y del calendario de las operaciones (desviaciones y revisiones)', 'Revisione di budget e programma delle operazioni (scostamenti e revisioni)'], 'projects', 'MENSUEL', 'DETECTIF', ['delay-overrun'])
b.control('handover-reserves', ['Suivi des réserves à la réception et des désordres signalés', 'Follow-up of handover snags and reported defects', 'Nachverfolgung von Abnahmemängeln und gemeldeten Schäden', 'Seguimiento de las reservas en la recepción y de los desperfectos notificados', 'Monitoraggio delle riserve alla consegna e dei difetti segnalati'], 'projects', 'TRIMESTRIEL', 'DETECTIF', ['defect-liability'], [CCH])
b.control('periodic-inspections', ['Suivi du calendrier des contrôles réglementaires périodiques des bâtiments', 'Follow-up of the schedule of periodic regulatory building inspections', 'Überwachung des Terminplans wiederkehrender gesetzlicher Gebäudeprüfungen', 'Seguimiento del calendario de las revisiones reglamentarias periódicas de los edificios', 'Monitoraggio del calendario delle verifiche normative periodiche degli edifici'], 'assets', 'MENSUEL', 'PREVENTIF', ['compliance-diagnostics'], [CCH])
b.control('building-system-access', ['Revue des accès distants et des comptes des systèmes techniques de bâtiment', 'Review of remote access and accounts of building technical systems', 'Überprüfung der Fernzugriffe und Konten der technischen Gebäudesysteme', 'Revisión de los accesos remotos y cuentas de los sistemas técnicos de edificios', 'Revisione degli accessi remoti e degli account dei sistemi tecnici degli edifici'], 'assets', 'TRIMESTRIEL', 'DETECTIF', ['building-systems'])
b.control('insurance-cover', ['Revue des garanties d’assurance de construction et de responsabilité professionnelle', 'Review of construction and professional-liability insurance cover', 'Überprüfung der Bauversicherungen und Berufshaftpflichtdeckung', 'Revisión de las garantías de seguro de construcción y responsabilidad profesional', 'Revisione delle coperture assicurative di costruzione e responsabilità professionale'], 'projects', 'ANNUEL', 'PREVENTIF', ['defect-liability', 'site-accident'])

b.control('sales-documents', ['Contrôle par échantillon de la complétude des dossiers de vente et des diagnostics obligatoires', 'Sample check of completeness of sales files and mandatory surveys', 'Stichprobenprüfung der Vollständigkeit von Verkaufsakten und Pflichtgutachten', 'Control por muestreo de la integridad de los expedientes de venta y de los diagnósticos obligatorios', 'Controllo a campione della completezza dei fascicoli di vendita e delle diagnosi obbligatorie'], 'transactions', 'TRIMESTRIEL', 'DETECTIF', ['defect-liability', 'client-funds'], [CCH])

b.kri('fund-differences', ['Écarts de rapprochement des comptes de fonds clients', 'Client-fund account reconciliation differences', 'Abstimmungsdifferenzen der Kundengeldkonten', 'Diferencias de conciliación de las cuentas de fondos de clientes', 'Differenze di riconciliazione dei conti dei fondi clienti'], 'transactions', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('atypical-transactions', ['Opérations atypiques détectées', 'Atypical transactions detected', 'Erkannte atypische Transaktionen', 'Operaciones atípicas detectadas', 'Operazioni atipiche rilevate'], 'transactions', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('rent-arrears', ['Taux d’impayés de loyers et de charges', 'Rent and charge arrears rate', 'Quote der Miet- und Nebenkostenrückstände', 'Tasa de impago de alquileres y gastos', 'Tasso di morosità di canoni e spese'], 'property-mgmt', U_PCT, 'HAUSSE', 'MENSUEL')
b.kri('site-accidents', ['Accidents avec arrêt sur les chantiers', 'Lost-time accidents on construction sites', 'Unfälle mit Ausfallzeit auf Baustellen', 'Accidentes con baja en las obras', 'Infortuni con astensione sui cantieri'], 'sites', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('schedule-slip', ['Retard moyen des opérations par rapport au planning', 'Average project delay against schedule', 'Durchschnittliche Projektverzögerung gegenüber dem Terminplan', 'Retraso medio de las operaciones respecto al calendario', 'Ritardo medio delle operazioni rispetto al programma'], 'projects', U_DAYS, 'HAUSSE', 'MENSUEL')
b.kri('missing-certificates', ['Sous-traitants sans attestations à jour', 'Subcontractors without up-to-date certificates', 'Nachunternehmer ohne aktuelle Nachweise', 'Subcontratistas sin certificados actualizados', 'Subappaltatori senza attestazioni aggiornate'], 'subcontracting', U_NB, 'HAUSSE', 'TRIMESTRIEL')
b.kri('overdue-inspections', ['Contrôles périodiques de bâtiments échus', 'Overdue periodic building inspections', 'Überfällige wiederkehrende Gebäudeprüfungen', 'Revisiones periódicas de edificios vencidas', 'Verifiche periodiche degli edifici scadute'], 'assets', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('snag-backlog', ['Réserves de réception non levées au-delà du délai prévu', 'Handover snags not cleared beyond the due date', 'Abnahmemängel, die über die Frist hinaus nicht behoben sind', 'Reservas de recepción no levantadas fuera del plazo previsto', 'Riserve di consegna non sanate oltre il termine previsto'], 'projects', U_NB, 'HAUSSE', 'MENSUEL')

b.audit('client-funds', ['Audit de la gestion des fonds de clients', 'Audit of client-fund management', 'Audit der Verwaltung von Kundengeldern', 'Auditoría de la gestión de fondos de clientes', 'Audit della gestione dei fondi dei clienti'], 'transactions', ['client-funds', 'wire-fraud'], [
  ['Les fonds de clients sont séparés des fonds propres et rapprochés régulièrement', 'Client funds are separated from own funds and reconciled regularly', 'Kundengelder sind von Eigenmitteln getrennt und werden regelmäßig abgeglichen', 'Los fondos de clientes están separados de los propios y se concilian regularmente', 'I fondi dei clienti sono separati dai fondi propri e riconciliati regolarmente'],
  ['Les sorties de fonds sont autorisées selon les délégations', 'Outgoing funds are authorised according to delegations', 'Mittelabflüsse werden gemäß den Vollmachten genehmigt', 'Las salidas de fondos se autorizan según las delegaciones', 'Le uscite di fondi sono autorizzate secondo le deleghe'],
  ['Les changements de coordonnées bancaires sont vérifiés par un canal indépendant', 'Bank-detail changes are verified through an independent channel', 'Änderungen von Bankverbindungen werden über einen unabhängigen Kanal geprüft', 'Los cambios de datos bancarios se verifican por un canal independiente', 'Le modifiche delle coordinate bancarie sono verificate tramite un canale indipendente'],
  ['Les écarts sont expliqués et résolus dans des délais définis', 'Differences are explained and resolved within defined timeframes', 'Differenzen werden innerhalb festgelegter Fristen erklärt und geklärt', 'Las diferencias se explican y resuelven en plazos definidos', 'Le differenze sono spiegate e risolte entro termini definiti'],
])
b.audit('aml-programme', ['Audit du dispositif de lutte contre le blanchiment', 'Audit of the anti-money-laundering framework', 'Audit des Geldwäschepräventionssystems', 'Auditoría del dispositivo contra el blanqueo de capitales', 'Audit del dispositivo antiriciclaggio'], 'transactions', ['aml-real-estate'], [
  ['Une classification des risques clients et opérations est établie et revue', 'A client and transaction risk classification is established and reviewed', 'Eine Risikoklassifizierung von Kunden und Transaktionen besteht und wird überprüft', 'Existe una clasificación de riesgos de clientes y operaciones, revisada periódicamente', 'Esiste una classificazione dei rischi di clienti e operazioni, rivista periodicamente'],
  ['Les vérifications d’identité et d’origine des fonds sont documentées', 'Identity and source-of-funds checks are documented', 'Identitäts- und Mittelherkunftsprüfungen sind dokumentiert', 'Las verificaciones de identidad y origen de fondos están documentadas', 'Le verifiche di identità e origine dei fondi sono documentate'],
  ['Les opérations atypiques sont analysées et les déclarations tracées', 'Atypical transactions are analysed and reports traced', 'Atypische Transaktionen werden analysiert und Meldungen dokumentiert', 'Las operaciones atípicas se analizan y las declaraciones quedan trazadas', 'Le operazioni atipiche sono analizzate e le segnalazioni tracciate'],
  ['Les collaborateurs sont formés et le dispositif est contrôlé', 'Staff are trained and the framework is monitored', 'Beschäftigte sind geschult und das System wird überwacht', 'El personal está formado y el dispositivo se controla', 'Il personale è formato e il dispositivo è controllato'],
])
b.audit('site-safety', ['Audit de la sécurité des chantiers et de la sous-traitance', 'Audit of site safety and subcontracting', 'Audit der Baustellensicherheit und Nachunternehmerkette', 'Auditoría de la seguridad de las obras y de la subcontratación', 'Audit della sicurezza dei cantieri e del subappalto'], 'sites', ['site-accident', 'undeclared-labour', 'subcontractor-failure'], [
  ['Un plan de prévention est établi pour chaque chantier', 'A prevention plan is drawn up for each site', 'Für jede Baustelle liegt ein Präventionsplan vor', 'Se establece un plan de prevención para cada obra', 'Per ogni cantiere è redatto un piano di prevenzione'],
  ['Les intervenants sont enregistrés et habilités', 'Workers are registered and authorised', 'Beschäftigte sind erfasst und berechtigt', 'Los intervinientes están registrados y habilitados', 'Gli addetti sono registrati e abilitati'],
  ['Les sous-traitants sont vérifiés avant leur intervention', 'Subcontractors are verified before they start', 'Nachunternehmer werden vor ihrem Einsatz geprüft', 'Los subcontratistas se verifican antes de intervenir', 'I subappaltatori sono verificati prima dell’intervento'],
  ['Les accidents et presque-accidents sont analysés et suivis', 'Accidents and near-misses are analysed and followed up', 'Unfälle und Beinahe-Unfälle werden analysiert und nachverfolgt', 'Los accidentes y casi accidentes se analizan y se les da seguimiento', 'Gli infortuni e i quasi-incidenti sono analizzati e monitorati'],
])
b.audit('property-data', ['Audit de la protection des données de locataires et d’acquéreurs', 'Audit of tenant and buyer data protection', 'Audit des Schutzes von Mieter- und Käuferdaten', 'Auditoría de la protección de datos de inquilinos y compradores', 'Audit della protezione dei dati di inquilini e acquirenti'], 'property-mgmt', ['tenant-data'], [
  ['Seules les pièces nécessaires sont demandées aux candidats', 'Only necessary documents are requested from applicants', 'Von Bewerbern werden nur erforderliche Unterlagen verlangt', 'Solo se piden a los candidatos los documentos necesarios', 'Ai candidati sono richiesti solo i documenti necessari'],
  ['Les accès aux dossiers sont limités et tracés', 'Access to files is limited and logged', 'Zugriffe auf Akten sind begrenzt und protokolliert', 'Los accesos a los expedientes son limitados y quedan registrados', 'Gli accessi ai fascicoli sono limitati e tracciati'],
  ['Les dossiers sont purgés à l’issue de la durée de conservation', 'Files are purged at the end of the retention period', 'Akten werden nach Ablauf der Aufbewahrungsfrist gelöscht', 'Los expedientes se eliminan al término del plazo de conservación', 'I fascicoli sono eliminati al termine del tempo di conservazione'],
  ['Les prestataires (syndic, diagnostiqueurs, logiciels) sont encadrés par contrat', 'Providers (managing agents, surveyors, software) are covered by contract', 'Dienstleister (Verwalter, Gutachter, Software) sind vertraglich eingebunden', 'Los proveedores (administrador, técnicos, software) están amparados por contrato', 'I fornitori (amministratore, tecnici, software) sono coperti da contratto'],
])

export const IMMOBILIER_PACK = b.pack
