/**
 * Approfondissement des packs « Banque / Finance » et « Assurance / Mutuelle » (catalogue 1.10) : risques, indicateurs et
 * missions d'audit complémentaires du pack 1.9 (mêmes processus). Suggestions à qualifier : jamais d'exécution, de seuil, de date,
 * de résultat ni de conformité acquise. Les `references` citent le texte d'origine sans reproduire d'exigence. Contenu à relire
 * par un expert du secteur (statut « à relire ») ; les seuils et périodicités sont des points de départ à adapter à la taille de l'entité.
 */
import { sectorPack, U_NB, U_PCT } from './catalogue-pack-builder'


// ════════════════════════════ Banque / Finance ══════════════════════════════
const fin = sectorPack('FINANCE')
fin.risk('model-risk', 7, ['Un modèle (notation, scoring, valorisation) est utilisé hors de son domaine de validité', 'A model (rating, scoring, valuation) is used outside its validity domain', 'Ein Modell (Rating, Scoring, Bewertung) wird außerhalb seines Gültigkeitsbereichs verwendet', 'Un modelo (calificación, scoring, valoración) se usa fuera de su dominio de validez', 'Un modello (rating, scoring, valutazione) viene usato fuori dal suo dominio di validità'], 'credit')
fin.risk('insider-trading', 1, ['Une information privilégiée ou confidentielle est utilisée ou divulguée', 'Inside or confidential information is used or disclosed', 'Eine Insider- oder vertrauliche Information wird genutzt oder weitergegeben', 'Se utiliza o divulga información privilegiada o confidencial', 'Un’informazione privilegiata o riservata viene utilizzata o divulgata'], 'markets')
fin.risk('fraudulent-onboarding', 1, ['Un compte est ouvert avec une identité ou des justificatifs falsifiés', 'An account is opened with a falsified identity or documents', 'Ein Konto wird mit gefälschter Identität oder gefälschten Nachweisen eröffnet', 'Se abre una cuenta con una identidad o justificantes falsificados', 'Un conto viene aperto con un’identità o documenti falsificati'], 'accounts')
fin.risk('instant-payment-fraud', 2, ['Un virement instantané frauduleux est exécuté avant toute possibilité de rappel', 'A fraudulent instant payment is executed before any recall is possible', 'Eine betrügerische Sofortüberweisung wird ausgeführt, bevor ein Rückruf möglich ist', 'Se ejecuta una transferencia instantánea fraudulenta antes de poder recuperarla', 'Un bonifico istantaneo fraudolento viene eseguito prima che sia possibile richiamarlo'], 'payments')
fin.kri('fraud-losses', ['Pertes brutes liées à la fraude (paiements, cartes, comptes)', 'Gross fraud losses (payments, cards, accounts)', 'Bruttoverluste aus Betrug (Zahlungen, Karten, Konten)', 'Pérdidas brutas por fraude (pagos, tarjetas, cuentas)', 'Perdite lorde da frode (pagamenti, carte, conti)'], 'payments', ['montant', 'amount', 'Betrag', 'importe', 'importo'], 'HAUSSE', 'MENSUEL')
fin.kri('aml-backlog', ['Alertes LCB-FT en attente au-delà du délai de traitement', 'AML alerts pending beyond the handling time', 'GwG-Warnungen, die über die Bearbeitungsfrist hinaus offen sind', 'Alertas de PBC-FT pendientes más allá del plazo de tratamiento', 'Alert antiriciclaggio in attesa oltre il termine di trattamento'], 'aml', U_NB, 'HAUSSE', 'MENSUEL')
fin.kri('kyc-overdue', ['Dossiers clients dont la revue périodique est échue', 'Customer files with overdue periodic review', 'Kundenakten mit überfälliger periodischer Überprüfung', 'Expedientes de clientes con revisión periódica vencida', 'Fascicoli clienti con revisione periodica scaduta'], 'aml', U_PCT, 'HAUSSE', 'MENSUEL')
fin.kri('complaints-delay', ['Réclamations clients traitées hors délai', 'Customer complaints handled late', 'Verspätet bearbeitete Kundenbeschwerden', 'Reclamaciones de clientes tramitadas fuera de plazo', 'Reclami dei clienti gestiti in ritardo'], 'compliance', U_PCT, 'HAUSSE', 'MENSUEL')
fin.kri('reporting-errors', ['Anomalies relevées sur les états réglementaires avant dépôt', 'Anomalies found in regulatory returns before filing', 'Vor der Einreichung festgestellte Auffälligkeiten in aufsichtlichen Meldungen', 'Anomalías detectadas en los estados reglamentarios antes de su presentación', 'Anomalie rilevate nei prospetti regolamentari prima del deposito'], 'reporting', U_NB, 'HAUSSE', 'TRIMESTRIEL')
fin.kri('ict-incidents', ['Incidents TIC majeurs ou significatifs détectés', 'Major or significant ICT incidents detected', 'Erkannte größere oder erhebliche IKT-Vorfälle', 'Incidentes TIC graves o significativos detectados', 'Incidenti ICT gravi o significativi rilevati'], 'ict', U_NB, 'HAUSSE', 'MENSUEL')
fin.kri('critical-provider-concentration', ['Fonctions critiques reposant sur un seul prestataire TIC', 'Critical functions relying on a single ICT provider', 'Kritische Funktionen, die von einem einzigen IKT-Dienstleister abhängen', 'Funciones críticas que dependen de un único proveedor TIC', 'Funzioni critiche che dipendono da un unico fornitore ICT'], 'ict', U_NB, 'HAUSSE', 'SEMESTRIEL')
fin.audit('aml-framework', ['Audit du dispositif de lutte contre le blanchiment et le financement du terrorisme', 'Audit of the anti-money-laundering and counter-terrorist-financing framework', 'Audit des Systems zur Bekämpfung von Geldwäsche und Terrorismusfinanzierung', 'Auditoría del dispositivo de prevención del blanqueo y de la financiación del terrorismo', 'Audit del dispositivo antiriciclaggio e di contrasto al finanziamento del terrorismo'], 'aml', ['aml', 'sanction-screening', 'fraudulent-onboarding'], [
  ['La classification des risques est établie et revue', 'The risk classification is established and reviewed', 'Die Risikoklassifizierung ist erstellt und wird überprüft', 'La clasificación de riesgos está establecida y se revisa', 'La classificazione dei rischi è stabilita e rivista'],
  ['Les diligences d’entrée en relation et de revue sont documentées', 'Onboarding and periodic-review due diligence is documented', 'Sorgfaltspflichten bei Aufnahme und Überprüfung sind dokumentiert', 'Las diligencias de alta y de revisión están documentadas', 'Le verifiche di avvio e di revisione sono documentate'],
  ['Les alertes sont traitées dans les délais et les déclarations tracées', 'Alerts are handled on time and reports are traced', 'Warnungen werden fristgerecht bearbeitet und Meldungen dokumentiert', 'Las alertas se tratan en plazo y las declaraciones quedan trazadas', 'Gli alert sono gestiti nei termini e le segnalazioni tracciate'],
  ['Le filtrage des sanctions et le gel des avoirs sont efficaces et testés', 'Sanctions screening and asset freezing are effective and tested', 'Sanktionsscreening und Vermögenseinfrieren sind wirksam und getestet', 'El filtrado de sanciones y la congelación de activos son eficaces y se prueban', 'Lo screening delle sanzioni e il congelamento dei beni sono efficaci e testati'],
])
fin.audit('ict-third-party', ['Audit de la gestion des risques liés aux prestataires de services TIC', 'Audit of ICT third-party risk management', 'Audit des Managements von Risiken durch IKT-Drittdienstleister', 'Auditoría de la gestión de riesgos de los proveedores de servicios TIC', 'Audit della gestione dei rischi dei fornitori di servizi ICT'], 'ict', ['channel-outage', 'payment-routing'], [
  ['Le registre d’informations sur les accords contractuels est complet et à jour', 'The register of information on contractual arrangements is complete and up to date', 'Das Informationsregister zu vertraglichen Vereinbarungen ist vollständig und aktuell', 'El registro de información sobre acuerdos contractuales está completo y actualizado', 'Il registro delle informazioni sugli accordi contrattuali è completo e aggiornato'],
  ['Les fonctions critiques ou importantes et leurs prestataires sont identifiés', 'Critical or important functions and their providers are identified', 'Kritische oder wichtige Funktionen und ihre Dienstleister sind identifiziert', 'Las funciones críticas o importantes y sus proveedores están identificados', 'Le funzioni critiche o importanti e i loro fornitori sono identificati'],
  ['Les contrats contiennent les clauses exigées et des stratégies de sortie', 'Contracts contain required clauses and exit strategies', 'Verträge enthalten die geforderten Klauseln und Exit-Strategien', 'Los contratos incluyen las cláusulas exigidas y estrategias de salida', 'I contratti contengono le clausole richieste e strategie di uscita'],
  ['La concentration auprès d’un prestataire est évaluée', 'Concentration with a provider is assessed', 'Die Konzentration auf einen Dienstleister wird bewertet', 'Se evalúa la concentración en un proveedor', 'La concentrazione su un fornitore è valutata'],
])
fin.audit('credit-process', ['Audit du processus d’octroi et de suivi du crédit', 'Audit of the credit granting and monitoring process', 'Audit des Kreditvergabe- und Überwachungsprozesses', 'Auditoría del proceso de concesión y seguimiento del crédito', 'Audit del processo di concessione e monitoraggio del credito'], 'credit', ['credit-data', 'model-risk'], [
  ['Les délégations d’octroi sont définies et respectées', 'Granting authorities are defined and respected', 'Kreditvergabevollmachten sind festgelegt und werden eingehalten', 'Las delegaciones de concesión están definidas y se respetan', 'Le deleghe di concessione sono definite e rispettate'],
  ['Les dossiers sont complets et les garanties valorisées', 'Files are complete and collateral valued', 'Akten sind vollständig und Sicherheiten bewertet', 'Los expedientes están completos y las garantías valoradas', 'I fascicoli sono completi e le garanzie valutate'],
  ['Les limites et dépassements sont suivis', 'Limits and breaches are monitored', 'Limits und Überschreitungen werden überwacht', 'Los límites y excesos se supervisan', 'I limiti e gli sconfinamenti sono monitorati'],
  ['Les modèles de notation sont validés et utilisés dans leur domaine', 'Rating models are validated and used within their domain', 'Ratingmodelle sind validiert und werden im Gültigkeitsbereich eingesetzt', 'Los modelos de calificación están validados y se usan en su dominio', 'I modelli di rating sono validati e usati nel loro dominio'],
])
fin.audit('customer-protection', ['Audit de la protection de la clientèle et du traitement des réclamations', 'Audit of customer protection and complaint handling', 'Audit des Kundenschutzes und der Beschwerdebearbeitung', 'Auditoría de la protección de la clientela y del tratamiento de reclamaciones', 'Audit della tutela della clientela e della gestione dei reclami'], 'compliance', ['core.risk.mis-selling'], [
  ['L’adéquation des produits aux clients est vérifiée et documentée', 'Product suitability for customers is checked and documented', 'Die Eignung von Produkten für Kunden wird geprüft und dokumentiert', 'La adecuación de los productos a los clientes se verifica y documenta', 'L’adeguatezza dei prodotti ai clienti è verificata e documentata'],
  ['Les communications commerciales sont validées avant diffusion', 'Marketing communications are approved before release', 'Werbliche Kommunikation wird vor Veröffentlichung freigegeben', 'Las comunicaciones comerciales se validan antes de su difusión', 'Le comunicazioni commerciali sono approvate prima della diffusione'],
  ['Les réclamations sont enregistrées, traitées dans les délais et analysées', 'Complaints are recorded, handled on time and analysed', 'Beschwerden werden erfasst, fristgerecht bearbeitet und ausgewertet', 'Las reclamaciones se registran, tramitan en plazo y analizan', 'I reclami sono registrati, gestiti nei termini e analizzati'],
  ['Les enseignements sont remontés à la gouvernance des produits', 'Lessons are fed back to product governance', 'Erkenntnisse fließen in die Produktgovernance zurück', 'Las enseñanzas se trasladan a la gobernanza de productos', 'Gli insegnamenti sono riportati alla governance dei prodotti'],
])

// ════════════════════════════ Assurance / Mutuelle ══════════════════════════
const ass = sectorPack('ASSURANCE')
ass.risk('reinsurance-gap', 7, ['Une couverture de réassurance ne répond pas au sinistre attendu (exclusion, plafond, défaillance)', 'A reinsurance cover does not respond to the expected loss (exclusion, limit, default)', 'Ein Rückversicherungsschutz greift beim erwarteten Schaden nicht (Ausschluss, Limit, Ausfall)', 'Una cobertura de reaseguro no responde al siniestro esperado (exclusión, límite, impago)', 'Una copertura di riassicurazione non risponde al sinistro atteso (esclusione, massimale, insolvenza)'], 'reserving')
ass.risk('lapse-wave', 7, ['Une vague de résiliations ou de rachats dégrade la rentabilité ou la liquidité', 'A wave of lapses or surrenders degrades profitability or liquidity', 'Eine Welle von Kündigungen oder Rückkäufen belastet Rentabilität oder Liquidität', 'Una ola de resoluciones o rescates deteriora la rentabilidad o la liquidez', 'Un’ondata di disdette o riscatti peggiora la redditività o la liquidità'], 'policy')
ass.risk('distribution-conduct', 4, ['Un distributeur commercialise un produit à des clients hors de la cible prévue', 'A distributor sells a product to customers outside the intended target', 'Ein Vertriebspartner verkauft ein Produkt an Kunden außerhalb der vorgesehenen Zielgruppe', 'Un distribuidor comercializa un producto a clientes fuera del objetivo previsto', 'Un distributore vende un prodotto a clienti al di fuori del target previsto'], 'brokers')
ass.risk('investment-limit', 7, ['Une limite de placement ou de concentration des actifs est dépassée', 'An investment or asset-concentration limit is breached', 'Ein Anlage- oder Konzentrationslimit wird überschritten', 'Se supera un límite de inversión o de concentración de activos', 'Un limite di investimento o di concentrazione degli attivi viene superato'], 'investments')
ass.risk('benefit-payment-error', 7, ['Une prestation est versée à un mauvais bénéficiaire ou pour un montant erroné', 'A benefit is paid to the wrong beneficiary or in a wrong amount', 'Eine Leistung wird an den falschen Begünstigten oder in falscher Höhe gezahlt', 'Una prestación se abona a un beneficiario equivocado o por un importe erróneo', 'Una prestazione viene pagata a un beneficiario sbagliato o per un importo errato'], 'members')
ass.kri('claims-fraud-suspected', ['Dossiers de sinistre présentant des indicateurs de fraude', 'Claim files showing fraud indicators', 'Schadenakten mit Betrugsindikatoren', 'Expedientes de siniestro con indicadores de fraude', 'Pratiche di sinistro con indicatori di frode'], 'claims', U_NB, 'HAUSSE', 'MENSUEL')
ass.kri('lapse-rate', ['Taux de résiliation ou de rachat', 'Lapse or surrender rate', 'Kündigungs- oder Rückkaufquote', 'Tasa de resolución o rescate', 'Tasso di disdetta o riscatto'], 'policy', U_PCT, 'HAUSSE', 'MENSUEL')
ass.kri('complaints-delay', ['Réclamations d’assurés traitées hors délai', 'Policyholder complaints handled late', 'Verspätet bearbeitete Beschwerden von Versicherten', 'Reclamaciones de asegurados tramitadas fuera de plazo', 'Reclami degli assicurati gestiti in ritardo'], 'policy', U_PCT, 'HAUSSE', 'MENSUEL')
ass.kri('solvency-watch', ['Écart entre le ratio de couverture et le seuil d’alerte interne', 'Gap between the coverage ratio and the internal alert level', 'Abstand zwischen Bedeckungsquote und interner Warnschwelle', 'Distancia entre el ratio de cobertura y el umbral de alerta interno', 'Distanza tra l’indice di copertura e la soglia di allerta interna'], 'orsa', U_PCT, 'BAISSE', 'TRIMESTRIEL')
ass.kri('investment-breaches', ['Dépassements de limites de placement non résolus', 'Unresolved investment-limit breaches', 'Nicht behobene Überschreitungen von Anlagelimits', 'Excesos de límites de inversión sin resolver', 'Sforamenti dei limiti di investimento non risolti'], 'investments', U_NB, 'HAUSSE', 'MENSUEL')
ass.kri('payment-returns', ['Prestations rejetées ou retournées par la banque', 'Benefit payments rejected or returned by the bank', 'Von der Bank abgelehnte oder zurückgegebene Leistungszahlungen', 'Prestaciones rechazadas o devueltas por el banco', 'Prestazioni respinte o restituite dalla banca'], 'members', U_NB, 'HAUSSE', 'MENSUEL')
ass.audit('underwriting-pricing', ['Audit de la souscription et de la tarification', 'Audit of underwriting and pricing', 'Audit von Zeichnung und Tarifierung', 'Auditoría de la suscripción y tarificación', 'Audit di sottoscrizione e tariffazione'], 'underwrite', ['pricing', 'policy-change', 'broker-data'], [
  ['Les délégations de souscription sont définies et respectées', 'Underwriting authorities are defined and respected', 'Zeichnungsvollmachten sind festgelegt und werden eingehalten', 'Las delegaciones de suscripción están definidas y se respetan', 'Le deleghe di sottoscrizione sono definite e rispettate'],
  ['Les paramètres tarifaires sont validés et leurs changements tracés', 'Pricing parameters are validated and changes traced', 'Tarifparameter sind validiert und Änderungen nachvollziehbar', 'Los parámetros tarifarios se validan y sus cambios quedan trazados', 'I parametri tariffari sono validati e le modifiche tracciate'],
  ['La qualité des données issues des distributeurs est contrôlée', 'The quality of data from distributors is checked', 'Die Qualität der Daten von Vertriebspartnern wird geprüft', 'Se controla la calidad de los datos procedentes de distribuidores', 'La qualità dei dati dei distributori è controllata'],
  ['Les affaires nouvelles font l’objet d’un contrôle par échantillon', 'New business is checked on a sample basis', 'Neugeschäft wird stichprobenweise geprüft', 'El negocio nuevo se controla por muestreo', 'Il nuovo business è controllato a campione'],
])
ass.audit('reserving-reinsurance', ['Audit du provisionnement et de la réassurance', 'Audit of reserving and reinsurance', 'Audit von Reservierung und Rückversicherung', 'Auditoría del provisionamiento y del reaseguro', 'Audit di riservazione e riassicurazione'], 'reserving', ['reserve', 'reinsurance-gap'], [
  ['Les données et hypothèses actuarielles sont documentées et validées', 'Actuarial data and assumptions are documented and validated', 'Aktuarielle Daten und Annahmen sind dokumentiert und validiert', 'Los datos e hipótesis actuariales están documentados y validados', 'I dati e le ipotesi attuariali sono documentati e validati'],
  ['Les provisions sont rétrotestées', 'Reserves are back-tested', 'Rückstellungen werden rückgetestet', 'Las provisiones se contrastan retrospectivamente', 'Gli accantonamenti sono sottoposti a back-testing'],
  ['Les programmes de réassurance sont revus au regard du profil de risque', 'Reinsurance programmes are reviewed against the risk profile', 'Rückversicherungsprogramme werden anhand des Risikoprofils überprüft', 'Los programas de reaseguro se revisan frente al perfil de riesgo', 'I programmi di riassicurazione sono rivisti rispetto al profilo di rischio'],
  ['Les créances sur les réassureurs sont suivies', 'Reinsurance recoverables are monitored', 'Forderungen gegenüber Rückversicherern werden überwacht', 'Los créditos frente a reaseguradores se supervisan', 'I crediti verso i riassicuratori sono monitorati'],
])
ass.audit('distribution', ['Audit de la distribution et du devoir de conseil', 'Audit of distribution and advice duty', 'Audit des Vertriebs und der Beratungspflicht', 'Auditoría de la distribución y del deber de asesoramiento', 'Audit della distribuzione e del dovere di consulenza'], 'brokers', ['distribution-conduct', 'broker-data'], [
  ['Le marché cible de chaque produit est défini et connu des distributeurs', 'The target market of each product is defined and known to distributors', 'Der Zielmarkt jedes Produkts ist festgelegt und den Vertriebspartnern bekannt', 'El mercado objetivo de cada producto está definido y es conocido por los distribuidores', 'Il mercato target di ogni prodotto è definito e noto ai distributori'],
  ['Les conventions de distribution encadrent conseil, données et rémunération', 'Distribution agreements cover advice, data and remuneration', 'Vertriebsvereinbarungen regeln Beratung, Daten und Vergütung', 'Los convenios de distribución regulan asesoramiento, datos y remuneración', 'Le convenzioni di distribuzione disciplinano consulenza, dati e remunerazione'],
  ['L’adéquation de la vente est contrôlée par échantillon', 'Suitability of sales is checked on a sample basis', 'Die Eignung des Verkaufs wird stichprobenweise geprüft', 'La adecuación de la venta se controla por muestreo', 'L’adeguatezza della vendita è controllata a campione'],
  ['Les réclamations remontent à la gouvernance des produits', 'Complaints are fed back to product governance', 'Beschwerden fließen in die Produktgovernance zurück', 'Las reclamaciones se trasladan a la gobernanza de productos', 'I reclami sono riportati alla governance dei prodotti'],
])
ass.audit('members-benefits', ['Audit de la gestion des adhérents et du paiement des prestations', 'Audit of member management and benefit payment', 'Audit der Mitgliederverwaltung und der Leistungszahlung', 'Auditoría de la gestión de socios y del pago de prestaciones', 'Audit della gestione dei soci e del pagamento delle prestazioni'], 'members', ['benefit-payment-error', 'customer-data'], [
  ['Les droits des adhérents et des bénéficiaires sont à jour', 'Members’ and beneficiaries’ entitlements are up to date', 'Ansprüche von Mitgliedern und Begünstigten sind aktuell', 'Los derechos de socios y beneficiarios están actualizados', 'I diritti di soci e beneficiari sono aggiornati'],
  ['Les prestations sont contrôlées avant paiement et rapprochées après', 'Benefits are checked before payment and reconciled after', 'Leistungen werden vor Zahlung geprüft und danach abgeglichen', 'Las prestaciones se controlan antes del pago y se concilian después', 'Le prestazioni sono controllate prima del pagamento e riconciliate dopo'],
  ['Les modifications de coordonnées bancaires sont vérifiées', 'Bank-detail changes are verified', 'Änderungen von Bankverbindungen werden geprüft', 'Los cambios de datos bancarios se verifican', 'Le modifiche delle coordinate bancarie sono verificate'],
  ['Les données de santé ne sont accessibles qu’aux fonctions habilitées', 'Health data is accessible only to authorised functions', 'Gesundheitsdaten sind nur befugten Funktionen zugänglich', 'Los datos de salud solo son accesibles a las funciones habilitadas', 'I dati sanitari sono accessibili solo alle funzioni autorizzate'],
])

export const DEEPEN_D_PACKS = [fin.pack, ass.pack]
