/**
 * Approfondissement des packs « Administration publique », « Énergie / Utilities » et « Industrie » (catalogue 1.10).
 * Complète les éléments existants (mêmes processus) : suggestions à qualifier, jamais d'exécution, de seuil, de date, de résultat
 * ni de conformité acquise. Les `references` citent le texte d'origine sans reproduire d'exigence. Contenu à relire par un expert du secteur.
 */
import { sectorPack, U_NB, U_PCT, U_DAYS } from './catalogue-pack-builder'

const RGS = 'Référentiel général de sécurité (RGS)'
const RGPD = 'Règlement (UE) 2016/679 (RGPD)'
const CCP = 'Code de la commande publique'
const NIS2 = 'Directive (UE) 2022/2555 (NIS 2)'
const IEC62443 = 'IEC 62443 (cybersécurité des systèmes d’automatisation et de contrôle industriels)'
const SEVESO = 'Directive 2012/18/UE (Seveso III)'

// ════════════════════════════ Administration publique ═══════════════════════
const pub = sectorPack('PUBLIC')
pub.risk('procurement-error', 7, ['Un marché public est attribué ou exécuté en méconnaissance des règles de la commande publique', 'A public contract is awarded or performed in breach of procurement rules', 'Ein öffentlicher Auftrag wird unter Verstoß gegen das Vergaberecht vergeben oder ausgeführt', 'Un contrato público se adjudica o ejecuta incumpliendo las reglas de contratación pública', 'Un appalto pubblico viene aggiudicato o eseguito in violazione delle norme sugli appalti'], 'grants')
pub.risk('conflict-interest', 1, ['Un agent ou élu participe à une décision malgré un conflit d’intérêts', 'An official or elected member takes part in a decision despite a conflict of interest', 'Ein Bediensteter oder Mandatsträger wirkt trotz Interessenkonflikts an einer Entscheidung mit', 'Un empleado o electo participa en una decisión pese a un conflicto de intereses', 'Un funzionario o eletto partecipa a una decisione nonostante un conflitto di interessi'], 'grants')
pub.risk('identity-fraud', 1, ['Une prestation est obtenue frauduleusement avec une identité usurpée', 'A benefit is fraudulently obtained with a stolen identity', 'Eine Leistung wird mit gestohlener Identität betrügerisch erlangt', 'Una prestación se obtiene fraudulentamente con una identidad usurpada', 'Una prestazione viene ottenuta fraudolentemente con un’identità rubata'], 'identity')
pub.risk('ransomware-local', 2, ['Un rançongiciel paralyse les services de la collectivité (état civil, paie, finances)', 'Ransomware paralyses the authority’s services (civil registry, payroll, finance)', 'Ransomware legt Dienste der Behörde lahm (Standesamt, Gehaltsabrechnung, Finanzen)', 'Un ransomware paraliza los servicios de la administración (registro civil, nóminas, finanzas)', 'Un ransomware paralizza i servizi dell’ente (stato civile, paghe, finanze)'], 'local')
pub.risk('records-loss', 6, ['Des archives publiques sont perdues ou ne sont plus lisibles', 'Public records are lost or no longer readable', 'Öffentliche Archivalien gehen verloren oder sind nicht mehr lesbar', 'Se pierden archivos públicos o dejan de ser legibles', 'Gli archivi pubblici vengono persi o non sono più leggibili'], 'local')
pub.control('conflict-declarations', ['Revue des déclarations d’intérêts avant les décisions d’attribution', 'Review of declarations of interest before award decisions', 'Überprüfung der Interessenerklärungen vor Vergabeentscheidungen', 'Revisión de las declaraciones de intereses antes de las decisiones de adjudicación', 'Revisione delle dichiarazioni di interessi prima delle decisioni di aggiudicazione'], 'grants', 'ANNUEL', 'PREVENTIF', ['conflict-interest'])
pub.control('procurement-sample', ['Contrôle par échantillon des procédures de marchés (publicité, mise en concurrence, avenants)', 'Sample check of procurement procedures (publicity, competition, amendments)', 'Stichprobenprüfung von Vergabeverfahren (Bekanntmachung, Wettbewerb, Nachträge)', 'Control por muestreo de los procedimientos de contratación (publicidad, concurrencia, modificaciones)', 'Controllo a campione delle procedure di appalto (pubblicità, concorrenza, varianti)'], 'grants', 'TRIMESTRIEL', 'DETECTIF', ['procurement-error'], [CCP])
pub.control('thresholds-splitting', ['Détection du fractionnement de commandes sous les seuils de procédure', 'Detection of order splitting below procedure thresholds', 'Erkennung der Aufteilung von Bestellungen unterhalb der Verfahrensschwellen', 'Detección del fraccionamiento de pedidos por debajo de los umbrales de procedimiento', 'Rilevamento del frazionamento degli ordini sotto le soglie di procedura'], 'grants', 'TRIMESTRIEL', 'DETECTIF', ['procurement-error'], [CCP])
pub.control('grant-follow-up', ['Suivi des justificatifs d’emploi des subventions versées', 'Follow-up of supporting documents for grants paid', 'Nachverfolgung der Verwendungsnachweise gezahlter Zuschüsse', 'Seguimiento de los justificantes de empleo de las subvenciones abonadas', 'Monitoraggio dei giustificativi di impiego delle sovvenzioni erogate'], 'grants', 'TRIMESTRIEL', 'DETECTIF', ['grant-error'])
pub.control('identity-proofing', ['Contrôle par échantillon des vérifications d’identité avant attribution d’une prestation', 'Sample check of identity verification before granting a benefit', 'Stichprobenprüfung der Identitätsprüfung vor Gewährung einer Leistung', 'Control por muestreo de las verificaciones de identidad antes de conceder una prestación', 'Controllo a campione delle verifiche d’identità prima dell’erogazione di una prestazione'], 'identity', 'TRIMESTRIEL', 'DETECTIF', ['identity-fraud', 'identity'], [RGS])
pub.control('case-file-access', ['Revue des accès aux dossiers d’usagers par les agents', 'Review of staff access to citizens’ case files', 'Überprüfung der Zugriffe von Bediensteten auf Bürgerakten', 'Revisión de los accesos de los agentes a los expedientes de usuarios', 'Revisione degli accessi del personale ai fascicoli dei cittadini'], 'citizens', 'TRIMESTRIEL', 'DETECTIF', ['case-leak'], [RGPD])
pub.control('privacy-impact', ['Vérification de l’analyse d’impact avant tout nouveau traitement de données d’usagers', 'Check of the impact assessment before any new processing of citizens’ data', 'Prüfung der Folgenabschätzung vor jeder neuen Verarbeitung von Bürgerdaten', 'Verificación de la evaluación de impacto antes de todo nuevo tratamiento de datos de usuarios', 'Verifica della valutazione d’impatto prima di ogni nuovo trattamento di dati dei cittadini'], 'citizens', 'ANNUEL', 'PREVENTIF', ['case-leak', 'open-data'], [RGPD])
pub.control('data-accuracy', ['Contrôle par échantillon de l’exactitude des données fondant des décisions individuelles', 'Sample check of accuracy of data underlying individual decisions', 'Stichprobenprüfung der Richtigkeit von Daten für Einzelentscheidungen', 'Control por muestreo de la exactitud de los datos que fundamentan decisiones individuales', 'Controllo a campione dell’esattezza dei dati su cui si fondano le decisioni individuali'], 'citizens', 'SEMESTRIEL', 'DETECTIF', ['stale-data'])
pub.control('portal-failover', ['Test de continuité du portail usagers et des téléservices essentiels', 'Continuity test of the citizen portal and essential e-services', 'Kontinuitätstest des Bürgerportals und wesentlicher E-Services', 'Prueba de continuidad del portal de usuarios y de los servicios electrónicos esenciales', 'Test di continuità del portale dei cittadini e dei servizi digitali essenziali'], 'citizens', 'SEMESTRIEL', 'DETECTIF', ['portal-outage'])
pub.control('restore-civil-registry', ['Test de restauration des applications d’état civil, paie et finances', 'Restoration test of civil-registry, payroll and finance applications', 'Wiederherstellungstest der Anwendungen für Standesamt, Gehalt und Finanzen', 'Prueba de restauración de las aplicaciones de registro civil, nóminas y finanzas', 'Test di ripristino delle applicazioni di stato civile, paghe e finanze'], 'local', 'SEMESTRIEL', 'DETECTIF', ['ransomware-local', 'local-outage'])
pub.control('homologation', ['Suivi de l’homologation de sécurité des téléservices', 'Follow-up of security accreditation of e-services', 'Nachverfolgung der Sicherheitsfreigabe der E-Services', 'Seguimiento de la homologación de seguridad de los servicios electrónicos', 'Monitoraggio dell’omologazione di sicurezza dei servizi digitali'], 'citizens', 'ANNUEL', 'PREVENTIF', ['portal-outage', 'case-leak'], [RGS])
pub.control('privileged-admin', ['Revue des comptes d’administration et des accès des prestataires informatiques', 'Review of administrator accounts and IT contractors’ access', 'Überprüfung der Administratorkonten und der Zugriffe von IT-Dienstleistern', 'Revisión de las cuentas de administración y de los accesos de proveedores informáticos', 'Revisione degli account di amministrazione e degli accessi dei fornitori informatici'], 'local', 'TRIMESTRIEL', 'DETECTIF', ['ransomware-local'])
pub.control('archives-readability', ['Vérification de la lisibilité et de la conservation des archives numériques', 'Check of readability and preservation of digital archives', 'Prüfung der Lesbarkeit und Aufbewahrung digitaler Archive', 'Verificación de la legibilidad y conservación de los archivos digitales', 'Verifica della leggibilità e della conservazione degli archivi digitali'], 'local', 'ANNUEL', 'DETECTIF', ['records-loss'])
pub.control('elected-officials-awareness', ['Sensibilisation des élus et directeurs aux risques cyber (hameçonnage, usurpation)', 'Awareness of elected members and directors on cyber risks (phishing, impersonation)', 'Sensibilisierung von Mandatsträgern und Leitungen für Cyberrisiken (Phishing, Identitätsmissbrauch)', 'Sensibilización de electos y directivos sobre ciberriesgos (phishing, suplantación)', 'Sensibilizzazione di eletti e dirigenti sui rischi cyber (phishing, furto d’identità)'], 'local', 'ANNUEL', 'PREVENTIF', ['ransomware-local'])
pub.control('open-data-registry', ['Tenue du registre des jeux de données ouverts avec revue de leur caractère anonyme', 'Maintenance of the open-dataset register with review of anonymity', 'Führung des Registers offener Datensätze mit Prüfung der Anonymität', 'Mantenimiento del registro de conjuntos de datos abiertos con revisión de su carácter anónimo', 'Tenuta del registro dei dataset aperti con revisione dell’anonimato'], 'citizens', 'SEMESTRIEL', 'PREVENTIF', ['open-data'])
pub.control('payment-chain', ['Contrôle par échantillon de la chaîne ordonnateur-comptable avant paiement', 'Sample check of the authorising officer–accountant chain before payment', 'Stichprobenprüfung der Kette Anordnungsbefugter–Kassenverwalter vor Zahlung', 'Control por muestreo de la cadena ordenador-contable antes del pago', 'Controllo a campione della catena ordinatore-contabile prima del pagamento'], 'grants', 'MENSUEL', 'PREVENTIF', ['grant-error', 'procurement-error'])
pub.control('local-event-continuity', ['Exercice de continuité des services essentiels (état civil, urgences sociales)', 'Continuity exercise for essential services (civil registry, social emergencies)', 'Kontinuitätsübung für wesentliche Dienste (Standesamt, soziale Notfälle)', 'Ejercicio de continuidad de los servicios esenciales (registro civil, urgencias sociales)', 'Esercitazione di continuità dei servizi essenziali (stato civile, emergenze sociali)'], 'local', 'ANNUEL', 'PREVENTIF', ['local-outage', 'ransomware-local'])
pub.control('mfa-agents', ['Vérification de l’authentification renforcée des agents accédant aux applications sensibles', 'Check of strong authentication for staff accessing sensitive applications', 'Prüfung der starken Authentifizierung von Bediensteten mit Zugriff auf sensible Anwendungen', 'Verificación de la autenticación reforzada de los agentes que acceden a aplicaciones sensibles', 'Verifica dell’autenticazione forte del personale che accede ad applicazioni sensibili'], 'citizens', 'TRIMESTRIEL', 'DETECTIF', ['case-leak', 'ransomware-local'], [RGS])
pub.kri('procurement-exceptions', ['Marchés avec avenant ou dérogation à la procédure', 'Contracts with amendment or procedural derogation', 'Aufträge mit Nachtrag oder Verfahrensabweichung', 'Contratos con modificación o excepción al procedimiento', 'Appalti con variante o deroga alla procedura'], 'grants', U_NB, 'HAUSSE', 'TRIMESTRIEL')
pub.kri('case-access-anomalies', ['Consultations anormales de dossiers d’usagers signalées', 'Abnormal consultations of citizens’ files reported', 'Gemeldete auffällige Abrufe von Bürgerakten', 'Consultas anómalas de expedientes de usuarios señaladas', 'Consultazioni anomale di fascicoli dei cittadini segnalate'], 'citizens', U_NB, 'HAUSSE', 'MENSUEL')
pub.kri('processing-time', ['Délai moyen de traitement des demandes d’usagers', 'Average processing time of citizen requests', 'Durchschnittliche Bearbeitungszeit von Bürgeranträgen', 'Plazo medio de tramitación de las solicitudes de usuarios', 'Tempo medio di trattamento delle richieste dei cittadini'], 'citizens', U_DAYS, 'HAUSSE', 'MENSUEL')
pub.kri('identity-fraud-cases', ['Cas de fraude à l’identité détectés', 'Identity-fraud cases detected', 'Erkannte Fälle von Identitätsbetrug', 'Casos de fraude de identidad detectados', 'Casi di frode d’identità rilevati'], 'identity', U_NB, 'HAUSSE', 'MENSUEL')
pub.kri('restore-age', ['Ancienneté du dernier test de restauration des applications critiques', 'Age of the last restoration test of critical applications', 'Alter des letzten Wiederherstellungstests kritischer Anwendungen', 'Antigüedad de la última prueba de restauración de aplicaciones críticas', 'Anzianità dell’ultimo test di ripristino delle applicazioni critiche'], 'local', U_DAYS, 'HAUSSE', 'MENSUEL')
pub.kri('unaccepted-grants', ['Subventions sans justificatif d’emploi reçu dans le délai', 'Grants without a supporting report received on time', 'Zuschüsse ohne fristgerecht eingegangenen Verwendungsnachweis', 'Subvenciones sin justificante de empleo recibido en plazo', 'Sovvenzioni senza giustificativo di impiego ricevuto nei termini'], 'grants', U_NB, 'HAUSSE', 'TRIMESTRIEL')
pub.audit('procurement', ['Audit des achats et de la commande publique', 'Audit of purchasing and public procurement', 'Audit von Einkauf und öffentlicher Auftragsvergabe', 'Auditoría de las compras y de la contratación pública', 'Audit degli acquisti e degli appalti pubblici'], 'grants', ['procurement-error', 'conflict-interest'], [
  ['Les besoins sont définis et les procédures adaptées aux seuils', 'Needs are defined and procedures fit the thresholds', 'Bedarfe sind definiert und Verfahren den Schwellenwerten angepasst', 'Las necesidades están definidas y los procedimientos se adaptan a los umbrales', 'I fabbisogni sono definiti e le procedure adeguate alle soglie'],
  ['Les décisions d’attribution sont motivées et tracées', 'Award decisions are reasoned and recorded', 'Zuschlagsentscheidungen sind begründet und dokumentiert', 'Las decisiones de adjudicación están motivadas y registradas', 'Le decisioni di aggiudicazione sono motivate e tracciate'],
  ['Les conflits d’intérêts sont déclarés et gérés', 'Conflicts of interest are declared and managed', 'Interessenkonflikte werden angezeigt und gehandhabt', 'Los conflictos de intereses se declaran y gestionan', 'I conflitti di interessi sono dichiarati e gestiti'],
  ['L’exécution et les avenants sont suivis', 'Performance and amendments are monitored', 'Ausführung und Nachträge werden überwacht', 'La ejecución y las modificaciones se supervisan', 'L’esecuzione e le varianti sono monitorate'],
])
pub.audit('citizen-data', ['Audit de la protection des données des usagers', 'Audit of citizens’ data protection', 'Audit des Schutzes von Bürgerdaten', 'Auditoría de la protección de datos de los usuarios', 'Audit della protezione dei dati dei cittadini'], 'citizens', ['case-leak', 'open-data', 'stale-data'], [
  ['Le registre des traitements est tenu à jour', 'The record of processing is kept up to date', 'Das Verzeichnis der Verarbeitungstätigkeiten ist aktuell', 'El registro de tratamientos está actualizado', 'Il registro dei trattamenti è aggiornato'],
  ['Les accès des agents sont limités aux besoins et tracés', 'Staff access is limited to needs and logged', 'Zugriffe von Bediensteten sind bedarfsgerecht begrenzt und protokolliert', 'Los accesos de los agentes se limitan a las necesidades y quedan registrados', 'Gli accessi del personale sono limitati alle necessità e tracciati'],
  ['La publication de données ouvertes passe par une revue d’anonymisation', 'Open-data publication goes through an anonymisation review', 'Die Veröffentlichung offener Daten durchläuft eine Anonymisierungsprüfung', 'La publicación de datos abiertos pasa por una revisión de anonimización', 'La pubblicazione di dati aperti passa da una revisione di anonimizzazione'],
  ['Les demandes d’exercice de droits sont traitées dans les délais', 'Data-rights requests are handled on time', 'Betroffenenanfragen werden fristgerecht bearbeitet', 'Las solicitudes de ejercicio de derechos se tramitan en plazo', 'Le richieste di esercizio dei diritti sono gestite nei termini'],
])
pub.audit('local-continuity', ['Audit de la continuité des services publics essentiels', 'Audit of essential public-service continuity', 'Audit der Kontinuität wesentlicher öffentlicher Dienste', 'Auditoría de la continuidad de los servicios públicos esenciales', 'Audit della continuità dei servizi pubblici essenziali'], 'local', ['local-outage', 'ransomware-local', 'portal-outage'], [
  ['Les services essentiels et leurs applications sont identifiés', 'Essential services and their applications are identified', 'Wesentliche Dienste und ihre Anwendungen sind identifiziert', 'Los servicios esenciales y sus aplicaciones están identificados', 'I servizi essenziali e le relative applicazioni sono identificati'],
  ['Les sauvegardes sont isolées et la restauration testée', 'Backups are isolated and restoration tested', 'Sicherungen sind isoliert und die Wiederherstellung getestet', 'Las copias están aisladas y la restauración se prueba', 'I backup sono isolati e il ripristino testato'],
  ['Un mode dégradé existe pour les services aux usagers', 'A fallback mode exists for citizen services', 'Für Bürgerdienste besteht ein Notbetrieb', 'Existe un modo degradado para los servicios a los usuarios', 'Esiste una modalità degradata per i servizi ai cittadini'],
  ['La gestion de crise implique élus et direction', 'Crisis management involves elected members and management', 'Das Krisenmanagement bezieht Mandatsträger und Leitung ein', 'La gestión de crisis implica a electos y dirección', 'La gestione delle crisi coinvolge eletti e direzione'],
])

// ════════════════════════════ Énergie / Utilities ═══════════════════════════
const en = sectorPack('ENERGIE')
en.risk('physical-attack', 5, ['Une intrusion ou un sabotage physique touche un site ou un poste critique', 'A physical intrusion or sabotage hits a critical site or substation', 'Ein Einbruch oder Sabotage trifft einen kritischen Standort oder ein Umspannwerk', 'Una intrusión o sabotaje físico afecta a un sitio o subestación crítica', 'Un’intrusione o un sabotaggio fisico colpisce un sito o una sottostazione critica'], 'operate')
en.risk('supply-chain-ot', 2, ['Un équipement ou logiciel de conduite livré est compromis dans la chaîne d’approvisionnement', 'Control equipment or software is compromised in the supply chain', 'Gelieferte Leit­technik oder Software wird in der Lieferkette kompromittiert', 'Un equipo o software de control entregado se ve comprometido en la cadena de suministro', 'Un’apparecchiatura o un software di controllo viene compromesso nella catena di fornitura'], 'operate')
en.risk('market-error', 7, ['Une erreur d’offre ou de nomination sur les marchés de l’énergie génère des pertes ou des pénalités', 'A bidding or nomination error on energy markets causes losses or penalties', 'Ein Gebots- oder Nominierungsfehler an Energiemärkten verursacht Verluste oder Strafen', 'Un error de oferta o nominación en los mercados de la energía provoca pérdidas o penalizaciones', 'Un errore di offerta o nomina sui mercati dell’energia causa perdite o penali'], 'dispatch')
en.risk('environmental-release', 5, ['Un rejet ou un incident environnemental survient sur une installation', 'An environmental release or incident occurs at a facility', 'An einer Anlage kommt es zu einem Umweltvorfall oder einer Freisetzung', 'Se produce un vertido o incidente ambiental en una instalación', 'Si verifica uno sversamento o un incidente ambientale in un impianto'], 'field')
en.risk('critical-spares', 6, ['Une pièce critique n’est pas disponible lors d’une avarie majeure', 'A critical spare is unavailable during a major failure', 'Ein kritisches Ersatzteil ist bei einer größeren Störung nicht verfügbar', 'Una pieza crítica no está disponible durante una avería importante', 'Un ricambio critico non è disponibile durante un guasto importante'], 'operate')
en.control('ot-segmentation', ['Vérification du cloisonnement entre réseau de conduite et réseaux de bureautique ou tiers', 'Check of segregation between the control network and office or third-party networks', 'Prüfung der Trennung zwischen Leitnetz und Büro- oder Drittnetzen', 'Verificación de la segregación entre la red de control y las redes ofimáticas o de terceros', 'Verifica della segregazione tra la rete di controllo e le reti d’ufficio o di terzi'], 'operate', 'TRIMESTRIEL', 'DETECTIF', ['scada', 'contractor-access'], [NIS2])
en.control('ot-inventory', ['Rapprochement de l’inventaire des équipements de conduite avec le réseau', 'Reconciliation of control-equipment inventory with the network', 'Abgleich des Inventars der Leittechnik mit dem Netz', 'Conciliación del inventario de equipos de control con la red', 'Riconciliazione dell’inventario delle apparecchiature di controllo con la rete'], 'operate', 'SEMESTRIEL', 'DETECTIF', ['scada'])
en.control('ot-logs', ['Revue des alertes et journaux des systèmes de conduite', 'Review of alerts and logs of control systems', 'Überprüfung der Warnungen und Protokolle der Leitsysteme', 'Revisión de las alertas y registros de los sistemas de control', 'Revisione degli alert e dei log dei sistemi di controllo'], 'operate', 'MENSUEL', 'DETECTIF', ['scada'])
en.control('ot-backup', ['Test de restauration des configurations et projets des automates et systèmes de conduite', 'Restoration test of PLC and control-system configurations', 'Wiederherstellungstest der Konfigurationen von SPS und Leitsystemen', 'Prueba de restauración de las configuraciones de autómatas y sistemas de control', 'Test di ripristino delle configurazioni di PLC e sistemi di controllo'], 'operate', 'SEMESTRIEL', 'DETECTIF', ['scada', 'outage'])
en.control('vendor-remote-sessions', ['Revue des sessions de télémaintenance de fournisseurs sur les installations', 'Review of vendor remote-maintenance sessions on facilities', 'Überprüfung der Fernwartungssitzungen von Lieferanten an Anlagen', 'Revisión de las sesiones de telemantenimiento de proveedores en instalaciones', 'Revisione delle sessioni di teleassistenza dei fornitori sugli impianti'], 'operate', 'MENSUEL', 'DETECTIF', ['contractor-access', 'scada'])
en.control('ot-supplier-security', ['Vérification des exigences de sécurité dans les marchés d’équipements de conduite', 'Check of security requirements in control-equipment contracts', 'Prüfung der Sicherheitsanforderungen in Beschaffungsverträgen für Leittechnik', 'Verificación de los requisitos de seguridad en los contratos de equipos de control', 'Verifica dei requisiti di sicurezza nei contratti per apparecchiature di controllo'], 'operate', 'ANNUEL', 'PREVENTIF', ['supply-chain-ot'], [NIS2])
en.control('site-physical-access', ['Revue des accès physiques aux postes et sites critiques', 'Review of physical access to critical substations and sites', 'Überprüfung des physischen Zutritts zu kritischen Umspannwerken und Standorten', 'Revisión de los accesos físicos a subestaciones y sitios críticos', 'Revisione degli accessi fisici a sottostazioni e siti critici'], 'operate', 'TRIMESTRIEL', 'DETECTIF', ['physical-attack'])
en.control('intrusion-alarms', ['Test des alarmes d’intrusion et de la levée de doute', 'Test of intrusion alarms and alarm verification', 'Test der Einbruchmeldeanlagen und der Alarmverifikation', 'Prueba de las alarmas de intrusión y de la verificación de alarmas', 'Test degli allarmi antintrusione e della verifica degli allarmi'], 'operate', 'SEMESTRIEL', 'DETECTIF', ['physical-attack'])
en.control('critical-spares-stock', ['Revue du stock de pièces critiques et des délais de réapprovisionnement', 'Review of critical-spares stock and replenishment lead times', 'Überprüfung des Bestands kritischer Ersatzteile und der Wiederbeschaffungszeiten', 'Revisión del stock de piezas críticas y de los plazos de reaprovisionamiento', 'Revisione delle scorte di ricambi critici e dei tempi di rifornimento'], 'operate', 'TRIMESTRIEL', 'DETECTIF', ['critical-spares', 'outage'])
en.control('black-start', ['Exercice de reprise de service après défaillance majeure (démarrage à froid, mode dégradé)', 'Service restoration exercise after a major failure (black start, degraded mode)', 'Wiederversorgungsübung nach schwerer Störung (Schwarzstart, Notbetrieb)', 'Ejercicio de reposición del servicio tras un fallo mayor (arranque en negro, modo degradado)', 'Esercitazione di ripristino del servizio dopo un guasto maggiore (black start, modalità degradata)'], 'operate', 'ANNUEL', 'PREVENTIF', ['outage'])
en.control('forecast-review', ['Revue de la qualité des prévisions de production et de consommation', 'Review of the quality of production and consumption forecasts', 'Überprüfung der Qualität der Erzeugungs- und Verbrauchsprognosen', 'Revisión de la calidad de las previsiones de producción y consumo', 'Revisione della qualità delle previsioni di produzione e consumo'], 'dispatch', 'MENSUEL', 'DETECTIF', ['imbalance'])
en.control('market-limits', ['Contrôle des limites d’engagement et des nominations avant clôture des marchés', 'Check of exposure limits and nominations before market gate closure', 'Prüfung der Positionslimits und Nominierungen vor Handelsschluss', 'Control de los límites de exposición y de las nominaciones antes del cierre de mercado', 'Controllo dei limiti di esposizione e delle nomine prima della chiusura del mercato'], 'dispatch', 'MENSUEL', 'PREVENTIF', ['market-error'])
en.control('imbalance-settlement', ['Rapprochement des écarts et pénalités d’équilibrage avec les nominations', 'Reconciliation of imbalance charges and penalties with nominations', 'Abgleich von Ausgleichsenergie und Pönalen mit den Nominierungen', 'Conciliación de los desvíos y penalizaciones de equilibrio con las nominaciones', 'Riconciliazione degli sbilanciamenti e delle penali con le nomine'], 'dispatch', 'MENSUEL', 'DETECTIF', ['imbalance', 'market-error'])
en.control('lockout-tagout', ['Contrôle par échantillon des consignations avant intervention sur ouvrage', 'Sample check of lock-out/tag-out before work on equipment', 'Stichprobenprüfung der Freischaltung vor Arbeiten an Anlagen', 'Control por muestreo de los enclavamientos antes de intervenir en instalaciones', 'Controllo a campione dei blocchi di sicurezza prima di interventi sugli impianti'], 'field', 'MENSUEL', 'PREVENTIF', ['field-safety'])
en.control('contractor-qualification', ['Vérification des habilitations et qualifications des intervenants terrain', 'Check of qualifications and authorisations of field workers', 'Prüfung der Qualifikationen und Berechtigungen von Einsatzkräften vor Ort', 'Verificación de las habilitaciones y cualificaciones de los intervinientes de campo', 'Verifica delle abilitazioni e qualifiche degli addetti sul campo'], 'field', 'TRIMESTRIEL', 'PREVENTIF', ['field-safety', 'contractor-access'])
en.control('environment-monitoring', ['Revue des mesures et déclarations environnementales des installations', 'Review of environmental measurements and declarations of facilities', 'Überprüfung der Umweltmessungen und -meldungen der Anlagen', 'Revisión de las mediciones y declaraciones ambientales de las instalaciones', 'Revisione delle misurazioni e dichiarazioni ambientali degli impianti'], 'field', 'TRIMESTRIEL', 'DETECTIF', ['environmental-release'])
en.control('meter-data-sample', ['Contrôle par échantillon des relevés de compteurs et des corrections de facturation', 'Sample check of meter readings and billing corrections', 'Stichprobenprüfung von Zählerständen und Abrechnungskorrekturen', 'Control por muestreo de las lecturas de contadores y de las correcciones de facturación', 'Controllo a campione delle letture dei contatori e delle correzioni di fatturazione'], 'metering', 'MENSUEL', 'DETECTIF', ['metering-error'])
en.control('consumption-data-access', ['Revue des accès aux données de consommation individuelles', 'Review of access to individual consumption data', 'Überprüfung der Zugriffe auf individuelle Verbrauchsdaten', 'Revisión de los accesos a los datos de consumo individuales', 'Revisione degli accessi ai dati di consumo individuali'], 'metering', 'TRIMESTRIEL', 'DETECTIF', ['customer-data'], [RGPD])
en.kri('ot-incidents', ['Événements de sécurité détectés sur les systèmes de conduite', 'Security events detected on control systems', 'Auf Leitsystemen erkannte Sicherheitsereignisse', 'Eventos de seguridad detectados en los sistemas de control', 'Eventi di sicurezza rilevati sui sistemi di controllo'], 'operate', U_NB, 'HAUSSE', 'MENSUEL')
en.kri('vendor-sessions', ['Sessions de télémaintenance non rattachées à une demande approuvée', 'Remote-maintenance sessions not linked to an approved request', 'Fernwartungssitzungen ohne zugehörige genehmigte Anforderung', 'Sesiones de telemantenimiento no vinculadas a una solicitud aprobada', 'Sessioni di teleassistenza non collegate a una richiesta approvata'], 'operate', U_NB, 'HAUSSE', 'MENSUEL')
en.kri('imbalance-cost', ['Écart moyen entre prévision et réalisé', 'Average gap between forecast and actual', 'Durchschnittliche Abweichung zwischen Prognose und Ist', 'Desviación media entre previsión y real', 'Scostamento medio tra previsione e consuntivo'], 'dispatch', U_PCT, 'HAUSSE', 'MENSUEL')
en.kri('field-accidents', ['Accidents et presque-accidents lors d’interventions terrain', 'Accidents and near-misses during field work', 'Unfälle und Beinaheunfälle bei Einsätzen vor Ort', 'Accidentes y casi accidentes en intervenciones de campo', 'Infortuni e quasi-incidenti durante gli interventi sul campo'], 'field', U_NB, 'HAUSSE', 'MENSUEL')
en.kri('meter-corrections', ['Corrections de facturation liées à des relevés erronés', 'Billing corrections linked to wrong meter readings', 'Abrechnungskorrekturen aufgrund fehlerhafter Zählerstände', 'Correcciones de facturación por lecturas erróneas', 'Correzioni di fatturazione dovute a letture errate'], 'metering', U_NB, 'HAUSSE', 'MENSUEL')
en.kri('spares-coverage', ['Pièces critiques sous le stock minimal défini', 'Critical spares below the defined minimum stock', 'Kritische Ersatzteile unter dem festgelegten Mindestbestand', 'Piezas críticas por debajo del stock mínimo definido', 'Ricambi critici sotto la scorta minima definita'], 'operate', U_NB, 'HAUSSE', 'MENSUEL')
en.audit('ot-security', ['Audit de la sécurité des systèmes de conduite', 'Audit of control-system security', 'Audit der Sicherheit der Leitsysteme', 'Auditoría de la seguridad de los sistemas de control', 'Audit della sicurezza dei sistemi di controllo'], 'operate', ['scada', 'supply-chain-ot', 'contractor-access'], [
  ['L’inventaire des équipements de conduite est complet et rapproché', 'The control-equipment inventory is complete and reconciled', 'Das Leittechnik-Inventar ist vollständig und abgeglichen', 'El inventario de equipos de control está completo y conciliado', 'L’inventario delle apparecchiature di controllo è completo e riconciliato'],
  ['Les réseaux de conduite sont cloisonnés des autres réseaux', 'Control networks are segregated from other networks', 'Leitnetze sind von anderen Netzen getrennt', 'Las redes de control están segregadas de las demás redes', 'Le reti di controllo sono segregate dalle altre reti'],
  ['Les accès distants et des tiers sont autorisés, limités et journalisés', 'Remote and third-party access is authorised, limited and logged', 'Fern- und Drittzugriffe sind genehmigt, begrenzt und protokolliert', 'Los accesos remotos y de terceros están autorizados, limitados y registrados', 'Gli accessi remoti e di terzi sono autorizzati, limitati e registrati'],
  ['Les sauvegardes de configuration sont testées', 'Configuration backups are tested', 'Konfigurationssicherungen werden getestet', 'Las copias de configuración se prueban', 'I backup di configurazione sono testati'],
])
en.audit('field-safety', ['Audit de la sécurité des interventions terrain', 'Audit of field-work safety', 'Audit der Sicherheit von Einsätzen vor Ort', 'Auditoría de la seguridad de las intervenciones de campo', 'Audit della sicurezza degli interventi sul campo'], 'field', ['field-safety', 'environmental-release'], [
  ['Les consignations sont appliquées avant intervention', 'Lock-out procedures are applied before work', 'Freischaltverfahren werden vor Arbeiten angewendet', 'Los enclavamientos se aplican antes de intervenir', 'I blocchi di sicurezza sono applicati prima dell’intervento'],
  ['Les intervenants sont qualifiés et habilités', 'Workers are qualified and authorised', 'Einsatzkräfte sind qualifiziert und berechtigt', 'Los intervinientes están cualificados y habilitados', 'Gli addetti sono qualificati e abilitati'],
  ['Les accidents et presque-accidents sont analysés et suivis', 'Accidents and near-misses are analysed and followed up', 'Unfälle und Beinaheunfälle werden analysiert und nachverfolgt', 'Los accidentes y casi accidentes se analizan y se les da seguimiento', 'Gli infortuni e i quasi-incidenti sono analizzati e monitorati'],
  ['Les risques environnementaux des installations sont maîtrisés', 'Environmental risks of facilities are controlled', 'Umweltrisiken der Anlagen sind beherrscht', 'Los riesgos ambientales de las instalaciones están controlados', 'I rischi ambientali degli impianti sono sotto controllo'],
])
en.audit('market-balance', ['Audit de l’équilibrage et des opérations de marché', 'Audit of balancing and market operations', 'Audit von Bilanzausgleich und Marktgeschäften', 'Auditoría del equilibrio y de las operaciones de mercado', 'Audit del bilanciamento e delle operazioni di mercato'], 'dispatch', ['imbalance', 'market-error'], [
  ['Les prévisions sont évaluées et leurs écarts analysés', 'Forecasts are evaluated and gaps analysed', 'Prognosen werden bewertet und Abweichungen analysiert', 'Las previsiones se evalúan y se analizan sus desviaciones', 'Le previsioni sono valutate e gli scostamenti analizzati'],
  ['Les limites d’engagement sont définies et respectées', 'Exposure limits are defined and respected', 'Positionslimits sind festgelegt und werden eingehalten', 'Los límites de exposición están definidos y se respetan', 'I limiti di esposizione sono definiti e rispettati'],
  ['Les nominations sont validées par deux personnes', 'Nominations are validated by two people', 'Nominierungen werden von zwei Personen validiert', 'Las nominaciones las validan dos personas', 'Le nomine sono validate da due persone'],
  ['Les pénalités et écarts sont rapprochés et expliqués', 'Penalties and gaps are reconciled and explained', 'Pönalen und Abweichungen werden abgeglichen und erklärt', 'Las penalizaciones y desviaciones se concilian y explican', 'Le penali e gli scostamenti sono riconciliati e spiegati'],
])

// ════════════════════════════ Industrie ═════════════════════════════════════
const ind = sectorPack('INDUSTRIE')
ind.risk('ip-theft', 2, ['Des plans, procédés ou secrets de fabrication sont exfiltrés', 'Designs, processes or trade secrets are exfiltrated', 'Konstruktionspläne, Verfahren oder Betriebsgeheimnisse werden entwendet', 'Se exfiltran planos, procesos o secretos de fabricación', 'Piani, processi o segreti di fabbricazione vengono esfiltrati'], 'produce')
ind.risk('environment-incident', 5, ['Un incident industriel provoque un rejet ou un accident majeur', 'An industrial incident causes a release or major accident', 'Ein Industrieunfall verursacht eine Freisetzung oder einen Störfall', 'Un incidente industrial provoca un vertido o un accidente mayor', 'Un incidente industriale provoca uno sversamento o un incidente rilevante'], 'maintain')
ind.risk('recall', 7, ['Un défaut de produit déjà livré impose un rappel', 'A defect in delivered product forces a recall', 'Ein Mangel an ausgelieferten Produkten erzwingt einen Rückruf', 'Un defecto en producto ya entregado obliga a una retirada', 'Un difetto in un prodotto già consegnato impone un richiamo'], 'quality')
ind.risk('counterfeit-parts', 7, ['Une pièce contrefaite ou non conforme entre dans la production', 'A counterfeit or non-conforming part enters production', 'Ein gefälschtes oder nicht konformes Teil gelangt in die Produktion', 'Una pieza falsificada o no conforme entra en la producción', 'Un componente contraffatto o non conforme entra in produzione'], 'supply')
ind.risk('erp-outage', 6, ['Une panne de l’ERP ou de la gestion de production arrête les expéditions', 'An ERP or production-management outage stops shipments', 'Ein Ausfall von ERP oder Produktionssteuerung stoppt den Versand', 'Una caída del ERP o de la gestión de producción detiene los envíos', 'Un’indisponibilità dell’ERP o della gestione della produzione ferma le spedizioni'], 'produce')
ind.control('ot-network-map', ['Revue de la cartographie des réseaux d’atelier et de leurs interconnexions', 'Review of the shop-floor network map and interconnections', 'Überprüfung der Netzübersicht der Fertigung und ihrer Verbindungen', 'Revisión de la cartografía de redes de taller y sus interconexiones', 'Revisione della mappatura delle reti di officina e delle interconnessioni'], 'produce', 'SEMESTRIEL', 'DETECTIF', ['ot-stop', 'remote-maintenance'], [IEC62443])
ind.control('plc-changes', ['Revue des modifications de programmes d’automates', 'Review of PLC program changes', 'Überprüfung von Änderungen an SPS-Programmen', 'Revisión de las modificaciones de programas de autómatas', 'Revisione delle modifiche ai programmi dei PLC'], 'produce', 'MENSUEL', 'DETECTIF', ['ot-stop', 'quality'])
ind.control('ot-backup', ['Test de restauration des programmes et paramètres de machines', 'Restoration test of machine programs and parameters', 'Wiederherstellungstest von Maschinenprogrammen und -parametern', 'Prueba de restauración de programas y parámetros de máquinas', 'Test di ripristino di programmi e parametri delle macchine'], 'produce', 'SEMESTRIEL', 'DETECTIF', ['ot-stop'])
ind.control('removable-media-ot', ['Contrôle de l’usage des supports amovibles en atelier', 'Check of removable-media use on the shop floor', 'Kontrolle der Nutzung von Wechseldatenträgern in der Fertigung', 'Control del uso de soportes extraíbles en el taller', 'Controllo dell’uso di supporti rimovibili in officina'], 'produce', 'MENSUEL', 'DETECTIF', ['ot-stop'])
ind.control('vendor-sessions', ['Revue des sessions de télémaintenance des constructeurs', 'Review of manufacturers’ remote-maintenance sessions', 'Überprüfung der Fernwartungssitzungen der Hersteller', 'Revisión de las sesiones de telemantenimiento de los fabricantes', 'Revisione delle sessioni di teleassistenza dei costruttori'], 'maintain', 'MENSUEL', 'DETECTIF', ['remote-maintenance'])
ind.control('design-data-access', ['Revue des accès aux plans, nomenclatures et procédés', 'Review of access to designs, bills of materials and processes', 'Überprüfung der Zugriffe auf Pläne, Stücklisten und Verfahren', 'Revisión de los accesos a planos, listas de materiales y procesos', 'Revisione degli accessi a piani, distinte base e processi'], 'produce', 'TRIMESTRIEL', 'DETECTIF', ['ip-theft'])
ind.control('contractor-confidentiality', ['Vérification des accords de confidentialité avec fournisseurs et sous-traitants de fabrication', 'Check of confidentiality agreements with manufacturing suppliers and subcontractors', 'Prüfung der Vertraulichkeitsvereinbarungen mit Fertigungslieferanten und Unterauftragnehmern', 'Verificación de los acuerdos de confidencialidad con proveedores y subcontratistas de fabricación', 'Verifica degli accordi di riservatezza con fornitori e subappaltatori di produzione'], 'supply', 'ANNUEL', 'PREVENTIF', ['ip-theft'])
ind.control('preventive-maintenance', ['Suivi de la réalisation de la maintenance préventive des équipements critiques', 'Follow-up of preventive maintenance on critical equipment', 'Nachverfolgung der vorbeugenden Instandhaltung kritischer Anlagen', 'Seguimiento de la realización del mantenimiento preventivo de los equipos críticos', 'Monitoraggio della manutenzione preventiva delle apparecchiature critiche'], 'maintain', 'MENSUEL', 'DETECTIF', ['ot-stop', 'spares'])
ind.control('spares-criticality', ['Revue de la criticité et du stock des pièces de rechange', 'Review of spare-parts criticality and stock', 'Überprüfung von Kritikalität und Bestand der Ersatzteile', 'Revisión de la criticidad y del stock de repuestos', 'Revisione della criticità e delle scorte dei ricambi'], 'maintain', 'TRIMESTRIEL', 'DETECTIF', ['spares'])
ind.control('safety-systems-test', ['Test périodique des systèmes de sécurité (arrêts d’urgence, détection, confinement)', 'Periodic test of safety systems (emergency stops, detection, containment)', 'Wiederkehrende Prüfung von Sicherheitssystemen (Not-Halt, Erkennung, Rückhaltung)', 'Prueba periódica de los sistemas de seguridad (paradas de emergencia, detección, confinamiento)', 'Test periodico dei sistemi di sicurezza (arresti di emergenza, rilevamento, contenimento)'], 'maintain', 'TRIMESTRIEL', 'PREVENTIF', ['safety', 'environment-incident'], [SEVESO])
ind.control('hazard-review', ['Revue des études de dangers et des modifications d’installations', 'Review of hazard studies and plant modifications', 'Überprüfung von Gefahrenanalysen und Anlagenänderungen', 'Revisión de los estudios de peligros y de las modificaciones de instalaciones', 'Revisione degli studi di pericolo e delle modifiche degli impianti'], 'maintain', 'ANNUEL', 'PREVENTIF', ['safety', 'environment-incident'], [SEVESO])
ind.control('quality-sample', ['Contrôle par échantillon de la conformité des produits avant expédition', 'Sample check of product conformity before shipment', 'Stichprobenprüfung der Produktkonformität vor Versand', 'Control por muestreo de la conformidad de los productos antes del envío', 'Controllo a campione della conformità dei prodotti prima della spedizione'], 'quality', 'MENSUEL', 'DETECTIF', ['quality', 'recall'])
ind.control('traceability-test', ['Exercice de traçabilité amont-aval d’un lot', 'Upstream-downstream batch traceability exercise', 'Übung zur Chargenrückverfolgung entlang der Kette', 'Ejercicio de trazabilidad aguas arriba y abajo de un lote', 'Esercitazione di tracciabilità a monte e a valle di un lotto'], 'quality', 'ANNUEL', 'DETECTIF', ['traceability', 'recall'])
ind.control('incoming-inspection', ['Contrôle à réception des composants critiques et suivi des non-conformités fournisseurs', 'Incoming inspection of critical components and supplier non-conformity follow-up', 'Wareneingangsprüfung kritischer Komponenten und Nachverfolgung von Lieferantenabweichungen', 'Control en recepción de componentes críticos y seguimiento de no conformidades de proveedores', 'Controllo in accettazione dei componenti critici e monitoraggio delle non conformità dei fornitori'], 'supply', 'MENSUEL', 'DETECTIF', ['counterfeit-parts', 'supplier'])
ind.control('single-source', ['Revue des approvisionnements à source unique et des solutions de repli', 'Review of single-source supplies and fallback options', 'Überprüfung von Single-Source-Beschaffungen und Ausweichlösungen', 'Revisión de los suministros de fuente única y de las soluciones alternativas', 'Revisione degli approvvigionamenti a fonte unica e delle soluzioni alternative'], 'supply', 'SEMESTRIEL', 'DETECTIF', ['supplier'])
ind.control('erp-recovery', ['Test de reprise de l’ERP et de la gestion de production', 'Recovery test of the ERP and production management', 'Wiederanlauftest von ERP und Produktionssteuerung', 'Prueba de recuperación del ERP y de la gestión de producción', 'Test di ripristino dell’ERP e della gestione della produzione'], 'produce', 'SEMESTRIEL', 'DETECTIF', ['erp-outage'])
ind.control('machine-conformity', ['Vérification de la conformité des machines mises en service ou modifiées', 'Check of conformity of machines put into service or modified', 'Prüfung der Konformität in Betrieb genommener oder geänderter Maschinen', 'Verificación de la conformidad de las máquinas puestas en servicio o modificadas', 'Verifica della conformità delle macchine messe in servizio o modificate'], 'maintain', 'ANNUEL', 'PREVENTIF', ['safety'], ['Règlement (UE) 2023/1230 (machines)'])
ind.control('ot-patch-windows', ['Suivi des correctifs et du maintien en conditions de sécurité des équipements d’atelier encore supportés', 'Follow-up of patches and security maintenance of supported shop-floor equipment', 'Nachverfolgung von Patches und Sicherheitswartung unterstützter Fertigungsanlagen', 'Seguimiento de parches y del mantenimiento de seguridad de los equipos de taller aún soportados', 'Monitoraggio delle patch e della manutenzione di sicurezza delle apparecchiature di officina ancora supportate'], 'maintain', 'SEMESTRIEL', 'DETECTIF', ['ot-stop'], [IEC62443])
ind.kri('ot-security-events', ['Événements de sécurité détectés sur les réseaux d’atelier', 'Security events detected on shop-floor networks', 'Auf Fertigungsnetzen erkannte Sicherheitsereignisse', 'Eventos de seguridad detectados en las redes de taller', 'Eventi di sicurezza rilevati sulle reti di officina'], 'produce', U_NB, 'HAUSSE', 'MENSUEL')
ind.kri('plc-unreviewed', ['Modifications d’automates sans revue approuvée', 'PLC changes without an approved review', 'SPS-Änderungen ohne genehmigte Prüfung', 'Modificaciones de autómatas sin revisión aprobada', 'Modifiche ai PLC senza revisione approvata'], 'produce', U_NB, 'HAUSSE', 'MENSUEL')
ind.kri('overdue-pm', ['Maintenances préventives critiques en retard', 'Overdue critical preventive maintenance', 'Überfällige kritische vorbeugende Instandhaltung', 'Mantenimientos preventivos críticos atrasados', 'Manutenzioni preventive critiche in ritardo'], 'maintain', U_PCT, 'HAUSSE', 'MENSUEL')
ind.kri('safety-incidents', ['Accidents du travail et presque-accidents déclarés', 'Reported workplace accidents and near-misses', 'Gemeldete Arbeitsunfälle und Beinaheunfälle', 'Accidentes laborales y casi accidentes notificados', 'Infortuni sul lavoro e quasi-incidenti denunciati'], 'maintain', U_NB, 'HAUSSE', 'MENSUEL')
ind.kri('customer-returns', ['Retours clients pour non-conformité', 'Customer returns for non-conformity', 'Kundenretouren wegen Nichtkonformität', 'Devoluciones de clientes por no conformidad', 'Resi dei clienti per non conformità'], 'quality', U_PCT, 'HAUSSE', 'MENSUEL')
ind.kri('single-source-share', ['Composants critiques à source unique', 'Critical components from a single source', 'Kritische Komponenten aus einer einzigen Quelle', 'Componentes críticos de fuente única', 'Componenti critici da fonte unica'], 'supply', U_PCT, 'HAUSSE', 'SEMESTRIEL')
ind.audit('ot-cybersecurity', ['Audit de la cybersécurité industrielle', 'Audit of industrial cybersecurity', 'Audit der industriellen Cybersicherheit', 'Auditoría de la ciberseguridad industrial', 'Audit della cybersicurezza industriale'], 'produce', ['ot-stop', 'remote-maintenance', 'ip-theft'], [
  ['Les réseaux d’atelier sont cartographiés et segmentés', 'Shop-floor networks are mapped and segmented', 'Fertigungsnetze sind erfasst und segmentiert', 'Las redes de taller están cartografiadas y segmentadas', 'Le reti di officina sono mappate e segmentate'],
  ['Les modifications de programmes sont autorisées et tracées', 'Program changes are authorised and logged', 'Programmänderungen sind genehmigt und protokolliert', 'Las modificaciones de programas están autorizadas y registradas', 'Le modifiche ai programmi sono autorizzate e tracciate'],
  ['Les accès distants des constructeurs sont maîtrisés', 'Manufacturers’ remote access is controlled', 'Fernzugriffe der Hersteller sind kontrolliert', 'Los accesos remotos de los fabricantes están controlados', 'Gli accessi remoti dei costruttori sono controllati'],
  ['Les procédés et plans sensibles sont protégés', 'Sensitive processes and designs are protected', 'Sensible Verfahren und Pläne sind geschützt', 'Los procesos y planos sensibles están protegidos', 'I processi e i piani sensibili sono protetti'],
])
ind.audit('maintenance-safety', ['Audit de la maintenance et de la sécurité industrielle', 'Audit of maintenance and industrial safety', 'Audit von Instandhaltung und Anlagensicherheit', 'Auditoría del mantenimiento y de la seguridad industrial', 'Audit della manutenzione e della sicurezza industriale'], 'maintain', ['safety', 'environment-incident', 'spares'], [
  ['Un plan de maintenance préventive couvre les équipements critiques', 'A preventive-maintenance plan covers critical equipment', 'Ein Plan zur vorbeugenden Instandhaltung deckt kritische Anlagen ab', 'Un plan de mantenimiento preventivo cubre los equipos críticos', 'Un piano di manutenzione preventiva copre le apparecchiature critiche'],
  ['Les systèmes de sécurité sont testés et leurs résultats conservés', 'Safety systems are tested and results retained', 'Sicherheitssysteme werden geprüft und Ergebnisse aufbewahrt', 'Los sistemas de seguridad se prueban y se conservan los resultados', 'I sistemi di sicurezza sono testati e i risultati conservati'],
  ['Les modifications d’installations font l’objet d’une analyse des risques', 'Plant modifications are subject to a risk analysis', 'Anlagenänderungen unterliegen einer Risikoanalyse', 'Las modificaciones de instalaciones se someten a un análisis de riesgos', 'Le modifiche agli impianti sono oggetto di un’analisi dei rischi'],
  ['Les pièces de rechange critiques sont identifiées et disponibles', 'Critical spare parts are identified and available', 'Kritische Ersatzteile sind identifiziert und verfügbar', 'Los repuestos críticos están identificados y disponibles', 'I ricambi critici sono identificati e disponibili'],
])
ind.audit('product-quality', ['Audit de la qualité produit et de la traçabilité', 'Audit of product quality and traceability', 'Audit von Produktqualität und Rückverfolgbarkeit', 'Auditoría de la calidad del producto y de la trazabilidad', 'Audit della qualità del prodotto e della tracciabilità'], 'quality', ['quality', 'recall', 'traceability', 'counterfeit-parts'], [
  ['Les contrôles qualité sont définis, réalisés et enregistrés', 'Quality checks are defined, performed and recorded', 'Qualitätsprüfungen sind festgelegt, durchgeführt und dokumentiert', 'Los controles de calidad están definidos, se realizan y se registran', 'I controlli qualità sono definiti, eseguiti e registrati'],
  ['Les non-conformités sont isolées et traitées avec leurs causes', 'Non-conformities are isolated and handled with their causes', 'Abweichungen werden isoliert und samt Ursachen behandelt', 'Las no conformidades se aíslan y tratan con sus causas', 'Le non conformità sono isolate e trattate con le relative cause'],
  ['La traçabilité des lots permet un rappel ciblé', 'Batch traceability allows a targeted recall', 'Die Chargenrückverfolgbarkeit ermöglicht einen gezielten Rückruf', 'La trazabilidad de los lotes permite una retirada dirigida', 'La tracciabilità dei lotti consente un richiamo mirato'],
  ['Les composants entrants critiques sont contrôlés', 'Critical incoming components are inspected', 'Kritische Eingangskomponenten werden geprüft', 'Los componentes entrantes críticos se controlan', 'I componenti in ingresso critici sono controllati'],
])

export const DEEPEN_A_PACKS = [pub.pack, en.pack, ind.pack]
