/**
 * Pack « Médias / Culture » (catalogue 1.10) : presse, audiovisuel, édition, plateformes de contenus, institutions culturelles.
 * Suggestions à qualifier : jamais d'exécution, de seuil, de date, de résultat ni de conformité acquise. Les `references`
 * citent le texte d'origine sans reproduire d'exigence. Contenu à relire par un expert du secteur (statut « à relire »).
 */
import { sectorPack, U_NB, U_PCT, U_MIN } from './catalogue-pack-builder'

const CPI = 'Code de la propriété intellectuelle (droit d’auteur et droits voisins)'
const RGPD = 'Règlement (UE) 2016/679 (RGPD)'
const DSA = 'Règlement (UE) 2022/2065 (Législation sur les services numériques)'
const PRESSE = 'Loi du 29 juillet 1881 sur la liberté de la presse'

const b = sectorPack('MEDIA')

b.process('editorial', ['Produire et valider les contenus éditoriaux', 'Produce and approve editorial content', 'Redaktionelle Inhalte erstellen und freigeben', 'Producir y validar los contenidos editoriales', 'Produrre e approvare i contenuti editoriali'])
b.process('publishing', ['Diffuser et publier sur les canaux numériques et linéaires', 'Distribute and publish on digital and linear channels', 'Über digitale und lineare Kanäle verbreiten und veröffentlichen', 'Difundir y publicar en canales digitales y lineales', 'Distribuire e pubblicare sui canali digitali e lineari'])
b.process('rights', ['Gérer les droits d’auteur, droits voisins et licences', 'Manage copyright, neighbouring rights and licences', 'Urheberrechte, verwandte Schutzrechte und Lizenzen verwalten', 'Gestionar los derechos de autor, derechos afines y licencias', 'Gestire diritti d’autore, diritti connessi e licenze'])
b.process('audience', ['Gérer les abonnés, l’audience et la publicité', 'Manage subscribers, audience and advertising', 'Abonnenten, Reichweite und Werbung steuern', 'Gestionar los suscriptores, la audiencia y la publicidad', 'Gestire abbonati, audience e pubblicità'])
b.process('production', ['Réaliser les productions et les captations (tournages, événements)', 'Carry out productions and recordings (shoots, events)', 'Produktionen und Aufzeichnungen durchführen (Drehs, Veranstaltungen)', 'Realizar las producciones y grabaciones (rodajes, eventos)', 'Realizzare produzioni e riprese (set, eventi)'])
b.process('archives', ['Conserver les archives, œuvres et collections', 'Preserve archives, works and collections', 'Archive, Werke und Sammlungen bewahren', 'Conservar los archivos, obras y colecciones', 'Conservare archivi, opere e collezioni'])

b.risk('defamation', 7, ['Un contenu publié est diffamatoire ou porte atteinte à la vie privée', 'Published content is defamatory or infringes privacy', 'Ein veröffentlichter Inhalt ist diffamierend oder verletzt die Privatsphäre', 'Un contenido publicado es difamatorio o vulnera la intimidad', 'Un contenuto pubblicato è diffamatorio o lede la riservatezza'], 'editorial')
b.risk('fake-content', 7, ['Un contenu falsifié ou généré artificiellement est publié sans vérification', 'Falsified or artificially generated content is published without verification', 'Ein gefälschter oder künstlich erzeugter Inhalt wird ohne Prüfung veröffentlicht', 'Se publica sin verificar un contenido falsificado o generado artificialmente', 'Un contenuto falsificato o generato artificialmente viene pubblicato senza verifica'], 'editorial')
b.risk('source-exposure', 4, ['L’identité d’une source confidentielle est exposée', 'The identity of a confidential source is exposed', 'Die Identität einer vertraulichen Quelle wird offengelegt', 'Se expone la identidad de una fuente confidencial', 'L’identità di una fonte riservata viene esposta'], 'editorial')
b.risk('account-takeover', 2, ['Un compte de réseau social ou de publication est piraté et diffuse de faux messages', 'A social or publishing account is hijacked and spreads false messages', 'Ein Social-Media- oder Redaktionskonto wird übernommen und verbreitet falsche Nachrichten', 'Una cuenta de redes sociales o de publicación es pirateada y difunde mensajes falsos', 'Un account social o editoriale viene violato e diffonde messaggi falsi'], 'publishing')
b.risk('broadcast-outage', 6, ['Une panne interrompt la diffusion ou la publication en direct', 'An outage interrupts live broadcast or publication', 'Ein Ausfall unterbricht die Live-Ausstrahlung oder -Veröffentlichung', 'Una avería interrumpe la emisión o publicación en directo', 'Un guasto interrompe la trasmissione o la pubblicazione in diretta'], 'publishing')
b.risk('site-defacement', 2, ['Un site ou une application est défiguré ou rendu indisponible lors d’un pic d’audience', 'A site or app is defaced or made unavailable during an audience peak', 'Eine Website oder App wird bei einem Zuschauerhoch verunstaltet oder unerreichbar', 'Un sitio o aplicación es alterado o queda inaccesible durante un pico de audiencia', 'Un sito o un’app viene deturpato o reso indisponibile durante un picco di audience'], 'publishing')
b.risk('rights-infringement', 7, ['Une œuvre est utilisée sans licence ou au-delà des droits acquis', 'A work is used without a licence or beyond the rights acquired', 'Ein Werk wird ohne Lizenz oder über die erworbenen Rechte hinaus genutzt', 'Una obra se utiliza sin licencia o más allá de los derechos adquiridos', 'Un’opera viene utilizzata senza licenza o oltre i diritti acquisiti'], 'rights')
b.risk('pre-release-leak', 4, ['Un contenu inédit fuite avant sa date de sortie', 'Unreleased content leaks before its release date', 'Ein unveröffentlichter Inhalt gelangt vor dem Veröffentlichungstermin an die Öffentlichkeit', 'Un contenido inédito se filtra antes de su fecha de estreno', 'Un contenuto inedito trapela prima della data di uscita'], 'production')
b.risk('subscriber-data', 4, ['Des données d’abonnés ou d’audience sont divulguées', 'Subscriber or audience data is disclosed', 'Abonnenten- oder Reichweitendaten werden offengelegt', 'Se divulgan datos de suscriptores o de audiencia', 'Vengono divulgati dati di abbonati o di audience'], 'audience')
b.risk('ad-fraud', 1, ['Un trafic ou des impressions publicitaires frauduleux faussent les revenus', 'Fraudulent traffic or ad impressions distort revenue', 'Betrügerischer Traffic oder Werbeeinblendungen verfälschen die Erlöse', 'Un tráfico o impresiones publicitarias fraudulentas distorsionan los ingresos', 'Traffico o impression pubblicitarie fraudolenti falsano i ricavi'], 'audience')
b.risk('archive-loss', 6, ['Des archives ou des œuvres numérisées sont perdues ou illisibles', 'Archives or digitised works are lost or unreadable', 'Archive oder digitalisierte Werke gehen verloren oder sind nicht mehr lesbar', 'Se pierden o quedan ilegibles archivos u obras digitalizadas', 'Archivi o opere digitalizzate vengono perse o diventano illeggibili'], 'archives')
b.risk('event-safety', 3, ['Un incident de sécurité des personnes survient lors d’un tournage ou d’un événement', 'A safety incident involving people occurs during a shoot or event', 'Bei einem Dreh oder einer Veranstaltung kommt es zu einem Sicherheitsvorfall mit Personen', 'Ocurre un incidente de seguridad de las personas durante un rodaje o evento', 'Si verifica un incidente di sicurezza delle persone durante una ripresa o un evento'], 'production')

b.control('editorial-validation', ['Revue par échantillon de la validation éditoriale avant publication des contenus sensibles', 'Sample review of editorial approval before publishing sensitive content', 'Stichprobenprüfung der redaktionellen Freigabe vor Veröffentlichung sensibler Inhalte', 'Revisión por muestreo de la validación editorial antes de publicar contenidos sensibles', 'Revisione a campione dell’approvazione editoriale prima della pubblicazione di contenuti sensibili'], 'editorial', 'MENSUEL', 'PREVENTIF', ['defamation', 'fake-content'], [PRESSE])
b.control('source-verification', ['Contrôle de l’application de la procédure de vérification des contenus et sources', 'Check that content and source verification procedures are applied', 'Prüfung der Anwendung des Verfahrens zur Überprüfung von Inhalten und Quellen', 'Control de la aplicación del procedimiento de verificación de contenidos y fuentes', 'Controllo dell’applicazione della procedura di verifica di contenuti e fonti'], 'editorial', 'MENSUEL', 'PREVENTIF', ['fake-content'])
b.control('corrections-log', ['Revue du registre des demandes de rectification et droits de réponse', 'Review of the log of correction and right-of-reply requests', 'Überprüfung des Registers der Berichtigungs- und Gegendarstellungsverlangen', 'Revisión del registro de solicitudes de rectificación y derecho de réplica', 'Revisione del registro delle richieste di rettifica e diritto di replica'], 'editorial', 'TRIMESTRIEL', 'DETECTIF', ['defamation'], [PRESSE])
b.control('source-protection', ['Revue des accès aux dossiers contenant des sources confidentielles', 'Review of access to files containing confidential sources', 'Überprüfung der Zugriffe auf Akten mit vertraulichen Quellen', 'Revisión de los accesos a expedientes con fuentes confidenciales', 'Revisione degli accessi ai fascicoli contenenti fonti riservate'], 'editorial', 'TRIMESTRIEL', 'DETECTIF', ['source-exposure'])
b.control('secure-channels', ['Vérification de l’usage de canaux chiffrés pour les échanges avec les sources', 'Check of encrypted channels for exchanges with sources', 'Prüfung der Nutzung verschlüsselter Kanäle für den Austausch mit Quellen', 'Verificación del uso de canales cifrados para los intercambios con las fuentes', 'Verifica dell’uso di canali cifrati per gli scambi con le fonti'], 'editorial', 'SEMESTRIEL', 'DETECTIF', ['source-exposure'])
b.control('social-accounts', ['Revue des accès et de l’authentification renforcée des comptes de publication', 'Review of access and strong authentication on publishing accounts', 'Überprüfung der Zugriffe und der starken Authentifizierung der Veröffentlichungskonten', 'Revisión de los accesos y de la autenticación reforzada de las cuentas de publicación', 'Revisione degli accessi e dell’autenticazione forte degli account di pubblicazione'], 'publishing', 'TRIMESTRIEL', 'DETECTIF', ['account-takeover'])
b.control('cms-privileges', ['Revue des droits dans le système de gestion de contenus', 'Review of rights in the content-management system', 'Überprüfung der Rechte im Content-Management-System', 'Revisión de los derechos en el sistema de gestión de contenidos', 'Revisione dei diritti nel sistema di gestione dei contenuti'], 'publishing', 'TRIMESTRIEL', 'DETECTIF', ['account-takeover', 'site-defacement'])
b.control('failover-test', ['Test de bascule de la diffusion sur la chaîne de secours', 'Failover test of broadcast to the backup chain', 'Umschalttest der Ausstrahlung auf die Ersatzkette', 'Prueba de conmutación de la emisión a la cadena de respaldo', 'Test di commutazione della trasmissione sulla catena di backup'], 'publishing', 'SEMESTRIEL', 'DETECTIF', ['broadcast-outage'])
b.control('load-test', ['Test de charge avant les temps forts (élections, événements, sorties)', 'Load test before peak events (elections, events, releases)', 'Lasttest vor Spitzenereignissen (Wahlen, Veranstaltungen, Veröffentlichungen)', 'Prueba de carga antes de los picos (elecciones, eventos, estrenos)', 'Test di carico prima dei picchi (elezioni, eventi, uscite)'], 'publishing', 'SEMESTRIEL', 'PREVENTIF', ['site-defacement', 'broadcast-outage'])
b.control('ddos-readiness', ['Vérification du dispositif de protection contre les attaques par déni de service', 'Check of denial-of-service protection arrangements', 'Prüfung der Schutzvorkehrungen gegen Denial-of-Service-Angriffe', 'Verificación del dispositivo de protección contra ataques de denegación de servicio', 'Verifica del dispositivo di protezione contro gli attacchi di tipo denial of service'], 'publishing', 'SEMESTRIEL', 'PREVENTIF', ['site-defacement'])
b.control('licence-register', ['Rapprochement des usages d’œuvres avec le registre des licences et droits acquis', 'Reconciliation of uses of works with the licence and rights register', 'Abgleich der Werknutzungen mit dem Lizenz- und Rechteregister', 'Conciliación de los usos de obras con el registro de licencias y derechos adquiridos', 'Riconciliazione degli usi di opere con il registro di licenze e diritti acquisiti'], 'rights', 'TRIMESTRIEL', 'DETECTIF', ['rights-infringement'], [CPI])
b.control('rights-expiry', ['Suivi des échéances de droits et retrait des contenus à l’échéance', 'Follow-up of rights expiry dates and content removal on expiry', 'Überwachung der Ablaufdaten von Rechten und Entfernung von Inhalten bei Ablauf', 'Seguimiento de los vencimientos de derechos y retirada de contenidos al vencimiento', 'Monitoraggio delle scadenze dei diritti e rimozione dei contenuti alla scadenza'], 'rights', 'MENSUEL', 'PREVENTIF', ['rights-infringement'], [CPI])
b.control('freelance-contracts', ['Vérification des cessions de droits dans les contrats de pigistes et de producteurs', 'Check of rights assignments in freelancer and producer contracts', 'Prüfung der Rechteübertragungen in Verträgen mit freien Mitarbeitern und Produzenten', 'Verificación de las cesiones de derechos en los contratos de colaboradores y productores', 'Verifica delle cessioni di diritti nei contratti con freelance e produttori'], 'rights', 'ANNUEL', 'PREVENTIF', ['rights-infringement'], [CPI])
b.control('notice-and-action', ['Revue du traitement des signalements de contenus illicites', 'Review of handling of illegal-content notices', 'Überprüfung der Bearbeitung von Meldungen rechtswidriger Inhalte', 'Revisión del tratamiento de las notificaciones de contenidos ilícitos', 'Revisione della gestione delle segnalazioni di contenuti illeciti'], 'audience', 'TRIMESTRIEL', 'DETECTIF', ['defamation'], [DSA])
b.control('subscriber-access', ['Revue des accès aux données d’abonnés et d’audience', 'Review of access to subscriber and audience data', 'Überprüfung der Zugriffe auf Abonnenten- und Reichweitendaten', 'Revisión de los accesos a los datos de suscriptores y audiencia', 'Revisione degli accessi ai dati di abbonati e audience'], 'audience', 'TRIMESTRIEL', 'DETECTIF', ['subscriber-data'], [RGPD])
b.control('consent-trackers', ['Contrôle du recueil du consentement et des traceurs publicitaires', 'Check of consent collection and advertising trackers', 'Prüfung der Einwilligungseinholung und der Werbe-Tracker', 'Control de la obtención del consentimiento y de los rastreadores publicitarios', 'Controllo della raccolta del consenso e dei tracker pubblicitari'], 'audience', 'SEMESTRIEL', 'DETECTIF', ['subscriber-data'], [RGPD])
b.control('ad-traffic-quality', ['Revue de la qualité du trafic publicitaire et des anomalies d’impressions', 'Review of ad-traffic quality and impression anomalies', 'Überprüfung der Qualität des Werbe-Traffics und von Einblendungs-Anomalien', 'Revisión de la calidad del tráfico publicitario y de las anomalías de impresiones', 'Revisione della qualità del traffico pubblicitario e delle anomalie di impression'], 'audience', 'MENSUEL', 'DETECTIF', ['ad-fraud'])
b.control('pre-release-access', ['Revue des accès aux contenus inédits et aux dailies', 'Review of access to unreleased content and dailies', 'Überprüfung der Zugriffe auf unveröffentlichte Inhalte und Tagesmaterial', 'Revisión de los accesos a contenidos inéditos y a copias de trabajo', 'Revisione degli accessi a contenuti inediti e ai giornalieri'], 'production', 'MENSUEL', 'DETECTIF', ['pre-release-leak'])
b.control('archive-restore', ['Test de restauration d’un échantillon d’archives numériques', 'Restoration test of a sample of digital archives', 'Wiederherstellungstest an einer Stichprobe digitaler Archive', 'Prueba de restauración de una muestra de archivos digitales', 'Test di ripristino su un campione di archivi digitali'], 'archives', 'ANNUEL', 'DETECTIF', ['archive-loss'])
b.control('shoot-safety', ['Vérification des plans de sécurité des tournages et événements', 'Check of safety plans for shoots and events', 'Prüfung der Sicherheitskonzepte für Dreharbeiten und Veranstaltungen', 'Verificación de los planes de seguridad de rodajes y eventos', 'Verifica dei piani di sicurezza di riprese ed eventi'], 'production', 'TRIMESTRIEL', 'PREVENTIF', ['event-safety'])

b.kri('publication-corrections', ['Corrections ou retraits de contenus publiés', 'Corrections or retractions of published content', 'Korrekturen oder Rücknahmen veröffentlichter Inhalte', 'Correcciones o retiradas de contenidos publicados', 'Correzioni o ritiri di contenuti pubblicati'], 'editorial', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('legal-claims', ['Mises en demeure ou plaintes relatives à des contenus', 'Formal notices or complaints about content', 'Abmahnungen oder Beschwerden zu Inhalten', 'Requerimientos o quejas relativos a contenidos', 'Diffide o reclami relativi ai contenuti'], 'editorial', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('airtime-lost', ['Durée d’interruption de diffusion ou de publication', 'Duration of broadcast or publication interruption', 'Dauer der Unterbrechung von Ausstrahlung oder Veröffentlichung', 'Duración de la interrupción de emisión o publicación', 'Durata dell’interruzione di trasmissione o pubblicazione'], 'publishing', U_MIN, 'HAUSSE', 'MENSUEL')
b.kri('site-availability', ['Disponibilité des sites et applications lors des pics d’audience', 'Availability of sites and apps during audience peaks', 'Verfügbarkeit von Websites und Apps bei Zuschauerspitzen', 'Disponibilidad de sitios y aplicaciones durante los picos de audiencia', 'Disponibilità di siti e app durante i picchi di audience'], 'publishing', U_PCT, 'BAISSE', 'MENSUEL')
b.kri('expired-rights', ['Contenus en ligne dont les droits sont échus', 'Online content whose rights have expired', 'Online verfügbare Inhalte mit abgelaufenen Rechten', 'Contenidos en línea con derechos vencidos', 'Contenuti online con diritti scaduti'], 'rights', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('notices-backlog', ['Signalements de contenus illicites non traités dans le délai cible', 'Illegal-content notices not handled within the target time', 'Meldungen rechtswidriger Inhalte, die nicht innerhalb der Zielzeit bearbeitet wurden', 'Notificaciones de contenidos ilícitos no tramitadas en el plazo objetivo', 'Segnalazioni di contenuti illeciti non gestite entro il termine obiettivo'], 'audience', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('invalid-traffic', ['Part du trafic publicitaire jugé invalide', 'Share of ad traffic judged invalid', 'Anteil des als ungültig eingestuften Werbe-Traffics', 'Parte del tráfico publicitario considerada inválida', 'Quota del traffico pubblicitario ritenuto non valido'], 'audience', U_PCT, 'HAUSSE', 'MENSUEL')
b.kri('archive-unread', ['Archives numériques non restaurées lors des tests (taux d’échec)', 'Digital archives not restored in tests (failure rate)', 'In Tests nicht wiederhergestellte digitale Archive (Fehlerquote)', 'Archivos digitales no restaurados en las pruebas (tasa de fallo)', 'Archivi digitali non ripristinati nei test (tasso di fallimento)'], 'archives', U_PCT, 'HAUSSE', 'ANNUEL')

b.audit('editorial-process', ['Audit du processus éditorial et de vérification', 'Audit of the editorial and verification process', 'Audit des redaktionellen Prozesses und der Faktenprüfung', 'Auditoría del proceso editorial y de verificación', 'Audit del processo editoriale e di verifica'], 'editorial', ['defamation', 'fake-content', 'source-exposure'], [
  ['Les règles de validation et de vérification sont formalisées et connues', 'Approval and verification rules are formalised and known', 'Freigabe- und Prüfregeln sind formalisiert und bekannt', 'Las reglas de validación y verificación están formalizadas y son conocidas', 'Le regole di approvazione e verifica sono formalizzate e conosciute'],
  ['Les contenus sensibles font l’objet d’une double lecture', 'Sensitive content is read by a second person', 'Sensible Inhalte werden im Vier-Augen-Prinzip gegengelesen', 'Los contenidos sensibles se someten a doble lectura', 'I contenuti sensibili sono oggetto di doppia lettura'],
  ['Les rectifications et droits de réponse sont suivis et traités dans les délais', 'Corrections and rights of reply are tracked and handled on time', 'Berichtigungen und Gegendarstellungen werden nachverfolgt und fristgerecht bearbeitet', 'Las rectificaciones y derechos de réplica se siguen y se tramitan en plazo', 'Le rettifiche e i diritti di replica sono monitorati e gestiti nei termini'],
  ['La protection des sources est assurée techniquement et organisationnellement', 'Source protection is ensured technically and organisationally', 'Der Quellenschutz ist technisch und organisatorisch gewährleistet', 'La protección de las fuentes está asegurada técnica y organizativamente', 'La protezione delle fonti è assicurata tecnicamente e organizzativamente'],
])
b.audit('publishing-continuity', ['Audit de la continuité de diffusion et de publication', 'Audit of broadcast and publication continuity', 'Audit der Kontinuität von Ausstrahlung und Veröffentlichung', 'Auditoría de la continuidad de emisión y publicación', 'Audit della continuità di trasmissione e pubblicazione'], 'publishing', ['broadcast-outage', 'site-defacement', 'account-takeover'], [
  ['Les chaînes critiques de diffusion sont identifiées avec leurs secours', 'Critical broadcast chains are identified with their backups', 'Kritische Ausstrahlungsketten sind mit ihren Ersatzlösungen identifiziert', 'Las cadenas críticas de emisión están identificadas con sus respaldos', 'Le catene critiche di trasmissione sono identificate con i relativi backup'],
  ['Des tests de bascule et de charge sont réalisés avant les pics', 'Failover and load tests are carried out before peaks', 'Umschalt- und Lasttests werden vor Spitzenzeiten durchgeführt', 'Se realizan pruebas de conmutación y de carga antes de los picos', 'Si eseguono test di commutazione e di carico prima dei picchi'],
  ['Les comptes de publication sont protégés par une authentification renforcée', 'Publishing accounts are protected by strong authentication', 'Veröffentlichungskonten sind durch starke Authentifizierung geschützt', 'Las cuentas de publicación están protegidas con autenticación reforzada', 'Gli account di pubblicazione sono protetti da autenticazione forte'],
  ['Un plan de communication de crise couvre les incidents de diffusion', 'A crisis communication plan covers broadcast incidents', 'Ein Krisenkommunikationsplan deckt Ausstrahlungsstörungen ab', 'Un plan de comunicación de crisis cubre los incidentes de emisión', 'Un piano di comunicazione di crisi copre gli incidenti di trasmissione'],
])
b.audit('rights-management', ['Audit de la gestion des droits et licences', 'Audit of rights and licence management', 'Audit der Rechte- und Lizenzverwaltung', 'Auditoría de la gestión de derechos y licencias', 'Audit della gestione di diritti e licenze'], 'rights', ['rights-infringement'], [
  ['Un registre des droits acquis, de leur durée et de leur territoire est tenu', 'A register of rights acquired, duration and territory is kept', 'Ein Register der erworbenen Rechte, ihrer Dauer und ihres Gebiets wird geführt', 'Se lleva un registro de los derechos adquiridos, su duración y su territorio', 'È tenuto un registro dei diritti acquisiti, della loro durata e del loro territorio'],
  ['Les contrats de création prévoient la cession des droits nécessaires', 'Creation contracts provide for the necessary rights assignment', 'Urheberverträge sehen die erforderliche Rechteübertragung vor', 'Los contratos de creación prevén la cesión de los derechos necesarios', 'I contratti di creazione prevedono la cessione dei diritti necessari'],
  ['Les contenus dont les droits expirent sont retirés ou renouvelés', 'Content whose rights expire is removed or renewed', 'Inhalte mit auslaufenden Rechten werden entfernt oder verlängert', 'Los contenidos cuyos derechos expiran se retiran o renuevan', 'I contenuti i cui diritti scadono sono rimossi o rinnovati'],
  ['Les déclarations aux sociétés de gestion collective sont exactes', 'Declarations to collective management bodies are accurate', 'Meldungen an Verwertungsgesellschaften sind zutreffend', 'Las declaraciones a las entidades de gestión colectiva son exactas', 'Le dichiarazioni agli organismi di gestione collettiva sono esatte'],
])
b.audit('audience-data', ['Audit des données d’abonnés, d’audience et de la publicité', 'Audit of subscriber, audience and advertising data', 'Audit der Abonnenten-, Reichweiten- und Werbedaten', 'Auditoría de los datos de suscriptores, audiencia y publicidad', 'Audit dei dati di abbonati, audience e pubblicità'], 'audience', ['subscriber-data', 'ad-fraud'], [
  ['Le recueil du consentement et la gestion des traceurs sont conformes aux règles applicables', 'Consent collection and tracker management follow applicable rules', 'Einwilligungseinholung und Tracker-Verwaltung folgen den geltenden Regeln', 'La obtención del consentimiento y la gestión de rastreadores siguen las normas aplicables', 'La raccolta del consenso e la gestione dei tracker seguono le regole applicabili'],
  ['Les accès aux données d’abonnés sont limités et tracés', 'Access to subscriber data is limited and logged', 'Zugriffe auf Abonnentendaten sind begrenzt und protokolliert', 'Los accesos a datos de suscriptores son limitados y quedan registrados', 'Gli accessi ai dati degli abbonati sono limitati e tracciati'],
  ['Les prestataires publicitaires et de mesure d’audience sont encadrés par contrat', 'Advertising and audience-measurement providers are covered by contract', 'Werbe- und Reichweitenmessungsdienstleister sind vertraglich eingebunden', 'Los proveedores publicitarios y de medición de audiencia están amparados por contrato', 'I fornitori pubblicitari e di misurazione dell’audience sono coperti da contratto'],
  ['Le trafic invalide est détecté et son impact sur les revenus mesuré', 'Invalid traffic is detected and its revenue impact measured', 'Ungültiger Traffic wird erkannt und seine Auswirkung auf die Erlöse gemessen', 'El tráfico inválido se detecta y se mide su impacto en los ingresos', 'Il traffico non valido è rilevato e il suo impatto sui ricavi misurato'],
])

export const MEDIA_PACK = b.pack
