/**
 * Pack « Tourisme / Hôtellerie-restauration » (catalogue 1.10) : hôtels, restauration, agences et opérateurs de voyages, sites de loisirs.
 * Suggestions à qualifier : jamais d'exécution, de seuil, de date, de résultat ni de conformité acquise. Les `references`
 * citent le texte d'origine sans reproduire d'exigence. Contenu à relire par un expert du secteur (statut « à relire »).
 */
import { sectorPack, U_NB, U_PCT, U_MIN } from './catalogue-pack-builder'

const RGPD = 'Règlement (UE) 2016/679 (RGPD)'
const PCI = 'PCI DSS v4.0.1 (norme de sécurité des données de l’industrie des cartes de paiement)'
const FORFAIT = 'Directive (UE) 2015/2302 relative aux voyages à forfait et aux prestations de voyage liées'
const HYG = 'Règlement (CE) n° 852/2004 (hygiène des denrées alimentaires)'
const TOURISME = 'Code du tourisme'

const b = sectorPack('TOURISME')

b.process('booking', ['Gérer les réservations et la distribution', 'Manage bookings and distribution', 'Buchungen und Vertrieb verwalten', 'Gestionar las reservas y la distribución', 'Gestire le prenotazioni e la distribuzione'])
b.process('guest', ['Accueillir les clients et gérer leur séjour', 'Welcome guests and manage their stay', 'Gäste empfangen und ihren Aufenthalt betreuen', 'Acoger a los clientes y gestionar su estancia', 'Accogliere gli ospiti e gestire il loro soggiorno'])
b.process('payments', ['Encaisser et gérer les moyens de paiement', 'Collect payments and manage payment means', 'Zahlungen einziehen und Zahlungsmittel verwalten', 'Cobrar y gestionar los medios de pago', 'Incassare e gestire i mezzi di pagamento'])
b.process('food', ['Préparer et servir la restauration', 'Prepare and serve food and beverages', 'Speisen und Getränke zubereiten und servieren', 'Preparar y servir la restauración', 'Preparare e servire la ristorazione'])
b.process('operations', ['Exploiter les sites, l’hébergement et les équipements', 'Operate sites, accommodation and equipment', 'Standorte, Unterkünfte und Anlagen betreiben', 'Operar los sitios, el alojamiento y los equipos', 'Gestire siti, alloggi e attrezzature'])
b.process('travel-packages', ['Concevoir et exécuter les voyages et prestations avec des partenaires', 'Design and deliver trips and services with partners', 'Reisen und Leistungen mit Partnern konzipieren und erbringen', 'Diseñar y ejecutar los viajes y servicios con socios', 'Progettare ed eseguire viaggi e servizi con i partner'])

b.risk('card-data', 2, ['Des données de cartes de paiement de clients sont compromises', 'Customers’ payment-card data is compromised', 'Zahlungskartendaten von Gästen werden kompromittiert', 'Se comprometen datos de tarjetas de pago de clientes', 'I dati delle carte di pagamento dei clienti vengono compromessi'], 'payments')
b.risk('booking-fraud', 2, ['Des réservations frauduleuses ou usurpations de comptes de réservation détournent des paiements', 'Fraudulent bookings or hijacked booking accounts divert payments', 'Betrügerische Buchungen oder übernommene Buchungskonten leiten Zahlungen um', 'Reservas fraudulentas o cuentas de reserva usurpadas desvían pagos', 'Prenotazioni fraudolente o account di prenotazione violati dirottano pagamenti'], 'booking')
b.risk('guest-data', 4, ['Des données de clients (identité, documents de voyage, préférences) sont divulguées', 'Guest data (identity, travel documents, preferences) is disclosed', 'Gästedaten (Identität, Reisedokumente, Präferenzen) werden offengelegt', 'Se divulgan datos de clientes (identidad, documentos de viaje, preferencias)', 'Vengono divulgati dati degli ospiti (identità, documenti di viaggio, preferenze)'], 'guest')
b.risk('overbooking', 7, ['Une surréservation ou un défaut de synchronisation des canaux prive des clients de leur prestation', 'Overbooking or channel desynchronisation leaves guests without their service', 'Überbuchung oder fehlende Kanalsynchronisierung lässt Gäste ohne Leistung', 'Una sobrerreserva o la falta de sincronización de canales deja a clientes sin su servicio', 'Un overbooking o una desincronizzazione dei canali lascia gli ospiti senza il servizio'], 'booking')
b.risk('pms-outage', 6, ['Une panne du système de gestion hôtelière ou de réservation bloque l’accueil', 'A property-management or booking system outage blocks reception', 'Ein Ausfall des Hotelverwaltungs- oder Buchungssystems blockiert den Empfang', 'Una caída del sistema de gestión hotelera o de reservas bloquea la recepción', 'Un’indisponibilità del sistema gestionale alberghiero o di prenotazione blocca l’accoglienza'], 'booking')
b.risk('food-poisoning', 3, ['Une intoxication alimentaire touche plusieurs clients', 'Food poisoning affects several guests', 'Eine Lebensmittelvergiftung betrifft mehrere Gäste', 'Una intoxicación alimentaria afecta a varios clientes', 'Un’intossicazione alimentare colpisce più ospiti'], 'food')
b.risk('allergen-error', 3, ['Un allergène n’est pas signalé et un client est exposé', 'An allergen is not flagged and a guest is exposed', 'Ein Allergen wird nicht gekennzeichnet und ein Gast ist gefährdet', 'No se señala un alérgeno y un cliente queda expuesto', 'Un allergene non viene segnalato e un ospite è esposto'], 'food')
b.risk('guest-safety', 3, ['Un incident met en danger des clients (incendie, accident, baignade, activité à risque)', 'An incident endangers guests (fire, accident, swimming, risky activity)', 'Ein Vorfall gefährdet Gäste (Brand, Unfall, Baden, Risikoaktivität)', 'Un incidente pone en peligro a clientes (incendio, accidente, baño, actividad de riesgo)', 'Un incidente mette in pericolo gli ospiti (incendio, incidente, balneazione, attività a rischio)'], 'operations')
b.risk('access-keys', 2, ['Un système de clés ou d’accès aux chambres est compromis', 'A room key or access system is compromised', 'Ein Schlüssel- oder Zutrittssystem für Zimmer wird kompromittiert', 'Un sistema de llaves o de acceso a las habitaciones se ve comprometido', 'Un sistema di chiavi o di accesso alle camere viene compromesso'], 'operations')
b.risk('partner-failure', 7, ['Un prestataire local ou une compagnie défaille et la prestation vendue n’est pas délivrée', 'A local provider or carrier fails and the sold service is not delivered', 'Ein lokaler Dienstleister oder eine Fluggesellschaft fällt aus und die verkaufte Leistung wird nicht erbracht', 'Un proveedor local o aerolínea incumple y no se presta el servicio vendido', 'Un fornitore locale o un vettore viene meno e il servizio venduto non è erogato'], 'travel-packages')
b.risk('refund-liability', 7, ['Un remboursement ou une assistance dus aux voyageurs ne peuvent pas être assurés lors d’une défaillance', 'A refund or assistance owed to travellers cannot be provided on a failure', 'Eine Erstattung oder Hilfe für Reisende kann im Insolvenzfall nicht geleistet werden', 'No se pueden asegurar un reembolso o una asistencia debidos a los viajeros en caso de quiebra', 'Un rimborso o un’assistenza dovuti ai viaggiatori non possono essere garantiti in caso di insolvenza'], 'travel-packages')
b.risk('reputation-reviews', 7, ['Des avis clients falsifiés ou une crise de réputation en ligne dégradent l’activité', 'Fake reviews or an online reputation crisis damage business', 'Gefälschte Bewertungen oder eine Reputationskrise im Netz schädigen das Geschäft', 'Reseñas falsas o una crisis de reputación en línea dañan la actividad', 'Recensioni false o una crisi di reputazione online danneggiano l’attività'], 'guest')
b.risk('seasonal-staff', 3, ['Un manque de personnel saisonnier dégrade le service en haute saison', 'A seasonal staffing shortage degrades service in peak season', 'Personalmangel in der Hochsaison beeinträchtigt den Service', 'La falta de personal estacional degrada el servicio en temporada alta', 'La carenza di personale stagionale peggiora il servizio in alta stagione'], 'operations')

b.control('pci-scope', ['Revue du périmètre et de la sécurité de l’environnement de données de cartes', 'Review of scope and security of the cardholder-data environment', 'Überprüfung von Umfang und Sicherheit der Karteninhaberdaten-Umgebung', 'Revisión del perímetro y de la seguridad del entorno de datos de tarjetas', 'Revisione del perimetro e della sicurezza dell’ambiente dei dati delle carte'], 'payments', 'ANNUEL', 'DETECTIF', ['card-data'], [PCI])
b.control('card-storage', ['Vérification de l’absence de conservation de données de carte sur les postes et dans les courriels', 'Check that card data is not kept on workstations or in emails', 'Prüfung, dass keine Kartendaten auf Arbeitsplätzen oder in E-Mails gespeichert sind', 'Verificación de que no se conservan datos de tarjetas en puestos ni en correos', 'Verifica che non siano conservati dati di carte su postazioni o e-mail'], 'payments', 'TRIMESTRIEL', 'DETECTIF', ['card-data'], [PCI])
b.control('terminal-inspection', ['Inspection des terminaux de paiement (altération, remplacement)', 'Inspection of payment terminals (tampering, substitution)', 'Inspektion der Zahlungsterminals (Manipulation, Austausch)', 'Inspección de los terminales de pago (manipulación, sustitución)', 'Ispezione dei terminali di pagamento (manomissione, sostituzione)'], 'payments', 'MENSUEL', 'DETECTIF', ['card-data'], [PCI])
b.control('chargebacks', ['Revue des litiges et impayés de paiement par carte', 'Review of card-payment disputes and chargebacks', 'Überprüfung von Kartenzahlungsstreitigkeiten und Rückbelastungen', 'Revisión de los litigios e impagos de pagos con tarjeta', 'Revisione dei contenziosi e degli insoluti dei pagamenti con carta'], 'payments', 'MENSUEL', 'DETECTIF', ['booking-fraud', 'card-data'])
b.control('booking-anomalies', ['Revue des réservations anormales (volume, pays, moyen de paiement)', 'Review of abnormal bookings (volume, country, payment method)', 'Überprüfung auffälliger Buchungen (Volumen, Land, Zahlungsmittel)', 'Revisión de reservas anómalas (volumen, país, medio de pago)', 'Revisione delle prenotazioni anomale (volume, paese, mezzo di pagamento)'], 'booking', 'MENSUEL', 'DETECTIF', ['booking-fraud'])
b.control('extranet-accounts', ['Revue des comptes et de l’authentification renforcée des extranets de réservation', 'Review of accounts and strong authentication on booking extranets', 'Überprüfung der Konten und der starken Authentifizierung der Buchungs-Extranets', 'Revisión de las cuentas y de la autenticación reforzada de los extranets de reserva', 'Revisione degli account e dell’autenticazione forte degli extranet di prenotazione'], 'booking', 'TRIMESTRIEL', 'DETECTIF', ['booking-fraud'])
b.control('channel-sync', ['Contrôle par échantillon de la synchronisation des disponibilités entre canaux', 'Sample check of availability synchronisation across channels', 'Stichprobenprüfung der Synchronisierung der Verfügbarkeiten zwischen Kanälen', 'Control por muestreo de la sincronización de disponibilidades entre canales', 'Controllo a campione della sincronizzazione delle disponibilità tra canali'], 'booking', 'MENSUEL', 'DETECTIF', ['overbooking'])
b.control('pms-downtime-drill', ['Exercice de fonctionnement en mode dégradé de l’accueil (sans système)', 'Exercise of reception in fallback mode (without system)', 'Übung zum Empfangsbetrieb im Notbetrieb (ohne System)', 'Ejercicio de funcionamiento de recepción en modo degradado (sin sistema)', 'Esercitazione di funzionamento della reception in modalità degradata (senza sistema)'], 'booking', 'ANNUEL', 'PREVENTIF', ['pms-outage'])
b.control('guest-data-access', ['Revue des accès aux fiches clients et aux pièces d’identité', 'Review of access to guest records and ID documents', 'Überprüfung der Zugriffe auf Gästeakten und Ausweisdokumente', 'Revisión de los accesos a fichas de clientes y documentos de identidad', 'Revisione degli accessi alle schede ospiti e ai documenti di identità'], 'guest', 'TRIMESTRIEL', 'DETECTIF', ['guest-data'], [RGPD])
b.control('guest-data-retention', ['Contrôle de la purge des fiches clients et des pièces d’identité après la durée utile', 'Check of purging of guest records and ID documents after the useful period', 'Prüfung der Löschung von Gästeakten und Ausweisdokumenten nach Ablauf der Nutzungsdauer', 'Control de la eliminación de fichas de clientes y documentos de identidad tras el plazo útil', 'Controllo dell’eliminazione di schede ospiti e documenti di identità dopo il periodo utile'], 'guest', 'SEMESTRIEL', 'DETECTIF', ['guest-data'], [RGPD])
b.control('review-handling', ['Suivi des avis clients négatifs et des demandes de suppression', 'Follow-up of negative guest reviews and removal requests', 'Nachverfolgung negativer Gästebewertungen und Löschverlangen', 'Seguimiento de las reseñas negativas y de las solicitudes de eliminación', 'Monitoraggio delle recensioni negative e delle richieste di rimozione'], 'guest', 'MENSUEL', 'DETECTIF', ['reputation-reviews'])
b.control('temperature-logs', ['Revue des relevés de température et du plan de nettoyage en cuisine', 'Review of kitchen temperature logs and cleaning plan', 'Überprüfung der Temperaturaufzeichnungen und des Reinigungsplans in der Küche', 'Revisión de los registros de temperatura y del plan de limpieza de cocina', 'Revisione dei registri di temperatura e del piano di pulizia in cucina'], 'food', 'MENSUEL', 'DETECTIF', ['food-poisoning'], [HYG])
b.control('allergen-info', ['Vérification de l’information sur les allergènes (cartes, menus, personnel)', 'Check of allergen information (menus, labels, staff)', 'Prüfung der Allergeninformation (Karten, Menüs, Personal)', 'Verificación de la información sobre alérgenos (cartas, menús, personal)', 'Verifica dell’informazione sugli allergeni (menu, etichette, personale)'], 'food', 'TRIMESTRIEL', 'PREVENTIF', ['allergen-error'])
b.control('supplier-traceability', ['Contrôle par échantillon de la traçabilité des denrées reçues', 'Sample check of traceability of goods received', 'Stichprobenprüfung der Rückverfolgbarkeit angelieferter Lebensmittel', 'Control por muestreo de la trazabilidad de los alimentos recibidos', 'Controllo a campione della tracciabilità degli alimenti ricevuti'], 'food', 'MENSUEL', 'DETECTIF', ['food-poisoning'], [HYG])
b.control('fire-safety-checks', ['Suivi des contrôles de sécurité incendie et des exercices d’évacuation', 'Follow-up of fire-safety checks and evacuation drills', 'Nachverfolgung der Brandschutzprüfungen und Evakuierungsübungen', 'Seguimiento de las revisiones de seguridad contra incendios y de los simulacros de evacuación', 'Monitoraggio dei controlli antincendio e delle esercitazioni di evacuazione'], 'operations', 'TRIMESTRIEL', 'PREVENTIF', ['guest-safety'])
b.control('activity-safety', ['Vérification des équipements et encadrants des activités à risque', 'Check of equipment and supervisors of risky activities', 'Prüfung von Ausrüstung und Aufsichtspersonen bei Risikoaktivitäten', 'Verificación de los equipos y monitores de las actividades de riesgo', 'Verifica delle attrezzature e degli accompagnatori delle attività a rischio'], 'operations', 'TRIMESTRIEL', 'PREVENTIF', ['guest-safety'])
b.control('key-system-audit', ['Revue des droits et journaux du système de clés et d’accès', 'Review of rights and logs of the key and access system', 'Überprüfung von Rechten und Protokollen des Schlüssel- und Zutrittssystems', 'Revisión de los derechos y registros del sistema de llaves y acceso', 'Revisione dei diritti e dei log del sistema di chiavi e accessi'], 'operations', 'TRIMESTRIEL', 'DETECTIF', ['access-keys'])
b.control('provider-solvency', ['Suivi de la situation des prestataires et compagnies engagés sur les voyages vendus', 'Follow-up of providers and carriers committed to trips sold', 'Beobachtung der Lage von Leistungsträgern und Fluggesellschaften zu verkauften Reisen', 'Seguimiento de la situación de los proveedores y compañías comprometidos con los viajes vendidos', 'Monitoraggio della situazione di fornitori e vettori impegnati nei viaggi venduti'], 'travel-packages', 'TRIMESTRIEL', 'DETECTIF', ['partner-failure'])
b.control('financial-guarantee', ['Vérification de la garantie financière et de l’assurance de responsabilité de l’opérateur', 'Check of the operator’s financial guarantee and liability insurance', 'Prüfung der finanziellen Absicherung und Haftpflichtversicherung des Veranstalters', 'Verificación de la garantía financiera y del seguro de responsabilidad del operador', 'Verifica della garanzia finanziaria e dell’assicurazione di responsabilità dell’operatore'], 'travel-packages', 'ANNUEL', 'PREVENTIF', ['refund-liability'], [FORFAIT, TOURISME])
b.control('traveller-information', ['Contrôle par échantillon de l’information précontractuelle remise aux voyageurs', 'Sample check of pre-contract information given to travellers', 'Stichprobenprüfung der vorvertraglichen Informationen an Reisende', 'Control por muestreo de la información precontractual entregada a los viajeros', 'Controllo a campione delle informazioni precontrattuali fornite ai viaggiatori'], 'travel-packages', 'SEMESTRIEL', 'PREVENTIF', ['refund-liability'], [FORFAIT])
b.control('season-staffing', ['Revue du plan de recrutement et de formation du personnel saisonnier', 'Review of the seasonal staff recruitment and training plan', 'Überprüfung des Rekrutierungs- und Schulungsplans für Saisonpersonal', 'Revisión del plan de contratación y formación del personal estacional', 'Revisione del piano di assunzione e formazione del personale stagionale'], 'operations', 'ANNUEL', 'PREVENTIF', ['seasonal-staff'])

b.kri('chargeback-rate', ['Taux de litiges et rétrofacturations de paiements', 'Payment dispute and chargeback rate', 'Quote von Zahlungsstreitigkeiten und Rückbelastungen', 'Tasa de litigios y contracargos de pagos', 'Tasso di contenziosi e storni dei pagamenti'], 'payments', U_PCT, 'HAUSSE', 'MENSUEL')
b.kri('suspicious-bookings', ['Réservations signalées comme suspectes', 'Bookings flagged as suspicious', 'Als verdächtig gemeldete Buchungen', 'Reservas señaladas como sospechosas', 'Prenotazioni segnalate come sospette'], 'booking', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('overbookings', ['Clients relogés ou compensés pour surréservation', 'Guests relocated or compensated for overbooking', 'Wegen Überbuchung umquartierte oder entschädigte Gäste', 'Clientes reubicados o compensados por sobrerreserva', 'Ospiti ricollocati o risarciti per overbooking'], 'booking', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('system-downtime', ['Durée d’indisponibilité du système de réservation ou de gestion', 'Downtime of the booking or management system', 'Ausfallzeit des Buchungs- oder Verwaltungssystems', 'Tiempo de indisponibilidad del sistema de reservas o gestión', 'Tempo di indisponibilità del sistema di prenotazione o gestione'], 'booking', U_MIN, 'HAUSSE', 'MENSUEL')
b.kri('guest-complaints', ['Réclamations clients reçues', 'Guest complaints received', 'Eingegangene Gästebeschwerden', 'Reclamaciones de clientes recibidas', 'Reclami degli ospiti ricevuti'], 'guest', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('food-incidents', ['Incidents sanitaires ou allergènes signalés', 'Reported hygiene or allergen incidents', 'Gemeldete Hygiene- oder Allergenvorfälle', 'Incidentes sanitarios o de alérgenos notificados', 'Incidenti igienico-sanitari o di allergeni segnalati'], 'food', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('safety-checks-overdue', ['Contrôles de sécurité des sites échus', 'Overdue site safety checks', 'Überfällige Sicherheitsprüfungen der Standorte', 'Controles de seguridad de los sitios vencidos', 'Controlli di sicurezza dei siti scaduti'], 'operations', U_NB, 'HAUSSE', 'MENSUEL')
b.kri('trips-at-risk', ['Voyages vendus dépendant d’un prestataire jugé fragile', 'Trips sold relying on a provider judged fragile', 'Verkaufte Reisen mit Abhängigkeit von einem als fragil eingestuften Leistungsträger', 'Viajes vendidos que dependen de un proveedor considerado frágil', 'Viaggi venduti dipendenti da un fornitore ritenuto fragile'], 'travel-packages', U_NB, 'HAUSSE', 'TRIMESTRIEL')

b.audit('payment-security', ['Audit de la sécurité des paiements par carte', 'Audit of card-payment security', 'Audit der Sicherheit von Kartenzahlungen', 'Auditoría de la seguridad de los pagos con tarjeta', 'Audit della sicurezza dei pagamenti con carta'], 'payments', ['card-data', 'booking-fraud'], [
  ['Le périmètre de données de cartes est cartographié et réduit', 'The cardholder-data scope is mapped and reduced', 'Der Umfang der Kartendaten ist erfasst und reduziert', 'El perímetro de datos de tarjetas está cartografiado y reducido', 'Il perimetro dei dati delle carte è mappato e ridotto'],
  ['Les terminaux et applications de paiement sont inventoriés et contrôlés', 'Payment terminals and applications are inventoried and checked', 'Zahlungsterminals und -anwendungen sind inventarisiert und geprüft', 'Los terminales y aplicaciones de pago están inventariados y controlados', 'I terminali e le applicazioni di pagamento sono inventariati e controllati'],
  ['Les prestataires de paiement attestent de leur conformité', 'Payment providers attest to their compliance', 'Zahlungsdienstleister bestätigen ihre Konformität', 'Los proveedores de pago acreditan su conformidad', 'I fornitori di pagamento attestano la propria conformità'],
  ['Les fraudes et litiges sont analysés et traités', 'Fraud and disputes are analysed and handled', 'Betrug und Streitfälle werden analysiert und bearbeitet', 'Los fraudes y litigios se analizan y tratan', 'Le frodi e i contenziosi sono analizzati e trattati'],
])
b.audit('booking-continuity', ['Audit de la continuité des réservations et de l’accueil', 'Audit of booking and reception continuity', 'Audit der Kontinuität von Buchung und Empfang', 'Auditoría de la continuidad de reservas y recepción', 'Audit della continuità di prenotazioni e accoglienza'], 'booking', ['pms-outage', 'overbooking'], [
  ['Les systèmes critiques de réservation et de gestion sont identifiés avec leurs secours', 'Critical booking and management systems are identified with backups', 'Kritische Buchungs- und Verwaltungssysteme sind mit Ersatzlösungen identifiziert', 'Los sistemas críticos de reserva y gestión están identificados con sus respaldos', 'I sistemi critici di prenotazione e gestione sono identificati con i relativi backup'],
  ['Un mode dégradé papier ou autonome est prévu et connu du personnel', 'A paper or standalone fallback exists and is known to staff', 'Ein Papier- oder Standalone-Notbetrieb ist vorgesehen und dem Personal bekannt', 'Existe un modo degradado en papel o autónomo conocido por el personal', 'È previsto un modo degradato cartaceo o autonomo noto al personale'],
  ['La synchronisation des canaux est contrôlée', 'Channel synchronisation is checked', 'Die Kanalsynchronisierung wird kontrolliert', 'La sincronización de canales se controla', 'La sincronizzazione dei canali è controllata'],
  ['Les sauvegardes sont testées', 'Backups are tested', 'Sicherungen werden getestet', 'Las copias de seguridad se prueban', 'I backup sono testati'],
])
b.audit('food-hygiene', ['Audit de l’hygiène et de la sécurité alimentaire', 'Audit of hygiene and food safety', 'Audit von Hygiene und Lebensmittelsicherheit', 'Auditoría de la higiene y seguridad alimentaria', 'Audit di igiene e sicurezza alimentare'], 'food', ['food-poisoning', 'allergen-error'], [
  ['Un plan de maîtrise sanitaire est appliqué et enregistré', 'A food-safety control plan is applied and recorded', 'Ein Hygienekonzept wird angewendet und dokumentiert', 'Se aplica y registra un plan de control sanitario', 'Un piano di controllo sanitario è applicato e registrato'],
  ['Les allergènes sont identifiés et l’information est fiable', 'Allergens are identified and information is reliable', 'Allergene sind identifiziert und die Information ist verlässlich', 'Los alérgenos están identificados y la información es fiable', 'Gli allergeni sono identificati e l’informazione è affidabile'],
  ['La traçabilité des denrées est assurée', 'Food traceability is ensured', 'Die Rückverfolgbarkeit der Lebensmittel ist gewährleistet', 'La trazabilidad de los alimentos está asegurada', 'La tracciabilità degli alimenti è assicurata'],
  ['Le personnel est formé aux règles d’hygiène', 'Staff are trained in hygiene rules', 'Das Personal ist in Hygieneregeln geschult', 'El personal está formado en las normas de higiene', 'Il personale è formato sulle regole di igiene'],
])
b.audit('traveller-protection', ['Audit de la protection des voyageurs et des prestataires', 'Audit of traveller protection and provider management', 'Audit des Reiseschutzes und der Leistungsträgersteuerung', 'Auditoría de la protección de los viajeros y de la gestión de proveedores', 'Audit della tutela dei viaggiatori e della gestione dei fornitori'], 'travel-packages', ['partner-failure', 'refund-liability'], [
  ['Les garanties financières et assurances exigées sont en vigueur', 'Required financial guarantees and insurance are in force', 'Die erforderlichen finanziellen Garantien und Versicherungen bestehen', 'Las garantías financieras y seguros exigidos están en vigor', 'Le garanzie finanziarie e le assicurazioni richieste sono in vigore'],
  ['Les prestataires critiques sont évalués et surveillés', 'Critical providers are assessed and monitored', 'Kritische Leistungsträger werden bewertet und überwacht', 'Los proveedores críticos se evalúan y supervisan', 'I fornitori critici sono valutati e monitorati'],
  ['L’information précontractuelle des voyageurs est complète', 'Pre-contract information to travellers is complete', 'Die vorvertraglichen Informationen an Reisende sind vollständig', 'La información precontractual a los viajeros es completa', 'Le informazioni precontrattuali ai viaggiatori sono complete'],
  ['Un dispositif d’assistance et de rapatriement est prévu', 'An assistance and repatriation arrangement is in place', 'Eine Unterstützungs- und Rückholregelung ist vorgesehen', 'Existe un dispositivo de asistencia y repatriación', 'È previsto un dispositivo di assistenza e rimpatrio'],
])

export const TOURISME_PACK = b.pack
