// ─── Historique du catalogue sectoriel : ce qui a été ajouté à chaque version ──────────────────────────────────────────────
// Sert à signaler « nouveautés depuis la version que vous avez importée » : on n'écrase rien, on propose seulement.
// Règle : toute évolution du catalogue (CATALOGUE_PACK_VERSION) ajoute UNE entrée ici avec les clés ajoutées (un test le vérifie).

import { EXT_ITEMS } from './sector-packs-ext'
import { MUTUELLE_PACK } from './sector-packs-mutuelle'
import { MUTUELLE_SANTE_PACK, SANTE_EXT_PACK, TECHNIQUE_PACK, TECHNIQUE_V113_PACK, SANTE_V113_PACK } from './sector-packs-sante-technique'

const MUTUELLE_KEYS = new Set(MUTUELLE_PACK.items.map(item => item.key))
const V112_KEYS = new Set([SANTE_EXT_PACK, MUTUELLE_SANTE_PACK, TECHNIQUE_PACK].flatMap(p => p.items.map(item => item.key)))
const V113_KEYS = new Set([TECHNIQUE_V113_PACK, SANTE_V113_PACK].flatMap(p => p.items.map(item => item.key)))

export const CATALOGUE_CHANGELOG: { version: string; added: string[] }[] = [
  { version: '1.1', added: [
      'assurance.risk.customer-data',
      'assurance.risk.reserve',
      'commerce.risk.loyalty',
      'commerce.risk.pricing',
      'core.process.buy.order',
      'core.process.buy.review',
      'core.process.buy.sourcing',
      'core.process.deliver.aftersales',
      'core.process.deliver.orders',
      'core.process.digital.backup',
      'core.process.digital.iam',
      'core.process.digital.monitor',
      'core.process.digital.patch',
      'core.process.finance.accounting',
      'core.process.finance.payments',
      'core.process.finance.treasury',
      'core.process.govern.compliance',
      'core.process.govern.crisis',
      'core.process.govern.strategy',
      'core.process.people.hiring',
      'core.process.people.payroll',
      'core.process.people.skills',
      'core.risk.backup-failure',
      'core.risk.detection-gap',
      'core.risk.leavers',
      'core.risk.privileged-access',
      'core.risk.supplier-contract',
      'core.risk.unpatched',
      'finance.risk.card-data',
      'finance.risk.sanction-screening',
      'industrie.risk.remote-maintenance',
      'industrie.risk.safety',
      'public.risk.open-data',
      'public.risk.stale-data',
      'saas.risk.secrets',
      'saas.risk.tenant-restore',
      'sante.risk.consent',
      'sante.risk.device',
      'services.risk.client-access',
      'services.risk.subcontractor',
    ] },
  { version: '1.2', added: [
      'core.control.access-review',
      'core.control.backup-restore',
      'core.control.leavers',
      'core.control.patch-follow-up',
      'core.control.payment-validation',
      'core.control.privileged-review',
      'core.control.security-alerts',
      'core.control.supplier-clauses',
      'core.control.supplier-review',
    ] },
  { version: '1.3', added: [
      'core.kri.backup-success',
      'core.kri.leaver-accounts',
      'core.kri.overdue-patches',
      'core.kri.payment-exceptions',
      'core.kri.phishing-click',
      'core.kri.privileged-accounts',
      'core.kri.restore-age',
      'core.kri.security-incidents',
      'core.kri.supplier-without-clauses',
    ] },
  { version: '1.4', added: [
      'core.audit.access',
      'core.audit.backup',
      'core.audit.payments',
      'core.audit.suppliers',
    ] },
  { version: '1.5', added: [
      'assurance.audit.claims',
      'assurance.control.claims-sample',
      'assurance.control.pricing-change',
      'assurance.kri.broker-data-rejects',
      'assurance.kri.claims-backlog',
      'commerce.audit.online-sales',
      'commerce.control.inventory-count',
      'commerce.control.price-changes',
      'commerce.kri.checkout-downtime',
      'commerce.kri.stock-gaps',
      'finance.audit.payment-chain',
      'finance.control.reconciliation',
      'finance.control.sanctions-alerts',
      'finance.kri.channel-availability',
      'finance.kri.reconciliation-breaks',
      'industrie.audit.ot',
      'industrie.control.batch-release',
      'industrie.control.remote-access',
      'industrie.kri.unplanned-stops',
      'industrie.kri.unsupported-ot',
      'public.audit.grants',
      'public.control.grant-sample',
      'public.control.open-data-review',
      'public.kri.grant-corrections',
      'public.kri.portal-availability',
      'saas.audit.change',
      'saas.control.release-review',
      'saas.control.support-access',
      'saas.kri.failed-changes',
      'saas.kri.platform-availability',
      'sante.audit.records',
      'sante.control.record-access',
      'sante.control.specimen-identity',
      'sante.kri.care-downtime',
      'sante.kri.stockouts',
      'services.audit.confidentiality',
      'services.control.engagement-acceptance',
      'services.control.unbilled-work',
      'services.kri.missed-deadlines',
      'services.kri.unbilled-age',
    ] },
  { version: '1.6', added: [
      'assurance.resilience.broker-interface',
      'assurance.resilience.claims-continuity',
      'core.resilience.network-segmentation',
      'core.resilience.pentest',
      'core.resilience.physical-review',
      'core.resilience.ransomware-restore',
      'core.resilience.source-code',
      'core.resilience.supplier-failure',
      'core.resilience.vulnerability-scan',
      'finance.resilience.channel-load',
      'finance.resilience.payment-end-to-end',
    ] },
  { version: '1.7', added: [
      'energie.audit.operations',
      'energie.control.field-permits',
      'energie.control.ot-access',
      'energie.kri.interruption-duration',
      'energie.kri.overdue-ot-patches',
      'energie.process.dispatch',
      'energie.process.field',
      'energie.process.metering',
      'energie.process.operate',
      'energie.risk.contractor-access',
      'energie.risk.customer-data',
      'energie.risk.field-safety',
      'energie.risk.imbalance',
      'energie.risk.metering-error',
      'energie.risk.outage',
      'energie.risk.scada',
      'telecom.audit.network-change',
      'telecom.control.revenue-assurance',
      'telecom.control.sim-swap',
      'telecom.kri.failed-changes',
      'telecom.kri.network-availability',
      'telecom.process.billing',
      'telecom.process.lawful',
      'telecom.process.network',
      'telecom.process.provision',
      'telecom.risk.billing-error',
      'telecom.risk.config-change',
      'telecom.risk.outage',
      'telecom.risk.request-error',
      'telecom.risk.revenue-leak',
      'telecom.risk.sim-swap',
      'telecom.risk.traffic-data',
      'transport.audit.continuity',
      'transport.control.cycle-count',
      'transport.control.maintenance-due',
      'transport.kri.on-time',
      'transport.kri.overdue-maintenance',
      'transport.process.fleet',
      'transport.process.move',
      'transport.process.plan',
      'transport.process.warehouse',
      'transport.risk.accident',
      'transport.risk.cargo-theft',
      'transport.risk.delay',
      'transport.risk.maintenance',
      'transport.risk.planning-outage',
      'transport.risk.stock-error',
      'transport.risk.telematics',
    ] },
  { version: '1.8', added: [
      'core.risk.continuity-plan',
      'core.risk.financial-reporting',
      'core.risk.internal-fraud',
      'core.risk.it-outage',
      'core.risk.mis-selling',
      'core.risk.obligation-missed',
      'core.risk.personal-data',
      'core.risk.premises',
      'core.risk.segregation',
      'core.risk.workplace',
      'finance.risk.aml',
    ] },
  { version: '1.9', added: [
      'finance.process.governance',
      'finance.process.markets',
      'finance.process.aml',
      'finance.process.compliance',
      'finance.process.reporting',
      'finance.process.ict',
      'finance.control.control-plan',
      'finance.control.delegations',
      'finance.control.incident-escalation',
      'finance.control.credit-sample',
      'finance.control.credit-limits',
      'finance.control.default-classification',
      'finance.control.collateral-valuation',
      'finance.control.market-limits',
      'finance.control.valuation-check',
      'finance.control.liquidity-ratios',
      'finance.control.payment-four-eyes',
      'finance.control.fraud-monitoring',
      'finance.control.strong-authentication',
      'finance.control.kyc-sample',
      'finance.control.aml-alerts',
      'finance.control.str-quality',
      'finance.control.asset-freeze',
      'finance.control.suitability',
      'finance.control.complaints',
      'finance.control.marketing-review',
      'finance.control.regulatory-reporting',
      'finance.control.suspense-accounts',
      'finance.control.ict-register',
      'finance.control.critical-providers',
      'finance.control.resilience-testing',
      'finance.control.incident-reporting-drill',
      'assurance.process.governance',
      'assurance.process.orsa',
      'assurance.process.reserving',
      'assurance.process.investments',
      'assurance.process.aml',
      'assurance.process.members',
      'assurance.process.ict',
      'assurance.control.key-functions',
      'assurance.control.policies-review',
      'assurance.control.fit-proper',
      'assurance.control.governance-escalation',
      'assurance.control.orsa-process',
      'assurance.control.solvency-coverage',
      'assurance.control.risk-appetite',
      'assurance.control.underwriting-delegations',
      'assurance.control.new-business-sample',
      'assurance.control.reserve-backtesting',
      'assurance.control.actuarial-data-quality',
      'assurance.control.claims-delays',
      'assurance.control.claims-segregation',
      'assurance.control.delegated-managers',
      'assurance.control.advice-sample',
      'assurance.control.intermediaries',
      'assurance.control.product-governance',
      'assurance.control.complaints',
      'assurance.control.investment-limits',
      'assurance.control.reinsurance',
      'assurance.control.aml-life',
      'assurance.control.asset-freeze',
      'assurance.control.member-contributions',
      'assurance.control.statutes-assembly',
      'assurance.control.benefits-sample',
      'assurance.control.ict-register',
      'assurance.control.critical-providers',
      'assurance.control.resilience-testing',
      'assurance.control.incident-reporting-drill',
    ] },
  // 1.10 : contenu sectoriel étendu (7 nouveaux secteurs + approfondissement des autres) — clés issues des packs `sector-packs-ext*`.
  { version: '1.10', added: EXT_ITEMS.map(item => item.key).filter(k => !MUTUELLE_KEYS.has(k) && !V112_KEYS.has(k) && !V113_KEYS.has(k)).sort() },
  // 1.11 : contrôles de mutuelle santé manquants (LCB-FT, données de santé, continuité) pour le plan de contrôle type.
  { version: '1.11', added: [...MUTUELLE_KEYS].sort() },
  // 1.12 : santé (portail, entrepôt de données, flux reçus), mutuelle santé (IBAN, délégation, tiers payant), secteur Technique / Interconnexion de SI.
  { version: '1.12', added: [...V112_KEYS].sort() },
  // 1.13 : analyseurs de fichiers et validation des entrées, pièces jointes de la messagerie d'un portail, continuité d'une plateforme de santé.
  { version: '1.13', added: [...V113_KEYS].sort() },
]

const parts = (v: string) => v.split('.').map(n => Number.parseInt(n, 10) || 0)
/** -1 | 0 | 1 selon l'ordre numérique des versions « majeure.mineure ». */
export function compareCatalogueVersions(a: string, b: string): number {
  const [am, an] = parts(a), [bm, bn] = parts(b)
  return am !== bm ? Math.sign(am - bm) : Math.sign((an ?? 0) - (bn ?? 0))
}

/** Plus petite version déjà importée par l'organisation (référence de comparaison) ; null si rien n'a été importé. */
export function oldestImportedVersion(versions: readonly (string | null | undefined)[]): string | null {
  const valid = versions.filter((v): v is string => typeof v === 'string' && /^\d+\.\d+$/.test(v))
  return valid.length ? valid.reduce((min, v) => (compareCatalogueVersions(v, min) < 0 ? v : min)) : null
}

/** Clés ajoutées APRÈS la version de référence et pas encore importées : des propositions, jamais des modifications de l'existant. */
export function newSince(since: string | null, existingKeys: readonly string[]): string[] {
  if (!since) return []
  const have = new Set(existingKeys)
  return CATALOGUE_CHANGELOG.filter(entry => compareCatalogueVersions(entry.version, since) > 0).flatMap(entry => entry.added).filter(key => !have.has(key))
}
