// ─── Historique du catalogue sectoriel : ce qui a été ajouté à chaque version ──────────────────────────────────────────────
// Sert à signaler « nouveautés depuis la version que vous avez importée » : on n'écrase rien, on propose seulement.
// Règle : toute évolution du catalogue (CATALOGUE_PACK_VERSION) ajoute UNE entrée ici avec les clés ajoutées (un test le vérifie).

export const CATALOGUE_CHANGELOG: { version: string; added: string[] }[] = [
  { version: '1.1', added: [
      'assurance.risk.customer-data',
      'assurance.risk.reserve',
      'commerce.risk.loyalty',
      'commerce.risk.pricing',
      'core.process.buy.order',
      'core.process.buy.review',
      'core.process.buy.sourcing',
      'core.process.deliver.aftersales',
      'core.process.deliver.orders',
      'core.process.digital.backup',
      'core.process.digital.iam',
      'core.process.digital.monitor',
      'core.process.digital.patch',
      'core.process.finance.accounting',
      'core.process.finance.payments',
      'core.process.finance.treasury',
      'core.process.govern.compliance',
      'core.process.govern.crisis',
      'core.process.govern.strategy',
      'core.process.people.hiring',
      'core.process.people.payroll',
      'core.process.people.skills',
      'core.risk.backup-failure',
      'core.risk.detection-gap',
      'core.risk.leavers',
      'core.risk.privileged-access',
      'core.risk.supplier-contract',
      'core.risk.unpatched',
      'finance.risk.card-data',
      'finance.risk.sanction-screening',
      'industrie.risk.remote-maintenance',
      'industrie.risk.safety',
      'public.risk.open-data',
      'public.risk.stale-data',
      'saas.risk.secrets',
      'saas.risk.tenant-restore',
      'sante.risk.consent',
      'sante.risk.device',
      'services.risk.client-access',
      'services.risk.subcontractor',
    ] },
  { version: '1.2', added: [
      'core.control.access-review',
      'core.control.backup-restore',
      'core.control.leavers',
      'core.control.patch-follow-up',
      'core.control.payment-validation',
      'core.control.privileged-review',
      'core.control.security-alerts',
      'core.control.supplier-clauses',
      'core.control.supplier-review',
    ] },
  { version: '1.3', added: [
      'core.kri.backup-success',
      'core.kri.leaver-accounts',
      'core.kri.overdue-patches',
      'core.kri.payment-exceptions',
      'core.kri.phishing-click',
      'core.kri.privileged-accounts',
      'core.kri.restore-age',
      'core.kri.security-incidents',
      'core.kri.supplier-without-clauses',
    ] },
  { version: '1.4', added: [
      'core.audit.access',
      'core.audit.backup',
      'core.audit.payments',
      'core.audit.suppliers',
    ] },
  { version: '1.5', added: [
      'assurance.audit.claims',
      'assurance.control.claims-sample',
      'assurance.control.pricing-change',
      'assurance.kri.broker-data-rejects',
      'assurance.kri.claims-backlog',
      'commerce.audit.online-sales',
      'commerce.control.inventory-count',
      'commerce.control.price-changes',
      'commerce.kri.checkout-downtime',
      'commerce.kri.stock-gaps',
      'finance.audit.payment-chain',
      'finance.control.reconciliation',
      'finance.control.sanctions-alerts',
      'finance.kri.channel-availability',
      'finance.kri.reconciliation-breaks',
      'industrie.audit.ot',
      'industrie.control.batch-release',
      'industrie.control.remote-access',
      'industrie.kri.unplanned-stops',
      'industrie.kri.unsupported-ot',
      'public.audit.grants',
      'public.control.grant-sample',
      'public.control.open-data-review',
      'public.kri.grant-corrections',
      'public.kri.portal-availability',
      'saas.audit.change',
      'saas.control.release-review',
      'saas.control.support-access',
      'saas.kri.failed-changes',
      'saas.kri.platform-availability',
      'sante.audit.records',
      'sante.control.record-access',
      'sante.control.specimen-identity',
      'sante.kri.care-downtime',
      'sante.kri.stockouts',
      'services.audit.confidentiality',
      'services.control.engagement-acceptance',
      'services.control.unbilled-work',
      'services.kri.missed-deadlines',
      'services.kri.unbilled-age',
    ] },
  { version: '1.6', added: [
      'assurance.resilience.broker-interface',
      'assurance.resilience.claims-continuity',
      'core.resilience.network-segmentation',
      'core.resilience.pentest',
      'core.resilience.physical-review',
      'core.resilience.ransomware-restore',
      'core.resilience.source-code',
      'core.resilience.supplier-failure',
      'core.resilience.vulnerability-scan',
      'finance.resilience.channel-load',
      'finance.resilience.payment-end-to-end',
    ] },
  { version: '1.7', added: [
      'energie.audit.operations',
      'energie.control.field-permits',
      'energie.control.ot-access',
      'energie.kri.interruption-duration',
      'energie.kri.overdue-ot-patches',
      'energie.process.dispatch',
      'energie.process.field',
      'energie.process.metering',
      'energie.process.operate',
      'energie.risk.contractor-access',
      'energie.risk.customer-data',
      'energie.risk.field-safety',
      'energie.risk.imbalance',
      'energie.risk.metering-error',
      'energie.risk.outage',
      'energie.risk.scada',
      'telecom.audit.network-change',
      'telecom.control.revenue-assurance',
      'telecom.control.sim-swap',
      'telecom.kri.failed-changes',
      'telecom.kri.network-availability',
      'telecom.process.billing',
      'telecom.process.lawful',
      'telecom.process.network',
      'telecom.process.provision',
      'telecom.risk.billing-error',
      'telecom.risk.config-change',
      'telecom.risk.outage',
      'telecom.risk.request-error',
      'telecom.risk.revenue-leak',
      'telecom.risk.sim-swap',
      'telecom.risk.traffic-data',
      'transport.audit.continuity',
      'transport.control.cycle-count',
      'transport.control.maintenance-due',
      'transport.kri.on-time',
      'transport.kri.overdue-maintenance',
      'transport.process.fleet',
      'transport.process.move',
      'transport.process.plan',
      'transport.process.warehouse',
      'transport.risk.accident',
      'transport.risk.cargo-theft',
      'transport.risk.delay',
      'transport.risk.maintenance',
      'transport.risk.planning-outage',
      'transport.risk.stock-error',
      'transport.risk.telematics',
    ] },
]

const parts = (v: string) => v.split('.').map(n => Number.parseInt(n, 10) || 0)
/** -1 | 0 | 1 selon l'ordre numérique des versions « majeure.mineure ». */
export function compareCatalogueVersions(a: string, b: string): number {
  const [am, an] = parts(a), [bm, bn] = parts(b)
  return am !== bm ? Math.sign(am - bm) : Math.sign((an ?? 0) - (bn ?? 0))
}

/** Plus petite version déjà importée par l'organisation (référence de comparaison) ; null si rien n'a été importé. */
export function oldestImportedVersion(versions: readonly (string | null | undefined)[]): string | null {
  const valid = versions.filter((v): v is string => typeof v === 'string' && /^\d+\.\d+$/.test(v))
  return valid.length ? valid.reduce((min, v) => (compareCatalogueVersions(v, min) < 0 ? v : min)) : null
}

/** Clés ajoutées APRÈS la version de référence et pas encore importées : des propositions, jamais des modifications de l'existant. */
export function newSince(since: string | null, existingKeys: readonly string[]): string[] {
  if (!since) return []
  const have = new Set(existingKeys)
  return CATALOGUE_CHANGELOG.filter(entry => compareCatalogueVersions(entry.version, since) > 0).flatMap(entry => entry.added).filter(key => !have.has(key))
}
