-- AlterTable
ALTER TABLE "PartiePrenante" DROP COLUMN "vulnerabilite",
ADD COLUMN     "confiance" DOUBLE PRECISION NOT NULL DEFAULT 3,
ADD COLUMN     "dependance" DOUBLE PRECISION NOT NULL DEFAULT 2,
ADD COLUMN     "maturite" DOUBLE PRECISION NOT NULL DEFAULT 3,
ADD COLUMN     "penetration" DOUBLE PRECISION NOT NULL DEFAULT 2,
ALTER COLUMN "exposition" SET DEFAULT 4,
ALTER COLUMN "exposition" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fiabilite" SET DEFAULT 9,
ALTER COLUMN "fiabilite" SET DATA TYPE DOUBLE PRECISION;

